import Mathlib
import JanusFormal.Branches.FundamentalGeometryD11NaturalImmersionOperators.Gates.P0EFTJanusCanonicalImmersionSymbolFamily
import JanusFormal.Branches.FundamentalGeometryD11NaturalImmersionOperators.Gates.P0EFTJanusNaturalLowerOrderFreedom

namespace JanusFormal
namespace P0EFTJanusNaturalOperatorBlueprint

set_option autoImplicit false

open P0EFTJanusCanonicalImmersionSymbolFamily
open P0EFTJanusNaturalLowerOrderFreedom

/-- Sectors generated by an immersed SpinC configuration after gauge fixing. -/
inductive NaturalOperatorSector where
  | normalJacobi
  | maxwellOneForm
  | metricLichnerowicz
  | squaredTwistedDirac
  | u1Ghost
  | diffeomorphismGhost
  deriving DecidableEq, Repr

/-- Differential order of the displayed Laplace-type sector. -/
def sectorDifferentialOrder : NaturalOperatorSector → ℕ
  | NaturalOperatorSector.normalJacobi => 2
  | NaturalOperatorSector.maxwellOneForm => 2
  | NaturalOperatorSector.metricLichnerowicz => 2
  | NaturalOperatorSector.squaredTwistedDirac => 2
  | NaturalOperatorSector.u1Ghost => 2
  | NaturalOperatorSector.diffeomorphismGhost => 2

/-- Real local fiber rank of each displayed sector. -/
def sectorRealRank : NaturalOperatorSector → ℕ
  | NaturalOperatorSector.normalJacobi => 1
  | NaturalOperatorSector.maxwellOneForm => 3
  | NaturalOperatorSector.metricLichnerowicz => 6
  | NaturalOperatorSector.squaredTwistedDirac => 4
  | NaturalOperatorSector.u1Ghost => 1
  | NaturalOperatorSector.diffeomorphismGhost => 3

/-- Statistics/parity used in the one-loop superdeterminant. -/
inductive SectorParity where
  | even
  | odd
  deriving DecidableEq, Repr

/-- Bosonic fields are even; Faddeev--Popov ghosts are odd. -/
def sectorParity : NaturalOperatorSector → SectorParity
  | NaturalOperatorSector.normalJacobi => SectorParity.even
  | NaturalOperatorSector.maxwellOneForm => SectorParity.even
  | NaturalOperatorSector.metricLichnerowicz => SectorParity.even
  | NaturalOperatorSector.squaredTwistedDirac => SectorParity.odd
  | NaturalOperatorSector.u1Ghost => SectorParity.odd
  | NaturalOperatorSector.diffeomorphismGhost => SectorParity.odd

/-- Natural geometric origin of each sector. -/
inductive SectorOrigin where
  | normalImmersion
  | gaugeConnection
  | tangentMetric
  | spinCCliffordModule
  | u1GaugeSymmetry
  | diffeomorphismSymmetry
  deriving DecidableEq, Repr

/-- Origin map. -/
def sectorOrigin : NaturalOperatorSector → SectorOrigin
  | NaturalOperatorSector.normalJacobi => SectorOrigin.normalImmersion
  | NaturalOperatorSector.maxwellOneForm => SectorOrigin.gaugeConnection
  | NaturalOperatorSector.metricLichnerowicz => SectorOrigin.tangentMetric
  | NaturalOperatorSector.squaredTwistedDirac =>
      SectorOrigin.spinCCliffordModule
  | NaturalOperatorSector.u1Ghost => SectorOrigin.u1GaugeSymmetry
  | NaturalOperatorSector.diffeomorphismGhost =>
      SectorOrigin.diffeomorphismSymmetry

/-- All sectors are second-order after squaring the Dirac block. -/
theorem every_blueprint_sector_is_second_order
    (sector : NaturalOperatorSector) :
    sectorDifferentialOrder sector = 2 := by
  cases sector <;> rfl

/-- Sum of displayed local real ranks. -/
theorem displayed_sector_rank_sum :
    sectorRealRank NaturalOperatorSector.normalJacobi +
      sectorRealRank NaturalOperatorSector.maxwellOneForm +
      sectorRealRank NaturalOperatorSector.metricLichnerowicz +
      sectorRealRank NaturalOperatorSector.squaredTwistedDirac +
      sectorRealRank NaturalOperatorSector.u1Ghost +
      sectorRealRank NaturalOperatorSector.diffeomorphismGhost = 18 := by
  norm_num [sectorRealRank]

/-- Metric block has the canonical `1+5` trace/traceless fiber split. -/
theorem metric_sector_trace_traceless_rank :
    sectorRealRank NaturalOperatorSector.metricLichnerowicz = 1 + 5 := by
  norm_num [sectorRealRank]

/-- Formal signed real-rank contribution of one sector. -/
def signedSectorRank (sector : NaturalOperatorSector) : ℤ :=
  match sectorParity sector with
  | SectorParity.even => sectorRealRank sector
  | SectorParity.odd => -(sectorRealRank sector : ℤ)

/-- Raw signed rank is not the physical determinant exponent. -/
theorem raw_signed_rank_value :
    signedSectorRank NaturalOperatorSector.normalJacobi +
      signedSectorRank NaturalOperatorSector.maxwellOneForm +
      signedSectorRank NaturalOperatorSector.metricLichnerowicz +
      signedSectorRank NaturalOperatorSector.squaredTwistedDirac +
      signedSectorRank NaturalOperatorSector.u1Ghost +
      signedSectorRank NaturalOperatorSector.diffeomorphismGhost = 2 := by
  norm_num [signedSectorRank, sectorParity, sectorRealRank]

/-- Lower-order data attached to each sector. -/
structure SectorLowerOrderData where
  massSquared : ℝ
  scalarCurvatureCoupling : ℝ
  extrinsicCurvatureCoupling : ℝ
  gaugeCurvatureCoupling : ℝ
  normalPotentialCoupling : ℝ

/-- Full natural operator blueprint. -/
structure NaturalOperatorBlueprint where
  lowerOrder : NaturalOperatorSector → SectorLowerOrderData
  boundaryDomainDerived : NaturalOperatorSector → Prop
  selfAdjointDomainDerived : NaturalOperatorSector → Prop
  globalFredholmPropertyDerived : NaturalOperatorSector → Prop
  principalSymbolCanonical : Prop

/-- Two blueprints can share canonical symbols while differing in lower order data. -/
def zeroLowerOrderData : SectorLowerOrderData :=
  { massSquared := 0
    scalarCurvatureCoupling := 0
    extrinsicCurvatureCoupling := 0
    gaugeCurvatureCoupling := 0
    normalPotentialCoupling := 0 }

/-- Unit mass in only the normal sector. -/
def normalMassLowerOrderData
    (sector : NaturalOperatorSector) : SectorLowerOrderData :=
  match sector with
  | NaturalOperatorSector.normalJacobi =>
      { massSquared := 1
        scalarCurvatureCoupling := 0
        extrinsicCurvatureCoupling := 0
        gaugeCurvatureCoupling := 0
        normalPotentialCoupling := 0 }
  | _ => zeroLowerOrderData

/-- Explicit lower-order nonuniqueness within the same sector blueprint. -/
theorem canonical_sector_list_does_not_fix_normal_mass :
    (zeroLowerOrderData.massSquared : ℝ) ≠
      (normalMassLowerOrderData
        NaturalOperatorSector.normalJacobi).massSquared := by
  norm_num [zeroLowerOrderData, normalMassLowerOrderData]

/--
The blueprint identifies the natural sectors, their leading differential order,
ranks and geometric origins.  It still does not determine the complete BRST
superdeterminant: reality conditions, powers `1/2`, complex versus real ghosts,
zero modes and Jacobians must be derived from the chosen action and measure.
-/
structure NaturalOperatorBlueprintPhysicalStatus where
  normalJacobiSectorDerived : Prop
  maxwellSectorDerived : Prop
  metricLichnerowiczSectorDerived : Prop
  twistedDiracSectorDerived : Prop
  u1GhostSectorDerived : Prop
  diffeomorphismGhostSectorDerived : Prop
  allPrincipalSymbolsMatched : Prop
  allLowerOrderTermsDerived : Prop
  domainsAndBoundaryConditionsDerived : Prop
  determinantPowersDerived : Prop
  zeroModesSeparated : Prop


def naturalOperatorBlueprintPhysicalClosure
    (s : NaturalOperatorBlueprintPhysicalStatus) : Prop :=
  s.normalJacobiSectorDerived /\
  s.maxwellSectorDerived /\
  s.metricLichnerowiczSectorDerived /\
  s.twistedDiracSectorDerived /\
  s.u1GhostSectorDerived /\
  s.diffeomorphismGhostSectorDerived /\
  s.allPrincipalSymbolsMatched /\
  s.allLowerOrderTermsDerived /\
  s.domainsAndBoundaryConditionsDerived /\
  s.determinantPowersDerived /\
  s.zeroModesSeparated

end P0EFTJanusNaturalOperatorBlueprint
end JanusFormal
