/- Active Janus facade.

`lake build JanusFormal` should compile only the current active proof surface.
Historical/full import graph is preserved in `JanusFormal.AllImportsArchive`.
-/

import JanusFormal.Basic
import JanusFormal.P0EFTGlobalTopologyMasterLock
import JanusFormal.P0EFTJanusZ4AcousticPolarizationClosedTheta2JointGate
import JanusFormal.P0EFTJanusZ4PhotonPolarizationBoltzmannHierarchyClosureGate
import JanusFormal.P0EFTJanusZ4OfficialPlanckClosedBoltzmannAcousticPolarizationTrial
import JanusFormal.P0EFTJanusZ4PlanckLikelihoodCompletenessGate
import JanusFormal.P0EFTJanusZ4ClosedBoltzmannCandidateRobustnessGate
import JanusFormal.P0EFTJanusZ4StandaloneTEEEAcquisitionGate
import JanusFormal.P0EFTJanusZ4StandaloneTEEEHandshakeGate
import JanusFormal.P0EFTJanusZ4StandaloneTEEEGRReferenceHandshake
import JanusFormal.P0EFTJanusZ4ClosedBoltzmannCandidateHighLDecompositionTrial
import JanusFormal.P0EFTJanusZ4NonOverlappingLikelihoodAccountingGate
import JanusFormal.P0EFTJanusZ4HighLDecomposedCandidatePromotionGate
import JanusFormal.P0EFTJanusZ4CandidateNuisanceForegroundPolicyGate
import JanusFormal.P0EFTJanusZ4HighLResidualDiagnosticReport
import JanusFormal.P0EFTJanusZ4CandidateNuisanceSensitivityGate
import JanusFormal.P0EFTJanusZ4CandidateLocalNuisanceProfilingGate
import JanusFormal.P0EFTJanusZ4BoundarySafeNuisanceProfilingGate
import JanusFormal.P0EFTJanusZ4CandidateCosmologyParameterPolicyGate
import JanusFormal.P0EFTJanusZ4CandidateLocalCosmologyProfilingGate
