import Mathlib

namespace JanusFormal.P0EFTJanusMixedGaugeScalarLoopOrder

set_option autoImplicit false

/-!
Loop-counting gate for vacuum/background diagrams made from the expansion of
`phi^-2 F^2`. Every such vertex has exactly two gauge half-edges.
-/

structure DressedMaxwellVacuumGraph where
  vertices : ℕ
  gaugeInternalLines : ℕ
  scalarInternalLines : ℕ
  loops : ℕ
  superficialDegree : ℕ
  gaugeHalfEdgeCount : 2 * vertices = 2 * gaugeInternalLines
  connectedLoopCount : loops + vertices =
    gaugeInternalLines + scalarInternalLines + 1
  uvDegreeCount : superficialDegree + 2 * gaugeInternalLines +
    2 * scalarInternalLines = 3 * loops + 2 * vertices

/-- Gauge half-edge counting reduces the loop number to one plus the number of
internal scalar lines. -/
theorem loop_number_eq_scalar_lines_plus_one
    (g : DressedMaxwellVacuumGraph) :
    g.loops = g.scalarInternalLines + 1 := by
  have hGauge := g.gaugeHalfEdgeCount
  have hLoop := g.connectedLoopCount
  omega

/-- A genuinely mixed gauge-scalar graph has at least two loops. Therefore the
one-loop gauge determinant exhausts the sector with no scalar propagator. -/
theorem mixed_graph_starts_at_two_loops
    (g : DressedMaxwellVacuumGraph)
    (hMixed : 0 < g.scalarInternalLines) :
    2 ≤ g.loops := by
  rw [loop_number_eq_scalar_lines_plus_one g]
  omega

/-- The one-loop case contains no internal scalar line and belongs to the
isolated gauge determinant already audited separately. -/
theorem one_loop_is_pure_gauge_ring
    (g : DressedMaxwellVacuumGraph)
    (hOneLoop : g.loops = 1) :
    g.scalarInternalLines = 0 := by
  have h := loop_number_eq_scalar_lines_plus_one g
  omega

/-- With two derivatives per dressed-Maxwell vertex and UV propagators
`p^-2`, the superficial degree is `I_scalar + 3`. It is power divergent, so a
logarithm can only arise in a subleading mass/momentum term after local power
subtractions. -/
theorem mixed_superficial_degree
    (g : DressedMaxwellVacuumGraph) :
    g.superficialDegree = g.scalarInternalLines + 3 := by
  have hGauge := g.gaugeHalfEdgeCount
  have hLoop := g.connectedLoopCount
  have hDegree := g.uvDegreeCount
  omega

/-- The nonpolynomial dressed-Maxwell expansion allows a family with any
number of internal scalar lines. -/
def unboundedMixedFamily (scalarLines : ℕ) : DressedMaxwellVacuumGraph where
  vertices := 2
  gaugeInternalLines := 2
  scalarInternalLines := scalarLines
  loops := scalarLines + 1
  superficialDegree := scalarLines + 3
  gaugeHalfEdgeCount := by omega
  connectedLoopCount := by omega
  uvDegreeCount := by omega

/-- No finite superficial-degree bound closes all mixed graphs generated by
the inverse-scalar Maxwell coefficient. -/
theorem mixed_superficial_degree_unbounded (bound : ℕ) :
    ∃ g : DressedMaxwellVacuumGraph, bound < g.superficialDegree := by
  refine ⟨unboundedMixedFamily bound, ?_⟩
  simp [unboundedMixedFamily]

end JanusFormal.P0EFTJanusMixedGaugeScalarLoopOrder
