from __future__ import annotations

import unittest

from scripts.build_p0_interaction_tensor_research_program import build_payload


class P0InteractionTensorResearchProgramTests(unittest.TestCase):
    def test_research_program_is_active_but_not_predictive(self) -> None:
        payload = build_payload()
        status = payload["current_status"]

        self.assertEqual(payload["status"], "active-research-open")
        self.assertIn(
            "source-law obligation ledgers",
            {row["track"] for row in payload["research_tracks"]},
        )
        self.assertTrue(status["candidate_enumeration_started"])
        self.assertTrue(status["dl_formula_family_available"])
        self.assertTrue(status["f_constraint_equations_available"])
        self.assertTrue(status["f_decomposition_available"])
        self.assertTrue(status["fermi_walker_branch_available"])
        self.assertTrue(status["receiver_geodesic_transport_available"])
        self.assertTrue(status["perfect_fluid_constraints_available"])
        self.assertTrue(status["anisotropic_orientation_constraints_available"])
        self.assertTrue(status["branch_decision_matrix_available"])
        self.assertTrue(status["k_candidate_families_available"])
        self.assertTrue(status["closure_acceptance_criteria_available"])
        self.assertTrue(status["density_measure_closure_condition_available"])
        self.assertTrue(status["source_measure_convention_matrix_available"])
        self.assertTrue(status["source_measure_selection_rules_available"])
        self.assertTrue(status["source_measure_residual_substitution_available"])
        self.assertTrue(status["residual_zero_condition_matrix_available"])
        self.assertTrue(status["dl_dlogb_identity_targets_available"])
        self.assertTrue(status["dl_lorentz_generator_obstruction_available"])
        self.assertTrue(status["dlogb_4volume_obstruction_available"])
        self.assertTrue(status["m15_source_identity_implications_available"])
        self.assertTrue(status["source_gap_scan_results_available"])
        self.assertTrue(status["minimal_axiom_transport_solution_available"])
        self.assertTrue(status["m30_zero_divergence_pde_derivation_available"])
        self.assertTrue(status["zero_divergence_solver_plan_available"])
        self.assertTrue(status["flrw_zero_divergence_toy_solution_available"])
        self.assertTrue(status["noncomoving_dust_pde_constraints_available"])
        self.assertTrue(status["omega_transverse_gauge_audit_available"])
        self.assertTrue(status["pi_eigenframe_gauge_fix_branch_available"])
        self.assertTrue(status["l_boundary_initial_condition_branch_available"])
        self.assertTrue(status["gauge_lifting_decision_matrix_available"])
        self.assertTrue(status["gauge_source_scan_results_available"])
        self.assertTrue(status["flat_omega_connection_branch_available"])
        self.assertTrue(status["pure_gauge_solder_connection_branch_available"])
        self.assertTrue(status["pure_gauge_pde_consistency_check_available"])
        self.assertTrue(status["relative_holonomy_branch_available"])
        self.assertTrue(status["flat_vs_holonomy_decision_available"])
        self.assertTrue(status["lorentz_polar_projection_regular_branch_available"])
        self.assertTrue(status["holonomy_path_rule_branch_available"])
        self.assertTrue(status["polar_projection_derivative_obstruction_available"])
        self.assertTrue(status["holonomy_loop_consistency_criteria_available"])
        self.assertTrue(status["transport_branch_closure_obligations_available"])
        self.assertTrue(status["solution_route_selection_available"])
        self.assertTrue(status["variational_closure_route_available"])
        self.assertTrue(status["integrability_closure_route_available"])
        self.assertTrue(status["source_derived_route_attempt_available"])
        self.assertTrue(status["auxiliary_l_action_attempt_available"])
        self.assertTrue(status["innovative_axiom_acceptance_gate_available"])
        self.assertTrue(status["stueckelberg_two_diffeo_route_available"])
        self.assertTrue(status["stueckelberg_conditional_closure_theorem_available"])
        self.assertTrue(status["stueckelberg_explicit_action_test_available"])
        self.assertTrue(status["stueckelberg_minimal_phi_dust_test_available"])
        self.assertTrue(status["stueckelberg_mirror_phi_constraints_available"])
        self.assertTrue(status["stueckelberg_zero_param_progression_available"])
        self.assertTrue(status["stueckelberg_zero_param_dust_compatibility_available"])
        self.assertTrue(status["stueckelberg_zero_param_residual_substitution_available"])
        self.assertTrue(status["stueckelberg_dphi_density_cancellation_available"])
        self.assertTrue(status["stueckelberg_dl_velocity_cancellation_available"])
        self.assertTrue(status["stueckelberg_dlogb_volume_cancellation_available"])
        self.assertTrue(status["stueckelberg_remaining_connection_gate_available"])
        self.assertTrue(status["stueckelberg_connection_difference_cancellation_available"])
        self.assertTrue(status["stueckelberg_map_equation_connection_compatibility_available"])
        self.assertTrue(status["stueckelberg_dust_congruence_escape_route_available"])
        self.assertTrue(status["stueckelberg_map_constraint_counting_available"])
        self.assertTrue(status["stueckelberg_map_integrability_curl_conditions_available"])
        self.assertTrue(status["stueckelberg_isometry_branch_no_go_available"])
        self.assertTrue(status["stueckelberg_weak_congruence_map_equation_available"])
        self.assertTrue(status["stueckelberg_weak_congruence_variational_origin_available"])
        self.assertTrue(status["stueckelberg_dust_current_multiplier_identification_available"])
        self.assertTrue(status["stueckelberg_transverse_source_requirement_available"])
        self.assertTrue(status["stueckelberg_projected_dust_variation_identity_available"])
        self.assertTrue(status["stueckelberg_projected_perfect_fluid_extension_available"])
        self.assertTrue(status["stueckelberg_phi_l_convention_lock_available"])
        self.assertTrue(status["stueckelberg_dust_branch_conditional_closure_gate_available"])
        self.assertTrue(status["stueckelberg_dust_image_curl_reduction_available"])
        self.assertTrue(status["stueckelberg_transverse_label_caustic_gate_available"])
        self.assertTrue(status["stueckelberg_multistream_extension_gate_available"])
        self.assertTrue(status["stueckelberg_sheet_sum_dust_model_available"])
        self.assertTrue(status["stueckelberg_sheet_creation_conservation_gate_available"])
        self.assertTrue(status["stueckelberg_kinetic_moment_sheet_limit_available"])
        self.assertTrue(status["stueckelberg_sheet_optical_no_fit_gate_available"])
        self.assertTrue(status["stueckelberg_sheet_diagnostic_execution_gate_available"])
        self.assertTrue(status["stueckelberg_kinetic_transport_candidate_available"])
        self.assertTrue(status["stueckelberg_qcross_kinetic_projection_candidate_available"])
        self.assertTrue(status["stueckelberg_rkin_pushforward_derivation_available"])
        self.assertTrue(status["stueckelberg_popt_acceptance_criteria_available"])
        self.assertTrue(status["stueckelberg_popt_null_tetrad_candidate_available"])
        self.assertTrue(status["stueckelberg_rkin_commutator_closure_gate_available"])
        self.assertTrue(status["stueckelberg_sachs_optical_source_gate_available"])
        self.assertTrue(status["stueckelberg_popt_reduced_sachs_candidate_available"])
        self.assertTrue(status["stueckelberg_janus_ricci_sign_substitution_gate_available"])
        self.assertTrue(status["stueckelberg_lensing_observable_chain_gate_available"])
        self.assertTrue(status["stueckelberg_scross_source_anchor_available"])
        self.assertTrue(status["stueckelberg_shear_distance_gauge_closure_gate_available"])
        self.assertTrue(status["stueckelberg_weyl_shear_diagnostic_gate_available"])
        self.assertTrue(status["stueckelberg_observer_source_gauge_contract_available"])
        self.assertTrue(status["stueckelberg_perturbed_metric_weyl_solver_target_available"])
        self.assertTrue(status["stueckelberg_gauge_contract_instantiation_target_available"])
        self.assertTrue(status["stueckelberg_weak_field_weyl_operator_available"])
        self.assertTrue(status["stueckelberg_weak_field_weyl_source_chain_available"])
        self.assertTrue(status["stueckelberg_metric_potential_closure_contract_available"])
        self.assertTrue(status["stueckelberg_linearized_field_equation_branch_available"])
        self.assertTrue(status["stueckelberg_gauge_slip_branch_available"])
        self.assertTrue(status["stueckelberg_source_identity_branch_available"])
        self.assertTrue(status["stueckelberg_metric_potential_promotion_gate_available"])
        self.assertTrue(status["stueckelberg_comoving_scalar_metric_closure_candidate_available"])
        self.assertTrue(status["stueckelberg_noncomoving_source_identity_target_available"])
        self.assertTrue(status["stueckelberg_beta_field_provenance_gate_available"])
        self.assertTrue(status["stueckelberg_beta_vec_u_transport_target_available"])
        self.assertTrue(status["stueckelberg_noncomoving_pressure_pi_closure_requirements_available"])
        self.assertTrue(status["source_derived_beta_reconstruction_target_available"])
        self.assertTrue(status["janus_linear_beta_vec_closure_gate_available"])
        self.assertTrue(status["janus_linear_source_operator_closure_target_available"])
        self.assertTrue(status["janus_linear_theta_beta_derivation_available"])
        self.assertTrue(status["janus_linear_theta_mode_reduction_derivation_available"])
        self.assertTrue(status["noncomoving_momentum_t0i_closure_target_available"])
        self.assertTrue(status["stueckelberg_noncomoving_pressure_pi_residual_substitution_gate_available"])
        self.assertTrue(status["same_l_dl_residual_closure_ledger_available"])
        self.assertTrue(status["same_phi_l_cuu_bridge_available"])
        self.assertTrue(status["dynamic_phi_l_selection_mirror_closure_available"])
        self.assertTrue(status["phi_scouple_source_or_axiom_decision_available"])
        self.assertTrue(status["phi_scouple_anti_rustine_gate_available"])
        self.assertTrue(status["phi_scouple_forced_selection_search_available"])
        self.assertTrue(status["global_review_outside_box_routes_available"])
        self.assertTrue(status["integrability_first_phi_l_selection_available"])
        self.assertTrue(status["integrability_first_equation_system_available"])
        self.assertTrue(status["integrability_regular_patch_toy_solver_available"])
        self.assertTrue(status["local_phi_scouple_no_go_target_available"])
        self.assertTrue(status["local_phi_scouple_symbolic_restricted_audit_available"])
        self.assertTrue(status["split_noether_calculable_target_available"])
        self.assertTrue(status["split_noether_linear_phi_candidate_available"])
        self.assertTrue(status["linear_imatter_tensor_contract_available"])
        self.assertTrue(status["linear_imatter_metric_variation_available"])
        self.assertTrue(status["linear_imatter_stress_response_target_available"])
        self.assertTrue(status["matter_action_stress_response_target_available"])
        self.assertTrue(status["dust_metric_stress_response_target_available"])
        self.assertTrue(status["dust_fixed_current_density_response_available"])
        self.assertTrue(status["dust_densitized_current_density_response_available"])
        self.assertTrue(status["dust_pullback_density_response_bridge_available"])
        self.assertTrue(status["source_pullback_metric_response_target_available"])
        self.assertTrue(status["dust_fixed_pullback_delta_t_branch_available"])
        self.assertTrue(status["linear_imatter_conditional_dust_k_variation_available"])
        self.assertTrue(status["pulled_m_metric_response_target_available"])
        self.assertTrue(status["l_metric_response_law_target_available"])
        self.assertTrue(status["pulled_m_symmetric_l_substitution_available"])
        self.assertTrue(status["omega_residual_closure_gate_available"])
        self.assertTrue(status["omega_dust_rank_one_condition_available"])
        self.assertTrue(status["omega_k_qcross_consistency_gate_available"])
        self.assertTrue(status["omega_closure_routes_gate_available"])
        self.assertTrue(status["omega_u_zero_source_derivation_target_available"])
        self.assertTrue(status["omega_source_law_trial_gate_available"])
        self.assertTrue(status["fermi_walker_omega_u_zero_trial_available"])
        self.assertTrue(status["source_congruence_omega_gate_available"])
        self.assertTrue(status["omega_source_or_axiom_decision_available"])
        self.assertTrue(status["janus_source_omega_traceability_audit_available"])
        self.assertTrue(status["transport_axiom_acceptance_gate_available"])
        self.assertTrue(status["transport_axiom_candidate_statement_available"])
        self.assertTrue(status["omega_next_decision_matrix_available"])
        self.assertTrue(status["external_janus_omega_source_search_gate_available"])
        self.assertTrue(status["external_janus_omega_source_search_results_available"])
        self.assertTrue(status["external_source_search_omega_transport_audit_available"])
        self.assertTrue(status["external_source_search_scouple_phi_audit_available"])
        self.assertTrue(status["du_l_omega_dynamic_derivation_attempt_available"])
        self.assertTrue(status["omega_source_no_go_axiom_boundary_available"])
        self.assertTrue(status["dlogb4vol_measure_law_derivation_attempt_available"])
        self.assertTrue(status["pressure_pi_omega_extension_blocker_available"])
        self.assertTrue(status["janus_equations_to_l_omega_law_attempt_available"])
        self.assertTrue(status["janus_equations_to_dlogb4vol_closure_attempt_available"])
        self.assertTrue(status["bianchi_minimal_joint_dl_dlogb_solution_available"])
        self.assertTrue(status["bianchi_minimal_integrability_mirror_gate_available"])
        self.assertTrue(status["bianchi_minimal_full_connection_lift_system_available"])
        self.assertTrue(status["bianchi_minimal_mirror_inverse_attempt_available"])
        self.assertTrue(status["bianchi_minimal_curvature_integrability_system_available"])
        self.assertTrue(status["flrw_relative_curvature_rows_target_available"])
        self.assertTrue(status["weakfield_relative_curvature_rows_target_available"])
        self.assertTrue(status["weakfield_tetrad_connection_target_available"])
        self.assertTrue(status["janus_source_tetrad_requirements_available"])
        self.assertTrue(status["janus_weakfield_metric_tetrad_bridge_available"])
        self.assertTrue(status["janus_weakfield_source_potential_system_available"])
        self.assertTrue(status["janus_weakfield_phi_psi_qdet_source_closure_attempt_available"])
        self.assertTrue(status["janus_weakfield_dust_slip_poisson_target_available"])
        self.assertTrue(status["janus_weakfield_dust_slip_fourier_solver_gate_available"])
        self.assertTrue(status["janus_weakfield_zero_mode_background_gauge_gate_available"])
        self.assertTrue(status["janus_weakfield_dust_slip_green_kernel_target_available"])
        self.assertTrue(status["janus_source_selected_branch_matrix_available"])
        self.assertTrue(status["janus_weakfield_lgeom_lorentz_no_go_gate_available"])
        self.assertTrue(status["janus_weakfield_lorentz_projection_derivation_available"])
        self.assertTrue(status["janus_weakfield_shift_boost_t0i_derivation_available"])
        self.assertTrue(status["janus_weakfield_g0i_shift_operator_derivation_available"])
        self.assertTrue(status["janus_pressure_pi0i_transport_gate_available"])
        self.assertTrue(status["janus_pressure_pi0i_transport_derivation_available"])
        self.assertTrue(status["janus_g0i_dust_beta_inversion_target_available"])
        self.assertTrue(status["janus_matter_eos_pi_branch_decision_available"])
        self.assertTrue(status["janus_eos_pi_source_audit_available"])
        self.assertTrue(status["janus_conditional_dust_branch_contract_available"])
        self.assertTrue(status["janus_kinetic_moment_eos_pi_closure_target_available"])
        self.assertTrue(status["janus_kinetic_moment_hierarchy_equations_available"])
        self.assertTrue(status["janus_kinetic_closure_routes_decision_available"])
        self.assertTrue(status["janus_full_vlasov_moment_closure_contract_available"])
        self.assertTrue(status["janus_pi_zero_preservation_gate_available"])
        self.assertTrue(status["janus_vlasov_geodesic_force_target_available"])
        self.assertTrue(status["janus_eos_prho_no_go_vlasov_gate_available"])
        self.assertTrue(status["janus_metric_tetrad_source_branch_gate_available"])
        self.assertTrue(status["janus_weakfield_metric_force_probe_available"])
        self.assertTrue(status["janus_same_l_transport_stack_gate_available"])
        self.assertTrue(status["janus_phase_space_b4vol_measure_gate_available"])
        self.assertTrue(status["janus_same_l_1p1_lorentz_probe_available"])
        self.assertTrue(status["janus_lgeom_tetrad_map_residual_probe_available"])
        self.assertTrue(status["janus_lgeom_dl_lie_residual_probe_available"])
        self.assertTrue(status["janus_phase_space_measure_probe_available"])
        self.assertTrue(status["janus_weakfield_b4vol_product_rule_probe_available"])
        self.assertTrue(status["source_derived_same_l_dl_residual_closure_target_available"])
        self.assertTrue(status["dlogb4vol_source_slice_lapse_obligation_ledger_available"])
        self.assertTrue(status["falpha_source_law_obligation_ledger_available"])
        self.assertTrue(status["projected_cuu_action_pullback_bridge_ledger_available"])
        self.assertTrue(status["janus_effective_vlasov_solver_gate_available"])
        self.assertTrue(status["janus_effective_vlasov_solver_probe_available"])
        self.assertTrue(status["janus_two_sector_vlasov_poisson_probe_available"])
        self.assertTrue(status["janus_metric_force_vlasov_step_probe_available"])
        self.assertTrue(status["janus_two_sector_metric_force_vlasov_probe_available"])
        self.assertTrue(status["janus_diagnostic_closure_dashboard_available"])
        self.assertTrue(status["janus_source_residual_closure_obligation_matrix_available"])
        self.assertTrue(status["bianchi_minimal_curvature_numeric_probe_available"])
        self.assertTrue(status["curvature_integrability_sparse_pde_probe_available"])
        self.assertTrue(status["weakfield_curvature_injection_probe_available"])
        self.assertTrue(status["weakfield_tetrad_pipeline_probe_available"])
        self.assertTrue(status["bianchi_minimal_same_l_qcross_gate_available"])
        self.assertTrue(status["mirror_inverse_numeric_residual_probe_available"])
        self.assertTrue(status["same_l_qcross_numeric_contraction_probe_available"])
        self.assertTrue(status["omega_projection_annihilation_gate_available"])
        self.assertTrue(status["linear_imatter_l_variation_available"])
        self.assertTrue(status["linear_imatter_lorentz_projected_el_available"])
        self.assertTrue(status["stueckelberg_connection_force_residual_target_available"])
        self.assertTrue(status["connection_force_weak_congruence_reduction_available"])
        self.assertTrue(status["stueckelberg_projected_cuu_map_force_balance_available"])
        self.assertTrue(status["projected_cuu_action_derivation_target_available"])
        self.assertTrue(status["projected_dust_el_cuu_derivation_chain_available"])
        self.assertTrue(status["effective_density_continuity_pullback_proof_available"])
        self.assertTrue(status["stueckelberg_pulled_dust_el_projection_derivation_available"])
        self.assertTrue(status["pulled_dust_el_cuu_substitution_proof_available"])
        self.assertTrue(status["pulled_dust_el_projection_substitution_available"])
        self.assertTrue(status["dphi_jacobian_volume_identity_target_available"])
        self.assertTrue(status["stueckelberg_density_measure_identity_lock_available"])
        self.assertTrue(status["pulled_dust_dl_velocity_tetrad_substitution_gate_available"])
        self.assertTrue(status["density_measure_branch_decision_gate_available"])
        self.assertTrue(status["b_jphi_qdet_source_measure_branch_selection_target_available"])
        self.assertTrue(status["falpha_free_components_gate_available"])
        self.assertTrue(status["dl_source_law_traceability_gate_available"])
        self.assertTrue(status["b_jphi_qdet_conditional_selection_available"])
        self.assertTrue(status["falpha_minimal_gauge_candidate_available"])
        self.assertTrue(status["b4vol_fminimal_residual_trial_available"])
        self.assertTrue(status["b4vol_residual_remaining_terms_available"])
        self.assertTrue(status["b4vol_janus_source_anchor_available"])
        self.assertTrue(status["falpha_flow_projected_dl_residual_substitution_available"])
        self.assertTrue(status["janus_linear_operator_growth_ic_gate_available"])
        self.assertTrue(status["terminal_blockers_status_available"])
        self.assertTrue(status["constrained_zero_divergence_k_route_available"])
        self.assertTrue(status["bf_connection_constraint_route_available"])
        self.assertTrue(status["optimal_transport_matching_route_available"])
        self.assertTrue(status["blocker_dependency_graph_available"])
        self.assertFalse(status["k_family_accepted"])
        self.assertFalse(status["r_plus_closed"])
        self.assertFalse(status["r_minus_closed"])
        self.assertFalse(status["prediction_ready"])

    def test_tracks_cover_l_k_and_bianchi(self) -> None:
        tracks = {track["track"] for track in build_payload()["research_tracks"]}

        self.assertIn("L/DL geometry", tracks)
        self.assertIn("K interaction tensors", tracks)
        self.assertIn("Bianchi closure criteria", tracks)

    def test_rejects_scalar_and_mismatched_transport_shortcuts(self) -> None:
        rules = " ".join(build_payload()["rejection_rules"])

        self.assertIn("Q_det or Q_cross", rules)
        self.assertIn("not for K_plus/K_minus", rules)
        self.assertIn("L_geom", rules)
        self.assertIn("FLRW or Newtonian/TOV", rules)
        self.assertIn("sigma8/S8", rules)

    def test_pipeline_requires_residual_and_source_traceability(self) -> None:
        pipeline = " ".join(build_payload()["proof_pipeline"])

        self.assertIn("compute DL", pipeline)
        self.assertIn("K/Q_cross compatibility", pipeline)
        self.assertIn("R_plus/R_minus residual closure", pipeline)
        self.assertIn("source traceability", pipeline)


if __name__ == "__main__":
    unittest.main()
