import unittest

from scripts.build_p0_eft_janus_z2_sigma_bao_component_readiness_audit_gate import build_payload


class P0EFTJanusZ2SigmaBAOComponentReadinessAuditGateTests(unittest.TestCase):
    def test_component_readiness_maps_required_manifest_fields(self):
        payload = build_payload()

        self.assertEqual(payload["active_core"], "Z2_tunnel_Sigma")
        self.assertIn("cartan_ghy", payload["component_groups"])
        self.assertIn("early_plasma", payload["component_groups"])
        self.assertEqual(payload["nearest_component_frontier"]["component"], "cartan_ghy")
        self.assertTrue(
            payload["radius_embedding_frontier"][
                "conditional_radius_to_embedding_ready"
            ]
        )
        self.assertFalse(
            payload["radius_embedding_frontier"][
                "radius_to_embedding_unconditional_ready"
            ]
        )
        self.assertFalse(payload["radius_embedding_frontier"]["R_Sigma_of_a_ready"])
        self.assertFalse(
            payload["radius_embedding_frontier"]["X_plus_minus_of_a_ready"]
        )
        self.assertIn(
            "matter_flux_radial_block",
            payload["radius_embedding_frontier"]["blockers"],
        )
        self.assertIn(
            "solve_E_RSigma_equals_zero_without_fit",
            payload["radius_embedding_frontier"]["blockers"],
        )
        self.assertIn(
            "outputs/active_z2_sigma/cartan_ghy_deltaK_inputs.json",
            payload["nearest_component_frontier"]["missing_input_paths"],
        )
        self.assertIn(
            "compressed_Planck_LCDM_background",
            payload["nearest_component_frontier"]["do_not_shortcut_with"],
        )
        self.assertIn(
            "archived_Z4_background",
            payload["nearest_component_frontier"]["do_not_shortcut_with"],
        )
        self.assertIn("cartan_ghy_rho", payload["blocked_fields"])
        self.assertIn("Gamma_drag_Z2Sigma", payload["blocked_fields"])
        self.assertNotIn("cartan_ghy_rho", payload["direct_blocked_fields"])
        self.assertNotIn("cartan_ghy_p", payload["direct_blocked_fields"])
        self.assertEqual(
            payload["dependent_blocked_fields"]["cartan_ghy_rho"],
            ["DeltaK_s_Z2Sigma_of_a", "kappa_rho_crit0_Z2Sigma"],
        )
        self.assertEqual(
            payload["dependent_blocked_fields"]["cartan_ghy_p"],
            [
                "DeltaK_s_Z2Sigma_of_a",
                "DeltaK_tau_Z2Sigma_of_a",
                "kappa_rho_crit0_Z2Sigma",
            ],
        )
        self.assertEqual(payload["direct_blocked_fields"], [])
        self.assertEqual(
            payload["dependent_blocked_fields"]["holst_nieh_yan_rho"],
            [
                "FLRW_irreducible_torsion_pullback_on_Sigma",
                "dynamic_Immirzi_Holst_Nieh_Yan_boundary_variation",
                "Holst_Nieh_Yan_FLRW_stress_reduction",
            ],
        )
        self.assertTrue(
            payload["component_groups"]["holst_nieh_yan"]["builders_ready"][
                "holst_nieh_yan_component_from_inputs_ready"
            ]
        )
        self.assertFalse(
            payload["component_groups"]["holst_nieh_yan"]["builders_ready"][
                "holst_nieh_yan_component_from_inputs_passed"
            ]
        )
        self.assertEqual(
            payload["dependent_blocked_fields"]["matter_flux_rho"],
            [
                "bulk_T_munu_plus_minus_on_active_Z2Sigma_background",
                "Sigma_transparency_condition",
                "matter_flux_FLRW_reduction",
            ],
        )
        self.assertEqual(
            payload["dependent_blocked_fields"]["counterterm_rho"],
            [
                "explicit_Sigma_counterterm_density",
                "counterterm_metric_variation",
                "counterterm_FLRW_stress_reduction",
                "counterterm_radial_reduction",
            ],
        )
        self.assertTrue(
            payload["component_groups"]["counterterm"]["builders_ready"][
                "counterterm_component_from_inputs_ready"
            ]
        )
        self.assertFalse(
            payload["component_groups"]["counterterm"]["builders_ready"][
                "counterterm_component_from_inputs_passed"
            ]
        )
        self.assertTrue(
            payload["component_groups"]["counterterm"]["builders_ready"][
                "counterterm_component_requires_FLRW_stress_reduced"
            ]
        )
        self.assertTrue(
            payload["component_groups"]["counterterm"]["builders_ready"][
                "counterterm_component_requires_radial_reduction_ready"
            ]
        )
        self.assertNotIn("rho_baryon_Z2Sigma", payload["direct_blocked_fields"])
        self.assertNotIn("rho_photon_Z2Sigma", payload["direct_blocked_fields"])
        self.assertNotIn(
            "baryon_number_density0_m3_Z2Sigma",
            payload["direct_blocked_fields"],
        )
        self.assertEqual(
            payload["dependent_blocked_fields"]["baryon_number_density0_m3_Z2Sigma"],
            [
                "projected_baryon_Noether_charge_Z2Sigma",
                "active_spatial_volume0_Z2Sigma",
            ],
        )
        self.assertEqual(
            payload["dependent_blocked_fields"]["rho_baryon_Z2Sigma"],
            ["rho_baryon0_Z2Sigma", "baryon_mass_convention_Z2Sigma"],
        )
        self.assertEqual(
            payload["dependent_blocked_fields"]["rho_photon_Z2Sigma"],
            ["Tgamma0_Z2Sigma", "radiation_constant_Z2Sigma"],
        )
        self.assertNotIn("Gamma_drag_Z2Sigma", payload["direct_blocked_fields"])
        self.assertEqual(
            payload["dependent_blocked_fields"]["Gamma_drag_Z2Sigma"],
            ["rho_baryon_Z2Sigma", "rho_photon_Z2Sigma"],
        )
        self.assertNotIn("Gamma_drag_over_H0_Z2Sigma", payload["direct_blocked_fields"])
        self.assertEqual(
            payload["dependent_blocked_fields"]["Gamma_drag_over_H0_Z2Sigma"],
            ["Gamma_drag_Z2Sigma", "H0_Z2Sigma"],
        )
        self.assertTrue(
            payload["component_groups"]["cartan_ghy"]["builders_ready"][
                "metric_geometry_primitives_ready"
            ]
        )
        self.assertTrue(
            payload["component_groups"]["cartan_ghy"]["builders_ready"][
                "extrinsic_curvature_tensor_builder_ready"
            ]
        )
        self.assertTrue(
            payload["component_groups"]["cartan_ghy"]["builders_ready"][
                "flrw_extrinsic_curvature_grid_builder_ready"
            ]
        )
        self.assertTrue(
            payload["component_groups"]["cartan_ghy"]["builders_ready"][
                "flrw_extrinsic_curvature_grid_writer_ready"
            ]
        )
        self.assertFalse(
            payload["component_groups"]["cartan_ghy"]["builders_ready"][
                "flrw_extrinsic_curvature_grid_writer_passed"
            ]
        )
        self.assertTrue(
            payload["component_groups"]["cartan_ghy"]["builders_ready"][
                "extrinsic_curvature_jump_builder_ready"
            ]
        )
        self.assertTrue(
            payload["component_groups"]["cartan_ghy"]["builders_ready"][
                "cartan_ghy_from_K_plus_minus_builder_ready"
            ]
        )
        self.assertTrue(
            payload["component_groups"]["cartan_ghy"]["builders_ready"][
                "cartan_ghy_deltaK_input_writer_ready"
            ]
        )
        self.assertFalse(
            payload["component_groups"]["cartan_ghy"]["builders_ready"][
                "cartan_ghy_deltaK_input_writer_passed"
            ]
        )
        self.assertTrue(
            payload["component_groups"]["cartan_ghy"]["builders_ready"][
                "cartan_ghy_component_from_deltaK_inputs_ready"
            ]
        )
        self.assertFalse(
            payload["component_groups"]["cartan_ghy"]["builders_ready"][
                "cartan_ghy_component_from_deltaK_inputs_passed"
            ]
        )
        self.assertTrue(
            payload["component_groups"]["cartan_ghy"]["builders_ready"][
                "critical_normalization_builder_ready"
            ]
        )
        self.assertIn(
            "supply_outputs_active_z2_sigma_cartan_ghy_deltaK_inputs_json",
            payload["component_groups"]["cartan_ghy"]["blockers"],
        )
        self.assertIn(
            "supply_outputs_active_z2_sigma_flrw_extrinsic_curvature_grid_json",
            payload["component_groups"]["cartan_ghy"]["blockers"],
        )
        self.assertIn(
            "run_active_embedding_to_flrw_extrinsic_curvature_input_gate",
            payload["component_groups"]["cartan_ghy"]["blockers"],
        )
        self.assertTrue(
            payload["component_groups"]["cartan_ghy"]["builders_ready"][
                "flrw_component_manifest_writer_from_inputs_ready"
            ]
        )
        self.assertFalse(
            payload["component_groups"]["cartan_ghy"]["builders_ready"][
                "flrw_component_manifest_writer_from_inputs_passed"
            ]
        )
        self.assertTrue(
            payload["component_groups"]["cartan_ghy"]["builders_ready"][
                "flrw_inputs_merge_transparent_matter_flux_ready"
            ]
        )
        self.assertFalse(
            payload["component_groups"]["cartan_ghy"]["builders_ready"][
                "flrw_inputs_merge_transparent_matter_flux_passed"
            ]
        )
        self.assertTrue(
            payload["component_groups"]["cartan_ghy"]["builders_ready"][
                "flrw_non_matter_inputs_assembler_ready"
            ]
        )
        self.assertFalse(
            payload["component_groups"]["cartan_ghy"]["builders_ready"][
                "flrw_non_matter_inputs_assembler_passed"
            ]
        )
        self.assertIn(
            "supply_outputs_active_z2_sigma_flrw_component_inputs_json",
            payload["component_groups"]["cartan_ghy"]["blockers"],
        )
        self.assertIn("kappa_rho_crit0_Z2Sigma", payload["blocked_fields"])
        self.assertNotIn("H0_Z2Sigma", payload["direct_blocked_fields"])
        self.assertEqual(
            payload["dependent_blocked_fields"]["H0_Z2Sigma"],
            [
                "active_background_scale_gate",
                "close_z2_sigma_effective_fluid_numeric_closure",
                "feed_active_H0_omega_k_and_rho_eff_into_existing_H_builder",
            ],
        )
        self.assertNotIn("kappa_rho_crit0_Z2Sigma", payload["direct_blocked_fields"])
        self.assertEqual(
            payload["dependent_blocked_fields"]["kappa_rho_crit0_Z2Sigma"],
            ["H0_Z2Sigma"],
        )
        self.assertNotIn("omega_k_Z2Sigma", payload["direct_blocked_fields"])
        self.assertEqual(
            payload["dependent_blocked_fields"]["omega_k_Z2Sigma"],
            [
                "active_omega_k_derivation_gate",
                "active_flrw_spatial_metric_branch_gate",
                "active_curvature_sign_gate",
                "active_FLRW_curvature_radius_or_embedding_scale",
            ],
        )
        self.assertTrue(
            payload["component_groups"]["matter_flux"]["builders_ready"][
                "transparent_flux_component_builder_ready"
            ]
        )
        self.assertTrue(
            payload["component_groups"]["matter_flux"]["builders_ready"][
                "transparency_input_writer_ready"
            ]
        )
        self.assertFalse(
            payload["component_groups"]["matter_flux"]["builders_ready"][
                "transparency_input_writer_passed"
            ]
        )
        self.assertTrue(
            payload["component_groups"]["matter_flux"]["builders_ready"][
                "zero_component_from_transparency_gate_ready"
            ]
        )
        self.assertFalse(
            payload["component_groups"]["matter_flux"]["builders_ready"][
                "zero_component_from_transparency_gate_passed"
            ]
        )
        self.assertFalse(
            payload["component_groups"]["matter_flux"]["builders_ready"][
                "zero_component_values_ready"
            ]
        )
        self.assertIn(
            "supply_outputs_active_z2_sigma_matter_flux_transparency_inputs_json",
            payload["component_groups"]["matter_flux"]["blockers"],
        )
        self.assertTrue(
            payload["component_groups"]["background_scalars"]["builders_ready"][
                "background_scalar_manifest_writer_ready"
            ]
        )
        self.assertTrue(
            payload["component_groups"]["background_scalars"]["builders_ready"][
                "background_h0_input_writer_ready"
            ]
        )
        self.assertFalse(
            payload["component_groups"]["background_scalars"]["builders_ready"][
                "background_h0_input_writer_passed"
            ]
        )
        self.assertTrue(
            payload["component_groups"]["background_scalars"]["builders_ready"][
                "background_curvature_input_writer_ready"
            ]
        )
        self.assertFalse(
            payload["component_groups"]["background_scalars"]["builders_ready"][
                "background_curvature_input_writer_passed"
            ]
        )
        self.assertTrue(
            payload["component_groups"]["background_scalars"]["builders_ready"][
                "background_curvature_normalization_from_branch_ready"
            ]
        )
        self.assertFalse(
            payload["component_groups"]["background_scalars"]["builders_ready"][
                "background_curvature_normalization_from_branch_passed"
            ]
        )
        self.assertTrue(
            payload["component_groups"]["background_scalars"]["builders_ready"][
                "background_curvature_branch_inputs_assembler_ready"
            ]
        )
        self.assertFalse(
            payload["component_groups"]["background_scalars"]["builders_ready"][
                "background_curvature_branch_inputs_assembler_passed"
            ]
        )
        self.assertTrue(
            payload["component_groups"]["background_scalars"]["builders_ready"][
                "background_curvature_radius_input_writer_ready"
            ]
        )
        self.assertFalse(
            payload["component_groups"]["background_scalars"]["builders_ready"][
                "background_curvature_radius_input_writer_passed"
            ]
        )
        self.assertTrue(
            payload["component_groups"]["background_scalars"]["builders_ready"][
                "active_omega_k_formula_builder_ready"
            ]
        )
        self.assertFalse(
            payload["component_groups"]["background_scalars"]["builders_ready"][
                "active_omega_k_values_ready"
            ]
        )
        self.assertTrue(
            payload["component_groups"]["background_scalars"]["builders_ready"][
                "scale_free_omega_k_from_curvature_scale_ready"
            ]
        )
        self.assertIn(
            "scale_free_omega_k_from_curvature_scale_passed",
            payload["component_groups"]["background_scalars"]["builders_ready"],
        )
        self.assertTrue(
            payload["component_groups"]["background_scalars"]["builders_ready"][
                "h0_radius_to_scale_free_omega_k_pipeline_ready"
            ]
        )
        self.assertTrue(
            payload["component_groups"]["background_scalars"]["builders_ready"][
                "h0_radius_flrw_to_scale_free_background_pipeline_ready"
            ]
        )
        self.assertFalse(
            payload["component_groups"]["background_scalars"]["builders_ready"][
                "h0_radius_to_scale_free_omega_k_pipeline_passed"
            ]
        )
        self.assertFalse(
            payload["component_groups"]["background_scalars"]["builders_ready"][
                "h0_radius_flrw_to_scale_free_background_pipeline_passed"
            ]
        )
        self.assertTrue(
            payload["component_groups"]["background_scalars"]["builders_ready"][
                "dimensionless_curvature_scale_from_h0_radius_ready"
            ]
        )
        self.assertFalse(
            payload["component_groups"]["background_scalars"]["builders_ready"][
                "dimensionless_curvature_scale_from_h0_radius_passed"
            ]
        )
        self.assertTrue(
            payload["component_groups"]["background_scalars"]["builders_ready"][
                "dimensionless_curvature_scale_input_writer_ready"
            ]
        )
        self.assertIn(
            "dimensionless_curvature_scale_input_writer_passed",
            payload["component_groups"]["background_scalars"]["builders_ready"],
        )
        self.assertFalse(
            payload["component_groups"]["background_scalars"]["builders_ready"][
                "active_flrw_spatial_metric_branch_gate_passed"
            ]
        )
        self.assertFalse(
            payload["component_groups"]["background_scalars"]["builders_ready"][
                "active_flrw_spatial_metric_branch_values_ready"
            ]
        )
        self.assertIn(
            payload["component_groups"]["background_scalars"]["builders_ready"][
                "active_curvature_sign_gate_passed"
            ],
            [True, False],
        )
        self.assertIn(
            payload["component_groups"]["background_scalars"]["builders_ready"][
                "active_curvature_sign_values_ready"
            ],
            [True, False],
        )
        self.assertTrue(
            payload["component_groups"]["background_scalars"]["builders_ready"][
                "projective_foliation_to_rp3_slice_rule_ready"
            ]
        )
        self.assertFalse(
            payload["component_groups"]["background_scalars"]["builders_ready"][
                "projective_foliation_compatibility_gate_passed"
            ]
        )
        self.assertFalse(
            payload["component_groups"]["background_scalars"]["builders_ready"][
                "single_leaf_RP3_inference_allowed"
            ]
        )
        self.assertTrue(
            payload["component_groups"]["background_scalars"]["builders_ready"][
                "projective_spatial_slice_topology_branch_ready"
            ]
        )
        self.assertTrue(
            payload["component_groups"]["background_scalars"]["builders_ready"][
                "signed_cover_time_coordinate_from_projective_tunnel_passed"
            ]
        )
        self.assertTrue(
            payload["component_groups"]["background_scalars"]["builders_ready"][
                "signed_cover_time_parity_rule_ready"
            ]
        )
        self.assertTrue(
            payload["component_groups"]["background_scalars"]["builders_ready"][
                "signed_cover_time_parity_input_writer_passed"
            ]
        )
        self.assertTrue(
            payload["component_groups"]["background_scalars"]["builders_ready"][
                "time_parity_to_leaf_action_rule_ready"
            ]
        )
        self.assertTrue(
            payload["component_groups"]["background_scalars"]["builders_ready"][
                "time_gauge_leaf_action_input_writer_passed"
            ]
        )
        self.assertTrue(
            payload["component_groups"]["background_scalars"]["builders_ready"][
                "projective_spatial_slice_topology_branch_selected"
            ]
        )
        self.assertFalse(
            payload["component_groups"]["background_scalars"]["builders_ready"][
                "rp3_spatial_slice_input_writer_passed"
            ]
        )
        self.assertTrue(
            payload["component_groups"]["background_scalars"]["builders_ready"][
                "rp3_spatial_slice_curvature_sign_rule_ready"
            ]
        )
        self.assertFalse(
            payload["component_groups"]["background_scalars"]["builders_ready"][
                "rp3_spatial_slice_curvature_sign_gate_passed"
            ]
        )
        self.assertTrue(
            payload["component_groups"]["background_scalars"]["builders_ready"][
                "background_gravity_input_writer_ready"
            ]
        )
        self.assertTrue(
            payload["component_groups"]["background_scalars"]["builders_ready"][
                "background_gravity_codata_convention_ready"
            ]
        )
        self.assertIn(
            payload["component_groups"]["background_scalars"]["builders_ready"][
                "background_gravity_input_writer_passed"
            ],
            [True, False],
        )
        self.assertTrue(
            payload["component_groups"]["background_scalars"]["builders_ready"][
                "background_scalar_inputs_assembler_ready"
            ]
        )
        self.assertFalse(
            payload["component_groups"]["background_scalars"]["builders_ready"][
                "background_scalar_inputs_assembler_passed"
            ]
        )
        self.assertTrue(
            payload["component_groups"]["background_scalars"]["builders_ready"][
                "background_scalar_manifest_writer_from_inputs_ready"
            ]
        )
        self.assertFalse(
            payload["component_groups"]["background_scalars"]["builders_ready"][
                "background_scalar_manifest_writer_from_inputs_passed"
            ]
        )
        self.assertTrue(
            payload["component_groups"]["background_scalars"]["builders_ready"][
                "background_physical_input_obligation_ready"
            ]
        )
        self.assertFalse(
            payload["component_groups"]["background_scalars"]["builders_ready"][
                "background_physical_input_obligation_passed"
            ]
        )
        self.assertIn(
            "H0_Z2Sigma",
            payload["component_groups"]["background_scalars"]["builders_ready"][
                "background_missing_physical_inputs"
            ],
        )
        self.assertTrue(
            payload["component_groups"]["background_scalars"]["builders_ready"][
                "critical_normalization_builder_ready"
            ]
        )
        self.assertIn(
            "supply_outputs_active_z2_sigma_background_scalar_inputs_json",
            payload["component_groups"]["background_scalars"]["blockers"],
        )
        self.assertIn(
            "supply_outputs_active_z2_sigma_background_H0_inputs_json",
            payload["component_groups"]["background_scalars"]["blockers"],
        )
        self.assertIn(
            "supply_outputs_active_z2_sigma_background_H0_normalization_inputs_json",
            payload["component_groups"]["background_scalars"]["blockers"],
        )
        self.assertIn(
            "supply_outputs_active_z2_sigma_background_curvature_inputs_json",
            payload["component_groups"]["background_scalars"]["blockers"],
        )
        self.assertIn(
            "supply_outputs_active_z2_sigma_background_curvature_normalization_inputs_json",
            payload["component_groups"]["background_scalars"]["blockers"],
        )
        self.assertIn(
            "supply_outputs_active_z2_sigma_background_curvature_radius_inputs_json",
            payload["component_groups"]["background_scalars"]["blockers"],
        )
        self.assertIn(
            "supply_outputs_active_z2_sigma_background_dimensionless_curvature_scale_inputs_json",
            payload["component_groups"]["background_scalars"]["blockers"],
        )
        self.assertIn(
            "write_outputs_active_z2_sigma_rp3_spatial_slice_inputs_json",
            payload["component_groups"]["background_scalars"]["blockers"],
        )
        self.assertIn(
            "write_outputs_active_z2_sigma_projective_foliation_inputs_json",
            payload["component_groups"]["background_scalars"]["blockers"],
        )
        self.assertIn(
            "select_RP3_invariant_leaf_or_S3_paired_leaf_representative_branch",
            payload["component_groups"]["background_scalars"]["blockers"],
        )
        self.assertIn(
            "write_outputs_active_z2_sigma_signed_cover_time_coordinate_inputs_json",
            payload["component_groups"]["background_scalars"]["blockers"],
        )
        self.assertIn(
            "write_outputs_active_z2_sigma_active_time_coordinate_parity_inputs_json",
            payload["component_groups"]["background_scalars"]["blockers"],
        )
        self.assertIn(
            "supply_outputs_active_z2_sigma_background_gravity_inputs_json",
            payload["component_groups"]["background_scalars"]["blockers"],
        )
        if not payload["component_groups"]["background_scalars"]["builders_ready"][
            "background_gravity_input_writer_passed"
        ]:
            self.assertIn(
                "supply_outputs_active_z2_sigma_background_gravity_normalization_inputs_json",
                payload["component_groups"]["background_scalars"]["blockers"],
            )
        self.assertTrue(
            payload["component_groups"]["early_plasma"]["builders_ready"][
                "thomson_drag_builder_ready"
            ]
        )
        self.assertTrue(
            payload["component_groups"]["early_plasma"]["builders_ready"][
                "gamma_drag_over_h0_builder_ready"
            ]
        )
        self.assertFalse(
            payload["component_groups"]["early_plasma"]["builders_ready"][
                "scale_free_gamma_drag_over_h0_from_active_h0_ready"
            ]
        )
        self.assertTrue(
            payload["component_groups"]["early_plasma"]["builders_ready"][
                "early_plasma_component_manifest_writer_ready"
            ]
        )
        self.assertTrue(
            payload["component_groups"]["early_plasma"]["builders_ready"][
                "early_plasma_baryon_photon_input_writer_ready"
            ]
        )
        self.assertFalse(
            payload["component_groups"]["early_plasma"]["builders_ready"][
                "early_plasma_baryon_photon_input_writer_passed"
            ]
        )
        self.assertTrue(
            payload["component_groups"]["early_plasma"]["builders_ready"][
                "early_plasma_ionization_thomson_input_writer_ready"
            ]
        )
        self.assertFalse(
            payload["component_groups"]["early_plasma"]["builders_ready"][
                "early_plasma_ionization_thomson_input_writer_passed"
            ]
        )
        self.assertTrue(
            payload["component_groups"]["early_plasma"]["builders_ready"][
                "early_plasma_inputs_assembler_ready"
            ]
        )
        self.assertFalse(
            payload["component_groups"]["early_plasma"]["builders_ready"][
                "early_plasma_inputs_assembler_passed"
            ]
        )
        self.assertTrue(
            payload["component_groups"]["early_plasma"]["builders_ready"][
                "early_plasma_physical_input_obligation_ready"
            ]
        )
        self.assertFalse(
            payload["component_groups"]["early_plasma"]["builders_ready"][
                "early_plasma_physical_input_obligation_passed"
            ]
        )
        self.assertTrue(
            payload["component_groups"]["early_plasma"]["fields"][
                "photon_temperature0_Z2Sigma"
            ]
        )
        self.assertTrue(
            payload["component_groups"]["early_plasma"]["fields"][
                "rho_photon0_Z2Sigma"
            ]
        )
        self.assertTrue(
            payload["component_groups"]["early_plasma"]["fields"][
                "rho_photon_history_Z2Sigma"
            ]
        )
        self.assertTrue(
            payload["component_groups"]["early_plasma"]["builders_ready"][
                "early_plasma_codata_constants_passed"
            ]
        )
        self.assertTrue(
            payload["component_groups"]["early_plasma"]["builders_ready"][
                "early_plasma_photon_temperature_firas_passed"
            ]
        )
        self.assertTrue(
            payload["component_groups"]["early_plasma"]["builders_ready"][
                "early_plasma_photon_density_firas_codata_passed"
            ]
        )
        self.assertTrue(
            payload["component_groups"]["early_plasma"]["builders_ready"][
                "early_plasma_photon_density_history_firas_codata_passed"
            ]
        )
        self.assertTrue(
            payload["component_groups"]["early_plasma"]["builders_ready"][
                "early_plasma_saha_ionization_readiness_ready"
            ]
        )
        self.assertTrue(
            payload["component_groups"]["early_plasma"]["builders_ready"][
                "saha_ionization_history_ready"
            ]
        )
        self.assertTrue(
            payload["component_groups"]["early_plasma"]["builders_ready"][
                "early_plasma_saha_inputs_assembler_ready"
            ]
        )
        self.assertTrue(
            payload["component_groups"]["early_plasma"]["builders_ready"][
                "noether_volume_to_saha_early_plasma_pipeline_ready"
            ]
        )
        self.assertTrue(
            payload["component_groups"]["early_plasma"]["builders_ready"][
                "curvature_charge_to_saha_early_plasma_pipeline_ready"
            ]
        )
        self.assertTrue(
            payload["component_groups"]["early_plasma"]["builders_ready"][
                "baryon_number_density_noether_volume_ready"
            ]
        )
        self.assertFalse(
            payload["component_groups"]["early_plasma"]["builders_ready"][
                "baryon_number_density_noether_volume_passed"
            ]
        )
        self.assertFalse(
            payload["component_groups"]["early_plasma"]["builders_ready"][
                "active_projected_baryon_charge_valid"
            ]
        )
        self.assertTrue(
            payload["component_groups"]["early_plasma"]["builders_ready"][
                "projected_baryon_noether_charge_input_ready"
            ]
        )
        self.assertFalse(
            payload["component_groups"]["early_plasma"]["builders_ready"][
                "projected_baryon_noether_charge_input_passed"
            ]
        )
        self.assertFalse(
            payload["component_groups"]["early_plasma"]["builders_ready"][
                "active_spatial_volume_valid"
            ]
        )
        self.assertTrue(
            payload["component_groups"]["early_plasma"]["builders_ready"][
                "spatial_volume_input_writer_from_curvature_branch_ready"
            ]
        )
        self.assertFalse(
            payload["component_groups"]["early_plasma"]["builders_ready"][
                "spatial_volume_input_writer_from_curvature_branch_passed"
            ]
        )
        self.assertTrue(
            payload["component_groups"]["early_plasma"]["builders_ready"][
                "spatial_volume_projective_slice_formula_ready"
            ]
        )
        self.assertFalse(
            payload["component_groups"]["early_plasma"]["builders_ready"][
                "spatial_volume_projective_slice_passed"
            ]
        )
        self.assertFalse(
            payload["component_groups"]["early_plasma"]["builders_ready"][
                "early_plasma_saha_ionization_readiness_passed"
            ]
        )
        self.assertFalse(
            payload["component_groups"]["early_plasma"]["builders_ready"][
                "saha_ionization_history_passed"
            ]
        )
        self.assertFalse(
            payload["component_groups"]["early_plasma"]["builders_ready"][
                "early_plasma_saha_inputs_assembler_passed"
            ]
        )
        self.assertFalse(
            payload["component_groups"]["early_plasma"]["builders_ready"][
                "noether_volume_to_saha_early_plasma_pipeline_passed"
            ]
        )
        self.assertFalse(
            payload["component_groups"]["early_plasma"]["builders_ready"][
                "curvature_charge_to_saha_early_plasma_pipeline_passed"
            ]
        )
        self.assertFalse(
            payload["component_groups"]["early_plasma"]["builders_ready"][
                "early_plasma_model_normalization_assembler_passed"
            ]
        )
        self.assertIn(
            "early_plasma_baryon_photon_normalization_inputs",
            payload["component_groups"]["early_plasma"]["builders_ready"][
                "early_plasma_missing_physical_inputs"
            ],
        )
        self.assertTrue(
            payload["component_groups"]["early_plasma"]["builders_ready"][
                "early_plasma_manifest_writer_from_inputs_ready"
            ]
        )
        self.assertFalse(
            payload["component_groups"]["early_plasma"]["builders_ready"][
                "early_plasma_manifest_writer_from_inputs_passed"
            ]
        )
        self.assertTrue(
            payload["component_groups"]["early_plasma"]["builders_ready"][
                "early_plasma_component_manifest_merge_ready"
            ]
        )
        self.assertTrue(
            payload["component_groups"]["early_plasma"]["builders_ready"][
                "drag_epoch_bracket_finder_ready"
            ]
        )
        self.assertNotIn(
            "derive_active_photon_temperature_history_Tgamma_Z2Sigma",
            payload["component_groups"]["early_plasma"]["blockers"],
        )
        self.assertNotIn(
            "derive_active_rho_photon0_Z2Sigma",
            payload["component_groups"]["early_plasma"]["blockers"],
        )
        self.assertNotIn(
            "derive_active_rho_baryon0_Z2Sigma",
            payload["component_groups"]["early_plasma"]["blockers"],
        )
        self.assertIn(
            "supply_outputs_active_z2_sigma_early_plasma_inputs_json",
            payload["component_groups"]["early_plasma"]["blockers"],
        )
        self.assertIn(
            "supply_outputs_active_z2_sigma_early_plasma_baryon_photon_inputs_json",
            payload["component_groups"]["early_plasma"]["blockers"],
        )
        self.assertIn(
            "supply_outputs_active_z2_sigma_early_plasma_baryon_photon_normalization_inputs_json",
            payload["component_groups"]["early_plasma"]["blockers"],
        )
        self.assertIn(
            "supply_outputs_active_z2_sigma_early_plasma_ionization_thomson_inputs_json",
            payload["component_groups"]["early_plasma"]["blockers"],
        )
        self.assertIn(
            "supply_outputs_active_z2_sigma_early_plasma_ionization_thomson_normalization_inputs_json",
            payload["component_groups"]["early_plasma"]["blockers"],
        )
        self.assertIn(
            "derive_R_Sigma_of_a_from_active_throat_radius_variational_equation",
            payload["root_obligations"],
        )
        self.assertIn(
            "derive_FLRW_irreducible_torsion_pullback_on_Sigma",
            payload["root_obligations"],
        )
        frontier_artifacts = {
            item["artifact"]: item["classification"]
            for item in payload["remaining_artifact_frontier"]
        }
        self.assertEqual(
            frontier_artifacts["outputs/active_z2_sigma/background_H0_inputs.json"],
            "physical_derivation_blocker",
        )
        self.assertEqual(
            frontier_artifacts[
                "outputs/active_z2_sigma/background_scalar_inputs.json"
            ],
            "plumbing_gap_after_physical_inputs",
        )
        self.assertEqual(
            frontier_artifacts[
                "outputs/active_z2_sigma/flrw_extrinsic_curvature_grid_inputs.json"
            ],
            "physical_derivation_blocker",
        )
        self.assertEqual(
            frontier_artifacts["outputs/active_z2_sigma/bao_inputs.json"],
            "plumbing_gap_after_three_active_manifests",
        )
        self.assertIn(
            "active_R_Sigma_of_a_and_X_plus_minus_of_a",
            payload["physical_derivation_frontier"],
        )
        self.assertIn(
            "active_ionization_free_electron_and_Thomson_drag_inputs",
            payload["physical_derivation_frontier"],
        )
        self.assertEqual(
            payload["canonical_first_active_artifact"]["artifact"],
            "outputs/active_z2_sigma/background_scalars.json",
        )
        self.assertIn(
            "outputs/active_z2_sigma/background_curvature_inputs.json",
            payload["canonical_first_active_artifact"]["required_upstream_inputs"],
        )
        self.assertIn(
            "no archived Z4 background",
            payload["canonical_first_active_artifact"]["required_policy"],
        )
        self.assertEqual(
            payload["canonical_first_scale_free_active_artifact"]["artifact"],
            "outputs/active_z2_sigma/bao_scale_free_inputs.json",
        )
        self.assertIn(
            "Gamma_drag_over_H0_Z2Sigma_of_z",
            payload["canonical_first_scale_free_active_artifact"][
                "required_primitives"
            ],
        )
        self.assertIn(
            "no observational H0 fit",
            payload["canonical_first_scale_free_active_artifact"][
                "required_policy"
            ],
        )
        self.assertIn("normalization_policy", payload)
        self.assertIn(
            "not an observational H0 fit",
            payload["normalization_policy"]["H0_Z2Sigma_role"],
        )
        self.assertIn(
            "self-consistently",
            payload["normalization_policy"]["bao_ratio_scale_invariance"],
        )
        self.assertIn("frontier_policy", payload)

    def test_component_readiness_blocks_manifest_until_active_fields_exist(self):
        payload = build_payload()

        self.assertFalse(payload["strict_manifest_inputs"]["required_manifests_available"])
        self.assertFalse(payload["strict_manifest_inputs"]["official_component_manifest_written"])
        self.assertFalse(payload["internal_derivation_component_inputs_ready"])
        self.assertFalse(payload["strict_manifest_component_inputs_ready"])
        self.assertFalse(payload["component_manifest_inputs_ready"])
        self.assertFalse(payload["bao_component_inputs_manifest_writable"])
        self.assertFalse(payload["bao_active_manifest_pipeline_gate_can_pass"])
        self.assertTrue(payload["bao_scale_free_active_manifest_pipeline_ready"])
        self.assertFalse(payload["bao_scale_free_active_manifest_pipeline_gate_passed"])
        self.assertFalse(payload["bao_scale_free_active_manifest_pipeline_can_pass"])
        self.assertFalse(payload["bao_scale_free_minimal_contract_ready"])
        self.assertTrue(payload["bao_scale_free_primitive_chi2_gate_ready"])
        self.assertFalse(payload["bao_scale_free_primitive_chi2_gate_passed"])
        self.assertTrue(payload["bao_component_to_scale_free_split_primitives_ready"])
        self.assertFalse(payload["bao_component_to_scale_free_split_primitives_passed"])
        self.assertTrue(payload["flrw_to_scale_free_background_primitive_ready"])
        self.assertFalse(payload["flrw_to_scale_free_background_primitive_passed"])
        self.assertTrue(payload["flrw_to_scale_free_background_primitive_normalization_input_ready"])
        self.assertFalse(payload["flrw_to_scale_free_background_primitive_normalization_input_passed"])
        self.assertTrue(payload["scale_free_background_primitive_input_writer_ready"])
        self.assertFalse(payload["scale_free_background_primitive_input_writer_passed"])
        self.assertTrue(payload["early_plasma_to_scale_free_plasma_primitive_ready"])
        self.assertFalse(payload["early_plasma_to_scale_free_plasma_primitive_passed"])
        self.assertTrue(payload["early_plasma_to_scale_free_plasma_primitive_normalization_input_ready"])
        self.assertFalse(payload["early_plasma_to_scale_free_plasma_primitive_normalization_input_passed"])
        self.assertTrue(payload["scale_free_plasma_primitive_input_writer_ready"])
        self.assertFalse(payload["scale_free_plasma_primitive_input_writer_passed"])
        self.assertTrue(payload["bao_component_to_scale_free_primitive_chi2_ready"])
        self.assertFalse(payload["bao_component_to_scale_free_primitive_chi2_passed"])
        self.assertTrue(payload["active_inputs_to_scale_free_primitive_chi2_ready"])
        self.assertFalse(payload["active_inputs_to_scale_free_primitive_chi2_passed"])
        self.assertTrue(payload["bao_active_primitive_physical_input_obligation_ready"])
        self.assertFalse(payload["bao_active_primitive_physical_input_obligation_passed"])
        self.assertIn(
            "flrw_component_inputs",
            payload["bao_active_primitive_physical_missing_groups"],
        )
        self.assertIn(
            "early_plasma_inputs",
            payload["bao_active_primitive_physical_missing_groups"],
        )
        self.assertTrue(payload["bao_scale_free_primitive_derivation_frontier_ready"])
        self.assertFalse(payload["bao_scale_free_primitive_derivation_frontier_passed"])
        self.assertEqual(
            payload["bao_scale_free_primitive_derivation_frontier_blocker"],
            "derive and write valid active scale-free background and plasma primitive manifests",
        )
        self.assertTrue(payload["bao_scale_free_primitive_inputs_assembler_ready"])
        self.assertFalse(payload["bao_scale_free_primitive_inputs_assembler_passed"])
        self.assertTrue(payload["bao_split_primitives_to_scale_free_chi2_ready"])
        self.assertFalse(payload["bao_split_primitives_to_scale_free_chi2_passed"])
        self.assertTrue(payload["bao_direct_primitives_to_scale_free_chi2_ready"])
        self.assertFalse(payload["bao_direct_primitives_to_scale_free_chi2_passed"])
        self.assertFalse(payload["bao_scale_free_primitive_input_manifest_available"])
        self.assertIn("E_Z2Sigma_of_z", payload["bao_scale_free_minimal_primitives"])
        self.assertIn("Gamma_drag_over_H0_Z2Sigma_of_z", payload["bao_scale_free_minimal_primitives"])
        self.assertFalse(payload["gate_passed"])
        self.assertTrue(payload["observational_fit_forbidden"])
        self.assertTrue(payload["compressed_planck_lcdm_rd_forbidden"])
        self.assertTrue(payload["archived_z4_reuse_forbidden"])


if __name__ == "__main__":
    unittest.main()
