from __future__ import annotations

import unittest

from scripts.build_p0_blocker_dependency_graph import build_payload


class P0BlockerDependencyGraphTests(unittest.TestCase):
    def test_graph_is_written_but_not_closed(self) -> None:
        payload = build_payload()

        self.assertTrue(payload["graph_written"])
        self.assertTrue(payload["artifact_availability_computed"])
        self.assertTrue(payload["blocker_closure_computed"])
        self.assertEqual(payload["source_residual_matrix_status"], "source-residual-closure-obligation-matrix-open")
        self.assertFalse(payload["all_blockers_closed"])
        self.assertTrue(payload["du_l_omega_dynamic_derivation_attempt_available"])
        self.assertTrue(payload["omega_source_no_go_axiom_boundary_available"])
        self.assertTrue(payload["dlogb4vol_measure_law_derivation_attempt_available"])
        self.assertTrue(payload["pressure_pi_omega_extension_blocker_available"])
        self.assertTrue(payload["janus_equations_to_l_omega_law_attempt_available"])
        self.assertTrue(payload["janus_equations_to_dlogb4vol_closure_attempt_available"])
        self.assertTrue(payload["bianchi_minimal_joint_dl_dlogb_solution_available"])
        self.assertTrue(payload["bianchi_minimal_integrability_mirror_gate_available"])
        self.assertTrue(payload["bianchi_minimal_full_connection_lift_system_available"])
        self.assertTrue(payload["bianchi_minimal_mirror_inverse_attempt_available"])
        self.assertTrue(payload["bianchi_minimal_curvature_integrability_system_available"])
        self.assertTrue(payload["flrw_relative_curvature_rows_target_available"])
        self.assertTrue(payload["weakfield_relative_curvature_rows_target_available"])
        self.assertTrue(payload["weakfield_tetrad_connection_target_available"])
        self.assertTrue(payload["janus_source_tetrad_requirements_available"])
        self.assertTrue(payload["janus_weakfield_metric_tetrad_bridge_available"])
        self.assertTrue(payload["janus_weakfield_source_potential_system_available"])
        self.assertTrue(payload["janus_weakfield_phi_psi_qdet_source_closure_attempt_available"])
        self.assertTrue(payload["janus_weakfield_dust_slip_poisson_target_available"])
        self.assertTrue(payload["janus_weakfield_dust_slip_fourier_solver_gate_available"])
        self.assertTrue(payload["janus_weakfield_zero_mode_background_gauge_gate_available"])
        self.assertTrue(payload["janus_weakfield_dust_slip_green_kernel_target_available"])
        self.assertTrue(payload["janus_source_selected_branch_matrix_available"])
        self.assertTrue(payload["janus_weakfield_lgeom_lorentz_no_go_gate_available"])
        self.assertTrue(payload["janus_weakfield_lorentz_projection_derivation_available"])
        self.assertTrue(payload["janus_weakfield_shift_boost_t0i_derivation_available"])
        self.assertTrue(payload["janus_weakfield_g0i_shift_operator_derivation_available"])
        self.assertTrue(payload["janus_pressure_pi0i_transport_gate_available"])
        self.assertTrue(payload["janus_pressure_pi0i_transport_derivation_available"])
        self.assertTrue(payload["janus_g0i_dust_beta_inversion_target_available"])
        self.assertTrue(payload["janus_matter_eos_pi_branch_decision_available"])
        self.assertTrue(payload["janus_eos_pi_source_audit_available"])
        self.assertTrue(payload["janus_conditional_dust_branch_contract_available"])
        self.assertTrue(payload["janus_kinetic_moment_eos_pi_closure_target_available"])
        self.assertTrue(payload["janus_kinetic_moment_hierarchy_equations_available"])
        self.assertTrue(payload["janus_kinetic_closure_routes_decision_available"])
        self.assertTrue(payload["janus_full_vlasov_moment_closure_contract_available"])
        self.assertTrue(payload["janus_pi_zero_preservation_gate_available"])
        self.assertTrue(payload["janus_vlasov_geodesic_force_target_available"])
        self.assertTrue(payload["janus_eos_prho_no_go_vlasov_gate_available"])
        self.assertTrue(payload["janus_metric_tetrad_source_branch_gate_available"])
        self.assertTrue(payload["janus_weakfield_metric_force_probe_available"])
        self.assertTrue(payload["janus_same_l_transport_stack_gate_available"])
        self.assertTrue(payload["janus_phase_space_b4vol_measure_gate_available"])
        self.assertTrue(payload["janus_same_l_1p1_lorentz_probe_available"])
        self.assertTrue(payload["janus_lgeom_tetrad_map_residual_probe_available"])
        self.assertTrue(payload["janus_lgeom_dl_lie_residual_probe_available"])
        self.assertTrue(payload["janus_phase_space_measure_probe_available"])
        self.assertTrue(payload["janus_weakfield_b4vol_product_rule_probe_available"])
        self.assertTrue(payload["shared_phi_j_source_selection_gate_available"])
        self.assertTrue(payload["source_derived_same_l_dl_residual_closure_target_available"])
        self.assertTrue(payload["dlogb4vol_source_slice_lapse_obligation_ledger_available"])
        self.assertTrue(payload["dlogb4vol_jacobian_lapse_slice_identity_target_available"])
        self.assertTrue(payload["falpha_source_law_obligation_ledger_available"])
        self.assertTrue(payload["falpha_from_jacobian_tetrad_identity_target_available"])
        self.assertTrue(payload["projected_cuu_action_pullback_bridge_ledger_available"])
        self.assertTrue(payload["cuu_inverse_map_integrability_target_available"])
        self.assertTrue(payload["cuu_jacobian_curl_numeric_probe_available"])
        self.assertTrue(payload["janus_effective_vlasov_solver_gate_available"])
        self.assertTrue(payload["janus_effective_vlasov_solver_probe_available"])
        self.assertTrue(payload["janus_two_sector_vlasov_poisson_probe_available"])
        self.assertTrue(payload["janus_metric_force_vlasov_step_probe_available"])
        self.assertTrue(payload["janus_two_sector_metric_force_vlasov_probe_available"])
        self.assertTrue(payload["janus_diagnostic_closure_dashboard_available"])
        self.assertTrue(payload["janus_source_residual_closure_obligation_matrix_available"])
        self.assertTrue(payload["source_derived_joint_dl_dlogb_residual_substitution_target_available"])
        self.assertTrue(payload["bianchi_minimal_curvature_numeric_probe_available"])
        self.assertTrue(payload["curvature_integrability_sparse_pde_probe_available"])
        self.assertTrue(payload["weakfield_curvature_injection_probe_available"])
        self.assertTrue(payload["weakfield_tetrad_pipeline_probe_available"])
        self.assertTrue(payload["bianchi_minimal_same_l_qcross_gate_available"])
        self.assertTrue(payload["mirror_inverse_numeric_residual_probe_available"])
        self.assertTrue(payload["same_l_qcross_numeric_contraction_probe_available"])
        self.assertFalse(payload["physics_closed"])
        self.assertFalse(payload["prediction_ready"])
        self.assertGreater(payload["available_artifact_count"], 0)
        self.assertEqual(payload["missing_listed_artifacts"], [])
        self.assertIn("D L transport law", payload["open_blockers"])
        self.assertEqual(payload["all_blockers_closed"], all(row["closed"] for row in payload["blockers"]))
        self.assertEqual(
            set(payload["open_blockers"]),
            {row["blocker"] for row in payload["blockers"] if not row["closed"]},
        )

    def test_critical_path_starts_with_dl_and_dlogb(self) -> None:
        order = build_payload()["priority_order"]

        self.assertEqual(order[0], "D L transport law")
        self.assertEqual(order[1], "D log B_4vol measure law")

    def test_blockers_cover_source_matter_and_observables(self) -> None:
        blockers = {row["blocker"] for row in build_payload()["blockers"]}

        self.assertIn("source-measure branch selection", blockers)
        self.assertIn("matter extension", blockers)
        self.assertIn("observable chain", blockers)
        rows = {row["blocker"]: row for row in build_payload()["blockers"]}
        self.assertFalse(rows["matter extension"]["closed"])
        self.assertFalse(rows["observable chain"]["closed"])
        self.assertFalse(rows["matter extension"]["closure_computed"])
        self.assertFalse(rows["observable chain"]["closure_computed"])

    def test_artifact_availability_is_derived_from_blocker_rows(self) -> None:
        payload = build_payload()
        artifacts = {
            artifact
            for row in payload["blockers"]
            for artifact in row["artifacts"]
        }

        self.assertEqual(set(payload["artifact_availability"]), artifacts)
        self.assertTrue(all(payload["artifact_availability"].values()))
        self.assertTrue(payload["janus_source_residual_closure_obligation_matrix_available"])

    def test_blocker_closure_is_computed_from_requirements(self) -> None:
        payload = build_payload()
        blockers = {row["blocker"]: row for row in payload["blockers"]}

        self.assertTrue(blockers["D L transport law"]["closure_computed"])
        self.assertTrue(blockers["D log B_4vol measure law"]["closure_computed"])
        self.assertTrue(blockers["source-measure branch selection"]["closure_computed"])
        self.assertIn("same_l_dl_source_law", blockers["D L transport law"]["closure_requirements"])
        self.assertIn("b4vol_source_measure_law", blockers["D log B_4vol measure law"]["closure_requirements"])
        self.assertFalse(blockers["D L transport law"]["closed"])
        self.assertFalse(blockers["D log B_4vol measure law"]["closed"])

    def test_dependencies_prevent_prediction_shortcut(self) -> None:
        text = " ".join(
            " ".join(row["depends_on"] + row["artifacts"] + row["unblocks"])
            for row in build_payload()["blockers"]
        )

        self.assertIn("source traceability", text)
        self.assertIn("p0_du_l_omega_dynamic_derivation_attempt", text)
        self.assertIn("p0_omega_source_no_go_axiom_boundary", text)
        self.assertIn("p0_dlogb4vol_measure_law_derivation_attempt", text)
        self.assertIn("p0_pressure_pi_omega_extension_blocker", text)
        self.assertIn("p0_janus_equations_to_l_omega_law_attempt", text)
        self.assertIn("p0_janus_equations_to_dlogb4vol_closure_attempt", text)
        self.assertIn("p0_bianchi_minimal_joint_dl_dlogb_solution", text)
        self.assertIn("p0_bianchi_minimal_integrability_mirror_gate", text)
        self.assertIn("p0_bianchi_minimal_full_connection_lift_system", text)
        self.assertIn("p0_bianchi_minimal_mirror_inverse_attempt", text)
        self.assertIn("p0_bianchi_minimal_curvature_integrability_system", text)
        self.assertIn("p0_flrw_relative_curvature_rows_target", text)
        self.assertIn("p0_weakfield_relative_curvature_rows_target", text)
        self.assertIn("p0_weakfield_tetrad_connection_target", text)
        self.assertIn("p0_janus_source_tetrad_requirements", text)
        self.assertIn("p0_janus_weakfield_metric_tetrad_bridge", text)
        self.assertIn("p0_janus_weakfield_source_potential_system", text)
        self.assertIn("p0_janus_weakfield_phi_psi_qdet_source_closure_attempt", text)
        self.assertIn("p0_janus_weakfield_dust_slip_poisson_target", text)
        self.assertIn("p0_janus_weakfield_dust_slip_fourier_solver_gate", text)
        self.assertIn("p0_janus_weakfield_zero_mode_background_gauge_gate", text)
        self.assertIn("p0_janus_weakfield_dust_slip_green_kernel_target", text)
        self.assertIn("p0_janus_source_selected_branch_matrix", text)
        self.assertIn("p0_janus_weakfield_lgeom_lorentz_no_go_gate", text)
        self.assertIn("p0_janus_weakfield_lorentz_projection_derivation", text)
        self.assertIn("p0_janus_weakfield_shift_boost_t0i_derivation", text)
        self.assertIn("p0_janus_weakfield_g0i_shift_operator_derivation", text)
        self.assertIn("p0_janus_pressure_pi0i_transport_gate", text)
        self.assertIn("p0_janus_pressure_pi0i_transport_derivation", text)
        self.assertIn("p0_janus_g0i_dust_beta_inversion_target", text)
        self.assertIn("p0_janus_matter_eos_pi_branch_decision", text)
        self.assertIn("p0_janus_eos_pi_source_audit", text)
        self.assertIn("p0_janus_conditional_dust_branch_contract", text)
        self.assertIn("p0_janus_kinetic_moment_eos_pi_closure_target", text)
        self.assertIn("p0_janus_kinetic_moment_hierarchy_equations", text)
        self.assertIn("p0_janus_kinetic_closure_routes_decision", text)
        self.assertIn("p0_janus_full_vlasov_moment_closure_contract", text)
        self.assertIn("p0_janus_pi_zero_preservation_gate", text)
        self.assertIn("p0_janus_vlasov_geodesic_force_target", text)
        self.assertIn("p0_janus_eos_prho_no_go_vlasov_gate", text)
        self.assertIn("p0_janus_metric_tetrad_source_branch_gate", text)
        self.assertIn("p0_janus_weakfield_metric_force_probe", text)
        self.assertIn("p0_janus_same_l_transport_stack_gate", text)
        self.assertIn("p0_janus_phase_space_b4vol_measure_gate", text)
        self.assertIn("p0_janus_same_l_1p1_lorentz_probe", text)
        self.assertIn("p0_janus_lgeom_tetrad_map_residual_probe", text)
        self.assertIn("p0_janus_lgeom_dl_lie_residual_probe", text)
        self.assertIn("p0_janus_phase_space_measure_probe", text)
        self.assertIn("p0_janus_weakfield_b4vol_product_rule_probe", text)
        self.assertIn("p0_shared_phi_j_source_selection_gate", text)
        self.assertIn("p0_source_derived_same_l_dl_residual_closure_target", text)
        self.assertIn("p0_dlogb4vol_source_slice_lapse_obligation_ledger", text)
        self.assertIn("p0_dlogb4vol_jacobian_lapse_slice_identity_target", text)
        self.assertIn("p0_falpha_source_law_obligation_ledger", text)
        self.assertIn("p0_falpha_from_jacobian_tetrad_identity_target", text)
        self.assertIn("p0_projected_cuu_action_pullback_bridge_ledger", text)
        self.assertIn("p0_cuu_inverse_map_integrability_target", text)
        self.assertIn("p0_cuu_jacobian_curl_numeric_probe", text)
        self.assertIn("p0_janus_effective_vlasov_solver_gate", text)
        self.assertIn("p0_janus_effective_vlasov_solver_probe", text)
        self.assertIn("p0_janus_two_sector_vlasov_poisson_probe", text)
        self.assertIn("p0_janus_metric_force_vlasov_step_probe", text)
        self.assertIn("p0_janus_two_sector_metric_force_vlasov_probe", text)
        self.assertIn("p0_janus_diagnostic_closure_dashboard", text)
        self.assertIn("p0_janus_source_residual_closure_obligation_matrix", text)
        self.assertIn("p0_source_derived_joint_dl_dlogb_residual_substitution_target", text)
        self.assertIn("p0_bianchi_minimal_curvature_numeric_probe", text)
        self.assertIn("p0_curvature_integrability_sparse_pde_probe", text)
        self.assertIn("p0_weakfield_curvature_injection_probe", text)
        self.assertIn("p0_weakfield_tetrad_pipeline_probe", text)
        self.assertIn("p0_bianchi_minimal_same_l_qcross_gate", text)
        self.assertIn("p0_mirror_inverse_numeric_residual_probe", text)
        self.assertIn("p0_same_l_qcross_numeric_contraction_probe", text)
        self.assertIn("no Q_det double-counting", text)
        self.assertIn("Q_cross normalization", text)
        self.assertIn("S8/lensing claims", text)


if __name__ == "__main__":
    unittest.main()
