from __future__ import annotations

import unittest

from scripts.build_p0_blocker_dependency_graph import build_payload as build_graph_payload
from scripts.build_p0_terminal_blockers_status import build_payload


class P0TerminalBlockersStatusTests(unittest.TestCase):
    def test_status_is_finite_but_open(self) -> None:
        payload = build_payload()
        graph = build_graph_payload()

        self.assertEqual(
            payload["status"],
            "terminal-blockers-closed" if graph["all_blockers_closed"] else "terminal-blockers-open",
        )
        self.assertEqual(payload["finite_blocker_count"], 5)
        self.assertTrue(payload["blocker_graph_consumed"])
        self.assertEqual(payload["all_terminal_blockers_closed"], graph["all_blockers_closed"])
        self.assertEqual(payload["physics_closed"], graph["physics_closed"])
        self.assertEqual(payload["prediction_ready"], graph["prediction_ready"])
        self.assertTrue(payload["du_l_omega_dynamic_derivation_attempt_available"])
        self.assertTrue(payload["omega_source_no_go_axiom_boundary_available"])
        self.assertTrue(payload["dlogb4vol_measure_law_derivation_attempt_available"])
        self.assertTrue(payload["pressure_pi_omega_extension_blocker_available"])
        self.assertTrue(payload["janus_equations_to_l_omega_law_attempt_available"])
        self.assertTrue(payload["janus_equations_to_dlogb4vol_closure_attempt_available"])
        self.assertTrue(payload["bianchi_minimal_joint_dl_dlogb_solution_available"])
        self.assertTrue(payload["bianchi_minimal_integrability_mirror_gate_available"])
        self.assertTrue(payload["bianchi_minimal_full_connection_lift_system_available"])
        self.assertTrue(payload["bianchi_minimal_mirror_inverse_attempt_available"])
        self.assertTrue(payload["bianchi_minimal_curvature_integrability_system_available"])
        self.assertTrue(payload["flrw_relative_curvature_rows_target_available"])
        self.assertTrue(payload["weakfield_relative_curvature_rows_target_available"])
        self.assertTrue(payload["weakfield_tetrad_connection_target_available"])
        self.assertTrue(payload["janus_source_tetrad_requirements_available"])
        self.assertTrue(payload["janus_weakfield_metric_tetrad_bridge_available"])
        self.assertTrue(payload["janus_weakfield_source_potential_system_available"])
        self.assertTrue(payload["janus_weakfield_phi_psi_qdet_source_closure_attempt_available"])
        self.assertTrue(payload["janus_weakfield_dust_slip_poisson_target_available"])
        self.assertTrue(payload["janus_weakfield_dust_slip_fourier_solver_gate_available"])
        self.assertTrue(payload["janus_weakfield_zero_mode_background_gauge_gate_available"])
        self.assertTrue(payload["janus_weakfield_dust_slip_green_kernel_target_available"])
        self.assertTrue(payload["janus_source_selected_branch_matrix_available"])
        self.assertTrue(payload["janus_weakfield_lgeom_lorentz_no_go_gate_available"])
        self.assertTrue(payload["janus_weakfield_lorentz_projection_derivation_available"])
        self.assertTrue(payload["janus_weakfield_shift_boost_t0i_derivation_available"])
        self.assertTrue(payload["janus_weakfield_g0i_shift_operator_derivation_available"])
        self.assertTrue(payload["janus_pressure_pi0i_transport_gate_available"])
        self.assertTrue(payload["janus_pressure_pi0i_transport_derivation_available"])
        self.assertTrue(payload["janus_g0i_dust_beta_inversion_target_available"])
        self.assertTrue(payload["janus_matter_eos_pi_branch_decision_available"])
        self.assertTrue(payload["janus_eos_pi_source_audit_available"])
        self.assertTrue(payload["janus_conditional_dust_branch_contract_available"])
        self.assertTrue(payload["janus_kinetic_moment_eos_pi_closure_target_available"])
        self.assertTrue(payload["janus_kinetic_moment_hierarchy_equations_available"])
        self.assertTrue(payload["janus_kinetic_closure_routes_decision_available"])
        self.assertTrue(payload["janus_full_vlasov_moment_closure_contract_available"])
        self.assertTrue(payload["janus_pi_zero_preservation_gate_available"])
        self.assertTrue(payload["janus_vlasov_geodesic_force_target_available"])
        self.assertTrue(payload["janus_eos_prho_no_go_vlasov_gate_available"])
        self.assertTrue(payload["janus_metric_tetrad_source_branch_gate_available"])
        self.assertTrue(payload["janus_weakfield_metric_force_probe_available"])
        self.assertTrue(payload["janus_same_l_transport_stack_gate_available"])
        self.assertTrue(payload["janus_phase_space_b4vol_measure_gate_available"])
        self.assertTrue(payload["janus_same_l_1p1_lorentz_probe_available"])
        self.assertTrue(payload["janus_lgeom_tetrad_map_residual_probe_available"])
        self.assertTrue(payload["janus_lgeom_dl_lie_residual_probe_available"])
        self.assertTrue(payload["janus_phase_space_measure_probe_available"])
        self.assertTrue(payload["janus_weakfield_b4vol_product_rule_probe_available"])
        self.assertTrue(payload["source_derived_same_l_dl_residual_closure_target_available"])
        self.assertTrue(payload["dlogb4vol_source_slice_lapse_obligation_ledger_available"])
        self.assertTrue(payload["falpha_source_law_obligation_ledger_available"])
        self.assertTrue(payload["projected_cuu_action_pullback_bridge_ledger_available"])
        self.assertTrue(payload["janus_effective_vlasov_solver_gate_available"])
        self.assertTrue(payload["janus_effective_vlasov_solver_probe_available"])
        self.assertTrue(payload["janus_two_sector_vlasov_poisson_probe_available"])
        self.assertTrue(payload["janus_metric_force_vlasov_step_probe_available"])
        self.assertTrue(payload["janus_two_sector_metric_force_vlasov_probe_available"])
        self.assertTrue(payload["janus_diagnostic_closure_dashboard_available"])
        self.assertTrue(payload["janus_source_residual_closure_obligation_matrix_available"])
        self.assertTrue(payload["bianchi_minimal_curvature_numeric_probe_available"])
        self.assertTrue(payload["curvature_integrability_sparse_pde_probe_available"])
        self.assertTrue(payload["weakfield_curvature_injection_probe_available"])
        self.assertTrue(payload["weakfield_tetrad_pipeline_probe_available"])
        self.assertTrue(payload["bianchi_minimal_same_l_qcross_gate_available"])
        self.assertTrue(payload["mirror_inverse_numeric_residual_probe_available"])
        self.assertTrue(payload["same_l_qcross_numeric_contraction_probe_available"])
        self.assertFalse(payload["all_terminal_blockers_closed"])
        self.assertIn("d_l_transport_law", payload["open_terminal_blockers"])
        self.assertFalse(payload["prediction_ready"])

    def test_terminal_blockers_are_named_and_owned(self) -> None:
        payload = build_payload()
        graph = build_graph_payload()
        blockers = {row["blocker"]: row for row in payload["terminal_blockers"]}
        graph_blockers = {row["blocker"]: row for row in graph["blockers"]}
        graph_name_by_terminal = {
            "d_l_transport_law": "D L transport law",
            "dlogb_4vol_measure_law": "D log B_4vol measure law",
            "source_measure_branch_selection": "source-measure branch selection",
            "matter_extension": "matter extension",
            "observable_chain": "observable chain",
        }

        self.assertIn("d_l_transport_law", blockers)
        self.assertIn("dlogb_4vol_measure_law", blockers)
        self.assertIn("source_measure_branch_selection", blockers)
        self.assertIn("matter_extension", blockers)
        self.assertIn("observable_chain", blockers)
        self.assertTrue(all(row["owned_by"] for row in blockers.values()))
        self.assertTrue(all(row["closure_source"] == "p0_blocker_dependency_graph" for row in blockers.values()))
        for terminal_name, graph_name in graph_name_by_terminal.items():
            self.assertEqual(blockers[terminal_name]["closed"], graph_blockers[graph_name]["closed"])

    def test_available_flags_mirror_blocker_graph(self) -> None:
        payload = build_payload()
        graph = build_graph_payload()
        graph_flags = {key: value for key, value in graph.items() if key.endswith("_available")}

        for key, value in graph_flags.items():
            self.assertEqual(payload[key], value)

    def test_next_action_prioritizes_projected_cuu(self) -> None:
        payload = build_payload()
        actions = " ".join(payload["next_best_actions"])

        self.assertIn("projected Cuu", actions)
        self.assertIn("p0_du_l_omega_dynamic_derivation_attempt", actions)
        self.assertIn("p0_omega_source_no_go_axiom_boundary", actions)
        self.assertIn("p0_dlogb4vol_measure_law_derivation_attempt", actions)
        self.assertIn("p0_pressure_pi_omega_extension_blocker", actions)
        self.assertIn("p0_janus_equations_to_l_omega_law_attempt", actions)
        self.assertIn("p0_janus_equations_to_dlogb4vol_closure_attempt", actions)
        self.assertIn("p0_bianchi_minimal_joint_dl_dlogb_solution", actions)
        self.assertIn("p0_bianchi_minimal_integrability_mirror_gate", actions)
        self.assertIn("p0_bianchi_minimal_full_connection_lift_system", actions)
        self.assertIn("p0_bianchi_minimal_mirror_inverse_attempt", actions)
        self.assertIn("p0_bianchi_minimal_curvature_integrability_system", actions)
        self.assertIn("p0_flrw_relative_curvature_rows_target", actions)
        self.assertIn("p0_weakfield_relative_curvature_rows_target", actions)
        self.assertIn("p0_weakfield_tetrad_connection_target", actions)
        self.assertIn("p0_janus_source_tetrad_requirements", actions)
        self.assertIn("p0_janus_weakfield_metric_tetrad_bridge", actions)
        self.assertIn("p0_janus_weakfield_source_potential_system", actions)
        self.assertIn("p0_janus_weakfield_phi_psi_qdet_source_closure_attempt", actions)
        self.assertIn("p0_janus_weakfield_dust_slip_poisson_target", actions)
        self.assertIn("p0_janus_weakfield_dust_slip_fourier_solver_gate", actions)
        self.assertIn("p0_janus_weakfield_zero_mode_background_gauge_gate", actions)
        self.assertIn("p0_janus_weakfield_dust_slip_green_kernel_target", actions)
        self.assertIn("p0_janus_source_selected_branch_matrix", actions)
        self.assertIn("p0_janus_weakfield_lgeom_lorentz_no_go_gate", actions)
        self.assertIn("p0_janus_weakfield_lorentz_projection_derivation", actions)
        self.assertIn("p0_janus_weakfield_shift_boost_t0i_derivation", actions)
        self.assertIn("p0_janus_weakfield_g0i_shift_operator_derivation", actions)
        self.assertIn("p0_janus_pressure_pi0i_transport_gate", actions)
        self.assertIn("p0_janus_pressure_pi0i_transport_derivation", actions)
        self.assertIn("p0_janus_g0i_dust_beta_inversion_target", actions)
        self.assertIn("p0_janus_matter_eos_pi_branch_decision", actions)
        self.assertIn("p0_janus_eos_pi_source_audit", actions)
        self.assertIn("p0_janus_conditional_dust_branch_contract", actions)
        self.assertIn("p0_janus_kinetic_moment_eos_pi_closure_target", actions)
        self.assertIn("p0_janus_kinetic_moment_hierarchy_equations", actions)
        self.assertIn("p0_janus_kinetic_closure_routes_decision", actions)
        self.assertIn("p0_janus_full_vlasov_moment_closure_contract", actions)
        self.assertIn("p0_janus_pi_zero_preservation_gate", actions)
        self.assertIn("p0_janus_vlasov_geodesic_force_target", actions)
        self.assertIn("p0_janus_eos_prho_no_go_vlasov_gate", actions)
        self.assertIn("p0_janus_metric_tetrad_source_branch_gate", actions)
        self.assertIn("p0_janus_weakfield_metric_force_probe", actions)
        self.assertIn("p0_janus_same_l_transport_stack_gate", actions)
        self.assertIn("p0_janus_phase_space_b4vol_measure_gate", actions)
        self.assertIn("p0_janus_same_l_1p1_lorentz_probe", actions)
        self.assertIn("p0_janus_lgeom_tetrad_map_residual_probe", actions)
        self.assertIn("p0_janus_lgeom_dl_lie_residual_probe", actions)
        self.assertIn("p0_janus_phase_space_measure_probe", actions)
        self.assertIn("p0_janus_weakfield_b4vol_product_rule_probe", actions)
        self.assertIn("p0_shared_phi_j_source_selection_gate", actions)
        self.assertIn("p0_source_derived_same_l_dl_residual_closure_target", actions)
        self.assertIn("p0_dlogb4vol_source_slice_lapse_obligation_ledger", actions)
        self.assertIn("p0_dlogb4vol_jacobian_lapse_slice_identity_target", actions)
        self.assertIn("p0_falpha_source_law_obligation_ledger", actions)
        self.assertIn("p0_falpha_from_jacobian_tetrad_identity_target", actions)
        self.assertIn("p0_projected_cuu_action_pullback_bridge_ledger", actions)
        self.assertIn("p0_cuu_inverse_map_integrability_target", actions)
        self.assertIn("p0_cuu_jacobian_curl_numeric_probe", actions)
        self.assertIn("p0_janus_effective_vlasov_solver_gate", actions)
        self.assertIn("p0_janus_effective_vlasov_solver_probe", actions)
        self.assertIn("p0_janus_two_sector_vlasov_poisson_probe", actions)
        self.assertIn("p0_janus_metric_force_vlasov_step_probe", actions)
        self.assertIn("p0_janus_two_sector_metric_force_vlasov_probe", actions)
        self.assertIn("p0_janus_diagnostic_closure_dashboard", actions)
        self.assertIn("p0_janus_source_residual_closure_obligation_matrix", actions)
        self.assertIn("p0_source_derived_joint_dl_dlogb_residual_substitution_target", actions)
        self.assertIn("p0_bianchi_minimal_curvature_numeric_probe", actions)
        self.assertIn("p0_curvature_integrability_sparse_pde_probe", actions)
        self.assertIn("p0_weakfield_curvature_injection_probe", actions)
        self.assertIn("p0_weakfield_tetrad_pipeline_probe", actions)
        self.assertIn("p0_bianchi_minimal_same_l_qcross_gate", actions)
        self.assertIn("p0_mirror_inverse_numeric_residual_probe", actions)
        self.assertIn("p0_same_l_qcross_numeric_contraction_probe", actions)
        self.assertIn("D L and D log B", actions)
        self.assertIn("observable_chain", actions)
        self.assertIn("ledger-driven", payload["verdict"])
        self.assertIn("same-L/DL", payload["verdict"])
        self.assertIn("R_plus/R_minus", payload["verdict"])


if __name__ == "__main__":
    unittest.main()
