import Mathlib

namespace JanusFormal
namespace P0EFTJanusClosedThreeDimensionalLogNoGo

set_option autoImplicit false

/-- Local heat-kernel coefficients through the dimension-three slot. -/
structure ClosedThreeDimensionalHeatData where
  a0 : ℝ
  a1 : ℝ
  a2 : ℝ
  a3 : ℝ
  oddCoefficientOneVanishes : a1 = 0
  oddCoefficientThreeVanishes : a3 = 0

/-- The local logarithmic coefficient in dimension three is the `a3` slot. -/
def localLogarithmicCoefficient
    (s : ClosedThreeDimensionalHeatData) : ℝ :=
  s.a3

/-- On a closed smooth three-manifold, the local logarithmic coefficient vanishes. -/
theorem closed_three_dimensional_log_coefficient_vanishes
    (s : ClosedThreeDimensionalHeatData) :
    localLogarithmicCoefficient s = 0 := by
  exact s.oddCoefficientThreeVanishes

/-- Model of local renormalization-scale dependence of a one-loop determinant. -/
def localScaleDerivative
    (s : ClosedThreeDimensionalHeatData)
    (normalization : ℝ) : ℝ :=
  normalization * localLogarithmicCoefficient s

/-- No local logarithmic running is generated by the free closed-manifold determinant. -/
theorem free_closed_determinant_has_zero_local_scale_derivative
    (s : ClosedThreeDimensionalHeatData)
    (normalization : ℝ) :
    localScaleDerivative s normalization = 0 := by
  unfold localScaleDerivative
  rw [closed_three_dimensional_log_coefficient_vanishes]
  ring

/-- PT pairing still leaves the local logarithmic coefficient zero. -/
theorem pt_pair_does_not_create_logarithmic_coefficient
    (s : ClosedThreeDimensionalHeatData) :
    2 * localLogarithmicCoefficient s = 0 := by
  rw [closed_three_dimensional_log_coefficient_vanishes]
  ring

/-- A free local heat-kernel anomaly cannot be the dimensional-transmutation source. -/
def FreeLocalHeatTransmutation
    (s : ClosedThreeDimensionalHeatData) : Prop :=
  localLogarithmicCoefficient s ≠ 0

/-- The free local transmutation mechanism is blocked on the closed throat. -/
theorem free_local_heat_transmutation_blocked
    (s : ClosedThreeDimensionalHeatData) :
    Not (FreeLocalHeatTransmutation s) := by
  unfold FreeLocalHeatTransmutation
  rw [closed_three_dimensional_log_coefficient_vanishes]
  exact not_false_eq_true.mpr rfl

/--
The absence of a local logarithmic coefficient does not make the determinant
constant: finite nonlocal winding/Casimir terms may still depend on the circle
modulus.  It only blocks dimensional transmutation from the free local anomaly.
-/
structure ThreeDimensionalScaleGenerationExitStatus where
  interactingMarginalCouplingRuns : Prop
  boundaryOrDefectCoefficientPresent : Prop
  singularGeometryCoefficientPresent : Prop
  bulkUVMatchingProvidesScale : Prop
  nonperturbativeGapEquationProvidesScale : Prop
  atLeastOneScaleExitDerived : Prop


def threeDimensionalScaleGenerationExitClosed
    (s : ThreeDimensionalScaleGenerationExitStatus) : Prop :=
  (s.interactingMarginalCouplingRuns \/
    s.boundaryOrDefectCoefficientPresent \/
    s.singularGeometryCoefficientPresent \/
    s.bulkUVMatchingProvidesScale \/
    s.nonperturbativeGapEquationProvidesScale) /\
  s.atLeastOneScaleExitDerived

/--
For Program D the clean exits are therefore an interacting world-volume beta
function, a genuine bridge/defect contribution, or microscopic bulk matching.
The normalized free Dirac heat kernel alone cannot fix the absolute scale.
-/
structure ClosedThreeDimensionalEffectiveActionStatus where
  throatClosedAndSmoothProved : Prop
  oddHeatCoefficientsVanishProved : Prop
  freeLocalLogRunningExcluded : Prop
  finiteNonlocalDeterminantComputed : Prop
  interactingOrBoundaryScaleMechanismDerived : Prop
  absoluteScaleDerived : Prop


def closedThreeDimensionalEffectiveActionClosed
    (s : ClosedThreeDimensionalEffectiveActionStatus) : Prop :=
  s.throatClosedAndSmoothProved /\
  s.oddHeatCoefficientsVanishProved /\
  s.freeLocalLogRunningExcluded /\
  s.finiteNonlocalDeterminantComputed /\
  s.interactingOrBoundaryScaleMechanismDerived /\
  s.absoluteScaleDerived

end P0EFTJanusClosedThreeDimensionalLogNoGo
end JanusFormal
