import Mathlib
import JanusFormal.Branches.FundamentalGeometryPEJetUniversality.Gates.P0EFTJanusRieszShapeOperatorProjectedSeedPhysicalRangeBridge

namespace JanusFormal
namespace P0EFTJanusRieszShapeOperatorProjectedSeedOrthogonalRange

set_option autoImplicit false

noncomputable section

open Set Module
open scoped ContDiff InnerProductSpace
open P0EFTJanusSmoothAdaptedFrame
open P0EFTJanusRieszShapeOperatorProjectedSeedAtlas
open P0EFTJanusRieszShapeOperatorPointwiseNormalBasisCover
open P0EFTJanusRieszShapeOperatorProjectedSeedSynthesisSmoothness
open P0EFTJanusRieszShapeOperatorProjectedSeedPhysicalRangeBridge

universe u v w x

variable {Base : Type w} {Model : Type u} {Ambient : Type v}
variable [NormedAddCommGroup Base] [NormedSpace ℝ Base]
variable [NormedAddCommGroup Model] [InnerProductSpace ℝ Model]
variable [NormedAddCommGroup Ambient] [InnerProductSpace ℝ Ambient]
variable [FiniteDimensional ℝ Model]
variable [FiniteDimensional ℝ Ambient]

variable {ι κ : Type x}
variable [Fintype ι] [Fintype κ]
variable [LinearOrder κ] [LocallyFiniteOrderBot κ] [WellFoundedLT κ]

/-- Ambient tangent subspace generated by the supplied tangent orthonormal frame. -/
def tangentFrameSpan
    (basisData : PointwiseNormalBasisData Base Ambient ι κ)
    (base : Base) : Submodule ℝ Ambient :=
  Submodule.span ℝ (Set.range (fun i => basisData.tangentFrame i base))

/-- Ambient subspace generated by the projected-seed Gram--Schmidt normal frame. -/
def projectedSeedNormalSpan
    (basisData : PointwiseNormalBasisData Base Ambient ι κ)
    (center base : Base) : Submodule ℝ Ambient :=
  Submodule.span ℝ
    (Set.range (fun k => projectedSeedNormalFrame
      basisData.tangentFrame (pointwiseNormalSeedCharts basisData)
      center k base))

/-- Gram--Schmidt normalization does not change the span of the projected normal
seed family. -/
theorem projectedSeedNormalSpan_eq_projectedNormalFamilySpan
    (basisData : PointwiseNormalBasisData Base Ambient ι κ)
    (center base : Base) :
    projectedSeedNormalSpan basisData center base =
      Submodule.span ℝ
        (Set.range (fun k => projectedNormalFamily
          basisData.tangentFrame
          (pointwiseNormalSeedCharts basisData).seed center k base)) := by
  change Submodule.span ℝ
      (Set.range (InnerProductSpace.gramSchmidtNormed ℝ
        (fun k => projectedNormalFamily basisData.tangentFrame
          (pointwiseNormalSeedCharts basisData).seed center k base))) =
    Submodule.span ℝ
      (Set.range (fun k => projectedNormalFamily basisData.tangentFrame
        (pointwiseNormalSeedCharts basisData).seed center k base))
  rw [InnerProductSpace.span_gramSchmidtNormed_range,
    InnerProductSpace.span_gramSchmidt]

/-- Every projected-seed normal vector belongs to the orthogonal complement of
the tangent span. -/
theorem projectedSeedNormalSpan_le_tangentFrameSpan_orthogonal
    (basisData : PointwiseNormalBasisData Base Ambient ι κ)
    (center base : Base) :
    projectedSeedNormalSpan basisData center base ≤
      (tangentFrameSpan basisData base)ᗮ := by
  apply Submodule.span_le.2
  rintro normal ⟨k, rfl⟩
  have hTangentOrthoSingleton :
      tangentFrameSpan basisData base ⟂
        (ℝ ∙ projectedSeedNormalFrame basisData.tangentFrame
          (pointwiseNormalSeedCharts basisData) center k base) := by
    unfold tangentFrameSpan
    apply Submodule.span_le.2
    rintro tangent ⟨i, rfl⟩
    rw [Submodule.mem_orthogonal_singleton_iff_inner_right]
    exact tangent_inner_projectedSeedNormalFrame_eq_zero
      basisData.tangentFrame (pointwiseNormalSeedCharts basisData)
      basisData.tangent_orthonormal center base i k
  exact hTangentOrthoSingleton.symm
    (Submodule.mem_span_singleton_self _)

/-- The tangent span has the expected dimension. -/
theorem tangentFrameSpan_finrank
    (basisData : PointwiseNormalBasisData Base Ambient ι κ)
    (base : Base) :
    finrank ℝ (tangentFrameSpan basisData base) = Fintype.card ι := by
  unfold tangentFrameSpan
  exact finrank_span_eq_card
    (basisData.tangent_orthonormal base).linearIndependent

/-- On a valid projected-seed chart, the normal span has the expected dimension. -/
theorem projectedSeedNormalSpan_finrank
    (basisData : PointwiseNormalBasisData Base Ambient ι κ)
    (center base : Base)
    (hValid : projectedSeedChartValid basisData.tangentFrame
      (pointwiseNormalSeedCharts basisData) center base) :
    finrank ℝ (projectedSeedNormalSpan basisData center base) =
      Fintype.card κ := by
  unfold projectedSeedNormalSpan
  exact finrank_span_eq_card
    (projectedSeedNormalFrame_orthonormal basisData.tangentFrame
      (pointwiseNormalSeedCharts basisData) center base hValid).linearIndependent

/-- Under the ambient dimension identity, the orthogonal complement of the
tangent span has the normal cardinality. -/
theorem tangentFrameSpan_orthogonal_finrank
    (basisData : PointwiseNormalBasisData Base Ambient ι κ)
    (hDimension : Fintype.card ι + Fintype.card κ = finrank ℝ Ambient)
    (base : Base) :
    finrank ℝ (tangentFrameSpan basisData base)ᗮ = Fintype.card κ := by
  apply Submodule.finrank_add_finrank_orthogonal'
  rw [tangentFrameSpan_finrank basisData base]
  exact hDimension

/-- Main range theorem: on every valid chart, the projected-seed Gram--Schmidt
normal frame spans exactly the physical normal subspace defined as the
orthogonal complement of the tangent span. -/
theorem projectedSeedNormalSpan_eq_tangentFrameSpan_orthogonal
    (basisData : PointwiseNormalBasisData Base Ambient ι κ)
    (hDimension : Fintype.card ι + Fintype.card κ = finrank ℝ Ambient)
    (center base : Base)
    (hValid : projectedSeedChartValid basisData.tangentFrame
      (pointwiseNormalSeedCharts basisData) center base) :
    projectedSeedNormalSpan basisData center base =
      (tangentFrameSpan basisData base)ᗮ := by
  apply Submodule.eq_of_le_of_finrank_eq
  · exact projectedSeedNormalSpan_le_tangentFrameSpan_orthogonal
      basisData center base
  · rw [projectedSeedNormalSpan_finrank basisData center base hValid,
      tangentFrameSpan_orthogonal_finrank basisData hDimension base]

/-- Any physical normal frame whose physical range is the tangent orthogonal
complement automatically satisfies the projected-seed range identification
obligation. -/
def projectedSeedPhysicalRangeIdentificationOfOrthogonal
    (coordinateBasis : Basis κ ℝ Model)
    (hCoordinateOrthonormal : Orthonormal ℝ coordinateBasis)
    (basisData : PointwiseNormalBasisData Base Ambient ι κ)
    (hDimension : Fintype.card ι + Fintype.card κ = finrank ℝ Ambient)
    (center : Base)
    (physical : PhysicalNormalFrameOn
      (Model := Model) basisData center)
    (hPhysicalRange :
      ∀ base,
        projectedSeedChartValid basisData.tangentFrame
          (pointwiseNormalSeedCharts basisData) center base →
        (tangentFrameSpan basisData base)ᗮ = physical.physicalRange base) :
    ProjectedSeedPhysicalRangeIdentification
      coordinateBasis hCoordinateOrthonormal basisData center physical where
  projected_range_eq := by
    intro base hValid
    exact (projectedSeedNormalSpan_eq_tangentFrameSpan_orthogonal
      basisData hDimension center base hValid).trans
        (hPhysicalRange base hValid)

/-- The projected-seed Gram--Schmidt frame itself is a smooth physical normal
frame for the orthogonal-complement definition of the normal bundle. -/
def projectedSeedOrthogonalPhysicalNormalFrameOn
    (coordinateBasis : Basis κ ℝ Model)
    (hCoordinateOrthonormal : Orthonormal ℝ coordinateBasis)
    (basisData : PointwiseNormalBasisData Base Ambient ι κ)
    (hDimension : Fintype.card ι + Fintype.card κ = finrank ℝ Ambient)
    (center : Base) :
    PhysicalNormalFrameOn (Model := Model) basisData center where
  frame := pointwiseBasisSmoothNormalFrameFamilyOn coordinateBasis
    hCoordinateOrthonormal basisData center
  physicalRange := fun base => (tangentFrameSpan basisData base)ᗮ
  frame_range_eq := by
    intro base hValid
    rw [pointwiseBasisSmoothNormalFrameFamilyOn_range
      coordinateBasis hCoordinateOrthonormal basisData center base hValid]
    exact projectedSeedNormalSpan_eq_tangentFrameSpan_orthogonal
      basisData hDimension center base hValid

/-- Canonical range identification for the orthogonal-complement physical normal
frame. -/
def projectedSeedOrthogonalRangeIdentification
    (coordinateBasis : Basis κ ℝ Model)
    (hCoordinateOrthonormal : Orthonormal ℝ coordinateBasis)
    (basisData : PointwiseNormalBasisData Base Ambient ι κ)
    (hDimension : Fintype.card ι + Fintype.card κ = finrank ℝ Ambient)
    (center : Base) :
    ProjectedSeedPhysicalRangeIdentification coordinateBasis
      hCoordinateOrthonormal basisData center
      (projectedSeedOrthogonalPhysicalNormalFrameOn coordinateBasis
        hCoordinateOrthonormal basisData hDimension center) where
  projected_range_eq := by
    intro base hValid
    exact projectedSeedNormalSpan_eq_tangentFrameSpan_orthogonal
      basisData hDimension center base hValid

/-- The canonical transition from projected-seed coordinates to the canonical
orthogonal physical frame acts as the identity on every valid chart point. -/
theorem projectedSeedOrthogonalNormalTransition_apply
    (coordinateBasis : Basis κ ℝ Model)
    (hCoordinateOrthonormal : Orthonormal ℝ coordinateBasis)
    (basisData : PointwiseNormalBasisData Base Ambient ι κ)
    (hDimension : Fintype.card ι + Fintype.card κ = finrank ℝ Ambient)
    (center base : Base)
    (hValid : projectedSeedChartValid basisData.tangentFrame
      (pointwiseNormalSeedCharts basisData) center base)
    (normal : Model) :
    (projectedSeedToPhysicalNormalTransition coordinateBasis
      hCoordinateOrthonormal basisData center
      (projectedSeedOrthogonalPhysicalNormalFrameOn coordinateBasis
        hCoordinateOrthonormal basisData hDimension center)
      (projectedSeedOrthogonalRangeIdentification coordinateBasis
        hCoordinateOrthonormal basisData hDimension center)).frame base normal =
      normal := by
  apply ((pointwiseBasisSmoothNormalFrameFamilyOn coordinateBasis
    hCoordinateOrthonormal basisData center).frame base).injective
  exact projectedSeedToPhysicalNormalTransition_spec coordinateBasis
    hCoordinateOrthonormal basisData center
    (projectedSeedOrthogonalPhysicalNormalFrameOn coordinateBasis
      hCoordinateOrthonormal basisData hDimension center)
    (projectedSeedOrthogonalRangeIdentification coordinateBasis
      hCoordinateOrthonormal basisData hDimension center)
    base hValid normal

/-- Status after identifying the projected normal span with the tangent
orthogonal complement. -/
structure ProjectedSeedOrthogonalRangeStatus where
  tangentSpanDefined : Prop
  projectedNormalSpanDefined : Prop
  gramSchmidtSpanPreserved : Prop
  normalSpanOrthogonalToTangent : Prop
  tangentFinrankComputed : Prop
  normalFinrankComputed : Prop
  orthogonalFinrankComputed : Prop
  projectedNormalEqualsOrthogonal : Prop
  physicalRangeIdentificationConstructed : Prop
  canonicalPhysicalFrameConstructed : Prop

/-- Closure of the orthogonal-range stage. -/
def projectedSeedOrthogonalRangeClosed
    (s : ProjectedSeedOrthogonalRangeStatus) : Prop :=
  s.tangentSpanDefined ∧
  s.projectedNormalSpanDefined ∧
  s.gramSchmidtSpanPreserved ∧
  s.normalSpanOrthogonalToTangent ∧
  s.tangentFinrankComputed ∧
  s.normalFinrankComputed ∧
  s.orthogonalFinrankComputed ∧
  s.projectedNormalEqualsOrthogonal ∧
  s.physicalRangeIdentificationConstructed ∧
  s.canonicalPhysicalFrameConstructed

/-- After the orthogonal-range theorem, the remaining geometric work is the
tangent-side frame connection and the actual Riesz coefficient instantiation. -/
theorem missing_tangent_connection_not_a_normal_range_obstruction
    (s : ProjectedSeedOrthogonalRangeStatus)
    (hClosed : projectedSeedOrthogonalRangeClosed s) :
    s.projectedNormalEqualsOrthogonal ∧
      s.physicalRangeIdentificationConstructed :=
  ⟨hClosed.2.2.2.2.2.2.2.1, hClosed.2.2.2.2.2.2.2.2.1⟩

end

end P0EFTJanusRieszShapeOperatorProjectedSeedOrthogonalRange
end JanusFormal
