import Mathlib

namespace JanusFormal
namespace P0EFTJanusSecondJetNormalForm

set_option autoImplicit false

universe u v

/-- Algebraic model of a second immersion jet after the first derivative has
been normalized to the standard tangent inclusion. The two components model the
tangential and normal parts of the quadratic term. -/
@[ext]
structure SecondJetData (Tangential : Type u) (Normal : Type v) where
  tangentialQuadratic : Tangential
  normalQuadratic : Normal

/-- A quadratic source-coordinate change translates the tangential quadratic
component and leaves the normal component unchanged. -/
def sourceQuadraticChange
    {Tangential : Type u}
    {Normal : Type v}
    [Add Tangential]
    (change : Tangential)
    (jet : SecondJetData Tangential Normal) :
    SecondJetData Tangential Normal where
  tangentialQuadratic := jet.tangentialQuadratic + change
  normalQuadratic := jet.normalQuadratic

/-- Canonical representative obtained by deleting the tangential quadratic
component. Geometrically, the surviving normal term is the model for the second
fundamental form. -/
def normalForm
    {Tangential : Type u}
    {Normal : Type v}
    [Zero Tangential]
    (jet : SecondJetData Tangential Normal) :
    SecondJetData Tangential Normal where
  tangentialQuadratic := 0
  normalQuadratic := jet.normalQuadratic

/-- Orbit relation generated by quadratic source-coordinate changes. -/
def EquivalentBySourceChange
    {Tangential : Type u}
    {Normal : Type v}
    [Add Tangential]
    (first second : SecondJetData Tangential Normal) : Prop :=
  ∃ change : Tangential,
    sourceQuadraticChange change first = second

/-- The explicit source change `-Q^top` kills the tangential quadratic term. -/
theorem chosen_change_reaches_normal_form
    {Tangential : Type u}
    {Normal : Type v}
    [AddGroup Tangential]
    (jet : SecondJetData Tangential Normal) :
    sourceQuadraticChange (-jet.tangentialQuadratic) jet =
      normalForm jet := by
  ext <;> simp [sourceQuadraticChange, normalForm]

/-- The normal quadratic component is unchanged by every source-coordinate
change. -/
theorem normal_component_is_invariant
    {Tangential : Type u}
    {Normal : Type v}
    [Add Tangential]
    (change : Tangential)
    (jet : SecondJetData Tangential Normal) :
    (sourceQuadraticChange change jet).normalQuadratic =
      jet.normalQuadratic :=
  rfl

/-- Complete orbit classification of the abstract normalized second-jet model:
two jets differ by a quadratic source reparametrization exactly when their normal
quadratic components agree. -/
theorem equivalent_iff_normal_eq
    {Tangential : Type u}
    {Normal : Type v}
    [AddGroup Tangential]
    (first second : SecondJetData Tangential Normal) :
    EquivalentBySourceChange first second ↔
      first.normalQuadratic = second.normalQuadratic := by
  constructor
  · rintro ⟨change, hChange⟩
    have hNormal := congrArg SecondJetData.normalQuadratic hChange
    simpa [sourceQuadraticChange] using hNormal
  · intro hNormal
    refine ⟨-first.tangentialQuadratic + second.tangentialQuadratic, ?_⟩
    ext
    · simp [sourceQuadraticChange]
    · simpa [sourceQuadraticChange] using hNormal

@[refl]
theorem equivalent_refl
    {Tangential : Type u}
    {Normal : Type v}
    [AddGroup Tangential]
    (jet : SecondJetData Tangential Normal) :
    EquivalentBySourceChange jet jet :=
  (equivalent_iff_normal_eq jet jet).2 rfl

@[symm]
theorem equivalent_symm
    {Tangential : Type u}
    {Normal : Type v}
    [AddGroup Tangential]
    {first second : SecondJetData Tangential Normal}
    (hEquivalent : EquivalentBySourceChange first second) :
    EquivalentBySourceChange second first :=
  (equivalent_iff_normal_eq second first).2
    ((equivalent_iff_normal_eq first second).1 hEquivalent).symm

@[trans]
theorem equivalent_trans
    {Tangential : Type u}
    {Normal : Type v}
    [AddGroup Tangential]
    {first second third : SecondJetData Tangential Normal}
    (hFirst : EquivalentBySourceChange first second)
    (hSecond : EquivalentBySourceChange second third) :
    EquivalentBySourceChange first third := by
  apply (equivalent_iff_normal_eq first third).2
  exact ((equivalent_iff_normal_eq first second).1 hFirst).trans
    ((equivalent_iff_normal_eq second third).1 hSecond)

/-- Every orbit meets the zero-tangential slice. -/
theorem every_orbit_meets_normal_slice
    {Tangential : Type u}
    {Normal : Type v}
    [AddGroup Tangential]
    (jet : SecondJetData Tangential Normal) :
    EquivalentBySourceChange jet (normalForm jet) := by
  exact ⟨-jet.tangentialQuadratic,
    chosen_change_reaches_normal_form jet⟩

/-- The intersection of an orbit with the zero-tangential slice is unique. -/
theorem normal_slice_representative_unique
    {Tangential : Type u}
    {Normal : Type v}
    [AddGroup Tangential]
    {first second : SecondJetData Tangential Normal}
    (hFirstNormal : first.tangentialQuadratic = 0)
    (hSecondNormal : second.tangentialQuadratic = 0)
    (hEquivalent : EquivalentBySourceChange first second) :
    first = second := by
  apply SecondJetData.ext
  · exact hFirstNormal.trans hSecondNormal.symm
  · exact (equivalent_iff_normal_eq first second).1 hEquivalent

/-- This theorem proves only the algebraic orbit reduction after a first-order
normalization. The geometric identification with an actual immersion jet still
requires adapted coordinates, tensor symmetries and residual frame actions. -/
structure GeometricSecondJetReductionStatus where
  firstDerivativeNormalized : Prop
  tangentialNormalSplittingConstructed : Prop
  sourceQuadraticActionIdentified : Prop
  algebraicOrbitReductionProved : Prop
  tensorSymmetryIdentified : Prop
  residualOrthogonalActionIdentified : Prop
  geometricSecondFundamentalFormIdentified : Prop

/-- Closure of the genuine geometric second-jet normal-form theorem. -/
def geometricSecondJetReductionClosed
    (s : GeometricSecondJetReductionStatus) : Prop :=
  s.firstDerivativeNormalized /\
  s.tangentialNormalSplittingConstructed /\
  s.sourceQuadraticActionIdentified /\
  s.algebraicOrbitReductionProved /\
  s.tensorSymmetryIdentified /\
  s.residualOrthogonalActionIdentified /\
  s.geometricSecondFundamentalFormIdentified

/-- The abstract additive orbit theorem is insufficient until the actual jet
action has been identified geometrically. -/
theorem missing_source_action_identification_blocks_geometric_reduction
    (s : GeometricSecondJetReductionStatus)
    (hMissing : Not s.sourceQuadraticActionIdentified) :
    Not (geometricSecondJetReductionClosed s) := by
  intro hClosed
  exact hMissing hClosed.2.2.1

end P0EFTJanusSecondJetNormalForm
end JanusFormal
