import JanusFormal.Branches.FundamentalGeometryPEJetUniversality.Gates.P0EFTJanusConcreteSecondJetChainRule
import JanusFormal.Branches.FundamentalGeometryPEJetUniversality.Gates.P0EFTJanusConcreteAbelianConnectionJet

namespace JanusFormal
namespace P0EFTJanusLowOrderStructuredBackground

set_option autoImplicit false

universe u v w x

open P0EFTJanusConcreteSecondJetChainRule
open P0EFTJanusConcreteAbelianConnectionJet

/-- First combined low-order structured background: a normalized immersion
second jet together with an abelian connection first jet. -/
@[ext]
structure LowOrderStructuredJet (Tangent : Type u) (Normal : Type v) where
  immersion : SplitImmersionSecondJet Tangent Normal
  connection : ConcreteConnectionOneJet Tangent

/-- Reduced quotient data. The curvature field carries its alternating identity,
which is exactly the realizability condition for the curvature slice below. -/
@[ext]
structure LowOrderReducedData (Tangent : Type u) (Normal : Type v) where
  secondFundamental : Tangent → Tangent → Normal
  gaugeCurvature : Tangent → Tangent → ℝ
  gaugeCurvature_alternating :
    ∀ x y, gaugeCurvature y x = -gaugeCurvature x y

/-- Quotient map from the unreduced low-order structured jet to `(B,F)`. -/
def reduceLowOrderJet
    {Tangent : Type u}
    {Normal : Type v}
    (jet : LowOrderStructuredJet Tangent Normal) :
    LowOrderReducedData Tangent Normal where
  secondFundamental := jet.immersion.normalQuadratic
  gaugeCurvature := curvature jet.connection
  gaugeCurvature_alternating := curvature_swap jet.connection

/-- Canonical representative of reduced data: zero tangential immersion
quadratic term, zero connection value, and derivative equal to one half of the
alternating curvature tensor. -/
def reducedSlice
    {Tangent : Type u}
    {Normal : Type v}
    [Zero Tangent]
    (data : LowOrderReducedData Tangent Normal) :
    LowOrderStructuredJet Tangent Normal where
  immersion :=
    { tangentialQuadratic := 0
      normalQuadratic := data.secondFundamental }
  connection :=
    { value := 0
      derivative := fun x y => data.gaugeCurvature x y / 2 }

/-- The canonical slice is a section of the quotient map. -/
theorem reduce_reducedSlice
    {Tangent : Type u}
    {Normal : Type v}
    [Zero Tangent]
    (data : LowOrderReducedData Tangent Normal) :
    reduceLowOrderJet (reducedSlice data) = data := by
  apply LowOrderReducedData.ext
  · rfl
  · funext x y
    have hAlternating := data.gaugeCurvature_alternating x y
    simp only [reduceLowOrderJet, reducedSlice, curvature]
    rw [hAlternating]
    ring

/-- Product orbit relation generated by quadratic source reparametrizations and
abelian gauge two-jets. -/
def CombinedEquivalent
    {Tangent : Type u}
    {Normal : Type v}
    [Add Tangent]
    [AddMonoid Normal]
    (first second : LowOrderStructuredJet Tangent Normal) : Prop :=
  EquivalentByQuadraticPrecomposition
      first.immersion second.immersion /\
    ConcreteGaugeEquivalent first.connection second.connection

/-- Exact classification of the combined low-order orbit relation by `(B,F)`. -/
theorem combined_equivalent_iff_reduced_eq
    {Tangent : Type u}
    {Normal : Type v}
    [AddGroup Tangent]
    [AddMonoid Normal]
    (first second : LowOrderStructuredJet Tangent Normal) :
    CombinedEquivalent first second ↔
      reduceLowOrderJet first = reduceLowOrderJet second := by
  constructor
  · rintro ⟨hImmersion, hConnection⟩
    apply LowOrderReducedData.ext
    · exact
        (concrete_equivalent_iff_normal_eq
          first.immersion second.immersion).1 hImmersion
    · exact
        (concrete_gauge_equivalent_iff_curvature_eq
          first.connection second.connection).1 hConnection
  · intro hReduced
    constructor
    · apply
        (concrete_equivalent_iff_normal_eq
          first.immersion second.immersion).2
      exact congrArg LowOrderReducedData.secondFundamental hReduced
    · apply
        (concrete_gauge_equivalent_iff_curvature_eq
          first.connection second.connection).2
      exact congrArg LowOrderReducedData.gaugeCurvature hReduced

/-- Every low-order structured jet is orbit-equivalent to the canonical
representative of its reduced `(B,F)` data. -/
theorem equivalent_to_reducedSlice
    {Tangent : Type u}
    {Normal : Type v}
    [AddGroup Tangent]
    [AddMonoid Normal]
    (jet : LowOrderStructuredJet Tangent Normal) :
    CombinedEquivalent jet (reducedSlice (reduceLowOrderJet jet)) := by
  apply (combined_equivalent_iff_reduced_eq _ _).2
  exact reduce_reducedSlice (reduceLowOrderJet jet)

/-- An observable is invariant under the combined orbit directions when it is
constant on `CombinedEquivalent` pairs. -/
def IsCombinedInvariant
    {Tangent : Type u}
    {Normal : Type v}
    {Target : Type w}
    [Add Tangent]
    [AddMonoid Normal]
    (observable : LowOrderStructuredJet Tangent Normal → Target) : Prop :=
  ∀ first second,
    CombinedEquivalent first second →
      observable first = observable second

/-- Restriction of an observable to the canonical `(B,F)` slice. -/
def reducedObservable
    {Tangent : Type u}
    {Normal : Type v}
    {Target : Type w}
    [Zero Tangent]
    (observable : LowOrderStructuredJet Tangent Normal → Target) :
    LowOrderReducedData Tangent Normal → Target :=
  fun data => observable (reducedSlice data)

/-- Combined source/gauge invariance forces factorization through `(B,F)`. -/
theorem combined_invariant_factors_through_reduced
    {Tangent : Type u}
    {Normal : Type v}
    {Target : Type w}
    [AddGroup Tangent]
    [AddMonoid Normal]
    (observable : LowOrderStructuredJet Tangent Normal → Target)
    (hInvariant : IsCombinedInvariant observable) :
    ∀ jet,
      observable jet =
        reducedObservable observable (reduceLowOrderJet jet) := by
  intro jet
  exact hInvariant jet (reducedSlice (reduceLowOrderJet jet))
    (equivalent_to_reducedSlice jet)

/-- Every function of `(B,F)` defines a combined-orbit-invariant observable. -/
theorem reduced_factorization_is_combined_invariant
    {Tangent : Type u}
    {Normal : Type v}
    {Target : Type w}
    [AddGroup Tangent]
    [AddMonoid Normal]
    (reduced : LowOrderReducedData Tangent Normal → Target) :
    IsCombinedInvariant
      (fun jet : LowOrderStructuredJet Tangent Normal =>
        reduced (reduceLowOrderJet jet)) := by
  intro first second hEquivalent
  rw [(combined_equivalent_iff_reduced_eq first second).1 hEquivalent]

/-- Universal quotient property: combined invariance is equivalent to
factorization through the reduced `(B,F)` data. -/
theorem combined_invariant_iff_factors_through_reduced
    {Tangent : Type u}
    {Normal : Type v}
    {Target : Type w}
    [AddGroup Tangent]
    [AddMonoid Normal]
    (observable : LowOrderStructuredJet Tangent Normal → Target) :
    IsCombinedInvariant observable ↔
      ∃ reduced : LowOrderReducedData Tangent Normal → Target,
        ∀ jet, observable jet = reduced (reduceLowOrderJet jet) := by
  constructor
  · intro hInvariant
    exact ⟨reducedObservable observable,
      combined_invariant_factors_through_reduced observable hInvariant⟩
  · rintro ⟨reduced, hFactor⟩
    intro first second hEquivalent
    rw [hFactor first, hFactor second]
    exact congrArg reduced
      ((combined_equivalent_iff_reduced_eq first second).1 hEquivalent)

/-- The reduced observable is unique. Hence `(B,F)` has the universal property
of the combined low-order orbit quotient in this algebraic model. -/
theorem combined_invariant_has_unique_reduction
    {Tangent : Type u}
    {Normal : Type v}
    {Target : Type w}
    [AddGroup Tangent]
    [AddMonoid Normal]
    (observable : LowOrderStructuredJet Tangent Normal → Target)
    (hInvariant : IsCombinedInvariant observable) :
    ∃! reduced : LowOrderReducedData Tangent Normal → Target,
      ∀ jet, observable jet = reduced (reduceLowOrderJet jet) := by
  refine ⟨reducedObservable observable,
    combined_invariant_factors_through_reduced observable hInvariant, ?_⟩
  intro other hOther
  funext data
  have hAtSlice := hOther (reducedSlice data)
  calc
    reducedObservable observable data =
        observable (reducedSlice data) := by
      rfl
    _ = other (reduceLowOrderJet (reducedSlice data)) := hAtSlice
    _ = other data := by rw [reduce_reducedSlice]

section ResidualReducedAction

variable {TangentGroup : Type w}
variable {NormalGroup : Type x}
variable {Tangent : Type u}
variable {Normal : Type v}
variable [Group TangentGroup]
variable [Group NormalGroup]
variable [MulAction TangentGroup Tangent]
variable [MulAction NormalGroup Normal]

/-- Residual tangent/normal frame action on the reduced low-order background. -/
def actOnReducedData
    (frame : TangentGroup × NormalGroup)
    (data : LowOrderReducedData Tangent Normal) :
    LowOrderReducedData Tangent Normal where
  secondFundamental :=
    actOnNormalTensor frame data.secondFundamental
  gaugeCurvature :=
    pullbackTwoForm frame.1 data.gaugeCurvature
  gaugeCurvature_alternating := by
    intro x y
    simp only [pullbackTwoForm]
    rw [data.gaugeCurvature_alternating]

@[simp]
theorem actOnReducedData_one
    (data : LowOrderReducedData Tangent Normal) :
    actOnReducedData
        (1 : TangentGroup × NormalGroup) data = data := by
  apply LowOrderReducedData.ext
  · exact actOnNormalTensor_one data.secondFundamental
  · exact pullbackTwoForm_one data.gaugeCurvature

@[simp]
theorem actOnReducedData_mul
    (first second : TangentGroup × NormalGroup)
    (data : LowOrderReducedData Tangent Normal) :
    actOnReducedData (first * second) data =
      actOnReducedData first (actOnReducedData second data) := by
  apply LowOrderReducedData.ext
  · exact actOnNormalTensor_mul first second data.secondFundamental
  · exact pullbackTwoForm_mul first.1 second.1 data.gaugeCurvature

end ResidualReducedAction

/-- Boundary between the first exact combined quotient and the genuine smooth
Janus structured background. -/
structure LowOrderStructuredBackgroundStatus where
  concreteImmersionOrbitClassified : Prop
  concreteConnectionOrbitClassified : Prop
  combinedOrbitClassifiedBySecondFundamentalAndCurvature : Prop
  universalInvariantFactorizationProved : Prop
  residualActionOnReducedDataConstructed : Prop
  finiteDimensionalTensorModelsInserted : Prop
  adaptedOrthogonalSpinCFramesConstructed : Prop
  smoothStructuredJetBaseConstructed : Prop
  globalSpinCAndHolonomySectorsReattached : Prop

/-- Closure of the first genuine Janus structured-background quotient theorem. -/
def lowOrderStructuredBackgroundClosed
    (s : LowOrderStructuredBackgroundStatus) : Prop :=
  s.concreteImmersionOrbitClassified /\
  s.concreteConnectionOrbitClassified /\
  s.combinedOrbitClassifiedBySecondFundamentalAndCurvature /\
  s.universalInvariantFactorizationProved /\
  s.residualActionOnReducedDataConstructed /\
  s.finiteDimensionalTensorModelsInserted /\
  s.adaptedOrthogonalSpinCFramesConstructed /\
  s.smoothStructuredJetBaseConstructed /\
  s.globalSpinCAndHolonomySectorsReattached

/-- The exact algebraic `(B,F)` quotient is not yet the smooth finite-dimensional
Janus jet base until concrete tensor spaces and adapted frames are inserted. -/
theorem missing_finite_dimensional_tensor_models_blocks_geometric_quotient
    (s : LowOrderStructuredBackgroundStatus)
    (hMissing : Not s.finiteDimensionalTensorModelsInserted) :
    Not (lowOrderStructuredBackgroundClosed s) := by
  intro hClosed
  exact hMissing hClosed.2.2.2.2.2.1

end P0EFTJanusLowOrderStructuredBackground
end JanusFormal
