import Mathlib.Analysis.SpecialFunctions.Complex.Circle
import Mathlib.GroupTheory.QuotientGroup.Basic
import JanusFormal.Branches.FundamentalGeometryPEJetUniversality.Gates.P0EFTJanusCirclePhaseTwoTorsion

namespace JanusFormal
namespace P0EFTJanusSpin2CircleModel

set_option autoImplicit false

noncomputable section

open P0EFTJanusCentralLiftCocycleObstruction
open P0EFTJanusSpinCDiagonalDefectCancellation
open P0EFTJanusDeterminantSquareRootDefect
open P0EFTJanusCirclePhaseTwoTorsion

universe u

/-- The circle squaring homomorphism. Under the standard identifications
`Spin(2) ≅ U(1)` and `SO(2) ≅ U(1)`, this is the Spin-to-SO projection. The
matrix and Clifford-algebra identifications themselves remain a separate
geometric theorem. -/
def circleSquaringProjection : Circle →* Circle where
  toFun phase := phase * phase
  map_one' := by simp
  map_mul' := by
    intro first second
    ac_rfl

@[simp]
theorem circleSquaringProjection_apply (phase : Circle) :
    circleSquaringProjection phase = phase * phase := by
  rfl

/-- Every circle phase has a square root, so the squaring projection is
surjective. -/
theorem circleSquaringProjection_surjective :
    Function.Surjective circleSquaringProjection := by
  intro phase
  let root : Circle := Circle.exp (Complex.arg (phase : ℂ) / 2)
  refine ⟨root, ?_⟩
  change root * root = phase
  calc
    root * root =
        Circle.exp
          (Complex.arg (phase : ℂ) / 2 +
            Complex.arg (phase : ℂ) / 2) := by
      simpa [root] using
        (Circle.exp_add
          (Complex.arg (phase : ℂ) / 2)
          (Complex.arg (phase : ℂ) / 2)).symm
    _ = Circle.exp (Complex.arg (phase : ℂ)) := by
      congr 1
      ring
    _ = phase := Circle.exp_arg phase

/-- Concrete central double-cover data for the circle squaring map. Its kernel
is exactly `{+1,-1}`. -/
def spin2CircleDoubleCover : CentralDoubleCoverData Circle Circle where
  projection := circleSquaringProjection
  kernel_central := by
    intro phase hKernel other
    exact mul_comm _ _
  minusOne := -1
  minusOne_mem_kernel := by
    change circleSquaringProjection (-1 : Circle) = 1
    apply Circle.ext
    norm_num
  minusOne_ne_one := Circle.neg_ne_self 1
  minusOne_sq := by
    apply Circle.ext
    norm_num
  kernel_dichotomy := by
    intro phase hKernel
    change circleSquaringProjection phase = 1 at hKernel
    exact circle_square_eq_one_dichotomy phase hKernel

@[simp]
theorem spin2CircleDoubleCover_minusOne :
    spin2CircleDoubleCover.minusOne = (-1 : Circle) := by
  rfl

/-- The concrete double-cover projection is onto. -/
theorem spin2CircleDoubleCover_projection_surjective :
    Function.Surjective spin2CircleDoubleCover.projection :=
  circleSquaringProjection_surjective

/-- Exact two-sheeted fiber theorem for circle squaring. -/
theorem circleSquaringProjection_eq_iff
    (first second : Circle) :
    circleSquaringProjection first = circleSquaringProjection second ↔
      first = second ∨ first = -second := by
  constructor
  · intro hProjection
    have hKernel : first * second⁻¹ ∈
        spin2CircleDoubleCover.projection.ker := by
      change circleSquaringProjection (first * second⁻¹) = 1
      rw [circleSquaringProjection.map_mul,
        circleSquaringProjection.map_inv, hProjection]
      exact mul_inv_cancel _
    rcases spin2CircleDoubleCover.kernel_dichotomy
        (first * second⁻¹) hKernel with
      hTrivial | hMinusOne
    · left
      exact mul_inv_eq_one.mp hTrivial
    · right
      change first * second⁻¹ = (-1 : Circle) at hMinusOne
      have hMultiply := congrArg
        (fun phase : Circle => phase * second) hMinusOne
      simpa [mul_assoc] using hMultiply
  · rintro (hEqual | hNegative)
    · rw [hEqual]
    · rw [hNegative]
      apply Circle.ext
      simp [circleSquaringProjection]

/-- The diagonal central element in `Spin(2) × U(1)`. -/
def spin2DiagonalMinusOne : Circle × Circle :=
  ((-1 : Circle), (-1 : Circle))

/-- Normal subgroup generated by the diagonal central involution. Since the
ambient product group is commutative, the subgroup is automatically normal. -/
def spin2DiagonalSubgroup : Subgroup (Circle × Circle) :=
  Subgroup.closure {spin2DiagonalMinusOne}

/-- Concrete quotient type for the rank-two SpinC circle model. -/
abbrev Spin2CircleSpinCGroup :=
  (Circle × Circle) ⧸ spin2DiagonalSubgroup

/-- Exact diagonal quotient map killing `(-1,-1)`. -/
def spin2DiagonalQuotientData :
    SpinCDiagonalQuotientData
      Circle Circle Spin2CircleSpinCGroup where
  quotient := QuotientGroup.mk' spin2DiagonalSubgroup
  spinMinusOne := -1
  phaseMinusOne := -1
  diagonalMinusOne_killed := by
    change
      ((spin2DiagonalMinusOne : Circle × Circle) :
        Spin2CircleSpinCGroup) = 1
    exact (QuotientGroup.eq_one_iff spin2DiagonalMinusOne).2
      (Subgroup.subset_closure (by simp [spin2DiagonalMinusOne]))

/-- The diagonal quotient projection is surjective. -/
theorem spin2DiagonalQuotient_surjective :
    Function.Surjective spin2DiagonalQuotientData.quotient :=
  QuotientGroup.mk'_surjective spin2DiagonalSubgroup

/-- Specialized SpinC cocycle theorem for the concrete rank-two circle model.
Once the Spin-lift defect and determinant-root defect represent the same
`±1` class, their diagonal quotient transitions satisfy the Čech cocycle law. -/
theorem matching_spin2_circle_defects_implies_spinCCocycle
    {Index : Type u}
    (orientedCocycle : TransitionCocycle Index Circle)
    (spinLift : ChosenTransitionLift
      spin2CircleDoubleCover.toCentralCoverData orientedCocycle)
    (determinantLine : TransitionCocycle Index Circle)
    (rootChoice : SquareRootTransitionChoice determinantLine)
    (hMatch : ∀ i j k,
      liftDefect spin2CircleDoubleCover.toCentralCoverData
          orientedCocycle spinLift i j k = 1 ↔
        phaseDefect rootChoice.root i j k = 1) :
    ∀ i j k,
      spinCTransition spin2CircleDoubleCover orientedCocycle spinLift
          rootChoice.root spin2DiagonalQuotientData j k *
        spinCTransition spin2CircleDoubleCover orientedCocycle spinLift
          rootChoice.root spin2DiagonalQuotientData i j =
      spinCTransition spin2CircleDoubleCover orientedCocycle spinLift
        rootChoice.root spin2DiagonalQuotientData i k := by
  exact matching_squareRoot_defects_implies_spinCCocycle
    spin2CircleDoubleCover orientedCocycle spinLift determinantLine rootChoice
    circleTwoTorsionPhaseData spin2DiagonalQuotientData rfl rfl hMatch

/-- Exact progress boundary for the concrete rank-two model. -/
structure Spin2CircleModelStatus where
  circleSpinModelInserted : Prop
  squaringProjectionConstructed : Prop
  squaringProjectionSurjective : Prop
  kernelExactlyPlusMinusOne : Prop
  twoSheetedFiberTheoremProved : Prop
  centralDoubleCoverDataConstructed : Prop
  diagonalSpinCQuotientConstructed : Prop
  matchingDefectsGiveSpinCCocycle : Prop
  circleIdentifiedWithMatrixSO2 : Prop
  circleIdentifiedWithCliffordSpin2 : Prop
  smoothPrincipalBundleConstructed : Prop
  determinantConnectionGluingProved : Prop

/-- Closure of the geometric rank-two SpinC model. -/
def spin2CircleModelClosed (s : Spin2CircleModelStatus) : Prop :=
  s.circleSpinModelInserted /\
  s.squaringProjectionConstructed /\
  s.squaringProjectionSurjective /\
  s.kernelExactlyPlusMinusOne /\
  s.twoSheetedFiberTheoremProved /\
  s.centralDoubleCoverDataConstructed /\
  s.diagonalSpinCQuotientConstructed /\
  s.matchingDefectsGiveSpinCCocycle /\
  s.circleIdentifiedWithMatrixSO2 /\
  s.circleIdentifiedWithCliffordSpin2 /\
  s.smoothPrincipalBundleConstructed /\
  s.determinantConnectionGluingProved

/-- The circle squaring theorem is a concrete double-cover model, but it does not
by itself identify the two circles with the matrix and Clifford definitions of
`SO(2)` and `Spin(2)`. -/
theorem missing_clifford_identification_blocks_geometric_spin2
    (s : Spin2CircleModelStatus)
    (hMissing : Not s.circleIdentifiedWithCliffordSpin2) :
    Not (spin2CircleModelClosed s) := by
  intro hClosed
  exact hMissing hClosed.2.2.2.2.2.2.2.2.2.1

end

end P0EFTJanusSpin2CircleModel
end JanusFormal
