import Mathlib.Topology.Order.UpperLowerSetTopology

/-!
# MF-TOP-001: topology from a primitive relation

This module reuses Mathlib's reflexive-transitive closure and upper-set
topology. It adds only the Program M relational signature and proves that the
construction is invariant under relabelling.
-/

namespace JanusFormal.ProgramM

open Relation Topology

universe u v u' v'

/-- The first Program M pilot signature. It contains no topology or geometry. -/
structure RelationalSystem (Obj : Type u) (Rel : Type v) where
  holds : Rel → Obj → Obj → Prop

/-- A simultaneous relabelling of objects and relation labels. -/
structure RelationalSystemIso
    {Obj : Type u} {Rel : Type v} {Obj' : Type u'} {Rel' : Type v'}
    (S : RelationalSystem Obj Rel) (T : RelationalSystem Obj' Rel') where
  objEquiv : Obj ≃ Obj'
  relEquiv : Rel ≃ Rel'
  holds_iff : ∀ q x y, T.holds (relEquiv q) (objEquiv x) (objEquiv y) ↔ S.holds q x y

/-- Reachability adds exactly reflexivity and transitivity to a selected relation. -/
def reachability {Obj : Type u} {Rel : Type v}
    (S : RelationalSystem Obj Rel) (q : Rel) : Obj → Obj → Prop :=
  ReflTransGen (S.holds q)

/-- The preorder generated by one selected primitive relation. -/
@[reducible] def reachabilityPreorder {Obj : Type u} {Rel : Type v}
    (S : RelationalSystem Obj Rel) (q : Rel) : Preorder Obj where
  le := reachability S q
  le_refl _ := ReflTransGen.refl
  le_trans _ _ _ := ReflTransGen.trans

/-- The Alexandrov upper-set topology generated from reachability. -/
@[reducible] def alexandrovTopology {Obj : Type u} {Rel : Type v}
    (S : RelationalSystem Obj Rel) (q : Rel) : TopologicalSpace Obj := by
  letI := reachabilityPreorder S q
  exact upperSet Obj

theorem reachability_map
    {Obj : Type u} {Rel : Type v} {Obj' : Type u'} {Rel' : Type v'}
    {S : RelationalSystem Obj Rel} {T : RelationalSystem Obj' Rel'}
    (e : RelationalSystemIso S T) {q : Rel} {x y : Obj}
    (h : reachability S q x y) :
    reachability T (e.relEquiv q) (e.objEquiv x) (e.objEquiv y) := by
  exact ReflTransGen.lift e.objEquiv
    (fun a b hab ↦ (e.holds_iff q a b).2 hab) h

theorem reachability_map_iff
    {Obj : Type u} {Rel : Type v} {Obj' : Type u'} {Rel' : Type v'}
    {S : RelationalSystem Obj Rel} {T : RelationalSystem Obj' Rel'}
    (e : RelationalSystemIso S T) {q : Rel} {x y : Obj} :
    reachability T (e.relEquiv q) (e.objEquiv x) (e.objEquiv y) ↔
      reachability S q x y := by
  constructor
  · intro h
    have h' := ReflTransGen.lift e.objEquiv.symm
      (fun a b hab ↦
        (e.holds_iff q (e.objEquiv.symm a) (e.objEquiv.symm b)).1 (by simpa using hab)) h
    simpa [reachability] using h'
  · exact reachability_map e

/-- MF-TOP-001 existence: every selected binary relation canonically yields an
Alexandrov-discrete upper-set topology after reflexive-transitive closure. -/
theorem alexandrovTopology_isAlexandrov
    {Obj : Type u} {Rel : Type v} (S : RelationalSystem Obj Rel) (q : Rel) :
    @AlexandrovDiscrete Obj (alexandrovTopology S q) := by
  letI := reachabilityPreorder S q
  change @AlexandrovDiscrete Obj (upperSet Obj)
  infer_instance

/-- Relabelling objects and relation labels gives a homeomorphic reconstructed
topology. -/
def alexandrovHomeomorph
    {Obj : Type u} {Rel : Type v} {Obj' : Type u'} {Rel' : Type v'}
    {S : RelationalSystem Obj Rel} {T : RelationalSystem Obj' Rel'}
    (e : RelationalSystemIso S T) (q : Rel) :
    @Homeomorph Obj Obj' (alexandrovTopology S q)
      (alexandrovTopology T (e.relEquiv q)) := by
  letI : Preorder Obj := reachabilityPreorder S q
  letI : Preorder Obj' := reachabilityPreorder T (e.relEquiv q)
  letI : TopologicalSpace Obj := upperSet Obj
  letI : TopologicalSpace Obj' := upperSet Obj'
  letI : Topology.IsUpperSet Obj := inferInstance
  letI : Topology.IsUpperSet Obj' := inferInstance
  refine
    { toEquiv := e.objEquiv
      continuous_toFun := (Topology.IsUpperSet.monotone_iff_continuous).1 ?_
      continuous_invFun := (Topology.IsUpperSet.monotone_iff_continuous).1 ?_ }
  · intro x y hxy
    exact reachability_map e hxy
  · intro x y hxy
    exact ReflTransGen.lift e.objEquiv.symm
      (fun a b hab ↦
        (e.holds_iff q (e.objEquiv.symm a) (e.objEquiv.symm b)).1 (by simpa using hab)) hxy

end JanusFormal.ProgramM
