/- Branch head: JanusNonThroatPTTransitions.

Purpose: compare non-throat PT transition candidates. The current preferred
candidate is ConformalPTBoundary; CrosscapPTTransition and NullPTBoundary remain
ranked alternatives. -/

import JanusFormal.Branches.JanusNonThroatPTTransitions.Gates.P0EFTJanusNonThroatPTTransitionCandidateMatrixGate
import JanusFormal.Branches.JanusNonThroatPTTransitions.Gates.P0EFTJanusConformalPTBoundaryMatchingAttemptGate
import JanusFormal.Branches.JanusNonThroatPTTransitions.Gates.P0EFTJanusCrosscapPTTransitionObstructionGate
import JanusFormal.Branches.JanusNonThroatPTTransitions.Gates.P0EFTJanusExoticPTTransitionConfigurationMatrixGate
import JanusFormal.Branches.JanusNonThroatPTTransitions.Gates.P0EFTJanusWeylCuspPTBoundaryClockRouteGate
import JanusFormal.Branches.JanusNonThroatPTTransitions.Gates.P0EFTJanusWeylCuspPhysicalClockCandidateMatrixGate
import JanusFormal.Branches.JanusNonThroatPTTransitions.Gates.P0EFTJanusVisibleMatterJordanFramePullbackAttemptGate
import JanusFormal.Branches.JanusNonThroatPTTransitions.Gates.P0EFTJanusBimetricScaleRatioClockAttemptGate
import JanusFormal.Branches.JanusNonThroatPTTransitions.Gates.P0EFTJanusGPlusWeylCuspKinematicPullbackGate
import JanusFormal.Branches.JanusNonThroatPTTransitions.Gates.P0EFTJanusConformalFriedmannOmegaEquationContractGate
import JanusFormal.Branches.JanusNonThroatPTTransitions.Gates.P0EFTJanusOmegaDynamicsCandidateMatrixGate
import JanusFormal.Branches.JanusNonThroatPTTransitions.Gates.P0EFTJanusConformalEinsteinTraceReductionGate
import JanusFormal.Branches.JanusNonThroatPTTransitions.Gates.P0EFTJanusDeterminantRatioToWeylOmegaObstructionGate
import JanusFormal.Branches.JanusNonThroatPTTransitions.Gates.P0EFTJanusWeylCuspLateSNMatchingBoundaryConditionsGate
import JanusFormal.Branches.JanusNonThroatPTTransitions.Gates.P0EFTJanusConformalTraceSourceContentAuditGate
import JanusFormal.Branches.JanusNonThroatPTTransitions.Gates.P0EFTJanusConformalEinstein00RadiationOmegaRouteGate
import JanusFormal.Branches.JanusNonThroatPTTransitions.Gates.P0EFTJanusHatBackgroundCandidateMatrixGate
import JanusFormal.Branches.JanusNonThroatPTTransitions.Gates.P0EFTJanusProjectiveS4RP4ConformalBackgroundGate
import JanusFormal.Branches.JanusNonThroatPTTransitions.Gates.P0EFTJanusBimetricRhoEffPlusSourceContractGate
import JanusFormal.Branches.JanusNonThroatPTTransitions.Gates.P0EFTJanusProjectiveHhatFromS4RP4LimitGate
import JanusFormal.Branches.JanusNonThroatPTTransitions.Gates.P0EFTJanusOmega00SolvabilityFrontierGate
import JanusFormal.Branches.JanusNonThroatPTTransitions.Gates.P0EFTJanusGlobalSignedEnergyToOmegaContractGate
import JanusFormal.Branches.JanusNonThroatPTTransitions.Gates.P0EFTJanusOmegaInternalRouteExhaustionMatrixGate
import JanusFormal.Branches.JanusNonThroatPTTransitions.Gates.P0EFTJanusNonThroatWeylCuspFinalFrontierGate
