/- Branch head: JanusEarlyUniverseNativePlasma.

Purpose: extend the paper/2026 Janus branch toward a native pre-drag
photon-baryon plasma. This branch does not import a Lambda-CDM sound ruler.
-/

import JanusFormal.Branches.JanusEarlyUniverseNativePlasma.Gates.P0EFTJanusEarlyUniverseNativePlasmaExtensionGate
import JanusFormal.Branches.JanusEarlyUniverseNativePlasma.Gates.P0EFTJanusEarlyUniverseNativePlasmaFrontierVerdictGate
import JanusFormal.Branches.JanusEarlyUniverseNativePlasma.Gates.P0EFTJanusEarlyRedshiftMapFeasibilityGate
import JanusFormal.Branches.JanusEarlyUniverseNativePlasma.Gates.P0EFTJanusEarlyBranchAttachmentRequirementsGate
import JanusFormal.Branches.JanusEarlyUniverseNativePlasma.Gates.P0EFTJanusExactShapeThroatLowerBoundGate
import JanusFormal.Branches.JanusEarlyUniverseNativePlasma.Gates.P0EFTJanusFourPowerRedshiftTransportObstructionGate
import JanusFormal.Branches.JanusEarlyUniverseNativePlasma.Gates.P0EFTJanusAdiabaticRadiationFirstLawGate
import JanusFormal.Branches.JanusEarlyUniverseNativePlasma.Gates.P0EFTJanusAttachedEarlyBranchC1DiagnosticGate
import JanusFormal.Branches.JanusEarlyUniverseNativePlasma.Gates.P0EFTJanusAttachedEarlyBranchTimescaleLawGate
import JanusFormal.Branches.JanusEarlyUniverseNativePlasma.Gates.P0EFTJanusAminSelectionCandidateMatrixGate
import JanusFormal.Branches.JanusEarlyUniverseNativePlasma.Gates.P0EFTJanusAminIntegerSectorRequirementsGate
import JanusFormal.Branches.JanusEarlyUniverseNativePlasma.Gates.P0EFTJanusBoundaryHilbertNSelectorRequirementsGate
import JanusFormal.Branches.JanusEarlyUniverseNativePlasma.Gates.P0EFTJanusBoundaryHilbertSectorSelectionFrontierGate
import JanusFormal.Branches.JanusEarlyUniverseNativePlasma.Gates.P0EFTJanusBoundaryStateLawCandidateMatrixGate
import JanusFormal.Branches.JanusEarlyUniverseNativePlasma.Gates.P0EFTJanusM31TorsorCPTExteriorPowerCandidateGate
import JanusFormal.Branches.JanusEarlyUniverseNativePlasma.Gates.P0EFTJanusM31ExteriorPowerConsistencyAuditGate
import JanusFormal.Branches.JanusEarlyUniverseNativePlasma.Gates.P0EFTJanusCPTBoundaryFermionizationFrontierGate
import JanusFormal.Branches.JanusEarlyUniverseNativePlasma.Gates.P0EFTJanusM31SymmetricPowerBoundarySectorCandidateGate
import JanusFormal.Branches.JanusEarlyUniverseNativePlasma.Gates.P0EFTJanusM31Sym4BoundaryStateLawDerivationAttemptGate
import JanusFormal.Branches.JanusEarlyUniverseNativePlasma.Gates.P0EFTJanusBoundaryDimensionToAminMapAuditGate
import JanusFormal.Branches.JanusEarlyUniverseNativePlasma.Gates.P0EFTJanusSym4LinearResolutionLawCandidateGate
import JanusFormal.Branches.JanusEarlyUniverseNativePlasma.Gates.P0EFTJanusEq40SahaIonizationScalingGate
import JanusFormal.Branches.JanusEarlyUniverseNativePlasma.Gates.P0EFTJanusEq40PhotonClockTransportAuditGate
import JanusFormal.Branches.JanusEarlyUniverseNativePlasma.Gates.P0EFTJanusNativeDragEpochEquationContractGate
import JanusFormal.Branches.JanusEarlyUniverseNativePlasma.Gates.P0EFTJanusPhaseSpaceOccupationSearchGate
import JanusFormal.Branches.JanusEarlyUniverseNativePlasma.Gates.P0EFTJanusNativeDragExponentFrontierGate
import JanusFormal.Branches.JanusEarlyUniverseNativePlasma.Gates.P0EFTJanusNativeSoundHorizonIntegralContractGate
import JanusFormal.Branches.JanusEarlyUniverseNativePlasma.Gates.P0EFTJanusPredragHubbleSourceExponentMatrixGate
import JanusFormal.Branches.JanusEarlyUniverseNativePlasma.Gates.P0EFTJanusRedshiftExponentQ0CompatibilityGate
import JanusFormal.Branches.JanusEarlyUniverseNativePlasma.Gates.P0EFTJanusPlusSectorMaxwellRadiationActionGate
import JanusFormal.Branches.JanusEarlyUniverseNativePlasma.Gates.P0EFTJanusPlusSectorPhotonStressConservationGate
import JanusFormal.Branches.JanusEarlyUniverseNativePlasma.Gates.P0EFTJanusVariableConstantsThermalFrameMapGate
