/- Branch head: null Sigma / PT bridge. -/

import JanusFormal.Shared.Z2SphericalSymmetry.Gates.P0EFTJanusZ2SO3EddingtonCrossTermCollarDiagnosticGate
import JanusFormal.Branches.NullPTBridgeMass.Gates.P0EFTJanusZ2NullSigmaPTBridgeSourceAlignmentGate
import JanusFormal.Branches.NullPTBridgeMass.Gates.P0EFTJanusZ2NullSigmaBoundaryVariablesGate
import JanusFormal.Branches.NullPTBridgeMass.Gates.P0EFTJanusZ2NullSigmaActionVariationGate
import JanusFormal.Branches.NullPTBridgeMass.Gates.P0EFTJanusZ2NullSigmaVariationReductionGate
import JanusFormal.Branches.NullPTBridgeMass.Gates.P0EFTJanusZ2NullSigmaPTJointGate
import JanusFormal.Branches.NullPTBridgeMass.Gates.P0EFTJanusZ2NullSigmaBarrabesIsraelGate
import JanusFormal.Branches.NullPTBridgeMass.Gates.P0EFTJanusZ2NullSigmaBranchVerdictGate
