import JanusFormal.Branches.P0BimetricOrbifoldPrototypeProgram.Gates.P0ActionTermCoefficientDerivation
import JanusFormal.Branches.P0BimetricOrbifoldPrototypeProgram.Gates.P0AetherGhostObservationConstraints
import JanusFormal.Branches.P0BimetricOrbifoldPrototypeProgram.Gates.P0BiMembraneConfinement
import JanusFormal.Branches.P0BimetricOrbifoldPrototypeProgram.Gates.P0BridgeUniquenessObligations
import JanusFormal.Branches.P0BimetricOrbifoldPrototypeProgram.Gates.P0CandidateClosureSummary
import JanusFormal.Branches.P0BimetricOrbifoldPrototypeProgram.Gates.P0CandidateOrbifoldActionInstantiation
import JanusFormal.Branches.P0BimetricOrbifoldPrototypeProgram.Gates.P0CandidateParameterPhaseSpace
import JanusFormal.Branches.P0BimetricOrbifoldPrototypeProgram.Gates.P0ClosureAxiomatics
import JanusFormal.Branches.P0BimetricOrbifoldPrototypeProgram.Gates.P0CoreGaugeLikeJanusClosure
import JanusFormal.Branches.P0BimetricOrbifoldPrototypeProgram.Gates.P0CosmologyObservableProgram
import JanusFormal.Branches.P0BimetricOrbifoldPrototypeProgram.Gates.P0DarkSectorEffectiveMap
import JanusFormal.Branches.P0BimetricOrbifoldPrototypeProgram.Gates.P0DoubleDualCartanConditionalClosure
import JanusFormal.Branches.P0BimetricOrbifoldPrototypeProgram.Gates.P0DynamicSourceObligations
import JanusFormal.Branches.P0BimetricOrbifoldPrototypeProgram.Gates.P0FalsifiableSignaturesMap
import JanusFormal.Branches.P0BimetricOrbifoldPrototypeProgram.Gates.P0FullLinearModeClosure
import JanusFormal.Branches.P0BimetricOrbifoldPrototypeProgram.Gates.P0GaugeLikeAetherTopology
import JanusFormal.Branches.P0BimetricOrbifoldPrototypeProgram.Gates.P0HubbleTensionEffectiveMap
import JanusFormal.Branches.P0BimetricOrbifoldPrototypeProgram.Gates.P0LinearGrowthEarlyStructureMap
import JanusFormal.Branches.P0BimetricOrbifoldPrototypeProgram.Gates.P0LinearTensorPerturbationStability
import JanusFormal.Branches.P0BimetricOrbifoldPrototypeProgram.Gates.P0MatterMeasureObligations
import JanusFormal.Branches.P0BimetricOrbifoldPrototypeProgram.Gates.P0ModernJanusViabilityRoadmap
import JanusFormal.Branches.P0BimetricOrbifoldPrototypeProgram.Gates.P0ModifiedFriedmannMinisuperspace
import JanusFormal.Branches.P0BimetricOrbifoldPrototypeProgram.Gates.P0OrbifoldActionCandidate
import JanusFormal.Branches.P0BimetricOrbifoldPrototypeProgram.Gates.P0OrbifoldActionProgram
import JanusFormal.Branches.P0BimetricOrbifoldPrototypeProgram.Gates.P0OrbifoldBoundaryNoether
import JanusFormal.Branches.P0BimetricOrbifoldPrototypeProgram.Gates.P0OrbifoldProjectionGuards
import JanusFormal.Branches.P0BimetricOrbifoldPrototypeProgram.Gates.P0RadionAmplitudeOrientationSplit
import JanusFormal.Branches.P0BimetricOrbifoldPrototypeProgram.Gates.P0RadionDilatonBranchSelection
import JanusFormal.Branches.P0BimetricOrbifoldPrototypeProgram.Gates.P0RadionVielbeinSouriauBridge
import JanusFormal.Branches.P0BimetricOrbifoldPrototypeProgram.Gates.P0ScalarVectorActionSpec
import JanusFormal.Branches.P0BimetricOrbifoldPrototypeProgram.Gates.P0ScalarVectorExactCoefficientMap
import JanusFormal.Branches.P0BimetricOrbifoldPrototypeProgram.Gates.P0ScalarVectorModeStability
import JanusFormal.Branches.P0BimetricOrbifoldPrototypeProgram.Gates.P0SouriauPoincareEnergyBranch
import JanusFormal.Branches.P0BimetricOrbifoldPrototypeProgram.Gates.P0SymbolicTensorCoefficientMap
import JanusFormal.Branches.P0BimetricOrbifoldPrototypeProgram.Gates.P0TensorParameterDerivations
import JanusFormal.Branches.P0BimetricOrbifoldPrototypeProgram.Gates.P0VielbeinEnergyResolution

/- Branch head: P0BimetricOrbifoldPrototypeProgram.
Build with: lake build JanusFormal.Branches.P0BimetricOrbifoldPrototypeProgram
Status is documented in docs/janus_branch_registry.md. -/