from __future__ import annotations

import json
import os
from pathlib import Path


REPORT_DIR = Path(os.environ.get("JANUS_REPORT_DIR", "outputs/reports"))


def build_payload() -> dict:
    return {
        "artifact": "bimetric_covariant_bianchi_matter",
        "status": "covariant_noether_bianchi_structure_closed_for_separate_matter",
        "identity": "sqrt(-g) nabla_g V_g + sqrt(-f) nabla_f V_f = 0",
        "matter_shell": {
            "plus": "nabla_g T_plus=0",
            "minus": "nabla_f T_minus=0",
            "direct_cross_transport_required": False,
        },
        "reason": "diagonal diffeomorphism invariance supplies one interaction Noether identity; separate matter diffeomorphism invariance supplies conservation in each native metric",
        "forbidden_extensions": [
            "copying T_minus into the g equation without a variational cross coupling",
            "using two independent interaction tensors not generated by one potential",
            "coupling one matter field minimally to both metrics",
        ],
        "closure": {
            "inhomogeneous_covariant_identity": True,
            "native_matter_conservation": True,
            "componentwise_tensor_expansion_mechanized": False,
            "janus_signed_cross_source_from_candidate_A": False,
        },
    }


def write_report() -> dict:
    payload = build_payload()
    REPORT_DIR.mkdir(parents=True, exist_ok=True)
    (REPORT_DIR / "bimetric_covariant_bianchi_matter.json").write_text(
        json.dumps(payload, indent=2), encoding="utf-8"
    )
    return payload


if __name__ == "__main__":
    print(json.dumps(write_report(), indent=2))
