from __future__ import annotations

from pathlib import Path
import json


REPORT_PATH = Path("outputs/reports/p0_interaction_tensor_research_program.md")
JSON_PATH = Path("outputs/reports/p0_interaction_tensor_research_program.json")


def build_payload() -> dict:
    research_tracks = [
        {
            "track": "L/DL geometry",
            "objective": "derive an admissible cross-sector tetrad transport and its derivative",
            "candidate_outputs": [
                "DL for L_geom=e_plus E_minus via spin connections",
                "Lorentz-admissible projection/polar branch",
                "local boost branch from source-derived relative velocity",
            ],
            "acceptance": "L^T eta L=eta and the same L induces K and Q_cross",
        },
        {
            "track": "K interaction tensors",
            "objective": "construct K_plus/K_minus families and eliminate non-tensorial shortcuts",
            "candidate_outputs": [
                "rejected naive copy",
                "diagnostic determinant-weighted copy",
                "Lorentz-transported dust",
                "perfect-fluid tensor transport",
                "anisotropic-stress tensor transport",
                "Bianchi-solved K as a divergence PDE",
            ],
            "acceptance": "both R_plus=0 and R_minus=0 after substitution",
        },
        {
            "track": "Bianchi closure criteria",
            "objective": "define pass/fail tests for claiming physical closure",
            "candidate_outputs": [
                "two-sector residual cancellation",
                "Newtonian/TOV limit recovery",
                "no fitted scalar patches",
                "accepted-source traceability",
            ],
            "acceptance": "full tensor closure, not only FLRW/Newtonian closure",
        },
        {
            "track": "source-law obligation ledgers",
            "objective": "mechanically bind same-L/DL, DlogB4vol, Falpha, and Cuu obligations to R_plus/R_minus rows",
            "candidate_outputs": [
                "source residual closure obligation matrix",
                "same-L/DL source-derived closure target",
                "DlogB4vol source/slice/lapse obligation ledger",
                "Falpha source-law obligation ledger",
                "projected Cuu action/pullback bridge ledger",
            ],
            "acceptance": "all required source identities are derived and both residual sectors close mechanically",
        },
    ]
    rejection_rules = [
        "reject any K that only works by absorbing tensor terms into Q_det or Q_cross",
        "reject any L used for Q_cross but not for K_plus/K_minus",
        "reject L_geom as physical optical transport unless Lorentz condition is proved",
        "reject a closure that works only in FLRW or Newtonian/TOV as a general tensor proof",
        "reject fitted parameters or survey-normalized sigma8/S8 amplitudes",
    ]
    proof_pipeline = [
        "enumerate L and K candidate families",
        "compute DL and divergence residual terms for each family",
        "apply Lorentz/tetrad admissibility",
        "apply same-map K/Q_cross compatibility",
        "apply R_plus/R_minus residual closure",
        "apply matter extension pressure/Pi checks",
        "apply source traceability to M15/M30/M31 or later accepted papers",
    ]
    current_status = {
        "candidate_enumeration_started": True,
        "dl_formula_family_available": True,
        "f_constraint_equations_available": True,
        "f_decomposition_available": True,
        "fermi_walker_branch_available": True,
        "receiver_geodesic_transport_available": True,
        "perfect_fluid_constraints_available": True,
        "anisotropic_orientation_constraints_available": True,
        "branch_decision_matrix_available": True,
        "k_candidate_families_available": True,
        "closure_acceptance_criteria_available": True,
        "density_measure_closure_condition_available": True,
        "source_measure_convention_matrix_available": True,
        "source_measure_selection_rules_available": True,
        "source_measure_residual_substitution_available": True,
        "residual_zero_condition_matrix_available": True,
        "dl_dlogb_identity_targets_available": True,
        "dl_lorentz_generator_obstruction_available": True,
        "dlogb_4volume_obstruction_available": True,
        "m15_source_identity_implications_available": True,
        "source_gap_scan_results_available": True,
        "minimal_axiom_transport_solution_available": True,
        "m30_zero_divergence_pde_derivation_available": True,
        "zero_divergence_solver_plan_available": True,
        "flrw_zero_divergence_toy_solution_available": True,
        "noncomoving_dust_pde_constraints_available": True,
        "omega_transverse_gauge_audit_available": True,
        "pi_eigenframe_gauge_fix_branch_available": True,
        "l_boundary_initial_condition_branch_available": True,
        "gauge_lifting_decision_matrix_available": True,
        "gauge_source_scan_results_available": True,
        "flat_omega_connection_branch_available": True,
        "pure_gauge_solder_connection_branch_available": True,
        "pure_gauge_pde_consistency_check_available": True,
        "relative_holonomy_branch_available": True,
        "flat_vs_holonomy_decision_available": True,
        "lorentz_polar_projection_regular_branch_available": True,
        "holonomy_path_rule_branch_available": True,
        "polar_projection_derivative_obstruction_available": True,
        "holonomy_loop_consistency_criteria_available": True,
        "transport_branch_closure_obligations_available": True,
        "solution_route_selection_available": True,
        "variational_closure_route_available": True,
        "integrability_closure_route_available": True,
        "source_derived_route_attempt_available": True,
        "auxiliary_l_action_attempt_available": True,
        "innovative_axiom_acceptance_gate_available": True,
        "stueckelberg_two_diffeo_route_available": True,
        "stueckelberg_conditional_closure_theorem_available": True,
        "stueckelberg_explicit_action_test_available": True,
        "stueckelberg_minimal_phi_dust_test_available": True,
        "stueckelberg_mirror_phi_constraints_available": True,
        "stueckelberg_zero_param_progression_available": True,
        "stueckelberg_zero_param_dust_compatibility_available": True,
        "stueckelberg_zero_param_residual_substitution_available": True,
        "stueckelberg_dphi_density_cancellation_available": True,
        "stueckelberg_dl_velocity_cancellation_available": True,
        "stueckelberg_dlogb_volume_cancellation_available": True,
        "stueckelberg_remaining_connection_gate_available": True,
        "stueckelberg_connection_difference_cancellation_available": True,
        "stueckelberg_map_equation_connection_compatibility_available": True,
        "stueckelberg_dust_congruence_escape_route_available": True,
        "stueckelberg_map_constraint_counting_available": True,
        "stueckelberg_map_integrability_curl_conditions_available": True,
        "stueckelberg_isometry_branch_no_go_available": True,
        "stueckelberg_weak_congruence_map_equation_available": True,
        "stueckelberg_weak_congruence_variational_origin_available": True,
        "stueckelberg_dust_current_multiplier_identification_available": True,
        "stueckelberg_transverse_source_requirement_available": True,
        "stueckelberg_projected_dust_variation_identity_available": True,
        "stueckelberg_projected_perfect_fluid_extension_available": True,
        "stueckelberg_phi_l_convention_lock_available": True,
        "stueckelberg_dust_branch_conditional_closure_gate_available": True,
        "stueckelberg_dust_image_curl_reduction_available": True,
        "stueckelberg_transverse_label_caustic_gate_available": True,
        "stueckelberg_multistream_extension_gate_available": True,
        "stueckelberg_sheet_sum_dust_model_available": True,
        "stueckelberg_sheet_creation_conservation_gate_available": True,
        "stueckelberg_kinetic_moment_sheet_limit_available": True,
        "stueckelberg_sheet_optical_no_fit_gate_available": True,
        "stueckelberg_sheet_diagnostic_execution_gate_available": True,
        "stueckelberg_kinetic_transport_candidate_available": True,
        "stueckelberg_qcross_kinetic_projection_candidate_available": True,
        "stueckelberg_rkin_pushforward_derivation_available": True,
        "stueckelberg_popt_acceptance_criteria_available": True,
        "stueckelberg_popt_null_tetrad_candidate_available": True,
        "stueckelberg_rkin_commutator_closure_gate_available": True,
        "stueckelberg_sachs_optical_source_gate_available": True,
        "stueckelberg_popt_reduced_sachs_candidate_available": True,
        "stueckelberg_janus_ricci_sign_substitution_gate_available": True,
        "stueckelberg_lensing_observable_chain_gate_available": True,
        "stueckelberg_scross_source_anchor_available": True,
        "stueckelberg_shear_distance_gauge_closure_gate_available": True,
        "stueckelberg_weyl_shear_diagnostic_gate_available": True,
        "stueckelberg_observer_source_gauge_contract_available": True,
        "stueckelberg_perturbed_metric_weyl_solver_target_available": True,
        "stueckelberg_gauge_contract_instantiation_target_available": True,
        "stueckelberg_weak_field_weyl_operator_available": True,
        "stueckelberg_weak_field_weyl_source_chain_available": True,
        "stueckelberg_metric_potential_closure_contract_available": True,
        "stueckelberg_linearized_field_equation_branch_available": True,
        "stueckelberg_gauge_slip_branch_available": True,
        "stueckelberg_source_identity_branch_available": True,
        "stueckelberg_metric_potential_promotion_gate_available": True,
        "stueckelberg_comoving_scalar_metric_closure_candidate_available": True,
        "stueckelberg_noncomoving_source_identity_target_available": True,
        "stueckelberg_beta_field_provenance_gate_available": True,
        "stueckelberg_beta_vec_u_transport_target_available": True,
        "stueckelberg_noncomoving_pressure_pi_closure_requirements_available": True,
        "source_derived_beta_reconstruction_target_available": True,
        "janus_linear_beta_vec_closure_gate_available": True,
        "janus_linear_source_operator_closure_target_available": True,
        "janus_linear_theta_beta_derivation_available": True,
        "janus_linear_theta_mode_reduction_derivation_available": True,
        "noncomoving_momentum_t0i_closure_target_available": True,
        "stueckelberg_noncomoving_pressure_pi_residual_substitution_gate_available": True,
        "same_l_dl_residual_closure_ledger_available": True,
        "same_phi_l_cuu_bridge_available": True,
        "dynamic_phi_l_selection_mirror_closure_available": True,
        "phi_scouple_source_or_axiom_decision_available": True,
        "phi_scouple_anti_rustine_gate_available": True,
        "phi_scouple_forced_selection_search_available": True,
        "global_review_outside_box_routes_available": True,
        "integrability_first_phi_l_selection_available": True,
        "integrability_first_equation_system_available": True,
        "integrability_regular_patch_toy_solver_available": True,
        "local_phi_scouple_no_go_target_available": True,
        "local_phi_scouple_symbolic_restricted_audit_available": True,
        "split_noether_calculable_target_available": True,
        "split_noether_linear_phi_candidate_available": True,
        "linear_imatter_tensor_contract_available": True,
        "linear_imatter_metric_variation_available": True,
        "linear_imatter_stress_response_target_available": True,
        "matter_action_stress_response_target_available": True,
        "dust_metric_stress_response_target_available": True,
        "dust_fixed_current_density_response_available": True,
        "dust_densitized_current_density_response_available": True,
        "dust_pullback_density_response_bridge_available": True,
        "source_pullback_metric_response_target_available": True,
        "dust_fixed_pullback_delta_t_branch_available": True,
        "linear_imatter_conditional_dust_k_variation_available": True,
        "pulled_m_metric_response_target_available": True,
        "l_metric_response_law_target_available": True,
        "pulled_m_symmetric_l_substitution_available": True,
        "omega_residual_closure_gate_available": True,
        "omega_dust_rank_one_condition_available": True,
        "omega_k_qcross_consistency_gate_available": True,
        "omega_closure_routes_gate_available": True,
        "omega_u_zero_source_derivation_target_available": True,
        "omega_source_law_trial_gate_available": True,
        "fermi_walker_omega_u_zero_trial_available": True,
        "source_congruence_omega_gate_available": True,
        "omega_source_or_axiom_decision_available": True,
        "janus_source_omega_traceability_audit_available": True,
        "transport_axiom_acceptance_gate_available": True,
        "transport_axiom_candidate_statement_available": True,
        "omega_next_decision_matrix_available": True,
        "external_janus_omega_source_search_gate_available": True,
        "external_janus_omega_source_search_results_available": True,
        "external_source_search_omega_transport_audit_available": True,
        "external_source_search_scouple_phi_audit_available": True,
        "du_l_omega_dynamic_derivation_attempt_available": True,
        "omega_source_no_go_axiom_boundary_available": True,
        "dlogb4vol_measure_law_derivation_attempt_available": True,
        "pressure_pi_omega_extension_blocker_available": True,
        "janus_equations_to_l_omega_law_attempt_available": True,
        "janus_equations_to_dlogb4vol_closure_attempt_available": True,
        "bianchi_minimal_joint_dl_dlogb_solution_available": True,
        "bianchi_minimal_integrability_mirror_gate_available": True,
        "bianchi_minimal_full_connection_lift_system_available": True,
        "bianchi_minimal_mirror_inverse_attempt_available": True,
        "bianchi_minimal_curvature_integrability_system_available": True,
        "flrw_relative_curvature_rows_target_available": True,
        "weakfield_relative_curvature_rows_target_available": True,
        "weakfield_tetrad_connection_target_available": True,
        "janus_source_tetrad_requirements_available": True,
        "janus_weakfield_metric_tetrad_bridge_available": True,
        "janus_weakfield_source_potential_system_available": True,
        "janus_weakfield_phi_psi_qdet_source_closure_attempt_available": True,
        "janus_weakfield_dust_slip_poisson_target_available": True,
        "janus_weakfield_dust_slip_fourier_solver_gate_available": True,
        "janus_weakfield_zero_mode_background_gauge_gate_available": True,
        "janus_weakfield_dust_slip_green_kernel_target_available": True,
        "janus_source_selected_branch_matrix_available": True,
        "janus_weakfield_lgeom_lorentz_no_go_gate_available": True,
        "janus_weakfield_lorentz_projection_derivation_available": True,
        "janus_weakfield_shift_boost_t0i_derivation_available": True,
        "janus_weakfield_g0i_shift_operator_derivation_available": True,
        "janus_pressure_pi0i_transport_gate_available": True,
        "janus_pressure_pi0i_transport_derivation_available": True,
        "janus_g0i_dust_beta_inversion_target_available": True,
        "janus_matter_eos_pi_branch_decision_available": True,
        "janus_eos_pi_source_audit_available": True,
        "janus_conditional_dust_branch_contract_available": True,
        "janus_kinetic_moment_eos_pi_closure_target_available": True,
        "janus_kinetic_moment_hierarchy_equations_available": True,
        "janus_kinetic_closure_routes_decision_available": True,
        "janus_full_vlasov_moment_closure_contract_available": True,
        "janus_pi_zero_preservation_gate_available": True,
        "janus_vlasov_geodesic_force_target_available": True,
        "janus_eos_prho_no_go_vlasov_gate_available": True,
        "janus_metric_tetrad_source_branch_gate_available": True,
        "janus_weakfield_metric_force_probe_available": True,
        "janus_same_l_transport_stack_gate_available": True,
        "janus_phase_space_b4vol_measure_gate_available": True,
        "janus_same_l_1p1_lorentz_probe_available": True,
        "janus_lgeom_tetrad_map_residual_probe_available": True,
        "janus_lgeom_dl_lie_residual_probe_available": True,
        "janus_phase_space_measure_probe_available": True,
        "janus_weakfield_b4vol_product_rule_probe_available": True,
        "source_derived_same_l_dl_residual_closure_target_available": True,
        "dlogb4vol_source_slice_lapse_obligation_ledger_available": True,
        "falpha_source_law_obligation_ledger_available": True,
        "projected_cuu_action_pullback_bridge_ledger_available": True,
        "janus_effective_vlasov_solver_gate_available": True,
        "janus_effective_vlasov_solver_probe_available": True,
        "janus_two_sector_vlasov_poisson_probe_available": True,
        "janus_metric_force_vlasov_step_probe_available": True,
        "janus_two_sector_metric_force_vlasov_probe_available": True,
        "janus_diagnostic_closure_dashboard_available": True,
        "janus_source_residual_closure_obligation_matrix_available": True,
        "bianchi_minimal_curvature_numeric_probe_available": True,
        "curvature_integrability_sparse_pde_probe_available": True,
        "weakfield_curvature_injection_probe_available": True,
        "weakfield_tetrad_pipeline_probe_available": True,
        "bianchi_minimal_same_l_qcross_gate_available": True,
        "mirror_inverse_numeric_residual_probe_available": True,
        "same_l_qcross_numeric_contraction_probe_available": True,
        "omega_projection_annihilation_gate_available": True,
        "linear_imatter_l_variation_available": True,
        "linear_imatter_lorentz_projected_el_available": True,
        "stueckelberg_connection_force_residual_target_available": True,
        "connection_force_weak_congruence_reduction_available": True,
        "stueckelberg_projected_cuu_map_force_balance_available": True,
        "projected_cuu_action_derivation_target_available": True,
        "projected_dust_el_cuu_derivation_chain_available": True,
        "effective_density_continuity_pullback_proof_available": True,
        "stueckelberg_pulled_dust_el_projection_derivation_available": True,
        "pulled_dust_el_cuu_substitution_proof_available": True,
        "pulled_dust_el_projection_substitution_available": True,
        "dphi_jacobian_volume_identity_target_available": True,
        "stueckelberg_density_measure_identity_lock_available": True,
        "pulled_dust_dl_velocity_tetrad_substitution_gate_available": True,
        "density_measure_branch_decision_gate_available": True,
        "b_jphi_qdet_source_measure_branch_selection_target_available": True,
        "falpha_free_components_gate_available": True,
        "dl_source_law_traceability_gate_available": True,
        "b_jphi_qdet_conditional_selection_available": True,
        "falpha_minimal_gauge_candidate_available": True,
        "b4vol_fminimal_residual_trial_available": True,
        "b4vol_residual_remaining_terms_available": True,
        "b4vol_janus_source_anchor_available": True,
        "falpha_flow_projected_dl_residual_substitution_available": True,
        "janus_linear_operator_growth_ic_gate_available": True,
        "terminal_blockers_status_available": True,
        "constrained_zero_divergence_k_route_available": True,
        "bf_connection_constraint_route_available": True,
        "optimal_transport_matching_route_available": True,
        "blocker_dependency_graph_available": True,
        "k_family_accepted": False,
        "r_plus_closed": False,
        "r_minus_closed": False,
        "physics_closed": False,
        "prediction_ready": False,
    }
    return {
        "description": "Research program for constructing the missing Janus interaction tensors and transport map.",
        "status": "active-research-open",
        "current_status": current_status,
        "research_tracks": research_tracks,
        "rejection_rules": rejection_rules,
        "proof_pipeline": proof_pipeline,
        "expected_agent_artifacts": [
            "p0_l_transport_candidate_geometry",
            "p0_k_interaction_tensor_candidate_families",
            "p0_bianchi_closure_candidate_criteria",
            "p0_branch_decision_matrix",
            "p0_density_measure_closure_condition",
            "p0_source_measure_convention_matrix",
            "p0_source_measure_selection_rules",
            "p0_source_measure_residual_substitution",
            "p0_residual_zero_condition_matrix",
            "p0_dl_dlogb_identity_targets",
            "p0_dl_lorentz_generator_obstruction",
            "p0_dlogb_4volume_obstruction",
            "p0_m15_source_identity_implications",
            "p0_source_gap_scan_results",
            "p0_minimal_axiom_transport_solution",
            "p0_m30_zero_divergence_pde_derivation",
            "p0_zero_divergence_solver_plan",
            "p0_flrw_zero_divergence_toy_solution",
            "p0_noncomoving_dust_pde_constraints",
            "p0_omega_transverse_gauge_audit",
            "p0_pi_eigenframe_gauge_fix_branch",
            "p0_l_boundary_initial_condition_branch",
            "p0_gauge_lifting_decision_matrix",
            "p0_gauge_source_scan_results",
            "p0_flat_omega_connection_branch",
            "p0_pure_gauge_solder_connection_branch",
            "p0_pure_gauge_pde_consistency_check",
            "p0_relative_holonomy_branch",
            "p0_flat_vs_holonomy_decision",
            "p0_lorentz_polar_projection_regular_branch",
            "p0_holonomy_path_rule_branch",
            "p0_polar_projection_derivative_obstruction",
            "p0_holonomy_loop_consistency_criteria",
            "p0_transport_branch_closure_obligations",
            "p0_solution_route_selection",
            "p0_variational_closure_route",
            "p0_integrability_closure_route",
            "p0_source_derived_route_attempt",
            "p0_auxiliary_l_action_attempt",
            "p0_innovative_axiom_acceptance_gate",
            "p0_stueckelberg_two_diffeo_route",
            "p0_stueckelberg_conditional_closure_theorem",
            "p0_stueckelberg_explicit_action_test",
            "p0_stueckelberg_minimal_phi_dust_test",
            "p0_stueckelberg_mirror_phi_constraints",
            "p0_stueckelberg_zero_param_progression",
            "p0_stueckelberg_zero_param_dust_compatibility",
            "p0_stueckelberg_zero_param_residual_substitution",
            "p0_stueckelberg_dphi_density_cancellation",
            "p0_stueckelberg_dl_velocity_cancellation",
            "p0_stueckelberg_dlogb_volume_cancellation",
            "p0_stueckelberg_remaining_connection_gate",
            "p0_stueckelberg_connection_difference_cancellation",
            "p0_stueckelberg_map_equation_connection_compatibility",
            "p0_stueckelberg_dust_congruence_escape_route",
            "p0_stueckelberg_map_constraint_counting",
            "p0_stueckelberg_map_integrability_curl_conditions",
            "p0_stueckelberg_isometry_branch_no_go",
            "p0_stueckelberg_weak_congruence_map_equation",
            "p0_stueckelberg_weak_congruence_variational_origin",
            "p0_stueckelberg_dust_current_multiplier_identification",
            "p0_stueckelberg_transverse_source_requirement",
            "p0_stueckelberg_projected_dust_variation_identity",
            "p0_stueckelberg_projected_perfect_fluid_extension",
            "p0_stueckelberg_phi_l_convention_lock",
            "p0_stueckelberg_dust_branch_conditional_closure_gate",
            "p0_stueckelberg_dust_image_curl_reduction",
            "p0_stueckelberg_transverse_label_caustic_gate",
            "p0_stueckelberg_multistream_extension_gate",
            "p0_stueckelberg_sheet_sum_dust_model",
            "p0_stueckelberg_sheet_creation_conservation_gate",
            "p0_stueckelberg_kinetic_moment_sheet_limit",
            "p0_stueckelberg_sheet_optical_no_fit_gate",
            "p0_stueckelberg_sheet_diagnostic_execution_gate",
            "p0_stueckelberg_kinetic_transport_candidate",
            "p0_stueckelberg_qcross_kinetic_projection_candidate",
            "p0_stueckelberg_rkin_pushforward_derivation",
            "p0_stueckelberg_popt_acceptance_criteria",
            "p0_stueckelberg_popt_null_tetrad_candidate",
            "p0_stueckelberg_rkin_commutator_closure_gate",
            "p0_stueckelberg_sachs_optical_source_gate",
            "p0_stueckelberg_popt_reduced_sachs_candidate",
            "p0_stueckelberg_janus_ricci_sign_substitution_gate",
            "p0_stueckelberg_lensing_observable_chain_gate",
            "p0_stueckelberg_scross_source_anchor",
            "p0_stueckelberg_shear_distance_gauge_closure_gate",
            "p0_stueckelberg_weyl_shear_diagnostic_gate",
            "p0_stueckelberg_observer_source_gauge_contract",
            "p0_stueckelberg_perturbed_metric_weyl_solver_target",
            "p0_stueckelberg_gauge_contract_instantiation_target",
            "p0_stueckelberg_weak_field_weyl_operator",
            "p0_stueckelberg_weak_field_weyl_source_chain",
            "p0_stueckelberg_metric_potential_closure_contract",
            "p0_stueckelberg_linearized_field_equation_branch",
            "p0_stueckelberg_gauge_slip_branch",
            "p0_stueckelberg_source_identity_branch",
            "p0_stueckelberg_metric_potential_promotion_gate",
            "p0_stueckelberg_comoving_scalar_metric_closure_candidate",
            "p0_stueckelberg_noncomoving_source_identity_target",
            "p0_stueckelberg_beta_field_provenance_gate",
            "p0_stueckelberg_beta_vec_u_transport_target",
            "p0_stueckelberg_noncomoving_pressure_pi_closure_requirements",
            "p0_source_derived_beta_reconstruction_target",
            "janus_linear_beta_vec_closure_gate",
            "janus_linear_source_operator_closure_target",
            "janus_linear_theta_beta_derivation",
            "janus_linear_theta_mode_reduction_derivation",
            "p0_noncomoving_momentum_t0i_closure_target",
            "p0_stueckelberg_noncomoving_pressure_pi_residual_substitution_gate",
            "p0_same_l_dl_residual_closure_ledger",
            "p0_same_phi_l_cuu_bridge",
            "p0_dynamic_phi_l_selection_mirror_closure",
            "p0_phi_scouple_source_or_axiom_decision",
            "p0_phi_scouple_anti_rustine_gate",
            "p0_phi_scouple_forced_selection_search",
            "p0_global_review_outside_box_routes",
            "p0_integrability_first_phi_l_selection",
            "p0_integrability_first_equation_system",
            "p0_integrability_regular_patch_toy_solver",
            "p0_local_phi_scouple_no_go_target",
            "p0_local_phi_scouple_symbolic_restricted_audit",
            "p0_split_noether_calculable_target",
            "p0_split_noether_linear_phi_candidate",
            "p0_linear_imatter_tensor_contract",
            "p0_linear_imatter_metric_variation",
            "p0_linear_imatter_stress_response_target",
            "p0_matter_action_stress_response_target",
            "p0_dust_metric_stress_response_target",
            "p0_dust_fixed_current_density_response",
            "p0_dust_densitized_current_density_response",
            "p0_dust_pullback_density_response_bridge",
            "p0_source_pullback_metric_response_target",
            "p0_dust_fixed_pullback_delta_t_branch",
            "p0_linear_imatter_conditional_dust_k_variation",
            "p0_pulled_m_metric_response_target",
            "p0_l_metric_response_law_target",
            "p0_pulled_m_symmetric_l_substitution",
            "p0_omega_residual_closure_gate",
            "p0_omega_dust_rank_one_condition",
            "p0_omega_k_qcross_consistency_gate",
            "p0_omega_closure_routes_gate",
            "p0_omega_u_zero_source_derivation_target",
            "p0_omega_source_law_trial_gate",
            "p0_fermi_walker_omega_u_zero_trial",
            "p0_source_congruence_omega_gate",
            "p0_omega_source_or_axiom_decision",
            "p0_janus_source_omega_traceability_audit",
            "p0_transport_axiom_acceptance_gate",
            "p0_transport_axiom_candidate_statement",
            "p0_omega_next_decision_matrix",
            "p0_external_janus_omega_source_search_gate",
            "p0_external_janus_omega_source_search_results",
            "p0_external_source_search_omega_transport_audit",
            "p0_external_source_search_scouple_phi_audit",
            "p0_du_l_omega_dynamic_derivation_attempt",
            "p0_omega_source_no_go_axiom_boundary",
            "p0_dlogb4vol_measure_law_derivation_attempt",
            "p0_pressure_pi_omega_extension_blocker",
            "p0_janus_equations_to_l_omega_law_attempt",
            "p0_janus_equations_to_dlogb4vol_closure_attempt",
            "p0_bianchi_minimal_joint_dl_dlogb_solution",
            "p0_bianchi_minimal_integrability_mirror_gate",
            "p0_bianchi_minimal_full_connection_lift_system",
            "p0_bianchi_minimal_mirror_inverse_attempt",
            "p0_bianchi_minimal_curvature_integrability_system",
            "p0_flrw_relative_curvature_rows_target",
            "p0_weakfield_relative_curvature_rows_target",
            "p0_weakfield_tetrad_connection_target",
            "p0_janus_source_tetrad_requirements",
            "p0_janus_weakfield_metric_tetrad_bridge",
            "p0_janus_weakfield_source_potential_system",
            "p0_janus_weakfield_phi_psi_qdet_source_closure_attempt",
            "p0_janus_weakfield_dust_slip_poisson_target",
            "p0_janus_weakfield_dust_slip_fourier_solver_gate",
            "p0_janus_weakfield_zero_mode_background_gauge_gate",
            "p0_janus_weakfield_dust_slip_green_kernel_target",
            "p0_janus_source_selected_branch_matrix",
            "p0_janus_weakfield_lgeom_lorentz_no_go_gate",
            "p0_janus_weakfield_lorentz_projection_derivation",
            "p0_janus_weakfield_shift_boost_t0i_derivation",
            "p0_janus_weakfield_g0i_shift_operator_derivation",
            "p0_janus_pressure_pi0i_transport_gate",
            "p0_janus_pressure_pi0i_transport_derivation",
            "p0_janus_g0i_dust_beta_inversion_target",
            "p0_janus_matter_eos_pi_branch_decision",
            "p0_janus_eos_pi_source_audit",
            "p0_janus_conditional_dust_branch_contract",
            "p0_janus_kinetic_moment_eos_pi_closure_target",
            "p0_janus_kinetic_moment_hierarchy_equations",
            "p0_janus_kinetic_closure_routes_decision",
            "p0_janus_full_vlasov_moment_closure_contract",
            "p0_janus_pi_zero_preservation_gate",
            "p0_janus_vlasov_geodesic_force_target",
            "p0_janus_eos_prho_no_go_vlasov_gate",
            "p0_janus_metric_tetrad_source_branch_gate",
            "p0_janus_weakfield_metric_force_probe",
            "p0_janus_same_l_transport_stack_gate",
            "p0_janus_phase_space_b4vol_measure_gate",
            "p0_janus_same_l_1p1_lorentz_probe",
            "p0_janus_lgeom_tetrad_map_residual_probe",
            "p0_janus_lgeom_dl_lie_residual_probe",
            "p0_janus_phase_space_measure_probe",
            "p0_janus_weakfield_b4vol_product_rule_probe",
            "p0_source_derived_same_l_dl_residual_closure_target",
            "p0_dlogb4vol_source_slice_lapse_obligation_ledger",
            "p0_falpha_source_law_obligation_ledger",
            "p0_projected_cuu_action_pullback_bridge_ledger",
            "p0_janus_effective_vlasov_solver_gate",
            "p0_janus_effective_vlasov_solver_probe",
            "p0_janus_two_sector_vlasov_poisson_probe",
            "p0_janus_metric_force_vlasov_step_probe",
            "p0_janus_two_sector_metric_force_vlasov_probe",
            "p0_janus_diagnostic_closure_dashboard",
            "p0_janus_source_residual_closure_obligation_matrix",
            "p0_bianchi_minimal_curvature_numeric_probe",
            "p0_curvature_integrability_sparse_pde_probe",
            "p0_weakfield_curvature_injection_probe",
            "p0_weakfield_tetrad_pipeline_probe",
            "p0_bianchi_minimal_same_l_qcross_gate",
            "p0_mirror_inverse_numeric_residual_probe",
            "p0_same_l_qcross_numeric_contraction_probe",
            "p0_omega_projection_annihilation_gate",
            "p0_linear_imatter_l_variation",
            "p0_linear_imatter_lorentz_projected_el",
            "p0_stueckelberg_connection_force_residual_target",
            "p0_connection_force_weak_congruence_reduction",
            "p0_stueckelberg_projected_cuu_map_force_balance",
            "p0_projected_cuu_action_derivation_target",
            "p0_projected_dust_el_cuu_derivation_chain",
            "p0_effective_density_continuity_pullback_proof",
            "p0_stueckelberg_pulled_dust_el_projection_derivation",
            "p0_pulled_dust_el_cuu_substitution_proof",
            "p0_pulled_dust_el_projection_substitution",
            "p0_dphi_jacobian_volume_identity_target",
            "p0_stueckelberg_density_measure_identity_lock",
            "p0_pulled_dust_dl_velocity_tetrad_substitution_gate",
            "p0_density_measure_branch_decision_gate",
            "p0_b_jphi_qdet_source_measure_branch_selection_target",
            "p0_falpha_free_components_gate",
            "p0_dl_source_law_traceability_gate",
            "p0_b_jphi_qdet_conditional_selection",
            "p0_falpha_minimal_gauge_candidate",
            "p0_b4vol_fminimal_residual_trial",
            "p0_b4vol_residual_remaining_terms",
            "p0_b4vol_janus_source_anchor",
            "p0_falpha_flow_projected_dl_residual_substitution",
            "janus_linear_operator_growth_ic_gate",
            "p0_terminal_blockers_status",
            "p0_constrained_zero_divergence_k_route",
            "p0_bf_connection_constraint_route",
            "p0_optimal_transport_matching_route",
            "p0_blocker_dependency_graph",
        ],
        "verdict": (
            "This is the correct next layer: act as physicist-mathematician-geometer by "
            "constructing and rejecting candidate tensors under explicit tensor criteria. "
            "No prediction is unlocked until a candidate survives every step."
        ),
    }


def render_markdown(payload: dict) -> str:
    status = payload["current_status"]
    lines = [
        "# P0 Interaction Tensor Research Program",
        "",
        payload["description"],
        "",
        f"Status: {payload['status']}",
    ]
    lines.extend(f"{key}: {value}" for key, value in status.items())
    lines.extend(["", "## Research Tracks", ""])
    for track in payload["research_tracks"]:
        lines.append(f"- {track['track']}: {track['objective']}")
        lines.extend(f"  - candidate: {item}" for item in track["candidate_outputs"])
        lines.append(f"  - acceptance: {track['acceptance']}")
    lines.extend(["", "## Rejection Rules", ""])
    lines.extend(f"- {item}" for item in payload["rejection_rules"])
    lines.extend(["", "## Proof Pipeline", ""])
    lines.extend(f"- {item}" for item in payload["proof_pipeline"])
    lines.extend(["", "## Expected Agent Artifacts", ""])
    lines.extend(f"- `{item}`" for item in payload["expected_agent_artifacts"])
    lines.extend(["", f"Verdict: {payload['verdict']}", ""])
    return "\n".join(lines)


def write_reports(report_path: Path = REPORT_PATH, json_path: Path = JSON_PATH) -> dict:
    report_path.parent.mkdir(parents=True, exist_ok=True)
    json_path.parent.mkdir(parents=True, exist_ok=True)
    payload = build_payload()
    json_path.write_text(json.dumps(payload, indent=2), encoding="utf-8")
    report_path.write_text(render_markdown(payload), encoding="utf-8")
    return payload


def main() -> None:
    write_reports()
    print(f"Wrote {REPORT_PATH}")
    print(f"Wrote {JSON_PATH}")


if __name__ == "__main__":
    main()
