from __future__ import annotations

from pathlib import Path
import json
import sys


ROOT = Path(__file__).resolve().parents[1]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

from scripts.build_p0_b4vol_fminimal_residual_trial import build_payload as build_b4vol_f_trial
from scripts.build_p0_b4vol_residual_remaining_terms import build_payload as build_b4vol_terms
from scripts.build_p0_dlogb4vol_source_slice_lapse_obligation_ledger import (
    build_payload as build_dlogb_ledger,
)
from scripts.build_p0_falpha_flow_projected_dl_residual_substitution import (
    build_payload as build_falpha_substitution,
)
from scripts.build_p0_falpha_source_law_obligation_ledger import (
    build_payload as build_falpha_ledger,
)
from scripts.build_p0_janus_diagnostic_closure_dashboard import build_payload as build_dashboard
from scripts.build_p0_janus_phase_space_b4vol_measure_gate import build_payload as build_measure_gate
from scripts.build_p0_projected_cuu_action_pullback_bridge_ledger import (
    build_payload as build_cuu_ledger,
)
from scripts.build_p0_source_derived_same_l_dl_residual_closure_target import (
    build_payload as build_same_l_source_target,
)
from scripts.build_p0_shared_phi_j_source_selection_gate import (
    build_payload as build_shared_phi_j_gate,
)


REPORT_PATH = Path("outputs/reports/p0_janus_source_residual_closure_obligation_matrix.md")
JSON_PATH = Path("outputs/reports/p0_janus_source_residual_closure_obligation_matrix.json")


def _identity_status() -> dict:
    same_l_source = build_same_l_source_target()
    measure = build_measure_gate()
    dlogb_ledger = build_dlogb_ledger()
    falpha = build_falpha_substitution()
    falpha_ledger = build_falpha_ledger()
    b4_terms = build_b4vol_terms()
    b4_trial = build_b4vol_f_trial()
    cuu_ledger = build_cuu_ledger()
    shared_phi_j = build_shared_phi_j_gate()
    return {
        "shared_phi_j_source_selection": {
            "artifact": "p0_shared_phi_j_source_selection_gate",
            "required": "one Janus-selected integrable phi/J shared by Cuu, F_alpha, B4vol and residual rows",
            "source_derived": bool(shared_phi_j["shared_source_selected_phi_j_closed"]),
        },
        "same_l_dl_source_law": {
            "artifact": "p0_source_derived_same_l_dl_residual_closure_target",
            "required": "one Lorentz same-L and D L law for K, Q_cross, kinetics, and residuals",
            "source_derived": bool(
                same_l_source["source_derived"]
                and same_l_source["same_l_closed"]
                and same_l_source["dl_closed"]
            ),
        },
        "b4vol_source_measure_law": {
            "artifact": "p0_dlogb4vol_source_slice_lapse_obligation_ledger",
            "required": "D log B_4vol with lapse/slice/J_phi/Q_det convention from source identity",
            "source_derived": bool(
                measure["b4vol_phase_space_measure_closed"]
                and b4_terms["dlogb_identity_source_derived"]
                and dlogb_ledger["source_slice_lapse_obligations_closed"]
            ),
        },
        "falpha_source_law": {
            "artifact": "p0_falpha_source_law_obligation_ledger",
            "required": "F_alpha generated by Janus source/connection data, not minimal-gauge choice",
            "source_derived": bool(
                falpha["falpha_source_derived"]
                and falpha_ledger["source_law_obligations_closed"]
            ),
        },
        "projected_cuu_force_balance": {
            "artifact": "p0_projected_cuu_action_pullback_bridge_ledger",
            "required": "h E_phi/E_L = rho h C(u,u) from action/pullback source, not imposed",
            "source_derived": bool(
                b4_trial["r_plus_closed"]
                and b4_trial["r_minus_closed"]
                and cuu_ledger["projected_cuu_action_bridge_closed"]
            ),
        },
    }


def _guardrail_status() -> dict:
    dashboard = build_dashboard(consume_graph=False)
    return {
        "diagnostic_non_promotion": {
            "artifact": "p0_janus_diagnostic_closure_dashboard",
            "required": "diagnostics remain non-predictive and cannot absorb tensor terms into scalars",
            "satisfied": bool(
                dashboard["all_probe_reports_non_predictive"]
                and dashboard["all_probe_reports_diagnostic"]
                and not dashboard["raw_lgeom_promoted"]
                and not dashboard["prediction_ready"]
            ),
        }
    }


def _residual_row(sector: str, row: str, requires: list[str], identities: dict, guardrails: dict) -> dict:
    required_identities_source_derived = all(
        identities[name]["source_derived"] for name in requires
    )
    guardrails_satisfied = all(item["satisfied"] for item in guardrails.values())
    return {
        "sector": sector,
        "row": row,
        "requires": requires,
        "required_identities_source_derived": required_identities_source_derived,
        "guardrails_satisfied": guardrails_satisfied,
        "closed": bool(required_identities_source_derived and guardrails_satisfied),
    }


def build_payload() -> dict:
    identities = _identity_status()
    guardrails = _guardrail_status()
    residual_rows = [
        _residual_row(
            "R_plus",
            "transported density/product rule",
            ["shared_phi_j_source_selection", "b4vol_source_measure_law"],
            identities,
            guardrails,
        ),
        _residual_row(
            "R_plus",
            "D L velocity/tetrad terms",
            ["shared_phi_j_source_selection", "same_l_dl_source_law", "falpha_source_law"],
            identities,
            guardrails,
        ),
        _residual_row(
            "R_plus",
            "projected connection force Cuu",
            ["shared_phi_j_source_selection", "projected_cuu_force_balance"],
            identities,
            guardrails,
        ),
        _residual_row(
            "R_minus",
            "mirror transported density/product rule",
            ["shared_phi_j_source_selection", "b4vol_source_measure_law"],
            identities,
            guardrails,
        ),
        _residual_row(
            "R_minus",
            "mirror D L velocity/tetrad terms",
            ["shared_phi_j_source_selection", "same_l_dl_source_law", "falpha_source_law"],
            identities,
            guardrails,
        ),
        _residual_row(
            "R_minus",
            "mirror projected connection force Cuu",
            ["shared_phi_j_source_selection", "projected_cuu_force_balance"],
            identities,
            guardrails,
        ),
    ]
    r_plus_closed = all(row["closed"] for row in residual_rows if row["sector"] == "R_plus")
    r_minus_closed = all(row["closed"] for row in residual_rows if row["sector"] == "R_minus")
    forbidden_shortcuts = [
        "do not close R_plus/R_minus by absorbing tensor rows into Q_det",
        "do not close R_plus/R_minus by absorbing tensor rows into Q_cross",
        "do not promote raw L_geom or minimal-gauge F_alpha without source derivation",
        "do not use diagnostic Vlasov or weak-field probes as physical branch selection",
    ]
    missing = [
        name for name, row in identities.items() if not row["source_derived"]
    ]
    return {
        "description": "Source-derived obligation matrix for closing Janus P0 residual rows.",
        "status": "source-residual-closure-obligation-matrix-open",
        "identity_status": identities,
        "guardrail_status": guardrails,
        "residual_rows": residual_rows,
        "forbidden_shortcuts": forbidden_shortcuts,
        "missing_source_identities": missing,
        "failed_guardrails": [
            name for name, row in guardrails.items() if not row["satisfied"]
        ],
        "all_required_identities_source_derived": not missing,
        "all_guardrails_satisfied": all(row["satisfied"] for row in guardrails.values()),
        "residual_matrix_written": True,
        "residual_row_closure_computed": True,
        "scalar_absorption_forbidden": True,
        "uses_observational_fit": False,
        "r_plus_closed": r_plus_closed,
        "r_minus_closed": r_minus_closed,
        "physics_closed": bool(r_plus_closed and r_minus_closed),
        "prediction_ready": False,
        "verdict": (
            "The residual closure is now reduced to named source-derived identities. "
            "Until those identities are proved from Janus sources, both R_plus and R_minus stay open."
        ),
    }


def render_markdown(payload: dict) -> str:
    lines = [
        "# P0 Janus Source Residual Closure Obligation Matrix",
        "",
        payload["description"],
        "",
        f"Status: {payload['status']}",
        f"Residual matrix written: {payload['residual_matrix_written']}",
        f"Residual row closure computed: {payload['residual_row_closure_computed']}",
        f"All required identities source-derived: {payload['all_required_identities_source_derived']}",
        f"All guardrails satisfied: {payload['all_guardrails_satisfied']}",
        f"Scalar absorption forbidden: {payload['scalar_absorption_forbidden']}",
        f"R plus closed: {payload['r_plus_closed']}",
        f"R minus closed: {payload['r_minus_closed']}",
        f"Prediction ready: {payload['prediction_ready']}",
        "",
        "## Identity Status",
        "",
        "| identity | artifact | source_derived | required |",
        "|---|---|---:|---|",
    ]
    for name, row in payload["identity_status"].items():
        lines.append(
            f"| {name} | {row['artifact']} | {row['source_derived']} | {row['required']} |"
        )
    lines.extend(
        [
            "",
            "## Guardrail Status",
            "",
            "| guardrail | artifact | satisfied | required |",
            "|---|---|---:|---|",
        ]
    )
    for name, row in payload["guardrail_status"].items():
        lines.append(
            f"| {name} | {row['artifact']} | {row['satisfied']} | {row['required']} |"
        )
    lines.extend(
        [
            "",
            "## Residual Rows",
            "",
            "| sector | row | requires | identities source-derived | guardrails | closed |",
            "|---|---|---|---:|---:|---:|",
        ]
    )
    for row in payload["residual_rows"]:
        lines.append(
            f"| {row['sector']} | {row['row']} | {'; '.join(row['requires'])} | "
            f"{row['required_identities_source_derived']} | {row['guardrails_satisfied']} | "
            f"{row['closed']} |"
        )
    lines.extend(["", "## Forbidden Shortcuts", ""])
    lines.extend(f"- {item}" for item in payload["forbidden_shortcuts"])
    lines.extend(["", "## Missing Source Identities", ""])
    lines.extend(f"- {item}" for item in payload["missing_source_identities"])
    lines.extend(["", f"Verdict: {payload['verdict']}", ""])
    return "\n".join(lines)


def write_reports(report_path: Path = REPORT_PATH, json_path: Path = JSON_PATH) -> dict:
    report_path.parent.mkdir(parents=True, exist_ok=True)
    json_path.parent.mkdir(parents=True, exist_ok=True)
    payload = build_payload()
    json_path.write_text(json.dumps(payload, indent=2), encoding="utf-8")
    report_path.write_text(render_markdown(payload), encoding="utf-8")
    return payload


def main() -> None:
    write_reports()
    print(f"Wrote {REPORT_PATH}")
    print(f"Wrote {JSON_PATH}")


if __name__ == "__main__":
    main()
