from __future__ import annotations

from pathlib import Path
import json

import sympy as sp


REPORT_PATH = Path("outputs/reports/p0_janus_weakfield_shift_boost_t0i_derivation.md")
JSON_PATH = Path("outputs/reports/p0_janus_weakfield_shift_boost_t0i_derivation.json")
ETA = sp.diag(-1, 1, 1, 1)


def weakfield_shift_a_matrix() -> sp.Matrix:
    delta_phi, delta_psi, dbx, dby, dbz = sp.symbols("Delta_Phi Delta_Psi Delta_Bx Delta_By Delta_Bz")
    return sp.Matrix(
        [
            [-delta_phi, dbx, dby, dbz],
            [0, delta_psi, 0, 0],
            [0, 0, delta_psi, 0],
            [0, 0, 0, delta_psi],
        ]
    )


def eta_skew_projection(a_matrix: sp.Matrix) -> sp.Matrix:
    return sp.simplify((a_matrix - ETA * a_matrix.T * ETA) / 2)


def boost_vector_from_shift() -> tuple[sp.Expr, sp.Expr, sp.Expr]:
    projection = eta_skew_projection(weakfield_shift_a_matrix())
    return projection[1, 0], projection[2, 0], projection[3, 0]


def build_payload() -> dict:
    a_matrix = weakfield_shift_a_matrix()
    boost_projection = eta_skew_projection(a_matrix)
    boost_vector = boost_vector_from_shift()
    source_rows = [
        {
            "sector": "plus",
            "source_row": "delta G0i_plus = chi(T0i_plus + B_4vol_plus_from_minus T0i_minus_to_plus)",
            "momentum_source": "T0i=(rho+p) gamma^2 beta_i + Pi0i",
            "dust_linear_limit": "T0i ~= rho beta_i",
            "closed": False,
        },
        {
            "sector": "minus",
            "source_row": "delta G0i_minus = -chi(B_4vol_minus_from_plus T0i_plus_to_minus + T0i_minus)",
            "momentum_source": "T0i=(rho+p) gamma^2 beta_i + Pi0i",
            "dust_linear_limit": "T0i ~= rho beta_i",
            "closed": False,
        },
    ]
    return {
        "description": (
            "Weak-field derivation of the Lorentz boost component generated by a "
            "relative shift/vector perturbation and its Janus T0i source target."
        ),
        "status": "shift-boost-t0i-derivation-open",
        "depends_on": [
            "p0_janus_weakfield_lorentz_projection_derivation",
            "p0_noncomoving_momentum_t0i_closure_target",
            "janus_linear_beta_vec_closure_gate",
        ],
        "metric_branch_with_shift": (
            "ds_s^2=-(1+2 Phi_s)dt^2+2 B_s_i dt dx^i+(1-2 Psi_s)delta_ij dx^i dx^j"
        ),
        "coframe_choice": "e_s^0=(1+Phi_s)dt-B_s_i dx^i, e_s^i=(1-Psi_s)dx^i",
        "a_matrix_lgeom_minus_identity": [[sp.sstr(item) for item in row] for row in a_matrix.tolist()],
        "eta_skew_lorentz_projection": [[sp.sstr(item) for item in row] for row in boost_projection.tolist()],
        "derived_boost_vector": [sp.sstr(item) for item in boost_vector],
        "source_rows": source_rows,
        "derived_consequences": [
            "scalar potentials contribute only eta-symmetric stretch, not a Lorentz boost",
            "relative shift Delta_B_i contributes boost generator F_i0=F_0i=Delta_B_i/2",
            "nontrivial same-L Q_cross requires source-derived Delta_B_i or equivalent T0i beta_i",
            "pressure and Pi0i must be transported or eliminated before claiming non-dust closure",
        ],
        "shift_to_boost_derived": True,
        "t0i_source_rows_written": True,
        "source_operator_for_shift_closed": True,
        "source_derived_beta_available": False,
        "pressure_pi_momentum_transport_closed": False,
        "same_l_noncomoving_branch_selected": False,
        "uses_observational_fit": False,
        "physics_closed": False,
        "prediction_ready": False,
        "verdict": (
            "The Lorentz boost part is now derived from the relative shift: F_i0=Delta_B_i/2. "
            "The linear G0i shift operator is available in p0_janus_weakfield_g0i_shift_operator_derivation. "
            "The remaining physical task is transporting beta, pressure, and Pi momentum terms without scalar absorption."
        ),
    }


def render_markdown(payload: dict) -> str:
    lines = [
        "# P0 Janus Weak-Field Shift Boost T0i Derivation",
        "",
        payload["description"],
        "",
        f"Status: {payload['status']}",
        f"Metric branch with shift: `{payload['metric_branch_with_shift']}`",
        f"Coframe choice: `{payload['coframe_choice']}`",
        f"Derived boost vector: `{payload['derived_boost_vector']}`",
        f"Shift to boost derived: {payload['shift_to_boost_derived']}",
        f"T0i source rows written: {payload['t0i_source_rows_written']}",
        f"Source operator for shift closed: {payload['source_operator_for_shift_closed']}",
        f"Source-derived beta available: {payload['source_derived_beta_available']}",
        f"Pressure/Pi momentum transport closed: {payload['pressure_pi_momentum_transport_closed']}",
        f"Same-L non-comoving branch selected: {payload['same_l_noncomoving_branch_selected']}",
        f"Uses observational fit: {payload['uses_observational_fit']}",
        f"Physics closed: {payload['physics_closed']}",
        f"Prediction ready: {payload['prediction_ready']}",
        "",
        "## Source Rows",
        "",
        "| sector | source row | momentum source | dust linear limit | closed |",
        "|---|---|---|---|---|",
    ]
    for row in payload["source_rows"]:
        lines.append(
            f"| {row['sector']} | `{row['source_row']}` | `{row['momentum_source']}` | "
            f"`{row['dust_linear_limit']}` | {row['closed']} |"
        )
    lines.extend(["", "## Consequences", ""])
    lines.extend(f"- {item}" for item in payload["derived_consequences"])
    lines.extend(["", f"Verdict: {payload['verdict']}", ""])
    return "\n".join(lines)


def write_reports(report_path: Path = REPORT_PATH, json_path: Path = JSON_PATH) -> dict:
    report_path.parent.mkdir(parents=True, exist_ok=True)
    json_path.parent.mkdir(parents=True, exist_ok=True)
    payload = build_payload()
    json_path.write_text(json.dumps(payload, indent=2), encoding="utf-8")
    report_path.write_text(render_markdown(payload), encoding="utf-8")
    return payload


def main() -> None:
    write_reports()
    print(f"Wrote {REPORT_PATH}")
    print(f"Wrote {JSON_PATH}")


if __name__ == "__main__":
    main()
