import JanusFormal.Branches.FundamentalGeometryPVariationalPrinciple.Gates.P0EFTJanusMappingTorusCanonicalPhysicalScalarIntrinsicWaveTransportedNormalFinalClosure4D
import JanusFormal.Branches.FundamentalGeometryPVariationalPrinciple.Gates.P0EFTJanusMappingTorusCanonicalPhysicalScalarCanonicalStandardBoundaryResolventClosure4D

/-!
# Standard boundaries for the transport-generated normal Green endpoint

Separated, Dirichlet, Neumann and constant real Robin realizations are exposed
for the endpoint whose normal Green density is generated by one universal
half-collar transport.
-/

namespace JanusFormal
namespace P0EFTJanusMappingTorusCanonicalPhysicalScalarIntrinsicWaveTransportedNormalStandardBoundaryFinalClosure4D

set_option autoImplicit false
noncomputable section

open Set Topology MeasureTheory
open P0EFTJanusMappingTorusCanonicalPhysicalScalarFirstSheetHilbertTrace4D
open P0EFTJanusMappingTorusCanonicalPhysicalScalarIntrinsicWaveTransportedNormalFinalClosure4D
open P0EFTJanusMappingTorusCanonicalPhysicalScalarCanonicalStandardBoundaryResolventClosure4D
open P0EFTJanusMappingTorusCanonicalPhysicalScalarFiniteCoordinateRellich4D
open P0EFTJanusMappingTorusScalarHilbertBoundarySymplectic4D
open P0EFTJanusMappingTorusScalarAbstractLagrangianBoundary4D
open P0EFTJanusMappingTorusScalarCompletedBoundaryTripleExternalPositiveShiftedForm4D

universe e

variable (period : Real) (hPeriod : period ≠ 0)
variable {massSquared : Real}
variable {Energy : Type e}
  [NormedAddCommGroup Energy] [NormedSpace Real Energy]

private abbrev BoundaryL2 := CanonicalPhysicalScalarFirstSheetL2 period

private abbrev BulkL2 :=
  P0EFTJanusMappingTorusCanonicalPhysicalBulkL2H1Bridge4D.CanonicalPhysicalBulkL2
    period hPeriod

/-- Final transported-normal data for one separated boundary condition. -/
structure CanonicalPhysicalScalarIntrinsicWaveTransportedNormalSeparatedFinalData
    (massSquared a b : Real)
    (hNondegenerate : a ≠ 0 ∨ b ≠ 0)
    (Energy : Type e)
    [NormedAddCommGroup Energy] [NormedSpace Real Energy] where
  geometric :
    P0EFTJanusMappingTorusCanonicalPhysicalScalarIntrinsicWaveTransportedNormalGreen4D.CanonicalPhysicalScalarIntrinsicWaveTransportedNormalGreenData
      period hPeriod massSquared
  energyIdentity : geometric.greenCore.ScalarRemainderEnergyIdentityData
    period hPeriod
  eulerCoefficientOperators :
    geometric.toCanonicalNormalGreenData.toNormalTangentialGreenData.toIntrinsicWaveLocalGreenData.toCanonicalLocalDivergenceData.toCanonicalWaveCauchyJetData.toCanonicalCauchyJetCompatibilityData.toCompatibilityData.toCauchyJetGeometricData.CauchyJetEulerSixCanonicalL2OperatorData
      period hPeriod
  referenceParameter : Real
  shiftedPositiveDecomposition :
    (P0EFTJanusMappingTorusCanonicalPhysicalScalarProgramPFinalObligations4D.assembleCanonicalPhysicalScalarBoundaryData
      period hPeriod geometric.toCanonicalNormalGreenData energyIdentity
        eulerCoefficientOperators).triple
      |>.LagrangianShiftedExternalPositiveDecompositionData
        (canonicalPhysicalScalarSeparatedCondition
          period a b hNondegenerate)
        referenceParameter Energy
  finiteCoordinateRellich : CanonicalPhysicalScalarFiniteCoordinateRellichData
    period hPeriod

namespace CanonicalPhysicalScalarIntrinsicWaveTransportedNormalSeparatedFinalData

/-- Conversion to the generic transported-normal endpoint. -/
def toFinalData
    {a b : Real} {hNondegenerate : a ≠ 0 ∨ b ≠ 0}
    (data : CanonicalPhysicalScalarIntrinsicWaveTransportedNormalSeparatedFinalData
      period hPeriod massSquared a b hNondegenerate Energy) :
    CanonicalPhysicalScalarIntrinsicWaveTransportedNormalFinalData
      period hPeriod massSquared Energy where
  geometric := data.geometric
  energyIdentity := data.energyIdentity
  eulerCoefficientOperators := data.eulerCoefficientOperators
  condition := canonicalPhysicalScalarSeparatedCondition
    period a b hNondegenerate
  referenceParameter := data.referenceParameter
  shiftedPositiveDecomposition := data.shiftedPositiveDecomposition
  finiteCoordinateRellich := data.finiteCoordinateRellich

/-- Membership is exactly the separated completed Riesz constraint. -/
theorem mem_lagrangianDomainSubmodule_iff
    {a b : Real} {hNondegenerate : a ≠ 0 ∨ b ≠ 0}
    (data : CanonicalPhysicalScalarIntrinsicWaveTransportedNormalSeparatedFinalData
      period hPeriod massSquared a b hNondegenerate Energy)
    (field : data.toFinalData.triple.MaximalDomain) :
    field ∈ data.toFinalData.triple.lagrangianDomainSubmodule
        (canonicalPhysicalScalarSeparatedCondition
          period a b hNondegenerate) ↔
      a • (data.toFinalData.completedBoundaryTrace period hPeriod field).1 +
        b • (data.toFinalData.completedBoundaryTrace period hPeriod field).2 = 0 := by
  change data.toFinalData.completedBoundaryTrace period hPeriod field ∈
      canonicalScalarHilbertSeparatedBoundarySubmodule
        (Trace := BoundaryL2 period) a b ↔ _
  exact mem_canonicalScalarHilbertSeparatedBoundarySubmodule
    (Trace := BoundaryL2 period) a b _

/-- Actual Hilbert self-adjointness. -/
theorem actualAdjointDomain_eq
    {a b : Real} {hNondegenerate : a ≠ 0 ∨ b ≠ 0}
    (data : CanonicalPhysicalScalarIntrinsicWaveTransportedNormalSeparatedFinalData
      period hPeriod massSquared a b hNondegenerate Energy) :
    data.toFinalData.triple.actualAdjointDomain
        (canonicalPhysicalScalarSeparatedCondition
          period a b hNondegenerate) =
      data.toFinalData.triple.realizationDomain
        (canonicalPhysicalScalarSeparatedCondition
          period a b hNondegenerate) :=
  data.toFinalData.actualAdjointDomain_eq period hPeriod

/-- Classical source solution. -/
noncomputable def sourceSolution
    {a b : Real} {hNondegenerate : a ≠ 0 ∨ b ≠ 0}
    (data : CanonicalPhysicalScalarIntrinsicWaveTransportedNormalSeparatedFinalData
      period hPeriod massSquared a b hNondegenerate Energy) :=
  data.toFinalData.sourceSolution period hPeriod

/-- Strong shifted source equation. -/
theorem sourceSolution_equation
    {a b : Real} {hNondegenerate : a ≠ 0 ∨ b ≠ 0}
    (data : CanonicalPhysicalScalarIntrinsicWaveTransportedNormalSeparatedFinalData
      period hPeriod massSquared a b hNondegenerate Energy)
    (source : BulkL2 period hPeriod) :
    data.toFinalData.triple.lagrangianShiftedOperator
        (canonicalPhysicalScalarSeparatedCondition
          period a b hNondegenerate)
        data.referenceParameter
        (data.sourceSolution period hPeriod source) = source :=
  data.toFinalData.sourceSolution_equation period hPeriod source

/-- Unique global minimizer. -/
theorem sourceSolution_unique_minimizer
    {a b : Real} {hNondegenerate : a ≠ 0 ∨ b ≠ 0}
    (data : CanonicalPhysicalScalarIntrinsicWaveTransportedNormalSeparatedFinalData
      period hPeriod massSquared a b hNondegenerate Energy)
    (source : BulkL2 period hPeriod) :
    (∀ field : data.toFinalData.triple.lagrangianDomainSubmodule
        (canonicalPhysicalScalarSeparatedCondition
          period a b hNondegenerate),
      data.toFinalData.triple.lagrangianSourceAction
          (canonicalPhysicalScalarSeparatedCondition
            period a b hNondegenerate)
          data.referenceParameter source
          (data.sourceSolution period hPeriod source) ≤
        data.toFinalData.triple.lagrangianSourceAction
          (canonicalPhysicalScalarSeparatedCondition
            period a b hNondegenerate)
          data.referenceParameter source field) ∧
      (∀ field : data.toFinalData.triple.lagrangianDomainSubmodule
          (canonicalPhysicalScalarSeparatedCondition
            period a b hNondegenerate),
        data.toFinalData.triple.lagrangianSourceAction
            (canonicalPhysicalScalarSeparatedCondition
              period a b hNondegenerate)
            data.referenceParameter source field =
          data.toFinalData.triple.lagrangianSourceAction
            (canonicalPhysicalScalarSeparatedCondition
              period a b hNondegenerate)
            data.referenceParameter source
            (data.sourceSolution period hPeriod source) →
        field = data.sourceSolution period hPeriod source) :=
  data.toFinalData.sourceSolution_unique_minimizer period hPeriod source

/-- Gaussian generating functional. -/
def gaussianGeneratingFunctional
    {a b : Real} {hNondegenerate : a ≠ 0 ∨ b ≠ 0}
    (data : CanonicalPhysicalScalarIntrinsicWaveTransportedNormalSeparatedFinalData
      period hPeriod massSquared a b hNondegenerate Energy)
    (source : BulkL2 period hPeriod) : Real :=
  data.toFinalData.gaussianGeneratingFunctional period hPeriod source

/-- On-shell Gaussian identity and positivity. -/
theorem gaussian_certificate
    {a b : Real} {hNondegenerate : a ≠ 0 ∨ b ≠ 0}
    (data : CanonicalPhysicalScalarIntrinsicWaveTransportedNormalSeparatedFinalData
      period hPeriod massSquared a b hNondegenerate Energy)
    (source : BulkL2 period hPeriod) :
    data.gaussianGeneratingFunctional period hPeriod source =
        -data.toFinalData.triple.lagrangianSourceAction
          (canonicalPhysicalScalarSeparatedCondition
            period a b hNondegenerate)
          data.referenceParameter source
          (data.sourceSolution period hPeriod source) ∧
      0 ≤ data.gaussianGeneratingFunctional period hPeriod source :=
  data.toFinalData.gaussian_certificate period hPeriod source

/-- Complete separated transport-generated certificate. -/
theorem finalProgramP_certificate
    {a b : Real} {hNondegenerate : a ≠ 0 ∨ b ≠ 0}
    (data : CanonicalPhysicalScalarIntrinsicWaveTransportedNormalSeparatedFinalData
      period hPeriod massSquared a b hNondegenerate Energy)
    (source : BulkL2 period hPeriod) :
    (∀ field test,
      Integrable (data.geometric.normalDensity period hPeriod field test)
        (P0EFTJanusMappingTorusCanonicalLatitudeCauchyJetProductCoarea4D.canonicalLatitudeCauchyJetProductMeasure
          period)) ∧
      data.toFinalData.triple.actualAdjointDomain
          (canonicalPhysicalScalarSeparatedCondition
            period a b hNondegenerate) =
        data.toFinalData.triple.realizationDomain
          (canonicalPhysicalScalarSeparatedCondition
            period a b hNondegenerate) ∧
      data.toFinalData.triple.lagrangianShiftedOperator
          (canonicalPhysicalScalarSeparatedCondition
            period a b hNondegenerate)
          data.referenceParameter
          (data.sourceSolution period hPeriod source) = source ∧
      (∀ field : data.toFinalData.triple.lagrangianDomainSubmodule
          (canonicalPhysicalScalarSeparatedCondition
            period a b hNondegenerate),
        data.toFinalData.triple.lagrangianSourceAction
            (canonicalPhysicalScalarSeparatedCondition
              period a b hNondegenerate)
            data.referenceParameter source
            (data.sourceSolution period hPeriod source) ≤
          data.toFinalData.triple.lagrangianSourceAction
            (canonicalPhysicalScalarSeparatedCondition
              period a b hNondegenerate)
            data.referenceParameter source field) ∧
      0 ≤ data.gaussianGeneratingFunctional period hPeriod source :=
  ⟨fun field test =>
      (data.geometric.toTransportedNormalDensityData period hPeriod)
        |>.normalDensity_integrable period hPeriod field test,
    data.actualAdjointDomain_eq period hPeriod,
    data.sourceSolution_equation period hPeriod source,
    (data.sourceSolution_unique_minimizer period hPeriod source).1,
    (data.gaussian_certificate period hPeriod source).2⟩

end CanonicalPhysicalScalarIntrinsicWaveTransportedNormalSeparatedFinalData

/-- Dirichlet endpoint. -/
abbrev CanonicalPhysicalScalarIntrinsicWaveTransportedNormalDirichletFinalData
    (massSquared : Real) (Energy : Type e)
    [NormedAddCommGroup Energy] [NormedSpace Real Energy] :=
  CanonicalPhysicalScalarIntrinsicWaveTransportedNormalSeparatedFinalData
    period hPeriod massSquared 1 0 (Or.inl one_ne_zero) Energy

/-- Neumann endpoint. -/
abbrev CanonicalPhysicalScalarIntrinsicWaveTransportedNormalNeumannFinalData
    (massSquared : Real) (Energy : Type e)
    [NormedAddCommGroup Energy] [NormedSpace Real Energy] :=
  CanonicalPhysicalScalarIntrinsicWaveTransportedNormalSeparatedFinalData
    period hPeriod massSquared 0 1 (Or.inr one_ne_zero) Energy

/-- Constant Robin endpoint. -/
abbrev CanonicalPhysicalScalarIntrinsicWaveTransportedNormalRobinFinalData
    (massSquared coefficient : Real) (Energy : Type e)
    [NormedAddCommGroup Energy] [NormedSpace Real Energy] :=
  CanonicalPhysicalScalarIntrinsicWaveTransportedNormalSeparatedFinalData
    period hPeriod massSquared (-coefficient) 1 (Or.inr one_ne_zero) Energy

namespace CanonicalPhysicalScalarIntrinsicWaveTransportedNormalSeparatedFinalData

/-- Dirichlet domain. -/
theorem mem_dirichletDomain_iff
    (data : CanonicalPhysicalScalarIntrinsicWaveTransportedNormalDirichletFinalData
      period hPeriod massSquared Energy)
    (field : data.toFinalData.triple.MaximalDomain) :
    field ∈ data.toFinalData.triple.lagrangianDomainSubmodule
        (canonicalPhysicalScalarDirichletCondition period) ↔
      (data.toFinalData.completedBoundaryTrace period hPeriod field).1 = 0 := by
  change data.toFinalData.completedBoundaryTrace period hPeriod field ∈
      canonicalScalarHilbertDirichletBoundarySubmodule
        (Trace := BoundaryL2 period) ↔ _
  exact mem_canonicalScalarHilbertDirichletBoundarySubmodule
    (Trace := BoundaryL2 period) _

/-- Neumann domain. -/
theorem mem_neumannDomain_iff
    (data : CanonicalPhysicalScalarIntrinsicWaveTransportedNormalNeumannFinalData
      period hPeriod massSquared Energy)
    (field : data.toFinalData.triple.MaximalDomain) :
    field ∈ data.toFinalData.triple.lagrangianDomainSubmodule
        (canonicalPhysicalScalarNeumannCondition period) ↔
      (data.toFinalData.completedBoundaryTrace period hPeriod field).2 = 0 := by
  change data.toFinalData.completedBoundaryTrace period hPeriod field ∈
      canonicalScalarHilbertNeumannBoundarySubmodule
        (Trace := BoundaryL2 period) ↔ _
  exact mem_canonicalScalarHilbertNeumannBoundarySubmodule
    (Trace := BoundaryL2 period) _

/-- Robin domain. -/
theorem mem_robinDomain_iff
    (coefficient : Real)
    (data : CanonicalPhysicalScalarIntrinsicWaveTransportedNormalRobinFinalData
      period hPeriod massSquared coefficient Energy)
    (field : data.toFinalData.triple.MaximalDomain) :
    field ∈ data.toFinalData.triple.lagrangianDomainSubmodule
        (canonicalPhysicalScalarRobinCondition period coefficient) ↔
      (data.toFinalData.completedBoundaryTrace period hPeriod field).2 =
        coefficient •
          (data.toFinalData.completedBoundaryTrace period hPeriod field).1 := by
  change data.toFinalData.completedBoundaryTrace period hPeriod field ∈
      canonicalScalarHilbertRobinBoundarySubmodule
        (Trace := BoundaryL2 period) coefficient ↔ _
  exact mem_canonicalScalarHilbertRobinBoundarySubmodule
    (Trace := BoundaryL2 period) coefficient _

end CanonicalPhysicalScalarIntrinsicWaveTransportedNormalSeparatedFinalData

/-- Marker for standard transport-generated boundary families. -/
theorem canonicalPhysicalScalarIntrinsicWaveTransportedNormalStandardBoundaryFinalClosure_available : True :=
  trivial

end
end P0EFTJanusMappingTorusCanonicalPhysicalScalarIntrinsicWaveTransportedNormalStandardBoundaryFinalClosure4D
end JanusFormal
