import Mathlib

/-!
# Cyclic reconstruction from all boundary moments

Equal Gram data on total families construct a unique linear isometry equivalence
of real Hilbert spaces. Applied to bounded self-adjoint bulk operators and their
boundary-generated Krylov families, equality of all boundary moments determines
the bulk operator and coupling up to this equivalence. Cyclicity is essential:
the theorem does not claim to recover an invisible orthogonal bulk sector.
-/

namespace JanusFormal
namespace P0EFTJanusCyclicMomentReconstruction

set_option autoImplicit false
noncomputable section

open scoped InnerProductSpace

variable {H₁ H₂ : Type*}
  [NormedAddCommGroup H₁] [InnerProductSpace ℝ H₁]
  [NormedAddCommGroup H₂] [InnerProductSpace ℝ H₂]
  {I : Type*}

/-- Equality of generator Gram data propagates to all finite combinations. -/
theorem gram_linearCombination
    (v₁ : I → H₁) (v₂ : I → H₂)
    (hgram : ∀ i j, ⟪v₁ i, v₁ j⟫_ℝ = ⟪v₂ i, v₂ j⟫_ℝ)
    (c d : I →₀ ℝ) :
    ⟪Finsupp.linearCombination ℝ v₁ c, Finsupp.linearCombination ℝ v₁ d⟫_ℝ =
      ⟪Finsupp.linearCombination ℝ v₂ c, Finsupp.linearCombination ℝ v₂ d⟫_ℝ := by
  classical
  simp only [Finsupp.linearCombination_apply, Finsupp.sum, inner_sum, sum_inner,
    real_inner_smul_left, real_inner_smul_right, hgram]

theorem denseRange_linearCombination (v : I → H₁)
    (htotal : Dense (Submodule.span ℝ (Set.range v) : Set H₁)) :
    DenseRange (Finsupp.linearCombination ℝ v) := by
  change Dense (LinearMap.range (Finsupp.linearCombination ℝ v) : Set H₁)
  simpa only [Finsupp.range_linearCombination] using htotal

variable [CompleteSpace H₁] [CompleteSpace H₂]

/-- The isometry is constructed by extending the identity on coefficient vectors;
the two linear-combination maps may have kernels. Equal Gram data identify them. -/
def gramEquivalence
    (v₁ : I → H₁) (v₂ : I → H₂)
    (hgram : ∀ i j, ⟪v₁ i, v₁ j⟫_ℝ = ⟪v₂ i, v₂ j⟫_ℝ)
    (htotal₁ : Dense (Submodule.span ℝ (Set.range v₁) : Set H₁))
    (htotal₂ : Dense (Submodule.span ℝ (Set.range v₂) : Set H₂)) :
    H₁ ≃ₗᵢ[ℝ] H₂ :=
  (LinearEquiv.refl ℝ (I →₀ ℝ)).extendOfIsometry
    (Finsupp.linearCombination ℝ v₁) (Finsupp.linearCombination ℝ v₂)
    (denseRange_linearCombination v₁ htotal₁)
    (denseRange_linearCombination v₂ htotal₂) (fun c => by
      simp only [LinearEquiv.refl_apply]
      rw [norm_eq_sqrt_real_inner, norm_eq_sqrt_real_inner,
        gram_linearCombination v₁ v₂ hgram])

theorem gramEquivalence_linearCombination
    (v₁ : I → H₁) (v₂ : I → H₂)
    (hgram : ∀ i j, ⟪v₁ i, v₁ j⟫_ℝ = ⟪v₂ i, v₂ j⟫_ℝ)
    (htotal₁ : Dense (Submodule.span ℝ (Set.range v₁) : Set H₁))
    (htotal₂ : Dense (Submodule.span ℝ (Set.range v₂) : Set H₂)) (c : I →₀ ℝ) :
    gramEquivalence v₁ v₂ hgram htotal₁ htotal₂ (Finsupp.linearCombination ℝ v₁ c) =
      Finsupp.linearCombination ℝ v₂ c := by
  exact LinearEquiv.extendOfIsometry_eq ..

theorem gramEquivalence_generator
    (v₁ : I → H₁) (v₂ : I → H₂)
    (hgram : ∀ i j, ⟪v₁ i, v₁ j⟫_ℝ = ⟪v₂ i, v₂ j⟫_ℝ)
    (htotal₁ : Dense (Submodule.span ℝ (Set.range v₁) : Set H₁))
    (htotal₂ : Dense (Submodule.span ℝ (Set.range v₂) : Set H₂)) (i : I) :
    gramEquivalence v₁ v₂ hgram htotal₁ htotal₂ (v₁ i) = v₂ i := by
  simpa using gramEquivalence_linearCombination v₁ v₂ hgram htotal₁ htotal₂
    (Finsupp.single i 1)

omit [CompleteSpace H₁] [CompleteSpace H₂] in
/-- A bounded linear map is determined by its values on a total family. -/
theorem continuousLinearMap_eq_of_total
    (v : I → H₁) (htotal : Dense (Submodule.span ℝ (Set.range v) : Set H₁))
    (f g : H₁ →L[ℝ] H₂) (h : ∀ i, f (v i) = g (v i)) : f = g := by
  apply DFunLike.coe_injective
  apply (denseRange_linearCombination v htotal).equalizer f.continuous g.continuous
  funext c
  simp only [Function.comp_apply, Finsupp.linearCombination_apply, Finsupp.sum,
    map_sum, map_smul, h]

theorem gramEquivalence_unique
    (v₁ : I → H₁) (v₂ : I → H₂)
    (hgram : ∀ i j, ⟪v₁ i, v₁ j⟫_ℝ = ⟪v₂ i, v₂ j⟫_ℝ)
    (htotal₁ : Dense (Submodule.span ℝ (Set.range v₁) : Set H₁))
    (htotal₂ : Dense (Submodule.span ℝ (Set.range v₂) : Set H₂))
    (U : H₁ ≃ₗᵢ[ℝ] H₂) (hU : ∀ i, U (v₁ i) = v₂ i) :
    U = gramEquivalence v₁ v₂ hgram htotal₁ htotal₂ := by
  have heq := continuousLinearMap_eq_of_total v₁ htotal₁ U.toLinearIsometry.toContinuousLinearMap
    (gramEquivalence v₁ v₂ hgram htotal₁ htotal₂).toLinearIsometry.toContinuousLinearMap
    (fun i => (hU i).trans (gramEquivalence_generator v₁ v₂ hgram htotal₁ htotal₂ i).symm)
  ext x
  exact congrArg (fun f : H₁ →L[ℝ] H₂ => f x) heq

variable {Boundary : Type*}

/-- The family generated by all powers of the bounded bulk operator. The boundary
marking may in particular be a continuous linear coupling. -/
def krylovFamily (A : H₁ →L[ℝ] H₁) (B : Boundary → H₁) : ℕ × Boundary → H₁ :=
  fun nq => (A ^ nq.1) (B nq.2)

/-- Every bulk direction is approximated by boundary-generated finite combinations. -/
def IsCyclic (A : H₁ →L[ℝ] H₁) (B : Boundary → H₁) : Prop :=
  Dense (Submodule.span ℝ (Set.range (krylovFamily A B)) : Set H₁)

/-- The complete boundary moment sequence, including the zeroth moment. -/
def boundaryMoment (A : H₁ →L[ℝ] H₁) (B : Boundary → H₁)
    (n : ℕ) (q r : Boundary) : ℝ :=
  ⟪B q, (A ^ n) (B r)⟫_ℝ

theorem inner_pow (A : H₁ →L[ℝ] H₁) (hA : IsSelfAdjoint A)
    (n : ℕ) (x y : H₁) : ⟪(A ^ n) x, y⟫_ℝ = ⟪x, (A ^ n) y⟫_ℝ := by
  induction n generalizing x y with
  | zero => simp
  | succ n ih =>
    calc
      ⟪(A ^ (n + 1)) x, y⟫_ℝ = ⟪A ((A ^ n) x), y⟫_ℝ := by
        rw [pow_succ', mul_apply_eq_comp]
      _ = ⟪(A ^ n) x, A y⟫_ℝ := hA.isSymmetric _ _
      _ = ⟪x, (A ^ n) (A y)⟫_ℝ := ih _ _
      _ = ⟪x, (A ^ (n + 1)) y⟫_ℝ := by rw [pow_succ, mul_apply_eq_comp]

theorem krylov_gram (A : H₁ →L[ℝ] H₁) (hA : IsSelfAdjoint A)
    (B : Boundary → H₁) (i j : ℕ × Boundary) :
    ⟪krylovFamily A B i, krylovFamily A B j⟫_ℝ =
      boundaryMoment A B (i.1 + j.1) i.2 j.2 := by
  unfold krylovFamily boundaryMoment
  rw [inner_pow A hA, pow_add, mul_apply_eq_comp]

omit [CompleteSpace H₁] [CompleteSpace H₂] in
theorem intertwiner_maps_krylov
    (A₁ : H₁ →L[ℝ] H₁) (A₂ : H₂ →L[ℝ] H₂)
    (B₁ : Boundary → H₁) (B₂ : Boundary → H₂)
    (U : H₁ ≃ₗᵢ[ℝ] H₂) (hB : ∀ q, U (B₁ q) = B₂ q)
    (hA : ∀ x, U (A₁ x) = A₂ (U x)) (i : ℕ × Boundary) :
    U (krylovFamily A₁ B₁ i) = krylovFamily A₂ B₂ i := by
  rcases i with ⟨n, q⟩
  change U ((A₁ ^ n) (B₁ q)) = (A₂ ^ n) (B₂ q)
  induction n with
  | zero => simpa using hB q
  | succ n ih => simp only [pow_succ', mul_apply_eq_comp, hA, ih]

omit [CompleteSpace H₁] [CompleteSpace H₂] in
/-- A marking-preserving isometric intertwiner preserves every boundary moment. -/
theorem intertwiner_preserves_moments
    (A₁ : H₁ →L[ℝ] H₁) (A₂ : H₂ →L[ℝ] H₂)
    (B₁ : Boundary → H₁) (B₂ : Boundary → H₂)
    (U : H₁ ≃ₗᵢ[ℝ] H₂) (hB : ∀ q, U (B₁ q) = B₂ q)
    (hA : ∀ x, U (A₁ x) = A₂ (U x)) (n : ℕ) (q r : Boundary) :
    boundaryMoment A₁ B₁ n q r = boundaryMoment A₂ B₂ n q r := by
  have hK : U ((A₁ ^ n) (B₁ r)) = (A₂ ^ n) (B₂ r) :=
    intertwiner_maps_krylov A₁ A₂ B₁ B₂ U hB hA (n, r)
  unfold boundaryMoment
  rw [← U.inner_map_map, hB, hK]

/-- Complete moments reconstruct a cyclic bounded self-adjoint realization,
including its boundary marking, up to a unique real Hilbert-space isometry.
No finite-dimensionality or pre-existing equivalence is assumed. -/
theorem moments_determine_cyclic_realization
    (A₁ : H₁ →L[ℝ] H₁) (A₂ : H₂ →L[ℝ] H₂)
    (hA₁ : IsSelfAdjoint A₁) (hA₂ : IsSelfAdjoint A₂)
    (B₁ : Boundary → H₁) (B₂ : Boundary → H₂)
    (hcyclic₁ : IsCyclic A₁ B₁) (hcyclic₂ : IsCyclic A₂ B₂)
    (hmom : ∀ n q r, boundaryMoment A₁ B₁ n q r = boundaryMoment A₂ B₂ n q r) :
    ∃! U : H₁ ≃ₗᵢ[ℝ] H₂,
      (∀ q, U (B₁ q) = B₂ q) ∧ (∀ x, U (A₁ x) = A₂ (U x)) := by
  have hgram : ∀ i j, ⟪krylovFamily A₁ B₁ i, krylovFamily A₁ B₁ j⟫_ℝ =
      ⟪krylovFamily A₂ B₂ i, krylovFamily A₂ B₂ j⟫_ℝ := by
    intro i j
    rw [krylov_gram A₁ hA₁, krylov_gram A₂ hA₂, hmom]
  let U := gramEquivalence (krylovFamily A₁ B₁) (krylovFamily A₂ B₂)
    hgram hcyclic₁ hcyclic₂
  have hU : ∀ i, U (krylovFamily A₁ B₁ i) = krylovFamily A₂ B₂ i :=
    gramEquivalence_generator _ _ _ _ _
  refine ⟨U, ⟨?_, ?_⟩, ?_⟩
  · intro q
    simpa [krylovFamily] using hU (0, q)
  · have hcomp : U.toLinearIsometry.toContinuousLinearMap.comp A₁ =
        A₂.comp U.toLinearIsometry.toContinuousLinearMap := by
      apply continuousLinearMap_eq_of_total (krylovFamily A₁ B₁) hcyclic₁
      rintro ⟨n, q⟩
      change U (A₁ ((A₁ ^ n) (B₁ q))) = A₂ (U ((A₁ ^ n) (B₁ q)))
      rw [show U ((A₁ ^ n) (B₁ q)) = (A₂ ^ n) (B₂ q) from hU (n, q)]
      simpa [krylovFamily, pow_succ', mul_apply_eq_comp] using hU (n + 1, q)
    intro x
    exact congrArg (fun f : H₁ →L[ℝ] H₂ => f x) hcomp
  · intro V hV
    apply gramEquivalence_unique
    exact intertwiner_maps_krylov A₁ A₂ B₁ B₂ V hV.1 hV.2

/-- Exact classification of cyclic bounded self-adjoint bulk realizations by
their entire boundary moment sequence. The direct boundary term is separate. -/
theorem cyclic_equivalence_iff_moments
    (A₁ : H₁ →L[ℝ] H₁) (A₂ : H₂ →L[ℝ] H₂)
    (hA₁ : IsSelfAdjoint A₁) (hA₂ : IsSelfAdjoint A₂)
    (B₁ : Boundary → H₁) (B₂ : Boundary → H₂)
    (hcyclic₁ : IsCyclic A₁ B₁) (hcyclic₂ : IsCyclic A₂ B₂) :
    (∃ U : H₁ ≃ₗᵢ[ℝ] H₂,
      (∀ q, U (B₁ q) = B₂ q) ∧ (∀ x, U (A₁ x) = A₂ (U x))) ↔
      ∀ n q r, boundaryMoment A₁ B₁ n q r = boundaryMoment A₂ B₂ n q r := by
  constructor
  · rintro ⟨U, hB, hA⟩
    exact intertwiner_preserves_moments A₁ A₂ B₁ B₂ U hB hA
  · intro hmom
    exact (moments_determine_cyclic_realization A₁ A₂ hA₁ hA₂ B₁ B₂
      hcyclic₁ hcyclic₂ hmom).exists

end
end P0EFTJanusCyclicMomentReconstruction
end JanusFormal
