import Mathlib.Topology.VectorBundle.Constructions
import JanusFormal.Branches.FundamentalGeometryPVariationalPrinciple.Gates.P0EFTJanusProgramPSelfAdjointFredholmFullComplexCoordinate4D
import JanusFormal.Branches.FundamentalGeometryPVariationalPrinciple.Gates.P0EFTJanusProgramPSelfAdjointFredholmFullTensorCoordinateTransport4D

/-!
# Topological vector bundle of the full Fredholm--zeta determinant family

The canonical complex coordinate of every full determinant fibre transports the
standard topology of `Complex` to that fibre.  These coordinates form one
global pretrivialization over the real family parameter, so the dependent
family

`a ↦ FullDet(H_a)`

is registered as a genuine Mathlib complex `VectorBundle`.
-/

namespace JanusFormal
namespace P0EFTJanusProgramPSelfAdjointFredholmFullDeterminantTopologicalBundle4D
end P0EFTJanusProgramPSelfAdjointFredholmFullDeterminantTopologicalBundle4D

namespace P0EFTJanusProgramPSelfAdjointFredholmDeterminantLineFamily4D

set_option autoImplicit false
set_option maxHeartbeats 9000000
set_option synthInstance.maxHeartbeats 4500000
noncomputable section

open Bundle Topology
open P0EFTJanusProgramPSelfAdjointFredholmDeterminantLineFamily4D
open P0EFTJanusProgramPSelfAdjointFredholmFullTensorDeterminantFiber4D
open P0EFTJanusProgramPSelfAdjointFredholmFullComplexCoordinate4D
open P0EFTJanusProgramPSelfAdjointFredholmFullTensorTransport4D
open P0EFTJanusProgramPSelfAdjointFredholmFullTensorCoordinateTransport4D

variable {E : Type*} {ZeroMode : Type}
  [NormedAddCommGroup E]
  [InnerProductSpace Real E] [CompleteSpace E]
  [Fintype ZeroMode] [DecidableEq ZeroMode] [LinearOrder ZeroMode]

namespace SelfAdjointFredholmDeterminantFamilyData

/-- Dependent full determinant fibre over the real family parameter. -/
abbrev FullDeterminantFiber
    {operator : Real → E →L[Real] E}
    (data : SelfAdjointFredholmDeterminantFamilyData operator ZeroMode)
    (parameter : Real) :=
  data.fullTensorDeterminantLine parameter

/-- Fibre topology transported from `Complex` by the canonical full determinant
coordinate. -/
noncomputable instance fullDeterminantFiberTopology
    {operator : Real → E →L[Real] E}
    (data : SelfAdjointFredholmDeterminantFamilyData operator ZeroMode)
    (parameter : Real) :
    TopologicalSpace (data.FullDeterminantFiber parameter) :=
  TopologicalSpace.induced
    (data.fullTensorDeterminantCoordinateEquiv parameter) inferInstance

/-- The canonical full determinant coordinate is inducing by construction. -/
theorem fullTensorDeterminantCoordinateEquiv_isInducing
    {operator : Real → E →L[Real] E}
    (data : SelfAdjointFredholmDeterminantFamilyData operator ZeroMode)
    (parameter : Real) :
    IsInducing (data.fullTensorDeterminantCoordinateEquiv parameter) := by
  exact ⟨rfl⟩

/-- Canonical homeomorphism between one full determinant fibre and `Complex`. -/
noncomputable def fullTensorDeterminantCoordinateHomeomorph
    {operator : Real → E →L[Real] E}
    (data : SelfAdjointFredholmDeterminantFamilyData operator ZeroMode)
    (parameter : Real) :
    data.FullDeterminantFiber parameter ≃ₜ Complex :=
  (data.fullTensorDeterminantCoordinateEquiv parameter).toEquiv.toHomeomorphOfIsInducing
      (data.fullTensorDeterminantCoordinateEquiv_isInducing parameter)

/-- Global pretrivialization supplied by the canonical full determinant
coordinate. -/
noncomputable def fullDeterminantPretrivialization
    {operator : Real → E →L[Real] E}
    (data : SelfAdjointFredholmDeterminantFamilyData operator ZeroMode) :
    Pretrivialization Complex (π Complex data.FullDeterminantFiber) where
  toFun point :=
    (point.proj,
      data.fullTensorDeterminantCoordinateEquiv point.proj point.2)
  invFun coordinate :=
    ⟨coordinate.1,
      (data.fullTensorDeterminantCoordinateEquiv coordinate.1).symm coordinate.2⟩
  source := Set.univ
  target := Set.univ
  map_source' _ _ := Set.mem_univ _
  map_target' _ _ := Set.mem_univ _
  left_inv' point _ := by
    cases point
    simp
  right_inv' coordinate _ := by
    simp
  open_target := isOpen_univ
  baseSet := Set.univ
  open_baseSet := isOpen_univ
  source_eq := by simp
  target_eq := by simp
  proj_toFun _ _ := rfl

/-- The global full determinant pretrivialization is complex-linear on every
fibre. -/
theorem fullDeterminantPretrivialization_isLinear
    {operator : Real → E →L[Real] E}
    (data : SelfAdjointFredholmDeterminantFamilyData operator ZeroMode) :
    data.fullDeterminantPretrivialization.IsLinear Complex where
  linear parameter _ :=
    (data.fullTensorDeterminantCoordinateEquiv parameter).isLinear

/-- Vector-prebundle generated by the single canonical coordinate atlas. -/
noncomputable def fullDeterminantVectorPrebundle
    {operator : Real → E →L[Real] E}
    (data : SelfAdjointFredholmDeterminantFamilyData operator ZeroMode) :
    VectorPrebundle Complex Complex data.FullDeterminantFiber where
  pretrivializationAtlas := {data.fullDeterminantPretrivialization}
  pretrivialization_linear' := by
    intro e he
    rw [Set.mem_singleton_iff.mp he]
    exact data.fullDeterminantPretrivialization_isLinear
  pretrivializationAt := fun _ => data.fullDeterminantPretrivialization
  mem_base_pretrivializationAt := by
    simp [fullDeterminantPretrivialization]
  pretrivialization_mem_atlas := by simp
  exists_coordChange := by
    intro first hFirst second hSecond
    rw [Set.mem_singleton_iff.mp hFirst, Set.mem_singleton_iff.mp hSecond]
    refine ⟨fun _ => ContinuousLinearMap.id Complex Complex,
      continuousOn_const, ?_⟩
    intro parameter _ scalar
    simp [fullDeterminantPretrivialization]
  totalSpaceMk_isInducing := by
    intro parameter
    change IsInducing
      (fun value : data.FullDeterminantFiber parameter =>
        (parameter, data.fullTensorDeterminantCoordinateEquiv parameter value))
    exact isInducing_const_prod.2
      (data.fullTensorDeterminantCoordinateEquiv_isInducing parameter)

/-- Total-space topology induced by the canonical determinant coordinate. -/
noncomputable instance fullDeterminantTotalSpaceTopology
    {operator : Real → E →L[Real] E}
    (data : SelfAdjointFredholmDeterminantFamilyData operator ZeroMode) :
    TopologicalSpace (TotalSpace Complex data.FullDeterminantFiber) :=
  data.fullDeterminantVectorPrebundle.totalSpaceTopology

/-- Registered Mathlib fibre-bundle structure. -/
noncomputable instance fullDeterminantFiberBundle
    {operator : Real → E →L[Real] E}
    (data : SelfAdjointFredholmDeterminantFamilyData operator ZeroMode) :
    FiberBundle Complex data.FullDeterminantFiber :=
  data.fullDeterminantVectorPrebundle.toFiberBundle

/-- Registered Mathlib complex vector-bundle structure. -/
noncomputable instance fullDeterminantVectorBundle
    {operator : Real → E →L[Real] E}
    (data : SelfAdjointFredholmDeterminantFamilyData operator ZeroMode) :
    VectorBundle Complex Complex data.FullDeterminantFiber :=
  data.fullDeterminantVectorPrebundle.toVectorBundle

/-- Promoted global trivialization of the full determinant bundle. -/
noncomputable def fullDeterminantGlobalTrivialization
    {operator : Real → E →L[Real] E}
    (data : SelfAdjointFredholmDeterminantFamilyData operator ZeroMode) :
    Trivialization Complex (π Complex data.FullDeterminantFiber) :=
  data.fullDeterminantVectorPrebundle.trivializationOfMemPretrivializationAtlas
    (e := data.fullDeterminantPretrivialization) (by
      exact Set.mem_singleton _)

/-- Global homeomorphism of the full determinant total space with
`Real × Complex`. -/
noncomputable def fullDeterminantTotalSpaceHomeomorph
    {operator : Real → E →L[Real] E}
    (data : SelfAdjointFredholmDeterminantFamilyData operator ZeroMode) :
    TotalSpace Complex data.FullDeterminantFiber ≃ₜ Real × Complex :=
  data.fullDeterminantGlobalTrivialization.toOpenPartialHomeomorph
    |>.toHomeomorphOfSourceEqUnivTargetEqUniv rfl rfl

/-- Public topological full determinant-bundle checkpoint. -/
theorem self_adjoint_fredholm_full_determinant_topological_bundle_gate
    {operator : Real → E →L[Real] E}
    (data : SelfAdjointFredholmDeterminantFamilyData operator ZeroMode) :
    Nonempty (VectorBundle Complex Complex data.FullDeterminantFiber) ∧
      Nonempty (TotalSpace Complex data.FullDeterminantFiber ≃ₜ Real × Complex) :=
  ⟨⟨data.fullDeterminantVectorBundle⟩,
    ⟨data.fullDeterminantTotalSpaceHomeomorph⟩⟩

end SelfAdjointFredholmDeterminantFamilyData

end
end P0EFTJanusProgramPSelfAdjointFredholmDeterminantLineFamily4D
end JanusFormal
