import Mathlib.Analysis.Normed.Algebra.Exponential
import Mathlib.Analysis.Normed.Operator.NormedSpace
import JanusFormal.Branches.FundamentalGeometryPVariationalPrinciple.Gates.P0EFTJanusProgramPFiniteDefectReducedResolventIdentity4D

/-!
# Exact exponential of the reduced finite-defect operator

The reduced operator is bounded on the exact zero-mode complement.  Its Banach
algebra exponential therefore exists without any spectral or heat-kernel
hypothesis:

`U(t) = exp (-t H_red)`.

This file proves the exact one-parameter group law, invertibility and
commutation with `H_red`.  Compactness, nuclearity and trace summability are
not asserted; those are the genuine remaining inputs for determinant and
Quillen constructions.
-/

namespace JanusFormal
namespace P0EFTJanusProgramPFiniteDefectReducedExponential4D

set_option autoImplicit false
noncomputable section

open scoped InnerProduct
open P0EFTJanusProgramPFiniteDefectCoerciveShift4D
open P0EFTJanusProgramPFiniteDefectReducedOperator4D
open P0EFTJanusProgramPFiniteDefectReducedResolvent4D
open P0EFTJanusProgramPFiniteDefectReducedResolventIdentity4D

variable {E : Type*}
  [NormedAddCommGroup E]
  [InnerProductSpace Real E] [CompleteSpace E]

local instance finiteDefectReducedExponentialNormedSpace
    (operator : E →L[Real] E)
    (data : FiniteDefectCoerciveShiftData operator) :
    NormedSpace Real data.projection.ker :=
  (inferInstance : InnerProductSpace Real data.projection.ker).toNormedSpace

local instance finiteDefectReducedExponentialCompleteSpace
    (operator : E →L[Real] E)
    (data : FiniteDefectCoerciveShiftData operator) :
    CompleteSpace data.projection.ker :=
  inferInstance

local instance finiteDefectReducedEndomorphismRatNormedAlgebra
    (operator : E →L[Real] E)
    (data : FiniteDefectCoerciveShiftData operator) :
    NormedAlgebra ℚ
      (data.projection.ker →L[Real] data.projection.ker) :=
  NormedAlgebra.restrictScalars ℚ ℝ _

local instance finiteDefectReducedEndomorphismSMulCommClass
    (operator : E →L[Real] E)
    (data : FiniteDefectCoerciveShiftData operator) :
    SMulCommClass Real
      (data.projection.ker →L[Real] data.projection.ker)
      (data.projection.ker →L[Real] data.projection.ker) where
  smul_comm scalar first second :=
    (Algebra.smul_mul_assoc scalar first second).trans
      (Algebra.mul_smul_comm scalar first second).symm

local instance finiteDefectReducedEndomorphismIsScalarTower
    (operator : E →L[Real] E)
    (data : FiniteDefectCoerciveShiftData operator) :
    IsScalarTower Real
      (data.projection.ker →L[Real] data.projection.ker)
      (data.projection.ker →L[Real] data.projection.ker) where
  smul_assoc := Algebra.smul_mul_assoc

/-- Exact bounded evolution generated by the reduced operator. -/
noncomputable def finiteDefectReducedExponential
    (operator : E →L[Real] E)
    (data : FiniteDefectCoerciveShiftData operator)
    (time : Real) :
    data.projection.ker →L[Real] data.projection.ker :=
  NormedSpace.exp
    ((-time) • finiteDefectReducedOperator operator data)

@[simp]
theorem finiteDefectReducedExponential_zero
    (operator : E →L[Real] E)
    (data : FiniteDefectCoerciveShiftData operator) :
    finiteDefectReducedExponential operator data 0 =
      (1 : data.projection.ker →L[Real] data.projection.ker) := by
  unfold finiteDefectReducedExponential
  have hZero :
      (0 : Real) • finiteDefectReducedOperator operator data = 0 := by
    ext vector
    simp
  rw [neg_zero, hZero, NormedSpace.exp_zero]

/-- The two scalar multiples of one reduced operator commute. -/
private theorem finiteDefectReducedGenerator_commute
    (operator : E →L[Real] E)
    (data : FiniteDefectCoerciveShiftData operator)
    (firstTime secondTime : Real) :
    Commute
      ((-firstTime) • finiteDefectReducedOperator operator data)
      ((-secondTime) • finiteDefectReducedOperator operator data) := by
  exact ((Commute.refl
    (finiteDefectReducedOperator operator data)).smul_left
      (-firstTime)).smul_right (-secondTime)

/-- Exact one-parameter group law. -/
theorem finiteDefectReducedExponential_add
    (operator : E →L[Real] E)
    (data : FiniteDefectCoerciveShiftData operator)
    (firstTime secondTime : Real) :
    finiteDefectReducedExponential operator data (firstTime + secondTime) =
      finiteDefectReducedExponential operator data firstTime *
        finiteDefectReducedExponential operator data secondTime := by
  unfold finiteDefectReducedExponential
  rw [show (-(firstTime + secondTime)) •
      finiteDefectReducedOperator operator data =
        (-firstTime) • finiteDefectReducedOperator operator data +
          (-secondTime) • finiteDefectReducedOperator operator data by
    module]
  exact NormedSpace.exp_add_of_commute
    (finiteDefectReducedGenerator_commute operator data firstTime secondTime)

/-- Every reduced exponential is a unit of the bounded-operator algebra. -/
theorem finiteDefectReducedExponential_isUnit
    (operator : E →L[Real] E)
    (data : FiniteDefectCoerciveShiftData operator)
    (time : Real) :
    IsUnit (finiteDefectReducedExponential operator data time) := by
  exact NormedSpace.isUnit_exp _

/-- Positive and negative times are exact two-sided inverses. -/
theorem finiteDefectReducedExponential_mul_neg
    (operator : E →L[Real] E)
    (data : FiniteDefectCoerciveShiftData operator)
    (time : Real) :
    finiteDefectReducedExponential operator data time *
        finiteDefectReducedExponential operator data (-time) =
      (1 : data.projection.ker →L[Real] data.projection.ker) := by
  rw [← finiteDefectReducedExponential_add]
  simp

/-- Reverse-order inverse identity. -/
theorem finiteDefectReducedExponential_neg_mul
    (operator : E →L[Real] E)
    (data : FiniteDefectCoerciveShiftData operator)
    (time : Real) :
    finiteDefectReducedExponential operator data (-time) *
        finiteDefectReducedExponential operator data time =
      (1 : data.projection.ker →L[Real] data.projection.ker) := by
  rw [← finiteDefectReducedExponential_add]
  simp

/-- The reduced Hessian commutes with its exponential. -/
theorem finiteDefectReducedOperator_commute_exponential
    (operator : E →L[Real] E)
    (data : FiniteDefectCoerciveShiftData operator)
    (time : Real) :
    Commute
      (finiteDefectReducedOperator operator data)
      (finiteDefectReducedExponential operator data time) := by
  unfold finiteDefectReducedExponential
  exact ((Commute.refl
    (finiteDefectReducedOperator operator data)).smul_right (-time)).exp_right

/-- Self-adjointness is preserved by the real reduced exponential. -/
theorem finiteDefectReducedExponential_isSelfAdjoint
    (operator : E →L[Real] E)
    (hSelfAdjoint : IsSelfAdjoint operator)
    (data : FiniteDefectCoerciveShiftData operator)
    (time : Real) :
    IsSelfAdjoint (finiteDefectReducedExponential operator data time) := by
  have hReduced :
      IsSelfAdjoint (finiteDefectReducedOperator operator data) :=
    finiteDefectReducedOperator_isSelfAdjoint operator hSelfAdjoint data
  have hGenerator :
      IsSelfAdjoint ((-time) • finiteDefectReducedOperator operator data) := by
    apply LinearMap.IsSymmetric.isSelfAdjoint
    intro first second
    change inner Real ((-time) •
        finiteDefectReducedOperator operator data first) second =
      inner Real first ((-time) •
        finiteDefectReducedOperator operator data second)
    calc
      inner Real ((-time) •
          finiteDefectReducedOperator operator data first) second =
        (-time) * inner Real
          (finiteDefectReducedOperator operator data first) second :=
        real_inner_smul_left _ _ _
      _ = (-time) * inner Real first
          (finiteDefectReducedOperator operator data second) :=
        congrArg (fun value : Real => (-time) * value)
          (hReduced.isSymmetric first second)
      _ = inner Real first ((-time) •
          finiteDefectReducedOperator operator data second) :=
        (real_inner_smul_right _ _ _).symm
  exact IsSelfAdjoint.exp
    (x := (-time) • finiteDefectReducedOperator operator data)
    hGenerator

/-- Public reduced exponential checkpoint. -/
theorem finite_defect_reduced_exponential_gate
    (operator : E →L[Real] E)
    (hSelfAdjoint : IsSelfAdjoint operator)
    (data : FiniteDefectCoerciveShiftData operator) :
    (∀ firstTime secondTime,
      finiteDefectReducedExponential operator data
          (firstTime + secondTime) =
        finiteDefectReducedExponential operator data firstTime *
          finiteDefectReducedExponential operator data secondTime) ∧
      (∀ time,
        IsUnit (finiteDefectReducedExponential operator data time)) ∧
      (∀ time,
        IsSelfAdjoint (finiteDefectReducedExponential operator data time)) ∧
      (∀ time,
        Commute
          (finiteDefectReducedOperator operator data)
          (finiteDefectReducedExponential operator data time)) :=
  ⟨finiteDefectReducedExponential_add operator data,
    finiteDefectReducedExponential_isUnit operator data,
    finiteDefectReducedExponential_isSelfAdjoint operator hSelfAdjoint data,
    finiteDefectReducedOperator_commute_exponential operator data⟩

end
end P0EFTJanusProgramPFiniteDefectReducedExponential4D
end JanusFormal
