import JanusFormal.Branches.FundamentalGeometryPVariationalPrinciple.Gates.P0EFTJanusMappingTorusCanonicalPhysicalScalarEulerDenseParametrizationClosure4D
import JanusFormal.Branches.FundamentalGeometryPVariationalPrinciple.Gates.P0EFTJanusMappingTorusCanonicalPhysicalScalarCanonicalCauchyJetCompatibilityGreenCore4D

/-!
# Canonical Cauchy-jet Green core from a dense physical parametrization

The faithful physical Euler operator previously entered the canonical Green-core
package through `CanonicalPhysicalScalarEulerCompatibilityData`.  That interface
still contains the consequence that a continuous residual which vanishes almost
everywhere vanishes everywhere.

Here this consequence is generated instead from a continuous dense-range
measure-preserving parametrization by an open-positive source measure.  Thus the
geometric package only asks for:

* Euler overlap compatibility;
* one dense physical measure parametrization;
* density of the canonical periodic and antiperiodic boundary cores;
* the global Euler-skew/divergence identity.

The resulting object is definitionally the existing canonical Cauchy-jet Green
core, but its Euler faithfulness is no longer an independent field.
-/

namespace JanusFormal
namespace P0EFTJanusMappingTorusCanonicalPhysicalScalarCanonicalDenseParametrizedCauchyJetGreenCore4D

set_option autoImplicit false
noncomputable section

open Set Topology MeasureTheory
open P0EFTJanusMappingTorusSmoothFieldDescent4D
open P0EFTJanusMappingTorusCanonicalPhysicalScalarEulerAtlas4D
open P0EFTJanusMappingTorusCanonicalPhysicalScalarEulerGreenL2Reduction4D
open P0EFTJanusMappingTorusCanonicalPhysicalScalarEulerFullSupportReduction4D
open P0EFTJanusMappingTorusCanonicalPhysicalScalarEulerDenseParametrizationClosure4D
open P0EFTJanusMappingTorusCanonicalLatitudeSmoothBoundaryCores4D
open P0EFTJanusMappingTorusCanonicalPhysicalScalarCanonicalCauchyJetCompatibilityGreenCore4D
open P0EFTJanusMappingTorusScalarBoundarySmoothExtensionDensity4D
open P0EFTJanusMappingTorusCutBulkCanonicalDivergenceMeasure4D

universe u

variable (period : Real) (hPeriod : period ≠ 0)
variable {massSquared : Real}

private abbrev ValueCore :=
  CanonicalLatitudeSmoothPeriodicValueCore period
private abbrev NormalCore :=
  CanonicalLatitudeSmoothAntiperiodicNormalCore period

/-- Canonical geometric Green-core data whose Euler faithfulness is generated by
one dense open-positive parametrization of the physical Lorentz volume. -/
structure CanonicalPhysicalScalarCanonicalDenseParametrizedCauchyJetData
    (Source : Type u)
    [TopologicalSpace Source] [MeasurableSpace Source]
    (sourceMeasure : Measure Source)
    (massSquared : Real) where
  parameterization : CanonicalPhysicalScalarEulerDenseParametrizationData
    period hPeriod Source sourceMeasure
  euler : CanonicalPhysicalScalarEulerCompatibilityOnlyData
    period hPeriod massSquared
  boundaryDensity : CanonicalLatitudeSmoothBoundaryCoreDensityData period
  integral_eq_divergence :
    ∀ field test : SmoothQuotientField period hPeriod Real,
      (∫ point,
        canonicalPhysicalScalarEulerSkewDensity
          period hPeriod massSquared field test point
        ∂P0EFTJanusMappingTorusCanonicalLorentzVolumeGluing4D.intrinsicCanonicalLorentzVolumeMeasure
          period hPeriod) =
      -2 * cutBulkCanonicalDivergenceMeasure
        period hPeriod massSquared field test Set.univ

namespace CanonicalPhysicalScalarCanonicalDenseParametrizedCauchyJetData

/-- The dense parametrization supplies the complete faithful Euler compatibility
package. -/
def eulerCompatibility
    {Source : Type u}
    [TopologicalSpace Source] [MeasurableSpace Source]
    {sourceMeasure : Measure Source}
    (data : CanonicalPhysicalScalarCanonicalDenseParametrizedCauchyJetData
      period hPeriod Source sourceMeasure massSquared) :=
  data.parameterization.toEulerCompatibilityData period hPeriod data.euler

/-- Conversion to the canonical compatibility-based Cauchy-jet package. -/
def toCanonicalCauchyJetCompatibilityData
    {Source : Type u}
    [TopologicalSpace Source] [MeasurableSpace Source]
    {sourceMeasure : Measure Source}
    (data : CanonicalPhysicalScalarCanonicalDenseParametrizedCauchyJetData
      period hPeriod Source sourceMeasure massSquared) :
    CanonicalPhysicalScalarCanonicalCauchyJetCompatibilityData
      period hPeriod massSquared where
  eulerCompatibility := data.eulerCompatibility period hPeriod
  boundaryDensity := data.boundaryDensity
  integral_eq_divergence := data.integral_eq_divergence

/-- Full support of the physical Lorentz volume generated by the source
parametrization. -/
def physicalMeasureOpenPositive
    {Source : Type u}
    [TopologicalSpace Source] [MeasurableSpace Source]
    {sourceMeasure : Measure Source}
    (data : CanonicalPhysicalScalarCanonicalDenseParametrizedCauchyJetData
      period hPeriod Source sourceMeasure massSquared) :
    (P0EFTJanusMappingTorusCanonicalLorentzVolumeGluing4D.intrinsicCanonicalLorentzVolumeMeasure
      period hPeriod).IsOpenPosMeasure :=
  data.parameterization.physicalMeasureOpenPositive period hPeriod

/-- Explicit global smooth Cauchy extension. -/
def extension
    {Source : Type u}
    [TopologicalSpace Source] [MeasurableSpace Source]
    {sourceMeasure : Measure Source}
    (data : CanonicalPhysicalScalarCanonicalDenseParametrizedCauchyJetData
      period hPeriod Source sourceMeasure massSquared) :=
  (data.toCanonicalCauchyJetCompatibilityData period hPeriod).extension
    period hPeriod

/-- Genuine faithful physical Euler operator. -/
def operatorData
    {Source : Type u}
    [TopologicalSpace Source] [MeasurableSpace Source]
    {sourceMeasure : Measure Source}
    (data : CanonicalPhysicalScalarCanonicalDenseParametrizedCauchyJetData
      period hPeriod Source sourceMeasure massSquared) :=
  (data.toCanonicalCauchyJetCompatibilityData period hPeriod).operatorData
    period hPeriod

/-- Correct dense physical scalar Green core. -/
def greenCore
    {Source : Type u}
    [TopologicalSpace Source] [MeasurableSpace Source]
    {sourceMeasure : Measure Source}
    (data : CanonicalPhysicalScalarCanonicalDenseParametrizedCauchyJetData
      period hPeriod Source sourceMeasure massSquared) :=
  (data.toCanonicalCauchyJetCompatibilityData period hPeriod).greenCore
    period hPeriod

/-- Dense-parametrized canonical Green-core certificate. -/
theorem certificate
    {Source : Type u}
    [TopologicalSpace Source] [MeasurableSpace Source]
    {sourceMeasure : Measure Source}
    (data : CanonicalPhysicalScalarCanonicalDenseParametrizedCauchyJetData
      period hPeriod Source sourceMeasure massSquared) :
    (P0EFTJanusMappingTorusCanonicalLorentzVolumeGluing4D.intrinsicCanonicalLorentzVolumeMeasure
        period hPeriod).IsOpenPosMeasure ∧
      DenseRange
        (P0EFTJanusMappingTorusCanonicalPhysicalScalarFirstSheetHilbertTrace4D.smoothCanonicalPhysicalScalarFirstSheetCauchyTrace
          period hPeriod) ∧
      (∀ boundary : ValueCore period × NormalCore period,
        P0EFTJanusMappingTorusCanonicalPhysicalScalarFirstSheetHilbertTrace4D.smoothCanonicalPhysicalScalarFirstSheetCauchyTrace
            period hPeriod (data.extension period hPeriod boundary) =
          canonicalScalarBoundaryCorePairEmbedding
            (canonicalLatitudeSmoothPeriodicValueEmbedding period)
            (canonicalLatitudeSmoothAntiperiodicNormalEmbedding period)
            boundary) :=
  ⟨data.physicalMeasureOpenPositive period hPeriod,
    (data.toCanonicalCauchyJetCompatibilityData period hPeriod)
      |>.boundaryTrace_denseRange period hPeriod,
    (data.toCanonicalCauchyJetCompatibilityData period hPeriod)
      |>.cauchyTrace_extension period hPeriod⟩

end CanonicalPhysicalScalarCanonicalDenseParametrizedCauchyJetData

end
end P0EFTJanusMappingTorusCanonicalPhysicalScalarCanonicalDenseParametrizedCauchyJetGreenCore4D
end JanusFormal
