import JanusFormal.Branches.FundamentalGeometryPVariationalPrinciple.Gates.P0EFTJanusMappingTorusCanonicalPhysicalScalarCanonicalResolventReducedAnalyticClosure4D
import JanusFormal.Branches.FundamentalGeometryPVariationalPrinciple.Gates.P0EFTJanusMappingTorusScalarCompletedBoundaryTripleResolventAdjointRegularity4D

/-!
# Physical adjoint regularity generated by the reference resolvent

The final physical scalar package no longer assumes an adjoint regularity
statement.  Its positive shifted decomposition produces a bounded real
resolvent, and minimal-core density makes the selected Lagrangian domain dense.
The generic resolvent theorem therefore constructs every former adjoint input:

* actual-adjoint graph membership;
* maximal adjoint regularity;
* smooth graph approximation of every Hilbert adjoint pair;
* equality of actual adjoint and realization domains.

This bridge keeps the older regularity-oriented APIs available without adding a
new hypothesis to the preferred endpoint.
-/

namespace JanusFormal
namespace P0EFTJanusMappingTorusCanonicalPhysicalScalarCanonicalResolventAdjointClosure4D
end P0EFTJanusMappingTorusCanonicalPhysicalScalarCanonicalResolventAdjointClosure4D

namespace P0EFTJanusMappingTorusCanonicalPhysicalScalarCanonicalResolventReducedAnalyticClosure4D

set_option autoImplicit false
noncomputable section

open Set Topology
open P0EFTJanusMappingTorusCanonicalPhysicalScalarCanonicalResolventReducedAnalyticClosure4D
open P0EFTJanusMappingTorusScalarCompletedBoundaryTripleAdjointGraphRegularity4D
open P0EFTJanusMappingTorusScalarCompletedBoundaryTripleAdjointSequentialClosure4D
open P0EFTJanusMappingTorusScalarCompletedBoundaryTripleResolventAdjointRegularity4D

universe r

variable (period : Real) (hPeriod : period ≠ 0)
variable {massSquared : Real}
variable {Regularity : Type r}
  [NormedAddCommGroup Regularity] [NormedSpace Real Regularity]
  [CompleteSpace Regularity]

namespace CanonicalPhysicalScalarCanonicalResolventReducedAnalyticData

/-- Actual-adjoint graph regularity generated by the bounded real resolvent. -/
theorem adjointGraphRegularity
    (analytic : CanonicalPhysicalScalarCanonicalResolventReducedAnalyticData
      period hPeriod massSquared (Regularity := Regularity)) :
    analytic.boundary.triple.AdjointPairGraphRegularity analytic.condition :=
  analytic.boundary.triple.adjointPairGraphRegularity_of_boundedResolvent
    analytic.condition analytic.referenceParameter
    (analytic.boundedResolvent period hPeriod)
    (analytic.denseDomain period hPeriod)

/-- Maximal adjoint regularity generated by the bounded real resolvent. -/
def maximalAdjointRegularity
    (analytic : CanonicalPhysicalScalarCanonicalResolventReducedAnalyticData
      period hPeriod massSquared (Regularity := Regularity)) :
    analytic.boundary.triple.MaximalAdjointRegularity analytic.condition :=
  analytic.boundary.triple.maximalAdjointRegularity_of_boundedResolvent
    analytic.condition analytic.referenceParameter
    (analytic.boundedResolvent period hPeriod)
    (analytic.denseDomain period hPeriod)

/-- Smooth approximation of every adjoint graph pair, generated by closure of
the smooth graph. -/
noncomputable def adjointApproximation
    (analytic : CanonicalPhysicalScalarCanonicalResolventReducedAnalyticData
      period hPeriod massSquared (Regularity := Regularity)) :
    analytic.boundary.triple.AdjointPairSmoothApproximationData
      analytic.condition :=
  analytic.boundary.triple
    |>.adjointPairSmoothApproximationData_of_boundedResolvent
      analytic.condition analytic.referenceParameter
      (analytic.boundedResolvent period hPeriod)
      (analytic.denseDomain period hPeriod)

/-- Complete physical adjoint-regularity certificate generated by the
reference resolvent. -/
theorem adjointRegularity_certificate
    (analytic : CanonicalPhysicalScalarCanonicalResolventReducedAnalyticData
      period hPeriod massSquared (Regularity := Regularity)) :
    analytic.boundary.triple.AdjointPairGraphRegularity analytic.condition ∧
      Nonempty
        (analytic.boundary.triple.MaximalAdjointRegularity analytic.condition) ∧
      Nonempty
        (analytic.boundary.triple.AdjointPairSmoothApproximationData
          analytic.condition) ∧
      analytic.boundary.triple.actualAdjointDomain analytic.condition =
        analytic.boundary.triple.realizationDomain analytic.condition :=
  analytic.boundary.triple.boundedResolvent_adjointRegularity_certificate
    analytic.condition analytic.referenceParameter
    (analytic.boundedResolvent period hPeriod)
    (analytic.denseDomain period hPeriod)

end CanonicalPhysicalScalarCanonicalResolventReducedAnalyticData

end
end P0EFTJanusMappingTorusCanonicalPhysicalScalarCanonicalResolventReducedAnalyticClosure4D
end JanusFormal
