import Mathlib.MeasureTheory.Measure.OpenPos

/-!
# Open-positive measures transported by dense measure-preserving maps

Mathlib transports `IsOpenPosMeasure` through a continuous surjective map.  For
applications to latitude and collar parametrizations, surjectivity is often
unnecessarily strong: the parametrization may omit a polar null set while still
having dense range.

A continuous dense-range map is enough.  Every nonempty open target set meets
its range, so its preimage is a nonempty open source set.  If the source measure
is positive on nonempty opens and the map is measure preserving, the target set
has positive measure.
-/

namespace JanusFormal
namespace P0EFTJanusMappingTorusMeasureOpenPositiveDenseMap4D

set_option autoImplicit false
noncomputable section

open Set Topology MeasureTheory

universe u v

variable {Source : Type u} {Target : Type v}
  [TopologicalSpace Source] [MeasurableSpace Source]
  [TopologicalSpace Target] [MeasurableSpace Target]
  [BorelSpace Target]
  {sourceMeasure : Measure Source} {targetMeasure : Measure Target}

/-- A dense subset meets every nonempty open set. -/
theorem DenseRange.nonempty_preimage_of_isOpen
    {map : Source → Target} (hDense : DenseRange map)
    {targetSet : Set Target} (hOpen : IsOpen targetSet)
    (hNonempty : targetSet.Nonempty) :
    (map ⁻¹' targetSet).Nonempty := by
  obtain ⟨target, hTarget⟩ := hNonempty
  have hClosure : target ∈ closure (Set.range map) := hDense target
  have hMeet : (Set.range map ∩ targetSet).Nonempty :=
    (mem_closure_iff.1 hClosure) targetSet (hOpen.mem_nhds hTarget)
  rcases hMeet with ⟨value, ⟨source, rfl⟩, hValue⟩
  exact ⟨source, hValue⟩

/-- Continuous dense measure-preserving maps transport positivity on nonempty
open sets. -/
theorem MeasurePreserving.isOpenPosMeasure_of_continuous_denseRange
    [sourceMeasure.IsOpenPosMeasure]
    {map : Source → Target}
    (hMeasure : MeasurePreserving map sourceMeasure targetMeasure)
    (hContinuous : Continuous map)
    (hDense : DenseRange map) :
    targetMeasure.IsOpenPosMeasure where
  open_pos targetSet hOpen hNonempty := by
    have hPreimageOpen : IsOpen (map ⁻¹' targetSet) :=
      hOpen.preimage hContinuous
    have hPreimageNonempty : (map ⁻¹' targetSet).Nonempty :=
      hDense.nonempty_preimage_of_isOpen hOpen hNonempty
    have hSourcePositive :
        sourceMeasure (map ⁻¹' targetSet) ≠ 0 :=
      hPreimageOpen.measure_ne_zero sourceMeasure hPreimageNonempty
    rw [← hMeasure.map_eq, Measure.map_apply hMeasure.measurable hOpen.measurableSet]
    exact hSourcePositive

/-- Convenience structure for one dense open-positive parametrization. -/
structure OpenPositiveDenseParametrization where
  map : Source → Target
  continuous : Continuous map
  denseRange : DenseRange map
  measurePreserving : MeasurePreserving map sourceMeasure targetMeasure
  sourceOpenPositive : sourceMeasure.IsOpenPosMeasure

namespace OpenPositiveDenseParametrization

/-- Target open positivity generated by the parametrization. -/
def targetOpenPositive
    (parameterization : OpenPositiveDenseParametrization
      (sourceMeasure := sourceMeasure) (targetMeasure := targetMeasure)) :
    targetMeasure.IsOpenPosMeasure := by
  letI : sourceMeasure.IsOpenPosMeasure :=
    parameterization.sourceOpenPositive
  exact parameterization.measurePreserving
    |>.isOpenPosMeasure_of_continuous_denseRange
      parameterization.continuous parameterization.denseRange

/-- Open-positive transport certificate. -/
theorem certificate
    (parameterization : OpenPositiveDenseParametrization
      (sourceMeasure := sourceMeasure) (targetMeasure := targetMeasure)) :
    ∀ targetSet : Set Target,
      IsOpen targetSet → targetSet.Nonempty →
        targetMeasure targetSet ≠ 0 := by
  letI : targetMeasure.IsOpenPosMeasure :=
    parameterization.targetOpenPositive
  exact fun targetSet hOpen hNonempty =>
    hOpen.measure_ne_zero targetMeasure hNonempty

end OpenPositiveDenseParametrization

end
end P0EFTJanusMappingTorusMeasureOpenPositiveDenseMap4D
end JanusFormal
