import JanusFormal.Branches.FundamentalGeometryPVariationalPrinciple.Gates.P0EFTJanusProgramPCandidateAFiveSectorSelfAdjointPhysicalSmallness4D
import JanusFormal.Branches.FundamentalGeometryPVariationalPrinciple.Gates.P0EFTJanusProgramPCandidateAFiveSectorProjectionOperatorGarding4D

/-!
# Operator lower bound from symmetric idempotent sector projections

The total quadratic margin generated by the natural five projection laws is
identified with one displayed Hessian operator energy.
-/

namespace JanusFormal
namespace P0EFTJanusProgramPCandidateAFiveSectorSelfAdjointOperatorGarding4D

set_option autoImplicit false
noncomputable section

open P0EFTJanusProgramPCandidateAFiveSectorSelfAdjointPhysicalSmallness4D
open P0EFTJanusProgramPCandidateAFiveSectorProjectionOperatorGarding4D
open P0EFTJanusProgramPCandidateAFiveSectorProjectionPhysicalSmallness4D
open P0EFTJanusProgramPCandidateAFiveSectorSelfAdjointPrincipalResolution4D

variable {E : Type*}
  [NormedAddCommGroup E]
  [InnerProductSpace Real E]

/-- Symmetric idempotent resolution identified with one operator energy. -/
structure CandidateAFiveSectorSelfAdjointOperatorGardingData
    (operator : E →L[Real] E) where
  finiteMargin : CandidateAFiveSectorSelfAdjointPhysicalSmallnessData (E := E)
  energy_upper : ∀ vector,
    finiteMargin.totalEnergy vector ≤ ‖vector‖ * ‖operator vector‖

namespace CandidateAFiveSectorSelfAdjointOperatorGardingData

/-- Established positive-projection operator packet. -/
def toProjectionOperatorGardingData
    {operator : E →L[Real] E}
    (data : CandidateAFiveSectorSelfAdjointOperatorGardingData operator) :
    CandidateAFiveSectorProjectionOperatorGardingData operator where
  finiteMargin := data.finiteMargin.toProjectionPhysicalSmallnessData
  energy_upper := data.energy_upper

/-- Explicit operator lower bound. -/
theorem lowerBound
    {operator : E →L[Real] E}
    (data : CandidateAFiveSectorSelfAdjointOperatorGardingData operator)
    (vector : E) :
    data.finiteMargin.margin * ‖vector‖ ≤ ‖operator vector‖ := by
  simpa [CandidateAFiveSectorSelfAdjointPhysicalSmallnessData.margin,
    toProjectionOperatorGardingData,
    CandidateAFiveSectorSelfAdjointPhysicalSmallnessData.toProjectionPhysicalSmallnessData,
    CandidateAFiveSectorSelfAdjointPrincipalResolutionData.margin,
    CandidateAFiveSectorProjectionPhysicalSmallnessData.margin] using
      CandidateAFiveSectorProjectionOperatorGardingData.lowerBound
        (toProjectionOperatorGardingData data) vector

/-- Injectivity on the actual zero-mode complement. -/
theorem injective
    {operator : E →L[Real] E}
    (data : CandidateAFiveSectorSelfAdjointOperatorGardingData operator) :
    Function.Injective operator :=
  CandidateAFiveSectorProjectionOperatorGardingData.injective
    (toProjectionOperatorGardingData data)

/-- Public operator checkpoint. -/
theorem candidateA_five_sector_selfAdjoint_operator_garding_gate
    (operator : E →L[Real] E)
    (data : CandidateAFiveSectorSelfAdjointOperatorGardingData operator) :
    (∀ vector,
      data.finiteMargin.margin * ‖vector‖ ≤ ‖operator vector‖) ∧
      Function.Injective operator :=
  ⟨data.lowerBound, data.injective⟩

end CandidateAFiveSectorSelfAdjointOperatorGardingData

end
end P0EFTJanusProgramPCandidateAFiveSectorSelfAdjointOperatorGarding4D
end JanusFormal
