import JanusFormal.Branches.FundamentalGeometryPVariationalPrinciple.Gates.P0EFTJanusMappingTorusCanonicalPhysicalScalarNormalRegularity4D

/-!
# Normal regularity directly on the completed maximal graph

Instead of supplying a smooth regularity map together with a separate graph
estimate and constant, the natural final datum is a continuous linear map from
the already completed maximal graph into the regularity space.

Its operator norm automatically controls the smooth core.  Composing with a
bounded normal trace produces the complete normal graph estimate.  Thus all
regularity constants and extension arguments become definitional consequences
of one completed graph map.
-/

namespace JanusFormal
namespace P0EFTJanusMappingTorusCanonicalPhysicalScalarCompletedNormalRegularity4D

set_option autoImplicit false
noncomputable section

open Set Topology
open P0EFTJanusMappingTorusSmoothFieldDescent4D
open P0EFTJanusMappingTorusCanonicalPhysicalScalarFirstSheetHilbertTrace4D
open P0EFTJanusMappingTorusCanonicalPhysicalScalarFirstSheetGreenCore4D
open P0EFTJanusMappingTorusScalarHilbertGreenCoreCompletion4D

universe r

variable (period : Real) (hPeriod : period ≠ 0)
variable {Regularity : Type r}
  [NormedAddCommGroup Regularity] [NormedSpace Real Regularity]
  [CompleteSpace Regularity]

private abbrev BoundaryL2 := CanonicalPhysicalScalarFirstSheetL2 period

namespace CanonicalPhysicalScalarFirstSheetGreenCoreData

/-- Higher regularity realized directly as a bounded map from the completed
maximal graph. -/
structure CompletedNormalRegularityData
    (green : CanonicalPhysicalScalarFirstSheetGreenCoreData
      period hPeriod massSquared) where
  completedRegularity :
    CanonicalScalarGreenCoreGraphSpace green.core →L[Real] Regularity
  normalTrace : Regularity →L[Real] BoundaryL2 period
  normal_agrees : ∀ field : SmoothQuotientField period hPeriod Real,
    normalTrace
        (completedRegularity
          (canonicalScalarGreenCoreToGraph green.core field)) =
      smoothCanonicalPhysicalScalarFirstSheetNormalL2
        period hPeriod field

namespace CompletedNormalRegularityData

/-- Smooth-core realization obtained by restricting the completed graph map. -/
def smoothRegularity
    (green : CanonicalPhysicalScalarFirstSheetGreenCoreData
      period hPeriod massSquared)
    (regularity : green.CompletedNormalRegularityData
      period hPeriod (Regularity := Regularity)) :
    SmoothQuotientField period hPeriod Real →ₗ[Real] Regularity :=
  regularity.completedRegularity.toLinearMap.comp
    (canonicalScalarGreenCoreToGraph green.core)

/-- Operator norm controls the smooth regularity realization. -/
theorem smoothRegularity_norm_le
    (green : CanonicalPhysicalScalarFirstSheetGreenCoreData
      period hPeriod massSquared)
    (regularity : green.CompletedNormalRegularityData
      period hPeriod (Regularity := Regularity))
    (field : SmoothQuotientField period hPeriod Real) :
    ‖regularity.smoothRegularity green field‖ ≤
      ‖regularity.completedRegularity‖ *
        ‖canonicalScalarGreenCoreToGraph green.core field‖ :=
  regularity.completedRegularity.le_opNorm _

/-- Squared graph estimate generated by the completed operator norm. -/
theorem smoothRegularity_bound_sq
    (green : CanonicalPhysicalScalarFirstSheetGreenCoreData
      period hPeriod massSquared)
    (regularity : green.CompletedNormalRegularityData
      period hPeriod (Regularity := Regularity))
    (field : SmoothQuotientField period hPeriod Real) :
    ‖regularity.smoothRegularity green field‖ ^ 2 ≤
      ‖regularity.completedRegularity‖ ^ 2 *
        ‖canonicalScalarGreenCoreToGraph green.core field‖ ^ 2 := by
  have hLinear := regularity.smoothRegularity_norm_le green field
  nlinarith [norm_nonneg (regularity.smoothRegularity green field),
    norm_nonneg regularity.completedRegularity,
    norm_nonneg (canonicalScalarGreenCoreToGraph green.core field)]

/-- Conversion to the established normal-regularity package. -/
def toNormalRegularityData
    (green : CanonicalPhysicalScalarFirstSheetGreenCoreData
      period hPeriod massSquared)
    (regularity : green.CompletedNormalRegularityData
      period hPeriod (Regularity := Regularity)) :
    green.NormalRegularityData period hPeriod (Regularity := Regularity) where
  smoothRegularity := regularity.smoothRegularity green
  normalTrace := regularity.normalTrace
  normal_agrees := regularity.normal_agrees
  constant := ‖regularity.completedRegularity‖
  nonnegative := norm_nonneg _
  regularity_bound_sq := regularity.smoothRegularity_bound_sq green

/-- Complete normal graph estimate. -/
def toNormalGraphEstimate
    (green : CanonicalPhysicalScalarFirstSheetGreenCoreData
      period hPeriod massSquared)
    (regularity : green.CompletedNormalRegularityData
      period hPeriod (Regularity := Regularity)) :
    green.NormalGraphEstimate period hPeriod :=
  (regularity.toNormalRegularityData green).toNormalGraphEstimate green

/-- The completed regularity map used by the established interface is exactly
the supplied map. -/
theorem toNormalRegularityData_completedRegularity_eq
    (green : CanonicalPhysicalScalarFirstSheetGreenCoreData
      period hPeriod massSquared)
    (regularity : green.CompletedNormalRegularityData
      period hPeriod (Regularity := Regularity)) :
    (regularity.toNormalRegularityData green).completedRegularity
        period hPeriod green =
      regularity.completedRegularity := by
  apply ContinuousLinearMap.ext
  intro field
  apply tendsto_nhds_unique
    ((regularity.toNormalRegularityData green).completedRegularity.continuous.continuousAt.tendsto)
  apply tendsto_nhds_unique
    (regularity.completedRegularity.continuous.continuousAt.tendsto)
  exact Filter.Eventually.of_forall fun _ => rfl

/-- The completed normal trace agrees with the completed Cauchy normal component. -/
theorem normalTrace_completedRegularity
    (green : CanonicalPhysicalScalarFirstSheetGreenCoreData
      period hPeriod massSquared)
    (regularity : green.CompletedNormalRegularityData
      period hPeriod (Regularity := Regularity))
    (traceBound : HasCanonicalScalarHilbertGreenCoreBoundaryGraphBound green.core)
    (field : CanonicalScalarGreenCoreGraphSpace green.core) :
    regularity.normalTrace (regularity.completedRegularity field) =
      (regularity.toNormalRegularityData green).completedBoundaryNormalTrace
        green traceBound field := by
  rw [← regularity.toNormalRegularityData_completedRegularity_eq green]
  exact (regularity.toNormalRegularityData green)
    |>.normalTrace_completedRegularity_eq_completedBoundaryNormalTrace
      green traceBound field

/-- Completed-normal-regularity certificate. -/
theorem certificate
    (green : CanonicalPhysicalScalarFirstSheetGreenCoreData
      period hPeriod massSquared)
    (regularity : green.CompletedNormalRegularityData
      period hPeriod (Regularity := Regularity)) :
    (∀ field : SmoothQuotientField period hPeriod Real,
      ‖regularity.smoothRegularity green field‖ ≤
        ‖regularity.completedRegularity‖ *
          ‖canonicalScalarGreenCoreToGraph green.core field‖) ∧
      (∀ field : SmoothQuotientField period hPeriod Real,
        ‖smoothCanonicalPhysicalScalarFirstSheetNormalL2
            period hPeriod field‖ ≤
          ‖regularity.normalTrace‖ * ‖regularity.completedRegularity‖ *
            ‖canonicalScalarGreenCoreToGraph green.core field‖) :=
  ⟨regularity.smoothRegularity_norm_le green,
    (regularity.toNormalGraphEstimate green).bound⟩

end CompletedNormalRegularityData

end CanonicalPhysicalScalarFirstSheetGreenCoreData

end
end P0EFTJanusMappingTorusCanonicalPhysicalScalarCompletedNormalRegularity4D
end JanusFormal
