import JanusFormal.Branches.FundamentalGeometryPVariationalPrinciple.Gates.P0EFTJanusProgramPFiniteModeSchurKernel4D

/-!
# Constructive finite-mode Schur elimination from four operator blocks

The abstract Schur-kernel packet stores two triangular reductions and their
factorization.  In applications those maps are not additional analytic data:
they are the standard Gaussian-elimination maps generated by the four blocks

`A : F → F`, `B : G → F`, `C : F → G`, `D : G → G`

once the complementary block `D` is invertible.

This file constructs the reductions, the Schur operator

`S = A - B D⁻¹ C`

and the exact diagonal factorization automatically.  Therefore the remaining
zero-mode calculation is finite-dimensional as soon as the complement block
is invertible.
-/

namespace JanusFormal
namespace P0EFTJanusProgramPFiniteModeSchurBlockElimination4D

set_option autoImplicit false
noncomputable section

open P0EFTJanusProgramPFiniteModeSchurKernel4D

variable {E : Type*}
  [NormedAddCommGroup E] [NormedSpace Real E]

/-- Four-block presentation of an operator after one linear decomposition. -/
structure FiniteModeSchurBlockData
    (operator : E →L[Real] E)
    (Mode Complement : Type*)
    [Fintype Mode] [DecidableEq Mode]
    [AddCommGroup Complement] [Module Real Complement] where
  decomposition : E ≃ₗ[Real] ((Mode → Real) × Complement)
  finiteBlock : (Mode → Real) →ₗ[Real] (Mode → Real)
  upperRight : Complement →ₗ[Real] (Mode → Real)
  lowerLeft : (Mode → Real) →ₗ[Real] Complement
  complementEquiv : Complement ≃ₗ[Real] Complement
  operator_block : ∀ state : (Mode → Real) × Complement,
    decomposition (operator (decomposition.symm state)) =
      (finiteBlock state.1 + upperRight state.2,
        lowerLeft state.1 + complementEquiv state.2)

/-- Finite Schur complement `A - B D⁻¹ C`. -/
def finiteModeSchurBlockOperator
    {operator : E →L[Real] E}
    {Mode Complement : Type*}
    [Fintype Mode] [DecidableEq Mode]
    [AddCommGroup Complement] [Module Real Complement]
    (data : FiniteModeSchurBlockData operator Mode Complement) :
    (Mode → Real) →ₗ[Real] (Mode → Real) :=
  data.finiteBlock -
    data.upperRight.comp
      (data.complementEquiv.symm.toLinearMap.comp data.lowerLeft)

/-- Right Gaussian elimination `(x,y) ↦ (x, y - D⁻¹Cx)`. -/
def finiteModeSchurRightReduction
    {operator : E →L[Real] E}
    {Mode Complement : Type*}
    [Fintype Mode] [DecidableEq Mode]
    [AddCommGroup Complement] [Module Real Complement]
    (data : FiniteModeSchurBlockData operator Mode Complement) :
    ((Mode → Real) × Complement) ≃ₗ[Real]
      ((Mode → Real) × Complement) where
  toFun state :=
    (state.1,
      state.2 - data.complementEquiv.symm (data.lowerLeft state.1))
  invFun state :=
    (state.1,
      state.2 + data.complementEquiv.symm (data.lowerLeft state.1))
  map_add' := by
    intro first second
    apply Prod.ext
    · rfl
    · simp [map_add]
      abel
  map_smul' := by
    intro scalar state
    apply Prod.ext
    · rfl
    · simpa [map_smul] using
        (smul_sub scalar state.2
          (data.complementEquiv.symm (data.lowerLeft state.1))).symm
  left_inv := by
    intro state
    apply Prod.ext
    · rfl
    · simp
  right_inv := by
    intro state
    apply Prod.ext
    · rfl
    · simp

/-- Left Gaussian elimination `(u,v) ↦ (u - BD⁻¹v, v)`. -/
def finiteModeSchurLeftReduction
    {operator : E →L[Real] E}
    {Mode Complement : Type*}
    [Fintype Mode] [DecidableEq Mode]
    [AddCommGroup Complement] [Module Real Complement]
    (data : FiniteModeSchurBlockData operator Mode Complement) :
    ((Mode → Real) × Complement) ≃ₗ[Real]
      ((Mode → Real) × Complement) where
  toFun state :=
    (state.1 -
      data.upperRight (data.complementEquiv.symm state.2), state.2)
  invFun state :=
    (state.1 +
      data.upperRight (data.complementEquiv.symm state.2), state.2)
  map_add' := by
    intro first second
    apply Prod.ext
    · simp [map_add]
      abel
    · rfl
  map_smul' := by
    intro scalar state
    apply Prod.ext
    · simpa [map_smul] using
        (smul_sub scalar state.1
          (data.upperRight (data.complementEquiv.symm state.2))).symm
    · rfl
  left_inv := by
    intro state
    apply Prod.ext
    · simp
    · rfl
  right_inv := by
    intro state
    apply Prod.ext
    · simp
    · rfl

/-- Exact block Gaussian elimination. -/
theorem finiteModeSchurBlock_factorization
    {operator : E →L[Real] E}
    {Mode Complement : Type*}
    [Fintype Mode] [DecidableEq Mode]
    [AddCommGroup Complement] [Module Real Complement]
    (data : FiniteModeSchurBlockData operator Mode Complement)
    (state : (Mode → Real) × Complement) :
    finiteModeSchurLeftReduction data
        (data.decomposition
          (operator
            (data.decomposition.symm
              (finiteModeSchurRightReduction data state)))) =
      (finiteModeSchurBlockOperator data state.1,
        data.complementEquiv state.2) := by
  rw [data.operator_block]
  apply Prod.ext
  · simp [finiteModeSchurLeftReduction, finiteModeSchurRightReduction,
      finiteModeSchurBlockOperator, map_sub]
    abel
  · simp [finiteModeSchurLeftReduction, finiteModeSchurRightReduction, map_sub]

/-- Construct the abstract kernel-reduction packet from the four blocks. -/
def FiniteModeSchurBlockData.toKernelData
    {operator : E →L[Real] E}
    {Mode Complement : Type*}
    [Fintype Mode] [DecidableEq Mode]
    [AddCommGroup Complement] [Module Real Complement]
    (data : FiniteModeSchurBlockData operator Mode Complement) :
    FiniteModeSchurKernelData operator Mode Complement where
  decomposition := data.decomposition
  leftReduction := finiteModeSchurLeftReduction data
  rightReduction := finiteModeSchurRightReduction data
  schur := finiteModeSchurBlockOperator data
  complementOperator := data.complementEquiv.toLinearMap
  complement_bijective := data.complementEquiv.bijective
  factorization := finiteModeSchurBlock_factorization data

/-- The full kernel is the kernel of the explicit finite Schur complement. -/
noncomputable def finiteModeSchurBlockKernelEquiv
    {operator : E →L[Real] E}
    {Mode Complement : Type*}
    [Fintype Mode] [DecidableEq Mode]
    [AddCommGroup Complement] [Module Real Complement]
    (data : FiniteModeSchurBlockData operator Mode Complement) :
    operator.ker ≃ₗ[Real] (finiteModeSchurBlockOperator data).ker :=
  finiteModeSchurKernelEquiv data.toKernelData

/-- Actual zero-mode count is bounded by the finite block size. -/
theorem finiteModeSchurBlock_operatorKernel_finrank_le_card
    {operator : E →L[Real] E}
    {Mode Complement : Type*}
    [Fintype Mode] [DecidableEq Mode]
    [AddCommGroup Complement] [Module Real Complement]
    (data : FiniteModeSchurBlockData operator Mode Complement) :
    Module.finrank Real operator.ker ≤ Fintype.card Mode :=
  finiteModeSchur_operatorKernel_finrank_le_card data.toKernelData

/-- Canonical finite kernel model generated from the Schur block. -/
noncomputable def finiteModeSchurBlockKernelModel
    {operator : E →L[Real] E}
    {Mode Complement : Type*}
    [Fintype Mode] [DecidableEq Mode]
    [AddCommGroup Complement] [Module Real Complement]
    (data : FiniteModeSchurBlockData operator Mode Complement) :
    P0EFTJanusProgramPFiniteKernelModel4D.FiniteKernelModel operator :=
  finiteModeSchurKernelModel data.toKernelData

/-- Public four-block elimination checkpoint. -/
theorem finite_mode_schur_block_elimination_gate
    {operator : E →L[Real] E}
    {Mode Complement : Type*}
    [Fintype Mode] [DecidableEq Mode]
    [AddCommGroup Complement] [Module Real Complement]
    (data : FiniteModeSchurBlockData operator Mode Complement) :
    Nonempty (operator.ker ≃ₗ[Real]
      (finiteModeSchurBlockOperator data).ker) ∧
      Module.finrank Real operator.ker ≤ Fintype.card Mode :=
  ⟨⟨finiteModeSchurBlockKernelEquiv data⟩,
    finiteModeSchurBlock_operatorKernel_finrank_le_card data⟩

end
end P0EFTJanusProgramPFiniteModeSchurBlockElimination4D
end JanusFormal
