import Mathlib.Tactic.Abel
import JanusFormal.Branches.FundamentalGeometryPVariationalPrinciple.Gates.P0EFTJanusProgramPOperatorNormDifferentiableUnitaryConjugation4D

/-!
# Green derivative for a unitarily conjugated inverse pair

Let `H_0` and `G_0` be bounded two-sided inverses and let `F_a` be an
operator-norm differentiable unitary frame.  Define

```text
H_a = F_a H_0 F_a⁻¹,
G_a = F_a G_0 F_a⁻¹.
```

Unitary conjugation preserves the two inverse identities.  The preceding
commutator formula gives

```text
H'_a = [A_a, H_a],
G'_a = [A_a, G_a],
A_a  = F'_a F_a⁻¹.
```

Using `H_a G_a = G_a H_a = id`, the Green commutator is exactly the canonical
inverse derivative:

```text
G'_a = -G_a H'_a G_a.
```
-/

namespace JanusFormal
namespace P0EFTJanusProgramPOperatorNormDifferentiableUnitaryGreenConjugation4D

set_option autoImplicit false
noncomputable section

open P0EFTJanusProgramPOperatorNormDifferentiableUnitaryFrame4D
open P0EFTJanusProgramPOperatorNormDifferentiableUnitaryFrameConnection4D
open P0EFTJanusProgramPOperatorNormDifferentiableUnitaryConjugation4D

variable {E : Type*}
  [NormedAddCommGroup E] [InnerProductSpace Real E] [CompleteSpace E]

/-- A bounded two-sided inverse pair at the fixed basepoint. -/
structure BoundedTwoSidedInversePair where
  operator : E →L[Real] E
  green : E →L[Real] E
  operator_green : operator.comp green = ContinuousLinearMap.id Real E
  green_operator : green.comp operator = ContinuousLinearMap.id Real E

namespace BoundedTwoSidedInversePair

/-- Moving operator obtained by unitary conjugation. -/
def conjugatedOperator
    (pair : BoundedTwoSidedInversePair (E := E))
    (frame : Real → E ≃ₗᵢ[Real] E)
    (parameter : Real) : E →L[Real] E :=
  conjugatedConstantOperator frame pair.operator parameter

/-- Moving Green obtained by the same unitary conjugation. -/
def conjugatedGreen
    (pair : BoundedTwoSidedInversePair (E := E))
    (frame : Real → E ≃ₗᵢ[Real] E)
    (parameter : Real) : E →L[Real] E :=
  conjugatedConstantOperator frame pair.green parameter

/-- The conjugated operator remains a left inverse of the conjugated Green. -/
theorem conjugatedOperator_green
    (pair : BoundedTwoSidedInversePair (E := E))
    (frame : Real → E ≃ₗᵢ[Real] E)
    (parameter : Real) :
    (pair.conjugatedOperator frame parameter).comp
        (pair.conjugatedGreen frame parameter) =
      ContinuousLinearMap.id Real E := by
  ext vector
  change frame parameter
      (pair.operator
        (pair.green ((frame parameter).symm vector))) = vector
  have hInverse := congrArg
    (fun map : E →L[Real] E => map ((frame parameter).symm vector))
    pair.operator_green
  simp only [ContinuousLinearMap.comp_apply,
    ContinuousLinearMap.id_apply] at hInverse
  rw [hInverse]
  exact (frame parameter).apply_symm_apply vector

/-- The conjugated Green remains a left inverse of the conjugated operator. -/
theorem conjugatedGreen_operator
    (pair : BoundedTwoSidedInversePair (E := E))
    (frame : Real → E ≃ₗᵢ[Real] E)
    (parameter : Real) :
    (pair.conjugatedGreen frame parameter).comp
        (pair.conjugatedOperator frame parameter) =
      ContinuousLinearMap.id Real E := by
  ext vector
  change frame parameter
      (pair.green
        (pair.operator ((frame parameter).symm vector))) = vector
  have hInverse := congrArg
    (fun map : E →L[Real] E => map ((frame parameter).symm vector))
    pair.green_operator
  simp only [ContinuousLinearMap.comp_apply,
    ContinuousLinearMap.id_apply] at hInverse
  rw [hInverse]
  exact (frame parameter).apply_symm_apply vector

/-- Operator derivative generated by the moving-frame commutator. -/
def operatorDerivative
    (pair : BoundedTwoSidedInversePair (E := E))
    {frame : Real → E ≃ₗᵢ[Real] E}
    (data : OperatorNormDifferentiableUnitaryFrameData frame)
    (parameter : Real) : E →L[Real] E :=
  continuousLinearMapCommutator
    (data.rightLogDerivative parameter)
    (pair.conjugatedOperator frame parameter)

/-- Green derivative generated by the moving-frame commutator. -/
def greenDerivative
    (pair : BoundedTwoSidedInversePair (E := E))
    {frame : Real → E ≃ₗᵢ[Real] E}
    (data : OperatorNormDifferentiableUnitaryFrameData frame)
    (parameter : Real) : E →L[Real] E :=
  continuousLinearMapCommutator
    (data.rightLogDerivative parameter)
    (pair.conjugatedGreen frame parameter)

/-- The conjugated operator has the commutator derivative. -/
theorem hasDerivAt_conjugatedOperator
    (pair : BoundedTwoSidedInversePair (E := E))
    {frame : Real → E ≃ₗᵢ[Real] E}
    (data : OperatorNormDifferentiableUnitaryFrameData frame)
    (parameter : Real) :
    HasDerivAt (pair.conjugatedOperator frame)
      (pair.operatorDerivative data parameter) parameter :=
  data.hasDerivAt_conjugatedConstantOperator_commutator pair.operator parameter

/-- The conjugated Green has the commutator derivative. -/
theorem hasDerivAt_conjugatedGreen
    (pair : BoundedTwoSidedInversePair (E := E))
    {frame : Real → E ≃ₗᵢ[Real] E}
    (data : OperatorNormDifferentiableUnitaryFrameData frame)
    (parameter : Real) :
    HasDerivAt (pair.conjugatedGreen frame)
      (pair.greenDerivative data parameter) parameter :=
  data.hasDerivAt_conjugatedConstantOperator_commutator pair.green parameter

/-- The Green commutator is the canonical derivative of the inverse family. -/
theorem greenDerivative_eq_inverse_formula
    (pair : BoundedTwoSidedInversePair (E := E))
    {frame : Real → E ≃ₗᵢ[Real] E}
    (data : OperatorNormDifferentiableUnitaryFrameData frame)
    (parameter : Real) :
    pair.greenDerivative data parameter =
      -((pair.conjugatedGreen frame parameter).comp
        ((pair.operatorDerivative data parameter).comp
          (pair.conjugatedGreen frame parameter))) := by
  let connection := data.rightLogDerivative parameter
  let operator := pair.conjugatedOperator frame parameter
  let green := pair.conjugatedGreen frame parameter
  have hOperatorGreen := pair.conjugatedOperator_green frame parameter
  have hGreenOperator := pair.conjugatedGreen_operator frame parameter
  apply ContinuousLinearMap.ext
  intro vector
  have hHG : operator (green vector) = vector := by
    have h := congrArg (fun map : E →L[Real] E => map vector)
      hOperatorGreen
    simpa [operator, green] using h
  have hGH : green (operator (connection (green vector))) =
      connection (green vector) := by
    have h := congrArg (fun map : E →L[Real] E =>
      map (connection (green vector))) hGreenOperator
    simpa [operator, green] using h
  change
    connection (green vector) - green (connection vector) =
      -green
        (connection (operator (green vector)) -
          operator (connection (green vector)))
  rw [hHG, map_sub, hGH]
  abel

/-- Direct canonical inverse-derivative statement for the moving Green. -/
theorem hasDerivAt_conjugatedGreen_inverse_formula
    (pair : BoundedTwoSidedInversePair (E := E))
    {frame : Real → E ≃ₗᵢ[Real] E}
    (data : OperatorNormDifferentiableUnitaryFrameData frame)
    (parameter : Real) :
    HasDerivAt (pair.conjugatedGreen frame)
      (-((pair.conjugatedGreen frame parameter).comp
        ((pair.operatorDerivative data parameter).comp
          (pair.conjugatedGreen frame parameter)))) parameter := by
  rw [← pair.greenDerivative_eq_inverse_formula data parameter]
  exact pair.hasDerivAt_conjugatedGreen data parameter

/-- Public unitarily conjugated Green-family checkpoint. -/
theorem operator_norm_differentiable_unitary_green_conjugation_gate
    (pair : BoundedTwoSidedInversePair (E := E))
    (frame : Real → E ≃ₗᵢ[Real] E)
    (data : OperatorNormDifferentiableUnitaryFrameData frame) :
    (∀ parameter,
      (pair.conjugatedOperator frame parameter).comp
          (pair.conjugatedGreen frame parameter) =
        ContinuousLinearMap.id Real E) ∧
    (∀ parameter,
      (pair.conjugatedGreen frame parameter).comp
          (pair.conjugatedOperator frame parameter) =
        ContinuousLinearMap.id Real E) ∧
    (∀ parameter,
      HasDerivAt (pair.conjugatedOperator frame)
        (pair.operatorDerivative data parameter) parameter) ∧
    (∀ parameter,
      HasDerivAt (pair.conjugatedGreen frame)
        (pair.greenDerivative data parameter) parameter) ∧
    (∀ parameter,
      pair.greenDerivative data parameter =
        -((pair.conjugatedGreen frame parameter).comp
          ((pair.operatorDerivative data parameter).comp
            (pair.conjugatedGreen frame parameter)))) :=
  ⟨pair.conjugatedOperator_green frame,
    pair.conjugatedGreen_operator frame,
    pair.hasDerivAt_conjugatedOperator data,
    pair.hasDerivAt_conjugatedGreen data,
    pair.greenDerivative_eq_inverse_formula data⟩

end BoundedTwoSidedInversePair

end
end P0EFTJanusProgramPOperatorNormDifferentiableUnitaryGreenConjugation4D
end JanusFormal
