import JanusFormal.Branches.FundamentalGeometryPVariationalPrinciple.Gates.P0EFTJanusProgramPFiniteUnitaryKernelComplementGapTransport4D
import JanusFormal.Branches.FundamentalGeometryPVariationalPrinciple.Gates.P0EFTJanusProgramPSelfAdjointKernelComplementFamilyTrivialization4D
import Mathlib.Analysis.Calculus.Deriv.Basic

/-!
# Fixed-complement trivialization generated by a unitary intertwining frame

The newer Fredholm continuation is expressed through one ambient unitary frame
`F_a`, while the earlier Bismut--Freed family interface consumes a unitary
trivialization of the varying reduced fibres.  These are not independent data.

If

```text
H_a F_a = F_a H_0
```

and `F_a` is unitary, its restriction gives

```text
(ker H_0)ᗮ ≃L (ker H_a)ᗮ.
```

A basepoint gap is transported to every fibre with the same constant.  Pulling
the current reduced operator back by this restriction gives the literal
constant family `H_red,0`.

This file constructs the old fixed-complement packet from the unitary frame and
proves exact constancy.  No second trivialization is selected.
-/

namespace JanusFormal
namespace P0EFTJanusProgramPFiniteUnitaryIntertwiningOperatorFrame4D

set_option autoImplicit false
noncomputable section

open P0EFTJanusProgramPFiniteUnitaryIntertwiningOperatorFrame4D
open P0EFTJanusProgramPFiniteUnitaryIntertwiningKernelComplementTransport4D
open P0EFTJanusProgramPFiniteUnitaryKernelComplementGapTransport4D
open P0EFTJanusProgramPSelfAdjointKernelComplementFamilyTrivialization4D
open P0EFTJanusProgramPSelfAdjointKernelComplementReduction4D

variable {E : Type*}
  [NormedAddCommGroup E] [InnerProductSpace Real E] [CompleteSpace E]

namespace FiniteUnitaryIntertwiningOperatorFrameData

/-- Restrict the ambient unitary frame to the genuine orthogonal kernel
complements in the format used by the fixed-complement family theory. -/
def toKernelComplementFamilyTrivialization
    {operator : Real → E →L[Real] E}
    (frame : FiniteUnitaryIntertwiningOperatorFrameData operator)
    (hSelfAdjoint : ∀ parameter, IsSelfAdjoint (operator parameter)) :
    SelfAdjointKernelComplementFamilyTrivializationData operator hSelfAdjoint where
  transport := fun parameter =>
    (frame.kernelComplementFrame parameter).toContinuousLinearEquiv
  transport_inner := by
    intro parameter first second
    exact (frame.kernelComplementFrame parameter).inner_map_map first second
  transport_norm := by
    intro parameter vector
    exact (frame.kernelComplementFrame parameter).norm_map vector
  transport_zero := by
    ext vector
    simpa [frame.frame_zero] using
      frame.kernelComplementFrame_apply_val 0 vector

/-- The transported reduced operator is exactly the basepoint reduced operator. -/
theorem transportedReducedOperator_eq_basepoint
    {operator : Real → E →L[Real] E}
    (frame : FiniteUnitaryIntertwiningOperatorFrameData operator)
    (hSelfAdjoint : ∀ parameter, IsSelfAdjoint (operator parameter))
    (parameter : Real) :
    (frame.toKernelComplementFamilyTrivialization hSelfAdjoint
      |>.transportedReducedOperator parameter) =
      selfAdjointKernelComplementOperator (operator 0) (hSelfAdjoint 0) := by
  ext vector
  rw [SelfAdjointKernelComplementFamilyTrivializationData.transportedReducedOperator_apply]
  change
    ((frame.kernelComplementFrame parameter).symm
      (selfAdjointKernelComplementOperator (operator parameter)
        (hSelfAdjoint parameter) (frame.kernelComplementFrame parameter vector))).1 =
      (selfAdjointKernelComplementOperator (operator 0) (hSelfAdjoint 0) vector).1
  have hSymm (current : (operator parameter).kerᗮ) :
      ((frame.kernelComplementFrame parameter).symm current).1 =
        (frame.frame parameter).symm current.1 := by
    apply (frame.frame parameter).injective
    rw [(frame.frame parameter).apply_symm_apply]
    rw [← frame.kernelComplementFrame_apply_val]
    rw [(frame.kernelComplementFrame parameter).apply_symm_apply]
  rw [hSymm]
  rw [selfAdjointKernelComplementOperator_apply]
  rw [frame.kernelComplementFrame_apply_val]
  rw [frame.intertwines_basepoint parameter vector.1]
  rw [(frame.frame parameter).symm_apply_apply]
  exact (selfAdjointKernelComplementOperator_apply
    (operator 0) (hSelfAdjoint 0) vector).symm

/-- A basepoint gap and the unitary frame produce the complete uniform-gap
trivialization packet expected by the fixed-fibre Bismut--Freed layer. -/
def toKernelComplementUniformGapTrivialization
    {operator : Real → E →L[Real] E}
    (frame : FiniteUnitaryIntertwiningOperatorFrameData operator)
    (hSelfAdjoint : ∀ parameter, IsSelfAdjoint (operator parameter))
    (basepointGap : FiniteKernelComplementBasepointNormGapData operator) :
    SelfAdjointKernelComplementUniformGapTrivializationData operator
      hSelfAdjoint where
  trivialization := frame.toKernelComplementFamilyTrivialization hSelfAdjoint
  gap := basepointGap.gap
  gap_pos := basepointGap.gap_pos
  lowerBound := by
    intro parameter vector
    simpa [SelfAdjointKernelComplementFamilyTrivializationData.currentReducedOperator]
      using frame.kernelComplement_subtype_norm_gap basepointGap parameter vector

/-- The fixed operator generated by the preceding packet is a constant family. -/
theorem fixedOperator_eq_basepoint
    {operator : Real → E →L[Real] E}
    (frame : FiniteUnitaryIntertwiningOperatorFrameData operator)
    (hSelfAdjoint : ∀ parameter, IsSelfAdjoint (operator parameter))
    (basepointGap : FiniteKernelComplementBasepointNormGapData operator)
    (parameter : Real) :
    (frame.toKernelComplementUniformGapTrivialization hSelfAdjoint basepointGap
      |>.fixedOperator parameter) =
      selfAdjointKernelComplementOperator (operator 0) (hSelfAdjoint 0) :=
  frame.transportedReducedOperator_eq_basepoint hSelfAdjoint parameter

/-- Hence the fixed operator family is differentiable with zero derivative. -/
theorem hasDerivAt_fixedOperator_zero
    {operator : Real → E →L[Real] E}
    (frame : FiniteUnitaryIntertwiningOperatorFrameData operator)
    (hSelfAdjoint : ∀ parameter, IsSelfAdjoint (operator parameter))
    (basepointGap : FiniteKernelComplementBasepointNormGapData operator)
    (parameter : Real) :
    HasDerivAt
      (frame.toKernelComplementUniformGapTrivialization hSelfAdjoint basepointGap
        |>.fixedOperator)
      0 parameter := by
  rw [show
    (frame.toKernelComplementUniformGapTrivialization hSelfAdjoint basepointGap
      |>.fixedOperator) =
        fun _ => selfAdjointKernelComplementOperator
          (operator 0) (hSelfAdjoint 0) by
    funext current
    exact frame.fixedOperator_eq_basepoint hSelfAdjoint basepointGap current]
  exact hasDerivAt_const (x := parameter)
    (c := selfAdjointKernelComplementOperator (operator 0) (hSelfAdjoint 0))

/-- The canonical Green family is constant in the fixed complement coordinates. -/
theorem fixedGreen_eq_basepoint
    {operator : Real → E →L[Real] E}
    (frame : FiniteUnitaryIntertwiningOperatorFrameData operator)
    (hSelfAdjoint : ∀ parameter, IsSelfAdjoint (operator parameter))
    (basepointGap : FiniteKernelComplementBasepointNormGapData operator)
    (parameter : Real) :
    (frame.toKernelComplementUniformGapTrivialization hSelfAdjoint basepointGap
      |>.fixedGreen parameter) =
      (frame.toKernelComplementUniformGapTrivialization hSelfAdjoint basepointGap
        |>.fixedGreen 0) := by
  let fixed :=
    frame.toKernelComplementUniformGapTrivialization hSelfAdjoint basepointGap
  change fixed.toUniformGapFamily.green parameter =
    fixed.toUniformGapFamily.green 0
  apply ContinuousLinearMap.ext
  intro vector
  apply (fixed.toUniformGapFamily.bijective parameter).1
  rw [fixed.toUniformGapFamily.operator_green parameter]
  rw [frame.fixedOperator_eq_basepoint hSelfAdjoint basepointGap parameter,
    ← frame.fixedOperator_eq_basepoint hSelfAdjoint basepointGap 0]
  exact (fixed.toUniformGapFamily.operator_green 0 vector).symm

/-- The fixed-coordinate Green family has zero derivative. -/
theorem hasDerivAt_fixedGreen_zero
    {operator : Real → E →L[Real] E}
    (frame : FiniteUnitaryIntertwiningOperatorFrameData operator)
    (hSelfAdjoint : ∀ parameter, IsSelfAdjoint (operator parameter))
    (basepointGap : FiniteKernelComplementBasepointNormGapData operator)
    (parameter : Real) :
    HasDerivAt
      (frame.toKernelComplementUniformGapTrivialization hSelfAdjoint basepointGap
        |>.fixedGreen)
      0 parameter := by
  rw [show
    (frame.toKernelComplementUniformGapTrivialization hSelfAdjoint basepointGap
      |>.fixedGreen) =
        fun _ =>
          (frame.toKernelComplementUniformGapTrivialization hSelfAdjoint
            basepointGap |>.fixedGreen 0) by
    funext current
    exact frame.fixedGreen_eq_basepoint hSelfAdjoint basepointGap current]
  exact hasDerivAt_const (x := parameter)
    (c := (frame.toKernelComplementUniformGapTrivialization hSelfAdjoint
      basepointGap |>.fixedGreen 0))

/-- Public unitary-frame/fixed-complement bridge. -/
theorem finite_unitary_frame_kernel_complement_trivialization_gate
    (operator : Real → E →L[Real] E)
    (hSelfAdjoint : ∀ parameter, IsSelfAdjoint (operator parameter))
    (frame : FiniteUnitaryIntertwiningOperatorFrameData operator)
    (basepointGap : FiniteKernelComplementBasepointNormGapData operator) :
    let fixed :=
      frame.toKernelComplementUniformGapTrivialization hSelfAdjoint basepointGap
    (∀ parameter,
      fixed.fixedOperator parameter =
        selfAdjointKernelComplementOperator (operator 0) (hSelfAdjoint 0)) ∧
    (∀ parameter,
      HasDerivAt fixed.fixedOperator 0 parameter) ∧
    fixed.gap = basepointGap.gap := by
  dsimp only
  exact
    ⟨frame.fixedOperator_eq_basepoint hSelfAdjoint basepointGap,
      frame.hasDerivAt_fixedOperator_zero hSelfAdjoint basepointGap,
      rfl⟩

end FiniteUnitaryIntertwiningOperatorFrameData

end
end P0EFTJanusProgramPFiniteUnitaryIntertwiningOperatorFrame4D
end JanusFormal
