import JanusFormal.Branches.FundamentalGeometryPVariationalPrinciple.Gates.P0EFTJanusProgramPT12NativeJetSpatialSmooth4D
import JanusFormal.Branches.FundamentalGeometryPVariationalPrinciple.Gates.P0EFTJanusProgramPT12MetricJetLinearizationSmooth4D
import JanusFormal.Branches.FundamentalGeometryPVariationalPrinciple.Gates.P0EFTJanusProgramPT12NativeEinsteinJetCoefficients4D
import JanusFormal.Branches.FundamentalGeometryPVariationalPrinciple.Gates.P0EFTJanusProgramPT12EinsteinSymbolJointSmooth4D
import JanusFormal.Branches.FundamentalGeometryPVariationalPrinciple.Gates.P0EFTJanusProgramPT12NativeCurvatureJetVelocity4D
import JanusFormal.Branches.FundamentalGeometryPVariationalPrinciple.Gates.P0EFTJanusProgramPT12NativeCurvatureJetAcceleration4D
import JanusFormal.Branches.FundamentalGeometryPVariationalPrinciple.Gates.P0EFTJanusProgramPT12MetricJetLinearization4D
import JanusFormal.Branches.FundamentalGeometryPVariationalPrinciple.Gates.P0EFTJanusProgramPT12EinsteinJetHessianIntegral4D
import JanusFormal.Branches.FundamentalGeometryPVariationalPrinciple.Gates.P0EFTJanusProgramPRegularGeneralMetricC2SmoothMetricParameterJet4D
import JanusFormal.Branches.FundamentalGeometryPVariationalPrinciple.Gates.P0EFTJanusProgramPRegularGeneralMetricC2InverseVelocityPointwise4D
import JanusFormal.Branches.FundamentalGeometryPVariationalPrinciple.Gates.P0EFTJanusProgramPT12NativeCurvatureJetHessian4D
import JanusFormal.Branches.FundamentalGeometryPVariationalPrinciple.Gates.P0EFTJanusProgramPT12CurvatureJetDifferentials4D
import JanusFormal.Branches.FundamentalGeometryPVariationalPrinciple.Gates.P0EFTJanusProgramPT12InverseMetricHessianPointwise4D
import JanusFormal.Branches.FundamentalGeometryPVariationalPrinciple.Gates.P0EFTJanusProgramPT12MetricJetAcceleration4D
import JanusFormal.Branches.FundamentalGeometryPVariationalPrinciple.Gates.P0EFTJanusProgramPT12NativeCurvatureJetBridge4D
import JanusFormal.Branches.FundamentalGeometryPVariationalPrinciple.Gates.P0EFTJanusProgramPT12NonlinearHessianPullback4D
import JanusFormal.Branches.FundamentalGeometryPVariationalPrinciple.Gates.P0EFTJanusProgramPT12CurvatureJetSymbol4D
import JanusFormal.Branches.FundamentalGeometryPVariationalPrinciple.Gates.P0EFTJanusProgramPT12AffineHessianPullback4D
import JanusFormal.Branches.FundamentalGeometryPVariationalPrinciple.Gates.P0EFTJanusPairedStrongMetricInvariantEinsteinVolumeCorrection4D
import JanusFormal.Branches.FundamentalGeometryPVariationalPrinciple.Gates.P0EFTJanusProgramPT12PairedEinsteinHilbertL24D
import JanusFormal.Branches.FundamentalGeometryPVariationalPrinciple.Gates.P0EFTJanusRegularFrameCanonicalGeneratorsDivergenceZero4D
import JanusFormal.Branches.FundamentalGeometryPVariationalPrinciple.Gates.P0EFTJanusProgramPRegularGeneralMetricC2EinsteinHilbertFixedVariableVolumeDiscrepancy4D
import JanusFormal.Branches.FundamentalGeometryPVariationalPrinciple.Gates.P0EFTJanusProgramPRegularGeneralMetricC2PairedMinimalPhysicalStrongMetricAllActionDerivatives4D

/-! Actual Einstein Hessian coefficients as smooth scalar fields. -/

namespace JanusFormal
namespace P0EFTJanusProgramPT12NativeEinsteinCoefficientFields4D

set_option autoImplicit false
set_option backward.isDefEq.respectTransparency false
set_option maxRecDepth 2048
set_option maxHeartbeats 800000
set_option synthInstance.maxHeartbeats 600000

noncomputable section
open Set MeasureTheory
open scoped Manifold ContDiff
open P0EFTJanusConvexHelmholtzReconstruction
open P0EFTJanusMappingTorusQuotient
open P0EFTJanusMappingTorusSmoothAtlasFrontier
open P0EFTJanusMappingTorusSmoothQuotientManifold
open P0EFTJanusMappingTorusCompactQuotient
open P0EFTJanusMappingTorusCanonicalDivergenceFreeLLFrame4D
open P0EFTJanusMappingTorusGeneralLorentzTensor4D
open P0EFTJanusMappingTorusGeneralLorentzMetricBVFirstLevel4D
open P0EFTJanusMappingTorusGeneralScalarFunctionalAction4D
open P0EFTJanusMappingTorusIntrinsicEinsteinHilbertAction4D
open P0EFTJanusMappingTorusFrameFreeRelativeLorentzVolume4D
open P0EFTJanusMappingTorusCanonicalLorentzVolumeGluing4D
open P0EFTJanusMappingTorusCanonicalPhysicalScalarC2JetCore4D
open P0EFTJanusProgramPGlobalCovariantAction4D
open P0EFTJanusProgramPGlobalEulerLagrange4D
open P0EFTJanusProgramPGlobalFieldSpace4D
open P0EFTJanusProgramPGlobalAnalysisDomain4D
open P0EFTJanusProgramPGlobalTypedNonminimalFieldSpace4D
open P0EFTJanusProgramPGlobalCandidateAMinimalPhysicalGraphProjections4D
open P0EFTJanusProgramPGlobalEulerLagrangeMinimalPhysicalComponentPDEBlockPairing4D
open P0EFTJanusProgramPPrimitiveSpinCMatterGraphSameActionHessian4D
open P0EFTJanusProgramPRegularGeneralMetricC2Chart4D
open P0EFTJanusProgramPRegularGeneralMetricC2EinsteinHilbert4D
open P0EFTJanusProgramPRegularGeneralMetricC2EinsteinHilbertDerivative4D
open P0EFTJanusProgramPRegularGeneralMetricC2MaxwellStressDerivative4D
open P0EFTJanusProgramPRegularGeneralMetricGlobalSmoothSymmetricEinsteinTensor4D
open P0EFTJanusProgramPRegularFrameEinsteinHilbertFrameFreeActionMeasureBridge4D
open P0EFTJanusProgramPRegularGeneralMetricAffineNondegenerateBridge4D
open P0EFTJanusProgramPRegularGeneralMetricC2PairedLorentzChartCenter4D
open P0EFTJanusProgramPRegularGeneralMetricC2PairedMinimalPhysicalMetricCoreProjection4D
open P0EFTJanusProgramPRegularGeneralMetricC2PairedMinimalPhysicalRelativeMetricCoreProjection4D
open P0EFTJanusProgramPRegularGeneralMetricC2PairedMinimalPhysicalAdmissibleLocalActionFamily4D
open P0EFTJanusProgramPRegularGeneralMetricC2PairedMinimalPhysicalConstantBoundaryC24D
open P0EFTJanusProgramPRegularGeneralMetricC2PairedMinimalPhysicalLLC0FirstJetProjection4D
open P0EFTJanusProgramPRegularGeneralMetricC2PairedMinimalPhysicalNineBlockC24D
open P0EFTJanusProgramPRegularGeneralMetricC2PairedMinimalPhysicalStrongLocalEuler4D
open P0EFTJanusProgramPRegularGeneralMetricC2PairedMinimalPhysicalStrongMetricTotalEulerReduction4D
open P0EFTJanusProgramPRegularGeneralMetricC2PairedMinimalPhysicalStrongInteractionDerivative4D
open P0EFTJanusProgramPRegularGeneralMetricC2PairedMinimalPhysicalStrongEinsteinHilbertDerivative4D
open P0EFTJanusProgramPRegularGeneralMetricC2PairedMinimalPhysicalStrongMaxwellDerivative4D
open P0EFTJanusProgramPRegularGeneralMetricC2PairedFixedVolumeEinsteinHilbertC24D
open P0EFTJanusRegularFrameCanonicalGeneratorsDivergenceZero4D
open P0EFTJanusProgramPRegularGeneralMetricC2EinsteinHilbertFixedVariableVolumeDiscrepancy4D
open P0EFTJanusProgramPRegularGeneralMetricC2PairedMinimalPhysicalStrongMetricAllActionDerivatives4D

attribute [local instance 2000]
  NormedAddCommGroup.toAddCommGroup NormedSpace.toModule
  PseudoMetricSpace.toUniformSpace UniformSpace.toTopologicalSpace
attribute [local instance 1900]
  P0EFTJanusProgramPRegularGeneralMetricC2PairedInteractionActionDerivative4D.relativeCoreNormedAddCommGroup
  P0EFTJanusProgramPRegularGeneralMetricC2PairedInteractionActionDerivative4D.relativeCoreNormedSpace

variable (period : Real) (hPeriod : period ≠ 0)
private abbrev EffectiveQuotient := MappingTorus (reflectedSphereData period hPeriod)
private abbrev C2Scalar := CanonicalPhysicalScalarC2JetCore period hPeriod

local instance : ChartedSpace CoverModel (EffectiveQuotient period hPeriod) :=
  reflectedSphereQuotientChartedSpace period hPeriod
local instance : IsManifold coverModelWithCorners ω (EffectiveQuotient period hPeriod) :=
  reflectedSphereQuotient_isManifold period hPeriod
local instance : CompactSpace (EffectiveQuotient period hPeriod) :=
  reflectedSphereQuotientCompactSpace period hPeriod
local instance : MeasurableSpace (EffectiveQuotient period hPeriod) := borel _
local instance : BorelSpace (EffectiveQuotient period hPeriod) where
  measurable_eq := rfl
local instance : IsFiniteMeasure (intrinsicCanonicalLorentzVolumeMeasure period hPeriod) :=
  intrinsicCanonicalLorentzVolumeMeasure_isFinite period hPeriod
local instance : NormedAddCommGroup (C2Scalar period hPeriod) :=
  (canonicalPhysicalScalarC2JetCoreSubmodule period hPeriod).normedAddCommGroup
local instance : NormedSpace Real (C2Scalar period hPeriod) := inferInstance
local instance : CompleteSpace (C2Scalar period hPeriod) :=
  canonicalPhysicalScalarC2JetCoreCompleteSpace period hPeriod

open P0EFTJanusProgramPRegularGeneralMetricC2LorentzChartDomain4D
open P0EFTJanusProgramPT12AffineHessianPullback4D

open P0EFTJanusProgramPT12CurvatureJetSymbol4D

open P0EFTJanusProgramPT12NativeCurvatureJetBridge4D
open P0EFTJanusProgramPT12NonlinearHessianPullback4D

open P0EFTJanusProgramPT12NativeCurvatureJetHessian4D
open P0EFTJanusProgramPT12CurvatureJetDifferentials4D
open P0EFTJanusProgramPT12VectorHessianPullback4D
open P0EFTJanusProgramPT12InverseMetricHessianPointwise4D
open P0EFTJanusProgramPT12MetricJetAcceleration4D
open P0EFTJanusProgramPRegularGeneralMetricC2MaxwellDensityPointwise4D
open P0EFTJanusProgramPRegularFrameMetricInverse4D

open P0EFTJanusProgramPRegularGeneralMetricC2SmoothMetricParameterJet4D
open P0EFTJanusProgramPRegularGeneralMetricC2InverseVelocityPointwise4D
open P0EFTJanusProgramPRegularGeneralMetricC2ScalarCurvatureDerivativePointwise4D

open P0EFTJanusProgramPT12NativeCurvatureJetVelocity4D
open P0EFTJanusProgramPT12NativeCurvatureJetAcceleration4D
open P0EFTJanusProgramPT12MetricJetCovector4D
open P0EFTJanusProgramPT12MetricJetLinearization4D
open P0EFTJanusProgramPT12EinsteinJetHessianIntegral4D
open P0EFTJanusProgramPT12NativeEinsteinHilbertHessian4D

open P0EFTJanusProgramPT12NativeEinsteinJetCoefficients4D
open P0EFTJanusProgramPT12EinsteinSymbolJointSmooth4D
open P0EFTJanusMappingTorusH1GraphTrace4D

open P0EFTJanusMappingTorusGeneralHolonomicScalarDensity4D
open P0EFTJanusProgramPT12NativeJetSpatialSmooth4D
open P0EFTJanusProgramPT12MetricJetLinearizationSmooth4D

local instance : NormedAddCommGroup CurvatureJet := inferInstance
local instance : NormedSpace Real CurvatureJet := inferInstance
local instance : NormedAddCommGroup MetricVariationJet := inferInstance
local instance : NormedSpace Real MetricVariationJet := inferInstance

variable (metric : RegularGeneralLorentzMetric period hPeriod) (couplings : EinsteinHilbertCouplings)

theorem nativeEinsteinJetCovector_apply_contMDiff
    (first : SmoothSymmetricCovariantTwoTensor period hPeriod) (test : MetricVariationJet) :
    ContMDiff coverModelWithCorners 𝓘(Real, Real) ∞
      (fun point => nativeEinsteinJetCovector period hPeriod metric couplings first point test) := by
  have hGradient : ContMDiff coverModelWithCorners 𝓘(Real, CurvatureJet →L[Real] Real) ∞
      (fun point => fderiv Real (jetEinsteinDensity period hPeriod metric couplings point)
        (nativeCurvatureJet period hPeriod metric 0 point)) :=
    (einsteinSymbolGradient_contDiff couplings.gravitationalCoupling couplings.cosmologicalConstant).comp_contMDiff
      (nativeEinsteinSymbolInput_contMDiff period hPeriod metric)
  have hHessian : ContMDiff coverModelWithCorners 𝓘(Real, CurvatureJet →L[Real] CurvatureJet →L[Real] Real) ∞
      (fun point => fderiv Real (fderiv Real (jetEinsteinDensity period hPeriod metric couplings point))
        (nativeCurvatureJet period hPeriod metric 0 point)) :=
    (einsteinSymbolHessian_contDiff couplings.gravitationalCoupling couplings.cosmologicalConstant).comp_contMDiff
      (nativeEinsteinSymbolInput_contMDiff period hPeriod metric)
  have hInverse : ContMDiff coverModelWithCorners 𝓘(Real, MetricMatrix) ∞
      (fun point row column => regularFrameMetricInverseMatrix period hPeriod metric row column point) :=
    nativeInverseCoefficients_contMDiff period hPeriod metric
  have hFirst := smoothMetricVariationJet_contMDiff period hPeriod metric first
  have hVelocityFirst := metricJetVelocity_joint_contDiff.comp_contMDiff (hInverse.prodMk_space hFirst)
  have hVelocityTest := metricJetVelocity_joint_contDiff.comp_contMDiff
    (hInverse.prodMk_space (contMDiff_const (c := test)))
  have hAcceleration := metricJetAcceleration_joint_contDiff.comp_contMDiff
    (hInverse.prodMk_space (hFirst.prodMk_space (contMDiff_const (c := test))))
  exact ((hHessian.clm_apply hVelocityFirst).clm_apply hVelocityTest).add (hGradient.clm_apply hAcceleration)

def nativeEinsteinJetValueField (first : SmoothSymmetricCovariantTwoTensor period hPeriod)
    (row column : Fin 4) : SmoothScalarField period hPeriod where
  toFun point := nativeEinsteinJetValueCoefficient period hPeriod metric couplings first point row column
  contMDiff_toFun := nativeEinsteinJetCovector_apply_contMDiff period hPeriod metric couplings first (valueBasis row column)

def nativeEinsteinJetFirstField (first : SmoothSymmetricCovariantTwoTensor period hPeriod)
    (direction row column : Fin 4) : SmoothScalarField period hPeriod where
  toFun point := nativeEinsteinJetFirstCoefficient period hPeriod metric couplings first point direction row column
  contMDiff_toFun := nativeEinsteinJetCovector_apply_contMDiff period hPeriod metric couplings first (firstBasis direction row column)

def nativeEinsteinJetSecondField (first : SmoothSymmetricCovariantTwoTensor period hPeriod)
    (outer inner row column : Fin 4) : SmoothScalarField period hPeriod where
  toFun point := nativeEinsteinJetSecondCoefficient period hPeriod metric couplings first point outer inner row column
  contMDiff_toFun := nativeEinsteinJetCovector_apply_contMDiff period hPeriod metric couplings first (secondBasis outer inner row column)

@[simp] theorem nativeEinsteinJetValueField_apply (first : SmoothSymmetricCovariantTwoTensor period hPeriod)
    (row column : Fin 4) (point : EffectiveQuotient period hPeriod) :
    nativeEinsteinJetValueField period hPeriod metric couplings first row column point =
      nativeEinsteinJetValueCoefficient period hPeriod metric couplings first point row column := rfl

@[simp] theorem nativeEinsteinJetFirstField_apply (first : SmoothSymmetricCovariantTwoTensor period hPeriod)
    (direction row column : Fin 4) (point : EffectiveQuotient period hPeriod) :
    nativeEinsteinJetFirstField period hPeriod metric couplings first direction row column point =
      nativeEinsteinJetFirstCoefficient period hPeriod metric couplings first point direction row column := rfl

@[simp] theorem nativeEinsteinJetSecondField_apply (first : SmoothSymmetricCovariantTwoTensor period hPeriod)
    (outer inner row column : Fin 4) (point : EffectiveQuotient period hPeriod) :
    nativeEinsteinJetSecondField period hPeriod metric couplings first outer inner row column point =
      nativeEinsteinJetSecondCoefficient period hPeriod metric couplings first point outer inner row column := rfl

end
end P0EFTJanusProgramPT12NativeEinsteinCoefficientFields4D
end JanusFormal
