import JanusFormal.Branches.FundamentalGeometryPVariationalPrinciple.Gates.P0EFTJanusMappingTorusCanonicalPhysicalScalarCauchyJetCandidateExtension4D
import JanusFormal.Branches.FundamentalGeometryPVariationalPrinciple.Gates.P0EFTJanusMappingTorusCanonicalLatitudeSmoothCauchyJet4D

/-!
# Global Cauchy-jet smoothness from a two-open-set cover

The explicit physical Cauchy candidate is the tubular expression on the embedded
latitude collar and zero away from that image.  Its global smoothness is local.
It is therefore enough to exhibit two open regions covering the physical bulk:

* a tubular region on which the candidate is smooth at every point;
* a polar region on which the candidate is identically zero.

This file turns that local open-cover statement into the global `C∞` theorem and
then installs the complete candidate extension package.  The boundary
representatives, their deck parity and their `L²` embeddings are separated from
the remaining local geometry.
-/

namespace JanusFormal
namespace P0EFTJanusMappingTorusCanonicalPhysicalScalarCauchyJetOpenCoverSmoothness4D

set_option autoImplicit false
noncomputable section

open scoped Manifold ContDiff ENNReal
open MeasureTheory Set Topology Filter
open P0EFTJanusMappingTorusQuotient
open P0EFTJanusMappingTorusSmoothAtlasFrontier
open P0EFTJanusMappingTorusSmoothQuotientManifold
open P0EFTJanusMappingTorusCanonicalPhysicalH1TraceBound4D
open P0EFTJanusMappingTorusCanonicalPhysicalScalarFirstSheetHilbertTrace4D
open P0EFTJanusMappingTorusCanonicalLatitudeCauchyJetDeckGluing4D
open P0EFTJanusMappingTorusCanonicalLatitudeCauchyJetCollarQuotient4D
open P0EFTJanusMappingTorusCanonicalPhysicalScalarCauchyJetGlobalCandidate4D
open P0EFTJanusMappingTorusCanonicalPhysicalScalarCauchyJetCandidateExtension4D

universe x y

variable (period : Real) (hPeriod : period ≠ 0)

private abbrev sphereData := reflectedSphereData period hPeriod
private abbrev EffectiveQuotient := MappingTorus (sphereData period hPeriod)
private abbrev BoundaryL2 := CanonicalPhysicalScalarFirstSheetL2 period

local instance effectiveQuotientChartedSpace :
    ChartedSpace CoverModel (EffectiveQuotient period hPeriod) :=
  reflectedSphereQuotientChartedSpace period hPeriod

local instance effectiveQuotientIsManifold :
    IsManifold coverModelWithCorners ω (EffectiveQuotient period hPeriod) :=
  reflectedSphereQuotient_isManifold period hPeriod

/-- Boundary-core data before proving global smoothness of the explicit physical
candidate. -/
structure CanonicalPhysicalScalarCauchyJetBoundaryCoreData
    (ValueCore : Type x) (NormalCore : Type y)
    [AddCommGroup ValueCore] [Module Real ValueCore]
    [AddCommGroup NormalCore] [Module Real NormalCore] where
  valueRepresentative : ValueCore →ₗ[Real]
    (CanonicalLatitudeBase → Real)
  normalRepresentative : NormalCore →ₗ[Real]
    (CanonicalLatitudeBase → Real)
  valuePeriodic : ∀ value : ValueCore,
    CanonicalLatitudeValueDeckPeriodic period (valueRepresentative value)
  normalAntiperiodic : ∀ normal : NormalCore,
    CanonicalLatitudeNormalDeckAntiperiodic period
      (normalRepresentative normal)
  valueEmbedding : ValueCore →ₗ[Real] BoundaryL2 period
  normalEmbedding : NormalCore →ₗ[Real] BoundaryL2 period
  valueDense : DenseRange valueEmbedding
  normalDense : DenseRange normalEmbedding
  valueEmbedding_ae : ∀ value : ValueCore,
    (valueEmbedding value : CanonicalLatitudeBase → Real) =ᵐ[
      canonicalLatitudeBaseMeasure period]
      valueRepresentative value
  normalEmbedding_ae : ∀ normal : NormalCore,
    (normalEmbedding normal : CanonicalLatitudeBase → Real) =ᵐ[
      canonicalLatitudeBaseMeasure period]
      normalRepresentative normal

namespace CanonicalPhysicalScalarCauchyJetBoundaryCoreData

/-- Linear deck-compatible boundary data generated by the two core
representatives. -/
def deckData
    {ValueCore : Type x} {NormalCore : Type y}
    [AddCommGroup ValueCore] [Module Real ValueCore]
    [AddCommGroup NormalCore] [Module Real NormalCore]
    (coreData : CanonicalPhysicalScalarCauchyJetBoundaryCoreData
      period ValueCore NormalCore) :
    ValueCore × NormalCore →ₗ[Real]
      CanonicalLatitudeDeckCauchyData period :=
  canonicalLatitudeDeckCauchyDataLinearMapOfRepresentatives period
    coreData.valueRepresentative coreData.normalRepresentative
    coreData.valuePeriodic coreData.normalAntiperiodic

/-- Explicit global candidate associated to one pair of boundary-core data. -/
def candidate
    {ValueCore : Type x} {NormalCore : Type y}
    [AddCommGroup ValueCore] [Module Real ValueCore]
    [AddCommGroup NormalCore] [Module Real NormalCore]
    (coreData : CanonicalPhysicalScalarCauchyJetBoundaryCoreData
      period ValueCore NormalCore)
    (data : ValueCore × NormalCore) :
    EffectiveQuotient period hPeriod → Real :=
  canonicalLatitudeCauchyJetGlobalCandidate period hPeriod
    (coreData.deckData data)

end CanonicalPhysicalScalarCauchyJetBoundaryCoreData

/-- A two-open-set proof of smoothness for every explicit Cauchy candidate.  The
`tubular_smoothAt` field is deliberately pointwise: later tubular-coordinate
work can provide it directly without first packaging an `IsOpen` image theorem.
The second region is open and the candidate vanishes there, so smoothness follows
from local equality with the zero function. -/
structure CanonicalPhysicalScalarCauchyJetOpenCoverData
    (ValueCore : Type x) (NormalCore : Type y)
    [AddCommGroup ValueCore] [Module Real ValueCore]
    [AddCommGroup NormalCore] [Module Real NormalCore] where
  core : CanonicalPhysicalScalarCauchyJetBoundaryCoreData
    period ValueCore NormalCore
  tubularRegion : Set (EffectiveQuotient period hPeriod)
  zeroRegion : Set (EffectiveQuotient period hPeriod)
  zeroRegion_open : IsOpen zeroRegion
  cover : tubularRegion ∪ zeroRegion = Set.univ
  tubular_smoothAt : ∀ (data : ValueCore × NormalCore)
    (point : EffectiveQuotient period hPeriod),
    point ∈ tubularRegion →
      ContMDiffAt coverModelWithCorners 𝓘(Real, Real) ∞
        (core.candidate hPeriod data) point
  zero_on : ∀ data : ValueCore × NormalCore,
    Set.EqOn (core.candidate hPeriod data) (fun _ => 0) zeroRegion

namespace CanonicalPhysicalScalarCauchyJetOpenCoverData

/-- On the open zero region the candidate is locally equal to the zero
function. -/
theorem candidate_eventuallyEq_zero
    {ValueCore : Type x} {NormalCore : Type y}
    [AddCommGroup ValueCore] [Module Real ValueCore]
    [AddCommGroup NormalCore] [Module Real NormalCore]
    (openCover : CanonicalPhysicalScalarCauchyJetOpenCoverData
      period hPeriod ValueCore NormalCore)
    (data : ValueCore × NormalCore)
    (point : EffectiveQuotient period hPeriod)
    (hPoint : point ∈ openCover.zeroRegion) :
    openCover.core.candidate hPeriod data =ᶠ[𝓝 point]
      fun _ : EffectiveQuotient period hPeriod => 0 := by
  filter_upwards [openCover.zeroRegion_open.mem_nhds hPoint]
    with nearby hNearby
  exact openCover.zero_on data hNearby

/-- The two local statements imply global smoothness of every candidate. -/
theorem candidate_contMDiff
    {ValueCore : Type x} {NormalCore : Type y}
    [AddCommGroup ValueCore] [Module Real ValueCore]
    [AddCommGroup NormalCore] [Module Real NormalCore]
    (openCover : CanonicalPhysicalScalarCauchyJetOpenCoverData
      period hPeriod ValueCore NormalCore)
    (data : ValueCore × NormalCore) :
    ContMDiff coverModelWithCorners 𝓘(Real, Real) ∞
      (openCover.core.candidate hPeriod data) := by
  intro point
  have hCovered : point ∈ openCover.tubularRegion ∪ openCover.zeroRegion := by
    rw [openCover.cover]
    trivial
  rcases hCovered with hTubular | hZero
  · exact openCover.tubular_smoothAt data point hTubular
  · have hConstant : ContMDiffAt coverModelWithCorners 𝓘(Real, Real) ∞
        (fun _ : EffectiveQuotient period hPeriod => (0 : Real)) point :=
      contMDiffAt_const
    exact hConstant.congr_of_eventuallyEq
      (openCover.candidate_eventuallyEq_zero data point hZero)

/-- Install the complete smooth candidate-extension package. -/
def toCandidateExtensionData
    {ValueCore : Type x} {NormalCore : Type y}
    [AddCommGroup ValueCore] [Module Real ValueCore]
    [AddCommGroup NormalCore] [Module Real NormalCore]
    (openCover : CanonicalPhysicalScalarCauchyJetOpenCoverData
      period hPeriod ValueCore NormalCore) :
    CanonicalPhysicalScalarCauchyJetCandidateExtensionData
      period hPeriod ValueCore NormalCore where
  valueRepresentative := openCover.core.valueRepresentative
  normalRepresentative := openCover.core.normalRepresentative
  valuePeriodic := openCover.core.valuePeriodic
  normalAntiperiodic := openCover.core.normalAntiperiodic
  valueEmbedding := openCover.core.valueEmbedding
  normalEmbedding := openCover.core.normalEmbedding
  valueDense := openCover.core.valueDense
  normalDense := openCover.core.normalDense
  valueEmbedding_ae := openCover.core.valueEmbedding_ae
  normalEmbedding_ae := openCover.core.normalEmbedding_ae
  candidate_contMDiff := openCover.candidate_contMDiff

/-- Open-cover smoothness immediately gives the exact smooth Cauchy extension and
dense boundary trace. -/
theorem certificate
    {ValueCore : Type x} {NormalCore : Type y}
    [AddCommGroup ValueCore] [Module Real ValueCore]
    [AddCommGroup NormalCore] [Module Real NormalCore]
    (openCover : CanonicalPhysicalScalarCauchyJetOpenCoverData
      period hPeriod ValueCore NormalCore) :
    (∀ data : ValueCore × NormalCore,
      ContMDiff coverModelWithCorners 𝓘(Real, Real) ∞
        (openCover.core.candidate hPeriod data)) ∧
      DenseRange
        (P0EFTJanusMappingTorusCanonicalPhysicalScalarFirstSheetHilbertTrace4D.smoothCanonicalPhysicalScalarFirstSheetCauchyTrace
          period hPeriod) :=
  ⟨openCover.candidate_contMDiff,
    openCover.toCandidateExtensionData.boundaryTrace_denseRange⟩

end CanonicalPhysicalScalarCauchyJetOpenCoverData

end
end P0EFTJanusMappingTorusCanonicalPhysicalScalarCauchyJetOpenCoverSmoothness4D
end JanusFormal
