import JanusFormal.Branches.FundamentalGeometryPVariationalPrinciple.Gates.P0EFTJanusProgramPFiveSectorOperatorBlockDiagonalization4D
import JanusFormal.Branches.FundamentalGeometryPVariationalPrinciple.Gates.P0EFTJanusProgramPGlobalHessianPreferredFiveSectorNaturalEllipticSectorRepresentation4D
import JanusFormal.Branches.FundamentalGeometryPVariationalPrinciple.Gates.P0EFTJanusProgramPGlobalCandidateAFiveSectorCompletionResolutionBridge4D

/-!
# Exact five-sector block diagonalization of the Candidate-A basepoint Hessian

The preferred Bismut--Freed family stores `actual_zero`, identifying its
parameter-zero operator with the concrete H12/H14 Candidate-A Hessian.  The H12
frontier already proves that this concrete operator commutes with the five
projectors generated by the unique completion isometry.

Consequently no block operators are supplied independently here.  The five
physical blocks are extracted from `actualOperator 0`, and conjugating that
same operator by the exact completion isometry is proved to be their direct
five-sector sum.
-/

namespace JanusFormal
namespace P0EFTJanusProgramPGlobalHessianPreferredFiveSectorBasepointBlockDiagonalization4D

set_option autoImplicit false
set_option maxHeartbeats 46000000
set_option synthInstance.maxHeartbeats 23000000
noncomputable section

open Set Topology MeasureTheory
open scoped BigOperators Manifold ContDiff InnerProductSpace
open P0EFTJanusMappingTorusQuotient
open P0EFTJanusMappingTorusSmoothAtlasFrontier
open P0EFTJanusMappingTorusSmoothQuotientManifold
open P0EFTJanusProgramPGlobalFieldSpace4D
open P0EFTJanusProgramPGlobalTypedNonminimalFieldSpace4D
open P0EFTJanusProgramPGlobalCovariantAction4D
open P0EFTJanusProgramPGlobalAnalysisDomain4D
open P0EFTJanusProgramPGlobalCandidateAMatterLLSameActionClosure4D
open P0EFTJanusProgramPGlobalCandidateAMinimalPhysicalActionFamilyH10Reduction4D
open P0EFTJanusProgramPGlobalCandidateACanonicalSixDenseCore4D
open P0EFTJanusProgramPGlobalCandidateAFiveSectorCompletionResolutionBridge4D
open P0EFTJanusProgramPGlobalCandidateANamedZeroModeSectors4D
open P0EFTJanusProgramPGlobalHessianPreferredFiveSectorNamedKernelFamilyClosure4D
open P0EFTJanusProgramPGlobalHessianPreferredFiveSectorNaturalEllipticSectorRepresentation4D
open P0EFTJanusProgramPFiveSectorHilbertCoordinates4D
open P0EFTJanusProgramPFiveSectorOperatorBlockDiagonalization4D
open P0EFTJanusProgramPDenseCoreChartBilinearBound4D

variable (period : Real) (hPeriod : period ≠ 0)

private abbrev EffectiveQuotient :=
  MappingTorus (reflectedSphereData period hPeriod)

local instance effectiveQuotientChartedSpace :
    ChartedSpace CoverModel (EffectiveQuotient period hPeriod) :=
  reflectedSphereQuotientChartedSpace period hPeriod

local instance effectiveQuotientIsManifold :
    IsManifold coverModelWithCorners ω (EffectiveQuotient period hPeriod) :=
  reflectedSphereQuotient_isManifold period hPeriod

local instance effectiveQuotientMeasurableSpace :
    MeasurableSpace (EffectiveQuotient period hPeriod) := borel _

local instance effectiveQuotientBorelSpace :
    BorelSpace (EffectiveQuotient period hPeriod) where
  measurable_eq := rfl

variable
    {couplings : GlobalCandidateAActionCouplings}
    {NonNullFace NullFace : Type*}
    [Fintype NonNullFace] [Fintype NullFace]
    {configuration : GlobalGaugeFixedFieldConfiguration period hPeriod}
    {data : GlobalCandidateAActionData period hPeriod configuration.physical
      couplings NonNullFace NullFace}
    {analysis : GlobalAnalysisData period hPeriod configuration.physical}
    {einsteinScale : Real}
    {hTransverse : HasNoTangentialRadical period hPeriod
      data.plusGravity.metric.metric}
    {family : ProgramPGlobalMinimalPhysicalLocalActionFamilyH10ReducedData4D
      period hPeriod configuration data analysis
        (diracGreenClosureMatterRealization period hPeriod
          couplings.matterMassSquared) einsteinScale}
    {chartBound : DenseCoreChartMapBound
      (globalCandidateASevenPhysicalCoreEmbedding period hPeriod configuration
        data analysis)
      (globalCandidateACanonicalSixCoreToChart period hPeriod configuration data
        analysis
          (globalCandidateAActualKernelChart period hPeriod configuration data
            analysis einsteinScale hTransverse family)
          (globalCandidateAActualKernelSameAction period hPeriod configuration
            data analysis einsteinScale hTransverse family))}
    {Metric Abelian Matter Longitudinal Boundary : Type*}
    [NormedAddCommGroup Metric] [InnerProductSpace Real Metric]
    [NormedAddCommGroup Abelian] [InnerProductSpace Real Abelian]
    [NormedAddCommGroup Matter] [InnerProductSpace Real Matter]
    [NormedAddCommGroup Longitudinal] [InnerProductSpace Real Longitudinal]
    [NormedAddCommGroup Boundary] [InnerProductSpace Real Boundary]
    {ZeroMode : Type*} [Fintype ZeroMode] [DecidableEq ZeroMode]
    {fold : Fold} {Index : Type*}

private def fivePhysicalSectorToCandidateA :
    FivePhysicalSector → CandidateAZeroModeSector
  | .metricDiffeomorphism => .metricDiffeomorphism
  | .abelianGauge => .abelianGauge
  | .primitiveSpinCMatter => .primitiveSpinCMatter
  | .longitudinalLL => .longitudinalLL
  | .boundaryFiniteBV => .boundaryFiniteBV

@[simp]
private theorem candidateA_to_fivePhysical_leftInverse
    (sector : FivePhysicalSector) :
    candidateAZeroModeSectorToFivePhysicalSector
        (fivePhysicalSectorToCandidateA sector) = sector := by
  cases sector <;> rfl

/-- The parameter-zero member of the genuine Candidate-A family, equipped with
the one completion-derived commuting five-sector geometry. -/
def preferredCandidateABasepointCommutingOperator
    (input : GlobalHessianPreferredFiveSectorNamedKernelFamilyClosure4D
      period hPeriod configuration data analysis einsteinScale hTransverse family
        chartBound Metric Abelian Matter Longitudinal Boundary ZeroMode fold
          Index) :
    FiveSectorCommutingOperatorData
      (Metric := Metric) (Abelian := Abelian) (Matter := Matter)
      (Longitudinal := Longitudinal) (Boundary := Boundary)
      (input.familyIndex.baseFamily.actualOperator 0) where
  coordinates := preferredCandidateAFiveSectorHilbertCoordinates
    period hPeriod input
  commutes := by
    intro sector vector
    let candidateSector := fivePhysicalSectorToCandidateA sector
    let sectorData :=
      input.familyIndex.baseFamily.quillen.intrinsicFamily.basepoint.intrinsic.
        closure.frontier.analytic.geometry.coordinates
    have hCommute :=
      input.familyIndex.baseFamily.quillen.intrinsicFamily.basepoint.intrinsic.
        closure.frontier.analytic.geometry.commute period hPeriod
          candidateSector vector
    have hProjection :=
      globalCandidateAFiveSectorOrthogonalProjection_agreement period hPeriod
        configuration data analysis sectorData candidateSector vector
    have hProjectionOperator :=
      globalCandidateAFiveSectorOrthogonalProjection_agreement period hPeriod
        configuration data analysis sectorData candidateSector
        (input.familyIndex.baseFamily.actualOperator 0 vector)
    have hProjection' :
        globalCandidateAFiveSectorOrthogonalProjection period hPeriod
            (globalCandidateAFiveSectorOrthogonalProductOfCompletionCoordinates
              period hPeriod configuration data analysis sectorData)
            candidateSector vector =
          (preferredCandidateAFiveSectorHilbertCoordinates period hPeriod input).
            sectorProjector sector vector := by
      simpa [preferredCandidateAFiveSectorHilbertCoordinates, candidateSector,
        sectorData] using hProjection
    rw [input.familyIndex.baseFamily.actual_zero] at hProjectionOperator
    have hProjectionOperator' := hProjectionOperator
    have hProjectionOperator'' :
        globalCandidateAFiveSectorOrthogonalProjection period hPeriod
            (globalCandidateAFiveSectorOrthogonalProductOfCompletionCoordinates
              period hPeriod configuration data analysis sectorData)
            candidateSector
            (globalCandidateAActualKernelOperator period hPeriod configuration data
              analysis
              (globalCandidateAActualKernelChart period hPeriod configuration data
                analysis einsteinScale hTransverse family)
              (globalCandidateAActualKernelSameAction period hPeriod configuration
                data analysis einsteinScale hTransverse family)
              (globalCandidateACanonicalSixPhysicalExtension_of_chartBound
                period hPeriod configuration data analysis einsteinScale
                hTransverse family chartBound) vector) =
          (preferredCandidateAFiveSectorHilbertCoordinates period hPeriod input).
            sectorProjector sector
            (globalCandidateAActualKernelOperator period hPeriod configuration data
              analysis
              (globalCandidateAActualKernelChart period hPeriod configuration data
                analysis einsteinScale hTransverse family)
              (globalCandidateAActualKernelSameAction period hPeriod configuration
                data analysis einsteinScale hTransverse family)
              (globalCandidateACanonicalSixPhysicalExtension_of_chartBound
                period hPeriod configuration data analysis einsteinScale
                hTransverse family chartBound) vector) := by
      simpa [preferredCandidateAFiveSectorHilbertCoordinates, candidateSector,
        sectorData] using hProjectionOperator'
    rw [input.familyIndex.baseFamily.actual_zero]
    rw [← hProjection', ← hProjectionOperator'']
    exact hCommute

/-- The five blocks extracted from the actual basepoint Hessian. -/
def preferredCandidateABasepointMetricBlock
    (input : GlobalHessianPreferredFiveSectorNamedKernelFamilyClosure4D
      period hPeriod configuration data analysis einsteinScale hTransverse family
        chartBound Metric Abelian Matter Longitudinal Boundary ZeroMode fold Index) :=
  (preferredCandidateABasepointCommutingOperator period hPeriod input).metricBlock

/-- Abelian block of the same basepoint Hessian. -/
def preferredCandidateABasepointAbelianBlock
    (input : GlobalHessianPreferredFiveSectorNamedKernelFamilyClosure4D
      period hPeriod configuration data analysis einsteinScale hTransverse family
        chartBound Metric Abelian Matter Longitudinal Boundary ZeroMode fold Index) :=
  (preferredCandidateABasepointCommutingOperator period hPeriod input).abelianBlock

/-- Primitive SpinC matter block of the same basepoint Hessian. -/
def preferredCandidateABasepointMatterBlock
    (input : GlobalHessianPreferredFiveSectorNamedKernelFamilyClosure4D
      period hPeriod configuration data analysis einsteinScale hTransverse family
        chartBound Metric Abelian Matter Longitudinal Boundary ZeroMode fold Index) :=
  (preferredCandidateABasepointCommutingOperator period hPeriod input).matterBlock

/-- Longitudinal/LL block of the same basepoint Hessian. -/
def preferredCandidateABasepointLongitudinalBlock
    (input : GlobalHessianPreferredFiveSectorNamedKernelFamilyClosure4D
      period hPeriod configuration data analysis einsteinScale hTransverse family
        chartBound Metric Abelian Matter Longitudinal Boundary ZeroMode fold Index) :=
  (preferredCandidateABasepointCommutingOperator period hPeriod input).longitudinalBlock

/-- Boundary/finite-BV block of the same basepoint Hessian. -/
def preferredCandidateABasepointBoundaryBlock
    (input : GlobalHessianPreferredFiveSectorNamedKernelFamilyClosure4D
      period hPeriod configuration data analysis einsteinScale hTransverse family
        chartBound Metric Abelian Matter Longitudinal Boundary ZeroMode fold Index) :=
  (preferredCandidateABasepointCommutingOperator period hPeriod input).boundaryBlock

/-- Exact product-coordinate formula for the genuine Candidate-A basepoint
Hessian. -/
theorem preferredCandidateABasepoint_blockDiagonal
    (input : GlobalHessianPreferredFiveSectorNamedKernelFamilyClosure4D
      period hPeriod configuration data analysis einsteinScale hTransverse family
        chartBound Metric Abelian Matter Longitudinal Boundary ZeroMode fold Index)
    (x : FiveSectorProduct Metric Abelian Matter Longitudinal Boundary) :
    (preferredCandidateABasepointCommutingOperator period hPeriod input).
        conjugatedOperator x =
      fiveSectorMetricAxis
          (preferredCandidateABasepointMetricBlock period hPeriod input
            (fiveSectorMetricCoordinate x)) +
        fiveSectorAbelianAxis
          (preferredCandidateABasepointAbelianBlock period hPeriod input
            (fiveSectorAbelianCoordinate x)) +
        fiveSectorMatterAxis
          (preferredCandidateABasepointMatterBlock period hPeriod input
            (fiveSectorMatterCoordinate x)) +
        fiveSectorLongitudinalAxis
          (preferredCandidateABasepointLongitudinalBlock period hPeriod input
            (fiveSectorLongitudinalCoordinate x)) +
        fiveSectorBoundaryAxis
          (preferredCandidateABasepointBoundaryBlock period hPeriod input
            (fiveSectorBoundaryCoordinate x)) :=
  (preferredCandidateABasepointCommutingOperator period hPeriod input).
    conjugatedOperator_blockDiagonal x

/-- Public Candidate-A basepoint block-diagonalization checkpoint. -/
theorem global_hessian_preferred_five_sector_basepoint_block_diagonalization_gate
    (input : GlobalHessianPreferredFiveSectorNamedKernelFamilyClosure4D
      period hPeriod configuration data analysis einsteinScale hTransverse family
        chartBound Metric Abelian Matter Longitudinal Boundary ZeroMode fold Index) :
    ∀ x : FiveSectorProduct Metric Abelian Matter Longitudinal Boundary,
      (preferredCandidateABasepointCommutingOperator period hPeriod input).
          conjugatedOperator x =
        fiveSectorMetricAxis
            (preferredCandidateABasepointMetricBlock period hPeriod input
              (fiveSectorMetricCoordinate x)) +
          fiveSectorAbelianAxis
            (preferredCandidateABasepointAbelianBlock period hPeriod input
              (fiveSectorAbelianCoordinate x)) +
          fiveSectorMatterAxis
            (preferredCandidateABasepointMatterBlock period hPeriod input
              (fiveSectorMatterCoordinate x)) +
          fiveSectorLongitudinalAxis
            (preferredCandidateABasepointLongitudinalBlock period hPeriod input
              (fiveSectorLongitudinalCoordinate x)) +
          fiveSectorBoundaryAxis
            (preferredCandidateABasepointBoundaryBlock period hPeriod input
              (fiveSectorBoundaryCoordinate x)) :=
  preferredCandidateABasepoint_blockDiagonal period hPeriod input

end
end P0EFTJanusProgramPGlobalHessianPreferredFiveSectorBasepointBlockDiagonalization4D
end JanusFormal
