import JanusFormal.Branches.FundamentalGeometryPVariationalPrinciple.Gates.P0EFTJanusProgramPFullTensorAtlasConnection4D

namespace JanusFormal
namespace P0EFTJanusProgramPFullTensorAtlasParallel4D
set_option autoImplicit false
noncomputable section
end
end P0EFTJanusProgramPFullTensorAtlasParallel4D
end JanusFormal
