import JanusFormal.Branches.FundamentalGeometryPVariationalPrinciple.Gates.P0EFTJanusProgramPGlobalHessianPreferredFiveSectorH14D11KernelSchwarzSpectralReferenceAtlas4D
import JanusFormal.Branches.FundamentalGeometryPVariationalPrinciple.Gates.P0EFTJanusProgramPIntrinsicNuclearTraceBoundedComposition4D
import JanusFormal.Branches.FundamentalGeometryPVariationalPrinciple.Gates.P0EFTJanusProgramPRelativeNuclearMellinDifferenceFamily4D
import JanusFormal.Branches.FundamentalGeometryPVariationalPrinciple.Gates.P0EFTJanusProgramPOperatorNormDifferentiableUnitaryGreenConjugation4D

/-!
# Terminal H14--D11 kernel-Schwarz nuclear-Duhamel zeta facade

This is the strongest independent terminal facade of the current PR #60
implementation.  Building it imports the complete preferred Candidate-A route
from the H14 reduced Green operator to the physical five-sector spectral-cut
atlas.

The actual family is generated by the operator-norm differentiable D11 unitary
frame.  Every standalone reference family is generated from

* intrinsic nuclear heat/Duhamel operators;
* common rank-one simplex-slice expansions;
* spectral construction of the averaged Duhamel operator;
* automatic trace cyclicity and heat-semigroup collapse to `H' K_t`;
* common short/long rank-one expansions and coefficient integrals;
* differentiable rank-one counterterm series;
* short-time renormalized endpoint limits;
* long-time primitive identities with vanishing terminal term;
* pointwise Schwarz symmetry of the real Mellin heat kernel;
* compatibility of complex conjugation with its Bochner integral;
* analytic continuation of the zeta function and its reflected function on a
  common preconnected domain joining the Mellin half-plane to zero.

The chain derives, rather than assumes,

```text
Tr(D_a(t)) = integral_s Tr(D_a(t,s)) dμ(s),
Tr(D_a(t,s)) = Tr(H'_a K_a(t)),
integral_t Tr(D_a(t)) = Tr(D_region,a),
counterterm derivative = Tr(C'_a),
C'_a - D_short,a = G_a H'_a + B_a,
D_long,a = B_a,
FP'_a = Tr(G_a H'_a),
I_a(s) = conj (I_a(conj s)),
M_a(s) = conj (M_a(conj s)),
Im (zeta'_a(0)) = 0,
T_reference,a = -Tr(G_a H'_a),
T_relative,a = Tr(G_ref,a H'_ref,a).
```

The remaining irreducible reference-side content is concentrated in concrete
spectral and analytic estimates:

1. construct the genuine reference heat and Duhamel operators;
2. prove their intrinsic nuclearity and parameter differentiability;
3. construct and control the simplex, collapsed-time and counterterm rank-one
   systems;
4. prove the three required sum/integral exchanges;
5. prove the heat semigroup law and slice operator identifications;
6. prove short-time renormalized convergence and long-time terminal decay;
7. discharge conjugation through the Bochner Mellin integral;
8. prove analytic regularity of the reflected continuation on the chosen
   conjugation-compatible domain.

No global scalar trace, finite-part derivative, endpoint identity, zeta reality
or connection-coefficient equality remains as an input of this terminal
interface.
-/

namespace JanusFormal
namespace P0EFTJanusProgramPGlobalHessianPreferredFiveSectorH14D11KernelSchwarzNuclearDuhamelZetaTerminal4D

set_option autoImplicit false
noncomputable section

end
end P0EFTJanusProgramPGlobalHessianPreferredFiveSectorH14D11KernelSchwarzNuclearDuhamelZetaTerminal4D
end JanusFormal
