import JanusFormal.Branches.FundamentalGeometryPVariationalPrinciple.Gates.P0EFTJanusProgramPProductThroatReferenceHeatDuhamelOperatorGeneratedCanonicalSchwarzAssembly4D

/-!
# Product-throat generated reference atlas

One base chart and every local chart generate their Mellin-zeta family from
short-time counterterms, countable operator boundaries and canonical Schwarz
continuation data.
-/

namespace JanusFormal
namespace P0EFTJanusProgramPProductThroatReferenceHeatDuhamelOperatorGeneratedCanonicalSchwarzAtlas4D

set_option autoImplicit false
noncomputable section

open P0EFTJanusGlobalSeparatedDiracModel
open P0EFTJanusCircleDiracHeatTraceCancellation
open P0EFTJanusProgramPNuclearHeatDuhamelTraceVariation4D
open P0EFTJanusProgramPProductThroatReferenceHeatDuhamelOperatorGeneratedCanonicalSchwarzAssembly4D
open P0EFTJanusProgramPRelativeZetaDeterminantConnection4D

universe u v

variable {E : Type u}
  [NormedAddCommGroup E] [InnerProductSpace Real E] [CompleteSpace E]

/-- Base and local product-throat reference charts. -/
structure ProductThroatReferenceHeatDuhamelOperatorGeneratedCanonicalSchwarzAtlasData
    (CountertermIndex Chart : Type*) (fold : Fold) where
  baseProductData : ProductThroatSpectralData
  baseTwist : CircleTwist
  baseNuclear : NuclearHeatDuhamelTraceVariationData.{u, v} (E := E)
  base :
    ProductThroatReferenceHeatDuhamelOperatorGeneratedCanonicalSchwarzAssemblyData
      CountertermIndex baseProductData fold baseTwist baseNuclear
  localProductData : Chart → ProductThroatSpectralData
  localTwist : Chart → CircleTwist
  localNuclear : Chart → NuclearHeatDuhamelTraceVariationData.{u, v} (E := E)
  localAssembly : ∀ chart,
    ProductThroatReferenceHeatDuhamelOperatorGeneratedCanonicalSchwarzAssemblyData
      CountertermIndex (localProductData chart) fold (localTwist chart)
        (localNuclear chart)

namespace ProductThroatReferenceHeatDuhamelOperatorGeneratedCanonicalSchwarzAtlasData

/-- Generated base reference family. -/
def baseFamily
    {CountertermIndex Chart : Type*} {fold : Fold}
    (data :
      ProductThroatReferenceHeatDuhamelOperatorGeneratedCanonicalSchwarzAtlasData
        (E := E) CountertermIndex Chart fold) :=
  data.base.toRelativeHeatMellinZetaFamilyData

/-- Generated local reference families. -/
def localFamily
    {CountertermIndex Chart : Type*} {fold : Fold}
    (data :
      ProductThroatReferenceHeatDuhamelOperatorGeneratedCanonicalSchwarzAtlasData
        (E := E) CountertermIndex Chart fold)
    (chart : Chart) :=
  (data.localAssembly chart).toRelativeHeatMellinZetaFamilyData

/-- Atlas checkpoint: every reference connection coefficient is generated by
the corresponding intrinsic logarithmic trace. -/
theorem product_throat_reference_heat_duhamel_operator_generated_canonical_schwarz_atlas_gate
    {CountertermIndex Chart : Type*} {fold : Fold}
    (data :
      ProductThroatReferenceHeatDuhamelOperatorGeneratedCanonicalSchwarzAtlasData
        (E := E) CountertermIndex Chart fold) :
    (∀ parameter,
      relativeZetaConnectionCoefficient data.baseFamily.toZetaFamily parameter =
        -(data.base.logarithmicTrace parameter : Complex)) ∧
    (∀ chart parameter,
      relativeZetaConnectionCoefficient
          (data.localFamily chart).toZetaFamily parameter =
        -((data.localAssembly chart).logarithmicTrace parameter : Complex)) := by
  exact ⟨data.base.product_throat_reference_heat_duhamel_operator_generated_canonical_schwarz_gate.2,
    fun chart =>
      (data.localAssembly chart).product_throat_reference_heat_duhamel_operator_generated_canonical_schwarz_gate.2⟩

end ProductThroatReferenceHeatDuhamelOperatorGeneratedCanonicalSchwarzAtlasData

end
end P0EFTJanusProgramPProductThroatReferenceHeatDuhamelOperatorGeneratedCanonicalSchwarzAtlas4D
end JanusFormal
