import JanusFormal.Branches.FundamentalGeometryPVariationalPrinciple.Gates.P0EFTJanusMappingTorusCanonicalPhysicalScalarNormalRegularity4D

/-!
# Physical normal trace from a higher elliptic estimate

The natural normal-trace theorem is stated on a higher regularity space.  The
corresponding elliptic estimate is normally proved in the sum-of-squares form

`||u||_R² ≤ C (||u||_L2² + ||A u||_L2²)`.

The maximal graph uses the product sup norm.  Since each component is bounded by
the graph norm, the sum of squares is bounded by twice its square.  Therefore
the higher regularity estimate gives the graph bound with constant `sqrt (2 C)`.
Composing with the bounded normal trace supplies the complete first-sheet normal
trace estimate.
-/

namespace JanusFormal
namespace P0EFTJanusMappingTorusCanonicalPhysicalScalarNormalEllipticRegularity4D

set_option autoImplicit false
noncomputable section

open Set Topology
open P0EFTJanusMappingTorusSmoothFieldDescent4D
open P0EFTJanusMappingTorusCanonicalPhysicalScalarFirstSheetHilbertTrace4D
open P0EFTJanusMappingTorusCanonicalPhysicalScalarFirstSheetGreenCore4D
open P0EFTJanusMappingTorusCanonicalPhysicalScalarNormalRegularity4D
open P0EFTJanusMappingTorusScalarHilbertGreenCoreCompletion4D

universe r

variable (period : Real) (hPeriod : period ≠ 0)
variable {Regularity : Type r}
  [NormedAddCommGroup Regularity] [NormedSpace Real Regularity]
  [CompleteSpace Regularity]

private abbrev BoundaryL2 := CanonicalPhysicalScalarFirstSheetL2 period

namespace CanonicalPhysicalScalarFirstSheetGreenCoreData

/-- Standard higher elliptic regularity and normal trace data. -/
structure NormalEllipticRegularityData
    (green : CanonicalPhysicalScalarFirstSheetGreenCoreData
      period hPeriod massSquared) where
  smoothRegularity : SmoothQuotientField period hPeriod Real →ₗ[Real] Regularity
  normalTrace : Regularity →L[Real] BoundaryL2 period
  normal_agrees : ∀ field : SmoothQuotientField period hPeriod Real,
    normalTrace (smoothRegularity field) =
      smoothCanonicalPhysicalScalarFirstSheetNormalL2 period hPeriod field
  ellipticConstant : Real
  ellipticConstant_nonnegative : 0 ≤ ellipticConstant
  elliptic_bound_sq : ∀ field : SmoothQuotientField period hPeriod Real,
    ‖smoothRegularity field‖ ^ 2 ≤
      ellipticConstant *
        (‖green.core.inclusion field‖ ^ 2 +
          ‖green.core.operator field‖ ^ 2)

namespace NormalEllipticRegularityData

/-- Graph constant generated by the sum-of-squares estimate. -/
def graphRegularityConstant
    {green : CanonicalPhysicalScalarFirstSheetGreenCoreData
      period hPeriod massSquared}
    (regularity : green.NormalEllipticRegularityData
      period hPeriod (Regularity := Regularity)) : Real :=
  Real.sqrt (2 * regularity.ellipticConstant)

/-- Nonnegativity of the graph regularity constant. -/
theorem graphRegularityConstant_nonnegative
    {green : CanonicalPhysicalScalarFirstSheetGreenCoreData
      period hPeriod massSquared}
    (regularity : green.NormalEllipticRegularityData
      period hPeriod (Regularity := Regularity)) :
    0 ≤ regularity.graphRegularityConstant :=
  Real.sqrt_nonneg _

/-- Higher regularity is bounded by the maximal graph norm. -/
theorem regularity_bound_sq_graph
    (green : CanonicalPhysicalScalarFirstSheetGreenCoreData
      period hPeriod massSquared)
    (regularity : green.NormalEllipticRegularityData
      period hPeriod (Regularity := Regularity))
    (field : SmoothQuotientField period hPeriod Real) :
    ‖regularity.smoothRegularity field‖ ^ 2 ≤
      regularity.graphRegularityConstant ^ 2 *
        ‖canonicalScalarGreenCoreToGraph green.core field‖ ^ 2 := by
  have hInclusion :
      ‖green.core.inclusion field‖ ≤
        ‖canonicalScalarGreenCoreToGraph green.core field‖ := by
    change ‖green.core.inclusion field‖ ≤
      max ‖green.core.inclusion field‖ ‖green.core.operator field‖
    exact le_max_left _ _
  have hOperator :
      ‖green.core.operator field‖ ≤
        ‖canonicalScalarGreenCoreToGraph green.core field‖ := by
    change ‖green.core.operator field‖ ≤
      max ‖green.core.inclusion field‖ ‖green.core.operator field‖
    exact le_max_right _ _
  have hComponentSum :
      ‖green.core.inclusion field‖ ^ 2 +
          ‖green.core.operator field‖ ^ 2 ≤
        2 * ‖canonicalScalarGreenCoreToGraph green.core field‖ ^ 2 := by
    nlinarith [sq_nonneg ‖green.core.inclusion field‖,
      sq_nonneg ‖green.core.operator field‖,
      sq_nonneg ‖canonicalScalarGreenCoreToGraph green.core field‖]
  calc
    ‖regularity.smoothRegularity field‖ ^ 2 ≤
        regularity.ellipticConstant *
          (‖green.core.inclusion field‖ ^ 2 +
            ‖green.core.operator field‖ ^ 2) :=
      regularity.elliptic_bound_sq field
    _ ≤ regularity.ellipticConstant *
        (2 * ‖canonicalScalarGreenCoreToGraph green.core field‖ ^ 2) :=
      mul_le_mul_of_nonneg_left hComponentSum
        regularity.ellipticConstant_nonnegative
    _ = regularity.graphRegularityConstant ^ 2 *
        ‖canonicalScalarGreenCoreToGraph green.core field‖ ^ 2 := by
      unfold graphRegularityConstant
      rw [Real.sq_sqrt]
      · ring
      · exact mul_nonneg (by norm_num)
          regularity.ellipticConstant_nonnegative

/-- Conversion to the graph-normal regularity interface. -/
def toNormalRegularityData
    (green : CanonicalPhysicalScalarFirstSheetGreenCoreData
      period hPeriod massSquared)
    (regularity : green.NormalEllipticRegularityData
      period hPeriod (Regularity := Regularity)) :
    green.NormalRegularityData period hPeriod (Regularity := Regularity) where
  smoothRegularity := regularity.smoothRegularity
  normalTrace := regularity.normalTrace
  normal_agrees := regularity.normal_agrees
  constant := regularity.graphRegularityConstant
  nonnegative := regularity.graphRegularityConstant_nonnegative
  regularity_bound_sq := regularity.regularity_bound_sq_graph green

/-- Complete normal graph estimate. -/
def toNormalGraphEstimate
    (green : CanonicalPhysicalScalarFirstSheetGreenCoreData
      period hPeriod massSquared)
    (regularity : green.NormalEllipticRegularityData
      period hPeriod (Regularity := Regularity)) :
    green.NormalGraphEstimate period hPeriod :=
  (regularity.toNormalRegularityData green).toNormalGraphEstimate green

/-- Continuous higher-regularity extension to the completed maximal graph. -/
def completedRegularity
    (green : CanonicalPhysicalScalarFirstSheetGreenCoreData
      period hPeriod massSquared)
    (regularity : green.NormalEllipticRegularityData
      period hPeriod (Regularity := Regularity)) :
    CanonicalScalarGreenCoreGraphSpace green.core →L[Real] Regularity :=
  (regularity.toNormalRegularityData green).completedRegularity green

/-- The completed regularity trace agrees with the completed Cauchy normal
component. -/
theorem normalTrace_completedRegularity
    (green : CanonicalPhysicalScalarFirstSheetGreenCoreData
      period hPeriod massSquared)
    (regularity : green.NormalEllipticRegularityData
      period hPeriod (Regularity := Regularity))
    (traceBound : HasCanonicalScalarHilbertGreenCoreBoundaryGraphBound green.core)
    (field : CanonicalScalarGreenCoreGraphSpace green.core) :
    regularity.normalTrace (regularity.completedRegularity green field) =
      (regularity.toNormalRegularityData green).completedBoundaryNormalTrace
        green traceBound field :=
  (regularity.toNormalRegularityData green)
    |>.normalTrace_completedRegularity_eq_completedBoundaryNormalTrace
      green traceBound field

/-- Normal elliptic-regularity certificate. -/
theorem certificate
    (green : CanonicalPhysicalScalarFirstSheetGreenCoreData
      period hPeriod massSquared)
    (regularity : green.NormalEllipticRegularityData
      period hPeriod (Regularity := Regularity)) :
    (∀ field : SmoothQuotientField period hPeriod Real,
      ‖regularity.smoothRegularity field‖ ^ 2 ≤
        regularity.graphRegularityConstant ^ 2 *
          ‖canonicalScalarGreenCoreToGraph green.core field‖ ^ 2) ∧
      (∀ field : SmoothQuotientField period hPeriod Real,
        ‖smoothCanonicalPhysicalScalarFirstSheetNormalL2 period hPeriod field‖ ≤
          ‖regularity.normalTrace‖ * regularity.graphRegularityConstant *
            ‖canonicalScalarGreenCoreToGraph green.core field‖) :=
  ⟨regularity.regularity_bound_sq_graph green,
    (regularity.toNormalGraphEstimate green).bound⟩

end NormalEllipticRegularityData

end CanonicalPhysicalScalarFirstSheetGreenCoreData

end
end P0EFTJanusMappingTorusCanonicalPhysicalScalarNormalEllipticRegularity4D
end JanusFormal
