import JanusFormal.Branches.FundamentalGeometryPVariationalPrinciple.Gates.P0EFTJanusMappingTorusCanonicalPhysicalScalarIntrinsicWave4D
import JanusFormal.Branches.FundamentalGeometryPVariationalPrinciple.Gates.P0EFTJanusMappingTorusCanonicalPhysicalScalarEulerLocalToCutBulkBridge4D
import JanusFormal.Branches.FundamentalGeometryPVariationalPrinciple.Gates.P0EFTJanusMappingTorusCanonicalPhysicalScalarEulerNormalTangentialSplit4D

/-!
# Canonical local Green core from an intrinsic scalar wave

The overlap theorem is generated by an intrinsic global scalar-wave
representative.  The Green theorem is generated by the canonical product-local
divergence and its comparison with the positive half collar.

This file combines these two geometric reductions, so no explicit chart-overlap
compatibility and no quotient-space integral identity remain in the preferred
Green-core input.
-/

namespace JanusFormal
namespace P0EFTJanusMappingTorusCanonicalPhysicalScalarIntrinsicWaveLocalGreen4D

set_option autoImplicit false
noncomputable section

open scoped Manifold ContDiff ENNReal Interval
open MeasureTheory Set Topology Filter
open P0EFTJanusMappingTorusSmoothFieldDescent4D
open P0EFTJanusMappingTorusCanonicalPhysicalH1TraceBound4D
open P0EFTJanusMappingTorusCanonicalLatitudeCutoffCurrentLocalStokes4D
open P0EFTJanusMappingTorusCanonicalLatitudeCauchyJetProductCoarea4D
open P0EFTJanusMappingTorusCanonicalPhysicalScalarIntrinsicWave4D
open P0EFTJanusMappingTorusCanonicalPhysicalScalarEulerCanonicalProductLocalDivergence4D
open P0EFTJanusMappingTorusCanonicalPhysicalScalarEulerLocalToCutBulkBridge4D
open P0EFTJanusMappingTorusCanonicalPhysicalScalarEulerNormalTangentialSplit4D

variable (period : Real) (hPeriod : period ≠ 0)

/-- Intrinsic-wave Green data using the direct local-to-half-collar comparison. -/
structure CanonicalPhysicalScalarIntrinsicWaveLocalGreenData
    (massSquared : Real) where
  intrinsicWave : CanonicalPhysicalScalarIntrinsicWaveData period hPeriod
  localDivergence_eq_halfCollar :
    ∀ field test : SmoothScalarField period hPeriod,
      (∫ parameter,
        canonicalPhysicalScalarEulerProductLocalDivergenceDensity
          period hPeriod field test parameter
        ∂canonicalLatitudeCauchyJetProductMeasure period) =
      -2 *
        (∫ base, (∫ normal in (0 : Real)..1,
          cutoffCollarScalarCurrentDensitizedDivergence
            period hPeriod massSquared field test base normal)
          ∂canonicalLatitudeBaseMeasure period)

namespace CanonicalPhysicalScalarIntrinsicWaveLocalGreenData

/-- Conversion to the local-to-cut-bulk package. -/
def toLocalToCutBulkData
    (data : CanonicalPhysicalScalarIntrinsicWaveLocalGreenData
      period hPeriod massSquared) :
    CanonicalPhysicalScalarEulerLocalToCutBulkData
      period hPeriod massSquared where
  waveNaturality := data.intrinsicWave.toWaveAtlasNaturality
  localDivergence_eq_halfCollar := data.localDivergence_eq_halfCollar

/-- Canonical local Green package. -/
def toCanonicalLocalDivergenceData
    (data : CanonicalPhysicalScalarIntrinsicWaveLocalGreenData
      period hPeriod massSquared) :=
  data.toLocalToCutBulkData.toCanonicalLocalDivergenceData

/-- Correct dense physical Green core. -/
def greenCore
    (data : CanonicalPhysicalScalarIntrinsicWaveLocalGreenData
      period hPeriod massSquared) :=
  data.toCanonicalLocalDivergenceData.greenCore

/-- Intrinsic-wave local Green certificate. -/
theorem certificate
    (data : CanonicalPhysicalScalarIntrinsicWaveLocalGreenData
      period hPeriod massSquared) :
    P0EFTJanusMappingTorusCanonicalPhysicalScalarEulerAtlasNaturality4D.CanonicalPhysicalScalarWaveAtlasNaturality
        period hPeriod ∧
      (∀ field test,
        (∫ point,
          P0EFTJanusMappingTorusCanonicalPhysicalScalarEulerGreenL2Reduction4D.canonicalPhysicalScalarEulerSkewDensity
            period hPeriod massSquared field test point
          ∂P0EFTJanusMappingTorusCanonicalLorentzVolumeGluing4D.intrinsicCanonicalLorentzVolumeMeasure
            period hPeriod) =
        -2 * P0EFTJanusMappingTorusCutBulkCanonicalDivergenceMeasure4D.cutBulkCanonicalDivergenceMeasure
          period hPeriod massSquared field test Set.univ) :=
  ⟨data.intrinsicWave.toWaveAtlasNaturality,
    data.toLocalToCutBulkData.certificate.2⟩

end CanonicalPhysicalScalarIntrinsicWaveLocalGreenData

/-- Intrinsic-wave Green data with a normal/tangential divergence split. -/
structure CanonicalPhysicalScalarIntrinsicWaveNormalTangentialGreenData
    (massSquared : Real) where
  intrinsicWave : CanonicalPhysicalScalarIntrinsicWaveData period hPeriod
  normalDensity :
    SmoothScalarField period hPeriod →
      SmoothScalarField period hPeriod →
        CanonicalLatitudeCauchyJetProductParameter → Real
  tangentialDensity :
    SmoothScalarField period hPeriod →
      SmoothScalarField period hPeriod →
        CanonicalLatitudeCauchyJetProductParameter → Real
  normalDensity_integrable : ∀ field test,
    Integrable (normalDensity field test)
      (canonicalLatitudeCauchyJetProductMeasure period)
  tangentialDensity_integrable : ∀ field test,
    Integrable (tangentialDensity field test)
      (canonicalLatitudeCauchyJetProductMeasure period)
  localDivergence_eq_normal_add_tangential :
    ∀ field test parameter,
      canonicalPhysicalScalarEulerProductLocalDivergenceDensity
          period hPeriod field test parameter =
        normalDensity field test parameter +
          tangentialDensity field test parameter
  tangential_base_integral_zero :
    ∀ field test normal,
      (∫ base,
        tangentialDensity field test (base, normal)
        ∂canonicalLatitudeBaseMeasure period) = 0
  normal_integral_eq_halfCollar :
    ∀ field test,
      (∫ parameter,
        normalDensity field test parameter
        ∂canonicalLatitudeCauchyJetProductMeasure period) =
      -2 *
        (∫ base, (∫ normal in (0 : Real)..1,
          cutoffCollarScalarCurrentDensitizedDivergence
            period hPeriod massSquared field test base normal)
          ∂canonicalLatitudeBaseMeasure period)

namespace CanonicalPhysicalScalarIntrinsicWaveNormalTangentialGreenData

/-- Conversion to the normal/tangential split package. -/
def toNormalTangentialSplitData
    (data : CanonicalPhysicalScalarIntrinsicWaveNormalTangentialGreenData
      period hPeriod massSquared) :
    CanonicalPhysicalScalarEulerNormalTangentialSplitData
      period hPeriod massSquared where
  waveNaturality := data.intrinsicWave.toWaveAtlasNaturality
  normalDensity := data.normalDensity
  tangentialDensity := data.tangentialDensity
  normalDensity_integrable := data.normalDensity_integrable
  tangentialDensity_integrable := data.tangentialDensity_integrable
  localDivergence_eq_normal_add_tangential :=
    data.localDivergence_eq_normal_add_tangential
  tangential_base_integral_zero := data.tangential_base_integral_zero
  normal_integral_eq_halfCollar := data.normal_integral_eq_halfCollar

/-- Direct local Green package. -/
def toIntrinsicWaveLocalGreenData
    (data : CanonicalPhysicalScalarIntrinsicWaveNormalTangentialGreenData
      period hPeriod massSquared) :
    CanonicalPhysicalScalarIntrinsicWaveLocalGreenData
      period hPeriod massSquared where
  intrinsicWave := data.intrinsicWave
  localDivergence_eq_halfCollar :=
    data.toNormalTangentialSplitData.localDivergence_eq_halfCollar

/-- Correct dense physical Green core. -/
def greenCore
    (data : CanonicalPhysicalScalarIntrinsicWaveNormalTangentialGreenData
      period hPeriod massSquared) :=
  data.toIntrinsicWaveLocalGreenData.greenCore

/-- Intrinsic normal/tangential Green certificate. -/
theorem certificate
    (data : CanonicalPhysicalScalarIntrinsicWaveNormalTangentialGreenData
      period hPeriod massSquared) :
    (∀ field test,
      (∫ parameter,
        data.tangentialDensity field test parameter
        ∂canonicalLatitudeCauchyJetProductMeasure period) = 0) ∧
      (∀ field test,
        (∫ point,
          P0EFTJanusMappingTorusCanonicalPhysicalScalarEulerGreenL2Reduction4D.canonicalPhysicalScalarEulerSkewDensity
            period hPeriod massSquared field test point
          ∂P0EFTJanusMappingTorusCanonicalLorentzVolumeGluing4D.intrinsicCanonicalLorentzVolumeMeasure
            period hPeriod) =
        -2 * P0EFTJanusMappingTorusCutBulkCanonicalDivergenceMeasure4D.cutBulkCanonicalDivergenceMeasure
          period hPeriod massSquared field test Set.univ) :=
  ⟨data.toNormalTangentialSplitData.tangential_integral_eq_zero,
    data.toIntrinsicWaveLocalGreenData.certificate.2⟩

end CanonicalPhysicalScalarIntrinsicWaveNormalTangentialGreenData

end
end P0EFTJanusMappingTorusCanonicalPhysicalScalarIntrinsicWaveLocalGreen4D
end JanusFormal
