import JanusFormal.Branches.FundamentalGeometryPVariationalPrinciple.Gates.P0EFTJanusProgramPT12DiffeomorphismCommonL2Column4D
import JanusFormal.Branches.FundamentalGeometryPVariationalPrinciple.Gates.P0EFTJanusProgramPT12DiffeomorphismH11Core4D
import JanusFormal.Branches.FundamentalGeometryPVariationalPrinciple.Gates.P0EFTJanusProgramPT12DiffeomorphismGraphRieszBridge4D
import JanusFormal.Branches.FundamentalGeometryPVariationalPrinciple.Gates.P0EFTJanusProgramPT12DiffeomorphismH11Smooth4D
import JanusFormal.Branches.FundamentalGeometryPVariationalPrinciple.Gates.P0EFTJanusProgramPT12InjectiveSmoothColumn4D
import JanusFormal.Branches.FundamentalGeometryPVariationalPrinciple.Gates.P0EFTJanusProgramPT12DiffeomorphismH11MetricDependence4D
import JanusFormal.Branches.FundamentalGeometryPVariationalPrinciple.Gates.P0EFTJanusProgramPT12CandidateAAbelianMixedPhysical4D
import JanusFormal.Branches.FundamentalGeometryPVariationalPrinciple.Gates.P0EFTJanusProgramPT12JointQuotientDiffeomorphismSmoothPairing4D
import JanusFormal.Branches.FundamentalGeometryPVariationalPrinciple.Gates.P0EFTJanusProgramPT12DiffeomorphismMetricSmooth4D

/-! The full diffeomorphism H11 column depends only on the physical metric perturbation. -/
namespace JanusFormal
namespace P0EFTJanusProgramPT12DiffeomorphismAugmentedL2Core4D
set_option autoImplicit false

set_option maxHeartbeats 800000
set_option synthInstance.maxHeartbeats 600000
noncomputable section

open Set MeasureTheory
open scoped ENNReal lp Manifold ContDiff InnerProductSpace
open P0EFTJanusMappingTorusQuotient
open P0EFTJanusMappingTorusSmoothAtlasFrontier
open P0EFTJanusMappingTorusSmoothQuotientManifold
open P0EFTJanusMappingTorusGeneralLorentzTensor4D
open P0EFTJanusMappingTorusGeneralScalarFunctionalAction4D
open P0EFTJanusProgramPGlobalFieldSpace4D
open P0EFTJanusProgramPGlobalTypedNonminimalFieldSpace4D
open P0EFTJanusProgramPGlobalCovariantAction4D
open P0EFTJanusProgramPGlobalAnalysisDomain4D
open P0EFTJanusProgramPGlobalCandidateABulkGraphC2Chart4D
open P0EFTJanusProgramPGlobalLocalVariationalChart4D
open P0EFTJanusProgramPGlobalAbelianBRSTOffShellGraphC2Chart4D
open P0EFTJanusProgramPGlobalCandidateAAbelianGaugeFixedAction4D
open P0EFTJanusProgramPGlobalCandidateAAbelianExtendedBulkGraphC2Chart4D
open P0EFTJanusProgramPGlobalCandidateAAbelianExtendedBulkL2Riesz4D
open P0EFTJanusProgramPGlobalCandidateADiagonalDiffeomorphismBRSTOffShellGraphC2Chart4D
open P0EFTJanusProgramPGlobalCandidateADiagonalExtendedBulkGraphC2Chart4D
open P0EFTJanusProgramPGlobalCandidateADiagonalCovariantHessianResidualBridge4D
open P0EFTJanusProgramPGlobalCandidateADiagonalExtendedBulkL2Riesz4D
open P0EFTJanusProgramPGlobalMetricTangentIntrinsicEmbedding4D
open P0EFTJanusProgramPGlobalCandidateACanonicalStablePerturbation4D
open P0EFTJanusProgramPGlobalCandidateACommonAugmentedAnalyticDomain4D
open P0EFTJanusProgramPGlobalCandidateAMatterLLSameActionClosure4D
open P0EFTJanusProgramPGlobalCandidateAMinimalPhysicalGraphProjections4D
open P0EFTJanusProgramPGlobalFullLLGraphRiesz4D
open P0EFTJanusProgramPPrimitiveSpinCMatterGraphSameActionHessian4D
open P0EFTJanusProgramPRegularGeneralMetricC2PairedLorentzChartCenter4D
open P0EFTJanusProgramPRegularGeneralMetricC2PairedMinimalPhysicalLocalActionFamilyCenter4D
open P0EFTJanusProgramPRegularGeneralMetricC2PairedMinimalPhysicalAdmissibleLocalActionFamily4D
open P0EFTJanusProgramPRegularGeneralMetricC2PairedMinimalPhysicalLLC0FirstJetProjection4D
open P0EFTJanusProgramPRegularGeneralMetricC2PairedMinimalPhysicalStrongComponentPDEBlockPairing4D
open P0EFTJanusProgramPRegularGeneralMetricC2PairedMinimalPhysicalStrongLLWeakFirstVariation4D
open P0EFTJanusProgramPRegularGeneralMetricC2PairedMinimalPhysicalStrongLocalEuler4D
open P0EFTJanusProgramPRegularGeneralMetricC2PairedMinimalPhysicalStrongSpinCTotalEuler4D
open P0EFTJanusProgramPT12GaugeFixedLLFriedrichsPhysicalRieszTransport4D
open P0EFTJanusProgramPT12LLCanonicalH1ClosedDomain4D
open P0EFTJanusProgramPT12LLCanonicalH1L2Bridge4D
open P0EFTJanusProgramPT12StrongLLPhysicalMixedHessianZero4D
open P0EFTJanusProgramPT12StrongMatterLLSameActionBridge4D
open P0EFTJanusProgramPT12StrongPhysicalSecondJet4D
open P0EFTJanusProgramPT12StrongToH11PhysicalSecondJet4D
open P0EFTJanusMappingTorusCanonicalDivergenceFreeLLFrame4D

attribute [local instance]
  GlobalCandidateALocalVariationalChart.normedAddCommGroup
  GlobalCandidateALocalVariationalChart.normedSpace
  P0EFTJanusProgramPGlobalCandidateADiagonalExtendedBulkL2Riesz4D.diagonalL2DiffeomorphismNormedAddCommGroup
  P0EFTJanusProgramPGlobalCandidateADiagonalExtendedBulkL2Riesz4D.diagonalL2DiffeomorphismInnerProductSpace
  P0EFTJanusProgramPGlobalCandidateADiagonalExtendedBulkL2Riesz4D.diagonalL2AbelianInnerProductSpace
  P0EFTJanusProgramPGlobalCandidateADiagonalExtendedBulkL2Riesz4D.diagonalL2MatterInnerProductSpace
  P0EFTJanusProgramPGlobalCandidateADiagonalExtendedBulkL2Riesz4D.diagonalL2MatterCompleteSpace
  P0EFTJanusProgramPGlobalCandidateADiagonalExtendedBulkL2Riesz4D.diagonalL2LLInnerProductSpace
  P0EFTJanusProgramPGlobalCandidateADiagonalExtendedBulkL2Riesz4D.diagonalL2LLCompleteSpace
  P0EFTJanusProgramPGlobalCandidateADiagonalExtendedBulkL2Riesz4D.diagonalL2ExtendedBulkNormedAddCommGroup
  P0EFTJanusProgramPGlobalCandidateADiagonalExtendedBulkL2Riesz4D.diagonalL2ExtendedBulkInnerProductSpace
  P0EFTJanusProgramPGlobalCandidateADiagonalExtendedBulkL2Riesz4D.diagonalL2ExtendedBulkCompleteSpace
  P0EFTJanusProgramPPrimitiveSpinCMatterGraphSameActionHessian4D.programPPrimitiveSpinCMatterHilbertRealInnerProductSpace

variable (period : Real) (hPeriod : period ≠ 0)

private abbrev EffectiveQuotient :=
  MappingTorus (reflectedSphereData period hPeriod)

local instance : ChartedSpace CoverModel (EffectiveQuotient period hPeriod) :=
  reflectedSphereQuotientChartedSpace period hPeriod

local instance : IsManifold coverModelWithCorners ω
    (EffectiveQuotient period hPeriod) :=
  reflectedSphereQuotient_isManifold period hPeriod

local instance : MeasurableSpace (EffectiveQuotient period hPeriod) := borel _

local instance : BorelSpace (EffectiveQuotient period hPeriod) where
  measurable_eq := rfl

section

variable {couplings : GlobalCandidateAActionCouplings}
variable {NonNullFace NullFace : Type*}
variable [Fintype NonNullFace] [Fintype NullFace]
variable {measure : Measure (EffectiveQuotient period hPeriod)}
variable (configuration : GlobalGaugeFixedFieldConfiguration period hPeriod)
variable (data : GlobalCandidateAActionData period hPeriod
  configuration.physical couplings NonNullFace NullFace)
variable (analysis : GlobalAnalysisData period hPeriod configuration.physical)

set_option backward.isDefEq.respectTransparency false
open P0EFTJanusProgramPT12StrongCompletedMatterLLPhysicalRieszZero4D
open P0EFTJanusProgramPT12LLQuotientFriedrichsRealization4D
open P0EFTJanusProgramPT12LLQuotientFriedrichsSmoothPairing4D
open P0EFTJanusProgramPT12LLFullJacobiHilbertQuotient4D

open P0EFTJanusProgramPT12StrongFullLLQuotientColumn4D
open P0EFTJanusProgramPGlobalLLAuxMeasureGraphRiesz4D
open P0EFTJanusProgramPT12LLFullJacobiZeroFluxKernel4D
open P0EFTJanusProgramPT12DiagonalGhostHilbertQuotient4D
open P0EFTJanusProgramPCandidateADiagonalDiffeomorphismKineticAdjointBridge4D

open P0EFTJanusProgramPT12StrongGhostLLNullSpace4D
open P0EFTJanusProgramPT12ClosedNullQuotient4D
open P0EFTJanusProgramPGlobalCandidateAMinimalPhysicalLocalHessianBridge4D

open P0EFTJanusProgramPT12StrongGhostLLHilbertQuotient4D
open P0EFTJanusProgramPT12JointQuotientAbelianFactor4D
open P0EFTJanusProgramPT12SignedBRSTAugmentedPairing4D
open P0EFTJanusProgramPT12AbelianSignedBRSTRealization4D
open P0EFTJanusProgramPT12DiffeomorphismSignedBRSTRealization4D
variable [IsFiniteMeasure measure]
variable (realization : ProgramPPrimitiveSpinCMatterSmoothGraphRealization4D
  period hPeriod couplings.matterMassSquared)
variable (plusBase minusBase : RegularGeneralLorentzMetric period hPeriod)
variable (hBase : RegularGeneralMetricC2PairedLorentzChartBaseCompatible
  period hPeriod plusBase minusBase)
variable (hCenter : RegularGeneralMetricC2PairedMinimalPhysicalCenterCompatible
  period hPeriod configuration.physical plusBase minusBase hBase)

variable (physical : GlobalCandidateASevenPhysicalCommonDomainExtension4D
  period hPeriod configuration data analysis
  (strongChart (measure := measure) period hPeriod configuration data analysis realization plusBase minusBase hBase)
  (strongBridge (measure := measure) period hPeriod configuration data analysis realization plusBase minusBase hBase hCenter))

open P0EFTJanusProgramPT12JointQuotientAbelianColumn4D
open P0EFTJanusProgramPGlobalEulerLagrangeMinimalPhysicalHilbertAugmentationObstruction4D

open P0EFTJanusProgramPT12JointQuotientAbelianSmoothPairing4D
open P0EFTJanusProgramPT12AbelianLorenzGraphShear4D
open P0EFTJanusProgramPT12AbelianBRSTNegativePhysicalColumn4D
open P0EFTJanusProgramPT12JointQuotientPhysicalRiesz4D

open P0EFTJanusProgramPT12AbelianGhostSmoothRotation4D
open P0EFTJanusProgramPGlobalPairedAbelianBRSTGaugeFermion4D
open P0EFTJanusProgramPGlobalGaugeTangentIntrinsicEmbedding4D

open P0EFTJanusProgramPT12CandidateAAbelianMixedOperator4D
open P0EFTJanusProgramPT12CandidateAAbelianMixedPotential4D
open P0EFTJanusProgramPT12AbelianPotentialGraphInclusion4D
open P0EFTJanusProgramPT12AbelianGhostRotationPhysical4D

open P0EFTJanusProgramPT12JointQuotientDiffeomorphismFactor4D
open P0EFTJanusProgramPT12JointQuotientDiffeomorphismSmoothPairing4D
open P0EFTJanusProgramPT12DiffeomorphismMetricSmooth4D

open P0EFTJanusProgramPT12DiffeomorphismH11MetricDependence4D

open P0EFTJanusProgramPT12DiffeomorphismH11Smooth4D
open P0EFTJanusProgramPT12DiffeomorphismL2Core4D
open P0EFTJanusProgramPT12InjectiveSmoothColumn4D

local instance physicalSourceInnerProductSpace : InnerProductSpace Real (DiffeomorphismL2 period hPeriod (globalCandidateAMetricBySector period hPeriod data .plus)) :=
  Submodule.innerProductSpace (𝕜 := Real) (E := DiffeomorphismL2Ambient period hPeriod)
    (diffeomorphismL2Space period hPeriod (globalCandidateAMetricBySector period hPeriod data .plus))

open P0EFTJanusProgramPT12DiffeomorphismGraphToL24D
open P0EFTJanusProgramPT12DiffeomorphismGraphRieszBridge4D
open P0EFTJanusProgramPT12HessianSmoothRiesz4D
open P0EFTJanusProgramPT12HessianL2OperatorCore4D

open P0EFTJanusProgramPT12DiffeomorphismCommonL2Column4D
open P0EFTJanusProgramPT12DiffeomorphismH11Core4D
open P0EFTJanusProgramPT12DiffeomorphismHessianExtension4D
open P0EFTJanusProgramPT12DiffeomorphismHessianRealization4D
open P0EFTJanusProgramPT12JointQuotientDiffeomorphismColumn4D

variable (reference : RegularGeneralLorentzMetric period hPeriod)

attribute [local irreducible] hessianSmoothRieszLinearMap diffeomorphismH11Smooth
  diffeomorphismCommonBRSTColumn

/-- All BRST and H11 outputs in the original common target. -/
def diffeomorphismAugmentedSmoothColumn : GlobalCandidateADiagonalDiffeomorphismBRSTState period hPeriod →ₗ[Real] CommonAugmentedHilbert period hPeriod configuration data analysis :=
  (diffeomorphismCommonBRSTColumn period hPeriod configuration data analysis).toLinearMap.comp
    (hessianSmoothRieszLinearMap period hPeriod reference (globalCandidateAMetricBySector period hPeriod data) couplings) + (diffeomorphismH11Smooth period hPeriod configuration data analysis realization plusBase minusBase hBase hCenter physical)

def diffeomorphismAugmentedL2Core : DiffeomorphismL2 period hPeriod (globalCandidateAMetricBySector period hPeriod data .plus) →ₗ.[Real] CommonAugmentedHilbert period hPeriod configuration data analysis :=
  injectiveSmoothColumn (D := GlobalCandidateADiagonalDiffeomorphismBRSTState period hPeriod) (E := DiffeomorphismL2 period hPeriod (globalCandidateAMetricBySector period hPeriod data .plus)) (F := CommonAugmentedHilbert period hPeriod configuration data analysis) (diffeomorphismL2Smooth period hPeriod (globalCandidateAMetricBySector period hPeriod data .plus)) (diffeomorphismAugmentedSmoothColumn period hPeriod configuration data analysis realization plusBase minusBase hBase hCenter physical reference) (diffeomorphismL2Smooth_injective period hPeriod (globalCandidateAMetricBySector period hPeriod data .plus))

def diffeomorphismAugmentedSmoothDomain (field : GlobalCandidateADiagonalDiffeomorphismBRSTState period hPeriod) :
    (diffeomorphismAugmentedL2Core period hPeriod configuration data analysis realization plusBase minusBase hBase hCenter physical reference).domain := ⟨(diffeomorphismL2Smooth period hPeriod (globalCandidateAMetricBySector period hPeriod data .plus)) field, ⟨field, rfl⟩⟩

theorem diffeomorphismAugmentedL2Core_denseDomain :
    Dense ((diffeomorphismAugmentedL2Core period hPeriod configuration data analysis realization plusBase minusBase hBase hCenter physical reference).domain : Set (DiffeomorphismL2 period hPeriod (globalCandidateAMetricBySector period hPeriod data .plus))) :=
  injectiveSmoothColumn_denseDomain (D := GlobalCandidateADiagonalDiffeomorphismBRSTState period hPeriod) (E := DiffeomorphismL2 period hPeriod (globalCandidateAMetricBySector period hPeriod data .plus)) (F := CommonAugmentedHilbert period hPeriod configuration data analysis) (diffeomorphismL2Smooth period hPeriod (globalCandidateAMetricBySector period hPeriod data .plus)) (diffeomorphismAugmentedSmoothColumn period hPeriod configuration data analysis realization plusBase minusBase hBase hCenter physical reference) (diffeomorphismL2Smooth_injective period hPeriod (globalCandidateAMetricBySector period hPeriod data .plus))
    (diffeomorphismL2Smooth_denseRange period hPeriod (globalCandidateAMetricBySector period hPeriod data .plus))

theorem diffeomorphismAugmentedL2Core_smooth (field : GlobalCandidateADiagonalDiffeomorphismBRSTState period hPeriod) :
    diffeomorphismAugmentedL2Core period hPeriod configuration data analysis realization plusBase minusBase hBase hCenter physical reference (diffeomorphismAugmentedSmoothDomain period hPeriod configuration data analysis realization plusBase minusBase hBase hCenter physical reference field) =
      diffeomorphismAugmentedSmoothColumn period hPeriod configuration data analysis realization plusBase minusBase hBase hCenter physical reference field :=
  injectiveSmoothColumn_smooth (D := GlobalCandidateADiagonalDiffeomorphismBRSTState period hPeriod) (E := DiffeomorphismL2 period hPeriod (globalCandidateAMetricBySector period hPeriod data .plus)) (F := CommonAugmentedHilbert period hPeriod configuration data analysis) (diffeomorphismL2Smooth period hPeriod (globalCandidateAMetricBySector period hPeriod data .plus)) (diffeomorphismAugmentedSmoothColumn period hPeriod configuration data analysis realization plusBase minusBase hBase hCenter physical reference) (diffeomorphismL2Smooth_injective period hPeriod (globalCandidateAMetricBySector period hPeriod data .plus)) field

theorem diffeomorphismAugmentedL2Core_realized_column (field : GlobalCandidateADiagonalDiffeomorphismBRSTState period hPeriod) :
    diffeomorphismAugmentedL2Core period hPeriod configuration data analysis realization plusBase minusBase hBase hCenter physical reference (diffeomorphismAugmentedSmoothDomain period hPeriod configuration data analysis realization plusBase minusBase hBase hCenter physical reference field) =
    diffeomorphismCommonBRSTColumn period hPeriod configuration data analysis
      (diffeomorphismHessianRealization period hPeriod reference (globalCandidateAMetricBySector period hPeriod data) couplings (diffeomorphismHessianRealizationSmoothDomain period hPeriod reference (globalCandidateAMetricBySector period hPeriod data) couplings field)) +
    diffeomorphismH11Core period hPeriod configuration data analysis realization plusBase minusBase hBase hCenter physical (diffeomorphismH11SmoothDomain period hPeriod configuration data analysis realization plusBase minusBase hBase hCenter physical field) := by
  rw [diffeomorphismAugmentedL2Core_smooth, diffeomorphismHessianRealization_smooth,
    diffeomorphismH11Core_smooth]
  unfold diffeomorphismAugmentedSmoothColumn hessianSmoothRieszLinearMap
  rfl

theorem diffeomorphismAugmentedL2Core_actual_column (field : GlobalCandidateADiagonalDiffeomorphismBRSTState period hPeriod) :
    diffeomorphismAugmentedL2Core period hPeriod configuration data analysis realization plusBase minusBase hBase hCenter physical reference (diffeomorphismAugmentedSmoothDomain period hPeriod configuration data analysis realization plusBase minusBase hBase hCenter physical reference field) =
    strongAugmentedRiesz (measure := measure) period hPeriod configuration data analysis realization plusBase minusBase hBase hCenter physical
      (diffeomorphismPhysicalSmoothLift period hPeriod configuration data analysis field) := by
  rw [diffeomorphismAugmentedL2Core_realized_column, diffeomorphismHessianRealization_smooth,
    diffeomorphismH11Core_smooth, diffeomorphismCommonBRSTColumn_smooth]
  unfold diffeomorphismH11Smooth diffeomorphismPhysicalSmoothLift
  exact (actualDiffeomorphism_augmented_column period hPeriod configuration data analysis realization plusBase minusBase hBase hCenter physical
    (globalCandidateADiagonalDiffeomorphismOffShellSmoothEmbedding period hPeriod
      (globalCandidateAMetricBySector period hPeriod data) field)).symm

theorem diffeomorphismAugmentedL2Core_pairing (field : GlobalCandidateADiagonalDiffeomorphismBRSTState period hPeriod) (test : CommonAugmentedHilbert period hPeriod configuration data analysis) :
    inner Real (diffeomorphismAugmentedL2Core period hPeriod configuration data analysis realization plusBase minusBase hBase hCenter physical reference
      (diffeomorphismAugmentedSmoothDomain period hPeriod configuration data analysis realization plusBase minusBase hBase hCenter physical reference field)) test =
    inner Real (diffeomorphismHessianRealization period hPeriod reference (globalCandidateAMetricBySector period hPeriod data) couplings (diffeomorphismHessianRealizationSmoothDomain period hPeriod reference (globalCandidateAMetricBySector period hPeriod data) couplings field))
      (diffeomorphismCommonL2Readout period hPeriod configuration data analysis test) +
    physical.form (diffeomorphismPhysicalSmoothLift period hPeriod configuration data analysis field) test := by
  rw [diffeomorphismAugmentedL2Core_realized_column, inner_add_left,
    diffeomorphismCommonBRSTColumn_pairing, diffeomorphismH11Core_pairing]

end
end
end P0EFTJanusProgramPT12DiffeomorphismAugmentedL2Core4D
end JanusFormal
