import JanusFormal.Branches.FundamentalGeometryPVariationalPrinciple.Gates.P0EFTJanusMappingTorusSpatialConformalMetricJet4D

/-!
# Four-dimensional spatial conformal curvature algebra

This gate isolates the finite-index quadratic contraction of the standard
conformal Christoffel correction.
-/

namespace JanusFormal
namespace P0EFTJanusMappingTorusSpatialConformalCurvatureAlgebra4D

set_option autoImplicit false
set_option maxHeartbeats 4000000

noncomputable section

open scoped BigOperators Matrix

abbrev Index4 :=
  P0EFTJanusMetricCoupledScalarMatterJetVariation.Index4

abbrev Vector4 :=
  P0EFTJanusMetricCoupledScalarMatterJetVariation.Vector4

abbrev Matrix4 :=
  P0EFTJanusMetricCoupledScalarMatterJetVariation.Matrix4

/-- Algebraic normal form
`A (delta^u_j p_i + delta^u_i p_j - g_ij p^u)`. -/
def conformalConnectionCorrection
    (factor : Real) (metric : Matrix4)
    (gradient raisedGradient : Vector4)
    (upper first second : Index4) : Real :=
  factor *
    ((if upper = second then gradient first else 0) +
      (if upper = first then gradient second else 0) -
      metric first second * raisedGradient upper)

/-- In dimension four, the quadratic Ricci correction generated by the
conformal connection normal form has the standard rank-one/traced form. -/
theorem conformalConnectionCorrection_quadraticRicci
    (factor : Real) (metric : Matrix4)
    (gradient raisedGradient : Vector4)
    (hMetricSymmetric : metric.transpose = metric)
    (hLowerRaised : ∀ first : Index4,
      (∑ upper : Index4, metric first upper * raisedGradient upper) =
        gradient first)
    (first second : Index4) :
    (∑ contracted : Index4,
      ((∑ auxiliary : Index4,
          conformalConnectionCorrection factor metric gradient raisedGradient
              contracted contracted auxiliary *
            conformalConnectionCorrection factor metric gradient raisedGradient
              auxiliary second first) -
        ∑ auxiliary : Index4,
          conformalConnectionCorrection factor metric gradient raisedGradient
              contracted second auxiliary *
            conformalConnectionCorrection factor metric gradient raisedGradient
              auxiliary contracted first)) =
      2 * factor ^ 2 *
        (gradient first * gradient second -
          metric first second *
            ∑ index : Index4, gradient index * raisedGradient index) := by
  classical
  have hSymmetric (left right : Index4) :
      metric left right = metric right left := by
    have hEntry := congrArg (fun current : Matrix4 => current right left)
      hMetricSymmetric
    simpa [Matrix.transpose_apply] using hEntry
  have hLower0 := hLowerRaised (0 : Index4)
  have hLower1 := hLowerRaised (1 : Index4)
  have hLower2 := hLowerRaised (2 : Index4)
  have hLower3 := hLowerRaised (3 : Index4)
  simp only [Fin.sum_univ_four] at hLower0 hLower1 hLower2 hLower3
  have h10 : metric 1 0 = metric 0 1 := hSymmetric 1 0
  have h20 : metric 2 0 = metric 0 2 := hSymmetric 2 0
  have h30 : metric 3 0 = metric 0 3 := hSymmetric 3 0
  have h21 : metric 2 1 = metric 1 2 := hSymmetric 2 1
  have h31 : metric 3 1 = metric 1 3 := hSymmetric 3 1
  have h32 : metric 3 2 = metric 2 3 := hSymmetric 3 2
  fin_cases first <;> fin_cases second <;>
    simp only [conformalConnectionCorrection, Fin.sum_univ_four] <;>
    simp <;>
    simp_rw [← hLower0, ← hLower1, ← hLower2, ← hLower3] <;>
    simp_rw [h10, h20, h30, h21, h31, h32] <;>
    ring

end

end P0EFTJanusMappingTorusSpatialConformalCurvatureAlgebra4D
end JanusFormal
