import JanusFormal.Branches.FundamentalGeometryPVariationalPrinciple.Gates.P0EFTJanusMappingTorusCanonicalPhysicalScalarCanonicalResolventAdjointClosure4D
import JanusFormal.Branches.FundamentalGeometryPVariationalPrinciple.Gates.P0EFTJanusMappingTorusCanonicalPhysicalScalarCanonicalResolventReducedVariational4D
import JanusFormal.Branches.FundamentalGeometryPVariationalPrinciple.Gates.P0EFTJanusMappingTorusCanonicalPhysicalScalarCanonicalResolventReducedGaussian4D

/-!
# Adjoint-free final canonical physical scalar Program P endpoint

This is the preferred full endpoint.

Its input contains only:

* the reduced completed physical PDE boundary package;
* one closed Lagrangian boundary condition;
* one positive-square decomposition of a real shifted form;
* one finite-rank approximation scheme for physical Rellich compactness.

The real bounded resolvent generated by the positive decomposition proves
self-adjointness and also reconstructs every former adjoint regularity package.
The endpoint then supplies compact spectral theory, the unique variational
source solution and the nonnegative Gaussian response.
-/

namespace JanusFormal
namespace P0EFTJanusMappingTorusCanonicalPhysicalScalarCanonicalResolventProgramPClosure4D

set_option autoImplicit false
noncomputable section

open Set Topology MeasureTheory
open P0EFTJanusMappingTorusCanonicalPhysicalScalarCanonicalResolventReducedAnalyticClosure4D
open P0EFTJanusMappingTorusCanonicalPhysicalScalarCanonicalResolventAdjointClosure4D
open P0EFTJanusMappingTorusCanonicalPhysicalScalarCanonicalResolventReducedVariational4D
open P0EFTJanusMappingTorusCanonicalPhysicalScalarCanonicalResolventReducedGaussian4D
open P0EFTJanusMappingTorusScalarHilbertGreenCoreCompletion4D

universe r

variable (period : Real) (hPeriod : period ≠ 0)
variable {Regularity : Type r}
  [NormedAddCommGroup Regularity] [NormedSpace Real Regularity]
  [CompleteSpace Regularity]

private abbrev BulkL2 :=
  P0EFTJanusMappingTorusCanonicalPhysicalBulkL2H1Bridge4D.CanonicalPhysicalBulkL2
    period hPeriod

/-- Stable abbreviation for the preferred final physical scalar input. -/
abbrev CanonicalPhysicalScalarProgramPResolventFinalData
    (massSquared : Real) :=
  CanonicalPhysicalScalarCanonicalResolventReducedAnalyticData
    period hPeriod massSquared (Regularity := Regularity)

namespace CanonicalPhysicalScalarCanonicalResolventReducedAnalyticData

/-- Combined boundary, self-adjoint, spectral, variational and Gaussian
certificate. -/
theorem finalProgramP_certificate
    (analytic : CanonicalPhysicalScalarProgramPResolventFinalData
      period hPeriod (Regularity := Regularity) massSquared)
    (source : BulkL2 period hPeriod) :
    Function.Surjective
        (canonicalScalarGreenCoreCompletedBoundaryTrace
          analytic.boundary.geometric.greenCore.core
          (analytic.boundary.completedInputs.traceBound
            analytic.boundary.geometric.greenCore)) ∧
      analytic.boundary.triple.actualAdjointDomain analytic.condition =
        analytic.boundary.triple.realizationDomain analytic.condition ∧
      analytic.boundary.triple.AdjointPairGraphRegularity analytic.condition ∧
      analytic.boundary.triple.lagrangianShiftedOperator
          analytic.condition analytic.referenceParameter
          (analytic.sourceSolution period hPeriod source) = source ∧
      analytic.boundary.triple.lagrangianSourceStationary
          analytic.condition analytic.referenceParameter source
          (analytic.sourceSolution period hPeriod source) ∧
      analytic.gaussianGeneratingFunctional period hPeriod source =
        -analytic.boundary.triple.lagrangianSourceAction
          analytic.condition analytic.referenceParameter source
          (analytic.sourceSolution period hPeriod source) ∧
      0 ≤ analytic.gaussianGeneratingFunctional period hPeriod source ∧
      IsCompactOperator
        (P0EFTJanusMappingTorusCanonicalPhysicalBulkL2H1Bridge4D.canonicalPhysicalScalarH1ToBulkL2
          period hPeriod) ∧
      (∀ spectralParameter : Real,
        spectralParameter ≠ analytic.referenceParameter →
          analytic.boundary.triple.LagrangianHasEigenvalue
              analytic.condition spectralParameter ∨
            analytic.boundary.triple.LagrangianResolventPoint
              analytic.condition spectralParameter) :=
  ⟨analytic.boundary.certificate.2.2.2.2.1,
    analytic.actualAdjointDomain_eq period hPeriod,
    analytic.adjointGraphRegularity period hPeriod,
    analytic.sourceSolution_equation period hPeriod source,
    analytic.sourceSolution_stationary period hPeriod source,
    analytic.gaussianGeneratingFunctional_eq_neg_onShell
      period hPeriod source,
    analytic.gaussianGeneratingFunctional_nonnegative
      period hPeriod source,
    analytic.rellich period hPeriod,
    analytic.fredholmAlternative period hPeriod⟩

/-- Unique global minimizer, Gaussian positivity, finite multiplicity and lower
spectral bound. -/
theorem finalProgramP_extended_certificate
    (analytic : CanonicalPhysicalScalarProgramPResolventFinalData
      period hPeriod (Regularity := Regularity) massSquared)
    (source : BulkL2 period hPeriod) :
    (∀ field : analytic.boundary.triple.lagrangianDomainSubmodule
        analytic.condition,
      analytic.boundary.triple.lagrangianSourceAction
          analytic.condition analytic.referenceParameter source
          (analytic.sourceSolution period hPeriod source) ≤
        analytic.boundary.triple.lagrangianSourceAction
          analytic.condition analytic.referenceParameter source field) ∧
      (∀ field : analytic.boundary.triple.lagrangianDomainSubmodule
          analytic.condition,
        analytic.boundary.triple.lagrangianSourceAction
            analytic.condition analytic.referenceParameter source field =
          analytic.boundary.triple.lagrangianSourceAction
            analytic.condition analytic.referenceParameter source
            (analytic.sourceSolution period hPeriod source) →
        field = analytic.sourceSolution period hPeriod source) ∧
      0 ≤ analytic.gaussianGeneratingFunctional period hPeriod source ∧
      (∀ eigenvalue : Real,
        eigenvalue ≠ analytic.referenceParameter →
          FiniteDimensional Real
            (analytic.boundary.triple.lagrangianOperatorEigenspace
              analytic.condition eigenvalue)) ∧
      (∀ eigenvalue : Real,
        analytic.boundary.triple.LagrangianHasEigenvalue
            analytic.condition eigenvalue →
          analytic.referenceParameter ≤ eigenvalue) :=
  ⟨(analytic.sourceSolution_unique_minimizer period hPeriod source).1,
    (analytic.sourceSolution_unique_minimizer period hPeriod source).2,
    analytic.gaussianGeneratingFunctional_nonnegative period hPeriod source,
    analytic.finiteDimensional_operatorEigenspace period hPeriod,
    analytic.eigenvalue_ge_referenceParameter period hPeriod⟩

end CanonicalPhysicalScalarCanonicalResolventReducedAnalyticData

/-- Marker theorem for the preferred adjoint-free Program P endpoint. -/
theorem canonicalPhysicalScalarCanonicalResolventProgramPClosure_available : True :=
  trivial

end
end P0EFTJanusMappingTorusCanonicalPhysicalScalarCanonicalResolventProgramPClosure4D
end JanusFormal
