import JanusFormal.Branches.FundamentalGeometryPVariationalPrinciple.Gates.P0EFTJanusProgramPFiveSectorHilbertProjectorCoordinates4D

/-!
# Block diagonalization from one commuting five-sector Hilbert decomposition

Let `C : E ≃ Metric × Abelian × Matter × LL × Boundary` be the unique physical
Hilbert coordinates and let `H : E →L E`.  If `H` commutes with every projector
generated by `C`, then `C H C⁻¹` is exactly block diagonal.

The five blocks below are not independent inputs: each is extracted from the
same operator by coordinate injection, application of `H`, and coordinate
projection.
-/

namespace JanusFormal
namespace P0EFTJanusProgramPFiveSectorOperatorBlockDiagonalization4D

set_option autoImplicit false
noncomputable section

open P0EFTJanusProgramPFiveSectorHilbertCoordinates4D
open P0EFTJanusProgramPFiveSectorHilbertProjectorCoordinates4D

variable
  {E Metric Abelian Matter Longitudinal Boundary : Type*}
  [NormedAddCommGroup E] [InnerProductSpace Real E]
  [NormedAddCommGroup Metric] [InnerProductSpace Real Metric]
  [NormedAddCommGroup Abelian] [InnerProductSpace Real Abelian]
  [NormedAddCommGroup Matter] [InnerProductSpace Real Matter]
  [NormedAddCommGroup Longitudinal] [InnerProductSpace Real Longitudinal]
  [NormedAddCommGroup Boundary] [InnerProductSpace Real Boundary]

local notation "ProductSpace" =>
  FiveSectorProduct Metric Abelian Matter Longitudinal Boundary

/-- One bounded operator together with the one physical coordinate system and
exact commutation with its five generated projectors. -/
structure FiveSectorCommutingOperatorData
    (operator : E →L[Real] E) where
  coordinates : FiveSectorHilbertCoordinates
    (E := E) (Metric := Metric) (Abelian := Abelian) (Matter := Matter)
    (Longitudinal := Longitudinal) (Boundary := Boundary)
  commutes : ∀ sector vector,
    operator (coordinates.sectorProjector sector vector) =
      coordinates.sectorProjector sector (operator vector)

namespace FiveSectorCommutingOperatorData

/-- Coordinate map `E → product`. -/
def toProduct
    {operator : E →L[Real] E}
    (data : FiveSectorCommutingOperatorData
      (Metric := Metric) (Abelian := Abelian) (Matter := Matter)
      (Longitudinal := Longitudinal) (Boundary := Boundary) operator) :
    E →L[Real] ProductSpace :=
  data.coordinates.decomposition.toLinearIsometry.toContinuousLinearMap

/-- Inverse coordinate map `product → E`. -/
def fromProduct
    {operator : E →L[Real] E}
    (data : FiveSectorCommutingOperatorData
      (Metric := Metric) (Abelian := Abelian) (Matter := Matter)
      (Longitudinal := Longitudinal) (Boundary := Boundary) operator) :
    ProductSpace →L[Real] E :=
  data.coordinates.decomposition.symm.toLinearIsometry.toContinuousLinearMap

/-- The total operator conjugated to the physical product coordinates. -/
def conjugatedOperator
    {operator : E →L[Real] E}
    (data : FiveSectorCommutingOperatorData
      (Metric := Metric) (Abelian := Abelian) (Matter := Matter)
      (Longitudinal := Longitudinal) (Boundary := Boundary) operator) :
    ProductSpace →L[Real] ProductSpace :=
  data.toProduct.comp (operator.comp data.fromProduct)

/-- Metric/diffeomorphism block extracted from the total operator. -/
def metricBlock
    {operator : E →L[Real] E}
    (data : FiveSectorCommutingOperatorData
      (Metric := Metric) (Abelian := Abelian) (Matter := Matter)
      (Longitudinal := Longitudinal) (Boundary := Boundary) operator) :
    Metric →L[Real] Metric :=
  fiveSectorMetricCoordinate.comp
    (data.conjugatedOperator.comp fiveSectorMetricAxis)

/-- Abelian gauge block. -/
def abelianBlock
    {operator : E →L[Real] E}
    (data : FiveSectorCommutingOperatorData
      (Metric := Metric) (Abelian := Abelian) (Matter := Matter)
      (Longitudinal := Longitudinal) (Boundary := Boundary) operator) :
    Abelian →L[Real] Abelian :=
  fiveSectorAbelianCoordinate.comp
    (data.conjugatedOperator.comp fiveSectorAbelianAxis)

/-- Primitive SpinC matter block. -/
def matterBlock
    {operator : E →L[Real] E}
    (data : FiveSectorCommutingOperatorData
      (Metric := Metric) (Abelian := Abelian) (Matter := Matter)
      (Longitudinal := Longitudinal) (Boundary := Boundary) operator) :
    Matter →L[Real] Matter :=
  fiveSectorMatterCoordinate.comp
    (data.conjugatedOperator.comp fiveSectorMatterAxis)

/-- Longitudinal/LL block. -/
def longitudinalBlock
    {operator : E →L[Real] E}
    (data : FiveSectorCommutingOperatorData
      (Metric := Metric) (Abelian := Abelian) (Matter := Matter)
      (Longitudinal := Longitudinal) (Boundary := Boundary) operator) :
    Longitudinal →L[Real] Longitudinal :=
  fiveSectorLongitudinalCoordinate.comp
    (data.conjugatedOperator.comp fiveSectorLongitudinalAxis)

/-- Boundary/finite-BV block. -/
def boundaryBlock
    {operator : E →L[Real] E}
    (data : FiveSectorCommutingOperatorData
      (Metric := Metric) (Abelian := Abelian) (Matter := Matter)
      (Longitudinal := Longitudinal) (Boundary := Boundary) operator) :
    Boundary →L[Real] Boundary :=
  fiveSectorBoundaryCoordinate.comp
    (data.conjugatedOperator.comp fiveSectorBoundaryAxis)

private theorem metric_projected_input
    {operator : E →L[Real] E}
    (data : FiveSectorCommutingOperatorData
      (Metric := Metric) (Abelian := Abelian) (Matter := Matter)
      (Longitudinal := Longitudinal) (Boundary := Boundary) operator)
    (x : ProductSpace) :
    data.coordinates.metricProjector (data.fromProduct x) =
      data.fromProduct (fiveSectorMetricAxis (fiveSectorMetricCoordinate x)) := by
  apply data.coordinates.decomposition.injective
  rw [data.coordinates.decomposition_metricProjector]
  simp [fromProduct]

private theorem abelian_projected_input
    {operator : E →L[Real] E}
    (data : FiveSectorCommutingOperatorData
      (Metric := Metric) (Abelian := Abelian) (Matter := Matter)
      (Longitudinal := Longitudinal) (Boundary := Boundary) operator)
    (x : ProductSpace) :
    data.coordinates.abelianProjector (data.fromProduct x) =
      data.fromProduct (fiveSectorAbelianAxis (fiveSectorAbelianCoordinate x)) := by
  apply data.coordinates.decomposition.injective
  rw [data.coordinates.decomposition_abelianProjector]
  simp [fromProduct]

private theorem matter_projected_input
    {operator : E →L[Real] E}
    (data : FiveSectorCommutingOperatorData
      (Metric := Metric) (Abelian := Abelian) (Matter := Matter)
      (Longitudinal := Longitudinal) (Boundary := Boundary) operator)
    (x : ProductSpace) :
    data.coordinates.matterProjector (data.fromProduct x) =
      data.fromProduct (fiveSectorMatterAxis (fiveSectorMatterCoordinate x)) := by
  apply data.coordinates.decomposition.injective
  rw [data.coordinates.decomposition_matterProjector]
  simp [fromProduct]

private theorem longitudinal_projected_input
    {operator : E →L[Real] E}
    (data : FiveSectorCommutingOperatorData
      (Metric := Metric) (Abelian := Abelian) (Matter := Matter)
      (Longitudinal := Longitudinal) (Boundary := Boundary) operator)
    (x : ProductSpace) :
    data.coordinates.longitudinalProjector (data.fromProduct x) =
      data.fromProduct
        (fiveSectorLongitudinalAxis (fiveSectorLongitudinalCoordinate x)) := by
  apply data.coordinates.decomposition.injective
  rw [data.coordinates.decomposition_longitudinalProjector]
  simp [fromProduct]

private theorem boundary_projected_input
    {operator : E →L[Real] E}
    (data : FiveSectorCommutingOperatorData
      (Metric := Metric) (Abelian := Abelian) (Matter := Matter)
      (Longitudinal := Longitudinal) (Boundary := Boundary) operator)
    (x : ProductSpace) :
    data.coordinates.boundaryProjector (data.fromProduct x) =
      data.fromProduct (fiveSectorBoundaryAxis (fiveSectorBoundaryCoordinate x)) := by
  apply data.coordinates.decomposition.injective
  rw [data.coordinates.decomposition_boundaryProjector]
  simp [fromProduct]

/-- Metric output coordinate depends only on the metric input coordinate. -/
theorem metricCoordinate_conjugatedOperator
    {operator : E →L[Real] E}
    (data : FiveSectorCommutingOperatorData
      (Metric := Metric) (Abelian := Abelian) (Matter := Matter)
      (Longitudinal := Longitudinal) (Boundary := Boundary) operator)
    (x : ProductSpace) :
    fiveSectorMetricCoordinate (data.conjugatedOperator x) =
      data.metricBlock (fiveSectorMetricCoordinate x) := by
  have hCommute := data.commutes .metricDiffeomorphism (data.fromProduct x)
  change operator (data.coordinates.metricProjector (data.fromProduct x)) =
      data.coordinates.metricProjector (operator (data.fromProduct x)) at hCommute
  rw [data.metric_projected_input x] at hCommute
  have h := congrArg
    (fun value : E => fiveSectorMetricCoordinate (data.toProduct value)) hCommute
  simpa [metricBlock, conjugatedOperator, toProduct, fromProduct] using h.symm

/-- Abelian output coordinate depends only on the Abelian input coordinate. -/
theorem abelianCoordinate_conjugatedOperator
    {operator : E →L[Real] E}
    (data : FiveSectorCommutingOperatorData
      (Metric := Metric) (Abelian := Abelian) (Matter := Matter)
      (Longitudinal := Longitudinal) (Boundary := Boundary) operator)
    (x : ProductSpace) :
    fiveSectorAbelianCoordinate (data.conjugatedOperator x) =
      data.abelianBlock (fiveSectorAbelianCoordinate x) := by
  have hCommute := data.commutes .abelianGauge (data.fromProduct x)
  change operator (data.coordinates.abelianProjector (data.fromProduct x)) =
      data.coordinates.abelianProjector (operator (data.fromProduct x)) at hCommute
  rw [data.abelian_projected_input x] at hCommute
  have h := congrArg
    (fun value : E => fiveSectorAbelianCoordinate (data.toProduct value)) hCommute
  simpa [abelianBlock, conjugatedOperator, toProduct, fromProduct] using h.symm

/-- Matter output coordinate depends only on the matter input coordinate. -/
theorem matterCoordinate_conjugatedOperator
    {operator : E →L[Real] E}
    (data : FiveSectorCommutingOperatorData
      (Metric := Metric) (Abelian := Abelian) (Matter := Matter)
      (Longitudinal := Longitudinal) (Boundary := Boundary) operator)
    (x : ProductSpace) :
    fiveSectorMatterCoordinate (data.conjugatedOperator x) =
      data.matterBlock (fiveSectorMatterCoordinate x) := by
  have hCommute := data.commutes .primitiveSpinCMatter (data.fromProduct x)
  change operator (data.coordinates.matterProjector (data.fromProduct x)) =
      data.coordinates.matterProjector (operator (data.fromProduct x)) at hCommute
  rw [data.matter_projected_input x] at hCommute
  have h := congrArg
    (fun value : E => fiveSectorMatterCoordinate (data.toProduct value)) hCommute
  simpa [matterBlock, conjugatedOperator, toProduct, fromProduct] using h.symm

/-- Longitudinal output coordinate depends only on the longitudinal input. -/
theorem longitudinalCoordinate_conjugatedOperator
    {operator : E →L[Real] E}
    (data : FiveSectorCommutingOperatorData
      (Metric := Metric) (Abelian := Abelian) (Matter := Matter)
      (Longitudinal := Longitudinal) (Boundary := Boundary) operator)
    (x : ProductSpace) :
    fiveSectorLongitudinalCoordinate (data.conjugatedOperator x) =
      data.longitudinalBlock (fiveSectorLongitudinalCoordinate x) := by
  have hCommute := data.commutes .longitudinalLL (data.fromProduct x)
  change operator (data.coordinates.longitudinalProjector (data.fromProduct x)) =
      data.coordinates.longitudinalProjector (operator (data.fromProduct x)) at hCommute
  rw [data.longitudinal_projected_input x] at hCommute
  have h := congrArg
    (fun value : E => fiveSectorLongitudinalCoordinate (data.toProduct value)) hCommute
  simpa [longitudinalBlock, conjugatedOperator, toProduct, fromProduct] using h.symm

/-- Boundary output coordinate depends only on the boundary input coordinate. -/
theorem boundaryCoordinate_conjugatedOperator
    {operator : E →L[Real] E}
    (data : FiveSectorCommutingOperatorData
      (Metric := Metric) (Abelian := Abelian) (Matter := Matter)
      (Longitudinal := Longitudinal) (Boundary := Boundary) operator)
    (x : ProductSpace) :
    fiveSectorBoundaryCoordinate (data.conjugatedOperator x) =
      data.boundaryBlock (fiveSectorBoundaryCoordinate x) := by
  have hCommute := data.commutes .boundaryFiniteBV (data.fromProduct x)
  change operator (data.coordinates.boundaryProjector (data.fromProduct x)) =
      data.coordinates.boundaryProjector (operator (data.fromProduct x)) at hCommute
  rw [data.boundary_projected_input x] at hCommute
  have h := congrArg
    (fun value : E => fiveSectorBoundaryCoordinate (data.toProduct value)) hCommute
  simpa [boundaryBlock, conjugatedOperator, toProduct, fromProduct] using h.symm

/-- Exact block diagonalization of the conjugated total operator. -/
theorem conjugatedOperator_blockDiagonal
    {operator : E →L[Real] E}
    (data : FiveSectorCommutingOperatorData
      (Metric := Metric) (Abelian := Abelian) (Matter := Matter)
      (Longitudinal := Longitudinal) (Boundary := Boundary) operator)
    (x : ProductSpace) :
    data.conjugatedOperator x =
      fiveSectorMetricAxis
          (data.metricBlock (fiveSectorMetricCoordinate x)) +
        fiveSectorAbelianAxis
          (data.abelianBlock (fiveSectorAbelianCoordinate x)) +
        fiveSectorMatterAxis
          (data.matterBlock (fiveSectorMatterCoordinate x)) +
        fiveSectorLongitudinalAxis
          (data.longitudinalBlock (fiveSectorLongitudinalCoordinate x)) +
        fiveSectorBoundaryAxis
          (data.boundaryBlock (fiveSectorBoundaryCoordinate x)) := by
  have hDecompose := fiveSector_axis_decomposition (data.conjugatedOperator x)
  rw [data.metricCoordinate_conjugatedOperator x,
    data.abelianCoordinate_conjugatedOperator x,
    data.matterCoordinate_conjugatedOperator x,
    data.longitudinalCoordinate_conjugatedOperator x,
    data.boundaryCoordinate_conjugatedOperator x] at hDecompose
  exact hDecompose.symm

/-- Public five-sector block-diagonalization checkpoint. -/
theorem five_sector_operator_block_diagonalization_gate
    {operator : E →L[Real] E}
    (data : FiveSectorCommutingOperatorData
      (Metric := Metric) (Abelian := Abelian) (Matter := Matter)
      (Longitudinal := Longitudinal) (Boundary := Boundary) operator) :
    ∀ x : ProductSpace,
      data.conjugatedOperator x =
        fiveSectorMetricAxis
            (data.metricBlock (fiveSectorMetricCoordinate x)) +
          fiveSectorAbelianAxis
            (data.abelianBlock (fiveSectorAbelianCoordinate x)) +
          fiveSectorMatterAxis
            (data.matterBlock (fiveSectorMatterCoordinate x)) +
          fiveSectorLongitudinalAxis
            (data.longitudinalBlock (fiveSectorLongitudinalCoordinate x)) +
          fiveSectorBoundaryAxis
            (data.boundaryBlock (fiveSectorBoundaryCoordinate x)) :=
  data.conjugatedOperator_blockDiagonal

end FiveSectorCommutingOperatorData

end
end P0EFTJanusProgramPFiveSectorOperatorBlockDiagonalization4D
end JanusFormal
