import JanusFormal.Branches.FundamentalGeometryPVariationalPrinciple.Gates.P0EFTJanusProgramPProductThroatNuclearHeatDuhamelLongTimeExponential4D
import JanusFormal.Branches.FundamentalGeometryPVariationalPrinciple.Gates.P0EFTJanusProgramPNuclearDuhamelLongTimeExponentialDominatedCollapsedRankOneIntegral4D

/-!
# Product-spectral long-time collapsed Duhamel integrals

This frontend keeps the full common rank-one expansion of
`H'_a K_a(t)` but replaces its freely supplied exponential weighted packet by
the concrete product-throat spectral packet.  The rate is therefore

```text
1 / R^2,
```

and the scale is the locally uniform insertion bound multiplied by the genuine
unit-time product heat trace.

Only the rank-one spectral sum/integral exchange remains at this layer.  The
long-time majorant, its integrability and differentiation of the weighted heat
integral are generated by the circle-times-monopole-sphere spectrum.
-/

namespace JanusFormal
namespace P0EFTJanusProgramPNuclearDuhamelProductThroatLongTimeCollapsedRankOneIntegral4D

set_option autoImplicit false
noncomputable section

open MeasureTheory Set
open P0EFTJanusGlobalSeparatedDiracModel
open P0EFTJanusCircleDiracHeatTraceCancellation
open P0EFTJanusProgramPSummableRankOneOperatorExpansion4D
open P0EFTJanusProgramPIntrinsicNuclearTrace4D
open P0EFTJanusProgramPNuclearHeatDuhamelTraceVariation4D
open P0EFTJanusProgramPNuclearDuhamelLongTimeExponentialDominatedCollapsedRankOneIntegral4D
open P0EFTJanusProgramPNuclearDuhamelSemigroupProbabilityFamily4D
open P0EFTJanusProgramPProductThroatNuclearHeatDuhamelLongTimeExponential4D
open P0EFTJanusProductThroatPositiveHeatGapLongTime4D
open P0EFTJanusProgramPLongTimeExponentialDominatingFunction4D

universe u

variable {Slice E : Type*}
  [MeasurableSpace Slice]
  [NormedAddCommGroup E] [NormedSpace Real E]
  [InnerProductSpace Real E] [CompleteSpace E]

/-- Collapsed rank-one Duhamel data whose long-time domination is generated by
a concrete product-throat reference spectrum. -/
structure NuclearDuhamelProductThroatLongTimeCollapsedRankOneIntegralData
    (productData : ProductThroatSpectralData)
    (fold : Fold) (twist : CircleTwist)
    (sliceMeasure : Measure Slice) [IsProbabilityMeasure sliceMeasure]
    (nuclear : NuclearHeatDuhamelTraceVariationData (E := E))
    (start : Real) where
  semigroup :
    NuclearDuhamelSemigroupProbabilityFamilyData sliceMeasure nuclear
  weighted :
    ProductThroatNuclearHeatDuhamelLongTimeExponentialData
      productData fold twist nuclear start
  Index : Type u
  coefficient : Real → Real → Index → Real
  leftVector : Real → Index → E
  rightVector : Real → Index → E
  pointwise_nuclearNorm_summable : ∀ parameter time : HeatTime,
    Summable (fun index =>
      |coefficient parameter time.1 index| *
        ‖leftVector parameter index‖ * ‖rightVector parameter index‖)
  pointwise_trace_summable : ∀ parameter time : HeatTime,
    Summable (fun index =>
      coefficient parameter time.1 index *
        inner Real (leftVector parameter index)
          (rightVector parameter index))
  collapsed_operator_eq_tsum : ∀ parameter time : HeatTime,
    (semigroup.insertion parameter time).comp
        (semigroup.fullHeat parameter time) = ∑' index,
      coefficient parameter time.1 index •
        InnerProductSpace.rankOne Real
          (leftVector parameter index) (rightVector parameter index)
  integratedCoefficient : Real → Index → Real
  integratedCoefficient_eq : ∀ parameter index,
    integratedCoefficient parameter index =
      ∫ time in Set.Ioi start,
        if 0 < time then coefficient parameter time index else 0
  integratedOperator : Real → E →L[Real] E
  integrated_nuclearNorm_summable : ∀ parameter,
    Summable (fun index =>
      |integratedCoefficient parameter index| *
        ‖leftVector parameter index‖ * ‖rightVector parameter index‖)
  integrated_trace_summable : ∀ parameter,
    Summable (fun index =>
      integratedCoefficient parameter index *
        inner Real (leftVector parameter index)
          (rightVector parameter index))
  integrated_operator_eq_tsum : ∀ parameter,
    integratedOperator parameter = ∑' index,
      integratedCoefficient parameter index •
        InnerProductSpace.rankOne Real
          (leftVector parameter index) (rightVector parameter index)
  integratedTraceClass : ∀ parameter,
    IntrinsicNuclearTraceData (integratedOperator parameter)
  trace_integral_interchange : ∀ parameter,
    (∫ time in Set.Ioi start,
      ∑' index,
        (if 0 < time then coefficient parameter time index else 0) *
          inner Real (leftVector parameter index)
            (rightVector parameter index)) =
      ∑' index,
        integratedCoefficient parameter index *
          inner Real (leftVector parameter index)
            (rightVector parameter index)

namespace NuclearDuhamelProductThroatLongTimeCollapsedRankOneIntegralData

/-- Forget the spectral origin only after generating the existing exponential
collapsed-rank-one packet. -/
def toLongTimeExponentialDominatedCollapsedRankOneIntegral
    {productData : ProductThroatSpectralData}
    {fold : Fold} {twist : CircleTwist}
    {sliceMeasure : Measure Slice} [IsProbabilityMeasure sliceMeasure]
    {nuclear : NuclearHeatDuhamelTraceVariationData (E := E)}
    {start : Real}
    (data : NuclearDuhamelProductThroatLongTimeCollapsedRankOneIntegralData
      productData fold twist sliceMeasure nuclear start) :
    NuclearDuhamelLongTimeExponentialDominatedCollapsedRankOneIntegralData
      sliceMeasure nuclear start where
  semigroup := data.semigroup
  weighted := data.weighted.toLongTimeExponentialDominatedWeightedIntegral
  Index := data.Index
  coefficient := data.coefficient
  leftVector := data.leftVector
  rightVector := data.rightVector
  pointwise_nuclearNorm_summable := data.pointwise_nuclearNorm_summable
  pointwise_trace_summable := data.pointwise_trace_summable
  collapsed_operator_eq_tsum := data.collapsed_operator_eq_tsum
  integratedCoefficient := data.integratedCoefficient
  integratedCoefficient_eq := data.integratedCoefficient_eq
  integratedOperator := data.integratedOperator
  integrated_nuclearNorm_summable := data.integrated_nuclearNorm_summable
  integrated_trace_summable := data.integrated_trace_summable
  integrated_operator_eq_tsum := data.integrated_operator_eq_tsum
  integratedTraceClass := data.integratedTraceClass
  trace_integral_interchange := data.trace_integral_interchange

/-- The rate stored by the converted long-time packet is definitionally the
positive product heat gap. -/
@[simp] theorem generatedRate_eq_productThroatPositiveHeatGap
    {productData : ProductThroatSpectralData}
    {fold : Fold} {twist : CircleTwist}
    {sliceMeasure : Measure Slice} [IsProbabilityMeasure sliceMeasure]
    {nuclear : NuclearHeatDuhamelTraceVariationData (E := E)}
    {start : Real}
    (data : NuclearDuhamelProductThroatLongTimeCollapsedRankOneIntegralData
      productData fold twist sliceMeasure nuclear start)
    (parameter : Real) :
    data.toLongTimeExponentialDominatedCollapsedRankOneIntegral.weighted.rate
        parameter =
      productThroatPositiveHeatGap productData :=
  rfl

/-- The product-generated exponential majorant is integrable. -/
theorem bound_integrable
    {productData : ProductThroatSpectralData}
    {fold : Fold} {twist : CircleTwist}
    {sliceMeasure : Measure Slice} [IsProbabilityMeasure sliceMeasure]
    {nuclear : NuclearHeatDuhamelTraceVariationData (E := E)}
    {start : Real}
    (data : NuclearDuhamelProductThroatLongTimeCollapsedRankOneIntegralData
      productData fold twist sliceMeasure nuclear start)
    (parameter : Real) :
    Integrable
      (longTimeExponentialBound (data.weighted.longTimeScale parameter)
        (productThroatPositiveHeatGap productData))
      (volume.restrict (Set.Ioi start)) :=
  data.weighted.bound_integrable parameter

/-- Long-time differentiation of the weighted heat trace. -/
theorem weightedIntegral_hasDerivAt
    {productData : ProductThroatSpectralData}
    {fold : Fold} {twist : CircleTwist}
    {sliceMeasure : Measure Slice} [IsProbabilityMeasure sliceMeasure]
    {nuclear : NuclearHeatDuhamelTraceVariationData (E := E)}
    {start : Real}
    (data : NuclearDuhamelProductThroatLongTimeCollapsedRankOneIntegralData
      productData fold twist sliceMeasure nuclear start)
    (parameter : Real) :
    HasDerivAt
      data.toLongTimeExponentialDominatedCollapsedRankOneIntegral.
        toDominatedCollapsedRankOneIntegral.toCollapsedRankOneIntegral.weighted.
          toWeightedHeatTraceVariation.contribution
      (-(∫ time in Set.Ioi start,
        nuclear.extendedDuhamelTrace parameter time)) parameter :=
  data.toLongTimeExponentialDominatedCollapsedRankOneIntegral.
    weightedIntegral_hasDerivAt parameter

/-- The scalar Duhamel integral is the intrinsic trace of the integrated
product-spectral operator. -/
theorem scalarIntegral_eq_intrinsicTrace
    {productData : ProductThroatSpectralData}
    {fold : Fold} {twist : CircleTwist}
    {sliceMeasure : Measure Slice} [IsProbabilityMeasure sliceMeasure]
    {nuclear : NuclearHeatDuhamelTraceVariationData (E := E)}
    {start : Real}
    (data : NuclearDuhamelProductThroatLongTimeCollapsedRankOneIntegralData
      productData fold twist sliceMeasure nuclear start)
    (parameter : Real) :
    (∫ time in Set.Ioi start,
      nuclear.extendedDuhamelTrace parameter time) =
        intrinsicNuclearTrace (data.integratedTraceClass parameter) :=
  data.toLongTimeExponentialDominatedCollapsedRankOneIntegral.
    scalarIntegral_eq_intrinsicTrace parameter

/-- Public product-throat collapsed Duhamel checkpoint. -/
theorem nuclear_duhamel_product_throat_long_time_collapsed_rank_one_integral_gate
    (productData : ProductThroatSpectralData)
    (fold : Fold) (twist : CircleTwist)
    (sliceMeasure : Measure Slice) [IsProbabilityMeasure sliceMeasure]
    (nuclear : NuclearHeatDuhamelTraceVariationData (E := E))
    (start : Real)
    (data : NuclearDuhamelProductThroatLongTimeCollapsedRankOneIntegralData
      productData fold twist sliceMeasure nuclear start) :
    0 < productThroatPositiveHeatGap productData ∧
    (∀ parameter,
      Integrable
        (longTimeExponentialBound (data.weighted.longTimeScale parameter)
          (productThroatPositiveHeatGap productData))
        (volume.restrict (Set.Ioi start))) ∧
    (∀ parameter,
      HasDerivAt
        data.toLongTimeExponentialDominatedCollapsedRankOneIntegral.
          toDominatedCollapsedRankOneIntegral.toCollapsedRankOneIntegral.
            weighted.toWeightedHeatTraceVariation.contribution
        (-(∫ time in Set.Ioi start,
          nuclear.extendedDuhamelTrace parameter time)) parameter) ∧
    (∀ parameter,
      (∫ time in Set.Ioi start,
        nuclear.extendedDuhamelTrace parameter time) =
          intrinsicNuclearTrace (data.integratedTraceClass parameter)) :=
  ⟨productThroatPositiveHeatGap_pos productData,
    data.bound_integrable,
    data.weightedIntegral_hasDerivAt,
    data.scalarIntegral_eq_intrinsicTrace⟩

end NuclearDuhamelProductThroatLongTimeCollapsedRankOneIntegralData

end
end P0EFTJanusProgramPNuclearDuhamelProductThroatLongTimeCollapsedRankOneIntegral4D
end JanusFormal
