import JanusFormal.Branches.FundamentalGeometryPVariationalPrinciple.Gates.P0EFTJanusLLBraneAuxiliaryActionVariation

/-!
# Composite non-Riemannian measure for the finite LL-brane model

This gate realizes the independent worldvolume density from three auxiliary
scalar fields.  In an affine `2 + 1` chart their first derivatives form a
`3 x 3` Jacobian `J`; the signed composite measure is `Phi(J) = det J` (the
usual double-epsilon formula with its conventional factorial normalized
away).

The scalar fields have genuine directional `HasDerivAt` statements.  The
determinant has a genuine variation along every affine first-jet curve, and
the displayed coefficient is the full entrywise derivative rather than an
assumed variation.  Left multiplication by an inverse coordinate Jacobian
gives the exact signed density weight, with an explicit coordinate-volume
compensation theorem.  The identity first jet supplies a nondegenerate
measure and a direction in which its actual derivative is nonzero.

This remains a finite affine first-jet model.  It does not construct global
auxiliary fields, worldvolume PDE, an integral, orientation-changing absolute
densities, or a lightlike-brane throat solution.
-/

namespace JanusFormal
namespace P0EFTJanusLLBraneCompositeMeasureVariation

set_option autoImplicit false

noncomputable section

open P0EFTJanusExplicitBoundaryDensityLocalVariations

abbrev Point3 := Fin 3 → ℝ
abbrev Matrix3 := Matrix (Fin 3) (Fin 3) ℝ

/-- Three affine auxiliary scalars.  The first matrix index is the chart
coordinate and the second labels the auxiliary field. -/
def affineAuxiliaryFields
    (offset : Fin 3 → ℝ) (jet : Matrix3) (point : Point3)
    (field : Fin 3) : ℝ :=
  offset field + ∑ coordinate : Fin 3,
    jet coordinate field * point coordinate

def fieldDirectionalDerivative
    (jet : Matrix3) (direction : Point3) (field : Fin 3) : ℝ :=
  ∑ coordinate : Fin 3, jet coordinate field * direction coordinate

theorem affineAuxiliaryFields_curve
    (offset : Fin 3 → ℝ) (jet : Matrix3) (point direction : Point3)
    (field : Fin 3) (t : ℝ) :
    affineAuxiliaryFields offset jet (point + t • direction) field =
      affineAuxiliaryFields offset jet point field +
        t * fieldDirectionalDerivative jet direction field := by
  simp [affineAuxiliaryFields, fieldDirectionalDerivative,
    Fin.sum_univ_succ]
  ring

/-- The entries of `jet` are actual directional derivatives of the three
affine scalar fields, not independently supplied symbols. -/
theorem affineAuxiliaryFields_curve_hasDerivAt
    (offset : Fin 3 → ℝ) (jet : Matrix3) (point direction : Point3)
    (field : Fin 3) :
    HasDerivAt
      (fun t : ℝ =>
        affineAuxiliaryFields offset jet (point + t • direction) field)
      (fieldDirectionalDerivative jet direction field) 0 := by
  have hDerivative := affineScalar_hasDerivAt
    (affineAuxiliaryFields offset jet point field)
    (fieldDirectionalDerivative jet direction field)
  exact hDerivative.congr_of_eventuallyEq
    (Filter.Eventually.of_forall fun t =>
      affineAuxiliaryFields_curve offset jet point direction field t)

def coordinateDirection (coordinate : Fin 3) : Point3 :=
  fun index => if index = coordinate then 1 else 0

theorem fieldDirectionalDerivative_coordinateDirection
    (jet : Matrix3) (coordinate field : Fin 3) :
    fieldDirectionalDerivative jet (coordinateDirection coordinate) field =
      jet coordinate field := by
  classical
  simp [fieldDirectionalDerivative, coordinateDirection]

/-- The matrix called `jet` is exactly the coordinate Jacobian of the three
affine auxiliary fields. -/
theorem affineAuxiliaryFields_coordinate_curve_hasDerivAt
    (offset : Fin 3 → ℝ) (jet : Matrix3) (point : Point3)
    (coordinate field : Fin 3) :
    HasDerivAt
      (fun t : ℝ => affineAuxiliaryFields offset jet
        (point + t • coordinateDirection coordinate) field)
      (jet coordinate field) 0 := by
  rw [← fieldDirectionalDerivative_coordinateDirection
    jet coordinate field]
  exact affineAuxiliaryFields_curve_hasDerivAt offset jet point
    (coordinateDirection coordinate) field

/-- Signed non-Riemannian measure generated by the auxiliary Jacobian. -/
def compositeMeasure (jet : Matrix3) : ℝ :=
  Matrix.det jet

def auxiliaryJetCurve
    (jet variation : Matrix3) (t : ℝ) : Matrix3 :=
  jet + t • variation

/-- Full entrywise derivative of the `3 x 3` determinant. -/
def compositeMeasureVariation
    (jet variation : Matrix3) : ℝ :=
  variation 0 0 * jet 1 1 * jet 2 2 +
    jet 0 0 * variation 1 1 * jet 2 2 +
    jet 0 0 * jet 1 1 * variation 2 2 -
    variation 0 0 * jet 1 2 * jet 2 1 -
    jet 0 0 * variation 1 2 * jet 2 1 -
    jet 0 0 * jet 1 2 * variation 2 1 -
    variation 0 1 * jet 1 0 * jet 2 2 -
    jet 0 1 * variation 1 0 * jet 2 2 -
    jet 0 1 * jet 1 0 * variation 2 2 +
    variation 0 1 * jet 1 2 * jet 2 0 +
    jet 0 1 * variation 1 2 * jet 2 0 +
    jet 0 1 * jet 1 2 * variation 2 0 +
    variation 0 2 * jet 1 0 * jet 2 1 +
    jet 0 2 * variation 1 0 * jet 2 1 +
    jet 0 2 * jet 1 0 * variation 2 1 -
    variation 0 2 * jet 1 1 * jet 2 0 -
    jet 0 2 * variation 1 1 * jet 2 0 -
    jet 0 2 * jet 1 1 * variation 2 0

theorem compositeMeasure_curve_hasDerivAt
    (jet variation : Matrix3) :
    HasDerivAt
      (fun t : ℝ => compositeMeasure (auxiliaryJetCurve jet variation t))
      (compositeMeasureVariation jet variation) 0 := by
  unfold compositeMeasure auxiliaryJetCurve compositeMeasureVariation
  rw [show
      (fun t : ℝ => Matrix.det (jet + t • variation)) =
        (fun t : ℝ =>
          (jet 0 0 + t * variation 0 0) *
              (jet 1 1 + t * variation 1 1) *
              (jet 2 2 + t * variation 2 2) -
            (jet 0 0 + t * variation 0 0) *
              (jet 1 2 + t * variation 1 2) *
              (jet 2 1 + t * variation 2 1) -
            (jet 0 1 + t * variation 0 1) *
              (jet 1 0 + t * variation 1 0) *
              (jet 2 2 + t * variation 2 2) +
            (jet 0 1 + t * variation 0 1) *
              (jet 1 2 + t * variation 1 2) *
              (jet 2 0 + t * variation 2 0) +
            (jet 0 2 + t * variation 0 2) *
              (jet 1 0 + t * variation 1 0) *
              (jet 2 1 + t * variation 2 1) -
            (jet 0 2 + t * variation 0 2) *
              (jet 1 1 + t * variation 1 1) *
              (jet 2 0 + t * variation 2 0)) by
        funext t
        simp [Matrix.det_fin_three]]
  have h00 := affineScalar_hasDerivAt (jet 0 0) (variation 0 0)
  have h01 := affineScalar_hasDerivAt (jet 0 1) (variation 0 1)
  have h02 := affineScalar_hasDerivAt (jet 0 2) (variation 0 2)
  have h10 := affineScalar_hasDerivAt (jet 1 0) (variation 1 0)
  have h11 := affineScalar_hasDerivAt (jet 1 1) (variation 1 1)
  have h12 := affineScalar_hasDerivAt (jet 1 2) (variation 1 2)
  have h20 := affineScalar_hasDerivAt (jet 2 0) (variation 2 0)
  have h21 := affineScalar_hasDerivAt (jet 2 1) (variation 2 1)
  have h22 := affineScalar_hasDerivAt (jet 2 2) (variation 2 2)
  have hFirst := (h00.mul h11).mul h22
  have hSecond := (h00.mul h12).mul h21
  have hThird := (h01.mul h10).mul h22
  have hFourth := (h01.mul h12).mul h20
  have hFifth := (h02.mul h10).mul h21
  have hSixth := (h02.mul h11).mul h20
  have hTotal :=
    ((((hFirst.sub hSecond).sub hThird).add hFourth).add hFifth).sub hSixth
  apply hTotal.congr_deriv
  simp only [Pi.mul_apply, zero_mul, add_zero]
  ring

/-- Under a chart change, covector first jets are left multiplied by the
inverse coordinate Jacobian. -/
def coordinateReparametrizedJet
    (inverseCoordinateJacobian jet : Matrix3) : Matrix3 :=
  inverseCoordinateJacobian * jet

/-- Exact signed density weight of the composite measure. -/
theorem compositeMeasure_coordinateReparametrized
    (inverseCoordinateJacobian jet : Matrix3) :
    compositeMeasure
        (coordinateReparametrizedJet inverseCoordinateJacobian jet) =
      Matrix.det inverseCoordinateJacobian * compositeMeasure jet := by
  simp [compositeMeasure, coordinateReparametrizedJet, Matrix.det_mul]

/-- The signed coordinate volume compensates the inverse-Jacobian weight.
No absolute value is inserted, so this is the oriented-density statement. -/
theorem compositeMeasure_coordinateVolume_compensated
    (coordinateJacobian inverseCoordinateJacobian jet : Matrix3)
    (hInverse : coordinateJacobian * inverseCoordinateJacobian = 1) :
    Matrix.det coordinateJacobian *
        compositeMeasure
          (coordinateReparametrizedJet inverseCoordinateJacobian jet) =
      compositeMeasure jet := by
  rw [compositeMeasure_coordinateReparametrized]
  have hDet := congrArg Matrix.det hInverse
  rw [Matrix.det_mul, Matrix.det_one] at hDet
  calc
    Matrix.det coordinateJacobian *
          (Matrix.det inverseCoordinateJacobian * compositeMeasure jet) =
        (Matrix.det coordinateJacobian *
            Matrix.det inverseCoordinateJacobian) * compositeMeasure jet := by
          ring
    _ = compositeMeasure jet := by rw [hDet, one_mul]

def identityAuxiliaryJet : Matrix3 := 1

def firstFieldScalingVariation : Matrix3 :=
  Matrix.single 0 0 1

/-- Explicit nondegenerate auxiliary-field first jet. -/
theorem identityAuxiliaryJet_measure_nonzero :
    compositeMeasure identityAuxiliaryJet = 1 ∧
      compositeMeasure identityAuxiliaryJet ≠ 0 := by
  simp [compositeMeasure, identityAuxiliaryJet]

/-- The composite measure is not locally constant at the nondegenerate
witness: scaling the first auxiliary field has actual derivative one. -/
theorem identityAuxiliaryJet_measure_has_nonzero_variation :
    compositeMeasureVariation identityAuxiliaryJet
        firstFieldScalingVariation = 1 ∧
      HasDerivAt
        (fun t : ℝ => compositeMeasure
          (auxiliaryJetCurve identityAuxiliaryJet
            firstFieldScalingVariation t))
        1 0 := by
  have hVariation :
      compositeMeasureVariation identityAuxiliaryJet
        firstFieldScalingVariation = 1 := by
    simp [compositeMeasureVariation, identityAuxiliaryJet,
      firstFieldScalingVariation, Matrix.single]
  exact ⟨hVariation,
    hVariation ▸ compositeMeasure_curve_hasDerivAt
      identityAuxiliaryJet firstFieldScalingVariation⟩

end

end P0EFTJanusLLBraneCompositeMeasureVariation
end JanusFormal
