import JanusFormal.Branches.FundamentalGeometryPVariationalPrinciple.Gates.P0EFTJanusProgramPCountableRankOneNuclearTraceBochnerBridge4D

/-!
# Direct countable rank-one frontend for the renormalized Duhamel integral

This packet supplies the already-renormalized operator integrand, its Bochner
integrability, its pointwise intrinsic trace, and countable rank-one data at
each family parameter.  The nuclear trace Bochner bridge and the complete
`RenormalizedNuclearDuhamelOperatorIntegralData` are constructed outputs.
-/

namespace JanusFormal
namespace P0EFTJanusProgramPRenormalizedNuclearDuhamelCountableRankOneBochnerFrontend4D

set_option autoImplicit false
noncomputable section

open MeasureTheory Set
open P0EFTJanusProgramPCountableRankOneNuclearTraceBochnerBridge4D
open P0EFTJanusProgramPIntrinsicNuclearTrace4D
open P0EFTJanusProgramPNuclearHeatDuhamelCountertermSubtractedShortTimeQuadratic4D
open P0EFTJanusProgramPNuclearHeatDuhamelTraceVariation4D
open P0EFTJanusProgramPProductThroatSphereNuclearBasepointOperatorBoundaryFinitePartAssembly4D
open P0EFTJanusProgramPRenormalizedNuclearDuhamelBochnerOperatorIntegral4D

universe u v

variable {E : Type u}
  [NormedAddCommGroup E] [InnerProductSpace Real E] [CompleteSpace E]

/-- Direct parameter-family input.  The reusable ambient nuclear-trace
uniqueness theorem is contained inside each `rankOne` packet. -/
structure RenormalizedNuclearDuhamelCountableRankOneBochnerFrontendData
    (nuclear : NuclearHeatDuhamelTraceVariationData.{u, v} (E := E))
    (shortTime : NuclearHeatDuhamelCountertermSubtractedShortTimeQuadraticData
      nuclear 1) where
  operatorIntegrand : Real → Real → E →L[Real] E
  operatorIntegrable : ∀ parameter,
    Integrable (operatorIntegrand parameter)
      (volume.restrict (Set.Ioo (0 : Real) 1))
  pointwiseTraceClass : ∀ parameter time,
    IntrinsicNuclearTraceData.{u, v} (operatorIntegrand parameter time)
  pointwiseTrace_eq_renormalized : ∀ parameter,
    ∀ᵐ time ∂volume.restrict (Set.Ioo (0 : Real) 1),
      intrinsicNuclearTrace (pointwiseTraceClass parameter time) =
        shortTime.renormalizedDuhamelTrace parameter time
  rankOne : ∀ parameter,
    CountableRankOneNuclearTraceBochnerBridgeData.{u, v}
      (Set.Ioo (0 : Real) 1) (operatorIntegrand parameter)
        (pointwiseTraceClass parameter)

namespace RenormalizedNuclearDuhamelCountableRankOneBochnerFrontendData

/-- The rank-one packets automatically generate the parameterwise nuclear
trace Bochner bridges. -/
def toBochnerOperatorIntegralData
    {nuclear : NuclearHeatDuhamelTraceVariationData.{u, v} (E := E)}
    {shortTime : NuclearHeatDuhamelCountertermSubtractedShortTimeQuadraticData
      nuclear 1}
    (data : RenormalizedNuclearDuhamelCountableRankOneBochnerFrontendData
      nuclear shortTime) :
    RenormalizedNuclearDuhamelBochnerOperatorIntegralData.{u, v}
      nuclear shortTime where
  operatorIntegrand := data.operatorIntegrand
  operatorIntegrable := data.operatorIntegrable
  pointwiseTraceClass := data.pointwiseTraceClass
  pointwiseTrace_eq_renormalized := data.pointwiseTrace_eq_renormalized
  traceIntegralBridge := fun parameter ↦
    (data.rankOne parameter).toIntrinsicNuclearTraceBochnerBridge

/-- Final operator-integral packet required by the signed boundary assembly.
The integrated operator, its intrinsic trace certificate, and its scalar trace
identity are all generated by the two preceding constructors. -/
def toRenormalizedOperatorIntegral
    {nuclear : NuclearHeatDuhamelTraceVariationData.{u, v} (E := E)}
    {shortTime : NuclearHeatDuhamelCountertermSubtractedShortTimeQuadraticData
      nuclear 1}
    (data : RenormalizedNuclearDuhamelCountableRankOneBochnerFrontendData
      nuclear shortTime) :
    RenormalizedNuclearDuhamelOperatorIntegralData.{u, v}
      nuclear shortTime :=
  data.toBochnerOperatorIntegralData.toRenormalizedOperatorIntegral

/-- The generated integrated operator is definitionally the single
renormalized Bochner integral. -/
theorem integratedOperator_eq_bochnerIntegral
    {nuclear : NuclearHeatDuhamelTraceVariationData.{u, v} (E := E)}
    {shortTime : NuclearHeatDuhamelCountertermSubtractedShortTimeQuadraticData
      nuclear 1}
    (data : RenormalizedNuclearDuhamelCountableRankOneBochnerFrontendData
      nuclear shortTime)
    (parameter : Real) :
    data.toRenormalizedOperatorIntegral.integratedOperator parameter =
      ∫ time in Set.Ioo (0 : Real) 1,
        data.operatorIntegrand parameter time :=
  rfl

/-- The generated operator is also the integrated countable rank-one series. -/
theorem integratedOperator_eq_rankOneSeries
    {nuclear : NuclearHeatDuhamelTraceVariationData.{u, v} (E := E)}
    {shortTime : NuclearHeatDuhamelCountertermSubtractedShortTimeQuadraticData
      nuclear 1}
    (data : RenormalizedNuclearDuhamelCountableRankOneBochnerFrontendData
      nuclear shortTime)
    (parameter : Real) :
    data.toRenormalizedOperatorIntegral.integratedOperator parameter =
      ∑' index,
        (data.rankOne parameter).integratedCoefficient index •
          InnerProductSpace.rankOne Real
            ((data.rankOne parameter).leftVector index)
            ((data.rankOne parameter).rightVector index) :=
  (data.rankOne parameter).operatorIntegral_eq_integratedSeries

/-- The required scalar integral identity is a theorem of the frontend. -/
theorem scalarIntegral_eq_trace
    {nuclear : NuclearHeatDuhamelTraceVariationData.{u, v} (E := E)}
    {shortTime : NuclearHeatDuhamelCountertermSubtractedShortTimeQuadraticData
      nuclear 1}
    (data : RenormalizedNuclearDuhamelCountableRankOneBochnerFrontendData
      nuclear shortTime)
    (parameter : Real) :
    (∫ time in Set.Ioo (0 : Real) 1,
      shortTime.renormalizedDuhamelTrace parameter time) =
        intrinsicNuclearTrace
          (data.toRenormalizedOperatorIntegral.integratedTraceClass parameter) :=
  data.toRenormalizedOperatorIntegral.scalarIntegral_eq_trace parameter

/-- Public direct-frontend checkpoint. -/
theorem renormalized_nuclear_duhamel_countable_rank_one_bochner_frontend_gate
    (nuclear : NuclearHeatDuhamelTraceVariationData.{u, v} (E := E))
    (shortTime : NuclearHeatDuhamelCountertermSubtractedShortTimeQuadraticData
      nuclear 1)
    (data : RenormalizedNuclearDuhamelCountableRankOneBochnerFrontendData
      nuclear shortTime) :
    (∀ parameter,
      data.toRenormalizedOperatorIntegral.integratedOperator parameter =
        ∫ time in Set.Ioo (0 : Real) 1,
          data.operatorIntegrand parameter time) ∧
    (∀ parameter,
      data.toRenormalizedOperatorIntegral.integratedOperator parameter =
        ∑' index,
          (data.rankOne parameter).integratedCoefficient index •
            InnerProductSpace.rankOne Real
              ((data.rankOne parameter).leftVector index)
              ((data.rankOne parameter).rightVector index)) ∧
    (∀ parameter,
      (∫ time in Set.Ioo (0 : Real) 1,
        shortTime.renormalizedDuhamelTrace parameter time) =
          intrinsicNuclearTrace
            (data.toRenormalizedOperatorIntegral.integratedTraceClass
              parameter)) :=
  ⟨data.integratedOperator_eq_bochnerIntegral,
    data.integratedOperator_eq_rankOneSeries,
    data.scalarIntegral_eq_trace⟩

end RenormalizedNuclearDuhamelCountableRankOneBochnerFrontendData

end
end P0EFTJanusProgramPRenormalizedNuclearDuhamelCountableRankOneBochnerFrontend4D
end JanusFormal
