import JanusFormal.Branches.FundamentalGeometryPVariationalPrinciple.Gates.P0EFTJanusProgramPNuclearDuhamelCountableRankOneBochnerOperatorIntegral4D
import JanusFormal.Branches.FundamentalGeometryPVariationalPrinciple.Gates.P0EFTJanusProgramPProductThroatNuclearHeatDuhamelLongTimeExponential4D

/-!
# Product-throat countable Bochner long-time integral

The product spectrum generates the weighted long-time packet; countable
rank-one Bochner data then construct the integrated operator and its intrinsic
nuclear trace.
-/

namespace JanusFormal
namespace P0EFTJanusProgramPProductThroatNuclearDuhamelCountableRankOneBochnerOperatorIntegral4D

set_option autoImplicit false
noncomputable section

open MeasureTheory Set
open P0EFTJanusGlobalSeparatedDiracModel
open P0EFTJanusCircleDiracHeatTraceCancellation
open P0EFTJanusProgramPCountableRankOneNuclearTraceBochnerBridge4D
open P0EFTJanusProgramPIntrinsicNuclearTrace4D
open P0EFTJanusProgramPNuclearDuhamelCountableRankOneBochnerOperatorIntegral4D
open P0EFTJanusProgramPNuclearHeatDuhamelTraceVariation4D
open P0EFTJanusProgramPNuclearHeatDuhamelWeightedIntegral4D.NuclearHeatDuhamelTraceVariationData
open P0EFTJanusProgramPProductThroatNuclearHeatDuhamelLongTimeExponential4D
open P0EFTJanusProductThroatPositiveHeatGapLongTime4D

universe u v

variable {E : Type u}
  [NormedAddCommGroup E] [InnerProductSpace Real E] [CompleteSpace E]

/-- Operator-valued long-time data with product-generated scalar domination. -/
structure ProductThroatNuclearDuhamelCountableRankOneBochnerOperatorIntegralData
    (productData : ProductThroatSpectralData)
    (fold : Fold) (twist : CircleTwist)
    (nuclear : NuclearHeatDuhamelTraceVariationData.{u, v} (E := E))
    (start : Real) where
  weighted : ProductThroatNuclearHeatDuhamelLongTimeExponentialData
    productData fold twist nuclear start
  operatorIntegrand : Real → Real → E →L[Real] E
  operatorIntegrable : ∀ parameter,
    Integrable (operatorIntegrand parameter) (volume.restrict (Set.Ioi start))
  pointwiseTraceClass : ∀ parameter time,
    IntrinsicNuclearTraceData.{u, v} (operatorIntegrand parameter time)
  pointwiseTrace_eq_extendedDuhamelTrace : ∀ parameter,
    ∀ᵐ time ∂volume.restrict (Set.Ioi start),
      intrinsicNuclearTrace (pointwiseTraceClass parameter time) =
        extendedDuhamelTrace nuclear parameter time
  rankOne : ∀ parameter,
    CountableRankOneNuclearTraceBochnerBridgeData.{u, v}
      (Set.Ioi start) (operatorIntegrand parameter)
        (pointwiseTraceClass parameter)

namespace ProductThroatNuclearDuhamelCountableRankOneBochnerOperatorIntegralData

/-- The generic Bochner packet, with its weighted component generated by the
product spectrum. -/
def toCountableRankOneBochnerOperatorIntegral
    {productData : ProductThroatSpectralData}
    {fold : Fold} {twist : CircleTwist}
    {nuclear : NuclearHeatDuhamelTraceVariationData.{u, v} (E := E)}
    {start : Real}
    (data :
      ProductThroatNuclearDuhamelCountableRankOneBochnerOperatorIntegralData
        productData fold twist nuclear start) :
    NuclearDuhamelCountableRankOneBochnerOperatorIntegralData
      nuclear (Set.Ioi start) where
  weighted :=
    data.weighted.toLongTimeExponentialDominatedWeightedIntegral.toDominatedWeightedIntegral.toWeightedIntegral
  operatorIntegrand := data.operatorIntegrand
  operatorIntegrable := data.operatorIntegrable
  pointwiseTraceClass := data.pointwiseTraceClass
  pointwiseTrace_eq_extendedDuhamelTrace :=
    data.pointwiseTrace_eq_extendedDuhamelTrace
  rankOne := data.rankOne

/-- Public checkpoint: positive rate, Bochner operator construction and trace
commutation are all available together. -/
theorem product_throat_nuclear_duhamel_countable_rank_one_bochner_gate
    {productData : ProductThroatSpectralData}
    {fold : Fold} {twist : CircleTwist}
    {nuclear : NuclearHeatDuhamelTraceVariationData.{u, v} (E := E)}
    {start : Real}
    (data :
      ProductThroatNuclearDuhamelCountableRankOneBochnerOperatorIntegralData
        productData fold twist nuclear start) :
    0 < productThroatPositiveHeatGap productData ∧
    (∀ parameter,
      data.toCountableRankOneBochnerOperatorIntegral.toNuclearDuhamelOperatorIntegral.integratedOperator
          parameter =
        ∫ time in Set.Ioi start, data.operatorIntegrand parameter time) ∧
    (∀ parameter,
      (∫ time in Set.Ioi start,
        extendedDuhamelTrace nuclear parameter time) =
      intrinsicNuclearTrace
        (data.toCountableRankOneBochnerOperatorIntegral.integratedTraceClass
          parameter)) := by
  exact ⟨productThroatPositiveHeatGap_pos productData, fun _ => rfl,
    data.toCountableRankOneBochnerOperatorIntegral.scalarIntegral_eq_intrinsicTrace⟩

end ProductThroatNuclearDuhamelCountableRankOneBochnerOperatorIntegralData

end
end P0EFTJanusProgramPProductThroatNuclearDuhamelCountableRankOneBochnerOperatorIntegral4D
end JanusFormal
