import JanusFormal.Branches.FundamentalGeometryPVariationalPrinciple.Gates.P0EFTJanusProgramPGlobalCandidateASevenPhysicalCanonicalExtensions4D
import JanusFormal.Branches.FundamentalGeometryPVariationalPrinciple.Gates.P0EFTJanusProgramPGlobalHessianH10RobinComplementClosure4D

/-!
# H14 from H10 and canonical continuous physical extensions

The seven smooth-core physical forms are fixed as the true local second
Fréchet derivatives of the corresponding Candidate-A action blocks.  This
terminal façade therefore asks only for their continuous symmetric extensions
and for the finite-complement inverse of the resulting augmented operator.
-/

namespace JanusFormal
namespace P0EFTJanusProgramPGlobalHessianH10RobinCanonicalClosure4D

set_option autoImplicit false
set_option maxHeartbeats 4200000
set_option synthInstance.maxHeartbeats 2100000

noncomputable section

open Set Topology MeasureTheory
open scoped Manifold ContDiff InnerProductSpace
open P0EFTJanusMappingTorusQuotient
open P0EFTJanusMappingTorusSmoothAtlasFrontier
open P0EFTJanusMappingTorusSmoothQuotientManifold
open P0EFTJanusProgramPGlobalFieldSpace4D
open P0EFTJanusProgramPGlobalTypedNonminimalFieldSpace4D
open P0EFTJanusProgramPGlobalCovariantAction4D
open P0EFTJanusProgramPGlobalAnalysisDomain4D
open P0EFTJanusProgramPGlobalLocalVariationalChart4D
open P0EFTJanusProgramPGlobalCandidateAMatterLLSameActionClosure4D
open P0EFTJanusProgramPGlobalCandidateACommonAugmentedAnalyticDomain4D
open P0EFTJanusProgramPGlobalCandidateAMinimalPhysicalActionFamilyH10RobinReduction4D
open P0EFTJanusProgramPGlobalCandidateASevenPhysicalCanonicalExtensions4D
open P0EFTJanusProgramPGlobalCandidateAAugmentedComplementInverse4D
open P0EFTJanusProgramPGlobalHessianDiracGreenBoundedClosure4D
open P0EFTJanusProgramPGlobalHessianH10RobinAnalyticClosure4D
open P0EFTJanusProgramPGlobalHessianH10RobinContinuousClosure4D
open P0EFTJanusProgramPGlobalHessianH10RobinComplementClosure4D

variable (period : Real) (hPeriod : period ≠ 0)

private abbrev EffectiveQuotient :=
  MappingTorus (reflectedSphereData period hPeriod)

local instance effectiveQuotientChartedSpace :
    ChartedSpace CoverModel (EffectiveQuotient period hPeriod) :=
  reflectedSphereQuotientChartedSpace period hPeriod

local instance effectiveQuotientIsManifold :
    IsManifold coverModelWithCorners ω (EffectiveQuotient period hPeriod) :=
  reflectedSphereQuotient_isManifold period hPeriod

local instance effectiveQuotientMeasurableSpace :
    MeasurableSpace (EffectiveQuotient period hPeriod) := borel _

local instance effectiveQuotientBorelSpace :
    BorelSpace (EffectiveQuotient period hPeriod) where
  measurable_eq := rfl

/-- H11 extension generated by the canonical physical block extensions. -/
def globalCandidateAH10RobinCanonicalPhysicalExtension
    {couplings : GlobalCandidateAActionCouplings}
    {NonNullFace NullFace : Type*}
    [Fintype NonNullFace] [Fintype NullFace]
    {measure : Measure (EffectiveQuotient period hPeriod)}
    (configuration : GlobalGaugeFixedFieldConfiguration period hPeriod)
    (data : GlobalCandidateAActionData period hPeriod configuration.physical
      couplings NonNullFace NullFace)
    (analysis : GlobalAnalysisData period hPeriod configuration.physical)
    (family : ProgramPGlobalMinimalPhysicalLocalActionFamilyH10RobinData4D
      period hPeriod configuration data analysis
        (diracGreenClosureMatterRealization period hPeriod
          couplings.matterMassSquared))
    (extensions : GlobalCandidateASevenPhysicalCanonicalContinuousExtensions4D
      period hPeriod configuration data analysis
        (globalCandidateAH10RobinChart period hPeriod configuration data
          analysis family)
        (globalCandidateAH10RobinSameAction period hPeriod configuration data
          analysis family)) :=
  globalCandidateAH10RobinContinuousPhysicalExtension period hPeriod
    configuration data analysis family
      (extensions.toContinuous period hPeriod)

/-- Preferred canonical H14 gate. -/
theorem global_candidateA_hessian_h10Robin_canonical_closure_gate
    {couplings : GlobalCandidateAActionCouplings}
    {NonNullFace NullFace : Type*}
    [Fintype NonNullFace] [Fintype NullFace]
    {measure : Measure (EffectiveQuotient period hPeriod)}
    (configuration : GlobalGaugeFixedFieldConfiguration period hPeriod)
    (data : GlobalCandidateAActionData period hPeriod configuration.physical
      couplings NonNullFace NullFace)
    (analysis : GlobalAnalysisData period hPeriod configuration.physical)
    (einsteinScale : Real)
    (hBoundaryTransverse : HasNoTangentialRadical period hPeriod
      data.plusGravity.metric.metric)
    (family : ProgramPGlobalMinimalPhysicalLocalActionFamilyH10RobinData4D
      period hPeriod configuration data analysis
        (diracGreenClosureMatterRealization period hPeriod
          couplings.matterMassSquared))
    (extensions : GlobalCandidateASevenPhysicalCanonicalContinuousExtensions4D
      period hPeriod configuration data analysis
        (globalCandidateAH10RobinChart period hPeriod configuration data
          analysis family)
        (globalCandidateAH10RobinSameAction period hPeriod configuration data
          analysis family))
    (inverse : GlobalCandidateAFaithfulAugmentedComplementInverse4D period
      hPeriod configuration data analysis
        (globalCandidateAH10RobinChart period hPeriod configuration data
          analysis family)
        (globalCandidateAH10RobinSameAction period hPeriod configuration data
          analysis family)
        (globalCandidateAH10RobinCanonicalPhysicalExtension period hPeriod
          configuration data analysis family extensions)) :=
  global_candidateA_hessian_h10Robin_complement_closure_gate period hPeriod
    configuration data analysis einsteinScale hBoundaryTransverse family
      (extensions.toContinuous period hPeriod)
      inverse

end
end P0EFTJanusProgramPGlobalHessianH10RobinCanonicalClosure4D
end JanusFormal
