import Mathlib.Analysis.InnerProductSpace.ProdL2
import Mathlib.Analysis.InnerProductSpace.Subspace
import JanusFormal.Branches.FundamentalGeometryPVariationalPrinciple.Gates.P0EFTJanusProgramPGlobalEulerLagrangeMinimalPhysicalSeparatingPDEResidual4D

/-!
# State-dependent augmented graph Riesz residuals

This file packages the repeated construction used when an authentic Hilbert
block is accompanied by a merely algebraic cross-block covector.  The latter
is retained as a scalar graph coordinate; no PDE interpretation is added.
-/

namespace JanusFormal
namespace P0EFTJanusProgramPStateDependentAugmentedGraphRieszResidual4D

set_option autoImplicit false
noncomputable section

open Set Topology
open scoped InnerProductSpace Topology
open P0EFTJanusProgramPGlobalEulerLagrangeMinimalPhysicalSeparatingPDEResidual4D

universe u v

variable {Test : Type u} {Base : Type v}
  [AddCommGroup Test] [Module Real Test]
  [NormedAddCommGroup Base] [InnerProductSpace Real Base]
  [CompleteSpace Base]

/-- A Hilbert block, an unrepresented scalar remainder, and a continuous
covector on the Hilbert block. -/
structure StateDependentAugmentedGraphRieszData where
  baseMap : Test →ₗ[Real] Base
  remainder : Test →ₗ[Real] Real
  baseCovector : Base →L[Real] Real

/-- Total algebraic test covector represented by the augmented graph. -/
def stateDependentAugmentedTotalCovector
    (data : StateDependentAugmentedGraphRieszData
      (Test := Test) (Base := Base)) : Test →ₗ[Real] Real :=
  data.baseCovector.toLinearMap.comp data.baseMap + data.remainder

/-- Algebraic graph map retaining the remainder as a scalar coordinate. -/
def stateDependentAugmentedGraphLinearMap
    (data : StateDependentAugmentedGraphRieszData
      (Test := Test) (Base := Base)) :
    Test →ₗ[Real] WithLp 2 (Base × Real) where
  toFun test := WithLp.toLp 2 (data.baseMap test, data.remainder test)
  map_add' first second := by
    apply WithLp.ofLp_injective
    simp
  map_smul' scalar test := by
    apply WithLp.ofLp_injective
    simp

/-- Closed Hilbert graph generated by the algebraic tests. -/
def stateDependentAugmentedGraphSubmodule
    (data : StateDependentAugmentedGraphRieszData
      (Test := Test) (Base := Base)) :
    Submodule Real (WithLp 2 (Base × Real)) :=
  (LinearMap.range
    (stateDependentAugmentedGraphLinearMap data)).topologicalClosure

abbrev StateDependentAugmentedGraphHilbert
    (data : StateDependentAugmentedGraphRieszData
      (Test := Test) (Base := Base)) :=
  stateDependentAugmentedGraphSubmodule data

@[implicit_reducible]
def stateDependentAugmentedGraphCompleteSpace
    (data : StateDependentAugmentedGraphRieszData
      (Test := Test) (Base := Base)) :
    CompleteSpace (StateDependentAugmentedGraphHilbert data) := by
  letI : CompleteSpace (WithLp 2 (Base × Real)) := inferInstance
  exact Submodule.topologicalClosure.completeSpace
    (LinearMap.range (stateDependentAugmentedGraphLinearMap data))

/-- Dense inclusion of algebraic tests into the completed graph. -/
def stateDependentAugmentedGraphEmbedding
    (data : StateDependentAugmentedGraphRieszData
      (Test := Test) (Base := Base)) :
    Test →ₗ[Real] StateDependentAugmentedGraphHilbert data where
  toFun test :=
    ⟨stateDependentAugmentedGraphLinearMap data test,
      (LinearMap.range
        (stateDependentAugmentedGraphLinearMap data)).le_topologicalClosure
        (LinearMap.mem_range_self
          (stateDependentAugmentedGraphLinearMap data) test)⟩
  map_add' first second := Subtype.ext (map_add _ first second)
  map_smul' scalar test := Subtype.ext (map_smul _ scalar test)

omit [CompleteSpace Base] in
theorem stateDependentAugmentedGraphEmbedding_denseRange
    (data : StateDependentAugmentedGraphRieszData
      (Test := Test) (Base := Base)) :
    DenseRange (stateDependentAugmentedGraphEmbedding data) := by
  simp only [DenseRange]
  rw [Subtype.dense_iff]
  let graph := stateDependentAugmentedGraphLinearMap data
  have hRange :
      Subtype.val '' Set.range (stateDependentAugmentedGraphEmbedding data) =
        (LinearMap.range graph : Set (WithLp 2 (Base × Real))) := by
    ext value
    constructor
    · rintro ⟨lifted, ⟨test, rfl⟩, rfl⟩
      exact ⟨test, rfl⟩
    · rintro ⟨test, rfl⟩
      exact ⟨stateDependentAugmentedGraphEmbedding data test,
        ⟨test, rfl⟩, rfl⟩
  change closure (LinearMap.range graph : Set (WithLp 2 (Base × Real))) ⊆
    closure (Subtype.val '' Set.range
      (stateDependentAugmentedGraphEmbedding data))
  rw [hRange]

/-- Continuous total covector on the completed augmented graph. -/
def stateDependentAugmentedGraphCovector
    (data : StateDependentAugmentedGraphRieszData
      (Test := Test) (Base := Base)) :
    StateDependentAugmentedGraphHilbert data →L[Real] Real :=
  ((data.baseCovector.comp (WithLp.fstL 2 Real Base Real)) +
      WithLp.sndL 2 Real Base Real).comp
    (stateDependentAugmentedGraphSubmodule data).subtypeL

/-- Riesz representative of the total covector on the augmented graph. -/
def stateDependentAugmentedGraphRieszResidual
    (data : StateDependentAugmentedGraphRieszData
      (Test := Test) (Base := Base)) :
    StateDependentAugmentedGraphHilbert data := by
  letI : CompleteSpace (StateDependentAugmentedGraphHilbert data) :=
    stateDependentAugmentedGraphCompleteSpace data
  exact
    (InnerProductSpace.toDual Real
      (StateDependentAugmentedGraphHilbert data)).symm
        (stateDependentAugmentedGraphCovector data)

theorem stateDependentAugmentedGraphRieszResidual_pairing
    (data : StateDependentAugmentedGraphRieszData
      (Test := Test) (Base := Base))
    (test : StateDependentAugmentedGraphHilbert data) :
    inner Real (stateDependentAugmentedGraphRieszResidual data) test =
      stateDependentAugmentedGraphCovector data test := by
  letI : CompleteSpace (StateDependentAugmentedGraphHilbert data) :=
    stateDependentAugmentedGraphCompleteSpace data
  unfold stateDependentAugmentedGraphRieszResidual
  exact InnerProductSpace.toDual_symm_apply

/-- Pair a graph residual with one original algebraic test. -/
def stateDependentAugmentedGraphResidualPairing
    (data : StateDependentAugmentedGraphRieszData
      (Test := Test) (Base := Base))
    (residual : StateDependentAugmentedGraphHilbert data)
    (test : Test) : Real :=
  inner Real residual (stateDependentAugmentedGraphEmbedding data test)

theorem stateDependentAugmentedTotalCovector_apply_eq_residualPairing
    (data : StateDependentAugmentedGraphRieszData
      (Test := Test) (Base := Base)) (test : Test) :
    stateDependentAugmentedTotalCovector data test =
      stateDependentAugmentedGraphResidualPairing data
        (stateDependentAugmentedGraphRieszResidual data) test := by
  unfold stateDependentAugmentedGraphResidualPairing
  rw [stateDependentAugmentedGraphRieszResidual_pairing]
  rfl

omit [CompleteSpace Base] in
theorem stateDependentAugmentedGraphResidualPairing_separates
    (data : StateDependentAugmentedGraphRieszData
      (Test := Test) (Base := Base))
    (residual : StateDependentAugmentedGraphHilbert data) :
    (∀ test : Test,
        stateDependentAugmentedGraphResidualPairing data residual test = 0) ↔
      residual = 0 := by
  constructor
  · intro hPairing
    apply (stateDependentAugmentedGraphEmbedding_denseRange data
      ).eq_zero_of_inner_left (𝕜 := Real)
    exact hPairing
  · rintro rfl test
    simp [stateDependentAugmentedGraphResidualPairing]

/-- Separating representation carried by the augmented closed graph. -/
def stateDependentAugmentedGraphResidualRepresentation
    (data : StateDependentAugmentedGraphRieszData
      (Test := Test) (Base := Base)) :
    SeparatingPDEResidualRepresentation
      (stateDependentAugmentedTotalCovector data) where
  Residual := StateDependentAugmentedGraphHilbert data
  zeroResidual := 0
  residual := stateDependentAugmentedGraphRieszResidual data
  pairing := stateDependentAugmentedGraphResidualPairing data
  represents := stateDependentAugmentedTotalCovector_apply_eq_residualPairing data
  separates := stateDependentAugmentedGraphResidualPairing_separates data _

theorem stateDependentAugmentedTotalCovector_eq_zero_iff_graphResidual
    (data : StateDependentAugmentedGraphRieszData
      (Test := Test) (Base := Base)) :
    stateDependentAugmentedTotalCovector data = 0 ↔
      stateDependentAugmentedGraphRieszResidual data = 0 :=
  separatingPDEResidualRepresentation_covector_eq_zero_iff
    (stateDependentAugmentedGraphResidualRepresentation data)

/-- Gate 252: a Hilbert block plus an algebraic scalar remainder always has
an exact separating residual on its state-dependent augmented graph. -/
theorem state_dependent_augmented_graph_riesz_residual_gate
    (data : StateDependentAugmentedGraphRieszData
      (Test := Test) (Base := Base)) :
    stateDependentAugmentedTotalCovector data = 0 ↔
      stateDependentAugmentedGraphRieszResidual data = 0 :=
  stateDependentAugmentedTotalCovector_eq_zero_iff_graphResidual data

end
end P0EFTJanusProgramPStateDependentAugmentedGraphRieszResidual4D
end JanusFormal
