import JanusFormal.Branches.FundamentalGeometryPVariationalPrinciple.Gates.P0EFTJanusProgramPGlobalCandidateAMinimalPhysicalActionFamilyPhysicalC2Reduction4D
import JanusFormal.Branches.FundamentalGeometryPVariationalPrinciple.Gates.P0EFTJanusProgramPGlobalCandidateASevenPhysicalBlockBounds4D
import JanusFormal.Branches.FundamentalGeometryPVariationalPrinciple.Gates.P0EFTJanusProgramPGlobalCandidateASevenPhysicalBoundedExtension4D
import JanusFormal.Branches.FundamentalGeometryPVariationalPrinciple.Gates.P0EFTJanusProgramPGlobalCandidateAAugmentedGeneralizedInverse4D
import JanusFormal.Branches.FundamentalGeometryPVariationalPrinciple.Gates.P0EFTJanusProgramPGlobalHessianDiracGreenBoundedClosure4D

/-!
# H14 closure from the three decomposed analytic packets

This gate composes the three constructive reductions of the remaining analytic
frontier:

1. only the seven physical Candidate-A blocks require local `C²` input;
2. their common H11 estimate is assembled from seven blockwise bounds;
3. the H12 finite-defect parametrix is generated from one bounded generalized
   inverse with canonical defects.

The primitive SpinC graph is still supplied by the unconditional Green closure.
No D10 direction, replacement action, auxiliary completion or extra physical
hypothesis enters this route.
-/

namespace JanusFormal
namespace P0EFTJanusProgramPGlobalHessianConstructiveAnalyticClosure4D

set_option autoImplicit false
set_option synthInstance.maxHeartbeats 1600000
set_option maxHeartbeats 3200000

noncomputable section

open Set Topology MeasureTheory
open scoped Manifold ContDiff InnerProductSpace
open P0EFTJanusMappingTorusQuotient
open P0EFTJanusMappingTorusSmoothAtlasFrontier
open P0EFTJanusMappingTorusSmoothQuotientManifold
open P0EFTJanusMappingTorusGeneralLorentzMetricThroatTrace4D
open P0EFTJanusProgramPGlobalFieldSpace4D
open P0EFTJanusProgramPGlobalTypedNonminimalFieldSpace4D
open P0EFTJanusProgramPGlobalCovariantAction4D
open P0EFTJanusProgramPGlobalAnalysisDomain4D
open P0EFTJanusProgramPGlobalLocalVariationalChart4D
open P0EFTJanusProgramPGlobalCandidateAMatterLLSameActionClosure4D
open P0EFTJanusProgramPGlobalCandidateACommonAugmentedAnalyticDomain4D
open P0EFTJanusProgramPGlobalHessianClosure4D
open P0EFTJanusProgramPGlobalCandidateAMinimalPhysicalActionFamilyPhysicalC2Reduction4D
open P0EFTJanusProgramPGlobalCandidateASevenPhysicalBlockBounds4D
open P0EFTJanusProgramPGlobalCandidateASevenPhysicalBoundedExtension4D
open P0EFTJanusProgramPGlobalCandidateAAugmentedGeneralizedInverse4D
open P0EFTJanusProgramPGlobalHessianDiracGreenBoundedClosure4D

variable (period : Real) (hPeriod : period ≠ 0)

private abbrev EffectiveQuotient :=
  MappingTorus (reflectedSphereData period hPeriod)

local instance effectiveQuotientChartedSpace :
    ChartedSpace CoverModel (EffectiveQuotient period hPeriod) :=
  reflectedSphereQuotientChartedSpace period hPeriod

local instance effectiveQuotientIsManifold :
    IsManifold coverModelWithCorners ω (EffectiveQuotient period hPeriod) :=
  reflectedSphereQuotient_isManifold period hPeriod

local instance effectiveQuotientMeasurableSpace :
    MeasurableSpace (EffectiveQuotient period hPeriod) := borel _

local instance effectiveQuotientBorelSpace :
    BorelSpace (EffectiveQuotient period hPeriod) where
  measurable_eq := rfl

/-- The first packet reconstructed as the reduced family expected by the Green
closure. -/
def globalCandidateAHessianConstructiveReducedFamily
    {couplings : GlobalCandidateAActionCouplings}
    {NonNullFace NullFace : Type*}
    [Fintype NonNullFace] [Fintype NullFace]
    {measure : Measure (EffectiveQuotient period hPeriod)}
    (configuration : GlobalGaugeFixedFieldConfiguration period hPeriod)
    (data : GlobalCandidateAActionData period hPeriod configuration.physical
      couplings NonNullFace NullFace)
    (analysis : GlobalAnalysisData period hPeriod configuration.physical)
    (family :
      ProgramPGlobalMinimalPhysicalLocalActionFamilyPhysicalC2Data4D
        period hPeriod configuration data analysis
          (diracGreenClosureMatterRealization period hPeriod
            couplings.matterMassSquared)) :=
  family.toReduced period hPeriod (measure := measure)

/-- Canonical local chart generated by the physical-`C²` family. -/
def globalCandidateAHessianConstructiveChart
    {couplings : GlobalCandidateAActionCouplings}
    {NonNullFace NullFace : Type*}
    [Fintype NonNullFace] [Fintype NullFace]
    {measure : Measure (EffectiveQuotient period hPeriod)}
    (configuration : GlobalGaugeFixedFieldConfiguration period hPeriod)
    (data : GlobalCandidateAActionData period hPeriod configuration.physical
      couplings NonNullFace NullFace)
    (analysis : GlobalAnalysisData period hPeriod configuration.physical)
    (family :
      ProgramPGlobalMinimalPhysicalLocalActionFamilyPhysicalC2Data4D
        period hPeriod configuration data analysis
          (diracGreenClosureMatterRealization period hPeriod
            couplings.matterMassSquared)) :=
  diracGreenClosureChart period hPeriod (measure := measure) configuration data analysis
    (globalCandidateAHessianConstructiveReducedFamily period hPeriod (measure := measure)
      configuration data analysis family)

/-- Canonical matter--LL same-action bridge generated by the same family. -/
def globalCandidateAHessianConstructiveSameAction
    {couplings : GlobalCandidateAActionCouplings}
    {NonNullFace NullFace : Type*}
    [Fintype NonNullFace] [Fintype NullFace]
    {measure : Measure (EffectiveQuotient period hPeriod)}
    (configuration : GlobalGaugeFixedFieldConfiguration period hPeriod)
    (data : GlobalCandidateAActionData period hPeriod configuration.physical
      couplings NonNullFace NullFace)
    (analysis : GlobalAnalysisData period hPeriod configuration.physical)
    (family :
      ProgramPGlobalMinimalPhysicalLocalActionFamilyPhysicalC2Data4D
        period hPeriod configuration data analysis
          (diracGreenClosureMatterRealization period hPeriod
            couplings.matterMassSquared)) :=
  diracGreenClosureMatterLLSameAction period hPeriod (measure := measure) configuration data analysis
    (globalCandidateAHessianConstructiveReducedFamily period hPeriod (measure := measure)
      configuration data analysis family)

/-- The second packet summed into the H11 common bound. -/
def globalCandidateAHessianConstructivePhysicalBound
    {couplings : GlobalCandidateAActionCouplings}
    {NonNullFace NullFace : Type*}
    [Fintype NonNullFace] [Fintype NullFace]
    {measure : Measure (EffectiveQuotient period hPeriod)}
    (configuration : GlobalGaugeFixedFieldConfiguration period hPeriod)
    (data : GlobalCandidateAActionData period hPeriod configuration.physical
      couplings NonNullFace NullFace)
    (analysis : GlobalAnalysisData period hPeriod configuration.physical)
    (family :
      ProgramPGlobalMinimalPhysicalLocalActionFamilyPhysicalC2Data4D
        period hPeriod configuration data analysis
          (diracGreenClosureMatterRealization period hPeriod
            couplings.matterMassSquared))
    (bounds : GlobalCandidateASevenPhysicalBlockCoreBounds4D period hPeriod
      configuration data analysis
        (globalCandidateAHessianConstructiveChart period hPeriod (measure := measure) configuration
          data analysis family)
        (globalCandidateAHessianConstructiveSameAction period hPeriod (measure := measure)
          configuration data analysis family)) :=
  globalCandidateASevenPhysicalCoreBound_of_blockBounds period hPeriod (measure := measure)
    configuration data analysis
      (globalCandidateAHessianConstructiveChart period hPeriod (measure := measure) configuration
        data analysis family)
      (globalCandidateAHessianConstructiveSameAction period hPeriod (measure := measure)
        configuration data analysis family)
      bounds

/-- H11 common-domain extension generated by the blockwise estimates. -/
def globalCandidateAHessianConstructivePhysicalExtension
    {couplings : GlobalCandidateAActionCouplings}
    {NonNullFace NullFace : Type*}
    [Fintype NonNullFace] [Fintype NullFace]
    {measure : Measure (EffectiveQuotient period hPeriod)}
    (configuration : GlobalGaugeFixedFieldConfiguration period hPeriod)
    (data : GlobalCandidateAActionData period hPeriod configuration.physical
      couplings NonNullFace NullFace)
    (analysis : GlobalAnalysisData period hPeriod configuration.physical)
    (family :
      ProgramPGlobalMinimalPhysicalLocalActionFamilyPhysicalC2Data4D
        period hPeriod configuration data analysis
          (diracGreenClosureMatterRealization period hPeriod
            couplings.matterMassSquared))
    (bounds : GlobalCandidateASevenPhysicalBlockCoreBounds4D period hPeriod
      configuration data analysis
        (globalCandidateAHessianConstructiveChart period hPeriod (measure := measure) configuration
          data analysis family)
        (globalCandidateAHessianConstructiveSameAction period hPeriod (measure := measure)
          configuration data analysis family)) :=
  globalCandidateASevenPhysicalCommonDomainExtension_of_bound period hPeriod (measure := measure)
    configuration data analysis
      (globalCandidateAHessianConstructiveChart period hPeriod (measure := measure) configuration
        data analysis family)
      (globalCandidateAHessianConstructiveSameAction period hPeriod (measure := measure)
        configuration data analysis family)
      (globalCandidateAHessianConstructivePhysicalBound period hPeriod (measure := measure)
        configuration data analysis family bounds)

/-- The third packet converted to the finite-defect parametrix expected by
H12. -/
def globalCandidateAHessianConstructiveParametrix
    {couplings : GlobalCandidateAActionCouplings}
    {NonNullFace NullFace : Type*}
    [Fintype NonNullFace] [Fintype NullFace]
    {measure : Measure (EffectiveQuotient period hPeriod)}
    (configuration : GlobalGaugeFixedFieldConfiguration period hPeriod)
    (data : GlobalCandidateAActionData period hPeriod configuration.physical
      couplings NonNullFace NullFace)
    (analysis : GlobalAnalysisData period hPeriod configuration.physical)
    (family :
      ProgramPGlobalMinimalPhysicalLocalActionFamilyPhysicalC2Data4D
        period hPeriod configuration data analysis
          (diracGreenClosureMatterRealization period hPeriod
            couplings.matterMassSquared))
    (bounds : GlobalCandidateASevenPhysicalBlockCoreBounds4D period hPeriod
      configuration data analysis
        (globalCandidateAHessianConstructiveChart period hPeriod (measure := measure) configuration
          data analysis family)
        (globalCandidateAHessianConstructiveSameAction period hPeriod (measure := measure)
          configuration data analysis family))
    (inverse : GlobalCandidateAFaithfulAugmentedGeneralizedInverse4D period
      hPeriod configuration data analysis
        (globalCandidateAHessianConstructiveChart period hPeriod configuration
          data analysis family)
        (globalCandidateAHessianConstructiveSameAction period hPeriod
          configuration data analysis family)
        (globalCandidateAHessianConstructivePhysicalExtension period hPeriod (measure := measure)
          configuration data analysis family bounds)) :=
  globalCandidateAFaithfulAugmentedFiniteDefectParametrix_of_generalizedInverse
    period hPeriod (measure := measure) configuration data analysis
      (globalCandidateAHessianConstructiveChart period hPeriod (measure := measure) configuration
        data analysis family)
      (globalCandidateAHessianConstructiveSameAction period hPeriod (measure := measure)
        configuration data analysis family)
      (globalCandidateAHessianConstructivePhysicalExtension period hPeriod (measure := measure)
        configuration data analysis family bounds)
      inverse

/-- Repackage the three decomposed packets into the terminal Green-closure
interface. -/
def globalCandidateAHessianConstructiveAnalyticInputs
    {couplings : GlobalCandidateAActionCouplings}
    {NonNullFace NullFace : Type*}
    [Fintype NonNullFace] [Fintype NullFace]
    {measure : Measure (EffectiveQuotient period hPeriod)}
    (configuration : GlobalGaugeFixedFieldConfiguration period hPeriod)
    (data : GlobalCandidateAActionData period hPeriod configuration.physical
      couplings NonNullFace NullFace)
    (analysis : GlobalAnalysisData period hPeriod configuration.physical)
    (family :
      ProgramPGlobalMinimalPhysicalLocalActionFamilyPhysicalC2Data4D
        period hPeriod configuration data analysis
          (diracGreenClosureMatterRealization period hPeriod
            couplings.matterMassSquared))
    (bounds : GlobalCandidateASevenPhysicalBlockCoreBounds4D period hPeriod
      configuration data analysis
        (globalCandidateAHessianConstructiveChart period hPeriod (measure := measure) configuration
          data analysis family)
        (globalCandidateAHessianConstructiveSameAction period hPeriod (measure := measure)
          configuration data analysis family))
    (inverse : GlobalCandidateAFaithfulAugmentedGeneralizedInverse4D period
      hPeriod configuration data analysis
        (globalCandidateAHessianConstructiveChart period hPeriod (measure := measure) configuration
          data analysis family)
        (globalCandidateAHessianConstructiveSameAction period hPeriod (measure := measure)
          configuration data analysis family)
        (globalCandidateAHessianConstructivePhysicalExtension period hPeriod (measure := measure)
          configuration data analysis family bounds)) :
    GlobalCandidateAHessianDiracGreenBoundedInputs4D period hPeriod (measure := measure)
      configuration data analysis where
  family := globalCandidateAHessianConstructiveReducedFamily period hPeriod (measure := measure)
    configuration data analysis family
  physicalBound := globalCandidateAHessianConstructivePhysicalBound period
    hPeriod (measure := measure) configuration data analysis family bounds
  parametrix := globalCandidateAHessianConstructiveParametrix period hPeriod (measure := measure)
    configuration data analysis family bounds inverse

/-- Preferred H14 gate from the three decomposed analytic work packets. -/
def global_candidateA_hessian_constructive_analytic_closure_gate
    {couplings : GlobalCandidateAActionCouplings}
    {NonNullFace NullFace : Type*}
    [Fintype NonNullFace] [Fintype NullFace]
    {measure : Measure (EffectiveQuotient period hPeriod)}
    (configuration : GlobalGaugeFixedFieldConfiguration period hPeriod)
    (data : GlobalCandidateAActionData period hPeriod configuration.physical
      couplings NonNullFace NullFace)
    (analysis : GlobalAnalysisData period hPeriod configuration.physical)
    (einsteinScale : Real)
    (hBoundaryTransverse : HasNoTangentialRadical period hPeriod
      data.plusGravity.metric.metric)
    (family :
      ProgramPGlobalMinimalPhysicalLocalActionFamilyPhysicalC2Data4D
        period hPeriod configuration data analysis
          (diracGreenClosureMatterRealization period hPeriod
            couplings.matterMassSquared))
    (bounds : GlobalCandidateASevenPhysicalBlockCoreBounds4D period hPeriod
      configuration data analysis
        (globalCandidateAHessianConstructiveChart period hPeriod (measure := measure) configuration
          data analysis family)
        (globalCandidateAHessianConstructiveSameAction period hPeriod (measure := measure)
          configuration data analysis family))
    (inverse : GlobalCandidateAFaithfulAugmentedGeneralizedInverse4D period
      hPeriod configuration data analysis
        (globalCandidateAHessianConstructiveChart period hPeriod (measure := measure) configuration
          data analysis family)
        (globalCandidateAHessianConstructiveSameAction period hPeriod (measure := measure)
          configuration data analysis family)
        (globalCandidateAHessianConstructivePhysicalExtension period hPeriod (measure := measure)
          configuration data analysis family bounds)) :=
  global_candidateA_hessian_diracGreen_bounded_closure_gate period hPeriod (measure := measure)
    configuration data analysis einsteinScale hBoundaryTransverse
      (globalCandidateAHessianConstructiveAnalyticInputs period hPeriod (measure := measure)
        configuration data analysis family bounds inverse)

end
end P0EFTJanusProgramPGlobalHessianConstructiveAnalyticClosure4D
end JanusFormal
