import Mathlib.Analysis.Calculus.Deriv.Polynomial
import Mathlib.Analysis.Calculus.Deriv.Comp
import Mathlib.Analysis.Calculus.FDeriv.Mul
import Mathlib.Analysis.Normed.Module.FiniteDimension
import Mathlib.LinearAlgebra.Matrix.Charpoly.Coeff

/-!
# Four-dimensional local density Lie derivative

On the coordinate model `R^4`, this file constructs an affine vector field
`xi(x) = A x + b` and the actual affine first-parameter family

`phi_epsilon(x) = x + epsilon xi(x)`.

Its spatial Frechet derivative has matrix `1 + epsilon A`.  The determinant
of that genuine Jacobian is differentiated at `epsilon = 0` from the exact
determinant polynomial, giving `trace A = div xi`.  For a differentiable
scalar density coefficient `rho`, differentiating

`det(D phi_epsilon) * rho(phi_epsilon(x))`

then gives `xi . grad rho + (div xi) rho`.  The same coefficient is proved to
be the sum of the four actual coordinate derivatives of the flux `rho xi`.

This is a local coordinate calculation on `R^4`.  It does not construct a
global diffeomorphism, an integral over a manifold, Einstein equations, or a
covariant Noether--Bianchi identity.
-/

namespace JanusFormal
namespace P0EFTJanusFourDimensionalDensityLieDerivativeNoether

set_option autoImplicit false

noncomputable section

/-- Fix the canonical normed-field module structure in scalar derivative
statements; this avoids an irrelevant instance diamond with the bare
semiring module on `Real`. -/
local instance realNormedModule : Module Real Real :=
  NormedField.toNormedSpace.toModule

abbrev Index4 := Fin 4
abbrev Point4 := Index4 -> Real
abbrev Matrix4 := Matrix Index4 Index4 Real

/-- Continuous linear action of a real `4 x 4` matrix on coordinate vectors. -/
def matrixAction (linearPart : Matrix4) : Point4 →L[Real] Point4 :=
  LinearMap.toContinuousLinearMap linearPart.mulVecLin

@[simp]
theorem matrixAction_apply (linearPart : Matrix4) (vector : Point4) :
    matrixAction linearPart vector = Matrix.mulVec linearPart vector := by
  rfl

/-- A genuine affine vector field on the coordinate model `R^4`. -/
def affineVectorField
    (linearPart : Matrix4) (translation point : Point4) : Point4 :=
  matrixAction linearPart point + translation

theorem affineVectorField_hasFDerivAt
    (linearPart : Matrix4) (translation point : Point4) :
    HasFDerivAt (affineVectorField linearPart translation)
      (matrixAction linearPart) point := by
  simpa [affineVectorField] using
    (matrixAction linearPart).hasFDerivAt.add_const translation

/-- Affine first-parameter family generated by the displayed vector field. -/
def affineFlow
    (linearPart : Matrix4) (translation : Point4)
    (epsilon : Real) (point : Point4) : Point4 :=
  point + epsilon • affineVectorField linearPart translation point

/-- Spatial Frechet derivative of `affineFlow` at fixed `epsilon`. -/
def affineFlowDerivative
    (linearPart : Matrix4) (epsilon : Real) : Point4 →L[Real] Point4 :=
  ContinuousLinearMap.id Real Point4 + epsilon • matrixAction linearPart

theorem affineFlow_hasFDerivAt
    (linearPart : Matrix4) (translation : Point4)
    (epsilon : Real) (point : Point4) :
    HasFDerivAt (affineFlow linearPart translation epsilon)
      (affineFlowDerivative linearPart epsilon) point := by
  have hId : HasFDerivAt (fun varied : Point4 => varied)
      (ContinuousLinearMap.id Real Point4) point := hasFDerivAt_id point
  have hField := affineVectorField_hasFDerivAt linearPart translation point
  simpa [affineFlow, affineFlowDerivative] using
    hId.add (hField.const_smul epsilon)

/-- Matrix of the actual spatial derivative of the affine family. -/
def affineJacobianMatrix (linearPart : Matrix4) (epsilon : Real) : Matrix4 :=
  1 + epsilon • linearPart

/-- The Frechet derivative above acts by the displayed Jacobian matrix. -/
theorem affineFlowDerivative_apply_eq_jacobian_mulVec
    (linearPart : Matrix4) (epsilon : Real) (variation : Point4) :
    affineFlowDerivative linearPart epsilon variation =
      Matrix.mulVec (affineJacobianMatrix linearPart epsilon) variation := by
  simp [affineFlowDerivative, affineJacobianMatrix,
    Matrix.add_mulVec, Matrix.one_mulVec, Matrix.smul_mulVec]

/-- At a fixed point the affine family has velocity exactly `xi(x)`. -/
theorem affineFlow_epsilon_hasDerivAt
    (linearPart : Matrix4) (translation point : Point4) :
    HasDerivAt (fun epsilon =>
      affineFlow linearPart translation epsilon point)
      (affineVectorField linearPart translation point) 0 := by
  have hScaled := (hasDerivAt_id (0 : Real)).smul_const
    (affineVectorField linearPart translation point)
  change HasDerivAt
    (fun epsilon : Real =>
      point + epsilon • affineVectorField linearPart translation point)
    (affineVectorField linearPart translation point) 0
  simpa only [id_eq, one_smul] using hScaled.const_add point

/-- Determinant of the genuine spatial Jacobian. -/
def jacobianDeterminant (linearPart : Matrix4) (epsilon : Real) : Real :=
  Matrix.det (affineJacobianMatrix linearPart epsilon)

/-- Polynomial collecting terms of order at least two in
`det (1 + epsilon A)`. -/
def determinantRemainderPolynomial (linearPart : Matrix4) : Polynomial Real :=
  (Matrix.det
    (1 + (Polynomial.X : Polynomial Real) •
      linearPart.map Polynomial.C)).divX.divX

theorem jacobianDeterminant_exact_expansion
    (linearPart : Matrix4) (epsilon : Real) :
    jacobianDeterminant linearPart epsilon =
      1 + Matrix.trace linearPart * epsilon +
        (determinantRemainderPolynomial linearPart).eval epsilon * epsilon ^ 2 := by
  simpa [jacobianDeterminant, affineJacobianMatrix,
    determinantRemainderPolynomial] using
    (Matrix.det_one_add_smul epsilon linearPart)

/-- The derivative of the actual Jacobian determinant is the affine-field
divergence.  It is derived from the exact determinant polynomial. -/
theorem jacobianDeterminant_hasDerivAt
    (linearPart : Matrix4) :
    HasDerivAt (jacobianDeterminant linearPart)
      (Matrix.trace linearPart) 0 := by
  let remainder := determinantRemainderPolynomial linearPart
  have hLinear : HasDerivAt
      (fun epsilon : Real => 1 + Matrix.trace linearPart * epsilon)
      (Matrix.trace linearPart) 0 := by
    have hId : HasDerivAt (fun epsilon : Real => epsilon) 1 0 :=
      hasDerivAt_id 0
    simpa using (hId.const_mul (Matrix.trace linearPart)).const_add 1
  have hSquareRaw :=
      (hasDerivAt_id (x := (0 : Real))).mul
        (hasDerivAt_id (x := (0 : Real)))
  have hSquare : HasDerivAt
      ((fun epsilon : Real => epsilon) * fun epsilon : Real => epsilon)
      0 0 := by
    refine (hSquareRaw.congr_of_eventuallyEq
      (Filter.Eventually.of_forall fun _ => rfl)).congr_deriv ?_
    norm_num [id]
  have hRemainder : HasDerivAt
      ((fun epsilon : Real => remainder.eval epsilon) *
        ((fun epsilon : Real => epsilon) * fun epsilon : Real => epsilon))
      0 0 := by
    have hEval : HasDerivAt (fun epsilon : Real => remainder.eval epsilon)
        (remainder.derivative.eval 0) 0 := remainder.hasDerivAt 0
    simpa only [Pi.mul_apply, mul_zero, zero_mul, add_zero] using
      hEval.mul hSquare
  have hExpanded := (hLinear.add hRemainder).congr_deriv (add_zero _)
  refine hExpanded.congr_of_eventuallyEq
    (Filter.Eventually.of_forall ?_)
  intro epsilon
  rw [jacobianDeterminant_exact_expansion]
  simp only [Pi.add_apply, Pi.mul_apply, pow_two, remainder]

/-- Trace/divergence of the affine vector field. -/
def affineDivergence (linearPart : Matrix4) : Real :=
  Matrix.trace linearPart

/-- Euclidean coordinate covector represented by a gradient. -/
def dotCovector (gradient : Point4) : Point4 →L[Real] Real :=
  LinearMap.toContinuousLinearMap
    { toFun := fun variation => ∑ index, gradient index * variation index
      map_add' := by
        intro first second
        simp only [Pi.add_apply, mul_add, Finset.sum_add_distrib]
      map_smul' := by
        intro scalar variation
        simp only [Pi.smul_apply, smul_eq_mul, RingHom.id_apply]
        rw [Finset.mul_sum]
        apply Finset.sum_congr rfl
        intro index _
        ring }

@[simp]
theorem dotCovector_apply (gradient variation : Point4) :
    dotCovector gradient variation =
      ∑ index, gradient index * variation index := by
  rfl

/-- A scalar density coefficient with an actual Frechet derivative represented
by its coordinate gradient. -/
structure DifferentiableScalarDensity where
  coefficient : Point4 -> Real
  gradient : Point4 -> Point4
  coefficient_hasFDerivAt : ∀ point,
    HasFDerivAt coefficient (dotCovector (gradient point)) point

/-- Advective part `xi . grad rho`. -/
def advectiveDensityDerivative
    (density : DifferentiableScalarDensity)
    (linearPart : Matrix4) (translation point : Point4) : Real :=
  dotCovector (density.gradient point)
    (affineVectorField linearPart translation point)

/-- Local weight-one density Lie derivative coefficient. -/
def densityLieDerivative
    (density : DifferentiableScalarDensity)
    (linearPart : Matrix4) (translation point : Point4) : Real :=
  advectiveDensityDerivative density linearPart translation point +
    affineDivergence linearPart * density.coefficient point

/-- Actual pullback coefficient under the affine first-parameter family. -/
def densityPullbackCurve
    (density : DifferentiableScalarDensity)
    (linearPart : Matrix4) (translation point : Point4)
    (epsilon : Real) : Real :=
  jacobianDeterminant linearPart epsilon *
    density.coefficient (affineFlow linearPart translation epsilon point)

/-- Differentiating the actual density pullback yields
`xi . grad rho + (div xi) rho`; the law is not supplied as a hypothesis. -/
theorem densityPullbackCurve_hasDerivAt
    (density : DifferentiableScalarDensity)
    (linearPart : Matrix4) (translation point : Point4) :
    HasDerivAt
      (densityPullbackCurve density linearPart translation point)
      (densityLieDerivative density linearPart translation point) 0 := by
  have hFlow := affineFlow_epsilon_hasDerivAt linearPart translation point
  have hDensityAt : HasFDerivAt density.coefficient
      (dotCovector (density.gradient point))
      (affineFlow linearPart translation 0 point) := by
    simpa [affineFlow] using density.coefficient_hasFDerivAt point
  have hDensity := hDensityAt.comp_hasDerivAt 0 hFlow
  have hJacobian := jacobianDeterminant_hasDerivAt linearPart
  have hProduct := hJacobian.mul hDensity
  refine (hProduct.congr_deriv ?_).congr_of_eventuallyEq
    (Filter.Eventually.of_forall ?_)
  · simp [densityLieDerivative, advectiveDensityDerivative, affineDivergence,
      jacobianDeterminant, affineJacobianMatrix, affineFlow]
    ring
  · intro epsilon
    rfl

/-- Coordinate basis vector. -/
def coordinateBasis (index : Index4) : Point4 :=
  fun other => if other = index then 1 else 0

@[simp]
theorem coordinateBasis_apply_self (index : Index4) :
    coordinateBasis index index = 1 := by
  simp [coordinateBasis]

@[simp]
theorem dotCovector_coordinateBasis (gradient : Point4) (index : Index4) :
    dotCovector gradient (coordinateBasis index) = gradient index := by
  simp [dotCovector, coordinateBasis]

/-- Coordinate line through `point` in the direction `e_index`. -/
def coordinateLine (point : Point4) (index : Index4) (parameter : Real) : Point4 :=
  point + parameter • coordinateBasis index

theorem coordinateLine_hasDerivAt (point : Point4) (index : Index4) :
    HasDerivAt (coordinateLine point index) (coordinateBasis index) 0 := by
  have hScaled := (hasDerivAt_id (0 : Real)).smul_const
    (coordinateBasis index)
  change HasDerivAt
    (fun parameter : Real => point + parameter • coordinateBasis index)
    (coordinateBasis index) 0
  simpa only [id_eq, one_smul] using hScaled.const_add point

/-- Coordinate evaluation covector. -/
def coordinateCovector (index : Index4) : Point4 →L[Real] Real :=
  LinearMap.toContinuousLinearMap
    { toFun := fun vector => vector index
      map_add' := by intro first second; rfl
      map_smul' := by intro scalar vector; rfl }

@[simp]
theorem coordinateCovector_apply (index : Index4) (vector : Point4) :
    coordinateCovector index vector = vector index := by
  rfl

@[simp]
theorem coordinateCovector_matrixAction_basis
    (linearPart : Matrix4) (index : Index4) :
    coordinateCovector index
      (matrixAction linearPart (coordinateBasis index)) =
        linearPart index index := by
  simp [coordinateCovector, matrixAction, coordinateBasis, Matrix.mulVec,
    dotProduct]

/-- The scalar density derivative along an actual coordinate line is the
corresponding gradient component. -/
theorem density_coordinateLine_hasDerivAt
    (density : DifferentiableScalarDensity)
    (point : Point4) (index : Index4) :
    HasDerivAt (fun parameter =>
      density.coefficient (coordinateLine point index parameter))
      (density.gradient point index) 0 := by
  have hDensityAt : HasFDerivAt density.coefficient
      (dotCovector (density.gradient point))
      (coordinateLine point index 0) := by
    simpa [coordinateLine] using density.coefficient_hasFDerivAt point
  have h := hDensityAt.comp_hasDerivAt 0
      (coordinateLine_hasDerivAt point index)
  refine (h.congr_deriv ?_).congr_of_eventuallyEq
    (Filter.Eventually.of_forall ?_)
  · exact dotCovector_coordinateBasis (density.gradient point) index
  · intro parameter
    rfl

/-- The component of the affine field has coordinate derivative `A_ii`. -/
theorem affineVectorFieldComponent_coordinateLine_hasDerivAt
    (linearPart : Matrix4) (translation point : Point4)
    (index : Index4) :
    HasDerivAt (fun parameter =>
      affineVectorField linearPart translation
        (coordinateLine point index parameter) index)
      (linearPart index index) 0 := by
  have hFieldAt : HasFDerivAt
      (affineVectorField linearPart translation) (matrixAction linearPart)
      (coordinateLine point index 0) := by
    simpa [coordinateLine] using
      affineVectorField_hasFDerivAt linearPart translation point
  have hVector := hFieldAt.comp_hasDerivAt 0
    (coordinateLine_hasDerivAt point index)
  have hCoordinate :=
    (coordinateCovector index).hasFDerivAt.comp_hasDerivAt 0 hVector
  refine (hCoordinate.congr_deriv ?_).congr_of_eventuallyEq
    (Filter.Eventually.of_forall ?_)
  · exact coordinateCovector_matrixAction_basis linearPart index
  · intro parameter
    rfl

/-- Physical coordinate flux `rho xi`. -/
def densityFlux
    (density : DifferentiableScalarDensity)
    (linearPart : Matrix4) (translation point : Point4) : Point4 :=
  fun index => density.coefficient point *
    affineVectorField linearPart translation point index

/-- Coefficient of the actual `index`-coordinate derivative of `rho xi^i`. -/
def coordinateFluxDerivative
    (density : DifferentiableScalarDensity)
    (linearPart : Matrix4) (translation point : Point4)
    (index : Index4) : Real :=
  density.gradient point index *
      affineVectorField linearPart translation point index +
    density.coefficient point * linearPart index index

theorem densityFluxComponent_coordinateLine_hasDerivAt
    (density : DifferentiableScalarDensity)
    (linearPart : Matrix4) (translation point : Point4)
    (index : Index4) :
    HasDerivAt (fun parameter =>
      densityFlux density linearPart translation
        (coordinateLine point index parameter) index)
      (coordinateFluxDerivative density linearPart translation point index) 0 := by
  have hDensity := density_coordinateLine_hasDerivAt density point index
  have hField := affineVectorFieldComponent_coordinateLine_hasDerivAt
    linearPart translation point index
  have hProduct := hDensity.mul hField
  refine (hProduct.congr_deriv ?_).congr_of_eventuallyEq
    (Filter.Eventually.of_forall ?_)
  · simp [coordinateFluxDerivative, coordinateLine]
  · intro parameter
    rfl

/-- Sum of the four genuine coordinate flux derivatives. -/
def coordinateFluxDivergence
    (density : DifferentiableScalarDensity)
    (linearPart : Matrix4) (translation point : Point4) : Real :=
  ∑ index, coordinateFluxDerivative density linearPart translation point index

/-- Product-rule divergence identity
`partial_mu (rho xi^mu) = xi^mu partial_mu rho + rho partial_mu xi^mu`. -/
theorem coordinateFluxDivergence_eq_densityLieDerivative
    (density : DifferentiableScalarDensity)
    (linearPart : Matrix4) (translation point : Point4) :
    coordinateFluxDivergence density linearPart translation point =
      densityLieDerivative density linearPart translation point := by
  simp [coordinateFluxDivergence, coordinateFluxDerivative,
    densityLieDerivative, advectiveDensityDerivative, affineDivergence,
    dotCovector, Matrix.trace, Finset.sum_add_distrib,
    ← Finset.mul_sum]
  ring

/-- The actual pullback derivative is therefore the actual coordinate
divergence of the four-component flux. -/
theorem densityPullbackCurve_hasDerivAt_coordinateFluxDivergence
    (density : DifferentiableScalarDensity)
    (linearPart : Matrix4) (translation point : Point4) :
    HasDerivAt
      (densityPullbackCurve density linearPart translation point)
      (coordinateFluxDivergence density linearPart translation point) 0 := by
  exact (densityPullbackCurve_hasDerivAt density linearPart translation point).congr_deriv
    (coordinateFluxDivergence_eq_densityLieDerivative
      density linearPart translation point).symm

end

end P0EFTJanusFourDimensionalDensityLieDerivativeNoether
end JanusFormal
