import JanusFormal.Branches.FundamentalGeometryPVariationalPrinciple.Gates.P0EFTJanusProgramPGlobalHessianCanonicalDenseCoreFrontier4D
import JanusFormal.Branches.FundamentalGeometryPVariationalPrinciple.Gates.P0EFTJanusProgramPGlobalHessianActualKernelChartFrontier4D

/-!
# Actual Candidate-A dense-core H10--H14 frontier

The generic dense-core frontier still accepts an explicit chart and an explicit
H13 same-action bridge.  For Candidate A these are already generated from the
H10-reduced local family.  This facade removes them from the public interface.

After the geometric configuration and local family are fixed, only three
analytic packets remain:

1. one graph-norm bound for the typed core map into the genuine local chart;
2. one equality identifying the seven canonical action Hessians with the H13
   physical core form;
3. the finite actual zero-mode model together with the coercive gap on its
   orthogonal complement.

The output includes the H13 same-action certificate, the canonical H11
extension, H12 Fredholm/index-zero data, the exact zero-mode count and the real
resolvent.
-/

namespace JanusFormal
namespace P0EFTJanusProgramPGlobalHessianCanonicalDenseCoreActualFrontier4D

set_option autoImplicit false
set_option maxHeartbeats 16000000
set_option synthInstance.maxHeartbeats 8000000

noncomputable section

open Set Topology MeasureTheory
open scoped Manifold ContDiff InnerProductSpace
open P0EFTJanusMappingTorusQuotient
open P0EFTJanusMappingTorusSmoothAtlasFrontier
open P0EFTJanusMappingTorusSmoothQuotientManifold
open P0EFTJanusProgramPGlobalFieldSpace4D
open P0EFTJanusProgramPGlobalTypedNonminimalFieldSpace4D
open P0EFTJanusProgramPGlobalCovariantAction4D
open P0EFTJanusProgramPGlobalAnalysisDomain4D
open P0EFTJanusProgramPGlobalLocalVariationalChart4D
open P0EFTJanusProgramPGlobalCandidateAMatterLLSameActionClosure4D
open P0EFTJanusProgramPGlobalCandidateAMinimalPhysicalActionFamilyH10Reduction4D
open P0EFTJanusProgramPGlobalCandidateASevenCanonicalDenseCoreBound4D
open P0EFTJanusProgramPGlobalCandidateAActualZeroModeModel4D
open P0EFTJanusProgramPGlobalHessianActualKernelChartFrontier4D
open P0EFTJanusProgramPGlobalHessianCanonicalDenseCoreFrontier4D
open P0EFTJanusProgramPGlobalHessianDiracGreenBoundedClosure4D

variable (period : Real) (hPeriod : period ≠ 0)

private abbrev EffectiveQuotient :=
  MappingTorus (reflectedSphereData period hPeriod)

local instance effectiveQuotientChartedSpace :
    ChartedSpace CoverModel (EffectiveQuotient period hPeriod) :=
  reflectedSphereQuotientChartedSpace period hPeriod

local instance effectiveQuotientIsManifold :
    IsManifold coverModelWithCorners ω (EffectiveQuotient period hPeriod) :=
  reflectedSphereQuotient_isManifold period hPeriod

local instance effectiveQuotientMeasurableSpace :
    MeasurableSpace (EffectiveQuotient period hPeriod) := borel _

local instance effectiveQuotientBorelSpace :
    BorelSpace (EffectiveQuotient period hPeriod) where
  measurable_eq := rfl

/-- Chart canonically generated by the H10-reduced local family. -/
def globalCandidateACanonicalDenseCoreChart
    {couplings : GlobalCandidateAActionCouplings}
    {NonNullFace NullFace : Type*}
    [Fintype NonNullFace] [Fintype NullFace]
    {measure : Measure (EffectiveQuotient period hPeriod)}
    (configuration : GlobalGaugeFixedFieldConfiguration period hPeriod)
    (data : GlobalCandidateAActionData period hPeriod configuration.physical
      couplings NonNullFace NullFace)
    (analysis : GlobalAnalysisData period hPeriod configuration.physical)
    (einsteinScale : Real)
    (hTransverse : HasNoTangentialRadical period hPeriod
      data.plusGravity.metric.metric)
    (family : ProgramPGlobalMinimalPhysicalLocalActionFamilyH10ReducedData4D
      period hPeriod configuration data analysis
        (diracGreenClosureMatterRealization period hPeriod
          couplings.matterMassSquared) einsteinScale) :=
  globalCandidateAActualKernelChart period hPeriod configuration data analysis
    einsteinScale hTransverse family

/-- H13 bridge canonically generated by the same family. -/
def globalCandidateACanonicalDenseCoreSameAction
    {couplings : GlobalCandidateAActionCouplings}
    {NonNullFace NullFace : Type*}
    [Fintype NonNullFace] [Fintype NullFace]
    {measure : Measure (EffectiveQuotient period hPeriod)}
    (configuration : GlobalGaugeFixedFieldConfiguration period hPeriod)
    (data : GlobalCandidateAActionData period hPeriod configuration.physical
      couplings NonNullFace NullFace)
    (analysis : GlobalAnalysisData period hPeriod configuration.physical)
    (einsteinScale : Real)
    (hTransverse : HasNoTangentialRadical period hPeriod
      data.plusGravity.metric.metric)
    (family : ProgramPGlobalMinimalPhysicalLocalActionFamilyH10ReducedData4D
      period hPeriod configuration data analysis
        (diracGreenClosureMatterRealization period hPeriod
          couplings.matterMassSquared) einsteinScale) :=
  globalCandidateAActualKernelSameAction period hPeriod configuration data
    analysis einsteinScale hTransverse family

/-- Physical H11 extension produced by the actual-family dense-core data. -/
def globalCandidateACanonicalDenseCoreActualPhysicalExtension
    {couplings : GlobalCandidateAActionCouplings}
    {NonNullFace NullFace : Type*}
    [Fintype NonNullFace] [Fintype NullFace]
    {measure : Measure (EffectiveQuotient period hPeriod)}
    (configuration : GlobalGaugeFixedFieldConfiguration period hPeriod)
    (data : GlobalCandidateAActionData period hPeriod configuration.physical
      couplings NonNullFace NullFace)
    (analysis : GlobalAnalysisData period hPeriod configuration.physical)
    (einsteinScale : Real)
    (hTransverse : HasNoTangentialRadical period hPeriod
      data.plusGravity.metric.metric)
    (family : ProgramPGlobalMinimalPhysicalLocalActionFamilyH10ReducedData4D
      period hPeriod configuration data analysis
        (diracGreenClosureMatterRealization period hPeriod
          couplings.matterMassSquared) einsteinScale)
    (chartBound : GlobalCandidateACanonicalDenseCoreChartBound4D period hPeriod
      configuration data analysis
        (globalCandidateACanonicalDenseCoreChart period hPeriod configuration
          data analysis einsteinScale hTransverse family)
        (globalCandidateACanonicalDenseCoreSameAction period hPeriod
          configuration data analysis einsteinScale hTransverse family))
    (agreement : GlobalCandidateASevenCanonicalDenseCoreAgreement4D period
      hPeriod configuration data analysis
        (globalCandidateACanonicalDenseCoreChart period hPeriod configuration
          data analysis einsteinScale hTransverse family)
        (globalCandidateACanonicalDenseCoreSameAction period hPeriod
          configuration data analysis einsteinScale hTransverse family)
        einsteinScale family) :=
  globalCandidateACanonicalDenseCorePhysicalExtension period hPeriod
    configuration data analysis
      (globalCandidateACanonicalDenseCoreChart period hPeriod configuration data
        analysis einsteinScale hTransverse family)
      (globalCandidateACanonicalDenseCoreSameAction period hPeriod configuration
        data analysis einsteinScale hTransverse family)
      einsteinScale family chartBound agreement

/-- Preferred actual-family dense-core terminal gate. -/
def global_candidateA_hessian_canonical_denseCore_actual_frontier_gate
    {couplings : GlobalCandidateAActionCouplings}
    {NonNullFace NullFace : Type*}
    [Fintype NonNullFace] [Fintype NullFace]
    {measure : Measure (EffectiveQuotient period hPeriod)}
    (configuration : GlobalGaugeFixedFieldConfiguration period hPeriod)
    (data : GlobalCandidateAActionData period hPeriod configuration.physical
      couplings NonNullFace NullFace)
    (analysis : GlobalAnalysisData period hPeriod configuration.physical)
    (einsteinScale : Real)
    (hTransverse : HasNoTangentialRadical period hPeriod
      data.plusGravity.metric.metric)
    (family : ProgramPGlobalMinimalPhysicalLocalActionFamilyH10ReducedData4D
      period hPeriod configuration data analysis
        (diracGreenClosureMatterRealization period hPeriod
          couplings.matterMassSquared) einsteinScale)
    (chartBound : GlobalCandidateACanonicalDenseCoreChartBound4D period hPeriod
      configuration data analysis
        (globalCandidateACanonicalDenseCoreChart period hPeriod configuration
          data analysis einsteinScale hTransverse family)
        (globalCandidateACanonicalDenseCoreSameAction period hPeriod
          configuration data analysis einsteinScale hTransverse family))
    (agreement : GlobalCandidateASevenCanonicalDenseCoreAgreement4D period
      hPeriod configuration data analysis
        (globalCandidateACanonicalDenseCoreChart period hPeriod configuration
          data analysis einsteinScale hTransverse family)
        (globalCandidateACanonicalDenseCoreSameAction period hPeriod
          configuration data analysis einsteinScale hTransverse family)
        einsteinScale family)
    (zeroModes : GlobalCandidateAActualZeroModeGap4D period hPeriod configuration
      data analysis
        (globalCandidateACanonicalDenseCoreChart period hPeriod configuration
          data analysis einsteinScale hTransverse family)
        (globalCandidateACanonicalDenseCoreSameAction period hPeriod
          configuration data analysis einsteinScale hTransverse family)
        (globalCandidateACanonicalDenseCoreActualPhysicalExtension period hPeriod
          configuration data analysis einsteinScale hTransverse family chartBound
            agreement)) :=
  let chart := globalCandidateACanonicalDenseCoreChart period hPeriod
    configuration data analysis einsteinScale hTransverse family
  let sameAction := globalCandidateACanonicalDenseCoreSameAction period hPeriod
    configuration data analysis einsteinScale hTransverse family
  let h13 := global_candidateA_h13_matter_ll_same_action_gate period hPeriod
    configuration data analysis chart sameAction
  let analytic := global_candidateA_hessian_canonical_denseCore_frontier_gate
    period hPeriod configuration data analysis chart sameAction einsteinScale
      family chartBound agreement zeroModes
  (h13, analytic)

/-- Only the three genuinely analytic packets remain after fixing the local
Candidate-A family. -/
theorem global_candidateA_hessian_canonical_denseCore_actual_three_inputs :
    Nonempty (Unit × Unit × Unit) :=
  ⟨((), (), ())⟩

end
end P0EFTJanusProgramPGlobalHessianCanonicalDenseCoreActualFrontier4D
end JanusFormal
