import JanusFormal.Branches.FundamentalGeometryPVariationalPrinciple.Gates.P0EFTJanusProgramPGlobalCandidateANormalBoundaryGaussFormGerm4D

/-!
# Componentwise terminal closure of the Candidate-A normal-boundary germ

This module composes the complete algebraic H10 chain:

* tangent, tangent derivative and Christoffel agreement;
* physical unit-normal and ambient-metric agreement;
* induced inverse-metric agreement;
* orientation and induced-density agreement;
* finite contraction, integration and two-sheet multiplicity;
* locality of first and second Fréchet derivatives.

The remaining physical instantiation is therefore a list of componentwise
identities on one common admissible open set.  The action and Hessian equalities
are conclusions, never fields of the input packet.
-/

namespace JanusFormal
namespace P0EFTJanusProgramPGlobalCandidateANormalBoundaryComponentwiseTerminalClosure4D

set_option autoImplicit false
set_option maxHeartbeats 2400000
set_option synthInstance.maxHeartbeats 1200000

noncomputable section

open Filter Set Topology MeasureTheory
open scoped BigOperators Topology

universe u v w z

variable {Variation : Type u}
  [NormedAddCommGroup Variation]
  [NormedSpace Real Variation]

variable {Boundary : Type v}
  [MeasurableSpace Boundary]

variable {TangentIndex : Type w} [Fintype TangentIndex]
variable {AmbientIndex : Type z} [Fintype AmbientIndex]

open P0EFTJanusProgramPGlobalCandidateANormalBoundaryActionGermCalculus4D
open P0EFTJanusProgramPGlobalCandidateANormalBoundaryIntegrandGermClosure4D
open P0EFTJanusProgramPGlobalCandidateANormalBoundaryGHYFactorGerm4D
open P0EFTJanusProgramPGlobalCandidateANormalBoundaryMeanCurvatureGerm4D
open P0EFTJanusProgramPGlobalCandidateANormalBoundaryGaussFormGerm4D

/-- All coefficient-level comparisons needed by H10, sharing the domain of the
covariant-acceleration comparison. -/
structure NormalBoundaryComponentwiseGermData
    (completedTangent historicalTangent :
      Variation → Boundary → TangentIndex → AmbientIndex → Real)
    (completedTangentDerivative historicalTangentDerivative :
      Variation → Boundary → TangentIndex → TangentIndex → AmbientIndex → Real)
    (completedChristoffel historicalChristoffel :
      Variation → Boundary → AmbientIndex → AmbientIndex → AmbientIndex → Real)
    (completedNormal historicalNormal :
      Variation → Boundary → AmbientIndex → Real)
    (completedMetric historicalMetric :
      Variation → Boundary → AmbientIndex → AmbientIndex → Real)
    (completedInverse historicalInverse :
      Variation → Boundary → TangentIndex → TangentIndex → Real)
    (completedOrientation historicalOrientation :
      Variation → Boundary → Real)
    (completedDensity historicalDensity :
      Variation → Boundary → Real)
    (base : Variation) : Type u where
  acceleration : SameCovariantAccelerationGermAt
    completedTangent historicalTangent
    completedTangentDerivative historicalTangentDerivative
    completedChristoffel historicalChristoffel base
  normal_eq : ∀ variation, variation ∈ acceleration.domain →
    ∀ boundary ambient,
      completedNormal variation boundary ambient =
        historicalNormal variation boundary ambient
  metric_eq : ∀ variation, variation ∈ acceleration.domain →
    ∀ boundary row column,
      completedMetric variation boundary row column =
        historicalMetric variation boundary row column
  inverse_eq : ∀ variation, variation ∈ acceleration.domain →
    ∀ boundary first second,
      completedInverse variation boundary first second =
        historicalInverse variation boundary first second
  orientation_eq : ∀ variation, variation ∈ acceleration.domain →
    ∀ boundary,
      completedOrientation variation boundary =
        historicalOrientation variation boundary
  density_eq : ∀ variation, variation ∈ acceleration.domain →
    ∀ boundary,
      completedDensity variation boundary =
        historicalDensity variation boundary

/-- Gauss second-form germ generated by the componentwise packet. -/
def NormalBoundaryComponentwiseGermData.gaussGerm
    {completedTangent historicalTangent :
      Variation → Boundary → TangentIndex → AmbientIndex → Real}
    {completedTangentDerivative historicalTangentDerivative :
      Variation → Boundary → TangentIndex → TangentIndex → AmbientIndex → Real}
    {completedChristoffel historicalChristoffel :
      Variation → Boundary → AmbientIndex → AmbientIndex → AmbientIndex → Real}
    {completedNormal historicalNormal :
      Variation → Boundary → AmbientIndex → Real}
    {completedMetric historicalMetric :
      Variation → Boundary → AmbientIndex → AmbientIndex → Real}
    {completedInverse historicalInverse :
      Variation → Boundary → TangentIndex → TangentIndex → Real}
    {completedOrientation historicalOrientation :
      Variation → Boundary → Real}
    {completedDensity historicalDensity : Variation → Boundary → Real}
    {base : Variation}
    (data : NormalBoundaryComponentwiseGermData
      completedTangent historicalTangent
      completedTangentDerivative historicalTangentDerivative
      completedChristoffel historicalChristoffel
      completedNormal historicalNormal completedMetric historicalMetric
      completedInverse historicalInverse
      completedOrientation historicalOrientation
      completedDensity historicalDensity base) :=
  data.acceleration.toGaussSecondFormGerm data.normal_eq data.metric_eq

/-- Contracted mean-curvature germ generated by the same packet. -/
def NormalBoundaryComponentwiseGermData.meanCurvatureGerm
    {completedTangent historicalTangent :
      Variation → Boundary → TangentIndex → AmbientIndex → Real}
    {completedTangentDerivative historicalTangentDerivative :
      Variation → Boundary → TangentIndex → TangentIndex → AmbientIndex → Real}
    {completedChristoffel historicalChristoffel :
      Variation → Boundary → AmbientIndex → AmbientIndex → AmbientIndex → Real}
    {completedNormal historicalNormal :
      Variation → Boundary → AmbientIndex → Real}
    {completedMetric historicalMetric :
      Variation → Boundary → AmbientIndex → AmbientIndex → Real}
    {completedInverse historicalInverse :
      Variation → Boundary → TangentIndex → TangentIndex → Real}
    {completedOrientation historicalOrientation :
      Variation → Boundary → Real}
    {completedDensity historicalDensity : Variation → Boundary → Real}
    {base : Variation}
    (data : NormalBoundaryComponentwiseGermData
      completedTangent historicalTangent
      completedTangentDerivative historicalTangentDerivative
      completedChristoffel historicalChristoffel
      completedNormal historicalNormal completedMetric historicalMetric
      completedInverse historicalInverse
      completedOrientation historicalOrientation
      completedDensity historicalDensity base) :=
  data.gaussGerm.toContractedMeanCurvatureGerm data.inverse_eq

/-- GHY factor germ generated without an independent mean-curvature field. -/
def NormalBoundaryComponentwiseGermData.ghyFactorGerm
    {completedTangent historicalTangent :
      Variation → Boundary → TangentIndex → AmbientIndex → Real}
    {completedTangentDerivative historicalTangentDerivative :
      Variation → Boundary → TangentIndex → TangentIndex → AmbientIndex → Real}
    {completedChristoffel historicalChristoffel :
      Variation → Boundary → AmbientIndex → AmbientIndex → AmbientIndex → Real}
    {completedNormal historicalNormal :
      Variation → Boundary → AmbientIndex → Real}
    {completedMetric historicalMetric :
      Variation → Boundary → AmbientIndex → AmbientIndex → Real}
    {completedInverse historicalInverse :
      Variation → Boundary → TangentIndex → TangentIndex → Real}
    {completedOrientation historicalOrientation :
      Variation → Boundary → Real}
    {completedDensity historicalDensity : Variation → Boundary → Real}
    {base : Variation}
    (data : NormalBoundaryComponentwiseGermData
      completedTangent historicalTangent
      completedTangentDerivative historicalTangentDerivative
      completedChristoffel historicalChristoffel
      completedNormal historicalNormal completedMetric historicalMetric
      completedInverse historicalInverse
      completedOrientation historicalOrientation
      completedDensity historicalDensity base) :=
  data.meanCurvatureGerm.toGHYFactorGerm data.orientation_eq data.density_eq

/-- Terminal two-sheet action germ generated by componentwise geometry. -/
def NormalBoundaryComponentwiseGermData.twoSheetActionGerm
    {completedTangent historicalTangent :
      Variation → Boundary → TangentIndex → AmbientIndex → Real}
    {completedTangentDerivative historicalTangentDerivative :
      Variation → Boundary → TangentIndex → TangentIndex → AmbientIndex → Real}
    {completedChristoffel historicalChristoffel :
      Variation → Boundary → AmbientIndex → AmbientIndex → AmbientIndex → Real}
    {completedNormal historicalNormal :
      Variation → Boundary → AmbientIndex → Real}
    {completedMetric historicalMetric :
      Variation → Boundary → AmbientIndex → AmbientIndex → Real}
    {completedInverse historicalInverse :
      Variation → Boundary → TangentIndex → TangentIndex → Real}
    {completedOrientation historicalOrientation :
      Variation → Boundary → Real}
    {completedDensity historicalDensity : Variation → Boundary → Real}
    {base : Variation}
    (data : NormalBoundaryComponentwiseGermData
      completedTangent historicalTangent
      completedTangentDerivative historicalTangentDerivative
      completedChristoffel historicalChristoffel
      completedNormal historicalNormal completedMetric historicalMetric
      completedInverse historicalInverse
      completedOrientation historicalOrientation
      completedDensity historicalDensity base)
    (measure : Measure Boundary) :=
  data.ghyFactorGerm.toTwoSheetActionGerm measure

/-- Equality of terminal H10 Hessians generated by the same packet. -/
def NormalBoundaryComponentwiseGermData.twoSheet_second_fderiv_eq
    {completedTangent historicalTangent :
      Variation → Boundary → TangentIndex → AmbientIndex → Real}
    {completedTangentDerivative historicalTangentDerivative :
      Variation → Boundary → TangentIndex → TangentIndex → AmbientIndex → Real}
    {completedChristoffel historicalChristoffel :
      Variation → Boundary → AmbientIndex → AmbientIndex → AmbientIndex → Real}
    {completedNormal historicalNormal :
      Variation → Boundary → AmbientIndex → Real}
    {completedMetric historicalMetric :
      Variation → Boundary → AmbientIndex → AmbientIndex → Real}
    {completedInverse historicalInverse :
      Variation → Boundary → TangentIndex → TangentIndex → Real}
    {completedOrientation historicalOrientation :
      Variation → Boundary → Real}
    {completedDensity historicalDensity : Variation → Boundary → Real}
    {base : Variation}
    (data : NormalBoundaryComponentwiseGermData
      completedTangent historicalTangent
      completedTangentDerivative historicalTangentDerivative
      completedChristoffel historicalChristoffel
      completedNormal historicalNormal completedMetric historicalMetric
      completedInverse historicalInverse
      completedOrientation historicalOrientation
      completedDensity historicalDensity base)
    (measure : Measure Boundary) :=
  (data.twoSheetActionGerm measure).second_fderiv_eq

/-- Public componentwise terminal H10 closure gate. -/
def candidate_a_normal_boundary_componentwise_terminal_closure_gate
    {completedTangent historicalTangent :
      Variation → Boundary → TangentIndex → AmbientIndex → Real}
    {completedTangentDerivative historicalTangentDerivative :
      Variation → Boundary → TangentIndex → TangentIndex → AmbientIndex → Real}
    {completedChristoffel historicalChristoffel :
      Variation → Boundary → AmbientIndex → AmbientIndex → AmbientIndex → Real}
    {completedNormal historicalNormal :
      Variation → Boundary → AmbientIndex → Real}
    {completedMetric historicalMetric :
      Variation → Boundary → AmbientIndex → AmbientIndex → Real}
    {completedInverse historicalInverse :
      Variation → Boundary → TangentIndex → TangentIndex → Real}
    {completedOrientation historicalOrientation :
      Variation → Boundary → Real}
    {completedDensity historicalDensity : Variation → Boundary → Real}
    {base : Variation}
    (data : NormalBoundaryComponentwiseGermData
      completedTangent historicalTangent
      completedTangentDerivative historicalTangentDerivative
      completedChristoffel historicalChristoffel
      completedNormal historicalNormal completedMetric historicalMetric
      completedInverse historicalInverse
      completedOrientation historicalOrientation
      completedDensity historicalDensity base)
    (measure : Measure Boundary) :=
  data.twoSheetActionGerm measure

end
end P0EFTJanusProgramPGlobalCandidateANormalBoundaryComponentwiseTerminalClosure4D
end JanusFormal
