import JanusFormal.Branches.FundamentalGeometryPVariationalPrinciple.Gates.P0EFTJanusMappingTorusCanonicalPhysicalScalarIntrinsicWaveNormalTangentialRieszPDEClosure4D
import JanusFormal.Branches.FundamentalGeometryPVariationalPrinciple.Gates.P0EFTJanusMappingTorusCanonicalPhysicalScalarScalarRemainderEnergyIdentity4D

/-!
# Normal/tangential Riesz PDE closure with scalar energy remainder

For the physical Klein--Gordon operator the lower-order energy remainder is
scalar multiplication in bulk `L²`.  The arbitrary bounded zeroth-order operator
of the generic exact-energy package is therefore replaced by one real
coefficient.

The remaining PDE input is:

* intrinsic wave and normal/tangential Green decomposition;
* `E₁(u) = σ <Au,u> + c ‖u‖²`;
* six bounded coefficient operators for the explicit Cauchy lift.
-/

namespace JanusFormal
namespace P0EFTJanusMappingTorusCanonicalPhysicalScalarIntrinsicWaveNormalTangentialRieszScalarEnergyPDEClosure4D

set_option autoImplicit false
noncomputable section

open Set Topology MeasureTheory
open P0EFTJanusMappingTorusCanonicalPhysicalScalarIntrinsicWaveLocalGreen4D
open P0EFTJanusMappingTorusCanonicalPhysicalScalarIntrinsicWaveNormalTangentialRieszPDEClosure4D
open P0EFTJanusMappingTorusCanonicalPhysicalScalarScalarRemainderEnergyIdentity4D
open P0EFTJanusMappingTorusCanonicalPhysicalScalarCauchyJetEulerBoundedCoefficients4D
open P0EFTJanusMappingTorusScalarHilbertGreenCoreCompletion4D

variable (period : Real) (hPeriod : period ≠ 0)

/-- Preferred PDE data with a scalar zeroth-order energy remainder. -/
structure CanonicalPhysicalScalarIntrinsicWaveNormalTangentialRieszScalarEnergyPDEData
    (massSquared : Real) where
  geometric : CanonicalPhysicalScalarIntrinsicWaveNormalTangentialGreenData
    period hPeriod massSquared
  energyIdentity : geometric.greenCore.ScalarRemainderEnergyIdentityData
    period hPeriod
  eulerCoefficients :
    geometric.toIntrinsicWaveLocalGreenData.toCanonicalLocalDivergenceData.toCanonicalWaveCauchyJetData.toCanonicalCauchyJetCompatibilityData.toCompatibilityData.toCauchyJetGeometricData.CauchyJetEulerSixBoundedCoefficientData
      period hPeriod
      geometric.toIntrinsicWaveLocalGreenData.toCanonicalLocalDivergenceData.toCanonicalWaveCauchyJetData.toCanonicalCauchyJetCompatibilityData.toCompatibilityData.toCauchyJetGeometricData.canonicalEulerProductRealization

namespace CanonicalPhysicalScalarIntrinsicWaveNormalTangentialRieszScalarEnergyPDEData

/-- Conversion to the general normal/tangential Riesz PDE package. -/
def toNormalTangentialRieszPDEData
    (data : CanonicalPhysicalScalarIntrinsicWaveNormalTangentialRieszScalarEnergyPDEData
      period hPeriod massSquared) :
    CanonicalPhysicalScalarIntrinsicWaveNormalTangentialRieszPDEData
      period hPeriod massSquared where
  geometric := data.geometric
  energyIdentity := data.energyIdentity.toExactEnergyGardingIdentityData
    data.geometric.greenCore
  eulerCoefficients := data.eulerCoefficients

/-- Riesz-generated completed boundary triple. -/
def triple
    (data : CanonicalPhysicalScalarIntrinsicWaveNormalTangentialRieszScalarEnergyPDEData
      period hPeriod massSquared) :=
  data.toNormalTangentialRieszPDEData.triple

/-- Riesz-generated completed trace. -/
def completedBoundaryTrace
    (data : CanonicalPhysicalScalarIntrinsicWaveNormalTangentialRieszScalarEnergyPDEData
      period hPeriod massSquared) :=
  data.toNormalTangentialRieszPDEData.completedBoundaryTrace

/-- Bounded right inverse of the completed trace. -/
def completedExtension
    (data : CanonicalPhysicalScalarIntrinsicWaveNormalTangentialRieszScalarEnergyPDEData
      period hPeriod massSquared) :=
  data.toNormalTangentialRieszPDEData.completedExtension

/-- Physical graph-elliptic estimate generated by the scalar remainder identity. -/
def graphEllipticEstimate
    (data : CanonicalPhysicalScalarIntrinsicWaveNormalTangentialRieszScalarEnergyPDEData
      period hPeriod massSquared) :=
  data.energyIdentity.toGraphEllipticEstimate data.geometric.greenCore

/-- Completed extension is a right inverse. -/
theorem completedBoundaryTrace_extension
    (data : CanonicalPhysicalScalarIntrinsicWaveNormalTangentialRieszScalarEnergyPDEData
      period hPeriod massSquared)
    (boundary :
      P0EFTJanusMappingTorusScalarHilbertBoundarySymplectic4D.CanonicalScalarHilbertBoundaryDatum
        (Trace := P0EFTJanusMappingTorusCanonicalPhysicalScalarFirstSheetHilbertTrace4D.CanonicalPhysicalScalarFirstSheetL2 period)) :
    data.completedBoundaryTrace (data.completedExtension boundary) = boundary :=
  data.toNormalTangentialRieszPDEData
    |>.completedBoundaryTrace_extension boundary

/-- Scalar-energy Riesz PDE certificate. -/
theorem certificate
    (data : CanonicalPhysicalScalarIntrinsicWaveNormalTangentialRieszScalarEnergyPDEData
      period hPeriod massSquared) :
    (∀ field test,
      (∫ parameter,
        data.geometric.tangentialDensity field test parameter
        ∂P0EFTJanusMappingTorusCanonicalLatitudeCauchyJetProductCoarea4D.canonicalLatitudeCauchyJetProductMeasure
          period) = 0) ∧
      (∀ field :
        P0EFTJanusMappingTorusSmoothFieldDescent4D.SmoothQuotientField
          period hPeriod Real,
        P0EFTJanusMappingTorusCanonicalPhysicalScalarAutomaticGardingEnergy4D.canonicalPhysicalScalarFirstJetComponentEnergy
            period hPeriod field =
          data.energyIdentity.pairingSign *
              inner Real (data.geometric.greenCore.core.operator field)
                (data.geometric.greenCore.core.inclusion field) +
            data.energyIdentity.zerothCoefficient *
              ‖data.geometric.greenCore.core.inclusion field‖ ^ 2) ∧
      Function.Injective
        (canonicalScalarGreenCoreGraphInclusion
          data.geometric.greenCore.core) ∧
      Function.Surjective data.completedBoundaryTrace ∧
      (∀ boundary,
        data.completedBoundaryTrace
          (data.completedExtension boundary) = boundary) :=
  ⟨data.geometric.toNormalTangentialSplitData.tangential_integral_eq_zero,
    data.energyIdentity.energy_identity,
    data.toNormalTangentialRieszPDEData.rieszBoundaryData.graphInclusion_injective,
    data.toNormalTangentialRieszPDEData.rieszBoundaryData.boundedSmoothExtension
      |>.rieszBoundaryTrace_surjective,
    data.completedBoundaryTrace_extension⟩

end CanonicalPhysicalScalarIntrinsicWaveNormalTangentialRieszScalarEnergyPDEData

end
end P0EFTJanusMappingTorusCanonicalPhysicalScalarIntrinsicWaveNormalTangentialRieszScalarEnergyPDEClosure4D
end JanusFormal
