import Mathlib.Analysis.InnerProductSpace.LinearPMap
import Mathlib.Analysis.InnerProductSpace.Spectrum
import JanusFormal.Branches.FundamentalGeometryPVariationalPrinciple.Gates.P0EFTJanusMappingTorusCanonicalPhysicalScalarIntrinsicH1CoerciveVariationalClosure4D

/-!
# Intrinsic physical H1 elliptic operator

The compact positive response `J J*` is injective with dense range.  Its
inverse on that range is therefore a densely defined positive self-adjoint
operator.  The response itself is its compact zero-resolvent.

This is the canonical intrinsic elliptic graph-energy realization.  It is not
identified with the Lorentzian wave Hessian.
-/

namespace JanusFormal
namespace P0EFTJanusMappingTorusCanonicalPhysicalScalarIntrinsicH1EllipticOperator4D

set_option autoImplicit false
noncomputable section

open Set
open scoped InnerProduct LinearPMap
open P0EFTJanusMappingTorusCanonicalVolumeH1Trace4D
open P0EFTJanusMappingTorusCanonicalPhysicalBulkL2H1Bridge4D
open P0EFTJanusMappingTorusCanonicalPhysicalH1HilbertRenorming4D
open P0EFTJanusMappingTorusCanonicalPhysicalScalarIntrinsicH1CoerciveVariationalClosure4D

variable (period : Real) (hPeriod : period ≠ 0)

private abbrev PhysicalHilbertH1 :=
  CanonicalPhysicalScalarHilbertH1 period hPeriod

private abbrev BulkL2 :=
  CanonicalPhysicalBulkL2 period hPeriod

private abbrev bulkInclusion :=
  canonicalPhysicalScalarHilbertH1ToBulkL2 period hPeriod

private abbrev sourceRepresenter :=
  canonicalPhysicalScalarIntrinsicH1SourceRepresenter period hPeriod

private abbrev bulkResponse :=
  canonicalPhysicalScalarIntrinsicH1BulkResponse period hPeriod

local instance intrinsicEllipticPhysicalH1CompleteSpace :
    CompleteSpace (PhysicalHilbertH1 period hPeriod) :=
  canonicalPhysicalScalarHilbertH1CompleteSpace period hPeriod

/-- The positive bulk response identifies bulk `L²` with its algebraic range. -/
def canonicalPhysicalScalarIntrinsicH1BulkResponseRangeEquiv :
    BulkL2 period hPeriod ≃ₗ[Real]
      LinearMap.range (bulkResponse period hPeriod).toLinearMap :=
  LinearEquiv.ofInjective
    (bulkResponse period hPeriod).toLinearMap
    (canonicalPhysicalScalarIntrinsicH1BulkResponse_injective period hPeriod)

/-- Densely defined inverse of the compact positive graph-energy response. -/
def canonicalPhysicalScalarIntrinsicH1EllipticOperator :
    BulkL2 period hPeriod →ₗ.[Real] BulkL2 period hPeriod where
  domain := LinearMap.range (bulkResponse period hPeriod).toLinearMap
  toFun :=
    (canonicalPhysicalScalarIntrinsicH1BulkResponseRangeEquiv
      period hPeriod).symm.toLinearMap

/-- The operator domain is exactly the range of the compact response. -/
theorem canonicalPhysicalScalarIntrinsicH1EllipticOperator_domain :
    (canonicalPhysicalScalarIntrinsicH1EllipticOperator
        period hPeriod).domain =
      LinearMap.range (bulkResponse period hPeriod).toLinearMap :=
  rfl

/-- Canonical domain element generated by a bulk source. -/
def canonicalPhysicalScalarIntrinsicH1EllipticDomainElement
    (source : BulkL2 period hPeriod) :
    (canonicalPhysicalScalarIntrinsicH1EllipticOperator
      period hPeriod).domain :=
  ⟨bulkResponse period hPeriod source,
    LinearMap.mem_range_self
      (bulkResponse period hPeriod).toLinearMap source⟩

/-- Applying the unbounded elliptic operator to its response returns the
source. -/
@[simp]
theorem canonicalPhysicalScalarIntrinsicH1EllipticOperator_on_response
    (source : BulkL2 period hPeriod) :
    canonicalPhysicalScalarIntrinsicH1EllipticOperator period hPeriod
        (canonicalPhysicalScalarIntrinsicH1EllipticDomainElement
          period hPeriod source) =
      source := by
  change
    (canonicalPhysicalScalarIntrinsicH1BulkResponseRangeEquiv
      period hPeriod).symm
        (canonicalPhysicalScalarIntrinsicH1EllipticDomainElement
          period hPeriod source) = source
  rw [LinearEquiv.symm_apply_eq]
  apply Subtype.ext
  rfl

/-- The compact response recovers every element of the elliptic domain. -/
@[simp]
theorem canonicalPhysicalScalarIntrinsicH1BulkResponse_operator
    (field :
      (canonicalPhysicalScalarIntrinsicH1EllipticOperator
        period hPeriod).domain) :
    bulkResponse period hPeriod
        (canonicalPhysicalScalarIntrinsicH1EllipticOperator
          period hPeriod field) =
      (field : BulkL2 period hPeriod) := by
  change
    (bulkResponse period hPeriod).toLinearMap
        ((canonicalPhysicalScalarIntrinsicH1BulkResponseRangeEquiv
          period hPeriod).symm field) =
      (field : BulkL2 period hPeriod)
  exact LinearEquiv.ofInjective_symm_apply
    (bulkResponse period hPeriod).toLinearMap field

/-- Injectivity and self-adjointness force the positive compact response to
have dense range. -/
theorem canonicalPhysicalScalarIntrinsicH1BulkResponse_denseRange :
    DenseRange (bulkResponse period hPeriod) := by
  let response := bulkResponse period hPeriod
  have hOrthogonal :
      response.toLinearMap.rangeᗮ = (⊥ : Submodule Real (BulkL2 period hPeriod)) := by
    rw [response.orthogonal_range,
      (canonicalPhysicalScalarIntrinsicH1BulkResponse_isSelfAdjoint
        period hPeriod).adjoint_eq]
    exact LinearMap.ker_eq_bot.mpr
      (canonicalPhysicalScalarIntrinsicH1BulkResponse_injective
        period hPeriod)
  have hClosure :
      response.toLinearMap.range.topologicalClosure =
        (⊤ : Submodule Real (BulkL2 period hPeriod)) := by
    rw [← response.toLinearMap.range.orthogonal_orthogonal_eq_closure,
      hOrthogonal, Submodule.bot_orthogonal_eq_top]
  rw [denseRange_iff_closure_range]
  change closure (response.toLinearMap.range : Set (BulkL2 period hPeriod)) =
    Set.univ
  rw [← Submodule.topologicalClosure_coe, hClosure]
  rfl

/-- The intrinsic elliptic operator is densely defined. -/
theorem canonicalPhysicalScalarIntrinsicH1EllipticOperator_domain_dense :
    Dense
      ((canonicalPhysicalScalarIntrinsicH1EllipticOperator
        period hPeriod).domain : Set (BulkL2 period hPeriod)) := by
  rw [canonicalPhysicalScalarIntrinsicH1EllipticOperator_domain,
    LinearMap.coe_range]
  exact canonicalPhysicalScalarIntrinsicH1BulkResponse_denseRange
    period hPeriod

/-- Symmetry of the inverse follows directly from symmetry of the response. -/
theorem canonicalPhysicalScalarIntrinsicH1EllipticOperator_isFormalAdjoint_self :
    (canonicalPhysicalScalarIntrinsicH1EllipticOperator
      period hPeriod).IsFormalAdjoint
      (canonicalPhysicalScalarIntrinsicH1EllipticOperator
        period hPeriod) := by
  intro first second
  have hSymmetric :
      (bulkResponse period hPeriod).toLinearMap.IsSymmetric :=
    (canonicalPhysicalScalarIntrinsicH1BulkResponse_isSelfAdjoint
      period hPeriod).isSymmetric
  calc
    inner Real
        (canonicalPhysicalScalarIntrinsicH1EllipticOperator
          period hPeriod first)
        (second : BulkL2 period hPeriod) =
      inner Real
        (canonicalPhysicalScalarIntrinsicH1EllipticOperator
          period hPeriod first)
        (bulkResponse period hPeriod
          (canonicalPhysicalScalarIntrinsicH1EllipticOperator
            period hPeriod second)) := by
        rw [canonicalPhysicalScalarIntrinsicH1BulkResponse_operator]
    _ = inner Real
        (bulkResponse period hPeriod
          (canonicalPhysicalScalarIntrinsicH1EllipticOperator
            period hPeriod first))
        (canonicalPhysicalScalarIntrinsicH1EllipticOperator
          period hPeriod second) :=
      (hSymmetric
        (canonicalPhysicalScalarIntrinsicH1EllipticOperator
          period hPeriod first)
        (canonicalPhysicalScalarIntrinsicH1EllipticOperator
          period hPeriod second)).symm
    _ = inner Real (first : BulkL2 period hPeriod)
        (canonicalPhysicalScalarIntrinsicH1EllipticOperator
          period hPeriod second) := by
        rw [canonicalPhysicalScalarIntrinsicH1BulkResponse_operator]

/-- The inverse of the positive compact response is genuinely self-adjoint. -/
theorem canonicalPhysicalScalarIntrinsicH1EllipticOperator_isSelfAdjoint :
    IsSelfAdjoint
      (canonicalPhysicalScalarIntrinsicH1EllipticOperator
        period hPeriod) := by
  let operator :=
    canonicalPhysicalScalarIntrinsicH1EllipticOperator period hPeriod
  let response := bulkResponse period hPeriod
  have hDense : Dense (operator.domain : Set (BulkL2 period hPeriod)) :=
    canonicalPhysicalScalarIntrinsicH1EllipticOperator_domain_dense
      period hPeriod
  have hFormal : operator.IsFormalAdjoint operator :=
    canonicalPhysicalScalarIntrinsicH1EllipticOperator_isFormalAdjoint_self
      period hPeriod
  have hOperatorLeAdjoint : operator ≤ operator.adjoint :=
    hFormal.le_adjoint hDense
  have hResponseSymmetric : response.toLinearMap.IsSymmetric :=
    (canonicalPhysicalScalarIntrinsicH1BulkResponse_isSelfAdjoint
      period hPeriod).isSymmetric
  have hAdjointDomain : operator.adjoint.domain ≤ operator.domain := by
    intro state hState
    let adjointState : operator.adjoint.domain := ⟨state, hState⟩
    let image : BulkL2 period hPeriod := operator.adjoint adjointState
    change state ∈ LinearMap.range response.toLinearMap
    refine ⟨image, ?_⟩
    apply ext_inner_left Real
    intro test
    let testState : operator.domain :=
      canonicalPhysicalScalarIntrinsicH1EllipticDomainElement
        period hPeriod test
    have hInner := (LinearPMap.adjoint_isFormalAdjoint hDense).symm
      testState adjointState
    change inner Real (operator testState)
        (adjointState : BulkL2 period hPeriod) =
      inner Real (testState : BulkL2 period hPeriod) image at hInner
    rw [canonicalPhysicalScalarIntrinsicH1EllipticOperator_on_response]
      at hInner
    change inner Real test state = inner Real (response test) image at hInner
    calc
      inner Real test (response image) =
          inner Real (response test) image :=
        (hResponseSymmetric test image).symm
      _ = inner Real test state := hInner.symm
  rw [LinearPMap.isSelfAdjoint_def]
  apply LinearPMap.dExt
    (le_antisymm hAdjointDomain hOperatorLeAdjoint.1)
  intro adjointState operatorState hState
  exact (hOperatorLeAdjoint.2 hState.symm).symm

/-- The intrinsic elliptic operator is closed. -/
theorem canonicalPhysicalScalarIntrinsicH1EllipticOperator_isClosed :
    (canonicalPhysicalScalarIntrinsicH1EllipticOperator
      period hPeriod).IsClosed :=
  (canonicalPhysicalScalarIntrinsicH1EllipticOperator_isSelfAdjoint
    period hPeriod).isClosed

/-- Canonical physical `H¹` regularity representative of an elliptic-domain
field. -/
def canonicalPhysicalScalarIntrinsicH1EllipticRegularityMap :
    (canonicalPhysicalScalarIntrinsicH1EllipticOperator
      period hPeriod).domain →ₗ[Real]
      PhysicalHilbertH1 period hPeriod :=
  (sourceRepresenter period hPeriod).toLinearMap.comp
    (canonicalPhysicalScalarIntrinsicH1EllipticOperator
      period hPeriod).toFun

/-- The regularity representative includes back to the original bulk field. -/
theorem canonicalPhysicalScalarIntrinsicH1EllipticRegularityMap_inclusion
    (field :
      (canonicalPhysicalScalarIntrinsicH1EllipticOperator
        period hPeriod).domain) :
    bulkInclusion period hPeriod
        (canonicalPhysicalScalarIntrinsicH1EllipticRegularityMap
          period hPeriod field) =
      (field : BulkL2 period hPeriod) := by
  exact canonicalPhysicalScalarIntrinsicH1BulkResponse_operator
    period hPeriod field

/-- Quantitative graph regularity: the physical `H¹` norm is controlled by
the elliptic operator value. -/
theorem canonicalPhysicalScalarIntrinsicH1EllipticRegularityMap_norm_le
    (field :
      (canonicalPhysicalScalarIntrinsicH1EllipticOperator
        period hPeriod).domain) :
    ‖canonicalPhysicalScalarIntrinsicH1EllipticRegularityMap
        period hPeriod field‖ ≤
      ‖sourceRepresenter period hPeriod‖ *
        ‖canonicalPhysicalScalarIntrinsicH1EllipticOperator
          period hPeriod field‖ :=
  (sourceRepresenter period hPeriod).le_opNorm
    (canonicalPhysicalScalarIntrinsicH1EllipticOperator
      period hPeriod field)

/-- The intrinsic graph-energy identity on the unbounded operator domain. -/
theorem canonicalPhysicalScalarIntrinsicH1EllipticOperator_energy_identity
    (field :
      (canonicalPhysicalScalarIntrinsicH1EllipticOperator
        period hPeriod).domain) :
    inner Real
        (canonicalPhysicalScalarIntrinsicH1EllipticOperator
          period hPeriod field)
        (field : BulkL2 period hPeriod) =
      ‖sourceRepresenter period hPeriod
        (canonicalPhysicalScalarIntrinsicH1EllipticOperator
          period hPeriod field)‖ ^ 2 := by
  rw [← canonicalPhysicalScalarIntrinsicH1BulkResponse_operator
    period hPeriod field]
  exact canonicalPhysicalScalarIntrinsicH1BulkResponse_pairing
    period hPeriod
      (canonicalPhysicalScalarIntrinsicH1EllipticOperator
        period hPeriod field)

/-- Every nonzero domain field has strictly positive elliptic energy. -/
theorem canonicalPhysicalScalarIntrinsicH1EllipticOperator_pairing_pos
    (field :
      (canonicalPhysicalScalarIntrinsicH1EllipticOperator
        period hPeriod).domain)
    (hField : (field : BulkL2 period hPeriod) ≠ 0) :
    0 < inner Real
      (canonicalPhysicalScalarIntrinsicH1EllipticOperator
        period hPeriod field)
      (field : BulkL2 period hPeriod) := by
  have hSource :
      canonicalPhysicalScalarIntrinsicH1EllipticOperator
          period hPeriod field ≠ 0 := by
    intro hZero
    apply hField
    rw [← canonicalPhysicalScalarIntrinsicH1BulkResponse_operator
      period hPeriod field, hZero]
    exact map_zero _
  rw [← canonicalPhysicalScalarIntrinsicH1BulkResponse_operator
    period hPeriod field]
  exact canonicalPhysicalScalarIntrinsicH1BulkResponse_pairing_pos
    period hPeriod
      (canonicalPhysicalScalarIntrinsicH1EllipticOperator
        period hPeriod field) hSource

/-- Coercivity in bulk norm, with the canonical inclusion norm as explicit
constant. -/
theorem canonicalPhysicalScalarIntrinsicH1EllipticOperator_coercive
    (field :
      (canonicalPhysicalScalarIntrinsicH1EllipticOperator
        period hPeriod).domain) :
    ‖(field : BulkL2 period hPeriod)‖ ^ 2 ≤
      ‖bulkInclusion period hPeriod‖ ^ 2 *
        inner Real
          (canonicalPhysicalScalarIntrinsicH1EllipticOperator
            period hPeriod field)
          (field : BulkL2 period hPeriod) := by
  have hNorm :=
    (bulkInclusion period hPeriod).le_opNorm
      (canonicalPhysicalScalarIntrinsicH1EllipticRegularityMap
        period hPeriod field)
  rw [canonicalPhysicalScalarIntrinsicH1EllipticRegularityMap_inclusion]
    at hNorm
  have hSquare :=
    (sq_le_sq₀
      (norm_nonneg (field : BulkL2 period hPeriod))
      (mul_nonneg
        (norm_nonneg (bulkInclusion period hPeriod))
        (norm_nonneg
          (canonicalPhysicalScalarIntrinsicH1EllipticRegularityMap
            period hPeriod field)))).2 hNorm
  rw [canonicalPhysicalScalarIntrinsicH1EllipticOperator_energy_identity]
  simpa [canonicalPhysicalScalarIntrinsicH1EllipticRegularityMap, mul_pow]
    using hSquare

/-- The unbounded intrinsic elliptic operator is onto bulk `L²`. -/
theorem canonicalPhysicalScalarIntrinsicH1EllipticOperator_surjective :
    Function.Surjective
      (canonicalPhysicalScalarIntrinsicH1EllipticOperator
        period hPeriod) :=
  fun source =>
    ⟨canonicalPhysicalScalarIntrinsicH1EllipticDomainElement
        period hPeriod source,
      canonicalPhysicalScalarIntrinsicH1EllipticOperator_on_response
        period hPeriod source⟩

/-- The unbounded intrinsic elliptic operator is injective. -/
theorem canonicalPhysicalScalarIntrinsicH1EllipticOperator_injective :
    Function.Injective
      (canonicalPhysicalScalarIntrinsicH1EllipticOperator
        period hPeriod) := by
  intro first second hEqual
  apply Subtype.ext
  rw [← canonicalPhysicalScalarIntrinsicH1BulkResponse_operator
      period hPeriod first,
    ← canonicalPhysicalScalarIntrinsicH1BulkResponse_operator
      period hPeriod second,
    hEqual]

/-- The bounded inverse of the intrinsic elliptic operator is compact. -/
theorem canonicalPhysicalScalarIntrinsicH1EllipticOperator_compactInverse :
    IsCompactOperator (bulkResponse period hPeriod) :=
  canonicalPhysicalScalarIntrinsicH1BulkResponse_isCompact_unconditional
    period hPeriod

/-- Nonzero eigenspaces of the compact inverse are finite dimensional. -/
theorem canonicalPhysicalScalarIntrinsicH1EllipticOperator_finiteDimensional_inverseEigenspace
    (eigenvalue : Real) (hEigenvalue : eigenvalue ≠ 0) :
    FiniteDimensional Real
      (Module.End.eigenspace
        (bulkResponse period hPeriod).toLinearMap eigenvalue) :=
  ContinuousLinearMap.finite_dimensional_eigenspace
    (canonicalPhysicalScalarIntrinsicH1EllipticOperator_compactInverse
      period hPeriod)
    eigenvalue hEigenvalue

/-- Spectral completeness of the compact inverse. -/
theorem canonicalPhysicalScalarIntrinsicH1EllipticOperator_spectral_complete :
    (⨆ eigenvalue : Real,
      Module.End.eigenspace
        (bulkResponse period hPeriod).toLinearMap eigenvalue)ᗮ = ⊥ :=
  ContinuousLinearMap.orthogonalComplement_iSup_eigenspaces_eq_bot
    (canonicalPhysicalScalarIntrinsicH1EllipticOperator_compactInverse
      period hPeriod)
    (canonicalPhysicalScalarIntrinsicH1BulkResponse_isSelfAdjoint
      period hPeriod).isSymmetric

/-- Every genuine eigenvalue of the compact inverse is strictly positive. -/
theorem canonicalPhysicalScalarIntrinsicH1BulkResponse_eigenvalue_pos
    (eigenvalue : Real) (field : BulkL2 period hPeriod)
    (hField : field ≠ 0)
    (hEigenfield :
      bulkResponse period hPeriod field = eigenvalue • field) :
    0 < eigenvalue := by
  have hPairing :=
    canonicalPhysicalScalarIntrinsicH1BulkResponse_pairing_pos
      period hPeriod field hField
  rw [hEigenfield, real_inner_smul_right,
    real_inner_self_eq_norm_sq] at hPairing
  have hNorm : 0 < ‖field‖ ^ 2 :=
    sq_pos_of_pos (norm_pos_iff.mpr hField)
  nlinarith

/-- Full unconditional elliptic/coercive closure certificate. -/
theorem canonicalPhysicalScalarIntrinsicH1EllipticOperator_certificate :
    Dense
        ((canonicalPhysicalScalarIntrinsicH1EllipticOperator
          period hPeriod).domain : Set (BulkL2 period hPeriod)) ∧
      IsSelfAdjoint
        (canonicalPhysicalScalarIntrinsicH1EllipticOperator
          period hPeriod) ∧
      (canonicalPhysicalScalarIntrinsicH1EllipticOperator
        period hPeriod).IsClosed ∧
      Function.Bijective
        (canonicalPhysicalScalarIntrinsicH1EllipticOperator
          period hPeriod) ∧
      IsCompactOperator (bulkResponse period hPeriod) ∧
      (∀ field :
          (canonicalPhysicalScalarIntrinsicH1EllipticOperator
            period hPeriod).domain,
        inner Real
            (canonicalPhysicalScalarIntrinsicH1EllipticOperator
              period hPeriod field)
            (field : BulkL2 period hPeriod) =
          ‖sourceRepresenter period hPeriod
            (canonicalPhysicalScalarIntrinsicH1EllipticOperator
              period hPeriod field)‖ ^ 2) ∧
      (∀ field :
          (canonicalPhysicalScalarIntrinsicH1EllipticOperator
            period hPeriod).domain,
        ‖(field : BulkL2 period hPeriod)‖ ^ 2 ≤
          ‖bulkInclusion period hPeriod‖ ^ 2 *
            inner Real
              (canonicalPhysicalScalarIntrinsicH1EllipticOperator
                period hPeriod field)
              (field : BulkL2 period hPeriod)) := by
  exact
    ⟨canonicalPhysicalScalarIntrinsicH1EllipticOperator_domain_dense
        period hPeriod,
      canonicalPhysicalScalarIntrinsicH1EllipticOperator_isSelfAdjoint
        period hPeriod,
      canonicalPhysicalScalarIntrinsicH1EllipticOperator_isClosed
        period hPeriod,
      ⟨canonicalPhysicalScalarIntrinsicH1EllipticOperator_injective
          period hPeriod,
        canonicalPhysicalScalarIntrinsicH1EllipticOperator_surjective
          period hPeriod⟩,
      canonicalPhysicalScalarIntrinsicH1EllipticOperator_compactInverse
        period hPeriod,
      canonicalPhysicalScalarIntrinsicH1EllipticOperator_energy_identity
        period hPeriod,
      canonicalPhysicalScalarIntrinsicH1EllipticOperator_coercive
        period hPeriod⟩

end
end P0EFTJanusMappingTorusCanonicalPhysicalScalarIntrinsicH1EllipticOperator4D
end JanusFormal
