import JanusFormal.Branches.FundamentalGeometryPVariationalPrinciple.Gates.P0EFTJanusProgramPCandidateAFiveSectorOrthogonalOffDiagonalPhysicalSmallness4D
import JanusFormal.Branches.FundamentalGeometryPVariationalPrinciple.Gates.P0EFTJanusProgramPQuadraticGardingOperatorLowerBound4D

/-!
# Operator lower bound from the one-form five-sector margin

The quadratic estimate with margin

`sectorFloor - ‖B_off‖ - C_physical`

is identified with one displayed operator energy.  Cauchy--Schwarz gives the
operator lower bound and injectivity.
-/

namespace JanusFormal
namespace P0EFTJanusProgramPCandidateAFiveSectorOrthogonalOffDiagonalOperatorGarding4D

set_option autoImplicit false
set_option maxHeartbeats 4600000
set_option synthInstance.maxHeartbeats 2300000

noncomputable section

open scoped InnerProductSpace
open P0EFTJanusProgramPCandidateAFiveSectorOrthogonalOffDiagonalPhysicalSmallness4D
open P0EFTJanusProgramPQuadraticGardingOperatorLowerBound4D

variable {E : Type*}
  [NormedAddCommGroup E] [NormedSpace Real E]
  [InnerProductSpace Real E]

variable (Component : CandidateAZeroModeSector → Type*)
  [∀ sector, NormedAddCommGroup (Component sector)]
  [∀ sector, NormedSpace Real (Component sector)]
  [∀ sector, InnerProductSpace Real (Component sector)]

/-- One-form finite margin identified with one bounded operator. -/
structure CandidateAFiveSectorOrthogonalOffDiagonalOperatorGardingData
    (operator : E →L[Real] E) where
  finiteMargin : CandidateAFiveSectorOrthogonalOffDiagonalPhysicalSmallnessData
    (E := E) Component
  energy_upper : ∀ vector,
    finiteMargin.totalEnergy vector ≤ ‖vector‖ * ‖operator vector‖

namespace CandidateAFiveSectorOrthogonalOffDiagonalOperatorGardingData

/-- Generic quadratic-to-operator packet. -/
def toQuadraticOperatorData
    {operator : E →L[Real] E}
    (data : CandidateAFiveSectorOrthogonalOffDiagonalOperatorGardingData
      (Component := Component) operator) :
    QuadraticGardingOperatorData operator where
  margin := data.finiteMargin.margin Component
  margin_pos :=
    (data.finiteMargin
      |>.candidateA_five_sector_orthogonal_offDiagonal_physical_smallness_gate
        Component).1
  energy := data.finiteMargin.totalEnergy
  energy_lower :=
    (data.finiteMargin
      |>.candidateA_five_sector_orthogonal_offDiagonal_physical_smallness_gate
        Component).2
  energy_upper := data.energy_upper

/-- Explicit operator lower bound. -/
theorem lowerBound
    {operator : E →L[Real] E}
    (data : CandidateAFiveSectorOrthogonalOffDiagonalOperatorGardingData
      (Component := Component) operator)
    (vector : E) :
    data.finiteMargin.margin Component * ‖vector‖ ≤ ‖operator vector‖ :=
  data.toQuadraticOperatorData Component |>.lowerBound vector

/-- Injectivity generated by the positive one-form margin. -/
theorem injective
    {operator : E →L[Real] E}
    (data : CandidateAFiveSectorOrthogonalOffDiagonalOperatorGardingData
      (Component := Component) operator) :
    Function.Injective operator :=
  data.toQuadraticOperatorData Component |>.injective

/-- Public one-form operator checkpoint. -/
theorem candidateA_five_sector_orthogonal_offDiagonal_operator_garding_gate
    (operator : E →L[Real] E)
    (data : CandidateAFiveSectorOrthogonalOffDiagonalOperatorGardingData
      (Component := Component) operator) :
    (∀ vector,
      data.finiteMargin.margin Component * ‖vector‖ ≤ ‖operator vector‖) ∧
      Function.Injective operator :=
  ⟨data.lowerBound Component, data.injective Component⟩

end CandidateAFiveSectorOrthogonalOffDiagonalOperatorGardingData

end
end P0EFTJanusProgramPCandidateAFiveSectorOrthogonalOffDiagonalOperatorGarding4D
end JanusFormal
