import JanusFormal.Branches.FundamentalGeometryPVariationalPrinciple.Gates.P0EFTJanusProgramPCandidateAFiveSectorPrincipalOperatorGarding4D
import JanusFormal.Branches.FundamentalGeometryPVariationalPrinciple.Gates.P0EFTJanusProgramPCandidateAFiveSectorCrossFormOperatorGarding4D

/-!
# Adapter from projected-principal to cross-form operator Gårding

The projected-principal packet already constructs the ten cross forms.  This
adapter exposes the older cross-form operator packet required by the first
finite-margin actual-kernel bridge.
-/

namespace JanusFormal
namespace P0EFTJanusProgramPCandidateAFiveSectorPrincipalOperatorAdapter4D

set_option autoImplicit false
noncomputable section

open P0EFTJanusProgramPCandidateAFiveSectorPrincipalOperatorGarding4D
open P0EFTJanusProgramPCandidateAFiveSectorCrossFormOperatorGarding4D

variable {E : Type*}
  [NormedAddCommGroup E] [NormedSpace Real E]

/-- Forget that the cross forms were generated by one principal form. -/
def CandidateAFiveSectorPrincipalOperatorGardingData.toCrossFormOperatorGardingData
    {operator : E →L[Real] E}
    (data : CandidateAFiveSectorPrincipalOperatorGardingData operator) :
    CandidateAFiveSectorCrossFormOperatorGardingData operator where
  finiteMargin := data.finiteMargin.toCrossFormPhysicalSmallnessData
  energy_upper := data.energy_upper

/-- Public compatibility checkpoint. -/
def candidateA_principal_operator_to_cross_form_gate
    (operator : E →L[Real] E)
    (data : CandidateAFiveSectorPrincipalOperatorGardingData operator) :
    CandidateAFiveSectorCrossFormOperatorGardingData operator :=
  data.toCrossFormOperatorGardingData

end
end P0EFTJanusProgramPCandidateAFiveSectorPrincipalOperatorAdapter4D
end JanusFormal
