import JanusFormal.Branches.FundamentalGeometryPVariationalPrinciple.Gates.P0EFTJanusMappingTorusCanonicalPhysicalScalarFirstSheetBoundaryExtension4D
import JanusFormal.Branches.FundamentalGeometryPVariationalPrinciple.Gates.P0EFTJanusMappingTorusCanonicalPhysicalScalarSquaredGraphEstimates4D
import JanusFormal.Branches.FundamentalGeometryPVariationalPrinciple.Gates.P0EFTJanusMappingTorusScalarBoundaryCauchyGraphExtension4D
import JanusFormal.Branches.FundamentalGeometryPVariationalPrinciple.Gates.P0EFTJanusMappingTorusScalarGreenCoreInteriorDensity4D

/-!
# Constructing the physical scalar boundary triple from concrete estimates

This file eliminates the abstract density and surjectivity fields from the
physical boundary-completion step.

A concrete construction consists of:

* a smooth Cauchy extension realizing dense smooth value and normal cores;
* the bulk Green--Stokes identity for the concrete Euler operator;
* squared graph-elliptic and normal-trace estimates;
* a dense interior smooth core with zero Cauchy trace;
* a graph-norm estimate for the smooth Cauchy extension.

The first item constructs the dense physical Green core.  The squared estimates
construct the paired graph-boundary trace.  The interior core gives minimal-core
density and closability.  The bounded smooth Cauchy extension prolongs to a
right inverse of the completed trace.  Together they install the corrected
surjective completed boundary triple.
-/

namespace JanusFormal
namespace P0EFTJanusMappingTorusCanonicalPhysicalScalarFirstSheetBoundaryTripleConstruction4D

set_option autoImplicit false
noncomputable section

open Set Topology
open P0EFTJanusMappingTorusSmoothFieldDescent4D
open P0EFTJanusMappingTorusCanonicalPhysicalH1TraceCoareaClosed4D
open P0EFTJanusMappingTorusCanonicalPhysicalScalarFirstSheetHilbertTrace4D
open P0EFTJanusMappingTorusCanonicalPhysicalScalarFirstSheetGreenCore4D
open P0EFTJanusMappingTorusCanonicalPhysicalScalarFirstSheetBoundaryExtension4D
open P0EFTJanusMappingTorusCanonicalPhysicalScalarSquaredGraphEstimates4D
open P0EFTJanusMappingTorusScalarHilbertGreenCoreCompletion4D
open P0EFTJanusMappingTorusScalarBoundarySmoothExtensionDensity4D
open P0EFTJanusMappingTorusScalarBoundaryCauchyGraphExtension4D
open P0EFTJanusMappingTorusScalarGreenCoreInteriorDensity4D

universe x y z

variable (period : Real) (hPeriod : period ≠ 0)

/-- Complete constructive boundary-triple input. -/
structure CanonicalPhysicalScalarBoundaryTripleConstructionData
    (massSquared : Real)
    (ValueCore : Type x) (NormalCore : Type y) (InteriorCore : Type z)
    [AddCommGroup ValueCore] [Module Real ValueCore]
    [AddCommGroup NormalCore] [Module Real NormalCore]
    [AddCommGroup InteriorCore] [Module Real InteriorCore] where
  smooth : CanonicalPhysicalScalarSmoothCauchyExtensionData
    period hPeriod massSquared ValueCore NormalCore
  elliptic :
    (smooth.greenCoreData).SquaredGraphEllipticEstimate period hPeriod
  normal :
    (smooth.greenCoreData).SquaredNormalGraphEstimate period hPeriod
  interior : CanonicalScalarGreenCoreInteriorDensityData
    (InteriorCore := InteriorCore) (smooth.greenCoreData).core
  extensionConstant : Real
  extensionConstant_nonnegative : 0 ≤ extensionConstant
  extensionGraphBound : ∀ data : ValueCore × NormalCore,
    ‖canonicalScalarGreenCoreToGraph (smooth.greenCoreData).core
        (smooth.extension data)‖ ≤
      extensionConstant *
        ‖canonicalScalarBoundaryCorePairEmbedding
          smooth.valueEmbedding smooth.normalEmbedding data‖

namespace CanonicalPhysicalScalarBoundaryTripleConstructionData

/-- Correct physical Green core generated by the smooth Cauchy extension. -/
def green
    {ValueCore : Type x} {NormalCore : Type y} {InteriorCore : Type z}
    [AddCommGroup ValueCore] [Module Real ValueCore]
    [AddCommGroup NormalCore] [Module Real NormalCore]
    [AddCommGroup InteriorCore] [Module Real InteriorCore]
    (construction : CanonicalPhysicalScalarBoundaryTripleConstructionData
      period hPeriod massSquared ValueCore NormalCore InteriorCore) :=
  construction.smooth.greenCoreData

/-- Linear graph-elliptic estimate extracted from its squared form. -/
def ellipticEstimate
    {ValueCore : Type x} {NormalCore : Type y} {InteriorCore : Type z}
    [AddCommGroup ValueCore] [Module Real ValueCore]
    [AddCommGroup NormalCore] [Module Real NormalCore]
    [AddCommGroup InteriorCore] [Module Real InteriorCore]
    (construction : CanonicalPhysicalScalarBoundaryTripleConstructionData
      period hPeriod massSquared ValueCore NormalCore InteriorCore) :
    construction.green.GraphEllipticEstimate period hPeriod :=
  construction.elliptic.toGraphEllipticEstimate construction.green

/-- Linear normal graph estimate extracted from its squared form. -/
def normalEstimate
    {ValueCore : Type x} {NormalCore : Type y} {InteriorCore : Type z}
    [AddCommGroup ValueCore] [Module Real ValueCore]
    [AddCommGroup NormalCore] [Module Real NormalCore]
    [AddCommGroup InteriorCore] [Module Real InteriorCore]
    (construction : CanonicalPhysicalScalarBoundaryTripleConstructionData
      period hPeriod massSquared ValueCore NormalCore InteriorCore) :
    construction.green.NormalGraphEstimate period hPeriod :=
  construction.normal.toNormalGraphEstimate construction.green

/-- Paired physical graph-boundary estimate. -/
def traceBound
    {ValueCore : Type x} {NormalCore : Type y} {InteriorCore : Type z}
    [AddCommGroup ValueCore] [Module Real ValueCore]
    [AddCommGroup NormalCore] [Module Real NormalCore]
    [AddCommGroup InteriorCore] [Module Real InteriorCore]
    (construction : CanonicalPhysicalScalarBoundaryTripleConstructionData
      period hPeriod massSquared ValueCore NormalCore InteriorCore) :
    HasCanonicalScalarHilbertGreenCoreBoundaryGraphBound
      construction.green.core :=
  construction.green.boundaryGraphBound period hPeriod
    (canonicalPhysicalScalarLatitudeCoareaTheorem period hPeriod)
    construction.ellipticEstimate construction.normalEstimate

/-- Generic bounded smooth Cauchy extension. -/
def boundedSmoothExtension
    {ValueCore : Type x} {NormalCore : Type y} {InteriorCore : Type z}
    [AddCommGroup ValueCore] [Module Real ValueCore]
    [AddCommGroup NormalCore] [Module Real NormalCore]
    [AddCommGroup InteriorCore] [Module Real InteriorCore]
    (construction : CanonicalPhysicalScalarBoundaryTripleConstructionData
      period hPeriod massSquared ValueCore NormalCore InteriorCore) :
    CanonicalScalarBoundedSmoothCauchyExtensionData
      (ValueCore := ValueCore) (NormalCore := NormalCore)
      construction.green.core where
  smooth := construction.smooth.toGenericExtension
  constant := construction.extensionConstant
  nonnegative := construction.extensionConstant_nonnegative
  graph_bound := construction.extensionGraphBound

/-- Minimal-core density generated by the dense interior core. -/
theorem minimalCoreDense
    {ValueCore : Type x} {NormalCore : Type y} {InteriorCore : Type z}
    [AddCommGroup ValueCore] [Module Real ValueCore]
    [AddCommGroup NormalCore] [Module Real NormalCore]
    [AddCommGroup InteriorCore] [Module Real InteriorCore]
    (construction : CanonicalPhysicalScalarBoundaryTripleConstructionData
      period hPeriod massSquared ValueCore NormalCore InteriorCore) :
    construction.green.MinimalCoreDense period hPeriod :=
  construction.interior.minimalCoreDense

/-- Surjectivity of the completed physical Cauchy trace. -/
theorem completedTraceSurjective
    {ValueCore : Type x} {NormalCore : Type y} {InteriorCore : Type z}
    [AddCommGroup ValueCore] [Module Real ValueCore]
    [AddCommGroup NormalCore] [Module Real NormalCore]
    [AddCommGroup InteriorCore] [Module Real InteriorCore]
    (construction : CanonicalPhysicalScalarBoundaryTripleConstructionData
      period hPeriod massSquared ValueCore NormalCore InteriorCore) :
    Function.Surjective
      (canonicalScalarGreenCoreCompletedBoundaryTrace
        construction.green.core construction.traceBound) :=
  construction.boundedSmoothExtension.completedBoundaryTrace_surjective
    construction.traceBound

/-- Completed physical boundary-triple input constructed from the concrete
estimates. -/
def completedInputs
    {ValueCore : Type x} {NormalCore : Type y} {InteriorCore : Type z}
    [AddCommGroup ValueCore] [Module Real ValueCore]
    [AddCommGroup NormalCore] [Module Real NormalCore]
    [AddCommGroup InteriorCore] [Module Real InteriorCore]
    (construction : CanonicalPhysicalScalarBoundaryTripleConstructionData
      period hPeriod massSquared ValueCore NormalCore InteriorCore) :
    construction.green.CompletedBoundaryTripleInputs period hPeriod where
  coarea := canonicalPhysicalScalarLatitudeCoareaTheorem period hPeriod
  elliptic := construction.ellipticEstimate
  normal := construction.normalEstimate
  minimalDense := construction.minimalCoreDense
  completedTraceSurjective := construction.completedTraceSurjective

/-- Correct completed physical boundary triple. -/
def triple
    {ValueCore : Type x} {NormalCore : Type y} {InteriorCore : Type z}
    [AddCommGroup ValueCore] [Module Real ValueCore]
    [AddCommGroup NormalCore] [Module Real NormalCore]
    [AddCommGroup InteriorCore] [Module Real InteriorCore]
    (construction : CanonicalPhysicalScalarBoundaryTripleConstructionData
      period hPeriod massSquared ValueCore NormalCore InteriorCore) :=
  (construction.completedInputs).triple construction.green

/-- Completed Cauchy extension with quantitative graph norm control. -/
def completedExtension
    {ValueCore : Type x} {NormalCore : Type y} {InteriorCore : Type z}
    [AddCommGroup ValueCore] [Module Real ValueCore]
    [AddCommGroup NormalCore] [Module Real NormalCore]
    [AddCommGroup InteriorCore] [Module Real InteriorCore]
    (construction : CanonicalPhysicalScalarBoundaryTripleConstructionData
      period hPeriod massSquared ValueCore NormalCore InteriorCore) :=
  construction.boundedSmoothExtension.completedExtension

/-- Full constructive physical boundary-triple certificate. -/
theorem certificate
    {ValueCore : Type x} {NormalCore : Type y} {InteriorCore : Type z}
    [AddCommGroup ValueCore] [Module Real ValueCore]
    [AddCommGroup NormalCore] [Module Real NormalCore]
    [AddCommGroup InteriorCore] [Module Real InteriorCore]
    (construction : CanonicalPhysicalScalarBoundaryTripleConstructionData
      period hPeriod massSquared ValueCore NormalCore InteriorCore) :
    DenseRange
        (smoothCanonicalPhysicalScalarFirstSheetCauchyTrace
          period hPeriod) ∧
      construction.green.MinimalCoreDense period hPeriod ∧
      Function.Injective
        (canonicalScalarGreenCoreGraphInclusion construction.green.core) ∧
      Function.Surjective
        (canonicalScalarGreenCoreCompletedBoundaryTrace
          construction.green.core construction.traceBound) ∧
      (∀ boundary,
        canonicalScalarGreenCoreCompletedBoundaryTrace
            construction.green.core construction.traceBound
            (construction.completedExtension boundary) = boundary) :=
  ⟨construction.smooth.boundaryTrace_denseRange,
    construction.minimalCoreDense,
    (construction.triple).inclusion_injective,
    construction.completedTraceSurjective,
    construction.boundedSmoothExtension.completedBoundaryTrace_extension
      construction.traceBound⟩

end CanonicalPhysicalScalarBoundaryTripleConstructionData

end
end P0EFTJanusMappingTorusCanonicalPhysicalScalarFirstSheetBoundaryTripleConstruction4D
end JanusFormal
