import JanusFormal.Branches.FundamentalGeometryPVariationalPrinciple.Gates.P0EFTJanusProgramPFiveSectorHilbertCoordinatesResolution4D
import JanusFormal.Branches.FundamentalGeometryPVariationalPrinciple.Gates.P0EFTJanusProgramPFiniteCommutingProjectionKernelResolution4D
import JanusFormal.Branches.FundamentalGeometryPVariationalPrinciple.Gates.P0EFTJanusProgramPGlobalHessianPreferredFiveSectorNaturalFamilyCommutation4D

/-!
# Natural Candidate-A sector resolution on every actual kernel

The represented Candidate-A family commutes at every parameter with the five
projectors generated by the one H12/H14 Hilbert decomposition.  Combining that
commutation theorem with the generic kernel-restriction construction produces
an exact self-adjoint five-sector resolution on every true kernel `ker H_a`.

No moving kernel subspace or auxiliary completion is chosen here: the kernel
projectors are simply the ambient physical projectors with their codomain
restricted using the genuine equation `H_a P_s = P_s H_a`.
-/

namespace JanusFormal
namespace P0EFTJanusProgramPGlobalHessianPreferredFiveSectorNaturalKernelResolution4D

set_option autoImplicit false
set_option maxHeartbeats 54000000
set_option synthInstance.maxHeartbeats 27000000
noncomputable section

open Set Topology MeasureTheory
open scoped BigOperators Manifold ContDiff InnerProductSpace
open P0EFTJanusMappingTorusQuotient
open P0EFTJanusMappingTorusSmoothAtlasFrontier
open P0EFTJanusMappingTorusSmoothQuotientManifold
open P0EFTJanusProgramPGlobalFieldSpace4D
open P0EFTJanusProgramPGlobalTypedNonminimalFieldSpace4D
open P0EFTJanusProgramPGlobalCovariantAction4D
open P0EFTJanusProgramPGlobalAnalysisDomain4D
open P0EFTJanusProgramPGlobalCandidateAMatterLLSameActionClosure4D
open P0EFTJanusProgramPGlobalCandidateAMinimalPhysicalActionFamilyH10Reduction4D
open P0EFTJanusProgramPGlobalCandidateACanonicalSixDenseCore4D
open P0EFTJanusProgramPFiniteCommutingProjectionKernelComplement4D
open P0EFTJanusProgramPFiniteCommutingProjectionKernelResolution4D
open P0EFTJanusProgramPFiveSectorHilbertCoordinates4D
open P0EFTJanusProgramPFiveSectorHilbertCoordinatesResolution4D
open P0EFTJanusProgramPGlobalHessianPreferredFiveSectorNamedKernelFamilyClosure4D
open P0EFTJanusProgramPGlobalHessianPreferredFiveSectorNaturalEllipticSectorOperatorFamily4D
open P0EFTJanusProgramPGlobalHessianPreferredFiveSectorNaturalFamilyCommutation4D
open P0EFTJanusProgramPDenseCoreChartBilinearBound4D

variable (period : Real) (hPeriod : period ≠ 0)

private abbrev EffectiveQuotient :=
  MappingTorus (reflectedSphereData period hPeriod)
local instance effectiveQuotientChartedSpace :
    ChartedSpace CoverModel (EffectiveQuotient period hPeriod) :=
  reflectedSphereQuotientChartedSpace period hPeriod
local instance effectiveQuotientIsManifold :
    IsManifold coverModelWithCorners ω (EffectiveQuotient period hPeriod) :=
  reflectedSphereQuotient_isManifold period hPeriod
local instance effectiveQuotientMeasurableSpace :
    MeasurableSpace (EffectiveQuotient period hPeriod) := borel _
local instance effectiveQuotientBorelSpace :
    BorelSpace (EffectiveQuotient period hPeriod) where measurable_eq := rfl

variable
    {couplings : GlobalCandidateAActionCouplings}
    {NonNullFace NullFace : Type*}
    [Fintype NonNullFace] [Fintype NullFace]
    {configuration : GlobalGaugeFixedFieldConfiguration period hPeriod}
    {data : GlobalCandidateAActionData period hPeriod configuration.physical
      couplings NonNullFace NullFace}
    {analysis : GlobalAnalysisData period hPeriod configuration.physical}
    {einsteinScale : Real}
    {hTransverse : HasNoTangentialRadical period hPeriod
      data.plusGravity.metric.metric}
    {family : ProgramPGlobalMinimalPhysicalLocalActionFamilyH10ReducedData4D
      period hPeriod configuration data analysis
        (diracGreenClosureMatterRealization period hPeriod
          couplings.matterMassSquared) einsteinScale}
    {chartBound : DenseCoreChartMapBound
      (globalCandidateASevenPhysicalCoreEmbedding period hPeriod configuration
        data analysis)
      (globalCandidateACanonicalSixCoreToChart period hPeriod configuration data
        analysis
          (globalCandidateAActualKernelChart period hPeriod configuration data
            analysis einsteinScale hTransverse family)
          (globalCandidateAActualKernelSameAction period hPeriod configuration
            data analysis einsteinScale hTransverse family))}
    {Metric Abelian Matter Longitudinal Boundary : Type*}
    [NormedAddCommGroup Metric] [InnerProductSpace Real Metric]
    [NormedAddCommGroup Abelian] [InnerProductSpace Real Abelian]
    [NormedAddCommGroup Matter] [InnerProductSpace Real Matter]
    [NormedAddCommGroup Longitudinal] [InnerProductSpace Real Longitudinal]
    [NormedAddCommGroup Boundary] [InnerProductSpace Real Boundary]
    {ZeroMode : Type*} [Fintype ZeroMode] [DecidableEq ZeroMode]
    {fold : Fold} {Index : Type*}

private abbrev Coordinates
    (input : GlobalHessianPreferredFiveSectorNamedKernelFamilyClosure4D
      period hPeriod configuration data analysis einsteinScale hTransverse family
        chartBound Metric Abelian Matter Longitudinal Boundary ZeroMode fold Index) :=
  preferredCandidateAFiveSectorHilbertCoordinates period hPeriod input

/-- All-parameter ambient commuting resolution for the actual Candidate-A
operator family. -/
def naturalCandidateACommutingResolution
    (input : GlobalHessianPreferredFiveSectorNamedKernelFamilyClosure4D
      period hPeriod configuration data analysis einsteinScale hTransverse family
        chartBound Metric Abelian Matter Longitudinal Boundary ZeroMode fold Index)
    (natural : GlobalHessianPreferredFiveSectorNaturalEllipticSectorOperatorFamily4D
      period hPeriod input)
    (parameter : Real) :
    FiniteCommutingProjectionResolutionData
      (Sector := FivePhysicalSector)
      (input.familyIndex.baseFamily.actualOperator parameter) where
  resolution := fiveSectorHilbertSelfAdjointResolution
    (Coordinates period hPeriod input)
  commute := by
    intro sector vector
    exact actualOperator_commutes_sectorProjector period hPeriod input natural
      parameter sector vector

/-- Canonical physical projector restricted to `ker H_parameter`. -/
def naturalCandidateAKernelProjection
    (input : GlobalHessianPreferredFiveSectorNamedKernelFamilyClosure4D
      period hPeriod configuration data analysis einsteinScale hTransverse family
        chartBound Metric Abelian Matter Longitudinal Boundary ZeroMode fold Index)
    (natural : GlobalHessianPreferredFiveSectorNaturalEllipticSectorOperatorFamily4D
      period hPeriod input)
    (parameter : Real) (sector : FivePhysicalSector) :
    (input.familyIndex.baseFamily.actualOperator parameter).ker →L[Real]
      (input.familyIndex.baseFamily.actualOperator parameter).ker :=
  (naturalCandidateACommutingResolution period hPeriod input natural parameter).
    kernelProjection sector

@[simp]
theorem naturalCandidateAKernelProjection_apply_val
    (input : GlobalHessianPreferredFiveSectorNamedKernelFamilyClosure4D
      period hPeriod configuration data analysis einsteinScale hTransverse family
        chartBound Metric Abelian Matter Longitudinal Boundary ZeroMode fold Index)
    (natural : GlobalHessianPreferredFiveSectorNaturalEllipticSectorOperatorFamily4D
      period hPeriod input)
    (parameter : Real) (sector : FivePhysicalSector)
    (vector : (input.familyIndex.baseFamily.actualOperator parameter).ker) :
    (naturalCandidateAKernelProjection period hPeriod input natural parameter
      sector vector).1 =
      (Coordinates period hPeriod input).sectorProjector sector vector.1 :=
  rfl

/-- Exact self-adjoint five-sector resolution on one actual kernel fibre. -/
def naturalCandidateAKernelResolution
    (input : GlobalHessianPreferredFiveSectorNamedKernelFamilyClosure4D
      period hPeriod configuration data analysis einsteinScale hTransverse family
        chartBound Metric Abelian Matter Longitudinal Boundary ZeroMode fold Index)
    (natural : GlobalHessianPreferredFiveSectorNaturalEllipticSectorOperatorFamily4D
      period hPeriod input)
    (parameter : Real) :
    FiniteSelfAdjointProjectionResolutionData
      (Sector := FivePhysicalSector)
      (E := (input.familyIndex.baseFamily.actualOperator parameter).ker) :=
  (naturalCandidateACommutingResolution period hPeriod input natural parameter).
    toKernelResolution

/-- The basepoint H12 named basis is fixed by its inherited physical kernel
projector. -/
theorem basepointKernelBasis_fixed_by_sector
    (input : GlobalHessianPreferredFiveSectorNamedKernelFamilyClosure4D
      period hPeriod configuration data analysis einsteinScale hTransverse family
        chartBound Metric Abelian Matter Longitudinal Boundary ZeroMode fold Index)
    (natural : GlobalHessianPreferredFiveSectorNaturalEllipticSectorOperatorFamily4D
      period hPeriod input)
    (mode : ZeroMode) :
    naturalCandidateAKernelProjection period hPeriod input natural 0
        (namedModeFiveSector period hPeriod input mode)
        (input.kernels.basis 0 mode) =
      input.kernels.basis 0 mode := by
  apply Subtype.ext
  rw [naturalCandidateAKernelProjection_apply_val]
  exact basis_fixed_by_sector_zero period hPeriod input mode

/-- Public natural Candidate-A actual-kernel resolution checkpoint. -/
theorem global_hessian_preferred_five_sector_natural_kernel_resolution_gate
    (input : GlobalHessianPreferredFiveSectorNamedKernelFamilyClosure4D
      period hPeriod configuration data analysis einsteinScale hTransverse family
        chartBound Metric Abelian Matter Longitudinal Boundary ZeroMode fold Index)
    (natural : GlobalHessianPreferredFiveSectorNaturalEllipticSectorOperatorFamily4D
      period hPeriod input) :
    (∀ parameter vector,
      (∑ sector : FivePhysicalSector,
        naturalCandidateAKernelProjection period hPeriod input natural parameter
          sector vector) = vector) ∧
    (∀ parameter sector vector,
      naturalCandidateAKernelProjection period hPeriod input natural parameter
          sector
          (naturalCandidateAKernelProjection period hPeriod input natural
            parameter sector vector) =
        naturalCandidateAKernelProjection period hPeriod input natural parameter
          sector vector) ∧
    (∀ parameter vector,
      ‖vector‖ ^ 2 =
        ∑ sector : FivePhysicalSector,
          ‖naturalCandidateAKernelProjection period hPeriod input natural
            parameter sector vector‖ ^ 2) ∧
    (∀ mode,
      naturalCandidateAKernelProjection period hPeriod input natural 0
          (namedModeFiveSector period hPeriod input mode)
          (input.kernels.basis 0 mode) =
        input.kernels.basis 0 mode) :=
  ⟨fun parameter =>
      (naturalCandidateAKernelResolution period hPeriod input natural parameter).
        sum_projection,
    fun parameter =>
      (naturalCandidateAKernelResolution period hPeriod input natural parameter).
        projection_idempotent,
    fun parameter =>
      (naturalCandidateAKernelResolution period hPeriod input natural parameter).
        norm_sq_decomposition,
    basepointKernelBasis_fixed_by_sector period hPeriod input natural⟩

end
end P0EFTJanusProgramPGlobalHessianPreferredFiveSectorNaturalKernelResolution4D
end JanusFormal