import JanusFormal.Branches.FundamentalGeometryPVariationalPrinciple.Gates.P0EFTJanusProgramPGlobalHessianPreferredFiveSectorSpectralCutReferenceAtlas4D

/-!
# Terminal preferred Candidate-A family-index closure

This façade collects the preferred route after the pointwise H14 theorem.
Starting from one Candidate-A actual family, a unitary trivialization of its
varying true kernel complements, intrinsic logarithmic traces and an
operator-generated family of spectral-cut references, it exposes one coherent
certificate containing:

* the intrinsic H14--Quillen closure at the physical basepoint;
* the genuine reduced family and its uniformly bounded Green operators;
* a common real resolvent interval and absence of reduced zero crossings;
* the Bismut--Freed connection `-Tr(GH' - G_ref H'_ref)`;
* a determinant-line atlas generated by reference changes;
* the additive reference-trace cocycle and multiplicative determinant cocycle;
* the circle clutching and unitary phase holonomy.

No independently supplied scalar atlas or second reduced operator family is
retained in this terminal route.
-/

namespace JanusFormal
namespace P0EFTJanusProgramPGlobalHessianPreferredFiveSectorFamilyIndexClosure4D

set_option autoImplicit false
set_option maxHeartbeats 22000000
set_option synthInstance.maxHeartbeats 11000000

noncomputable section

open Set Topology MeasureTheory
open scoped BigOperators Manifold ContDiff InnerProductSpace
open P0EFTJanusCircleQuillenMetricFlatConnection
open P0EFTJanusMappingTorusQuotient
open P0EFTJanusMappingTorusSmoothAtlasFrontier
open P0EFTJanusMappingTorusSmoothQuotientManifold
open P0EFTJanusProgramPGlobalFieldSpace4D
open P0EFTJanusProgramPGlobalTypedNonminimalFieldSpace4D
open P0EFTJanusProgramPGlobalCovariantAction4D
open P0EFTJanusProgramPGlobalAnalysisDomain4D
open P0EFTJanusProgramPGlobalCandidateAMatterLLSameActionClosure4D
open P0EFTJanusProgramPGlobalCandidateAMinimalPhysicalActionFamilyH10Reduction4D
open P0EFTJanusProgramPGlobalCandidateACanonicalSixDenseCore4D
open P0EFTJanusProgramPGlobalHessianPreferredFiveSectorBismutFreedFamily4D
open P0EFTJanusProgramPGlobalHessianPreferredFiveSectorIntrinsicQuillenClosure4D
open P0EFTJanusProgramPGlobalHessianPreferredFiveSectorSpectralCutReferenceAtlas4D
open P0EFTJanusProgramPIntrinsicBismutFreedReferenceAtlas4D
open P0EFTJanusProgramPIntrinsicRelativeTraceReferenceCocycle4D
open P0EFTJanusProgramPRelativeHeatMellinZetaFamily4D
open P0EFTJanusProgramPRelativeZetaDeterminantConnection4D
open P0EFTJanusProgramPRelativeZetaDeterminantCocycle4D
open P0EFTJanusProgramPRelativeZetaDeterminantLineAtlas4D
open P0EFTJanusProgramPRelativeZetaFinitePartFamily4D
open P0EFTJanusProgramPSelfAdjointUniformGapFamilyResolvent4D
open P0EFTJanusProgramPDenseCoreChartBilinearBound4D

variable (period : Real) (hPeriod : period ≠ 0)

private abbrev EffectiveQuotient :=
  MappingTorus (reflectedSphereData period hPeriod)

local instance effectiveQuotientChartedSpace :
    ChartedSpace CoverModel (EffectiveQuotient period hPeriod) :=
  reflectedSphereQuotientChartedSpace period hPeriod

local instance effectiveQuotientIsManifold :
    IsManifold coverModelWithCorners ω (EffectiveQuotient period hPeriod) :=
  reflectedSphereQuotient_isManifold period hPeriod

local instance effectiveQuotientMeasurableSpace :
    MeasurableSpace (EffectiveQuotient period hPeriod) := borel _

local instance effectiveQuotientBorelSpace :
    BorelSpace (EffectiveQuotient period hPeriod) where
  measurable_eq := rfl

/-- Terminal family-index certificate. -/
structure GlobalHessianPreferredFiveSectorFamilyIndexClosureCertificate4D
    {couplings : GlobalCandidateAActionCouplings}
    {NonNullFace NullFace : Type*}
    [Fintype NonNullFace] [Fintype NullFace]
    {configuration : GlobalGaugeFixedFieldConfiguration period hPeriod}
    {data : GlobalCandidateAActionData period hPeriod configuration.physical
      couplings NonNullFace NullFace}
    {analysis : GlobalAnalysisData period hPeriod configuration.physical}
    {einsteinScale : Real}
    {hTransverse : HasNoTangentialRadical period hPeriod
      data.plusGravity.metric.metric}
    {family : ProgramPGlobalMinimalPhysicalLocalActionFamilyH10ReducedData4D
      period hPeriod configuration data analysis
        (diracGreenClosureMatterRealization period hPeriod
          couplings.matterMassSquared) einsteinScale}
    {chartBound : DenseCoreChartMapBound
      (globalCandidateASevenPhysicalCoreEmbedding period hPeriod configuration
        data analysis)
      (globalCandidateACanonicalSixCoreToChart period hPeriod configuration data
        analysis
          (globalCandidateAActualKernelChart period hPeriod configuration data
            analysis einsteinScale hTransverse family)
          (globalCandidateAActualKernelSameAction period hPeriod configuration
            data analysis einsteinScale hTransverse family))}
    {Metric Abelian Matter Longitudinal Boundary : Type*}
    [NormedAddCommGroup Metric] [InnerProductSpace Real Metric]
    [NormedAddCommGroup Abelian] [InnerProductSpace Real Abelian]
    [NormedAddCommGroup Matter] [InnerProductSpace Real Matter]
    [NormedAddCommGroup Longitudinal] [InnerProductSpace Real Longitudinal]
    [NormedAddCommGroup Boundary] [InnerProductSpace Real Boundary]
    {ZeroMode : Type*} [Fintype ZeroMode] [DecidableEq ZeroMode]
    {fold : Fold} {Index : Type*}
    (input : GlobalHessianPreferredFiveSectorSpectralCutReferenceAtlas4D period
      hPeriod configuration data analysis einsteinScale hTransverse family
        chartBound Metric Abelian Matter Longitudinal Boundary ZeroMode fold
          Index) : Prop where
  spectralCut :
    GlobalHessianPreferredFiveSectorSpectralCutReferenceAtlasOutput4D input
  baseFamily :
    GlobalHessianPreferredFiveSectorBismutFreedFamilyOutput4D input.baseFamily
  intrinsicQuillen :
    GlobalHessianPreferredFiveSectorIntrinsicQuillenClosureCertificate4D
      input.generatedQuillenAtlas
  baseDeterminant :
    input.referenceAtlas.localDeterminant
        input.baseFamily.quillen.baseIndex 0 =
      input.baseFamily.quillen.intrinsicFamily.basepoint.determinant
  noReducedCrossing : UniformGapFamilyNoCrossingCertificate
    input.baseFamily.familyIndex.actualDifferentiable.analytic
  uniformResolvent : ∀ parameter spectralParameter,
    ∀ hSpectral : |spectralParameter| <
      input.baseFamily.familyIndex.actualDifferentiable.analytic.gap,
      ‖uniformGapFamilyResolvent
          input.baseFamily.familyIndex.actualDifferentiable.analytic parameter
          spectralParameter hSpectral‖ ≤
        (input.baseFamily.familyIndex.actualDifferentiable.analytic.gap -
          |spectralParameter|)⁻¹
  localLogDerivative : ∀ index parameter,
    (input.localFamily index).finitePartFamily.logDerivative parameter =
      input.operatorCocycle.localTrace index parameter
  referenceTraceCocycle : ∀ first second third parameter,
    input.operatorCocycle.referenceChangeTrace first second parameter +
        input.operatorCocycle.referenceChangeTrace second third parameter =
      input.operatorCocycle.referenceChangeTrace first third parameter
  transitionDerivative : ∀ first second parameter,
    relativeZetaTransitionDerivative input.referenceAtlas.zetaAtlas first second
        parameter =
      (input.operatorCocycle.referenceChangeTrace first second parameter :
          Complex) *
        input.referenceAtlas.transition first second parameter
  determinantCocycle : ∀ first second third parameter,
    input.referenceAtlas.transition second third parameter *
        input.referenceAtlas.transition first second parameter =
      input.referenceAtlas.transition first third parameter
  connectionGauge : ∀ first second parameter,
    relativeZetaTransitionDerivative input.referenceAtlas.zetaAtlas first second
          parameter +
        relativeZetaConnectionCoefficient
            (input.localFamily second).toZetaFamily parameter *
          input.referenceAtlas.transition first second parameter =
      input.referenceAtlas.transition first second parameter *
        relativeZetaConnectionCoefficient
          (input.localFamily first).toZetaFamily parameter
  circleTrace : ∀ parameter,
    input.baseFamily.familyIndex.relativeTrace.trace parameter =
      -circleQuillenConnectionCoefficient fold
  phaseHolonomy :
    circleQuillenClosedHolonomy fold =
      relativeZetaFinitePartPhase
          input.baseFamily.familyIndex.zetaFamily.toFinitePartComparison 0 /
        relativeZetaFinitePartPhase
          input.baseFamily.familyIndex.zetaFamily.toFinitePartComparison 1

/-- Construct the terminal family-index certificate. -/
def globalHessianPreferredFiveSectorFamilyIndexClosureCertificate
    {couplings : GlobalCandidateAActionCouplings}
    {NonNullFace NullFace : Type*}
    [Fintype NonNullFace] [Fintype NullFace]
    {configuration : GlobalGaugeFixedFieldConfiguration period hPeriod}
    {data : GlobalCandidateAActionData period hPeriod configuration.physical
      couplings NonNullFace NullFace}
    {analysis : GlobalAnalysisData period hPeriod configuration.physical}
    {einsteinScale : Real}
    {hTransverse : HasNoTangentialRadical period hPeriod
      data.plusGravity.metric.metric}
    {family : ProgramPGlobalMinimalPhysicalLocalActionFamilyH10ReducedData4D
      period hPeriod configuration data analysis
        (diracGreenClosureMatterRealization period hPeriod
          couplings.matterMassSquared) einsteinScale}
    {chartBound : DenseCoreChartMapBound
      (globalCandidateASevenPhysicalCoreEmbedding period hPeriod configuration
        data analysis)
      (globalCandidateACanonicalSixCoreToChart period hPeriod configuration data
        analysis
          (globalCandidateAActualKernelChart period hPeriod configuration data
            analysis einsteinScale hTransverse family)
          (globalCandidateAActualKernelSameAction period hPeriod configuration
            data analysis einsteinScale hTransverse family))}
    {Metric Abelian Matter Longitudinal Boundary : Type*}
    [NormedAddCommGroup Metric] [InnerProductSpace Real Metric]
    [NormedAddCommGroup Abelian] [InnerProductSpace Real Abelian]
    [NormedAddCommGroup Matter] [InnerProductSpace Real Matter]
    [NormedAddCommGroup Longitudinal] [InnerProductSpace Real Longitudinal]
    [NormedAddCommGroup Boundary] [InnerProductSpace Real Boundary]
    {ZeroMode : Type*} [Fintype ZeroMode] [DecidableEq ZeroMode]
    {fold : Fold} {Index : Type*}
    (input : GlobalHessianPreferredFiveSectorSpectralCutReferenceAtlas4D period
      hPeriod configuration data analysis einsteinScale hTransverse family
        chartBound Metric Abelian Matter Longitudinal Boundary ZeroMode fold
          Index) :
    GlobalHessianPreferredFiveSectorFamilyIndexClosureCertificate4D input where
  spectralCut := input.close
  baseFamily := input.baseFamily.close
  intrinsicQuillen :=
    globalHessianPreferredFiveSectorIntrinsicQuillenClosureCertificate
      input.generatedQuillenAtlas
  baseDeterminant := input.baseDeterminant_eq_intrinsic period hPeriod
  noReducedCrossing := input.baseFamily.noCrossing
  uniformResolvent :=
    input.baseFamily.familyIndex.actualDifferentiable.analytic.
      uniformGapFamilyResolvent_opNorm_le
  localLogDerivative :=
    input.referenceAtlas.finitePart_logDerivative_eq_localTrace
  referenceTraceCocycle := input.operatorCocycle.referenceChangeTrace_cocycle
  transitionDerivative :=
    input.referenceAtlas.transitionDerivative_eq_referenceChangeTrace
  determinantCocycle := input.referenceAtlas.transition_cocycle
  connectionGauge := input.referenceAtlas.transition_connectionGauge
  circleTrace :=
    input.baseFamily.toCircleTraceBridge.relativeTrace_eq_neg_circleCoefficient
  phaseHolonomy := input.baseFamily.toCircleTraceBridge.closedHolonomy_eq_phase_ratio

/-- Public terminal preferred family-index checkpoint. -/
theorem global_hessian_preferred_five_sector_family_index_closure_gate
    {couplings : GlobalCandidateAActionCouplings}
    {NonNullFace NullFace : Type*}
    [Fintype NonNullFace] [Fintype NullFace]
    {configuration : GlobalGaugeFixedFieldConfiguration period hPeriod}
    {data : GlobalCandidateAActionData period hPeriod configuration.physical
      couplings NonNullFace NullFace}
    {analysis : GlobalAnalysisData period hPeriod configuration.physical}
    {einsteinScale : Real}
    {hTransverse : HasNoTangentialRadical period hPeriod
      data.plusGravity.metric.metric}
    {family : ProgramPGlobalMinimalPhysicalLocalActionFamilyH10ReducedData4D
      period hPeriod configuration data analysis
        (diracGreenClosureMatterRealization period hPeriod
          couplings.matterMassSquared) einsteinScale}
    {chartBound : DenseCoreChartMapBound
      (globalCandidateASevenPhysicalCoreEmbedding period hPeriod configuration
        data analysis)
      (globalCandidateACanonicalSixCoreToChart period hPeriod configuration data
        analysis
          (globalCandidateAActualKernelChart period hPeriod configuration data
            analysis einsteinScale hTransverse family)
          (globalCandidateAActualKernelSameAction period hPeriod configuration
            data analysis einsteinScale hTransverse family))}
    {Metric Abelian Matter Longitudinal Boundary : Type*}
    [NormedAddCommGroup Metric] [InnerProductSpace Real Metric]
    [NormedAddCommGroup Abelian] [InnerProductSpace Real Abelian]
    [NormedAddCommGroup Matter] [InnerProductSpace Real Matter]
    [NormedAddCommGroup Longitudinal] [InnerProductSpace Real Longitudinal]
    [NormedAddCommGroup Boundary] [InnerProductSpace Real Boundary]
    {ZeroMode : Type*} [Fintype ZeroMode] [DecidableEq ZeroMode]
    {fold : Fold} {Index : Type*}
    (input : GlobalHessianPreferredFiveSectorSpectralCutReferenceAtlas4D period
      hPeriod configuration data analysis einsteinScale hTransverse family
        chartBound Metric Abelian Matter Longitudinal Boundary ZeroMode fold
          Index) :
    GlobalHessianPreferredFiveSectorFamilyIndexClosureCertificate4D input :=
  globalHessianPreferredFiveSectorFamilyIndexClosureCertificate input

end
end P0EFTJanusProgramPGlobalHessianPreferredFiveSectorFamilyIndexClosure4D
end JanusFormal
