import JanusFormal.Branches.FundamentalGeometryPVariationalPrinciple.Gates.P0EFTJanusMappingTorusCanonicalLatitudeCauchyJetAllWindingDeck4D

/-!
# Descent of the latitude Cauchy jet to the collar quotient

The all-winding gluing theorem makes the local Cauchy extension constant on the
integer deck orbits of the model collar.  This file installs the corresponding
`ℤ` action and performs the quotient descent explicitly.
-/

namespace JanusFormal
namespace P0EFTJanusMappingTorusCanonicalLatitudeCauchyJetCollarQuotient4D

set_option autoImplicit false
noncomputable section

open P0EFTJanusMappingTorusCanonicalPhysicalH1TraceBound4D
open P0EFTJanusMappingTorusCanonicalLatitudeCauchyJetProfiles4D
open P0EFTJanusMappingTorusCanonicalLatitudeCauchyJetDeckGluing4D
open P0EFTJanusMappingTorusCanonicalLatitudeCauchyJetAllWindingDeck4D

/-- Model collar before quotienting. -/
def CanonicalLatitudeCauchyCollar (_period : Real) :=
  CanonicalLatitudeBase × Real

/-- Integer deck action generated by time translation and normal reversal. -/
instance (period : Real) : VAdd Int (CanonicalLatitudeCauchyCollar period) where
  vadd winding parameter :=
    (canonicalLatitudeCollarDeckEquiv period ^ winding) parameter

instance (period : Real) : AddAction Int (CanonicalLatitudeCauchyCollar period) where
  zero_vadd parameter := by
    change (canonicalLatitudeCollarDeckEquiv period ^ (0 : Int)) parameter = parameter
    simp
  add_vadd first second parameter := by
    change (canonicalLatitudeCollarDeckEquiv period ^ (first + second)) parameter =
      (canonicalLatitudeCollarDeckEquiv period ^ first)
        ((canonicalLatitudeCollarDeckEquiv period ^ second) parameter)
    rw [zpow_add]
    rfl

/-- Orbit quotient of the model latitude collar. -/
abbrev CanonicalLatitudeCauchyCollarQuotient (period : Real) :=
  AddAction.orbitRel.Quotient Int (CanonicalLatitudeCauchyCollar period)

/-- Quotient projection of the model collar. -/
def canonicalLatitudeCauchyCollarMk (period : Real) :
    CanonicalLatitudeCauchyCollar period →
      CanonicalLatitudeCauchyCollarQuotient period :=
  Quotient.mk (AddAction.orbitRel Int (CanonicalLatitudeCauchyCollar period))

/-- Boundary data carrying the correct generator parity. -/
structure CanonicalLatitudeDeckCauchyData (period : Real) where
  value : CanonicalLatitudeBase → Real
  normal : CanonicalLatitudeBase → Real
  value_periodic : CanonicalLatitudeValueDeckPeriodic period value
  normal_antiperiodic : CanonicalLatitudeNormalDeckAntiperiodic period normal

namespace CanonicalLatitudeDeckCauchyData

variable {period : Real}

/-- Local exact Cauchy extension before quotienting. -/
def localExtension
    (data : CanonicalLatitudeDeckCauchyData period)
    (parameter : CanonicalLatitudeCauchyCollar period) : Real :=
  canonicalLatitudeLocalCauchyExtension (data.value, data.normal) parameter

/-- All-winding invariance in the installed additive action. -/
theorem localExtension_vadd
    (data : CanonicalLatitudeDeckCauchyData period)
    (winding : Int) (parameter : CanonicalLatitudeCauchyCollar period) :
    data.localExtension (winding +ᵥ parameter) =
      data.localExtension parameter := by
  exact canonicalLatitudeLocalCauchyExtension_deck_zpow
    period data.value data.normal data.value_periodic
      data.normal_antiperiodic winding parameter

/-- Descended scalar field on the model collar quotient. -/
def descend
    (data : CanonicalLatitudeDeckCauchyData period) :
    CanonicalLatitudeCauchyCollarQuotient period → Real :=
  Quotient.lift data.localExtension (fun first second hOrbit => by
    change AddAction.orbitRel Int (CanonicalLatitudeCauchyCollar period)
      first second at hOrbit
    rw [AddAction.orbitRel_apply, AddAction.mem_orbit_iff] at hOrbit
    rcases hOrbit with ⟨winding, hWinding⟩
    rw [← hWinding]
    exact data.localExtension_vadd winding second)

@[simp] theorem descend_mk
    (data : CanonicalLatitudeDeckCauchyData period)
    (parameter : CanonicalLatitudeCauchyCollar period) :
    data.descend (canonicalLatitudeCauchyCollarMk period parameter) =
      data.localExtension parameter :=
  rfl

/-- The descended field realizes the prescribed value jet on every quotient
representative at normal coordinate zero. -/
@[simp] theorem descend_value
    (data : CanonicalLatitudeDeckCauchyData period)
    (base : CanonicalLatitudeBase) :
    data.descend (canonicalLatitudeCauchyCollarMk period (base, 0)) =
      data.value base := by
  rw [descend_mk]
  exact canonicalLatitudeLocalCauchyExtensionSlice_zero
    (data.value, data.normal) base

/-- The representative normal slice has the prescribed derivative. -/
theorem representative_normal_derivative
    (data : CanonicalLatitudeDeckCauchyData period)
    (base : CanonicalLatitudeBase) :
    deriv (fun normal =>
      data.descend (canonicalLatitudeCauchyCollarMk period (base, normal))) 0 =
      data.normal base := by
  have hFunction :
      (fun normal =>
        data.descend (canonicalLatitudeCauchyCollarMk period (base, normal))) =
      canonicalLatitudeLocalCauchyExtensionSlice
        (data.value, data.normal) base := by
    funext normal
    rfl
  rw [hFunction]
  exact deriv_canonicalLatitudeLocalCauchyExtensionSlice_zero
    (data.value, data.normal) base

/-- Exact quotient-descent certificate. -/
theorem certificate
    (data : CanonicalLatitudeDeckCauchyData period) :
    (∀ (winding : Int) (parameter : CanonicalLatitudeCauchyCollar period),
      data.localExtension (winding +ᵥ parameter) =
        data.localExtension parameter) ∧
      (∀ base,
        data.descend (canonicalLatitudeCauchyCollarMk period (base, 0)) =
          data.value base) ∧
      (∀ base,
        deriv (fun normal =>
          data.descend (canonicalLatitudeCauchyCollarMk period (base, normal))) 0 =
            data.normal base) :=
  ⟨data.localExtension_vadd,
    data.descend_value,
    data.representative_normal_derivative⟩

end CanonicalLatitudeDeckCauchyData

end
end P0EFTJanusMappingTorusCanonicalLatitudeCauchyJetCollarQuotient4D
end JanusFormal
