import JanusFormal.Branches.FundamentalGeometryPVariationalPrinciple.Gates.P0EFTJanusProgramPGlobalEulerLagrange4D
import JanusFormal.Branches.FundamentalGeometryPVariationalPrinciple.Gates.P0EFTJanusProgramPGlobalCompatibilityOperators4D
import JanusFormal.Branches.FundamentalGeometryPVariationalPrinciple.Gates.P0EFTJanusMappingTorusPhysicalGaugeSobolevComplex4D
import JanusFormal.Branches.FundamentalGeometryPVariationalPrinciple.Gates.P0EFTJanusMappingTorusSmoothDiffeomorphismGhostLieBracket4D

/-!
# Global Noether identities for the exact Candidate-A action

An infinitesimal physical ghost acts in one regular variational chart.  The
invariance certificate is termwise on the nine exact action blocks; invariance
of the assembled action and annihilation by its actual Euler derivative are
then theorems.  The result is paired with the already proved curved Bianchi
identity on the same physical quotient.
-/

namespace JanusFormal
namespace P0EFTJanusProgramPGlobalNoether4D

set_option autoImplicit false
set_option synthInstance.maxHeartbeats 600000

noncomputable section

open scoped Manifold ContDiff
open MeasureTheory
open P0EFTJanusMappingTorusQuotient
open P0EFTJanusMappingTorusSmoothAtlasFrontier
open P0EFTJanusMappingTorusSmoothQuotientManifold
open P0EFTJanusMappingTorusSmoothFieldDescent4D
open P0EFTJanusMappingTorusSmoothDiffeomorphismGhostLieBracket4D
open P0EFTJanusMappingTorusGeneralLorentzTensor4D
open P0EFTJanusMappingTorusGeneralHolonomicScalarDensity4D
open P0EFTJanusMappingTorusGeneralLorentzMetricLocalLeviCivitaPatch4D
open P0EFTJanusMappingTorusIntrinsicEinsteinHilbertAction4D
open P0EFTJanusMappingTorusIntrinsicAbelianMaxwellAction4D
open P0EFTJanusMappingTorusAbelianGaugeBRST4D
open P0EFTJanusMappingTorusPhysicalGaugeSobolevComplex4D
open P0EFTJanusProgramPGlobalCovariantAction4D
open P0EFTJanusProgramPFullCoupledHelmholtzAssembly4D
open P0EFTJanusProgramPGlobalEulerLagrange4D
open P0EFTJanusProgramPGlobalCompatibilityOperators4D

universe u

variable (period : Real) (hPeriod : period ≠ 0)

private abbrev EffectiveQuotient :=
  MappingTorus (reflectedSphereData period hPeriod)

local instance effectiveQuotientChartedSpace :
    ChartedSpace CoverModel (EffectiveQuotient period hPeriod) :=
  reflectedSphereQuotientChartedSpace period hPeriod

local instance effectiveQuotientIsManifold :
    IsManifold coverModelWithCorners ω
      (EffectiveQuotient period hPeriod) :=
  reflectedSphereQuotient_isManifold period hPeriod

local instance effectiveQuotientMeasurableSpace :
    MeasurableSpace (EffectiveQuotient period hPeriod) := borel _

local instance effectiveQuotientBorelSpace :
    BorelSpace (EffectiveQuotient period hPeriod) where
  measurable_eq := rfl

attribute [local instance]
  GlobalCandidateAVariationalChart.normedAddCommGroup
  GlobalCandidateAVariationalChart.normedSpace

/-- Affine chart action generated by an arbitrary paired physical ghost. -/
def globalGhostAffineTransform
    {couplings : GlobalCandidateAActionCouplings}
    {NonNullFace NullFace : Type*}
    [Fintype NonNullFace] [Fintype NullFace]
    {measure : Measure (EffectiveQuotient period hPeriod)}
    (chart : GlobalCandidateAVariationalChart period hPeriod couplings
      NonNullFace NullFace measure)
    (generator :
      PhysicalPairedGaugeGhost period hPeriod →ₗ[Real] chart.Configuration)
    (ghostAndParameter :
      PhysicalPairedGaugeGhost period hPeriod × Real)
    (configuration : chart.Configuration) :
    chart.Configuration :=
  configuration + ghostAndParameter.2 • generator ghostAndParameter.1

/-- A physical ghost representation whose invariance is verified separately
on every exact action block. -/
structure GlobalCandidateAGhostSymmetry
    {couplings : GlobalCandidateAActionCouplings}
    {NonNullFace NullFace : Type*}
    [Fintype NonNullFace] [Fintype NullFace]
    {measure : Measure (EffectiveQuotient period hPeriod)}
    (chart : GlobalCandidateAVariationalChart period hPeriod couplings
      NonNullFace NullFace measure) where
  generator :
    PhysicalPairedGaugeGhost period hPeriod →ₗ[Real] chart.Configuration
  blocksInvariant :
    FullCoupledInvariantUnder
      (globalCandidateAActionBlocks period hPeriod chart.family measure)
      (globalGhostAffineTransform period hPeriod chart generator)

/-- Affine chart action generated by an arbitrary real-linear gauge
parameter space.  This is the common interface used to combine the physical
`U(1)²` ghosts with future diffeomorphism/BRST generators. -/
def globalLinearGaugeAffineTransform
    {couplings : GlobalCandidateAActionCouplings}
    {NonNullFace NullFace GaugeParameter : Type*}
    [Fintype NonNullFace] [Fintype NullFace]
    [AddCommGroup GaugeParameter] [Module Real GaugeParameter]
    {measure : Measure (EffectiveQuotient period hPeriod)}
    (chart : GlobalCandidateAVariationalChart period hPeriod couplings
      NonNullFace NullFace measure)
    (generator : GaugeParameter →ₗ[Real] chart.Configuration)
    (gaugeAndParameter : GaugeParameter × Real)
    (configuration : chart.Configuration) :
    chart.Configuration :=
  configuration + gaugeAndParameter.2 • generator gaugeAndParameter.1

/-- Termwise symmetry for any real-linear gauge parameter space. -/
structure GlobalCandidateALinearGaugeSymmetry
    {couplings : GlobalCandidateAActionCouplings}
    {NonNullFace NullFace : Type*}
    [Fintype NonNullFace] [Fintype NullFace]
    {measure : Measure (EffectiveQuotient period hPeriod)}
    (chart : GlobalCandidateAVariationalChart period hPeriod couplings
      NonNullFace NullFace measure)
    (GaugeParameter : Type*)
    [AddCommGroup GaugeParameter] [Module Real GaugeParameter] where
  generator : GaugeParameter →ₗ[Real] chart.Configuration
  blocksInvariant :
    FullCoupledInvariantUnder
      (globalCandidateAActionBlocks period hPeriod chart.family measure)
      (globalLinearGaugeAffineTransform period hPeriod chart generator)

/-- Abstract full-action diffeomorphism symmetry contract, specialized to the
global smooth tangent-vector ghost space.  An inhabitant must still prove
invariance of all nine physical action blocks and separately identify its
chart generator with the geometric diffeomorphism action. -/
abbrev GlobalCandidateADiffeomorphismGaugeSymmetry
    {couplings : GlobalCandidateAActionCouplings}
    {NonNullFace NullFace : Type*}
    [Fintype NonNullFace] [Fintype NullFace]
    {measure : Measure (EffectiveQuotient period hPeriod)}
    (chart : GlobalCandidateAVariationalChart period hPeriod couplings
      NonNullFace NullFace measure) :=
  GlobalCandidateALinearGaugeSymmetry period hPeriod chart
    (CInfinityDiffeomorphismGhost period hPeriod)

/-- The already constructed paired physical symmetry is the first instance
of the general linear-gauge interface. -/
def GlobalCandidateAGhostSymmetry.toLinearGaugeSymmetry
    {couplings : GlobalCandidateAActionCouplings}
    {NonNullFace NullFace : Type*}
    [Fintype NonNullFace] [Fintype NullFace]
    {measure : Measure (EffectiveQuotient period hPeriod)}
    {chart : GlobalCandidateAVariationalChart period hPeriod couplings
      NonNullFace NullFace measure}
    (symmetry : GlobalCandidateAGhostSymmetry period hPeriod chart) :
    GlobalCandidateALinearGaugeSymmetry period hPeriod chart
      (PhysicalPairedGaugeGhost period hPeriod) where
  generator := symmetry.generator
  blocksInvariant := by
    change FullCoupledInvariantUnder
      (globalCandidateAActionBlocks period hPeriod chart.family measure)
      (globalGhostAffineTransform period hPeriod chart symmetry.generator)
    exact symmetry.blocksInvariant

@[simp]
theorem GlobalCandidateAGhostSymmetry.toLinearGaugeSymmetry_generator
    {couplings : GlobalCandidateAActionCouplings}
    {NonNullFace NullFace : Type*}
    [Fintype NonNullFace] [Fintype NullFace]
    {measure : Measure (EffectiveQuotient period hPeriod)}
    {chart : GlobalCandidateAVariationalChart period hPeriod couplings
      NonNullFace NullFace measure}
    (symmetry : GlobalCandidateAGhostSymmetry period hPeriod chart)
    (ghost : PhysicalPairedGaugeGhost period hPeriod) :
    (symmetry.toLinearGaugeSymmetry period hPeriod).generator ghost =
      symmetry.generator ghost :=
  rfl

/-- Direct product of two exact linear gauge symmetries. -/
def GlobalCandidateALinearGaugeSymmetry.prod
    {couplings : GlobalCandidateAActionCouplings}
    {NonNullFace NullFace FirstGauge SecondGauge : Type*}
    [Fintype NonNullFace] [Fintype NullFace]
    [AddCommGroup FirstGauge] [Module Real FirstGauge]
    [AddCommGroup SecondGauge] [Module Real SecondGauge]
    {measure : Measure (EffectiveQuotient period hPeriod)}
    {chart : GlobalCandidateAVariationalChart period hPeriod couplings
      NonNullFace NullFace measure}
    (first :
      GlobalCandidateALinearGaugeSymmetry period hPeriod chart FirstGauge)
    (second :
      GlobalCandidateALinearGaugeSymmetry period hPeriod chart SecondGauge) :
    GlobalCandidateALinearGaugeSymmetry period hPeriod chart
      (FirstGauge × SecondGauge) where
  generator :=
    { toFun := fun gauge =>
        first.generator gauge.1 + second.generator gauge.2
      map_add' := by
        intro left right
        simp only [Prod.fst_add, Prod.snd_add, map_add]
        abel
      map_smul' := by
        intro scalar gauge
        simp only [Prod.smul_fst, Prod.smul_snd, map_smul, smul_add,
          RingHom.id_apply] }
  blocksInvariant := by
    let combined :
        (FirstGauge × SecondGauge) →ₗ[Real] chart.Configuration :=
      { toFun := fun gauge =>
          first.generator gauge.1 + second.generator gauge.2
        map_add' := by
          intro left right
          simp only [Prod.fst_add, Prod.snd_add, map_add]
          abel
        map_smul' := by
          intro scalar gauge
          simp only [Prod.smul_fst, Prod.smul_snd, map_smul, smul_add,
            RingHom.id_apply] }
    have hTransform (gauge : FirstGauge × SecondGauge) (parameter : Real)
        (configuration : chart.Configuration) :
        globalLinearGaugeAffineTransform period hPeriod chart combined
            (gauge, parameter) configuration =
          globalLinearGaugeAffineTransform period hPeriod chart
            second.generator (gauge.2, parameter)
            (globalLinearGaugeAffineTransform period hPeriod chart
              first.generator (gauge.1, parameter) configuration) := by
      simp only [globalLinearGaugeAffineTransform, combined,
        LinearMap.coe_mk, AddHom.coe_mk, smul_add]
      abel
    constructor <;>
      intro gaugeAndParameter configuration <;>
      rcases gaugeAndParameter with ⟨gauge, parameter⟩ <;>
      rw [hTransform gauge parameter configuration] <;>
      first
      | rw [second.blocksInvariant.candidateA,
          first.blocksInvariant.candidateA]
      | rw [second.blocksInvariant.matter,
          first.blocksInvariant.matter]
      | rw [second.blocksInvariant.robin,
          first.blocksInvariant.robin]
      | rw [second.blocksInvariant.ll,
          first.blocksInvariant.ll]
      | rw [second.blocksInvariant.einsteinHilbertPlus,
          first.blocksInvariant.einsteinHilbertPlus]
      | rw [second.blocksInvariant.einsteinHilbertMinus,
          first.blocksInvariant.einsteinHilbertMinus]
      | rw [second.blocksInvariant.maxwellPlus,
          first.blocksInvariant.maxwellPlus]
      | rw [second.blocksInvariant.maxwellMinus,
          first.blocksInvariant.maxwellMinus]
      | rw [second.blocksInvariant.finiteBV,
          first.blocksInvariant.finiteBV]

/-- Termwise symmetry implies exact invariance of the same assembled action. -/
theorem globalCandidateAAction_ghost_invariant
    {couplings : GlobalCandidateAActionCouplings}
    {NonNullFace NullFace : Type*}
    [Fintype NonNullFace] [Fintype NullFace]
    {measure : Measure (EffectiveQuotient period hPeriod)}
    (chart : GlobalCandidateAVariationalChart period hPeriod couplings
      NonNullFace NullFace measure)
    (symmetry : GlobalCandidateAGhostSymmetry period hPeriod chart)
    (ghost : PhysicalPairedGaugeGhost period hPeriod)
    (parameter : Real)
    (configuration : chart.Configuration) :
    globalCandidateAActionPullback period hPeriod chart
        (globalGhostAffineTransform period hPeriod chart symmetry.generator
          (ghost, parameter) configuration) =
      globalCandidateAActionPullback period hPeriod chart configuration := by
  rw [globalCandidateAActionPullback_eq_blocks period hPeriod chart]
  exact fullCoupledAction_invariant
    (globalCandidateAActionBlocks period hPeriod chart.family measure)
    (globalGhostAffineTransform period hPeriod chart symmetry.generator)
    symmetry.blocksInvariant (ghost, parameter) configuration

/-- Exact invariance for an arbitrary certified linear gauge symmetry. -/
theorem globalCandidateAAction_linearGauge_invariant
    {couplings : GlobalCandidateAActionCouplings}
    {NonNullFace NullFace GaugeParameter : Type*}
    [Fintype NonNullFace] [Fintype NullFace]
    [AddCommGroup GaugeParameter] [Module Real GaugeParameter]
    {measure : Measure (EffectiveQuotient period hPeriod)}
    (chart : GlobalCandidateAVariationalChart period hPeriod couplings
      NonNullFace NullFace measure)
    (symmetry :
      GlobalCandidateALinearGaugeSymmetry period hPeriod chart GaugeParameter)
    (gauge : GaugeParameter)
    (parameter : Real)
    (configuration : chart.Configuration) :
    globalCandidateAActionPullback period hPeriod chart
        (globalLinearGaugeAffineTransform period hPeriod chart
          symmetry.generator (gauge, parameter) configuration) =
      globalCandidateAActionPullback period hPeriod chart configuration := by
  rw [globalCandidateAActionPullback_eq_blocks period hPeriod chart]
  exact fullCoupledAction_invariant
    (globalCandidateAActionBlocks period hPeriod chart.family measure)
    (globalLinearGaugeAffineTransform period hPeriod chart symmetry.generator)
    symmetry.blocksInvariant (gauge, parameter) configuration

/-- Pullback of the true Euler covector to the paired physical ghost space. -/
def globalGhostNoetherOperator
    {couplings : GlobalCandidateAActionCouplings}
    {NonNullFace NullFace : Type*}
    [Fintype NonNullFace] [Fintype NullFace]
    {measure : Measure (EffectiveQuotient period hPeriod)}
  (chart : GlobalCandidateAVariationalChart period hPeriod couplings
      NonNullFace NullFace measure)
    (symmetry : GlobalCandidateAGhostSymmetry period hPeriod chart)
    (configuration : chart.Configuration) :
    PhysicalPairedGaugeGhost period hPeriod →ₗ[Real] Real :=
  (globalEulerLagrangeOperator period hPeriod chart configuration).toLinearMap.comp
    symmetry.generator

@[simp]
theorem globalGhostNoetherOperator_apply
    {couplings : GlobalCandidateAActionCouplings}
    {NonNullFace NullFace : Type*}
    [Fintype NonNullFace] [Fintype NullFace]
    {measure : Measure (EffectiveQuotient period hPeriod)}
    (chart : GlobalCandidateAVariationalChart period hPeriod couplings
      NonNullFace NullFace measure)
    (symmetry : GlobalCandidateAGhostSymmetry period hPeriod chart)
    (configuration : chart.Configuration)
    (ghost : PhysicalPairedGaugeGhost period hPeriod) :
    globalGhostNoetherOperator period hPeriod chart symmetry configuration
        ghost =
      globalEulerLagrangeOperator period hPeriod chart configuration
        (symmetry.generator ghost) :=
  rfl

/-- Local Noether identity for every smooth paired physical ghost. -/
theorem globalEuler_annihilates_arbitrary_ghost
    {couplings : GlobalCandidateAActionCouplings}
    {NonNullFace NullFace : Type*}
    [Fintype NonNullFace] [Fintype NullFace]
    {measure : Measure (EffectiveQuotient period hPeriod)}
    (chart : GlobalCandidateAVariationalChart period hPeriod couplings
      NonNullFace NullFace measure)
    (symmetry : GlobalCandidateAGhostSymmetry period hPeriod chart)
    (configuration : chart.Configuration)
    (ghost : PhysicalPairedGaugeGhost period hPeriod) :
    globalEulerLagrangeOperator period hPeriod chart configuration
        (symmetry.generator ghost) = 0 := by
  let direction := symmetry.generator ghost
  have hLine :
      HasDerivAt
        (fun parameter : Real => configuration + parameter • direction)
        direction 0 := by
    have hConstant : HasDerivAt (fun _ : Real => configuration) 0 0 :=
      hasDerivAt_const (x := (0 : Real)) (c := configuration)
    have hLinear := (hasDerivAt_id (0 : Real)).smul_const direction
    exact (hConstant.add hLinear).congr_deriv (by simp)
  have hActionDerivative :
      HasDerivAt
        (fun parameter : Real =>
          globalCandidateAActionPullback period hPeriod chart
            (configuration + parameter • direction))
        (globalEulerLagrangeOperator period hPeriod chart configuration
          direction) 0 := by
    have hDerivative :=
      (globalCandidateAAction_hasFDerivAt period hPeriod chart configuration)
        |>.comp_hasDerivAt_of_eq 0 hLine (by simp)
    simpa [Function.comp_def] using hDerivative
  have hConstantCurve :
      (fun parameter : Real =>
        globalCandidateAActionPullback period hPeriod chart
          (configuration + parameter • direction)) =
        fun _ =>
          globalCandidateAActionPullback period hPeriod chart
            configuration := by
    funext parameter
    exact globalCandidateAAction_ghost_invariant period hPeriod chart symmetry
      ghost parameter configuration
  have hZeroDerivative :
      HasDerivAt
        (fun parameter : Real =>
          globalCandidateAActionPullback period hPeriod chart
            (configuration + parameter • direction)) 0 0 := by
    rw [hConstantCurve]
    exact hasDerivAt_const (x := (0 : Real))
      (c := globalCandidateAActionPullback period hPeriod chart configuration)
  exact hActionDerivative.unique hZeroDerivative

/-- Noether identity for every parameter of an arbitrary certified linear
gauge symmetry. -/
theorem globalEuler_annihilates_linearGauge
    {couplings : GlobalCandidateAActionCouplings}
    {NonNullFace NullFace GaugeParameter : Type*}
    [Fintype NonNullFace] [Fintype NullFace]
    [AddCommGroup GaugeParameter] [Module Real GaugeParameter]
    {measure : Measure (EffectiveQuotient period hPeriod)}
    (chart : GlobalCandidateAVariationalChart period hPeriod couplings
      NonNullFace NullFace measure)
    (symmetry :
      GlobalCandidateALinearGaugeSymmetry period hPeriod chart GaugeParameter)
    (configuration : chart.Configuration)
    (gauge : GaugeParameter) :
    globalEulerLagrangeOperator period hPeriod chart configuration
        (symmetry.generator gauge) = 0 := by
  let direction := symmetry.generator gauge
  have hLine :
      HasDerivAt
        (fun parameter : Real => configuration + parameter • direction)
        direction 0 := by
    have hConstant : HasDerivAt (fun _ : Real => configuration) 0 0 :=
      hasDerivAt_const (x := (0 : Real)) (c := configuration)
    have hLinear := (hasDerivAt_id (0 : Real)).smul_const direction
    exact (hConstant.add hLinear).congr_deriv (by simp)
  have hActionDerivative :
      HasDerivAt
        (fun parameter : Real =>
          globalCandidateAActionPullback period hPeriod chart
            (configuration + parameter • direction))
        (globalEulerLagrangeOperator period hPeriod chart configuration
          direction) 0 := by
    have hDerivative :=
      (globalCandidateAAction_hasFDerivAt period hPeriod chart configuration)
        |>.comp_hasDerivAt_of_eq 0 hLine (by simp)
    simpa [Function.comp_def] using hDerivative
  have hConstantCurve :
      (fun parameter : Real =>
        globalCandidateAActionPullback period hPeriod chart
          (configuration + parameter • direction)) =
        fun _ =>
          globalCandidateAActionPullback period hPeriod chart
            configuration := by
    funext parameter
    exact globalCandidateAAction_linearGauge_invariant period hPeriod chart
      symmetry gauge parameter configuration
  have hZeroDerivative :
      HasDerivAt
        (fun parameter : Real =>
          globalCandidateAActionPullback period hPeriod chart
            (configuration + parameter • direction)) 0 0 := by
    rw [hConstantCurve]
    exact hasDerivAt_const (x := (0 : Real))
      (c := globalCandidateAActionPullback period hPeriod chart configuration)
  exact hActionDerivative.unique hZeroDerivative

/-- Specialized diffeomorphism Noether identity.  All analytic differentiation
is discharged; only the exact nine-block symmetry certificate is input. -/
theorem globalEuler_annihilates_diffeomorphismGauge
    {couplings : GlobalCandidateAActionCouplings}
    {NonNullFace NullFace : Type*}
    [Fintype NonNullFace] [Fintype NullFace]
    {measure : Measure (EffectiveQuotient period hPeriod)}
    (chart : GlobalCandidateAVariationalChart period hPeriod couplings
      NonNullFace NullFace measure)
    (symmetry :
      GlobalCandidateADiffeomorphismGaugeSymmetry
        period hPeriod chart)
    (configuration : chart.Configuration)
    (ghost : CInfinityDiffeomorphismGhost period hPeriod) :
    globalEulerLagrangeOperator period hPeriod chart configuration
        (symmetry.generator ghost) = 0 :=
  globalEuler_annihilates_linearGauge
    period hPeriod chart symmetry configuration ghost

/-- Operator form of the full paired abelian Noether identity. -/
theorem globalGhostNoetherOperator_eq_zero
    {couplings : GlobalCandidateAActionCouplings}
    {NonNullFace NullFace : Type*}
    [Fintype NonNullFace] [Fintype NullFace]
    {measure : Measure (EffectiveQuotient period hPeriod)}
    (chart : GlobalCandidateAVariationalChart period hPeriod couplings
      NonNullFace NullFace measure)
    (symmetry : GlobalCandidateAGhostSymmetry period hPeriod chart)
    (configuration : chart.Configuration) :
    globalGhostNoetherOperator period hPeriod chart symmetry configuration =
      0 := by
  apply LinearMap.ext
  intro ghost
  exact globalEuler_annihilates_arbitrary_ghost period hPeriod chart symmetry
    configuration ghost

/-- Exact action orbit obtained by gauge-transforming the two intrinsic
Maxwell potentials while leaving every gauge-neutral block unchanged. -/
def globalCandidateAPhysicalGaugeOrbit
    {configuration :
      P0EFTJanusProgramPGlobalFieldSpace4D.GlobalFieldConfiguration
        period hPeriod}
    {couplings : GlobalCandidateAActionCouplings}
    {NonNullFace NullFace : Type*}
    [Fintype NonNullFace] [Fintype NullFace]
    (data : GlobalCandidateAActionData period hPeriod configuration couplings
      NonNullFace NullFace)
    (measure : Measure (EffectiveQuotient period hPeriod))
    (ghosts : PhysicalPairedGaugeGhost period hPeriod)
    (parameter : Real) : Real :=
  globalCandidateAEinsteinHilbertAction period hPeriod data measure +
    globalCandidateAInteractionAction period hPeriod data measure +
    globalCandidateAMatterAction period hPeriod configuration couplings +
    (couplings.plusMaxwellScale *
      intrinsicMaxwellAction period hPeriod data.plusGravity.metric
        (data.plusMaxwell.gaugeTransform period hPeriod
          data.plusGravity.metric (parameter • ghosts.1)).basePairing
        measure +
      couplings.minusMaxwellScale *
        intrinsicMaxwellAction period hPeriod data.minusGravity.metric
          (data.minusMaxwell.gaugeTransform period hPeriod
            data.minusGravity.metric (parameter • ghosts.2)).basePairing
          measure) +
    globalCandidateALLAction period hPeriod data +
    globalCandidateAGHYAction period hPeriod data +
    globalCandidateANullBoundaryAction period hPeriod data

/-- The physical paired gauge orbit is exactly constant for arbitrary smooth
ghosts; this uses `d(A + dλ) = dA` in each intrinsic Maxwell block. -/
theorem globalCandidateAPhysicalGaugeOrbit_eq_action
    {configuration :
      P0EFTJanusProgramPGlobalFieldSpace4D.GlobalFieldConfiguration
        period hPeriod}
    {couplings : GlobalCandidateAActionCouplings}
    {NonNullFace NullFace : Type*}
    [Fintype NonNullFace] [Fintype NullFace]
    (data : GlobalCandidateAActionData period hPeriod configuration couplings
      NonNullFace NullFace)
    (measure : Measure (EffectiveQuotient period hPeriod))
    (ghosts : PhysicalPairedGaugeGhost period hPeriod)
    (parameter : Real) :
    globalCandidateAPhysicalGaugeOrbit period hPeriod data measure ghosts
        parameter =
      globalCandidateACovariantAction period hPeriod data measure := by
  unfold globalCandidateAPhysicalGaugeOrbit
    globalCandidateACovariantAction globalCandidateAMaxwellAction
  rw [intrinsicMaxwellAction_gaugeTransform,
    intrinsicMaxwellAction_gaugeTransform]

/-- Unconditional Noether identity on the same global action for every
smooth paired `U(1)` ghost. -/
theorem globalCandidateAPhysicalGaugeOrbit_hasDerivAt_zero
    {configuration :
      P0EFTJanusProgramPGlobalFieldSpace4D.GlobalFieldConfiguration
        period hPeriod}
    {couplings : GlobalCandidateAActionCouplings}
    {NonNullFace NullFace : Type*}
    [Fintype NonNullFace] [Fintype NullFace]
    (data : GlobalCandidateAActionData period hPeriod configuration couplings
      NonNullFace NullFace)
    (measure : Measure (EffectiveQuotient period hPeriod))
    (ghosts : PhysicalPairedGaugeGhost period hPeriod) :
    HasDerivAt
      (globalCandidateAPhysicalGaugeOrbit period hPeriod data measure ghosts)
      0 0 := by
  have hConstant :
      globalCandidateAPhysicalGaugeOrbit period hPeriod data measure ghosts =
        fun _ => globalCandidateACovariantAction period hPeriod data measure := by
    funext parameter
    exact globalCandidateAPhysicalGaugeOrbit_eq_action period hPeriod data
      measure ghosts parameter
  rw [hConstant]
  exact hasDerivAt_const
    (x := (0 : Real))
    (c := globalCandidateACovariantAction period hPeriod data measure)

/-- Combined global Noether--Bianchi closure on the exact action and the
intrinsic Levi--Civita geometry. -/
theorem global_noether_bianchi_gate
    {couplings : GlobalCandidateAActionCouplings}
    {NonNullFace NullFace : Type*}
    [Fintype NonNullFace] [Fintype NullFace]
    {measure : Measure (EffectiveQuotient period hPeriod)}
    (chart : GlobalCandidateAVariationalChart period hPeriod couplings
      NonNullFace NullFace measure)
    (symmetry : GlobalCandidateAGhostSymmetry period hPeriod chart)
    (configuration : chart.Configuration)
    (metric : SmoothGeneralLorentzMetric period hPeriod)
    (point : EffectiveQuotient period hPeriod) :
    globalGhostNoetherOperator period hPeriod chart symmetry configuration =
        0 ∧
      ∃ patch : SmoothHolonomicFrameChart4 period hPeriod,
        ∃ coordinate : IntrinsicVector4,
          patch.coordinateMap coordinate = point ∧
            ∀ first second third : IntrinsicIndex4,
              B_Bianchi period hPeriod metric (K_SV period hPeriod metric)
                patch coordinate first second third = 0 := by
  exact ⟨globalGhostNoetherOperator_eq_zero period hPeriod chart symmetry
      configuration,
    B_Bianchi_comp_K_SV_eq_zero_at_every_point
      period hPeriod metric point⟩

/-- Unconditional physical Noether--Bianchi gate: arbitrary paired smooth
abelian ghosts act on the exact global action, and the true curved Bianchi
identity holds at every quotient point. -/
theorem global_physical_noether_bianchi_gate
    {configuration :
      P0EFTJanusProgramPGlobalFieldSpace4D.GlobalFieldConfiguration
        period hPeriod}
    {couplings : GlobalCandidateAActionCouplings}
    {NonNullFace NullFace : Type*}
    [Fintype NonNullFace] [Fintype NullFace]
    (data : GlobalCandidateAActionData period hPeriod configuration couplings
      NonNullFace NullFace)
    (measure : Measure (EffectiveQuotient period hPeriod))
    (ghosts : PhysicalPairedGaugeGhost period hPeriod)
    (metric : SmoothGeneralLorentzMetric period hPeriod)
    (point : EffectiveQuotient period hPeriod) :
    HasDerivAt
        (globalCandidateAPhysicalGaugeOrbit period hPeriod data measure ghosts)
        0 0 ∧
      ∃ patch : SmoothHolonomicFrameChart4 period hPeriod,
        ∃ coordinate : IntrinsicVector4,
          patch.coordinateMap coordinate = point ∧
            ∀ first second third : IntrinsicIndex4,
              B_Bianchi period hPeriod metric (K_SV period hPeriod metric)
                patch coordinate first second third = 0 := by
  exact
    ⟨globalCandidateAPhysicalGaugeOrbit_hasDerivAt_zero
      period hPeriod data measure ghosts,
    B_Bianchi_comp_K_SV_eq_zero_at_every_point
      period hPeriod metric point⟩

end
end P0EFTJanusProgramPGlobalNoether4D
end JanusFormal
