import JanusFormal.Branches.FundamentalGeometryPVariationalPrinciple.Gates.P0EFTJanusMappingTorusCanonicalPhysicalScalarCanonicalWaveAutomaticSixCoefficientPDEClosure4D
import JanusFormal.Branches.FundamentalGeometryPVariationalPrinciple.Gates.P0EFTJanusMappingTorusCanonicalPhysicalScalarCauchyJetEulerBoundedCoefficients4D

/-!
# Minimal canonical PDE closure from bounded Euler coefficient operators

The six coefficient estimates are generated by six continuous operators on the
completed Cauchy boundary space.  Their operator norms provide the constants;
coefficient and separated-product integrability are theorems.

The remaining boundary PDE input is therefore:

* six concrete coefficient representatives;
* six bounded operators realizing those representatives in boundary `L²`;
* the exact six-profile expansion of the pulled-back Euler residual.
-/

namespace JanusFormal
namespace P0EFTJanusMappingTorusCanonicalPhysicalScalarCanonicalWaveBoundedCoefficientPDEClosure4D

set_option autoImplicit false
noncomputable section

open Set Topology MeasureTheory
open P0EFTJanusMappingTorusCanonicalPhysicalScalarCanonicalWaveCauchyJetGreenCore4D
open P0EFTJanusMappingTorusCanonicalPhysicalScalarCanonicalWaveAutomaticSixCoefficientPDEClosure4D
open P0EFTJanusMappingTorusCanonicalPhysicalScalarAutomaticGardingEnergy4D
open P0EFTJanusMappingTorusCanonicalPhysicalScalarNormalEllipticRegularity4D
open P0EFTJanusMappingTorusCanonicalPhysicalScalarCauchyJetEulerBoundedCoefficients4D
open P0EFTJanusMappingTorusScalarHilbertGreenCoreCompletion4D

universe r

variable (period : Real) (hPeriod : period ≠ 0)
variable {Regularity : Type r}
  [NormedAddCommGroup Regularity] [NormedSpace Real Regularity]
  [CompleteSpace Regularity]

/-- Minimal canonical PDE data with all six coefficient estimates generated by
operator norms. -/
structure CanonicalPhysicalScalarCanonicalWaveBoundedCoefficientPDEData
    (massSquared : Real) where
  geometric : CanonicalPhysicalScalarCanonicalWaveCauchyJetData
    period hPeriod massSquared
  energy : geometric.greenCore.AutomaticEnergyGardingData period hPeriod
  normalRegularity : geometric.greenCore.NormalEllipticRegularityData
    period hPeriod (Regularity := Regularity)
  eulerCoefficients :
    geometric.toCanonicalCauchyJetCompatibilityData.toCompatibilityData.toCauchyJetGeometricData.CauchyJetEulerSixBoundedCoefficientData
      period hPeriod
      geometric.toCanonicalCauchyJetCompatibilityData.toCompatibilityData.toCauchyJetGeometricData.canonicalEulerProductRealization

namespace CanonicalPhysicalScalarCanonicalWaveBoundedCoefficientPDEData

/-- Conversion to the six-coefficient minimal PDE package. -/
def toWaveAutomaticSixCoefficientPDEData
    (data : CanonicalPhysicalScalarCanonicalWaveBoundedCoefficientPDEData
      period hPeriod massSquared (Regularity := Regularity)) :
    CanonicalPhysicalScalarCanonicalWaveAutomaticSixCoefficientPDEData
      period hPeriod massSquared (Regularity := Regularity) where
  geometric := data.geometric
  energy := data.energy
  normalRegularity := data.normalRegularity
  eulerCoefficients := data.eulerCoefficients.toSixCoefficientData

/-- Correct completed physical boundary triple. -/
def triple
    (data : CanonicalPhysicalScalarCanonicalWaveBoundedCoefficientPDEData
      period hPeriod massSquared (Regularity := Regularity)) :=
  data.toWaveAutomaticSixCoefficientPDEData.triple

/-- Completed physical boundary inputs. -/
def completedInputs
    (data : CanonicalPhysicalScalarCanonicalWaveBoundedCoefficientPDEData
      period hPeriod massSquared (Regularity := Regularity)) :=
  data.toWaveAutomaticSixCoefficientPDEData.completedInputs

/-- Bounded right inverse of the completed Cauchy trace. -/
def completedExtension
    (data : CanonicalPhysicalScalarCanonicalWaveBoundedCoefficientPDEData
      period hPeriod massSquared (Regularity := Regularity)) :=
  data.toWaveAutomaticSixCoefficientPDEData.completedExtension

/-- Physical graph-elliptic estimate. -/
def graphEllipticEstimate
    (data : CanonicalPhysicalScalarCanonicalWaveBoundedCoefficientPDEData
      period hPeriod massSquared (Regularity := Regularity)) :=
  data.toWaveAutomaticSixCoefficientPDEData.graphEllipticEstimate

/-- Full Euler graph bound obtained from the six bounded coefficient operators. -/
theorem euler_product_bound
    (data : CanonicalPhysicalScalarCanonicalWaveBoundedCoefficientPDEData
      period hPeriod massSquared (Regularity := Regularity))
    (boundary :
      P0EFTJanusMappingTorusCanonicalLatitudeSmoothBoundaryCores4D.CanonicalLatitudeSmoothPeriodicValueCore period ×
      P0EFTJanusMappingTorusCanonicalLatitudeSmoothBoundaryCores4D.CanonicalLatitudeSmoothAntiperiodicNormalCore period) :
    (∫ parameter,
      data.geometric.toCanonicalCauchyJetCompatibilityData.toCompatibilityData.toCauchyJetGeometricData.canonicalEulerProductResidual
        boundary parameter ^ 2
      ∂P0EFTJanusMappingTorusCanonicalLatitudeCauchyJetProductCoarea4D.canonicalLatitudeCauchyJetProductMeasure
        period) ≤
      data.eulerCoefficients.toSixCoefficientData.toSeparatedExpansionData.toFiniteExpansionData.combinedConstant ^ 2 *
        ‖data.geometric.toCanonicalCauchyJetCompatibilityData.toCompatibilityData.toCauchyJetGeometricData.boundaryCoreEmbedding
          boundary‖ ^ 2 :=
  data.eulerCoefficients.certificate boundary

/-- Bounded-coefficient minimal PDE certificate. -/
theorem certificate
    (data : CanonicalPhysicalScalarCanonicalWaveBoundedCoefficientPDEData
      period hPeriod massSquared (Regularity := Regularity)) :
    Function.Injective
        (canonicalScalarGreenCoreGraphInclusion
          data.geometric.greenCore.core) ∧
      Function.Surjective
        (canonicalScalarGreenCoreCompletedBoundaryTrace
          data.geometric.greenCore.core
          (data.completedInputs.traceBound data.geometric.greenCore)) ∧
      (∀ boundary,
        canonicalScalarGreenCoreCompletedBoundaryTrace
            data.geometric.greenCore.core
            (data.completedInputs.traceBound data.geometric.greenCore)
            (data.completedExtension boundary) = boundary) :=
  ⟨data.toWaveAutomaticSixCoefficientPDEData.certificate.2.1,
    data.toWaveAutomaticSixCoefficientPDEData.certificate.2.2.1,
    data.toWaveAutomaticSixCoefficientPDEData.certificate.2.2.2⟩

end CanonicalPhysicalScalarCanonicalWaveBoundedCoefficientPDEData

end
end P0EFTJanusMappingTorusCanonicalPhysicalScalarCanonicalWaveBoundedCoefficientPDEClosure4D
end JanusFormal
