import JanusFormal.Branches.FundamentalGeometryPVariationalPrinciple.Gates.P0EFTJanusProgramPReferenceNuclearDuhamelGreenSelectedTraceBoundaryLimits4D
import JanusFormal.Branches.FundamentalGeometryPVariationalPrinciple.Gates.P0EFTJanusProgramPReferenceNuclearHeatFinitePartCanonicalSchwarzAssembly4D

/-!
# Canonical-Schwarz reference assembly tied to the selected trace

A spectral chart already carries an
`IntrinsicLogarithmicDerivativeTraceData` for its reference operator family.
The preceding canonical-Schwarz assembly still exposed the scalar generated by
its endpoint construction under an independently named logarithmic trace.

This frontend inserts the selected reference packet directly into the
Duhamel--Green boundary limits.  It therefore derives

```text
finitePartLogDerivative(a) = selectedTrace.trace(a),
T_reference(a) = -selectedTrace.trace(a),
```

while retaining the canonical Mellin Schwarz argument and the same standalone
reference zeta family.  No generated-to-selected operator or scalar comparison
is part of the input.
-/

namespace JanusFormal
namespace P0EFTJanusProgramPReferenceNuclearHeatFinitePartSelectedTraceCanonicalSchwarzAssembly4D

set_option autoImplicit false
noncomputable section

open Filter Set
open P0EFTJanusProgramPIntrinsicLogarithmicDerivativeTrace4D
open P0EFTJanusProgramPNuclearHeatDuhamelTraceVariation4D
open P0EFTJanusProgramPReferenceNuclearDuhamelGreenSelectedTraceBoundaryLimits4D
open P0EFTJanusProgramPReferenceNuclearHeatFinitePartCanonicalSchwarzAssembly4D
open P0EFTJanusProgramPRelativeHeatMellinZetaCanonicalSchwarzReflection4D
open P0EFTJanusProgramPRelativeHeatMellinZetaFamily4D

variable {Slice ShortCutoff LongCutoff E : Type*}
  [MeasurableSpace Slice]
  [NormedAddCommGroup E] [NormedSpace Real E]
  [InnerProductSpace Real E] [CompleteSpace E]

/-- Standalone reference data whose Duhamel endpoint target and nuclear trace
are selected by the determinant chart itself. -/
structure ReferenceNuclearHeatFinitePartSelectedTraceCanonicalSchwarzAssemblyData
    (sliceMeasure : Measure Slice) [IsProbabilityMeasure sliceMeasure]
    (shortCutoffFilter : Filter ShortCutoff) [NeBot shortCutoffFilter]
    (longCutoffFilter : Filter LongCutoff) [NeBot longCutoffFilter]
    (referenceOperator : Real → E →L[Real] E)
    (selectedTrace : IntrinsicLogarithmicDerivativeTraceData referenceOperator)
    (family : RelativeHeatMellinZetaFamilyData)
    (shortTimeRegion longTimeRegion : Set Real) where
  nuclear : NuclearHeatDuhamelTraceVariationData (E := E)
  countertermContribution : Real → Real
  spectralBoundary :
    ReferenceNuclearDuhamelGreenSelectedTraceBoundaryLimitsData
      sliceMeasure shortCutoffFilter longCutoffFilter nuclear
        countertermContribution shortTimeRegion longTimeRegion
          referenceOperator selectedTrace
  logDeterminant_eq : ∀ parameter,
    P0EFTJanusProgramPRelativeHeatFinitePartDeterminant4D.
        relativeHeatFinitePartLogDeterminant
          (family.finitePartFamily.finitePart parameter) =
      countertermContribution parameter +
        spectralBoundary.toFullySpectralBoundaryLimits.shortTime.weighted.
            toWeightedHeatTraceVariation.contribution parameter +
          spectralBoundary.toFullySpectralBoundaryLimits.longTime.weighted.
            toWeightedHeatTraceVariation.contribution parameter
  zetaCanonicalSchwarz : ∀ parameter,
    RelativeHeatMellinZetaCanonicalSchwarzReflectionData
      (family.continuation parameter)

namespace ReferenceNuclearHeatFinitePartSelectedTraceCanonicalSchwarzAssemblyData

/-- Forget the selected-reference presentation only after installing it in the
existing canonical-Schwarz assembly. -/
def toCanonicalSchwarzAssembly
    {sliceMeasure : Measure Slice} [IsProbabilityMeasure sliceMeasure]
    {shortCutoffFilter : Filter ShortCutoff} [NeBot shortCutoffFilter]
    {longCutoffFilter : Filter LongCutoff} [NeBot longCutoffFilter]
    {referenceOperator : Real → E →L[Real] E}
    {selectedTrace : IntrinsicLogarithmicDerivativeTraceData referenceOperator}
    {family : RelativeHeatMellinZetaFamilyData}
    {shortTimeRegion longTimeRegion : Set Real}
    (data : ReferenceNuclearHeatFinitePartSelectedTraceCanonicalSchwarzAssemblyData
      (E := E) sliceMeasure shortCutoffFilter longCutoffFilter
        referenceOperator selectedTrace family shortTimeRegion longTimeRegion) :
    ReferenceNuclearHeatFinitePartCanonicalSchwarzAssemblyData
      (E := E) sliceMeasure shortCutoffFilter longCutoffFilter family
        shortTimeRegion longTimeRegion where
  nuclear := data.nuclear
  countertermContribution := data.countertermContribution
  spectralBoundary := data.spectralBoundary.toFullySpectralBoundaryLimits
  logDeterminant_eq := data.logDeterminant_eq
  zetaCanonicalSchwarz := data.zetaCanonicalSchwarz

/-- The scalar at the end of the canonical endpoint chain is definitionally the
selected chart trace. -/
@[simp] theorem generatedLogarithmicTrace_eq_selectedTrace
    {sliceMeasure : Measure Slice} [IsProbabilityMeasure sliceMeasure]
    {shortCutoffFilter : Filter ShortCutoff} [NeBot shortCutoffFilter]
    {longCutoffFilter : Filter LongCutoff} [NeBot longCutoffFilter]
    {referenceOperator : Real → E →L[Real] E}
    {selectedTrace : IntrinsicLogarithmicDerivativeTraceData referenceOperator}
    {family : RelativeHeatMellinZetaFamilyData}
    {shortTimeRegion longTimeRegion : Set Real}
    (data : ReferenceNuclearHeatFinitePartSelectedTraceCanonicalSchwarzAssemblyData
      (E := E) sliceMeasure shortCutoffFilter longCutoffFilter
        referenceOperator selectedTrace family shortTimeRegion longTimeRegion)
    (parameter : Real) :
    data.toCanonicalSchwarzAssembly.spectralBoundary.toCollapsedBoundaryLimits.
        toCollapsedBoundary.toBoundaryMatching.toOperatorIdentity.
          logarithmicTrace parameter =
      selectedTrace.trace parameter :=
  data.spectralBoundary.generatedLogarithmicTrace_eq_selectedTrace parameter

/-- Canonical Schwarz reflection forces reality of the regularized derivative
for the selected reference family. -/
theorem zetaPrimeAtZero_im_eq_zero
    {sliceMeasure : Measure Slice} [IsProbabilityMeasure sliceMeasure]
    {shortCutoffFilter : Filter ShortCutoff} [NeBot shortCutoffFilter]
    {longCutoffFilter : Filter LongCutoff} [NeBot longCutoffFilter]
    {referenceOperator : Real → E →L[Real] E}
    {selectedTrace : IntrinsicLogarithmicDerivativeTraceData referenceOperator}
    {family : RelativeHeatMellinZetaFamilyData}
    {shortTimeRegion longTimeRegion : Set Real}
    (data : ReferenceNuclearHeatFinitePartSelectedTraceCanonicalSchwarzAssemblyData
      (E := E) sliceMeasure shortCutoffFilter longCutoffFilter
        referenceOperator selectedTrace family shortTimeRegion longTimeRegion)
    (parameter : Real) :
    (family.zetaPrimeAtZero parameter).im = 0 :=
  data.toCanonicalSchwarzAssembly.zetaPrimeAtZero_im_eq_zero parameter

/-- The standalone reference coefficient is generated directly from the
selected intrinsic trace. -/
theorem connectionCoefficient_eq_neg_selectedTrace
    {sliceMeasure : Measure Slice} [IsProbabilityMeasure sliceMeasure]
    {shortCutoffFilter : Filter ShortCutoff} [NeBot shortCutoffFilter]
    {longCutoffFilter : Filter LongCutoff} [NeBot longCutoffFilter]
    {referenceOperator : Real → E →L[Real] E}
    {selectedTrace : IntrinsicLogarithmicDerivativeTraceData referenceOperator}
    {family : RelativeHeatMellinZetaFamilyData}
    {shortTimeRegion longTimeRegion : Set Real}
    (data : ReferenceNuclearHeatFinitePartSelectedTraceCanonicalSchwarzAssemblyData
      (E := E) sliceMeasure shortCutoffFilter longCutoffFilter
        referenceOperator selectedTrace family shortTimeRegion longTimeRegion)
    (parameter : Real) :
    P0EFTJanusProgramPRelativeZetaDeterminantConnection4D.
        relativeZetaConnectionCoefficient family.toZetaFamily parameter =
      -(selectedTrace.trace parameter : Complex) := by
  calc
    P0EFTJanusProgramPRelativeZetaDeterminantConnection4D.
        relativeZetaConnectionCoefficient family.toZetaFamily parameter =
      -(data.toCanonicalSchwarzAssembly.spectralBoundary.
          toCollapsedBoundaryLimits.toCollapsedBoundary.toBoundaryMatching.
            toOperatorIdentity.logarithmicTrace parameter : Complex) :=
      data.toCanonicalSchwarzAssembly.
        connectionCoefficient_eq_neg_logarithmicTrace parameter
    _ = -(selectedTrace.trace parameter : Complex) := by
      rw [data.generatedLogarithmicTrace_eq_selectedTrace parameter]

/-- Public selected-trace canonical-Schwarz checkpoint. -/
theorem reference_nuclear_heat_finite_part_selected_trace_canonical_schwarz_assembly_gate
    (sliceMeasure : Measure Slice) [IsProbabilityMeasure sliceMeasure]
    (shortCutoffFilter : Filter ShortCutoff) [NeBot shortCutoffFilter]
    (longCutoffFilter : Filter LongCutoff) [NeBot longCutoffFilter]
    (referenceOperator : Real → E →L[Real] E)
    (selectedTrace : IntrinsicLogarithmicDerivativeTraceData referenceOperator)
    (family : RelativeHeatMellinZetaFamilyData)
    (shortTimeRegion longTimeRegion : Set Real)
    (data : ReferenceNuclearHeatFinitePartSelectedTraceCanonicalSchwarzAssemblyData
      (E := E) sliceMeasure shortCutoffFilter longCutoffFilter
        referenceOperator selectedTrace family shortTimeRegion longTimeRegion) :
    (∀ parameter,
      Set.EqOn (family.continuation parameter).zeta
        (P0EFTJanusProgramPRelativeHeatMellinZetaSchwarzReflection4D.
          schwarzReflect (family.continuation parameter).zeta)
        (data.zetaCanonicalSchwarz parameter).domain) ∧
    (∀ parameter,
      (family.zetaPrimeAtZero parameter).im = 0) ∧
    (∀ parameter,
      P0EFTJanusProgramPRelativeZetaDeterminantConnection4D.
          relativeZetaConnectionCoefficient family.toZetaFamily parameter =
        -(selectedTrace.trace parameter : Complex)) :=
  ⟨fun parameter =>
      (data.zetaCanonicalSchwarz parameter).zeta_eqOn_schwarz_domain,
    data.zetaPrimeAtZero_im_eq_zero,
    data.connectionCoefficient_eq_neg_selectedTrace⟩

end ReferenceNuclearHeatFinitePartSelectedTraceCanonicalSchwarzAssemblyData

end
end P0EFTJanusProgramPReferenceNuclearHeatFinitePartSelectedTraceCanonicalSchwarzAssembly4D
end JanusFormal
