import JanusFormal.Branches.FundamentalGeometryPVariationalPrinciple.Gates.P0EFTJanusProgramPGlobalCandidateANormalBoundaryActionGermCalculus4D

/-!
# From the normal-boundary integrand germ to the action germ

The remaining geometric comparison in H10 is pointwise: the completed mean
curvature, induced density and orientation sign must reproduce the historical
Gauss--Weingarten GHY integrand on one admissible neighbourhood.  Integration
and the already established two-sheet multiplicity must not be repeated as a
new hypothesis.

This module supplies that formal passage.  A pointwise integrand equality on an
open parameter domain gives equality of the integrated actions on the same
domain and therefore equality of their two Fréchet derivatives at the anchor.
-/

namespace JanusFormal
namespace P0EFTJanusProgramPGlobalCandidateANormalBoundaryIntegrandGermClosure4D

set_option autoImplicit false
set_option maxHeartbeats 1200000
set_option synthInstance.maxHeartbeats 600000

noncomputable section

open Filter Set Topology MeasureTheory
open scoped Topology

universe u v

variable {Variation : Type u}
  [NormedAddCommGroup Variation]
  [NormedSpace Real Variation]

variable {Boundary : Type v}
  [MeasurableSpace Boundary]

open P0EFTJanusProgramPGlobalCandidateANormalBoundaryActionGermCalculus4D

/-- Pointwise agreement of two integrands on one open variation domain. -/
structure SameRealIntegrandGermAt
    (completed historical : Variation → Boundary → Real)
    (base : Variation) : Type u where
  domain : Set Variation
  isOpen_domain : IsOpen domain
  base_mem_domain : base ∈ domain
  eqOn_domain : ∀ variation, variation ∈ domain →
    ∀ boundary, completed variation boundary = historical variation boundary

/-- The integrated one-sheet actions associated with a pair of integrands. -/
def integratedRealBoundaryAction
    (measure : Measure Boundary)
    (integrand : Variation → Boundary → Real) : Variation → Real :=
  fun variation => ∫ boundary, integrand variation boundary ∂measure

/-- Pointwise equality of the integrands produces equality of their one-sheet
integrals. -/
theorem SameRealIntegrandGermAt.integrated_eqOn
    {completed historical : Variation → Boundary → Real}
    {base : Variation}
    (germ : SameRealIntegrandGermAt completed historical base)
    (measure : Measure Boundary) :
    Set.EqOn
      (integratedRealBoundaryAction measure completed)
      (integratedRealBoundaryAction measure historical)
      germ.domain := by
  intro variation hVariation
  apply integral_congr_ae
  filter_upwards [] with boundary
  exact germ.eqOn_domain variation hVariation boundary

/-- The one-sheet integral comparison is itself a same-action germ. -/
def SameRealIntegrandGermAt.integratedActionGerm
    {completed historical : Variation → Boundary → Real}
    {base : Variation}
    (germ : SameRealIntegrandGermAt completed historical base)
    (measure : Measure Boundary) :
    SameRealActionGermAt
      (integratedRealBoundaryAction measure completed)
      (integratedRealBoundaryAction measure historical)
      base where
  domain := germ.domain
  isOpen_domain := germ.isOpen_domain
  base_mem_domain := germ.base_mem_domain
  eqOn_domain := germ.integrated_eqOn measure

/-- Multiplying both actions by the fixed two-sheet factor preserves the same
action germ. -/
def sameRealActionGermAtConstMul
    {completed historical : Variation → Real}
    {base : Variation}
    (germ : SameRealActionGermAt completed historical base)
    (factor : Real) :
    SameRealActionGermAt
      (fun variation => factor * completed variation)
      (fun variation => factor * historical variation)
      base where
  domain := germ.domain
  isOpen_domain := germ.isOpen_domain
  base_mem_domain := germ.base_mem_domain
  eqOn_domain := by
    intro variation hVariation
    exact congrArg (fun value : Real => factor * value)
      (germ.eqOn_domain hVariation)

/-- The two-sheet action germ generated by a pointwise integrand germ.  The
factor is explicit so the theorem can also be reused for oriented sums other
than the canonical factor `2`. -/
def SameRealIntegrandGermAt.integratedTwoSheetActionGerm
    {completed historical : Variation → Boundary → Real}
    {base : Variation}
    (germ : SameRealIntegrandGermAt completed historical base)
    (measure : Measure Boundary)
    (sheetFactor : Real := 2) :
    SameRealActionGermAt
      (fun variation => sheetFactor *
        integratedRealBoundaryAction measure completed variation)
      (fun variation => sheetFactor *
        integratedRealBoundaryAction measure historical variation)
      base :=
  sameRealActionGermAtConstMul (germ.integratedActionGerm measure) sheetFactor

/-- Equality of the completed and historical two-sheet Hessians follows from
pointwise equality of the integrands; it is not a separate H10 assumption. -/
theorem SameRealIntegrandGermAt.integratedTwoSheet_second_fderiv_eq
    {completed historical : Variation → Boundary → Real}
    {base : Variation}
    (germ : SameRealIntegrandGermAt completed historical base)
    (measure : Measure Boundary)
    (sheetFactor : Real := 2) :
    fderiv Real
        (fun state => fderiv Real
          (fun variation => sheetFactor *
            integratedRealBoundaryAction measure completed variation)
          state)
        base =
      fderiv Real
        (fun state => fderiv Real
          (fun variation => sheetFactor *
            integratedRealBoundaryAction measure historical variation)
          state)
        base :=
  (germ.integratedTwoSheetActionGerm measure sheetFactor).second_fderiv_eq

/-- Public H10 integration gate. -/
def candidate_a_normal_boundary_integrand_germ_closure_gate
    {completed historical : Variation → Boundary → Real}
    {base : Variation}
    (germ : SameRealIntegrandGermAt completed historical base)
    (measure : Measure Boundary) :
    SameRealActionGermAt
      (fun variation => 2 *
        integratedRealBoundaryAction measure completed variation)
      (fun variation => 2 *
        integratedRealBoundaryAction measure historical variation)
      base :=
  germ.integratedTwoSheetActionGerm measure 2

end
end P0EFTJanusProgramPGlobalCandidateANormalBoundaryIntegrandGermClosure4D
end JanusFormal
