import JanusFormal.Branches.FundamentalGeometryPVariationalPrinciple.Gates.P0EFTJanusProgramPRelativeZetaReferenceAtlasDerivation4D
import JanusFormal.Branches.FundamentalGeometryPVariationalPrinciple.Gates.P0EFTJanusProgramPUnitaryActualZetaFamily4D

/-!
# Reference-atlas derivation from one unitary actual zeta family

`RelativeZetaReferenceAtlasDerivationData` accepts an actual zeta family and a
separate proof that its connection coefficient is zero.  For an actual family
produced by unitary heat conjugation, both are already outputs of one
`UnitaryActualZetaFamilyData`.

This file removes that duplication.  The remaining inputs are exactly the base
and local reference zeta families, their standalone inverse-trace identities,
and the analytic relative-difference comparisons.
-/

namespace JanusFormal
namespace P0EFTJanusProgramPUnitaryRelativeZetaReferenceAtlasDerivation4D

set_option autoImplicit false
noncomputable section

open P0EFTJanusProgramPRelativeHeatMellinAnalyticDifferenceFamily4D
open P0EFTJanusProgramPRelativeHeatMellinZetaFamily4D
open P0EFTJanusProgramPRelativeZetaDeterminantConnection4D
open P0EFTJanusProgramPRelativeZetaReferenceAtlasDerivation4D
open P0EFTJanusProgramPUnitaryActualZetaFamily4D

variable {Index E : Type*}
  [NormedAddCommGroup E] [InnerProductSpace Real E]

/-- Reference-atlas data whose actual side is generated by one unitary nuclear
heat frame. -/
structure UnitaryRelativeZetaReferenceAtlasDerivationData
    (Index : Type*) (E : Type*)
    [NormedAddCommGroup E] [InnerProductSpace Real E] where
  actual : UnitaryActualZetaFamilyData (E := E)
  baseRelativeFamily : RelativeHeatMellinZetaFamilyData
  baseReferenceFamily : RelativeHeatMellinZetaFamilyData
  baseReferenceTrace : Real → Real
  baseDifference : RelativeHeatMellinAnalyticDifferenceFamilyData
    baseRelativeFamily actual.family baseReferenceFamily
  baseReferenceCoefficient : ∀ parameter,
    relativeZetaConnectionCoefficient baseReferenceFamily.toZetaFamily parameter =
      -baseReferenceTrace parameter
  localRelativeFamily : Index → RelativeHeatMellinZetaFamilyData
  localReferenceFamily : Index → RelativeHeatMellinZetaFamilyData
  localReferenceTrace : Index → Real → Real
  localDifference : ∀ index,
    RelativeHeatMellinAnalyticDifferenceFamilyData
      (localRelativeFamily index) actual.family (localReferenceFamily index)
  localReferenceCoefficient : ∀ index parameter,
    relativeZetaConnectionCoefficient
        (localReferenceFamily index).toZetaFamily parameter =
      -localReferenceTrace index parameter

namespace UnitaryRelativeZetaReferenceAtlasDerivationData

/-- Forget the unitary construction after deriving its actual family and zero
coefficient. -/
def toReferenceAtlasDerivation
    (data : UnitaryRelativeZetaReferenceAtlasDerivationData Index E) :
    RelativeZetaReferenceAtlasDerivationData Index where
  actualFamily := data.actual.family
  actualCoefficient_zero := data.actual.connectionCoefficient_zero
  baseRelativeFamily := data.baseRelativeFamily
  baseReferenceFamily := data.baseReferenceFamily
  baseReferenceTrace := data.baseReferenceTrace
  baseDifference := data.baseDifference
  baseReferenceCoefficient := data.baseReferenceCoefficient
  localRelativeFamily := data.localRelativeFamily
  localReferenceFamily := data.localReferenceFamily
  localReferenceTrace := data.localReferenceTrace
  localDifference := data.localDifference
  localReferenceCoefficient := data.localReferenceCoefficient

/-- Base relative coefficient equals the base reference trace. -/
theorem baseCoefficient_eq_referenceTrace
    (data : UnitaryRelativeZetaReferenceAtlasDerivationData Index E)
    (parameter : Real) :
    relativeZetaConnectionCoefficient data.baseRelativeFamily.toZetaFamily
        parameter = data.baseReferenceTrace parameter :=
  data.toReferenceAtlasDerivation.baseCoefficient_eq_referenceTrace parameter

/-- Every local relative coefficient equals its reference trace. -/
theorem localCoefficient_eq_referenceTrace
    (data : UnitaryRelativeZetaReferenceAtlasDerivationData Index E)
    (index : Index) (parameter : Real) :
    relativeZetaConnectionCoefficient
        (data.localRelativeFamily index).toZetaFamily parameter =
      data.localReferenceTrace index parameter :=
  data.toReferenceAtlasDerivation.localCoefficient_eq_referenceTrace index
    parameter

/-- Every local relative determinant is the actual determinant divided by its
reference determinant. -/
theorem localDeterminant_eq_div
    (data : UnitaryRelativeZetaReferenceAtlasDerivationData Index E)
    (index : Index) (parameter : Real) :
    relativeHeatMellinZetaFamilyDeterminant
        (data.localRelativeFamily index) parameter =
      relativeHeatMellinZetaFamilyDeterminant data.actual.family parameter /
        relativeHeatMellinZetaFamilyDeterminant
          (data.localReferenceFamily index) parameter :=
  data.toReferenceAtlasDerivation.localDeterminant_eq_div index parameter

/-- The actual determinant factor is independent of the family parameter. -/
theorem actualDeterminant_eq_base
    (data : UnitaryRelativeZetaReferenceAtlasDerivationData Index E)
    (parameter : Real) :
    relativeHeatMellinZetaFamilyDeterminant data.actual.family parameter =
      relativeHeatMellinZetaDeterminant data.actual.baseContinuation :=
  data.actual.determinant_eq_base parameter

/-- Public unitary actual/reference atlas checkpoint. -/
theorem unitary_relative_zeta_reference_atlas_derivation_gate
    (data : UnitaryRelativeZetaReferenceAtlasDerivationData Index E) :
    (∀ parameter,
      relativeZetaConnectionCoefficient data.actual.family.toZetaFamily
          parameter = 0) ∧
    (∀ parameter,
      relativeZetaConnectionCoefficient data.baseRelativeFamily.toZetaFamily
          parameter = data.baseReferenceTrace parameter) ∧
    (∀ index parameter,
      relativeZetaConnectionCoefficient
          (data.localRelativeFamily index).toZetaFamily parameter =
        data.localReferenceTrace index parameter) ∧
    (∀ index parameter,
      relativeHeatMellinZetaFamilyDeterminant
          (data.localRelativeFamily index) parameter =
        relativeHeatMellinZetaFamilyDeterminant data.actual.family parameter /
          relativeHeatMellinZetaFamilyDeterminant
            (data.localReferenceFamily index) parameter) :=
  ⟨data.actual.connectionCoefficient_zero,
    data.baseCoefficient_eq_referenceTrace,
    data.localCoefficient_eq_referenceTrace,
    data.localDeterminant_eq_div⟩

end UnitaryRelativeZetaReferenceAtlasDerivationData

end
end P0EFTJanusProgramPUnitaryRelativeZetaReferenceAtlasDerivation4D
end JanusFormal
