import JanusFormal.Branches.FundamentalGeometryPVariationalPrinciple.Gates.P0EFTJanusMappingTorusCanonicalPhysicalScalarEulerLinearity4D
import JanusFormal.Branches.FundamentalGeometryPVariationalPrinciple.Gates.P0EFTJanusMappingTorusCanonicalTotalR4BallParametrization4D

/-!
# Physical scalar Euler globalization reduced to overlap compatibility

The concrete total holonomic charts are local diffeomorphisms.  Therefore a
chartwise continuous scalar family which is compatible on overlaps defines a
continuous global scalar function: continuity can be reflected through any one
of the local chart maps.

Linearity of the physical Euler residual is already proved separately.  Hence
the sole remaining globalization datum is the coordinate-invariance statement
that the local residuals agree whenever two canonical holonomic charts represent
the same quotient point.
-/

namespace JanusFormal
namespace P0EFTJanusMappingTorusCanonicalPhysicalScalarEulerCompatibilityClosure4D

set_option autoImplicit false
noncomputable section

open Set Topology
open scoped Manifold ContDiff
open P0EFTJanusMappingTorusQuotient
open P0EFTJanusMappingTorusSmoothAtlasFrontier
open P0EFTJanusMappingTorusSmoothQuotientManifold
open P0EFTJanusMappingTorusSmoothFieldDescent4D
open P0EFTJanusMappingTorusGeneralLorentzMetricLocalLeviCivitaPatch4D
open P0EFTJanusMappingTorusCanonicalHolonomicChartBallRealization4D
open P0EFTJanusMappingTorusCanonicalTotalR4BallParametrization4D
open P0EFTJanusMappingTorusCanonicalPhysicalScalarEulerAtlas4D
open P0EFTJanusMappingTorusCanonicalPhysicalScalarEulerLinearity4D

variable (period : Real) (hPeriod : period ≠ 0)

private abbrev sphereData := reflectedSphereData period hPeriod
private abbrev EffectiveCover := MappingTorusCover (sphereData period hPeriod)
private abbrev EffectiveQuotient := MappingTorus (sphereData period hPeriod)

local instance effectiveCoverChartedSpace :
    ChartedSpace CoverModel (EffectiveCover period hPeriod) :=
  reflectedSphereCoverChartedSpace period hPeriod

local instance effectiveCoverIsManifold :
    IsManifold coverModelWithCorners ω (EffectiveCover period hPeriod) :=
  reflectedSphereCover_isManifold period hPeriod

@[implicit_reducible] local instance effectiveQuotientChartedSpace :
    ChartedSpace CoverModel (EffectiveQuotient period hPeriod) :=
  reflectedSphereQuotientChartedSpace period hPeriod

local instance effectiveQuotientIsManifold :
    IsManifold coverModelWithCorners ω (EffectiveQuotient period hPeriod) :=
  reflectedSphereQuotient_isManifold period hPeriod

/-- A canonical total holonomic coordinate map through a point, retaining the
local-diffeomorphism theorem used to construct its frame. -/
structure CanonicalPhysicalScalarEulerLocalDiffeomorphWitness
    (point : EffectiveQuotient period hPeriod) where
  coordinateMap : Vector4 → EffectiveQuotient period hPeriod
  isLocalDiffeomorph : IsLocalDiffeomorph
    (modelWithCornersSelf Real Vector4) coverModelWithCorners ∞ coordinateMap
  at_zero : coordinateMap 0 = point

/-- The public ball parametrization supplies a local-diffeomorphism witness at
every quotient point. -/
noncomputable def canonicalPhysicalScalarEulerLocalDiffeomorphWitness
    (point : EffectiveQuotient period hPeriod) :
    CanonicalPhysicalScalarEulerLocalDiffeomorphWitness
      period hPeriod point := by
  obtain ⟨anchor, rfl⟩ :=
    mappingTorusMk_surjective (sphereData period hPeriod) point
  let center := extChartAt coverModelWithCorners anchor anchor
  obtain ⟨radius, hRadius, hBall⟩ := Metric.isOpen_iff.1
    (isOpen_extChartAt_target (I := coverModelWithCorners) anchor) center
      (mem_extChartAt_target (I := coverModelWithCorners) anchor)
  let parametrization := totalR4BallParametrization center radius hRadius
  let coordinateMap := realizedBallQuotientCoordinateMap
    period hPeriod anchor parametrization
  have hCoordinateMap : IsLocalDiffeomorph
      (modelWithCornersSelf Real Vector4) coverModelWithCorners ∞ coordinateMap :=
    realizedBallQuotientCoordinateMap_isLocalDiffeomorph
      period hPeriod anchor parametrization hBall
  refine ⟨coordinateMap, hCoordinateMap, ?_⟩
  exact realizedBallQuotientCoordinateMap_zero
    period hPeriod anchor parametrization

/-- The holonomic patch generated by the retained local diffeomorphism. -/
noncomputable def CanonicalPhysicalScalarEulerLocalDiffeomorphWitness.patch
    {point : EffectiveQuotient period hPeriod}
    (witness : CanonicalPhysicalScalarEulerLocalDiffeomorphWitness
      period hPeriod point) :
    SmoothHolonomicFrameChart4 period hPeriod :=
  smoothHolonomicFrameChart4OfLocalDiffeomorph
    period hPeriod witness.coordinateMap witness.isLocalDiffeomorph

@[simp] theorem CanonicalPhysicalScalarEulerLocalDiffeomorphWitness.patch_coordinateMap
    {point : EffectiveQuotient period hPeriod}
    (witness : CanonicalPhysicalScalarEulerLocalDiffeomorphWitness
      period hPeriod point) :
    witness.patch.coordinateMap = witness.coordinateMap :=
  rfl

/-- Continuity can be reflected through a local homeomorphism. -/
private theorem continuousAt_of_isLocalHomeomorph_comp
    {X Y Z : Type*}
    [TopologicalSpace X] [TopologicalSpace Y] [TopologicalSpace Z]
    {localMap : X → Y} (hLocal : IsLocalHomeomorph localMap)
    {function : Y → Z} {point : X}
    (hComposition : ContinuousAt (function ∘ localMap) point) :
    ContinuousAt function (localMap point) := by
  rw [← hLocal.map_nhds_eq point]
  exact Filter.tendsto_map'_iff.mpr hComposition

/-- Overlap compatibility implies continuity of the selected global physical
Euler residual. -/
theorem canonicalPhysicalScalarEulerGlobalResidual_continuous_of_compatible
    (massSquared : Real)
    (field : SmoothScalarField period hPeriod)
    (hCompatible : CanonicalPhysicalScalarEulerAtlasCompatible
      period hPeriod massSquared field) :
    Continuous (canonicalPhysicalScalarEulerGlobalResidual
      period hPeriod massSquared field) := by
  rw [continuous_iff_continuousAt]
  intro point
  let witness := canonicalPhysicalScalarEulerLocalDiffeomorphWitness
    period hPeriod point
  let patch := witness.patch
  have hComposition :
      canonicalPhysicalScalarEulerGlobalResidual
          period hPeriod massSquared field ∘ witness.coordinateMap =
        canonicalPhysicalScalarEulerAtlasResidual
          period hPeriod massSquared field patch := by
    funext coordinate
    simpa [patch] using
      canonicalPhysicalScalarEulerGlobalResidual_eq_chart
        period hPeriod massSquared field hCompatible patch coordinate
  have hLocalContinuous : ContinuousAt
      (canonicalPhysicalScalarEulerGlobalResidual
        period hPeriod massSquared field ∘ witness.coordinateMap) 0 := by
    rw [hComposition]
    exact (canonicalPhysicalScalarEulerAtlasResidual_contDiff
      period hPeriod massSquared field patch).continuous.continuousAt
  have hAtImage := continuousAt_of_isLocalHomeomorph_comp
    witness.isLocalDiffeomorph.isLocalHomeomorph hLocalContinuous
  rwa [witness.at_zero] at hAtImage

/-- The exact remaining physical Euler-globalization input. -/
structure CanonicalPhysicalScalarEulerCompatibilityData
    (massSquared : Real) where
  compatible : ∀ field : SmoothScalarField period hPeriod,
    CanonicalPhysicalScalarEulerAtlasCompatible
      period hPeriod massSquared field

namespace CanonicalPhysicalScalarEulerCompatibilityData

/-- Compatibility alone constructs the reduced globalization package; continuity
and linearity are filled by theorem. -/
def toGlobalizationData
    (data : CanonicalPhysicalScalarEulerCompatibilityData
      period hPeriod massSquared) :
    CanonicalPhysicalScalarEulerGlobalizationData
      period hPeriod massSquared where
  compatible := data.compatible
  continuous := fun field =>
    canonicalPhysicalScalarEulerGlobalResidual_continuous_of_compatible
      period hPeriod massSquared field (data.compatible field)

/-- Genuine smooth-core-to-bulk-`L²` operator from overlap compatibility alone. -/
def toBulkL2LinearMap
    (data : CanonicalPhysicalScalarEulerCompatibilityData
      period hPeriod massSquared) :
    SmoothScalarField period hPeriod →ₗ[Real]
      CanonicalPhysicalBulkL2 period hPeriod :=
  data.toGlobalizationData.toBulkL2LinearMap

/-- Conversion to the original full operator-data interface. -/
def toOperatorData
    (data : CanonicalPhysicalScalarEulerCompatibilityData
      period hPeriod massSquared) :
    CanonicalPhysicalScalarEulerGlobalOperatorData
      period hPeriod massSquared :=
  data.toGlobalizationData.toOperatorData

/-- Euler globalization certificate: only overlap compatibility is assumed. -/
theorem certificate
    (data : CanonicalPhysicalScalarEulerCompatibilityData
      period hPeriod massSquared) :
    (∀ field : SmoothScalarField period hPeriod,
      Continuous (canonicalPhysicalScalarEulerGlobalResidual
        period hPeriod massSquared field)) ∧
      (∀ first second : SmoothScalarField period hPeriod,
        canonicalPhysicalScalarEulerGlobalResidual period hPeriod massSquared
            (first + second) =
          canonicalPhysicalScalarEulerGlobalResidual
              period hPeriod massSquared first +
            canonicalPhysicalScalarEulerGlobalResidual
              period hPeriod massSquared second) ∧
      (∀ scalar field,
        canonicalPhysicalScalarEulerGlobalResidual period hPeriod massSquared
            (scalar • field) =
          scalar • canonicalPhysicalScalarEulerGlobalResidual
            period hPeriod massSquared field) :=
  ⟨fun field =>
      canonicalPhysicalScalarEulerGlobalResidual_continuous_of_compatible
        period hPeriod massSquared field (data.compatible field),
    canonicalPhysicalScalarEulerGlobalResidual_add period hPeriod massSquared,
    canonicalPhysicalScalarEulerGlobalResidual_smul period hPeriod massSquared⟩

end CanonicalPhysicalScalarEulerCompatibilityData

end
end P0EFTJanusMappingTorusCanonicalPhysicalScalarEulerCompatibilityClosure4D
end JanusFormal
