import JanusFormal.Branches.FundamentalGeometryPVariationalPrinciple.Gates.P0EFTJanusProgramPCandidateASectorModeMultiplicity4D

/-!
# Numerical multiplicity profile of the five Candidate-A sectors

For concrete applications it is often preferable to specify five natural
numbers rather than five unrelated finite types.  This file assigns `Fin n` to
each physical sector and packages the resulting dependent mode family.

The generic sector assembly remains available for geometrically meaningful
index types.  The numerical profile is only a canonical coordinate model and
does not change the actual vectors or the coupled Hessian.
-/

namespace JanusFormal
namespace P0EFTJanusProgramPCandidateASectorMultiplicityProfile4D

set_option autoImplicit false
noncomputable section

open P0EFTJanusProgramPCandidateAZeroModeSector4D
open P0EFTJanusProgramPGlobalCandidateANamedZeroModeSectors4D
open P0EFTJanusProgramPCandidateASectorModeAssembly4D
open P0EFTJanusProgramPCandidateASectorModeMultiplicity4D

local instance candidateASectorModeFintype
    (types : CandidateASectorModeTypes)
    (sector : CandidateAZeroModeSector) : Fintype (types.Mode sector) :=
  types.modeFintype sector

/-- Five numerical multiplicities, one for each D10-free physical sector. -/
structure CandidateASectorMultiplicityProfile where
  metricDiffeomorphism : Nat
  abelianGauge : Nat
  primitiveSpinCMatter : Nat
  longitudinalLL : Nat
  boundaryFiniteBV : Nat

namespace CandidateASectorMultiplicityProfile

/-- Numerical multiplicity selected by a sector label. -/
def multiplicity
    (profile : CandidateASectorMultiplicityProfile) :
    CandidateAZeroModeSector → Nat
  | .metricDiffeomorphism => profile.metricDiffeomorphism
  | .abelianGauge => profile.abelianGauge
  | .primitiveSpinCMatter => profile.primitiveSpinCMatter
  | .longitudinalLL => profile.longitudinalLL
  | .boundaryFiniteBV => profile.boundaryFiniteBV

/-- Canonical finite index type of one sector. -/
def Mode
    (profile : CandidateASectorMultiplicityProfile)
    (sector : CandidateAZeroModeSector) : Type :=
  Fin (profile.multiplicity sector)

noncomputable instance modeFintype
    (profile : CandidateASectorMultiplicityProfile)
    (sector : CandidateAZeroModeSector) :
    Fintype (profile.Mode sector) :=
  by
    change Fintype (Fin (profile.multiplicity sector))
    infer_instance

/-- Canonical dependent mode-type packet generated by the five numbers. -/
def modeTypes (profile : CandidateASectorMultiplicityProfile) :
    CandidateASectorModeTypes where
  Mode := profile.Mode
  modeFintype := fun sector => profile.modeFintype sector

@[simp]
theorem mode_card
    (profile : CandidateASectorMultiplicityProfile)
    (sector : CandidateAZeroModeSector) :
    Fintype.card ((profile.modeTypes).Mode sector) =
      profile.multiplicity sector := by
  change Fintype.card (Fin (profile.multiplicity sector)) =
    profile.multiplicity sector
  exact Fintype.card_fin _

/-- The canonical classification reports exactly the numerical profile. -/
theorem classification_multiplicity
    (profile : CandidateASectorMultiplicityProfile)
    (sector : CandidateAZeroModeSector) :
    profile.modeTypes.classification.multiplicity sector =
      profile.multiplicity sector := by
  rw [candidateASectorMultiplicity_eq_card]
  exact profile.mode_card sector

/-- The total mode type has cardinality equal to the sum of the five numerical
multiplicities. -/
theorem globalMode_card
    (profile : CandidateASectorMultiplicityProfile) :
    Fintype.card profile.modeTypes.GlobalMode =
      ∑ sector : CandidateAZeroModeSector,
        profile.multiplicity sector := by
  rw [candidateASectorGlobalMode_card]
  apply Finset.sum_congr rfl
  intro sector _
  exact profile.mode_card sector

/-- Public numerical-profile checkpoint. -/
theorem candidateA_sector_multiplicity_profile_gate
    (profile : CandidateASectorMultiplicityProfile) :
    (∀ sector,
      profile.modeTypes.classification.multiplicity sector =
        profile.multiplicity sector) ∧
      Fintype.card profile.modeTypes.GlobalMode =
        ∑ sector : CandidateAZeroModeSector,
          profile.multiplicity sector :=
  ⟨profile.classification_multiplicity, profile.globalMode_card⟩

end CandidateASectorMultiplicityProfile

end
end P0EFTJanusProgramPCandidateASectorMultiplicityProfile4D
end JanusFormal
