import Mathlib.MeasureTheory.Integral.Prod
import JanusFormal.Branches.FundamentalGeometryPVariationalPrinciple.Gates.P0EFTJanusMappingTorusCanonicalPhysicalScalarEulerCanonicalNormalSplit4D

/-!
# Normal Green density from a universal half-collar transport

The factor `2` in the oriented cut-boundary Green formula is geometric, not
field dependent.  Isolate it once in a transport from the full weighted normal
coarea domain to the positive unit collar.

A transport package states, for every integrable scalar function `f` on the
positive collar,

`∫ f ∘ transport dμ_product = 2 ∫ f dμ_collar`.

The canonical normal Green density is then defined, rather than supplied, as
minus the pullback of the cutoff-collar densitized divergence.  Its
integrability and its total integral are automatic.  The only PDE-specific
Green condition left in this layer is cancellation of the induced tangential
remainder after integration over the boundary base.
-/

namespace JanusFormal
namespace P0EFTJanusMappingTorusCanonicalPhysicalScalarEulerNormalHalfCollarTransport4D

set_option autoImplicit false
noncomputable section

open scoped Manifold ContDiff ENNReal Interval
open MeasureTheory Set Topology Filter Function
open P0EFTJanusMappingTorusGeneralHolonomicScalarDensity4D
open P0EFTJanusMappingTorusSmoothFieldDescent4D
open P0EFTJanusMappingTorusCanonicalPhysicalH1TraceBound4D
open P0EFTJanusMappingTorusCanonicalLatitudeCutoffCurrentLocalStokes4D
open P0EFTJanusMappingTorusCanonicalLatitudeCauchyJetProductCoarea4D
open P0EFTJanusMappingTorusCanonicalPhysicalScalarEulerCanonicalProductLocalDivergence4D
open P0EFTJanusMappingTorusCanonicalPhysicalScalarEulerCanonicalNormalSplit4D

variable (period : Real) (hPeriod : period ≠ 0)
variable {massSquared : Real}

local instance normalHalfCollarLatitudeBaseMeasureFinite :
    IsFiniteMeasure (canonicalLatitudeBaseMeasure period) :=
  canonicalLatitudeBaseMeasure_isFinite period

/-- Field-independent geometric transport from the full weighted normal product
to the positive unit collar. -/
structure CanonicalLatitudeNormalToHalfCollarTransportData where
  transport : CanonicalLatitudeCauchyJetProductParameter →
    CanonicalLatitudeCollarParameter
  integrable_comp : ∀ function : CanonicalLatitudeCollarParameter → Real,
    Integrable function (canonicalLatitudeCollarMeasure period) →
      Integrable (function ∘ transport)
        (canonicalLatitudeCauchyJetProductMeasure period)
  integral_comp : ∀ function : CanonicalLatitudeCollarParameter → Real,
    Integrable function (canonicalLatitudeCollarMeasure period) →
      (∫ parameter,
        function (transport parameter)
        ∂canonicalLatitudeCauchyJetProductMeasure period) =
      2 * ∫ parameter,
        function parameter ∂canonicalLatitudeCollarMeasure period

namespace CanonicalLatitudeNormalToHalfCollarTransportData

/-- Integral of a collar function as the canonical base/positive-normal
iterated integral. -/
theorem integral_eq_iterated
    (transportData : CanonicalLatitudeNormalToHalfCollarTransportData period)
    (function : CanonicalLatitudeCollarParameter → Real)
    (hFunction : Integrable function (canonicalLatitudeCollarMeasure period)) :
    (∫ parameter,
      function parameter ∂canonicalLatitudeCollarMeasure period) =
      ∫ base, (∫ normal in (0 : Real)..1,
        function (base, normal))
        ∂canonicalLatitudeBaseMeasure period := by
  unfold canonicalLatitudeCollarMeasure at hFunction ⊢
  rw [integral_prod function hFunction]
  apply integral_congr_ae
  exact Filter.Eventually.of_forall fun base => by
    change (∫ normal,
      function (base, normal) ∂canonicalLatitudeUnitNormalMeasure) =
      ∫ normal in (0 : Real)..1, function (base, normal)
    rw [intervalIntegral.integral_of_le (by norm_num : (0 : Real) ≤ 1)]
    rfl

end CanonicalLatitudeNormalToHalfCollarTransportData

/-- Cutoff-collar densitized divergence as a scalar function on the collar
parameter space. -/
def canonicalPhysicalScalarHalfCollarDivergenceDensity
    (massSquared : Real)
    (field test : SmoothScalarField period hPeriod)
    (parameter : CanonicalLatitudeCollarParameter) : Real :=
  cutoffCollarScalarCurrentDensitizedDivergence
    period hPeriod massSquared field test parameter.1 parameter.2

/-- Green data whose normal component is generated by the universal transport. -/
structure CanonicalPhysicalScalarEulerTransportedNormalDensityData
    (massSquared : Real) where
  waveNaturality :
    P0EFTJanusMappingTorusCanonicalPhysicalScalarEulerAtlasNaturality4D.CanonicalPhysicalScalarWaveAtlasNaturality
      period hPeriod
  transportData : CanonicalLatitudeNormalToHalfCollarTransportData period
  halfCollarDivergence_integrable :
    ∀ field test : SmoothScalarField period hPeriod,
      Integrable
        (canonicalPhysicalScalarHalfCollarDivergenceDensity
          period hPeriod massSquared field test)
        (canonicalLatitudeCollarMeasure period)
  tangential_base_integral_zero :
    ∀ field test normal,
      (∫ base,
        (canonicalPhysicalScalarEulerProductLocalDivergenceDensity
            period hPeriod field test (base, normal) +
          canonicalPhysicalScalarHalfCollarDivergenceDensity
            period hPeriod massSquared field test
            (transportData.transport (base, normal)))
        ∂canonicalLatitudeBaseMeasure period) = 0

namespace CanonicalPhysicalScalarEulerTransportedNormalDensityData

/-- Canonical transported normal Green density. -/
def normalDensity
    (data : CanonicalPhysicalScalarEulerTransportedNormalDensityData
      period hPeriod massSquared)
    (field test : SmoothScalarField period hPeriod)
    (parameter : CanonicalLatitudeCauchyJetProductParameter) : Real :=
  -canonicalPhysicalScalarHalfCollarDivergenceDensity
    period hPeriod massSquared field test
      (data.transportData.transport parameter)

/-- Integrability of the transported normal density. -/
theorem normalDensity_integrable
    (data : CanonicalPhysicalScalarEulerTransportedNormalDensityData
      period hPeriod massSquared)
    (field test : SmoothScalarField period hPeriod) :
    Integrable (data.normalDensity period hPeriod field test)
      (canonicalLatitudeCauchyJetProductMeasure period) := by
  unfold normalDensity
  exact (data.transportData.integrable_comp
    (canonicalPhysicalScalarHalfCollarDivergenceDensity
      period hPeriod massSquared field test)
    (data.halfCollarDivergence_integrable field test)).neg

/-- The universal transport produces exactly the required `-2` half-collar
integral. -/
theorem normal_integral_eq_halfCollar
    (data : CanonicalPhysicalScalarEulerTransportedNormalDensityData
      period hPeriod massSquared)
    (field test : SmoothScalarField period hPeriod) :
    (∫ parameter,
      data.normalDensity period hPeriod field test parameter
      ∂canonicalLatitudeCauchyJetProductMeasure period) =
      -2 *
        (∫ base, (∫ normal in (0 : Real)..1,
          cutoffCollarScalarCurrentDensitizedDivergence
            period hPeriod massSquared field test base normal)
          ∂canonicalLatitudeBaseMeasure period) := by
  let collarDensity := canonicalPhysicalScalarHalfCollarDivergenceDensity
    period hPeriod massSquared field test
  have hIntegrable := data.halfCollarDivergence_integrable field test
  have hTransport := data.transportData.integral_comp collarDensity hIntegrable
  have hIterated := data.transportData.integral_eq_iterated
    period collarDensity hIntegrable
  unfold normalDensity
  rw [integral_neg]
  change -(∫ parameter,
      collarDensity (data.transportData.transport parameter)
      ∂canonicalLatitudeCauchyJetProductMeasure period) = _
  rw [hTransport, hIterated]
  simp only [collarDensity, canonicalPhysicalScalarHalfCollarDivergenceDensity]
  ring

/-- Conversion to the canonical one-normal-component Green package. -/
def toCanonicalNormalSplitData
    (data : CanonicalPhysicalScalarEulerTransportedNormalDensityData
      period hPeriod massSquared) :
    CanonicalPhysicalScalarEulerCanonicalNormalSplitData
      period hPeriod massSquared where
  waveNaturality := data.waveNaturality
  normalDensity := data.normalDensity period hPeriod
  normalDensity_integrable := data.normalDensity_integrable period hPeriod
  tangential_base_integral_zero := by
    intro field test normal
    simpa [normalDensity, sub_neg_eq_add] using
      data.tangential_base_integral_zero field test normal
  normal_integral_eq_halfCollar := data.normal_integral_eq_halfCollar period hPeriod

/-- Correct dense physical Green core. -/
def greenCore
    (data : CanonicalPhysicalScalarEulerTransportedNormalDensityData
      period hPeriod massSquared) :=
  (data.toCanonicalNormalSplitData period hPeriod).greenCore period hPeriod

/-- Transported-normal Green certificate. -/
theorem certificate
    (data : CanonicalPhysicalScalarEulerTransportedNormalDensityData
      period hPeriod massSquared) :
    (∀ field test,
      Integrable (data.normalDensity period hPeriod field test)
        (canonicalLatitudeCauchyJetProductMeasure period)) ∧
      (∀ field test,
        (∫ parameter,
          data.normalDensity period hPeriod field test parameter
          ∂canonicalLatitudeCauchyJetProductMeasure period) =
        -2 *
          (∫ base, (∫ normal in (0 : Real)..1,
            cutoffCollarScalarCurrentDensitizedDivergence
              period hPeriod massSquared field test base normal)
            ∂canonicalLatitudeBaseMeasure period)) ∧
      (∀ field test,
        (∫ point,
          P0EFTJanusMappingTorusCanonicalPhysicalScalarEulerGreenL2Reduction4D.canonicalPhysicalScalarEulerSkewDensity
            period hPeriod massSquared field test point
          ∂P0EFTJanusMappingTorusCanonicalLorentzVolumeGluing4D.intrinsicCanonicalLorentzVolumeMeasure
            period hPeriod) =
        -2 * P0EFTJanusMappingTorusCutBulkCanonicalDivergenceMeasure4D.cutBulkCanonicalDivergenceMeasure
          period hPeriod massSquared field test Set.univ) :=
  ⟨data.normalDensity_integrable period hPeriod,
    data.normal_integral_eq_halfCollar period hPeriod,
    ((data.toCanonicalNormalSplitData period hPeriod).certificate period hPeriod).2.2.2⟩

end CanonicalPhysicalScalarEulerTransportedNormalDensityData

end
end P0EFTJanusMappingTorusCanonicalPhysicalScalarEulerNormalHalfCollarTransport4D
end JanusFormal
