import JanusFormal.Branches.FundamentalGeometryPEJetUniversality.Gates.P0EFTJanusMappingTorusStructuredJetGroupoid

/-!
# Extension across the effective deck isotropy stratification

The effective D8 deck groupoid has trivial stabilizers at every object.  Its
regular isotropy stratum is therefore the whole object space and its singular
stratum is empty.  This gate records the exact consequence for arbitrary
dependent data: restriction to the regular stratum is an equivalence, so
extension across the deck-isotropy stratification exists uniquely.

This statement concerns only isotropy generated by the effective deck action.
It does not construct or extend `Pin⁻`/`PinC`, frame, or other internal
structured-jet fibers.
-/

namespace JanusFormal
namespace P0EFTJanusMappingTorusDeckTrivialIsotropyExtension4D

set_option autoImplicit false

noncomputable section

open CategoryTheory
open P0EFTJanusMappingTorusQuotient
open P0EFTJanusMappingTorusStructuredJetGroupoid

universe u v

variable {X : Type u} [TopologicalSpace X]

/-- Objects whose deck stabilizer contains only the identity arrow. -/
def DeckRegularObject (data : MappingTorusData X) :=
  {base : JanusDeckObject data //
    ∀ arrow : base ⟶ base, arrow = 𝟙 base}

/-- Objects carrying a genuinely nonidentity deck-isotropy arrow. -/
def DeckSingularObject (data : MappingTorusData X) :=
  {base : JanusDeckObject data //
    ∃ arrow : base ⟶ base, arrow ≠ 𝟙 base}

/-- Every effective deck object belongs to the regular isotropy stratum. -/
def deckRegularObject
    (data : MappingTorusData X)
    (base : JanusDeckObject data) : DeckRegularObject data :=
  ⟨base, janusDeck_endomorphism_eq_id data base⟩

@[simp]
theorem deckRegularObject_val
    (data : MappingTorusData X)
    (base : JanusDeckObject data) :
    (deckRegularObject data base).1 = base :=
  rfl

/-- The effective deck isotropy stratification has no singular object. -/
theorem deckSingularObject_not_nonempty
    (data : MappingTorusData X) :
    ¬ Nonempty (DeckSingularObject data) := by
  rintro ⟨⟨base, arrow, hArrow⟩⟩
  exact hArrow (janusDeck_endomorphism_eq_id data base arrow)

/-- Arbitrary dependent data on every deck object. -/
abbrev DeckSection
    (data : MappingTorusData X)
    (Fiber : JanusDeckObject data → Type v) :=
  ∀ base : JanusDeckObject data, Fiber base

/-- The same dependent data restricted to the regular deck stratum. -/
abbrev DeckRegularSection
    (data : MappingTorusData X)
    (Fiber : JanusDeckObject data → Type v) :=
  ∀ base : DeckRegularObject data, Fiber base.1

/-- Restriction of global data to the regular deck stratum. -/
def DeckSection.restrict
    {data : MappingTorusData X}
    {Fiber : JanusDeckObject data → Type v}
    (s : DeckSection data Fiber) :
    DeckRegularSection data Fiber :=
  fun base => s base.1

/-- Extension from the regular deck stratum.  It is total because every deck
object is regular. -/
def DeckRegularSection.extend
    {data : MappingTorusData X}
    {Fiber : JanusDeckObject data → Type v}
    (s : DeckRegularSection data Fiber) :
    DeckSection data Fiber :=
  fun base => s (deckRegularObject data base)

@[simp]
theorem DeckSection.extend_restrict
    {data : MappingTorusData X}
    {Fiber : JanusDeckObject data → Type v}
    (s : DeckSection data Fiber) :
    s.restrict.extend = s := by
  funext base
  rfl

@[simp]
theorem DeckRegularSection.restrict_extend
    {data : MappingTorusData X}
    {Fiber : JanusDeckObject data → Type v}
    (s : DeckRegularSection data Fiber) :
    s.extend.restrict = s := by
  funext base
  rcases base with ⟨base, hbase⟩
  rfl

/-- Restriction to the regular deck stratum is an exact equivalence. -/
def deckSectionEquivRegularSection
    (data : MappingTorusData X)
    (Fiber : JanusDeckObject data → Type v) :
    DeckSection data Fiber ≃ DeckRegularSection data Fiber where
  toFun := DeckSection.restrict
  invFun := DeckRegularSection.extend
  left_inv := DeckSection.extend_restrict
  right_inv := DeckRegularSection.restrict_extend

/-- Any extension agreeing with prescribed regular data is the canonical
extension; there is no hidden choice on a singular deck stratum. -/
theorem DeckRegularSection.extend_unique
    {data : MappingTorusData X}
    {Fiber : JanusDeckObject data → Type v}
    (regular : DeckRegularSection data Fiber)
    (total : DeckSection data Fiber)
    (hRestrict : total.restrict = regular) :
    total = regular.extend := by
  funext base
  exact congrFun hRestrict (deckRegularObject data base)

section EffectiveD8

variable (period : Real) (hPeriod : period ≠ 0)

/-- Actual reflected-sphere D8 specialization: its effective deck
presentation has no singular deck-isotropy object. -/
theorem reflectedSphereDeckSingularObject_not_nonempty :
    ¬ Nonempty
      (DeckSingularObject (reflectedSphereData period hPeriod)) :=
  deckSingularObject_not_nonempty (reflectedSphereData period hPeriod)

/-- On the actual reflected-sphere D8 presentation, restriction to the
regular deck stratum is an equivalence for every dependent fiber family. -/
def reflectedSphereDeckSectionEquivRegularSection
    (Fiber :
      JanusDeckObject (reflectedSphereData period hPeriod) → Type v) :
    DeckSection (reflectedSphereData period hPeriod) Fiber ≃
      DeckRegularSection (reflectedSphereData period hPeriod) Fiber :=
  deckSectionEquivRegularSection (reflectedSphereData period hPeriod) Fiber

end EffectiveD8

end

end P0EFTJanusMappingTorusDeckTrivialIsotropyExtension4D
end JanusFormal
