import JanusFormal.Branches.FundamentalGeometryPVariationalPrinciple.Gates.P0EFTJanusMappingTorusCanonicalLatitudeCauchyJetProductCoarea4D
import JanusFormal.Branches.FundamentalGeometryPVariationalPrinciple.Gates.P0EFTJanusMappingTorusCanonicalPhysicalScalarCauchyJetGeometricGreenCore4D
import JanusFormal.Branches.FundamentalGeometryPVariationalPrinciple.Gates.P0EFTJanusMappingTorusCanonicalPhysicalScalarCauchyJetBoundaryCoreLp4D

/-!
# Reduction of the physical Cauchy `L²` estimate to a product integral

The product-ordered coarea map is measure preserving and the pullback of the
global explicit extension is the local Cauchy formula.  Therefore the squared
bulk `L²` norm of the extension is exactly the product integral of the square of
that local formula.

This file isolates the remaining elementary Fubini estimate.  Supplying a bound
for the product integral immediately gives the squared inclusion component of
the graph estimate.
-/

namespace JanusFormal
namespace P0EFTJanusMappingTorusCanonicalPhysicalScalarCauchyJetBulkL2Reduction4D

set_option autoImplicit false
noncomputable section

open scoped ENNReal Manifold ContDiff
open MeasureTheory Set Topology Filter
open P0EFTJanusMappingTorusSmoothFieldDescent4D
open P0EFTJanusMappingTorusL2PTFunctionalSpace4D
open P0EFTJanusMappingTorusCanonicalLorentzVolumeGluing4D
open P0EFTJanusMappingTorusCanonicalPhysicalBulkL2H1Bridge4D
open P0EFTJanusMappingTorusCanonicalLatitudeCauchyJetDeckGluing4D
open P0EFTJanusMappingTorusCanonicalLatitudeCauchyJetProductCoarea4D
open P0EFTJanusMappingTorusCanonicalPhysicalScalarCauchyJetGeometricGreenCore4D
open P0EFTJanusMappingTorusCanonicalPhysicalScalarCauchyJetGraphBound4D
open P0EFTJanusMappingTorusCanonicalPhysicalScalarCauchyJetSquaredGraphBound4D

universe x y

variable (period : Real) (hPeriod : period ≠ 0)

local instance canonicalLorentzVolumeFinite :
    IsFiniteMeasure
      (intrinsicCanonicalLorentzVolumeMeasure period hPeriod) :=
  intrinsicCanonicalLorentzVolumeMeasure_isFinite period hPeriod

namespace CanonicalPhysicalScalarCauchyJetGeometricData

/-- Local product-coordinate Cauchy extension generated by one boundary-core
pair. -/
def localProductExtension
    {ValueCore : Type x} {NormalCore : Type y}
    [AddCommGroup ValueCore] [Module Real ValueCore]
    [AddCommGroup NormalCore] [Module Real NormalCore]
    (geometric : CanonicalPhysicalScalarCauchyJetGeometricData
      period hPeriod massSquared ValueCore NormalCore)
    (data : ValueCore × NormalCore)
    (parameter : CanonicalLatitudeCauchyJetProductParameter) : Real :=
  canonicalLatitudeLocalCauchyExtension
    (geometric.boundaryCore.valueRepresentative data.1,
      geometric.boundaryCore.normalRepresentative data.2)
    parameter

/-- Squared physical norm as a bulk integral. -/
theorem inclusion_norm_sq_eq_bulk_integral
    {ValueCore : Type x} {NormalCore : Type y}
    [AddCommGroup ValueCore] [Module Real ValueCore]
    [AddCommGroup NormalCore] [Module Real NormalCore]
    (geometric : CanonicalPhysicalScalarCauchyJetGeometricData
      period hPeriod massSquared ValueCore NormalCore)
    (data : ValueCore × NormalCore) :
    ‖geometric.greenCore.core.inclusion (geometric.extension data)‖ ^ 2 =
      ∫ point,
        geometric.extension data point ^ 2
        ∂intrinsicCanonicalLorentzVolumeMeasure period hPeriod := by
  change ‖smoothToCanonicalPhysicalBulkL2 period hPeriod
      (geometric.extension data)‖ ^ 2 = _
  rw [← real_inner_self_eq_norm_sq, MeasureTheory.L2.inner_def]
  apply integral_congr_ae
  filter_upwards
    [smoothFieldToL2_ae period hPeriod Real
      (intrinsicCanonicalLorentzVolumeMeasure period hPeriod)
      (geometric.extension data)]
    with point hPoint
  rw [hPoint]
  simp [real_inner_self_eq_norm_sq, Real.norm_eq_abs, sq_abs]

/-- The bulk integral is exactly the product-coordinate integral. -/
theorem bulk_integral_eq_product_integral
    {ValueCore : Type x} {NormalCore : Type y}
    [AddCommGroup ValueCore] [Module Real ValueCore]
    [AddCommGroup NormalCore] [Module Real NormalCore]
    (geometric : CanonicalPhysicalScalarCauchyJetGeometricData
      period hPeriod massSquared ValueCore NormalCore)
    (data : ValueCore × NormalCore) :
    (∫ point,
        geometric.extension data point ^ 2
        ∂intrinsicCanonicalLorentzVolumeMeasure period hPeriod) =
      ∫ parameter,
        geometric.localProductExtension data parameter ^ 2
        ∂canonicalLatitudeCauchyJetProductMeasure period := by
  let map := canonicalLatitudeCauchyJetProductPhysicalMap period hPeriod
  let sourceMeasure := canonicalLatitudeCauchyJetProductMeasure period
  let targetMeasure := intrinsicCanonicalLorentzVolumeMeasure period hPeriod
  have hMeasure := canonicalLatitudeCauchyJetProductPhysicalMap_measurePreserving
    period hPeriod
  have hIntegrable : Integrable
      (fun point => geometric.extension data point ^ 2) targetMeasure :=
    (P0EFTJanusMappingTorusL2PTFunctionalSpace4D.smoothQuotientField_memLp
      period hPeriod Real targetMeasure
      (geometric.extension data)).integrable_sq
  have hMapIntegral := hMeasure.integral_comp hIntegrable
  rw [hMapIntegral]
  apply integral_congr_ae
  filter_upwards
    [ae_productCoarea_normal_mem_latitudeAngle period]
    with parameter hNormal
  have hCandidate :=
    (geometric.boundaryCore.deckData data).globalCandidate_productCoarea
      period hPeriod parameter hNormal
  change geometric.extension data (map parameter) ^ 2 = _
  simpa [CanonicalPhysicalScalarCauchyJetGeometricData.extension,
    CanonicalPhysicalScalarCauchyJetCandidateExtensionData.extension,
    CanonicalPhysicalScalarCauchyJetCandidateExtensionData.deckData,
    CanonicalPhysicalScalarCauchyJetGeometricData.localProductExtension]
    using congrArg (fun value : Real => value ^ 2) hCandidate

/-- Exact squared norm identity in product coarea coordinates. -/
theorem inclusion_norm_sq_eq_product_integral
    {ValueCore : Type x} {NormalCore : Type y}
    [AddCommGroup ValueCore] [Module Real ValueCore]
    [AddCommGroup NormalCore] [Module Real NormalCore]
    (geometric : CanonicalPhysicalScalarCauchyJetGeometricData
      period hPeriod massSquared ValueCore NormalCore)
    (data : ValueCore × NormalCore) :
    ‖geometric.greenCore.core.inclusion (geometric.extension data)‖ ^ 2 =
      ∫ parameter,
        geometric.localProductExtension data parameter ^ 2
        ∂canonicalLatitudeCauchyJetProductMeasure period := by
  rw [geometric.inclusion_norm_sq_eq_bulk_integral,
    geometric.bulk_integral_eq_product_integral]

/-- Product-integral estimate for the local explicit jet. -/
structure CauchyJetProductL2EstimateData
    {ValueCore : Type x} {NormalCore : Type y}
    [AddCommGroup ValueCore] [Module Real ValueCore]
    [AddCommGroup NormalCore] [Module Real NormalCore]
    (geometric : CanonicalPhysicalScalarCauchyJetGeometricData
      period hPeriod massSquared ValueCore NormalCore) where
  constant : Real
  nonnegative : 0 ≤ constant
  product_bound_sq : ∀ data : ValueCore × NormalCore,
    (∫ parameter,
      geometric.localProductExtension data parameter ^ 2
      ∂canonicalLatitudeCauchyJetProductMeasure period) ≤
        constant ^ 2 * ‖geometric.boundaryCoreEmbedding data‖ ^ 2

namespace CauchyJetProductL2EstimateData

/-- Physical squared bulk estimate derived from the product estimate. -/
theorem inclusion_bound_sq
    {ValueCore : Type x} {NormalCore : Type y}
    [AddCommGroup ValueCore] [Module Real ValueCore]
    [AddCommGroup NormalCore] [Module Real NormalCore]
    {geometric : CanonicalPhysicalScalarCauchyJetGeometricData
      period hPeriod massSquared ValueCore NormalCore}
    (estimate : geometric.CauchyJetProductL2EstimateData period hPeriod)
    (data : ValueCore × NormalCore) :
    ‖geometric.greenCore.core.inclusion (geometric.extension data)‖ ^ 2 ≤
      estimate.constant ^ 2 * ‖geometric.boundaryCoreEmbedding data‖ ^ 2 := by
  rw [geometric.inclusion_norm_sq_eq_product_integral]
  exact estimate.product_bound_sq data

/-- Combine the now-physical bulk estimate with a squared Euler-residual
estimate. -/
def toSquaredComponentGraphEstimateData
    {ValueCore : Type x} {NormalCore : Type y}
    [AddCommGroup ValueCore] [Module Real ValueCore]
    [AddCommGroup NormalCore] [Module Real NormalCore]
    {geometric : CanonicalPhysicalScalarCauchyJetGeometricData
      period hPeriod massSquared ValueCore NormalCore}
    (estimate : geometric.CauchyJetProductL2EstimateData period hPeriod)
    (operatorConstant : Real) (hOperatorConstant : 0 ≤ operatorConstant)
    (operatorBound : ∀ data : ValueCore × NormalCore,
      ‖geometric.greenCore.core.operator (geometric.extension data)‖ ^ 2 ≤
        operatorConstant ^ 2 * ‖geometric.boundaryCoreEmbedding data‖ ^ 2) :
    geometric.CauchyJetSquaredComponentGraphEstimateData period hPeriod where
  inclusionConstant := estimate.constant
  inclusionConstant_nonnegative := estimate.nonnegative
  operatorConstant := operatorConstant
  operatorConstant_nonnegative := hOperatorConstant
  inclusion_bound_sq := estimate.inclusion_bound_sq
  operator_bound_sq := operatorBound

/-- Bulk-`L²` reduction certificate. -/
theorem certificate
    {ValueCore : Type x} {NormalCore : Type y}
    [AddCommGroup ValueCore] [Module Real ValueCore]
    [AddCommGroup NormalCore] [Module Real NormalCore]
    {geometric : CanonicalPhysicalScalarCauchyJetGeometricData
      period hPeriod massSquared ValueCore NormalCore}
    (estimate : geometric.CauchyJetProductL2EstimateData period hPeriod) :
    (∀ data : ValueCore × NormalCore,
      ‖geometric.greenCore.core.inclusion (geometric.extension data)‖ ^ 2 =
        ∫ parameter,
          geometric.localProductExtension data parameter ^ 2
          ∂canonicalLatitudeCauchyJetProductMeasure period) ∧
      (∀ data : ValueCore × NormalCore,
        ‖geometric.greenCore.core.inclusion (geometric.extension data)‖ ^ 2 ≤
          estimate.constant ^ 2 * ‖geometric.boundaryCoreEmbedding data‖ ^ 2) :=
  ⟨geometric.inclusion_norm_sq_eq_product_integral,
    estimate.inclusion_bound_sq⟩

end CauchyJetProductL2EstimateData

end CanonicalPhysicalScalarCauchyJetGeometricData

end
end P0EFTJanusMappingTorusCanonicalPhysicalScalarCauchyJetBulkL2Reduction4D
end JanusFormal
