import JanusFormal.Branches.FundamentalGeometryPVariationalPrinciple.Gates.P0EFTJanusCommonPairedD9LinearBRSTBlock4D
import JanusFormal.Branches.FundamentalGeometryPVariationalPrinciple.Gates.P0EFTJanusMappingTorusFiniteTemporalFourierGaugeGhostCohomology4D

/-!
# Paired finite temporal BRST cohomology in the common D9 block

The two genuine smooth `U(1)^2` Program-P ghosts are restricted to the
finite temporal Fourier subspace already constructed on the actual D8
mapping torus.  Their common linear BRST image is the pair of intrinsic
exact potentials `dc`, and its kernel consists exactly of the two constant
temporal modes.  The same states are inserted in the paired D9 block, whose
ghost coordinate vanishes after one BRST step.

This is a finite temporal abelian subcomplex.  It does not supply Sobolev
domains, the diffeomorphism-ghost cohomology, or the full global D9/BRST
complex.
-/

namespace JanusFormal
namespace P0EFTJanusMappingTorusPairedFiniteTemporalBRSTD9Cohomology4D

set_option autoImplicit false
noncomputable section

open scoped Manifold ContDiff
open P0EFTJanusMappingTorusQuotient
open P0EFTJanusMappingTorusSmoothGlobalFieldConfiguration4D
open P0EFTJanusMappingTorusAbelianGaugeBRST4D
open P0EFTJanusShiftedSobolevMappingTorusFiniteTemporalFourierBridge4D
open P0EFTJanusMappingTorusFiniteTemporalFourierGaugeGhostZeroMode4D
open P0EFTJanusMappingTorusFiniteTemporalFourierGaugeGhostCohomology4D
open P0EFTJanusCommonPairedD9GhostPacket4D
open P0EFTJanusCommonPairedD9LinearBRSTBlock4D

variable (period : Real) [hPeriodPos : Fact (0 < period)]

abbrev PairedFiniteTemporalGhostCoefficients :=
  FiniteTemporalFourierCoefficients × FiniteTemporalFourierCoefficients

/-- The genuine pair of exact gauge potentials generated by the two finite
temporal `U(1)^2` ghosts. -/
def pairedFiniteTemporalExactGaugeLinearMap :
    PairedFiniteTemporalGhostCoefficients →ₗ[Real]
      (SmoothAbelianGaugePotential period hPeriodPos.out.ne' ×
        SmoothAbelianGaugePotential period hPeriodPos.out.ne') where
  toFun coefficients :=
    (finiteTemporalFourierExactGaugeLinearMap period coefficients.1,
      finiteTemporalFourierExactGaugeLinearMap period coefficients.2)
  map_add' first second := by
    apply Prod.ext <;> simp
  map_smul' scalar coefficients := by
    apply Prod.ext <;> simp

/-- Exact kernel computation for the paired genuine finite temporal ghosts:
both components, and only those components, are constant temporal modes. -/
theorem pairedFiniteTemporalExactGauge_eq_zero_iff
    (coefficients : PairedFiniteTemporalGhostCoefficients) :
    pairedFiniteTemporalExactGaugeLinearMap period coefficients = 0 ↔
      ∃ firstZero secondZero : Complex,
        coefficients.1 = temporalZeroModeCoefficientLinearMap firstZero ∧
        coefficients.2 = temporalZeroModeCoefficientLinearMap secondZero := by
  constructor
  · intro hZero
    have hFirst :
        finiteTemporalFourierExactGaugeLinearMap period coefficients.1 = 0 := by
      exact congrArg Prod.fst hZero
    have hSecond :
        finiteTemporalFourierExactGaugeLinearMap period coefficients.2 = 0 := by
      exact congrArg Prod.snd hZero
    have hFirstKernel : coefficients.1 ∈
        LinearMap.ker (finiteTemporalFourierExactGaugeLinearMap period) :=
      hFirst
    have hSecondKernel : coefficients.2 ∈
        LinearMap.ker (finiteTemporalFourierExactGaugeLinearMap period) :=
      hSecond
    rw [finiteTemporalFourierExactGauge_kernel_eq_zeroMode_range period] at hFirstKernel
    rw [finiteTemporalFourierExactGauge_kernel_eq_zeroMode_range period] at hSecondKernel
    obtain ⟨firstZero, hFirstZero⟩ := hFirstKernel
    obtain ⟨secondZero, hSecondZero⟩ := hSecondKernel
    exact ⟨firstZero, secondZero, hFirstZero.symm, hSecondZero.symm⟩
  · rintro ⟨firstZero, secondZero, hFirstZero, hSecondZero⟩
    apply Prod.ext
    · change finiteTemporalFourierExactGaugeLinearMap period coefficients.1 = 0
      rw [hFirstZero]
      exact finiteTemporalFourierExactGaugeLinearMap_zeroMode period firstZero
    · change finiteTemporalFourierExactGaugeLinearMap period coefficients.2 = 0
      rw [hSecondZero]
      exact finiteTemporalFourierExactGaugeLinearMap_zeroMode period secondZero

/-- Insert the two genuine finite temporal ghosts into the common paired
linear BRST/D9 state, with zero initial potentials and zero throat ghost. -/
def pairedFiniteTemporalBRSTBlock
    (coefficients : PairedFiniteTemporalGhostCoefficients) :
    CommonPairedD9LinearBRSTBlock period hPeriodPos.out.ne' where
  firstU1 :=
    { potential := 0
      ghost := finiteTemporalFourierGaugeGhostLinearMap period coefficients.1 }
  secondU1 :=
    { potential := 0
      ghost := finiteTemporalFourierGaugeGhostLinearMap period coefficients.2 }
  diffeomorphismGhost :=
    (zeroCommonPairedD9LinearBRSTBlock period hPeriodPos.out.ne').diffeomorphismGhost

/-- The potential part of the common BRST differential is exactly the paired
global operator above, on the same two actual quotient ghost fields. -/
theorem pairedFiniteTemporalBRSTBlock_image_potentials
    (coefficients : PairedFiniteTemporalGhostCoefficients) :
    let image := commonPairedD9LinearBRSTDifferential period hPeriodPos.out.ne'
      (pairedFiniteTemporalBRSTBlock period coefficients)
    (image.firstU1.potential, image.secondU1.potential) =
      pairedFiniteTemporalExactGaugeLinearMap period coefficients := by
  rfl

/-- The D9 ghost coordinate of this genuine paired state vanishes after one
common linear BRST step. -/
theorem pairedFiniteTemporalBRSTBlock_d9Coordinate_after_differential
    (coefficients : PairedFiniteTemporalGhostCoefficients)
    (column : Fin 2)
    (point : MappingTorus
      (fixedEquatorData period hPeriodPos.out.ne')) :
    commonPairedD9GhostCoordinate period hPeriodPos.out.ne'
        ((commonPairedD9LinearBRSTDifferential period hPeriodPos.out.ne'
          (pairedFiniteTemporalBRSTBlock period coefficients)).toGhostPacket
            period hPeriodPos.out.ne') column point = 0 :=
  commonPairedD9LinearBRSTDifferential_d9Coordinate
    period hPeriodPos.out.ne' _ column point

end
end P0EFTJanusMappingTorusPairedFiniteTemporalBRSTD9Cohomology4D
end JanusFormal
