import JanusFormal.Branches.FundamentalGeometryPVariationalPrinciple.Gates.P0EFTJanusMappingTorusCanonicalPhysicalScalarIntrinsicWave4D
import JanusFormal.Branches.FundamentalGeometryPVariationalPrinciple.Gates.P0EFTJanusMappingTorusCanonicalPhysicalScalarEulerNormalHalfCollarTransport4D
import JanusFormal.Branches.FundamentalGeometryPVariationalPrinciple.Gates.P0EFTJanusMappingTorusCanonicalPhysicalScalarIntrinsicWaveCanonicalNormalGreen4D

/-!
# Intrinsic Green data generated by a universal normal transport

The intrinsic scalar wave supplies atlas naturality.  A field-independent
transport from the full weighted normal coarea domain to the positive half
collar supplies the normal Green density and its exact `-2` integral.

The remaining Green-specific input is only:

* integrability of the explicit cutoff-collar divergence;
* cancellation, after base integration, of the induced tangential remainder.
-/

namespace JanusFormal
namespace P0EFTJanusMappingTorusCanonicalPhysicalScalarIntrinsicWaveTransportedNormalGreen4D

set_option autoImplicit false
noncomputable section

open scoped Manifold ContDiff ENNReal Interval
open MeasureTheory Set Topology Filter
open P0EFTJanusMappingTorusSmoothFieldDescent4D
open P0EFTJanusMappingTorusCanonicalPhysicalH1TraceBound4D
open P0EFTJanusMappingTorusCanonicalLatitudeCauchyJetProductCoarea4D
open P0EFTJanusMappingTorusCanonicalPhysicalScalarIntrinsicWave4D
open P0EFTJanusMappingTorusCanonicalPhysicalScalarEulerCanonicalProductLocalDivergence4D
open P0EFTJanusMappingTorusCanonicalPhysicalScalarEulerNormalHalfCollarTransport4D
open P0EFTJanusMappingTorusCanonicalPhysicalScalarIntrinsicWaveCanonicalNormalGreen4D

variable (period : Real) (hPeriod : period ≠ 0)

/-- Intrinsic-wave Green data with transport-generated normal component. -/
structure CanonicalPhysicalScalarIntrinsicWaveTransportedNormalGreenData
    (massSquared : Real) where
  intrinsicWave : CanonicalPhysicalScalarIntrinsicWaveData period hPeriod
  transportData : CanonicalLatitudeNormalToHalfCollarTransportData period
  halfCollarDivergence_integrable :
    ∀ field test : SmoothScalarField period hPeriod,
      Integrable
        (canonicalPhysicalScalarHalfCollarDivergenceDensity
          period hPeriod massSquared field test)
        (canonicalLatitudeCollarMeasure period)
  tangential_base_integral_zero :
    ∀ field test normal,
      (∫ base,
        (canonicalPhysicalScalarEulerProductLocalDivergenceDensity
            period hPeriod field test (base, normal) +
          canonicalPhysicalScalarHalfCollarDivergenceDensity
            period hPeriod massSquared field test
            (transportData.transport (base, normal)))
        ∂canonicalLatitudeBaseMeasure period) = 0

namespace CanonicalPhysicalScalarIntrinsicWaveTransportedNormalGreenData

/-- Transport-generated normal-density package. -/
def toTransportedNormalDensityData
    (data : CanonicalPhysicalScalarIntrinsicWaveTransportedNormalGreenData
      period hPeriod massSquared) :
    CanonicalPhysicalScalarEulerTransportedNormalDensityData
      period hPeriod massSquared where
  waveNaturality := data.intrinsicWave.toWaveAtlasNaturality
  transportData := data.transportData
  halfCollarDivergence_integrable := data.halfCollarDivergence_integrable
  tangential_base_integral_zero := data.tangential_base_integral_zero

/-- Canonical normal Green density, defined as a transported cutoff divergence. -/
def normalDensity
    (data : CanonicalPhysicalScalarIntrinsicWaveTransportedNormalGreenData
      period hPeriod massSquared) :=
  data.toTransportedNormalDensityData.normalDensity

/-- Conversion to the smallest canonical-normal Green package. -/
def toCanonicalNormalGreenData
    (data : CanonicalPhysicalScalarIntrinsicWaveTransportedNormalGreenData
      period hPeriod massSquared) :
    CanonicalPhysicalScalarIntrinsicWaveCanonicalNormalGreenData
      period hPeriod massSquared where
  intrinsicWave := data.intrinsicWave
  normalDensity := data.normalDensity
  normalDensity_integrable :=
    data.toTransportedNormalDensityData.normalDensity_integrable
  tangential_base_integral_zero := by
    intro field test normal
    exact data.toTransportedNormalDensityData.toCanonicalNormalSplitData
      |>.tangential_base_integral_zero field test normal
  normal_integral_eq_halfCollar :=
    data.toTransportedNormalDensityData.normal_integral_eq_halfCollar

/-- Correct dense physical Green core. -/
def greenCore
    (data : CanonicalPhysicalScalarIntrinsicWaveTransportedNormalGreenData
      period hPeriod massSquared) :=
  data.toCanonicalNormalGreenData.greenCore

/-- Transport-generated intrinsic Green certificate. -/
theorem certificate
    (data : CanonicalPhysicalScalarIntrinsicWaveTransportedNormalGreenData
      period hPeriod massSquared) :
    P0EFTJanusMappingTorusCanonicalPhysicalScalarEulerAtlasNaturality4D.CanonicalPhysicalScalarWaveAtlasNaturality
        period hPeriod ∧
      (∀ field test,
        Integrable (data.normalDensity field test)
          (canonicalLatitudeCauchyJetProductMeasure period)) ∧
      (∀ field test,
        (∫ parameter,
          data.normalDensity field test parameter
          ∂canonicalLatitudeCauchyJetProductMeasure period) =
        -2 *
          (∫ base, (∫ normal in (0 : Real)..1,
            P0EFTJanusMappingTorusCanonicalLatitudeCutoffCurrentLocalStokes4D.cutoffCollarScalarCurrentDensitizedDivergence
              period hPeriod massSquared field test base normal)
            ∂canonicalLatitudeBaseMeasure period)) ∧
      (∀ field test,
        (∫ point,
          P0EFTJanusMappingTorusCanonicalPhysicalScalarEulerGreenL2Reduction4D.canonicalPhysicalScalarEulerSkewDensity
            period hPeriod massSquared field test point
          ∂P0EFTJanusMappingTorusCanonicalLorentzVolumeGluing4D.intrinsicCanonicalLorentzVolumeMeasure
            period hPeriod) =
        -2 * P0EFTJanusMappingTorusCutBulkCanonicalDivergenceMeasure4D.cutBulkCanonicalDivergenceMeasure
          period hPeriod massSquared field test Set.univ) :=
  ⟨data.intrinsicWave.toWaveAtlasNaturality,
    data.toTransportedNormalDensityData.normalDensity_integrable,
    data.toTransportedNormalDensityData.normal_integral_eq_halfCollar,
    data.toCanonicalNormalGreenData.certificate.2.2.2⟩

end CanonicalPhysicalScalarIntrinsicWaveTransportedNormalGreenData

end
end P0EFTJanusMappingTorusCanonicalPhysicalScalarIntrinsicWaveTransportedNormalGreen4D
end JanusFormal
