import JanusFormal.Branches.FundamentalGeometryPVariationalPrinciple.Gates.P0EFTJanusProgramPReferenceNuclearDuhamelGreenSelectedTraceDominatedExponentialBoundaryLimits4D
import JanusFormal.Branches.FundamentalGeometryPVariationalPrinciple.Gates.P0EFTJanusProgramPReferenceNuclearHeatFinitePartSelectedTraceExponentialCanonicalSchwarzAssembly4D

/-!
# Selected-trace finite-part assembly from domination and exponential decay

This frontend packages the complete generic reference route in which

* short- and long-time weighted differentiation are generated by local
  domination;
* the long-time terminal primitive limit is generated by an exponential
  spectral estimate;
* the Duhamel endpoint target and nuclear trace are the ones already selected
  by the determinant chart;
* canonical Schwarz symmetry forces reality of the standalone Mellin
  derivative at zero.

It produces the standalone coefficient

```text
T_reference(a) = -selectedTrace.trace(a)
```

without an opaque differentiation-under-the-integral theorem, a direct
long-time convergence field, or a generated-to-selected trace comparison.
-/

namespace JanusFormal
namespace P0EFTJanusProgramPReferenceNuclearHeatFinitePartSelectedTraceDominatedExponentialCanonicalSchwarzAssembly4D

set_option autoImplicit false
noncomputable section

open Filter Set Topology MeasureTheory
open P0EFTJanusProgramPRelativeHeatFinitePartDeterminant4D
open P0EFTJanusProgramPRelativeZetaDeterminantConnection4D
open P0EFTJanusProgramPIntrinsicLogarithmicDerivativeTrace4D
open P0EFTJanusProgramPNuclearHeatDuhamelTraceVariation4D
open P0EFTJanusProgramPNuclearHeatDuhamelWeightedIntegral4D.NuclearHeatDuhamelTraceVariationData
open P0EFTJanusProgramPReferenceNuclearDuhamelGreenSelectedTraceDominatedExponentialBoundaryLimits4D
open P0EFTJanusProgramPReferenceNuclearHeatFinitePartSelectedTraceExponentialCanonicalSchwarzAssembly4D
open P0EFTJanusProgramPRelativeHeatMellinZetaCanonicalSchwarzReflection4D
open P0EFTJanusProgramPRelativeHeatMellinZetaFamily4D

universe e i s a b

variable {Slice : Type s} {ShortCutoff : Type a} {LongCutoff : Type b}
  {E : Type e}
  [MeasurableSpace Slice]
  [NormedAddCommGroup E]
  [InnerProductSpace Real E] [CompleteSpace E]

/-- Standalone reference data with dominated time integrals and exponential
long-time decay. -/
structure ReferenceNuclearHeatFinitePartSelectedTraceDominatedExponentialCanonicalSchwarzAssemblyData
    (sliceMeasure : Measure Slice) [IsProbabilityMeasure sliceMeasure]
    (shortCutoffFilter : Filter ShortCutoff) [NeBot shortCutoffFilter]
    (longCutoffFilter : Filter LongCutoff) [NeBot longCutoffFilter]
    (referenceOperator : Real → E →L[Real] E)
    (selectedTrace : IntrinsicLogarithmicDerivativeTraceData.{e, i}
      referenceOperator)
    (family : RelativeHeatMellinZetaFamilyData)
    (shortTimeRegion longTimeRegion : Set Real) where
  nuclear : NuclearHeatDuhamelTraceVariationData.{e, i} (E := E)
  countertermContribution : Real → Real
  spectralBoundary :
    ReferenceNuclearDuhamelGreenSelectedTraceDominatedExponentialBoundaryLimitsData.{e, i, s, a, b}
      sliceMeasure shortCutoffFilter longCutoffFilter nuclear
        countertermContribution shortTimeRegion longTimeRegion
          referenceOperator selectedTrace
  logDeterminant_eq : ∀ parameter,
    relativeHeatFinitePartLogDeterminant
          (family.finitePartFamily.finitePart parameter) =
      countertermContribution parameter +
        spectralBoundary.toSelectedTraceExponentialBoundaryLimits.toSelectedTraceBoundaryLimits.toFullySpectralBoundaryLimits.shortTime.weighted.toWeightedHeatTraceVariation.contribution
            parameter +
          spectralBoundary.toSelectedTraceExponentialBoundaryLimits.toSelectedTraceBoundaryLimits.toFullySpectralBoundaryLimits.longTime.weighted.toWeightedHeatTraceVariation.contribution
              parameter
  zetaCanonicalSchwarz : ∀ parameter,
    RelativeHeatMellinZetaCanonicalSchwarzReflectionData
      (family.continuation parameter)

namespace ReferenceNuclearHeatFinitePartSelectedTraceDominatedExponentialCanonicalSchwarzAssemblyData

/-- Forget domination witnesses only after constructing the weighted derivative
theorems, and forget the exponential envelope only after constructing the
terminal primitive limit. -/
def toSelectedTraceExponentialCanonicalSchwarzAssembly
    {sliceMeasure : Measure Slice} [IsProbabilityMeasure sliceMeasure]
    {shortCutoffFilter : Filter ShortCutoff} [NeBot shortCutoffFilter]
    {longCutoffFilter : Filter LongCutoff} [NeBot longCutoffFilter]
    {referenceOperator : Real → E →L[Real] E}
    {selectedTrace : IntrinsicLogarithmicDerivativeTraceData.{e, i} referenceOperator}
    {family : RelativeHeatMellinZetaFamilyData}
    {shortTimeRegion longTimeRegion : Set Real}
    (data :
      ReferenceNuclearHeatFinitePartSelectedTraceDominatedExponentialCanonicalSchwarzAssemblyData
        (E := E) sliceMeasure shortCutoffFilter longCutoffFilter
          referenceOperator selectedTrace family shortTimeRegion longTimeRegion) :
    ReferenceNuclearHeatFinitePartSelectedTraceExponentialCanonicalSchwarzAssemblyData
      (E := E) sliceMeasure shortCutoffFilter longCutoffFilter
        referenceOperator selectedTrace family shortTimeRegion longTimeRegion where
  nuclear := data.nuclear
  countertermContribution := data.countertermContribution
  spectralBoundary :=
    data.spectralBoundary.toSelectedTraceExponentialBoundaryLimits
  logDeterminant_eq := data.logDeterminant_eq
  zetaCanonicalSchwarz := data.zetaCanonicalSchwarz

/-- Dominated short-time differentiation. -/
theorem shortTime_hasDerivAt
    {sliceMeasure : Measure Slice} [IsProbabilityMeasure sliceMeasure]
    {shortCutoffFilter : Filter ShortCutoff} [NeBot shortCutoffFilter]
    {longCutoffFilter : Filter LongCutoff} [NeBot longCutoffFilter]
    {referenceOperator : Real → E →L[Real] E}
    {selectedTrace : IntrinsicLogarithmicDerivativeTraceData.{e, i} referenceOperator}
    {family : RelativeHeatMellinZetaFamilyData}
    {shortTimeRegion longTimeRegion : Set Real}
    (data :
      ReferenceNuclearHeatFinitePartSelectedTraceDominatedExponentialCanonicalSchwarzAssemblyData
        (E := E) sliceMeasure shortCutoffFilter longCutoffFilter
          referenceOperator selectedTrace family shortTimeRegion longTimeRegion)
    (parameter : Real) :
    HasDerivAt
      data.spectralBoundary.shortTime.toCollapsedRankOneIntegral.weighted.toWeightedHeatTraceVariation.contribution
      (-(∫ time in shortTimeRegion,
        extendedDuhamelTrace data.nuclear parameter time)) parameter :=
  data.spectralBoundary.shortTime_hasDerivAt parameter

/-- Dominated long-time differentiation. -/
theorem longTime_hasDerivAt
    {sliceMeasure : Measure Slice} [IsProbabilityMeasure sliceMeasure]
    {shortCutoffFilter : Filter ShortCutoff} [NeBot shortCutoffFilter]
    {longCutoffFilter : Filter LongCutoff} [NeBot longCutoffFilter]
    {referenceOperator : Real → E →L[Real] E}
    {selectedTrace : IntrinsicLogarithmicDerivativeTraceData.{e, i} referenceOperator}
    {family : RelativeHeatMellinZetaFamilyData}
    {shortTimeRegion longTimeRegion : Set Real}
    (data :
      ReferenceNuclearHeatFinitePartSelectedTraceDominatedExponentialCanonicalSchwarzAssemblyData
        (E := E) sliceMeasure shortCutoffFilter longCutoffFilter
          referenceOperator selectedTrace family shortTimeRegion longTimeRegion)
    (parameter : Real) :
    HasDerivAt
      data.spectralBoundary.longTime.toCollapsedRankOneIntegral.weighted.toWeightedHeatTraceVariation.contribution
      (-(∫ time in longTimeRegion,
        extendedDuhamelTrace data.nuclear parameter time)) parameter :=
  data.spectralBoundary.longTime_hasDerivAt parameter

/-- Exponential long-time decay generates the terminal limit. -/
theorem terminalPrimitive_tendsto_zero
    {sliceMeasure : Measure Slice} [IsProbabilityMeasure sliceMeasure]
    {shortCutoffFilter : Filter ShortCutoff} [NeBot shortCutoffFilter]
    {longCutoffFilter : Filter LongCutoff} [NeBot longCutoffFilter]
    {referenceOperator : Real → E →L[Real] E}
    {selectedTrace : IntrinsicLogarithmicDerivativeTraceData.{e, i} referenceOperator}
    {family : RelativeHeatMellinZetaFamilyData}
    {shortTimeRegion longTimeRegion : Set Real}
    (data :
      ReferenceNuclearHeatFinitePartSelectedTraceDominatedExponentialCanonicalSchwarzAssemblyData
        (E := E) sliceMeasure shortCutoffFilter longCutoffFilter
          referenceOperator selectedTrace family shortTimeRegion longTimeRegion)
    (parameter : Real) :
    Tendsto (data.spectralBoundary.longBoundaryDecay parameter).terminalPrimitive
      longCutoffFilter (𝓝 0) :=
  data.spectralBoundary.terminalPrimitive_tendsto_zero parameter

/-- Canonical Schwarz reality for the standalone reference family. -/
theorem zetaPrimeAtZero_im_eq_zero
    {sliceMeasure : Measure Slice} [IsProbabilityMeasure sliceMeasure]
    {shortCutoffFilter : Filter ShortCutoff} [NeBot shortCutoffFilter]
    {longCutoffFilter : Filter LongCutoff} [NeBot longCutoffFilter]
    {referenceOperator : Real → E →L[Real] E}
    {selectedTrace : IntrinsicLogarithmicDerivativeTraceData.{e, i} referenceOperator}
    {family : RelativeHeatMellinZetaFamilyData}
    {shortTimeRegion longTimeRegion : Set Real}
    (data :
      ReferenceNuclearHeatFinitePartSelectedTraceDominatedExponentialCanonicalSchwarzAssemblyData
        (E := E) sliceMeasure shortCutoffFilter longCutoffFilter
          referenceOperator selectedTrace family shortTimeRegion longTimeRegion)
    (parameter : Real) :
    (family.zetaPrimeAtZero parameter).im = 0 :=
  data.toSelectedTraceExponentialCanonicalSchwarzAssembly.zetaPrimeAtZero_im_eq_zero
    parameter

/-- The selected standalone reference coefficient. -/
theorem connectionCoefficient_eq_neg_selectedTrace
    {sliceMeasure : Measure Slice} [IsProbabilityMeasure sliceMeasure]
    {shortCutoffFilter : Filter ShortCutoff} [NeBot shortCutoffFilter]
    {longCutoffFilter : Filter LongCutoff} [NeBot longCutoffFilter]
    {referenceOperator : Real → E →L[Real] E}
    {selectedTrace : IntrinsicLogarithmicDerivativeTraceData.{e, i} referenceOperator}
    {family : RelativeHeatMellinZetaFamilyData}
    {shortTimeRegion longTimeRegion : Set Real}
    (data :
      ReferenceNuclearHeatFinitePartSelectedTraceDominatedExponentialCanonicalSchwarzAssemblyData
        (E := E) sliceMeasure shortCutoffFilter longCutoffFilter
          referenceOperator selectedTrace family shortTimeRegion longTimeRegion)
    (parameter : Real) :
    relativeZetaConnectionCoefficient family.toZetaFamily parameter =
      -(selectedTrace.trace parameter : Complex) :=
  data.toSelectedTraceExponentialCanonicalSchwarzAssembly.connectionCoefficient_eq_neg_selectedTrace
    parameter

/-- Public dominated/exponential selected-trace finite-part checkpoint. -/
theorem reference_nuclear_heat_finite_part_selected_trace_dominated_exponential_canonical_schwarz_assembly_gate
    (sliceMeasure : Measure Slice) [IsProbabilityMeasure sliceMeasure]
    (shortCutoffFilter : Filter ShortCutoff) [NeBot shortCutoffFilter]
    (longCutoffFilter : Filter LongCutoff) [NeBot longCutoffFilter]
    (referenceOperator : Real → E →L[Real] E)
    (selectedTrace : IntrinsicLogarithmicDerivativeTraceData.{e, i} referenceOperator)
    (family : RelativeHeatMellinZetaFamilyData)
    (shortTimeRegion longTimeRegion : Set Real)
    (data :
      ReferenceNuclearHeatFinitePartSelectedTraceDominatedExponentialCanonicalSchwarzAssemblyData
        (E := E) sliceMeasure shortCutoffFilter longCutoffFilter
          referenceOperator selectedTrace family shortTimeRegion longTimeRegion) :
    (∀ parameter,
      HasDerivAt
        data.spectralBoundary.shortTime.toCollapsedRankOneIntegral.weighted.toWeightedHeatTraceVariation.contribution
        (-(∫ time in shortTimeRegion,
          extendedDuhamelTrace data.nuclear parameter time)) parameter) ∧
    (∀ parameter,
      HasDerivAt
        data.spectralBoundary.longTime.toCollapsedRankOneIntegral.weighted.toWeightedHeatTraceVariation.contribution
        (-(∫ time in longTimeRegion,
          extendedDuhamelTrace data.nuclear parameter time)) parameter) ∧
    (∀ parameter,
      Tendsto (data.spectralBoundary.longBoundaryDecay parameter).terminalPrimitive
        longCutoffFilter (𝓝 0)) ∧
    (∀ parameter,
      (family.zetaPrimeAtZero parameter).im = 0) ∧
    (∀ parameter,
      relativeZetaConnectionCoefficient family.toZetaFamily parameter =
        -(selectedTrace.trace parameter : Complex)) :=
  ⟨data.shortTime_hasDerivAt,
    data.longTime_hasDerivAt,
    data.terminalPrimitive_tendsto_zero,
    data.zetaPrimeAtZero_im_eq_zero,
    data.connectionCoefficient_eq_neg_selectedTrace⟩

end ReferenceNuclearHeatFinitePartSelectedTraceDominatedExponentialCanonicalSchwarzAssemblyData

end
end P0EFTJanusProgramPReferenceNuclearHeatFinitePartSelectedTraceDominatedExponentialCanonicalSchwarzAssembly4D
end JanusFormal
