import JanusFormal.Branches.FundamentalGeometryPVariationalPrinciple.Gates.P0EFTJanusProgramPT06FiniteRankBilinearValueCurrent4D

/-!
# A multifield first-order quadratic Euler kernel

This gate treats an autonomous quadratic family on a finite-dimensional real
normed fiber.  Besides a constant and an arbitrary linear value coefficient,
it contains one normalized symmetric value-square obstruction and every
three-direction finite-rank bilinear value current from Gate898.  The latter
supplies all mixed `u`--`u_i` terms generated by finite sums of continuous
linear covectors.

The genuine Gate880 Euler operator is computed directly from Frechet
derivatives.  It vanishes exactly when the linear value coefficient and the
normalized value-square coefficient vanish.  In that case the density is its
constant plus the genuine Gate898 horizontal divergence, giving an explicit
algebraic homotopy on this multifield subclass.

The normalization witness removes coefficient redundancy in the square and
makes the converse honest.  The result does not classify arbitrary bilinear
forms, gradient-gradient couplings, second-jet densities, or the full T02
degree-four carrier.
-/

namespace JanusFormal
namespace P0EFTJanusProgramPT06MultifieldFirstOrderQuadraticKernel4D

set_option autoImplicit false
noncomputable section

open scoped BigOperators
open P0EFTJanusProgramPT06ThroatSpatialFinsuppJetTower4D
open P0EFTJanusProgramPT06LocalFunctionTotalDerivative4D
open P0EFTJanusProgramPT06SecondOrderLocalEuler4D
open P0EFTJanusProgramPT06DirectedQuadraticValueCurrent4D
open P0EFTJanusProgramPT06FiniteRankBilinearValueCurrent4D

attribute [local instance 2000]
  NormedAddCommGroup.toAddCommGroup NormedSpace.toModule
  PseudoMetricSpace.toUniformSpace UniformSpace.toTopologicalSpace

universe u v

variable {Fiber : Type u} [NormedAddCommGroup Fiber] [NormedSpace Real Fiber]
  [FiniteDimensional Real Fiber]
variable {Rank : Type v} [Fintype Rank]

private abbrev SecondJet := ThroatSpatialMultiindexJet2 Fiber
private abbrev FourthJet := ThroatSpatialMultiindexJet4 Fiber

/-- A multifield quadratic density with a normalized value-square direction
and a full Gate898 finite-rank boundary current. -/
structure ProgramPT06MultifieldFirstOrderQuadraticDensity4D
    (Fiber : Type u) [NormedAddCommGroup Fiber] [NormedSpace Real Fiber]
    [FiniteDimensional Real Fiber]
    (Rank : Type v) [Fintype Rank] where
  constant : Real
  valueLinear : Fiber →L[Real] Real
  normalizedValueCovector : Fiber →L[Real] Real
  normalizedValueWitness : Fiber
  normalizedValueCovector_witness :
    normalizedValueCovector normalizedValueWitness = 1
  valueSquare : Real
  boundaryCurrent : ProgramPT06FiniteRankBilinearValueCurrent4D Fiber Rank

private def secondOrderValueProjection :
    SecondJet (Fiber := Fiber) →L[Real] Fiber :=
  ContinuousLinearMap.proj programPT06SecondOrderZeroMultiIndex

private def secondOrderNormalizedValueCovector
    (density : ProgramPT06MultifieldFirstOrderQuadraticDensity4D Fiber Rank) :
    SecondJet (Fiber := Fiber) →L[Real] Real :=
  density.normalizedValueCovector.comp
    (secondOrderValueProjection (Fiber := Fiber))

private def secondOrderLinearValueCovector
    (density : ProgramPT06MultifieldFirstOrderQuadraticDensity4D Fiber Rank) :
    SecondJet (Fiber := Fiber) →L[Real] Real :=
  density.valueLinear.comp (secondOrderValueProjection (Fiber := Fiber))

private def fourthOrderZeroMultiIndex : ThroatSpatialTruncatedIndex 4 :=
  ⟨0, by simp⟩

omit [FiniteDimensional Real Fiber] in
@[simp] private theorem secondOrderValueProjection_truncate_fourth
    (jet : FourthJet (Fiber := Fiber)) :
    secondOrderValueProjection (Fiber := Fiber)
        (truncateThroatSpatialMultiindexJet (by omega : 2 <= 4) jet) =
      jet fourthOrderZeroMultiIndex := by
  change jet _ = jet _
  apply congrArg jet
  apply Subtype.ext
  rfl

private theorem secondOrderFirstMultiIndex_ne_zero (direction : Fin 3) :
    programPT06SecondOrderFirstMultiIndex direction ≠
      programPT06SecondOrderZeroMultiIndex := by
  intro hIndex
  have hOrder := congrArg
    (fun index : ThroatSpatialTruncatedIndex 2 =>
      throatSpatialMultiIndexOrder index.val) hIndex
  simp [programPT06SecondOrderFirstMultiIndex,
    programPT06SecondOrderZeroMultiIndex] at hOrder

private theorem secondOrderSecondMultiIndex_ne_zero
    (first second : Fin 3) :
    programPT06SecondOrderSecondMultiIndex first second ≠
      programPT06SecondOrderZeroMultiIndex := by
  intro hIndex
  have hOrder := congrArg
    (fun index : ThroatSpatialTruncatedIndex 2 =>
      throatSpatialMultiIndexOrder index.val) hIndex
  simp [programPT06SecondOrderSecondMultiIndex,
    programPT06SecondOrderZeroMultiIndex,
    throatSpatialMultiIndexOrder_add] at hOrder

/-- The continuous symmetric bilinear form underlying the normalized
value-square coefficient. -/
def programPT06MultifieldFirstOrderQuadraticValueBilinear
    (density : ProgramPT06MultifieldFirstOrderQuadraticDensity4D Fiber Rank) :
    Fiber →L[Real] (Fiber →L[Real] Real) :=
  density.valueSquare •
    density.normalizedValueCovector.smulRight
      density.normalizedValueCovector

@[simp] theorem programPT06MultifieldFirstOrderQuadraticValueBilinear_apply
    (density : ProgramPT06MultifieldFirstOrderQuadraticDensity4D Fiber Rank)
    (first second : Fiber) :
    programPT06MultifieldFirstOrderQuadraticValueBilinear density first second =
      density.valueSquare * density.normalizedValueCovector first *
        density.normalizedValueCovector second := by
  simp [programPT06MultifieldFirstOrderQuadraticValueBilinear,
    smul_eq_mul]
  ring

theorem programPT06MultifieldFirstOrderQuadraticValueBilinear_symmetric
    (density : ProgramPT06MultifieldFirstOrderQuadraticDensity4D Fiber Rank)
    (first second : Fiber) :
    programPT06MultifieldFirstOrderQuadraticValueBilinear density first second =
      programPT06MultifieldFirstOrderQuadraticValueBilinear density second first := by
  rw [programPT06MultifieldFirstOrderQuadraticValueBilinear_apply,
    programPT06MultifieldFirstOrderQuadraticValueBilinear_apply]
  ring

private def programPT06MultifieldFirstOrderQuadraticObstructionEvaluation
    (density : ProgramPT06MultifieldFirstOrderQuadraticDensity4D Fiber Rank) :
    SecondJet (Fiber := Fiber) -> Real :=
  fun jet =>
    density.constant + secondOrderLinearValueCovector density jet +
      density.valueSquare *
        (secondOrderNormalizedValueCovector density jet) ^ 2

/-- Evaluation of the complete autonomous first-order quadratic density. -/
def programPT06MultifieldFirstOrderQuadraticDensityEvaluation
    (density : ProgramPT06MultifieldFirstOrderQuadraticDensity4D Fiber Rank) :
    SecondJet (Fiber := Fiber) -> Real :=
  fun jet =>
    programPT06MultifieldFirstOrderQuadraticObstructionEvaluation density jet +
      programPT06FiniteRankBilinearValueDensityEvaluation
        density.boundaryCurrent jet

private def programPT06MultifieldFirstOrderQuadraticObstructionDerivative
    (density : ProgramPT06MultifieldFirstOrderQuadraticDensity4D Fiber Rank)
    (jet : SecondJet (Fiber := Fiber)) :
    SecondJet (Fiber := Fiber) →L[Real] Real :=
  secondOrderLinearValueCovector density +
    (2 * density.valueSquare *
        secondOrderNormalizedValueCovector density jet) •
      secondOrderNormalizedValueCovector density

private theorem
    programPT06MultifieldFirstOrderQuadraticObstruction_hasFDerivAt
    (density : ProgramPT06MultifieldFirstOrderQuadraticDensity4D Fiber Rank)
    (jet : SecondJet (Fiber := Fiber)) :
    HasFDerivAt
      (programPT06MultifieldFirstOrderQuadraticObstructionEvaluation density)
      (programPT06MultifieldFirstOrderQuadraticObstructionDerivative density jet)
      jet := by
  have hRaw :=
    ((hasFDerivAt_const (x := jet) (c := density.constant)).add
      (secondOrderLinearValueCovector density).hasFDerivAt).add
        (((secondOrderNormalizedValueCovector density).hasFDerivAt.pow 2).const_mul
          density.valueSquare)
  refine hRaw.congr_fderiv ?_
  ext variation
  simp [programPT06MultifieldFirstOrderQuadraticObstructionDerivative]
  ring

private theorem programPT06FiniteRankBoundaryDensity_differentiableAt
    (density : ProgramPT06MultifieldFirstOrderQuadraticDensity4D Fiber Rank)
    (jet : SecondJet (Fiber := Fiber)) :
    DifferentiableAt Real
      (programPT06FiniteRankBilinearValueDensityEvaluation
        density.boundaryCurrent) jet := by
  unfold programPT06FiniteRankBilinearValueDensityEvaluation
  let derivative : SecondJet (Fiber := Fiber) →L[Real] Real :=
    ∑ index : Fin 3 × Rank,
      density.boundaryCurrent.coefficient index.1 index.2 •
        fderiv Real
          (programPT06DirectedQuadraticValueDensityEvaluation
            (programPT06FiniteRankBilinearValueAtom
              density.boundaryCurrent index)) jet
  have hDerivative : HasFDerivAt
      (fun candidate : SecondJet (Fiber := Fiber) =>
        ∑ index : Fin 3 × Rank,
          density.boundaryCurrent.coefficient index.1 index.2 •
            programPT06DirectedQuadraticValueDensityEvaluation
              (programPT06FiniteRankBilinearValueAtom
                density.boundaryCurrent index) candidate)
      derivative jet := by
    apply HasFDerivAt.fun_sum
    intro index _
    exact
      ((programPT06DirectedQuadraticValueDensityEvaluation_hasFDerivAt
          (programPT06FiniteRankBilinearValueAtom
            density.boundaryCurrent index) jet).differentiableAt.hasFDerivAt).const_smul
          (density.boundaryCurrent.coefficient index.1 index.2)
  exact hDerivative.differentiableAt

private theorem
    programPT06MultifieldFirstOrderQuadraticVerticalPartial_add
    (density : ProgramPT06MultifieldFirstOrderQuadraticDensity4D Fiber Rank)
    (jet : SecondJet (Fiber := Fiber))
    (index : ThroatSpatialTruncatedIndex 2) :
    programPT06ThroatSpatialVerticalPartialDerivative
        (programPT06MultifieldFirstOrderQuadraticDensityEvaluation density)
        jet index =
      programPT06ThroatSpatialVerticalPartialDerivative
          (programPT06MultifieldFirstOrderQuadraticObstructionEvaluation density)
          jet index +
        programPT06ThroatSpatialVerticalPartialDerivative
          (programPT06FiniteRankBilinearValueDensityEvaluation
            density.boundaryCurrent) jet index := by
  apply ContinuousLinearMap.ext
  intro variation
  change
    fderiv Real
        (programPT06MultifieldFirstOrderQuadraticObstructionEvaluation density +
          programPT06FiniteRankBilinearValueDensityEvaluation
            density.boundaryCurrent)
        jet
        (programPT06ThroatSpatialJetCoordinateInjection index variation) = _
  rw [fderiv_add
    (programPT06MultifieldFirstOrderQuadraticObstruction_hasFDerivAt
      density jet).differentiableAt
    (programPT06FiniteRankBoundaryDensity_differentiableAt density jet)]
  rfl

private theorem
    programPT06MultifieldFirstOrderQuadraticObstructionVerticalPartialZero
    (density : ProgramPT06MultifieldFirstOrderQuadraticDensity4D Fiber Rank)
    (jet : SecondJet (Fiber := Fiber)) :
    programPT06SecondOrderLocalVerticalPartialZero
        (programPT06MultifieldFirstOrderQuadraticObstructionEvaluation density)
        jet =
      density.valueLinear +
        (2 * density.valueSquare *
            density.normalizedValueCovector
              (secondOrderValueProjection (Fiber := Fiber) jet)) •
          density.normalizedValueCovector := by
  change programPT06ThroatSpatialVerticalPartialDerivative
    (programPT06MultifieldFirstOrderQuadraticObstructionEvaluation density) jet
      programPT06SecondOrderZeroMultiIndex = _
  rw [programPT06ThroatSpatialVerticalPartialDerivative_eq_of_hasFDerivAt
    (programPT06MultifieldFirstOrderQuadraticObstructionEvaluation density) jet
    programPT06SecondOrderZeroMultiIndex
    (programPT06MultifieldFirstOrderQuadraticObstructionDerivative density jet)
    (programPT06MultifieldFirstOrderQuadraticObstruction_hasFDerivAt density jet)]
  apply ContinuousLinearMap.ext
  intro variation
  simp [programPT06MultifieldFirstOrderQuadraticObstructionDerivative,
    secondOrderLinearValueCovector, secondOrderNormalizedValueCovector,
    secondOrderValueProjection]

private theorem
    programPT06MultifieldFirstOrderQuadraticObstructionVerticalPartialOne
    (density : ProgramPT06MultifieldFirstOrderQuadraticDensity4D Fiber Rank)
    (direction : Fin 3) :
    programPT06SecondOrderLocalVerticalPartialOne
        (programPT06MultifieldFirstOrderQuadraticObstructionEvaluation density)
        direction = 0 := by
  funext jet
  change programPT06ThroatSpatialVerticalPartialDerivative
    (programPT06MultifieldFirstOrderQuadraticObstructionEvaluation density) jet
      (programPT06SecondOrderFirstMultiIndex direction) = _
  rw [programPT06ThroatSpatialVerticalPartialDerivative_eq_of_hasFDerivAt
    (programPT06MultifieldFirstOrderQuadraticObstructionEvaluation density) jet
    (programPT06SecondOrderFirstMultiIndex direction)
    (programPT06MultifieldFirstOrderQuadraticObstructionDerivative density jet)
    (programPT06MultifieldFirstOrderQuadraticObstruction_hasFDerivAt density jet)]
  apply ContinuousLinearMap.ext
  intro variation
  simp [programPT06MultifieldFirstOrderQuadraticObstructionDerivative,
    secondOrderLinearValueCovector, secondOrderNormalizedValueCovector,
    secondOrderValueProjection,
    Ne.symm (secondOrderFirstMultiIndex_ne_zero direction)]

private theorem
    programPT06MultifieldFirstOrderQuadraticObstructionVerticalPartialTwo
    (density : ProgramPT06MultifieldFirstOrderQuadraticDensity4D Fiber Rank)
    (first second : Fin 3) :
    programPT06SecondOrderLocalVerticalPartialTwo
        (programPT06MultifieldFirstOrderQuadraticObstructionEvaluation density)
        first second = 0 := by
  funext jet
  change programPT06ThroatSpatialVerticalPartialDerivative
    (programPT06MultifieldFirstOrderQuadraticObstructionEvaluation density) jet
      (programPT06SecondOrderSecondMultiIndex first second) = _
  rw [programPT06ThroatSpatialVerticalPartialDerivative_eq_of_hasFDerivAt
    (programPT06MultifieldFirstOrderQuadraticObstructionEvaluation density) jet
    (programPT06SecondOrderSecondMultiIndex first second)
    (programPT06MultifieldFirstOrderQuadraticObstructionDerivative density jet)
    (programPT06MultifieldFirstOrderQuadraticObstruction_hasFDerivAt density jet)]
  apply ContinuousLinearMap.ext
  intro variation
  simp [programPT06MultifieldFirstOrderQuadraticObstructionDerivative,
    secondOrderLinearValueCovector, secondOrderNormalizedValueCovector,
    secondOrderValueProjection,
    Ne.symm (secondOrderSecondMultiIndex_ne_zero first second)]

private theorem programPT06MultifieldFirstOrderQuadraticVerticalPartialZero
    (density : ProgramPT06MultifieldFirstOrderQuadraticDensity4D Fiber Rank) :
    programPT06SecondOrderLocalVerticalPartialZero
        (programPT06MultifieldFirstOrderQuadraticDensityEvaluation density) =
      fun jet =>
        density.valueLinear +
          (2 * density.valueSquare *
              density.normalizedValueCovector
                (secondOrderValueProjection (Fiber := Fiber) jet)) •
            density.normalizedValueCovector +
          programPT06SecondOrderLocalVerticalPartialZero
            (programPT06FiniteRankBilinearValueDensityEvaluation
              density.boundaryCurrent) jet := by
  funext jet
  rw [show
    programPT06SecondOrderLocalVerticalPartialZero
        (programPT06MultifieldFirstOrderQuadraticDensityEvaluation density) jet =
      programPT06SecondOrderLocalVerticalPartialZero
          (programPT06MultifieldFirstOrderQuadraticObstructionEvaluation density)
          jet +
        programPT06SecondOrderLocalVerticalPartialZero
          (programPT06FiniteRankBilinearValueDensityEvaluation
            density.boundaryCurrent) jet from
      programPT06MultifieldFirstOrderQuadraticVerticalPartial_add density jet
        programPT06SecondOrderZeroMultiIndex]
  rw [programPT06MultifieldFirstOrderQuadraticObstructionVerticalPartialZero]

private theorem programPT06MultifieldFirstOrderQuadraticVerticalPartialOne
    (density : ProgramPT06MultifieldFirstOrderQuadraticDensity4D Fiber Rank)
    (direction : Fin 3) :
    programPT06SecondOrderLocalVerticalPartialOne
        (programPT06MultifieldFirstOrderQuadraticDensityEvaluation density)
        direction =
      programPT06SecondOrderLocalVerticalPartialOne
        (programPT06FiniteRankBilinearValueDensityEvaluation
          density.boundaryCurrent) direction := by
  funext jet
  rw [show
    programPT06SecondOrderLocalVerticalPartialOne
        (programPT06MultifieldFirstOrderQuadraticDensityEvaluation density)
        direction jet =
      programPT06SecondOrderLocalVerticalPartialOne
          (programPT06MultifieldFirstOrderQuadraticObstructionEvaluation density)
          direction jet +
        programPT06SecondOrderLocalVerticalPartialOne
          (programPT06FiniteRankBilinearValueDensityEvaluation
            density.boundaryCurrent) direction jet from
      programPT06MultifieldFirstOrderQuadraticVerticalPartial_add density jet
        (programPT06SecondOrderFirstMultiIndex direction)]
  rw [programPT06MultifieldFirstOrderQuadraticObstructionVerticalPartialOne]
  simp

private theorem programPT06MultifieldFirstOrderQuadraticVerticalPartialTwo
    (density : ProgramPT06MultifieldFirstOrderQuadraticDensity4D Fiber Rank)
    (first second : Fin 3) :
    programPT06SecondOrderLocalVerticalPartialTwo
        (programPT06MultifieldFirstOrderQuadraticDensityEvaluation density)
        first second =
      programPT06SecondOrderLocalVerticalPartialTwo
        (programPT06FiniteRankBilinearValueDensityEvaluation
          density.boundaryCurrent) first second := by
  funext jet
  rw [show
    programPT06SecondOrderLocalVerticalPartialTwo
        (programPT06MultifieldFirstOrderQuadraticDensityEvaluation density)
        first second jet =
      programPT06SecondOrderLocalVerticalPartialTwo
          (programPT06MultifieldFirstOrderQuadraticObstructionEvaluation density)
          first second jet +
        programPT06SecondOrderLocalVerticalPartialTwo
          (programPT06FiniteRankBilinearValueDensityEvaluation
            density.boundaryCurrent) first second jet from
      programPT06MultifieldFirstOrderQuadraticVerticalPartial_add density jet
        (programPT06SecondOrderSecondMultiIndex first second)]
  rw [programPT06MultifieldFirstOrderQuadraticObstructionVerticalPartialTwo]
  simp

private theorem programPT06MultifieldFirstOrderQuadraticEulerFirstTerm
    (density : ProgramPT06MultifieldFirstOrderQuadraticDensity4D Fiber Rank)
    (direction : Fin 3) :
    programPT06SecondOrderLocalEulerFirstTotalTerm
        (programPT06MultifieldFirstOrderQuadraticDensityEvaluation density)
        direction =
      programPT06SecondOrderLocalEulerFirstTotalTerm
        (programPT06FiniteRankBilinearValueDensityEvaluation
          density.boundaryCurrent) direction := by
  rw [programPT06SecondOrderLocalEulerFirstTotalTerm,
    programPT06MultifieldFirstOrderQuadraticVerticalPartialOne]
  rfl

private theorem programPT06MultifieldFirstOrderQuadraticEulerSecondTerm
    (density : ProgramPT06MultifieldFirstOrderQuadraticDensity4D Fiber Rank)
    (first second : Fin 3) :
    programPT06SecondOrderLocalEulerSecondTotalTerm
        (programPT06MultifieldFirstOrderQuadraticDensityEvaluation density)
        first second =
      programPT06SecondOrderLocalEulerSecondTotalTerm
        (programPT06FiniteRankBilinearValueDensityEvaluation
          density.boundaryCurrent) first second := by
  rw [programPT06SecondOrderLocalEulerSecondTotalTerm,
    programPT06MultifieldFirstOrderQuadraticVerticalPartialTwo]
  rfl

/-- Exact Gate880 Euler formula for the normalized multifield family. -/
theorem programPT06SecondOrderLocalEuler_multifieldFirstOrderQuadratic_formula
    (density : ProgramPT06MultifieldFirstOrderQuadraticDensity4D Fiber Rank)
    (jet : FourthJet (Fiber := Fiber)) :
    programPT06SecondOrderLocalEuler
        (programPT06MultifieldFirstOrderQuadraticDensityEvaluation density) jet =
      density.valueLinear +
        (2 * density.valueSquare *
            density.normalizedValueCovector
              (jet fourthOrderZeroMultiIndex)) •
          density.normalizedValueCovector := by
  rw [programPT06SecondOrderLocalEuler_formula,
    programPT06MultifieldFirstOrderQuadraticVerticalPartialZero]
  simp_rw [programPT06MultifieldFirstOrderQuadraticEulerFirstTerm,
    programPT06MultifieldFirstOrderQuadraticEulerSecondTerm]
  rw [secondOrderValueProjection_truncate_fourth]
  have hBoundary :=
    programPT06SecondOrderLocalEuler_finiteRankBilinearValueDensity_eq_zero
      density.boundaryCurrent jet
  rw [programPT06SecondOrderLocalEuler_formula] at hBoundary
  calc
    (density.valueLinear +
          (2 * density.valueSquare *
              density.normalizedValueCovector (jet fourthOrderZeroMultiIndex)) •
            density.normalizedValueCovector +
          programPT06SecondOrderLocalVerticalPartialZero
            (programPT06FiniteRankBilinearValueDensityEvaluation
              density.boundaryCurrent)
            (truncateThroatSpatialMultiindexJet (by omega : 2 <= 4) jet)) -
        (∑ direction : Fin 3,
          programPT06SecondOrderLocalEulerFirstTotalTerm
            (programPT06FiniteRankBilinearValueDensityEvaluation
              density.boundaryCurrent) direction
            (truncateThroatSpatialMultiindexJet (by omega : 3 <= 4) jet)) +
        ∑ first : Fin 3, ∑ second : Fin 3,
          programPT06SecondOrderEulerSymmetryWeight first second •
            programPT06SecondOrderLocalEulerSecondTotalTerm
              (programPT06FiniteRankBilinearValueDensityEvaluation
                density.boundaryCurrent) first second jet =
      (density.valueLinear +
          (2 * density.valueSquare *
              density.normalizedValueCovector (jet fourthOrderZeroMultiIndex)) •
            density.normalizedValueCovector) +
        (programPT06SecondOrderLocalVerticalPartialZero
              (programPT06FiniteRankBilinearValueDensityEvaluation
                density.boundaryCurrent)
              (truncateThroatSpatialMultiindexJet (by omega : 2 <= 4) jet) -
          (∑ direction : Fin 3,
            programPT06SecondOrderLocalEulerFirstTotalTerm
              (programPT06FiniteRankBilinearValueDensityEvaluation
                density.boundaryCurrent) direction
              (truncateThroatSpatialMultiindexJet (by omega : 3 <= 4) jet)) +
          ∑ first : Fin 3, ∑ second : Fin 3,
            programPT06SecondOrderEulerSymmetryWeight first second •
              programPT06SecondOrderLocalEulerSecondTotalTerm
                (programPT06FiniteRankBilinearValueDensityEvaluation
                  density.boundaryCurrent) first second jet) := by
        abel
    _ = density.valueLinear +
          (2 * density.valueSquare *
              density.normalizedValueCovector (jet fourthOrderZeroMultiIndex)) •
            density.normalizedValueCovector := by
      rw [hBoundary]
      simp

/-- The normalization witness makes Euler vanishing equivalent to vanishing
of the two displayed value coefficients. -/
theorem programPT06_multifieldFirstOrderQuadratic_euler_eq_zero_iff
    (density : ProgramPT06MultifieldFirstOrderQuadraticDensity4D Fiber Rank) :
    (forall jet : FourthJet (Fiber := Fiber),
      programPT06SecondOrderLocalEuler
        (programPT06MultifieldFirstOrderQuadraticDensityEvaluation density)
        jet = 0) <->
      density.valueLinear = 0 ∧ density.valueSquare = 0 := by
  constructor
  · intro hEuler
    have hAtZero := hEuler 0
    rw [programPT06SecondOrderLocalEuler_multifieldFirstOrderQuadratic_formula]
      at hAtZero
    have hLinear : density.valueLinear = 0 := by
      simpa using hAtZero
    have hAtWitness := congrArg
      (fun covector : Fiber →L[Real] Real =>
        covector density.normalizedValueWitness)
      (hEuler
        (programPT06ThroatSpatialJetCoordinateInjection
          fourthOrderZeroMultiIndex density.normalizedValueWitness))
    rw [programPT06SecondOrderLocalEuler_multifieldFirstOrderQuadratic_formula]
      at hAtWitness
    have hSquare : density.valueSquare = 0 := by
      simp [hLinear, density.normalizedValueCovector_witness] at hAtWitness
      linarith
    exact ⟨hLinear, hSquare⟩
  · rintro ⟨hLinear, hSquare⟩ jet
    rw [programPT06SecondOrderLocalEuler_multifieldFirstOrderQuadratic_formula]
    simp [hLinear, hSquare]

/-- Gate898's current is the explicit horizontal primitive of the quadratic
kernel part. -/
def programPT06MultifieldFirstOrderQuadraticKernelCurrent
    (density : ProgramPT06MultifieldFirstOrderQuadraticDensity4D Fiber Rank) :
    ProgramPT06FiniteRankBilinearValueCurrent4D Fiber Rank :=
  density.boundaryCurrent

/-- Under the coefficient kernel conditions, the density is a constant plus
the genuine Gate898 horizontal divergence. -/
theorem programPT06MultifieldFirstOrderQuadratic_eq_constant_add_dH
    (density : ProgramPT06MultifieldFirstOrderQuadraticDensity4D Fiber Rank)
    (hLinear : density.valueLinear = 0)
    (hSquare : density.valueSquare = 0)
    (jet : SecondJet (Fiber := Fiber)) :
    programPT06MultifieldFirstOrderQuadraticDensityEvaluation density jet =
      density.constant +
        programPT06FiniteRankBilinearValueCurrentDivergence
          (programPT06MultifieldFirstOrderQuadraticKernelCurrent density) jet := by
  rw [programPT06FiniteRankBilinearValueCurrentDivergence_eq_density]
  simp [programPT06MultifieldFirstOrderQuadraticDensityEvaluation,
    programPT06MultifieldFirstOrderQuadraticObstructionEvaluation,
    programPT06MultifieldFirstOrderQuadraticKernelCurrent,
    secondOrderLinearValueCovector, hLinear, hSquare]

/-- Exact coefficient-and-homotopy classification on this normalized
multifield quadratic subclass. -/
theorem programPT06_multifieldFirstOrderQuadratic_euler_eq_zero_iff_divergence_form
    (density : ProgramPT06MultifieldFirstOrderQuadraticDensity4D Fiber Rank) :
    (forall jet : FourthJet (Fiber := Fiber),
      programPT06SecondOrderLocalEuler
        (programPT06MultifieldFirstOrderQuadraticDensityEvaluation density)
        jet = 0) <->
      density.valueLinear = 0 ∧ density.valueSquare = 0 ∧
        forall jet : SecondJet (Fiber := Fiber),
          programPT06MultifieldFirstOrderQuadraticDensityEvaluation density jet =
            density.constant +
              programPT06FiniteRankBilinearValueCurrentDivergence
                (programPT06MultifieldFirstOrderQuadraticKernelCurrent density)
                jet := by
  constructor
  · intro hEuler
    rcases
        (programPT06_multifieldFirstOrderQuadratic_euler_eq_zero_iff density).mp
          hEuler with
      ⟨hLinear, hSquare⟩
    exact ⟨hLinear, hSquare,
      programPT06MultifieldFirstOrderQuadratic_eq_constant_add_dH
        density hLinear hSquare⟩
  · rintro ⟨hLinear, hSquare, _hDivergence⟩
    exact
      (programPT06_multifieldFirstOrderQuadratic_euler_eq_zero_iff density).mpr
        ⟨hLinear, hSquare⟩

/-- Every Gate898 finite-rank current embeds into the kernel family after a
choice of normalized covector. -/
def programPT06MultifieldFirstOrderQuadraticOfFiniteRank
    (current : ProgramPT06FiniteRankBilinearValueCurrent4D Fiber Rank)
    (normalizedCovector : Fiber →L[Real] Real) (witness : Fiber)
    (hWitness : normalizedCovector witness = 1) :
    ProgramPT06MultifieldFirstOrderQuadraticDensity4D Fiber Rank where
  constant := 0
  valueLinear := 0
  normalizedValueCovector := normalizedCovector
  normalizedValueWitness := witness
  normalizedValueCovector_witness := hWitness
  valueSquare := 0
  boundaryCurrent := current

@[simp] theorem
    programPT06MultifieldFirstOrderQuadraticOfFiniteRank_evaluation
    (current : ProgramPT06FiniteRankBilinearValueCurrent4D Fiber Rank)
    (normalizedCovector : Fiber →L[Real] Real) (witness : Fiber)
    (hWitness : normalizedCovector witness = 1)
    (jet : SecondJet (Fiber := Fiber)) :
    programPT06MultifieldFirstOrderQuadraticDensityEvaluation
        (programPT06MultifieldFirstOrderQuadraticOfFiniteRank
          current normalizedCovector witness hWitness) jet =
      programPT06FiniteRankBilinearValueDensityEvaluation current jet := by
  simp [programPT06MultifieldFirstOrderQuadraticDensityEvaluation,
    programPT06MultifieldFirstOrderQuadraticObstructionEvaluation,
    programPT06MultifieldFirstOrderQuadraticOfFiniteRank,
    secondOrderLinearValueCovector]

end
end P0EFTJanusProgramPT06MultifieldFirstOrderQuadraticKernel4D
end JanusFormal
