import JanusFormal.Branches.FundamentalGeometryPVariationalPrinciple.Gates.P0EFTJanusMappingTorusCanonicalPhysicalScalarIntrinsicWaveCanonicalNormalRieszScalarEnergyPDEClosure4D
import JanusFormal.Branches.FundamentalGeometryPVariationalPrinciple.Gates.P0EFTJanusMappingTorusCanonicalPhysicalScalarCauchyJetEulerCanonicalL2Operators4D

/-!
# Smallest PDE package from six canonical boundary `L²` operators

The six Euler coefficients are now supplied directly as continuous operators on
the completed Cauchy boundary space.  Their canonical `L²` representatives,
`MemLp` proofs, constants, product integrability and residual-square
integrability are all theorems.

The remaining PDE input is exactly:

* one intrinsic global scalar-wave representative;
* one normal Green density and its two integral identities;
* one scalar first-jet energy identity;
* six canonical boundary `L²` coefficient operators and the exact residual
  expansion.
-/

namespace JanusFormal
namespace P0EFTJanusMappingTorusCanonicalPhysicalScalarIntrinsicWaveCanonicalNormalRieszScalarEnergyL2OperatorPDEClosure4D

set_option autoImplicit false
noncomputable section

open Set Topology MeasureTheory
open P0EFTJanusMappingTorusCanonicalPhysicalScalarIntrinsicWaveCanonicalNormalGreen4D
open P0EFTJanusMappingTorusCanonicalPhysicalScalarIntrinsicWaveCanonicalNormalRieszScalarEnergyPDEClosure4D
open P0EFTJanusMappingTorusCanonicalPhysicalScalarScalarRemainderEnergyIdentity4D
open P0EFTJanusMappingTorusCanonicalPhysicalScalarCauchyJetGeometricGreenCore4D
open P0EFTJanusMappingTorusScalarHilbertGreenCoreCompletion4D

variable (period : Real) (hPeriod : period ≠ 0)
variable {massSquared : Real}

/-- Smallest current completed-boundary PDE data with canonical `L²`
coefficients. -/
structure CanonicalPhysicalScalarIntrinsicWaveCanonicalNormalRieszScalarEnergyL2OperatorPDEData
    (massSquared : Real) where
  geometric : CanonicalPhysicalScalarIntrinsicWaveCanonicalNormalGreenData
    period hPeriod massSquared
  energyIdentity : (geometric.greenCore period hPeriod).ScalarRemainderEnergyIdentityData
    period hPeriod
  eulerCoefficientOperators :
    geometric.toNormalTangentialGreenData.toIntrinsicWaveLocalGreenData.toCanonicalLocalDivergenceData.toCanonicalWaveCauchyJetData.toCanonicalCauchyJetCompatibilityData.toCompatibilityData.toCauchyJetGeometricData.CauchyJetEulerSixCanonicalL2OperatorData
      period hPeriod

namespace CanonicalPhysicalScalarIntrinsicWaveCanonicalNormalRieszScalarEnergyL2OperatorPDEData

/-- Explicit Cauchy-jet geometric data. -/
def jetGeometric
    (data : CanonicalPhysicalScalarIntrinsicWaveCanonicalNormalRieszScalarEnergyL2OperatorPDEData
      period hPeriod massSquared) :=
  data.geometric.toNormalTangentialGreenData period hPeriod
    |>.toIntrinsicWaveLocalGreenData period hPeriod
    |>.toCanonicalLocalDivergenceData period hPeriod
    |>.toCanonicalWaveCauchyJetData period hPeriod
    |>.toCanonicalCauchyJetCompatibilityData period hPeriod
    |>.toCompatibilityData period hPeriod
    |>.toCauchyJetGeometricData period hPeriod

/-- Conversion to the former bounded-coefficient smallest PDE package. -/
def toCanonicalNormalRieszScalarEnergyPDEData
    (data : CanonicalPhysicalScalarIntrinsicWaveCanonicalNormalRieszScalarEnergyL2OperatorPDEData
      period hPeriod massSquared) :
    CanonicalPhysicalScalarIntrinsicWaveCanonicalNormalRieszScalarEnergyPDEData
      period hPeriod massSquared where
  geometric := data.geometric
  energyIdentity := data.energyIdentity
  eulerCoefficients :=
    data.eulerCoefficientOperators.toSixBoundedCoefficientData period hPeriod

/-- Final Euler product estimate generated by operator norms. -/
def eulerEstimate
    (data : CanonicalPhysicalScalarIntrinsicWaveCanonicalNormalRieszScalarEnergyL2OperatorPDEData
      period hPeriod massSquared) :=
  data.eulerCoefficientOperators.toEulerProductEstimateData period hPeriod

/-- Riesz-generated completed physical boundary triple. -/
def triple
    (data : CanonicalPhysicalScalarIntrinsicWaveCanonicalNormalRieszScalarEnergyL2OperatorPDEData
      period hPeriod massSquared) :=
  (data.toCanonicalNormalRieszScalarEnergyPDEData period hPeriod).triple
    period hPeriod

/-- Completed Riesz trace. -/
def completedBoundaryTrace
    (data : CanonicalPhysicalScalarIntrinsicWaveCanonicalNormalRieszScalarEnergyL2OperatorPDEData
      period hPeriod massSquared) :=
  (data.toCanonicalNormalRieszScalarEnergyPDEData period hPeriod).completedBoundaryTrace
    period hPeriod

/-- Bounded right inverse of the completed trace. -/
def completedExtension
    (data : CanonicalPhysicalScalarIntrinsicWaveCanonicalNormalRieszScalarEnergyL2OperatorPDEData
      period hPeriod massSquared) :=
  (data.toCanonicalNormalRieszScalarEnergyPDEData period hPeriod).completedExtension
    period hPeriod

/-- Physical graph-elliptic estimate. -/
def graphEllipticEstimate
    (data : CanonicalPhysicalScalarIntrinsicWaveCanonicalNormalRieszScalarEnergyL2OperatorPDEData
      period hPeriod massSquared) :=
  data.energyIdentity.toGraphEllipticEstimate period hPeriod
    (data.geometric.greenCore period hPeriod)

/-- Completed extension is a right inverse of the Riesz trace. -/
theorem completedBoundaryTrace_extension
    (data : CanonicalPhysicalScalarIntrinsicWaveCanonicalNormalRieszScalarEnergyL2OperatorPDEData
      period hPeriod massSquared)
    (boundary :
      P0EFTJanusMappingTorusScalarHilbertBoundarySymplectic4D.CanonicalScalarHilbertBoundaryDatum
        (Trace := P0EFTJanusMappingTorusCanonicalPhysicalScalarFirstSheetHilbertTrace4D.CanonicalPhysicalScalarFirstSheetL2 period)) :
    data.completedBoundaryTrace period hPeriod
        (data.completedExtension period hPeriod boundary) = boundary :=
  (data.toCanonicalNormalRieszScalarEnergyPDEData period hPeriod)
    |>.completedBoundaryTrace_extension period hPeriod boundary

/-- Canonical-`L²`-operator PDE certificate. -/
theorem certificate
    (data : CanonicalPhysicalScalarIntrinsicWaveCanonicalNormalRieszScalarEnergyL2OperatorPDEData
      period hPeriod massSquared) :
    P0EFTJanusMappingTorusCanonicalPhysicalScalarEulerAtlasNaturality4D.CanonicalPhysicalScalarWaveAtlasNaturality
        period hPeriod ∧
      (∀ index boundary,
        MemLp
          (data.eulerCoefficientOperators.coefficient period hPeriod index boundary)
          (2 : ENNReal)
          (P0EFTJanusMappingTorusCanonicalPhysicalH1TraceBound4D.canonicalLatitudeBaseMeasure
            period)) ∧
      (∀ boundary,
        Integrable
          (fun parameter =>
            (data.jetGeometric period hPeriod).canonicalEulerProductResidual
              period hPeriod boundary parameter ^ 2)
          (P0EFTJanusMappingTorusCanonicalLatitudeCauchyJetProductCoarea4D.canonicalLatitudeCauchyJetProductMeasure
            period)) ∧
      Function.Injective
        (canonicalScalarGreenCoreGraphInclusion
          (data.geometric.greenCore period hPeriod).core) ∧
      Function.Surjective (data.completedBoundaryTrace period hPeriod) ∧
      (∀ boundary,
        data.completedBoundaryTrace period hPeriod
          (data.completedExtension period hPeriod boundary) = boundary) :=
  ⟨data.geometric.intrinsicWave.toWaveAtlasNaturality period hPeriod,
    data.eulerCoefficientOperators.coefficient_memLp period hPeriod,
    (data.jetGeometric period hPeriod).canonicalEulerProductResidual_sq_integrable
      period hPeriod,
    ((data.toCanonicalNormalRieszScalarEnergyPDEData period hPeriod).certificate
      period hPeriod).2.2.2.1,
    ((data.toCanonicalNormalRieszScalarEnergyPDEData period hPeriod).certificate
      period hPeriod).2.2.2.2.1,
    data.completedBoundaryTrace_extension period hPeriod⟩

end CanonicalPhysicalScalarIntrinsicWaveCanonicalNormalRieszScalarEnergyL2OperatorPDEData

end
end P0EFTJanusMappingTorusCanonicalPhysicalScalarIntrinsicWaveCanonicalNormalRieszScalarEnergyL2OperatorPDEClosure4D
end JanusFormal
