import JanusFormal.Branches.FundamentalGeometryPVariationalPrinciple.Gates.P0EFTJanusProgramPFiveSectorL2LinearNaturalRepresentationAdmissibleIsomorphismFrameBridge4D
import JanusFormal.Branches.FundamentalGeometryPVariationalPrinciple.Gates.P0EFTJanusProgramPFiniteLinearEquivTransportGram4D

/-!
# L² admissible frames, kernel transport and global Gram nondegeneracy

An admissible D11 basepoint frame restricts to linear equivalences between the
true kernels.  Once a genuine basis of the base kernel is supplied, the generic
linear-equivalence Gram theorem proves nondegeneracy at every parameter.
-/

namespace JanusFormal
namespace P0EFTJanusProgramPFiveSectorL2AdmissibleFrameKernelGramBridge4D

set_option autoImplicit false

noncomputable section

open scoped InnerProductSpace
open P0EFTJanusSpinCImmersionCategory
open P0EFTJanusNaturalEllipticFamilyExistence
open P0EFTJanusProgramPNaturalEllipticOperatorRepresentation4D
open P0EFTJanusProgramPFiveSectorHilbertCoordinates4D
open P0EFTJanusProgramPFiveSectorL2HilbertCoordinates4D
open P0EFTJanusProgramPFiveSectorNaturalRepresentationRefinement4D
open P0EFTJanusProgramPFiveSectorNaturalRepresentationPullback4D
open P0EFTJanusProgramPFiveSectorL2NaturalRepresentationPullbackBridge4D
open P0EFTJanusProgramPFiveSectorOrthogonalProductResolution4D
open P0EFTJanusProgramPLinearNaturalRepresentationAdmissibleIsomorphismFrame4D
open P0EFTJanusProgramPFiveSectorL2LinearNaturalRepresentationAdmissibleIsomorphismFrameBridge4D
open P0EFTJanusProgramPFiniteIntertwiningOperatorFrameTransport4D
open P0EFTJanusProgramPFiniteIntertwiningOperatorKernelTransport4D
open P0EFTJanusProgramPFiniteLinearEquivTransportGram4D

variable
  {State Metric Abelian Matter Longitudinal Boundary Index : Type*}
  [NormedAddCommGroup State] [InnerProductSpace Real State]
  [NormedAddCommGroup Metric] [InnerProductSpace Real Metric]
  [NormedAddCommGroup Abelian] [InnerProductSpace Real Abelian]
  [NormedAddCommGroup Matter] [InnerProductSpace Real Matter]
  [NormedAddCommGroup Longitudinal] [InnerProductSpace Real Longitudinal]
  [NormedAddCommGroup Boundary] [InnerProductSpace Real Boundary]
  {immersionCategory : SpinCImmersionCategory}
  {family : NaturalEllipticOperatorFamily immersionCategory}
  {operator : Real → State →L[Real] State}

/-- Minimal honest input for the L² frame-to-Gram route.  The base-kernel
basis is data, not inferred from the frame. -/
structure FiveSectorL2AdmissibleFrameKernelGramData
    (representation : NaturalEllipticOperatorRepresentationData
      immersionCategory family
        (fun parameter state => operator parameter state))
    (coordinates : FiveSectorHilbertCoordinates
      (E := State) (Metric := Metric) (Abelian := Abelian) (Matter := Matter)
      (Longitudinal := Longitudinal) (Boundary := Boundary))
    (refinement : FiveSectorNaturalRepresentationRefinementData
      representation coordinates)
    (pullback : FiveSectorNaturalRepresentationPullbackData
      representation coordinates refinement) where
  l2Coordinates : FiveSectorL2HilbertCoordinates
    (E := State) (Metric := Metric) (Abelian := Abelian) (Matter := Matter)
    (Longitudinal := Longitudinal) (Boundary := Boundary)
  projector_eq : ∀ sector,
    coordinates.sectorProjector sector =
      l2Coordinates.sectorProjector (fivePhysicalSectorL2SlotEquiv sector)
  frameData : LinearNaturalRepresentationAdmissibleIsomorphismFrameData
    representation coordinates refinement pullback
  baseKernelBasis : Module.Basis Index Real (operator 0).ker

namespace FiveSectorL2AdmissibleFrameKernelGramData

variable
  (representation : NaturalEllipticOperatorRepresentationData
    immersionCategory family
      (fun parameter state => operator parameter state))
  (coordinates : FiveSectorHilbertCoordinates
    (E := State) (Metric := Metric) (Abelian := Abelian) (Matter := Matter)
    (Longitudinal := Longitudinal) (Boundary := Boundary))
  (refinement : FiveSectorNaturalRepresentationRefinementData
    representation coordinates)
  (pullback : FiveSectorNaturalRepresentationPullbackData
    representation coordinates refinement)
  (data : FiveSectorL2AdmissibleFrameKernelGramData
    (Index := Index) representation coordinates refinement pullback)

/-- Generic operator frame supplied by the admissible represented frame. -/
def operatorFrame : FiniteIntertwiningOperatorFrameData operator :=
  data.frameData.toFiniteIntertwiningOperatorFrame representation coordinates
    refinement pullback

/-- Coherent pairwise ambient transport generated by the basepoint frame. -/
def operatorTransport : FiniteIntertwiningOperatorTransportData operator :=
  FiniteIntertwiningOperatorFrameData.toFiniteIntertwiningOperatorTransport
    (data.operatorFrame representation coordinates refinement pullback)

/-- Restriction of the basepoint frame transport to the true kernels. -/
def kernelTransport (parameter : Real) :
    (operator 0).ker ≃ₗ[Real] (operator parameter).ker :=
  FiniteIntertwiningOperatorTransportData.kernelTransport
    (data.operatorTransport representation coordinates refinement pullback)
      0 parameter

/-- Base-kernel basis vector transported into the true kernel at a parameter. -/
def transportedKernelVector (parameter : Real) (index : Index) :
    (operator parameter).ker :=
  data.kernelTransport representation coordinates refinement pullback parameter
    (data.baseKernelBasis index)

/-- The transported kernel vectors remain linearly independent. -/
theorem transportedKernelVector_linearIndependent (parameter : Real) :
    LinearIndependent Real
      (data.transportedKernelVector representation coordinates refinement
        pullback parameter) :=
  linearIndependent_basis_linearEquiv data.baseKernelBasis
    (data.kernelTransport representation coordinates refinement pullback
      parameter)

/-- The transported kernel Gram determinant is nonzero at every parameter. -/
theorem transportedKernelGram_det_ne_zero
    [Fintype Index] [DecidableEq Index] (parameter : Real) :
    (Matrix.gram Real
      (data.transportedKernelVector representation coordinates refinement
        pullback parameter)).det ≠ 0 :=
  gram_det_ne_zero_of_basis_linearEquiv data.baseKernelBasis
    (data.kernelTransport representation coordinates refinement pullback
      parameter)

/-- The same admissible frame preserves every L² physical projector. -/
theorem frame_commutes_l2Projector
    (parameter : Real) (sector : FiveSectorSlot) (state : State) :
    data.frameData.frame representation coordinates refinement pullback parameter
        (data.l2Coordinates.sectorProjector sector state) =
      data.l2Coordinates.sectorProjector sector
        (data.frameData.frame representation coordinates refinement pullback
          parameter state) :=
  frame_commutes_l2SectorProjector representation coordinates refinement
    pullback data.frameData data.l2Coordinates data.projector_eq parameter sector
      state

/-- Public all-parameter L² frame/kernel/Gram checkpoint. -/
theorem five_sector_l2_admissible_frame_kernel_gram_gate
    [Fintype Index] [DecidableEq Index] :
    (∀ parameter sector state,
      data.frameData.frame representation coordinates refinement pullback
          parameter (data.l2Coordinates.sectorProjector sector state) =
        data.l2Coordinates.sectorProjector sector
          (data.frameData.frame representation coordinates refinement pullback
            parameter state)) ∧
    (∀ parameter index,
      operator parameter
        (data.transportedKernelVector representation coordinates refinement
          pullback parameter index).1 = 0) ∧
    (∀ parameter,
      LinearIndependent Real
        (data.transportedKernelVector representation coordinates refinement
          pullback parameter)) ∧
    (∀ parameter,
      (Matrix.gram Real
        (data.transportedKernelVector representation coordinates refinement
          pullback parameter)).det ≠ 0) :=
  ⟨data.frame_commutes_l2Projector representation coordinates refinement
      pullback,
    fun parameter index =>
      (data.transportedKernelVector representation coordinates refinement
        pullback parameter index).2,
    data.transportedKernelVector_linearIndependent representation coordinates
      refinement pullback,
    data.transportedKernelGram_det_ne_zero representation coordinates refinement
      pullback⟩

end FiveSectorL2AdmissibleFrameKernelGramData

end

end P0EFTJanusProgramPFiveSectorL2AdmissibleFrameKernelGramBridge4D
end JanusFormal
