import JanusFormal.Branches.FundamentalGeometryPVariationalPrinciple.Gates.P0EFTJanusMappingTorusCanonicalLatitudeTubularCollarEmbedding4D
import JanusFormal.Branches.FundamentalGeometryPVariationalPrinciple.Gates.P0EFTJanusMappingTorusCanonicalLatitudeCauchyJetCollarQuotient4D

/-!
# Global physical candidate generated by the latitude Cauchy jet

The tubular collar quotient embeds injectively into the physical mapping torus.
A deck-compatible local Cauchy jet therefore defines an unambiguous scalar on the
physical tubular image.  Extend it by zero away from that image.  The resulting
global function has exactly the prescribed value and normal derivative at the
canonical throat.

Smoothness across the boundary of the tubular image is deliberately separated:
the compactly supported profiles make it a local extension-by-zero problem.
-/

namespace JanusFormal
namespace P0EFTJanusMappingTorusCanonicalPhysicalScalarCauchyJetGlobalCandidate4D

set_option autoImplicit false
noncomputable section

open Set Topology Filter
open P0EFTJanusMappingTorusQuotient
open P0EFTJanusMappingTorusSmoothAtlasFrontier
open P0EFTJanusMappingTorusCanonicalPhysicalH1TraceBound4D
open P0EFTJanusMappingTorusCanonicalLatitudeCauchyJetProfiles4D
open P0EFTJanusMappingTorusCanonicalLatitudeCauchyJetDeckGluing4D
open P0EFTJanusMappingTorusCanonicalLatitudeCauchyJetCollarQuotient4D
open P0EFTJanusMappingTorusCanonicalLatitudeTubularCollarEmbedding4D

variable (period : Real) (hPeriod : period ≠ 0)

private abbrev sphereData := reflectedSphereData period hPeriod
private abbrev EffectiveQuotient := MappingTorus (sphereData period hPeriod)

namespace CanonicalLatitudeDeckCauchyData

/-- Restriction of the local Cauchy expression to the genuine tubular band. -/
def tubularLocalExtension
    (data : CanonicalLatitudeDeckCauchyData period)
    (parameter : CanonicalLatitudeTubularCollar) : Real :=
  data.localExtension (parameter.1, parameter.2.1)

/-- Generator invariance on the tubular band. -/
theorem tubularLocalExtension_deck
    (data : CanonicalLatitudeDeckCauchyData period)
    (parameter : CanonicalLatitudeTubularCollar) :
    data.tubularLocalExtension
        (canonicalLatitudeTubularDeckEquiv period parameter) =
      data.tubularLocalExtension parameter := by
  rcases parameter with ⟨base, normal⟩
  unfold tubularLocalExtension canonicalLatitudeTubularDeckEquiv
  simp only [Equiv.coe_fn_mk, canonicalLatitudeTubularNormalNeg]
  exact canonicalLatitudeLocalCauchyExtension_deck
    period data.value data.normal data.value_periodic
      data.normal_antiperiodic (base, normal.1)

/-- Inverse-generator invariance on the tubular band. -/
theorem tubularLocalExtension_deck_inv
    (data : CanonicalLatitudeDeckCauchyData period)
    (parameter : CanonicalLatitudeTubularCollar) :
    data.tubularLocalExtension
        ((canonicalLatitudeTubularDeckEquiv period).symm parameter) =
      data.tubularLocalExtension parameter := by
  have hForward := data.tubularLocalExtension_deck
    ((canonicalLatitudeTubularDeckEquiv period).symm parameter)
  rw [(canonicalLatitudeTubularDeckEquiv period).apply_symm_apply] at hForward
  exact hForward.symm

/-- All-winding invariance on the tubular band. -/
theorem tubularLocalExtension_vadd
    (data : CanonicalLatitudeDeckCauchyData period)
    (winding : Int) (parameter : CanonicalLatitudeTubularCollar) :
    data.tubularLocalExtension (winding +ᵥ parameter) =
      data.tubularLocalExtension parameter := by
  change data.tubularLocalExtension
      ((canonicalLatitudeTubularDeckEquiv period ^ winding) parameter) = _
  induction winding using Int.induction_on with
  | zero =>
      simp
  | succ winding ih =>
      rw [zpow_add_one]
      change data.tubularLocalExtension
          ((canonicalLatitudeTubularDeckEquiv period ^ winding)
            (canonicalLatitudeTubularDeckEquiv period parameter)) = _
      rw [ih (canonicalLatitudeTubularDeckEquiv period parameter)]
      exact data.tubularLocalExtension_deck parameter
  | pred winding ih =>
      rw [zpow_sub_one]
      change data.tubularLocalExtension
          ((canonicalLatitudeTubularDeckEquiv period ^ (-(winding : Int)))
            ((canonicalLatitudeTubularDeckEquiv period).symm parameter)) = _
      rw [ih ((canonicalLatitudeTubularDeckEquiv period).symm parameter)]
      exact data.tubularLocalExtension_deck_inv parameter

/-- Descent to the genuine tubular collar quotient. -/
def tubularDescend
    (data : CanonicalLatitudeDeckCauchyData period) :
    CanonicalLatitudeTubularCollarQuotient period → Real :=
  Quotient.lift data.tubularLocalExtension
    (fun first second hOrbit => by
      change AddAction.orbitRel Int CanonicalLatitudeTubularCollar
        first second at hOrbit
      rw [AddAction.orbitRel_apply, AddAction.mem_orbit_iff] at hOrbit
      rcases hOrbit with ⟨winding, hWinding⟩
      rw [← hWinding]
      exact data.tubularLocalExtension_vadd winding second)

@[simp] theorem tubularDescend_mk
    (data : CanonicalLatitudeDeckCauchyData period)
    (parameter : CanonicalLatitudeTubularCollar) :
    data.tubularDescend
        (canonicalLatitudeTubularCollarMk period parameter) =
      data.tubularLocalExtension parameter :=
  rfl

end CanonicalLatitudeDeckCauchyData

/-- Physical tubular image. -/
def canonicalLatitudeTubularBulkSet : Set (EffectiveQuotient period hPeriod) :=
  Set.range (canonicalLatitudeTubularCollarToBulk period hPeriod)

/-- The tubular quotient is equivalent to its physical image. -/
def canonicalLatitudeTubularCollarEquivBulkSet :
    CanonicalLatitudeTubularCollarQuotient period ≃
      canonicalLatitudeTubularBulkSet period hPeriod :=
  Equiv.ofInjective (canonicalLatitudeTubularCollarToBulk period hPeriod)
    (canonicalLatitudeTubularCollarToBulk_injective period hPeriod)

/-- Physical image point represented by one tubular parameter. -/
def canonicalLatitudeTubularBulkPoint
    (parameter : CanonicalLatitudeTubularCollar) :
    canonicalLatitudeTubularBulkSet period hPeriod :=
  canonicalLatitudeTubularCollarEquivBulkSet period hPeriod
    (canonicalLatitudeTubularCollarMk period parameter)

@[simp] theorem canonicalLatitudeTubularBulkPoint_val
    (parameter : CanonicalLatitudeTubularCollar) :
    (canonicalLatitudeTubularBulkPoint period hPeriod parameter :
      EffectiveQuotient period hPeriod) =
      canonicalLatitudeTubularPhysicalMap period hPeriod parameter :=
  rfl

/-- Scalar field on the embedded physical tubular image. -/
def canonicalLatitudeTubularBulkField
    (data : CanonicalLatitudeDeckCauchyData period)
    (point : canonicalLatitudeTubularBulkSet period hPeriod) : Real :=
  data.tubularDescend
    ((canonicalLatitudeTubularCollarEquivBulkSet period hPeriod).symm point)

@[simp] theorem canonicalLatitudeTubularBulkField_point
    (data : CanonicalLatitudeDeckCauchyData period)
    (parameter : CanonicalLatitudeTubularCollar) :
    canonicalLatitudeTubularBulkField period hPeriod data
        (canonicalLatitudeTubularBulkPoint period hPeriod parameter) =
      data.tubularLocalExtension parameter := by
  unfold canonicalLatitudeTubularBulkField canonicalLatitudeTubularBulkPoint
  rw [(canonicalLatitudeTubularCollarEquivBulkSet
    period hPeriod).symm_apply_apply]
  rfl

/-- Global candidate: the descended tubular field on the tubular image and zero
elsewhere. -/
def canonicalLatitudeCauchyJetGlobalCandidate
    (data : CanonicalLatitudeDeckCauchyData period)
    (point : EffectiveQuotient period hPeriod) : Real :=
  if hPoint : point ∈ canonicalLatitudeTubularBulkSet period hPeriod then
    canonicalLatitudeTubularBulkField period hPeriod data ⟨point, hPoint⟩
  else 0

/-- On every tubular representative, the global candidate is the exact local
Cauchy expression. -/
theorem canonicalLatitudeCauchyJetGlobalCandidate_tubular
    (data : CanonicalLatitudeDeckCauchyData period)
    (parameter : CanonicalLatitudeTubularCollar) :
    canonicalLatitudeCauchyJetGlobalCandidate period hPeriod data
        (canonicalLatitudeTubularPhysicalMap period hPeriod parameter) =
      data.tubularLocalExtension parameter := by
  let quotientPoint := canonicalLatitudeTubularCollarMk period parameter
  have hMem : canonicalLatitudeTubularPhysicalMap period hPeriod parameter ∈
      canonicalLatitudeTubularBulkSet period hPeriod := by
    exact ⟨quotientPoint, rfl⟩
  unfold canonicalLatitudeCauchyJetGlobalCandidate
  rw [dif_pos hMem]
  have hPoint :
      (⟨canonicalLatitudeTubularPhysicalMap period hPeriod parameter, hMem⟩ :
        canonicalLatitudeTubularBulkSet period hPeriod) =
      canonicalLatitudeTubularBulkPoint period hPeriod parameter := by
    apply Subtype.ext
    rfl
  rw [hPoint, canonicalLatitudeTubularBulkField_point]

/-- In a neighborhood of the throat, every canonical normal slice of the global
candidate equals the exact local extension slice. -/
theorem canonicalLatitudeCauchyJetGlobalCandidate_slice_eventuallyEq
    (data : CanonicalLatitudeDeckCauchyData period)
    (base : CanonicalLatitudeBase) :
    (fun normal =>
      canonicalLatitudeCauchyJetGlobalCandidate period hPeriod data
        (quotientNormalLatitude period hPeriod
          (canonicalLatitudeAnchor period hPeriod base) normal)) =ᶠ[𝓝 0]
      canonicalLatitudeLocalCauchyExtensionSlice
        (data.value, data.normal) base := by
  have hZero : (0 : Real) ∈
      Set.Ioo (-(Real.pi / 2)) (Real.pi / 2) := by
    constructor <;> nlinarith [Real.pi_pos]
  filter_upwards [isOpen_Ioo.mem_nhds hZero] with normal hNormal
  let parameter : CanonicalLatitudeTubularCollar :=
    (base, ⟨normal, hNormal⟩)
  have hCandidate := canonicalLatitudeCauchyJetGlobalCandidate_tubular
    period hPeriod data parameter
  change canonicalLatitudeCauchyJetGlobalCandidate period hPeriod data
      (quotientNormalLatitude period hPeriod
        (canonicalLatitudeAnchor period hPeriod base) normal) =
    canonicalLatitudeLocalCauchyExtension (data.value, data.normal)
      (base, normal)
  exact hCandidate

/-- Exact value of the global candidate at the throat. -/
@[simp] theorem canonicalLatitudeCauchyJetGlobalCandidate_value
    (data : CanonicalLatitudeDeckCauchyData period)
    (base : CanonicalLatitudeBase) :
    canonicalLatitudeCauchyJetGlobalCandidate period hPeriod data
        (quotientNormalLatitude period hPeriod
          (canonicalLatitudeAnchor period hPeriod base) 0) =
      data.value base := by
  have hLocal := data |> canonicalLatitudeCauchyJetGlobalCandidate_slice_eventuallyEq
    period hPeriod base
  rw [hLocal.eq_of_nhds]
  exact canonicalLatitudeLocalCauchyExtensionSlice_zero
    (data.value, data.normal) base

/-- Exact normal derivative of the global candidate at the throat. -/
theorem canonicalLatitudeCauchyJetGlobalCandidate_normalDerivative
    (data : CanonicalLatitudeDeckCauchyData period)
    (base : CanonicalLatitudeBase) :
    deriv (fun normal =>
      canonicalLatitudeCauchyJetGlobalCandidate period hPeriod data
        (quotientNormalLatitude period hPeriod
          (canonicalLatitudeAnchor period hPeriod base) normal)) 0 =
      data.normal base := by
  have hLocal := canonicalLatitudeCauchyJetGlobalCandidate_slice_eventuallyEq
    period hPeriod data base
  have hDerivative : HasDerivAt
      (canonicalLatitudeLocalCauchyExtensionSlice
        (data.value, data.normal) base)
      (data.normal base) 0 :=
    canonicalLatitudeLocalCauchyExtensionSlice_hasDerivAt_zero
      (data.value, data.normal) base
  exact (hDerivative.congr_of_eventuallyEq hLocal).deriv

/-- Global candidate certificate. -/
theorem canonicalLatitudeCauchyJetGlobalCandidate_certificate
    (data : CanonicalLatitudeDeckCauchyData period) :
    (∀ base,
      canonicalLatitudeCauchyJetGlobalCandidate period hPeriod data
          (quotientNormalLatitude period hPeriod
            (canonicalLatitudeAnchor period hPeriod base) 0) =
        data.value base) ∧
      (∀ base,
        deriv (fun normal =>
          canonicalLatitudeCauchyJetGlobalCandidate period hPeriod data
            (quotientNormalLatitude period hPeriod
              (canonicalLatitudeAnchor period hPeriod base) normal)) 0 =
          data.normal base) :=
  ⟨canonicalLatitudeCauchyJetGlobalCandidate_value period hPeriod data,
    canonicalLatitudeCauchyJetGlobalCandidate_normalDerivative
      period hPeriod data⟩

end
end P0EFTJanusMappingTorusCanonicalPhysicalScalarCauchyJetGlobalCandidate4D
end JanusFormal
