import JanusFormal.Branches.FundamentalGeometryPVariationalPrinciple.Gates.P0EFTJanusProgramPGlobalCandidateAActualOrthogonalSchurBasis4D
import JanusFormal.Branches.FundamentalGeometryPVariationalPrinciple.Gates.P0EFTJanusProgramPGlobalCandidateAActualSchurDeterminant4D

/-!
# Candidate-A determinant on the orthogonal finite-mode Schur problem

A physical finite basis and invertibility of the canonical orthogonal-complement
block determine the finite Schur operator.  Its determinant is therefore a
canonical scalar attached to the displayed Candidate-A Hessian and the selected
reference modes.

Nonvanishing of that scalar proves that the complete augmented Hessian is
bijective and supplies the full-space Green operator.  No arbitrary four-block
packet or full-space decomposition is retained in the determinant interface.
-/

namespace JanusFormal
namespace P0EFTJanusProgramPGlobalCandidateAActualOrthogonalSchurDeterminant4D

set_option autoImplicit false
set_option maxHeartbeats 9400000
set_option synthInstance.maxHeartbeats 4700000

noncomputable section

open Set Topology MeasureTheory
open scoped Manifold ContDiff InnerProductSpace
open P0EFTJanusMappingTorusQuotient
open P0EFTJanusMappingTorusSmoothAtlasFrontier
open P0EFTJanusMappingTorusSmoothQuotientManifold
open P0EFTJanusProgramPGlobalFieldSpace4D
open P0EFTJanusProgramPGlobalTypedNonminimalFieldSpace4D
open P0EFTJanusProgramPGlobalCovariantAction4D
open P0EFTJanusProgramPGlobalAnalysisDomain4D
open P0EFTJanusProgramPGlobalLocalVariationalChart4D
open P0EFTJanusProgramPGlobalCandidateAMatterLLSameActionClosure4D
open P0EFTJanusProgramPGlobalCandidateACommonAugmentedAnalyticDomain4D
open P0EFTJanusProgramPGlobalCandidateAAugmentedActualKernelComplement4D
open P0EFTJanusProgramPGlobalCandidateAActualOrthogonalSchurBasis4D
open P0EFTJanusProgramPGlobalCandidateAActualSchurDeterminant4D
open P0EFTJanusProgramPGlobalCandidateAActualSchurNondegenerate4D
open P0EFTJanusProgramPFiniteModeSchurDeterminant4D

variable (period : Real) (hPeriod : period ≠ 0)

private abbrev EffectiveQuotient :=
  MappingTorus (reflectedSphereData period hPeriod)

local instance effectiveQuotientChartedSpace :
    ChartedSpace CoverModel (EffectiveQuotient period hPeriod) :=
  reflectedSphereQuotientChartedSpace period hPeriod

local instance effectiveQuotientIsManifold :
    IsManifold coverModelWithCorners ω (EffectiveQuotient period hPeriod) :=
  reflectedSphereQuotient_isManifold period hPeriod

local instance effectiveQuotientMeasurableSpace :
    MeasurableSpace (EffectiveQuotient period hPeriod) := borel _

local instance effectiveQuotientBorelSpace :
    BorelSpace (EffectiveQuotient period hPeriod) where
  measurable_eq := rfl

/-- Canonical finite Schur determinant generated by the orthogonal basis
packet. -/
def globalCandidateAOrthogonalSchurDeterminant
    {couplings : GlobalCandidateAActionCouplings}
    {NonNullFace NullFace : Type*}
    [Fintype NonNullFace] [Fintype NullFace]
    {measure : Measure (EffectiveQuotient period hPeriod)}
    {configuration : GlobalGaugeFixedFieldConfiguration period hPeriod}
    {data : GlobalCandidateAActionData period hPeriod configuration.physical
      couplings NonNullFace NullFace}
    {analysis : GlobalAnalysisData period hPeriod configuration.physical}
    {chart : GlobalCandidateALocalVariationalChart period hPeriod couplings
      NonNullFace NullFace measure}
    {sameAction : ProgramPGlobalMinimalPhysicalLocalMatterLLSameActionBridge4D
      period hPeriod configuration data analysis chart}
    {physical : GlobalCandidateASevenPhysicalCommonDomainExtension4D period
      hPeriod configuration data analysis chart sameAction}
    {Mode : Type*} [Fintype Mode] [DecidableEq Mode]
    (schur : GlobalCandidateAActualOrthogonalSchurBasisData4D period hPeriod
      configuration data analysis chart sameAction physical Mode) : Real :=
  (finiteModeSchurMatrix
    ((schur.toOrthogonalData period hPeriod).toBoundedSchurBlockData
      period hPeriod).blocks.toLinearBlockData).det

/-- Orthogonal basis Schur data on the nondegenerate stratum. -/
structure GlobalCandidateAActualOrthogonalSchurDeterminantData4D
    {couplings : GlobalCandidateAActionCouplings}
    {NonNullFace NullFace : Type*}
    [Fintype NonNullFace] [Fintype NullFace]
    {measure : Measure (EffectiveQuotient period hPeriod)}
    (configuration : GlobalGaugeFixedFieldConfiguration period hPeriod)
    (data : GlobalCandidateAActionData period hPeriod configuration.physical
      couplings NonNullFace NullFace)
    (analysis : GlobalAnalysisData period hPeriod configuration.physical)
    (chart : GlobalCandidateALocalVariationalChart period hPeriod couplings
      NonNullFace NullFace measure)
    (sameAction : ProgramPGlobalMinimalPhysicalLocalMatterLLSameActionBridge4D
      period hPeriod configuration data analysis chart)
    (physical : GlobalCandidateASevenPhysicalCommonDomainExtension4D period
      hPeriod configuration data analysis chart sameAction)
    (Mode : Type*) [Fintype Mode] [DecidableEq Mode] where
  schur : GlobalCandidateAActualOrthogonalSchurBasisData4D period hPeriod
    configuration data analysis chart sameAction physical Mode
  determinant_ne_zero :
    globalCandidateAOrthogonalSchurDeterminant period hPeriod schur ≠ 0

/-- Convert to the existing determinant packet. -/
def GlobalCandidateAActualOrthogonalSchurDeterminantData4D.toDeterminantData
    {couplings : GlobalCandidateAActionCouplings}
    {NonNullFace NullFace : Type*}
    [Fintype NonNullFace] [Fintype NullFace]
    {measure : Measure (EffectiveQuotient period hPeriod)}
    {configuration : GlobalGaugeFixedFieldConfiguration period hPeriod}
    {data : GlobalCandidateAActionData period hPeriod configuration.physical
      couplings NonNullFace NullFace}
    {analysis : GlobalAnalysisData period hPeriod configuration.physical}
    {chart : GlobalCandidateALocalVariationalChart period hPeriod couplings
      NonNullFace NullFace measure}
    {sameAction : ProgramPGlobalMinimalPhysicalLocalMatterLLSameActionBridge4D
      period hPeriod configuration data analysis chart}
    {physical : GlobalCandidateASevenPhysicalCommonDomainExtension4D period
      hPeriod configuration data analysis chart sameAction}
    {Mode : Type*} [Fintype Mode] [DecidableEq Mode]
    (determinant : GlobalCandidateAActualOrthogonalSchurDeterminantData4D period
      hPeriod configuration data analysis chart sameAction physical Mode) :
    GlobalCandidateAActualSchurDeterminantData4D period hPeriod configuration
      data analysis chart sameAction physical Mode
        determinant.schur.schur.basisData.modeSubspaceᗮ where
  blockData :=
    (determinant.schur.toOrthogonalData period hPeriod).toBoundedSchurBlockData
      period hPeriod
  determinant_ne_zero := determinant.determinant_ne_zero

/-- Full-space Green operator on the determinant-nondegenerate stratum. -/
noncomputable def globalCandidateAOrthogonalSchurFullGreen
    {couplings : GlobalCandidateAActionCouplings}
    {NonNullFace NullFace : Type*}
    [Fintype NonNullFace] [Fintype NullFace]
    {measure : Measure (EffectiveQuotient period hPeriod)}
    {configuration : GlobalGaugeFixedFieldConfiguration period hPeriod}
    {data : GlobalCandidateAActionData period hPeriod configuration.physical
      couplings NonNullFace NullFace}
    {analysis : GlobalAnalysisData period hPeriod configuration.physical}
    {chart : GlobalCandidateALocalVariationalChart period hPeriod couplings
      NonNullFace NullFace measure}
    {sameAction : ProgramPGlobalMinimalPhysicalLocalMatterLLSameActionBridge4D
      period hPeriod configuration data analysis chart}
    {physical : GlobalCandidateASevenPhysicalCommonDomainExtension4D period
      hPeriod configuration data analysis chart sameAction}
    {Mode : Type*} [Fintype Mode] [DecidableEq Mode]
    (determinant : GlobalCandidateAActualOrthogonalSchurDeterminantData4D period
      hPeriod configuration data analysis chart sameAction physical Mode) :=
  globalCandidateAActualFullGreen period hPeriod
    (determinant.toDeterminantData period hPeriod |>.toNondegenerateData
      period hPeriod)

/-- The finite determinant controls bijectivity of the complete Candidate-A
Hessian and yields two-sided full-space Green identities. -/
theorem global_candidateA_actual_orthogonal_schur_determinant_gate
    {couplings : GlobalCandidateAActionCouplings}
    {NonNullFace NullFace : Type*}
    [Fintype NonNullFace] [Fintype NullFace]
    {measure : Measure (EffectiveQuotient period hPeriod)}
    (configuration : GlobalGaugeFixedFieldConfiguration period hPeriod)
    (data : GlobalCandidateAActionData period hPeriod configuration.physical
      couplings NonNullFace NullFace)
    (analysis : GlobalAnalysisData period hPeriod configuration.physical)
    (chart : GlobalCandidateALocalVariationalChart period hPeriod couplings
      NonNullFace NullFace measure)
    (sameAction : ProgramPGlobalMinimalPhysicalLocalMatterLLSameActionBridge4D
      period hPeriod configuration data analysis chart)
    (physical : GlobalCandidateASevenPhysicalCommonDomainExtension4D period
      hPeriod configuration data analysis chart sameAction)
    (Mode : Type*) [Fintype Mode] [DecidableEq Mode]
    (determinant : GlobalCandidateAActualOrthogonalSchurDeterminantData4D period
      hPeriod configuration data analysis chart sameAction physical Mode) :=
  global_candidateA_actual_schur_determinant_gate period hPeriod configuration
    data analysis chart sameAction physical Mode
      determinant.schur.schur.basisData.modeSubspaceᗮ
      (determinant.toDeterminantData period hPeriod)

/-- Stored nonvanishing theorem for the public scalar. -/
theorem globalCandidateAOrthogonalSchurDeterminant_ne_zero
    {couplings : GlobalCandidateAActionCouplings}
    {NonNullFace NullFace : Type*}
    [Fintype NonNullFace] [Fintype NullFace]
    {measure : Measure (EffectiveQuotient period hPeriod)}
    {configuration : GlobalGaugeFixedFieldConfiguration period hPeriod}
    {data : GlobalCandidateAActionData period hPeriod configuration.physical
      couplings NonNullFace NullFace}
    {analysis : GlobalAnalysisData period hPeriod configuration.physical}
    {chart : GlobalCandidateALocalVariationalChart period hPeriod couplings
      NonNullFace NullFace measure}
    {sameAction : ProgramPGlobalMinimalPhysicalLocalMatterLLSameActionBridge4D
      period hPeriod configuration data analysis chart}
    {physical : GlobalCandidateASevenPhysicalCommonDomainExtension4D period
      hPeriod configuration data analysis chart sameAction}
    {Mode : Type*} [Fintype Mode] [DecidableEq Mode]
    (determinant : GlobalCandidateAActualOrthogonalSchurDeterminantData4D period
      hPeriod configuration data analysis chart sameAction physical Mode) :
    globalCandidateAOrthogonalSchurDeterminant period hPeriod
      determinant.schur ≠ 0 :=
  determinant.determinant_ne_zero

end
end P0EFTJanusProgramPGlobalCandidateAActualOrthogonalSchurDeterminant4D
end JanusFormal
