import JanusFormal.Branches.FundamentalGeometryPVariationalPrinciple.Gates.P0EFTJanusMappingTorusCanonicalPhysicalScalarIntrinsicWaveTangentialTimePrimitiveGreen4D
import JanusFormal.Branches.FundamentalGeometryPVariationalPrinciple.Gates.P0EFTJanusMappingTorusCanonicalPhysicalScalarProgramPFinalObligations4D

/-!
# Final Program P closure from a periodic tangential time primitive

This endpoint exposes the most local current Green input directly at the final
Program P level.  The time component of the tangential divergence is supplied as
the derivative of a primitive with matching period endpoints.  Its integral
vanishes automatically by FTC and Fubini.

The remaining fields are the sphere-divergence cancellation, one normal Green
density, the scalar energy identity, six canonical boundary `L²` operators, an
external positive shifted square and finite-coordinate Rellich approximation.
-/

namespace JanusFormal
namespace P0EFTJanusMappingTorusCanonicalPhysicalScalarIntrinsicWaveTangentialTimePrimitiveFinalClosure4D

set_option autoImplicit false
noncomputable section

open Set Topology MeasureTheory
open P0EFTJanusMappingTorusCanonicalPhysicalScalarFirstSheetHilbertTrace4D
open P0EFTJanusMappingTorusCanonicalPhysicalScalarIntrinsicWaveTangentialTimePrimitiveGreen4D
open P0EFTJanusMappingTorusCanonicalPhysicalScalarScalarRemainderEnergyIdentity4D
open P0EFTJanusMappingTorusCanonicalPhysicalScalarCauchyJetGeometricGreenCore4D
open P0EFTJanusMappingTorusCanonicalPhysicalScalarProgramPFinalObligations4D
open P0EFTJanusMappingTorusCanonicalPhysicalScalarFiniteCoordinateRellich4D
open P0EFTJanusMappingTorusScalarHilbertBoundarySymplectic4D
open P0EFTJanusMappingTorusScalarAbstractLagrangianBoundary4D
open P0EFTJanusMappingTorusScalarCompletedBoundaryTripleExternalPositiveShiftedForm4D

universe e

variable (period : Real) (hPeriod : period ≠ 0)
variable {massSquared : Real}
variable {Energy : Type e}
  [NormedAddCommGroup Energy] [NormedSpace Real Energy]

private abbrev BoundaryL2 := CanonicalPhysicalScalarFirstSheetL2 period

private abbrev BulkL2 :=
  P0EFTJanusMappingTorusCanonicalPhysicalBulkL2H1Bridge4D.CanonicalPhysicalBulkL2
    period hPeriod

/-- Final data with time cancellation generated by a periodic primitive. -/
structure CanonicalPhysicalScalarIntrinsicWaveTangentialTimePrimitiveFinalData
    (massSquared : Real) (Energy : Type e)
    [NormedAddCommGroup Energy] [NormedSpace Real Energy] where
  geometric : CanonicalPhysicalScalarIntrinsicWaveTangentialTimePrimitiveGreenData
    period hPeriod massSquared
  energyIdentity : geometric.greenCore.ScalarRemainderEnergyIdentityData
    period hPeriod
  eulerCoefficientOperators :
    geometric.toCanonicalNormalGreenData.toNormalTangentialGreenData.toIntrinsicWaveLocalGreenData.toCanonicalLocalDivergenceData.toCanonicalWaveCauchyJetData.toCanonicalCauchyJetCompatibilityData.toCompatibilityData.toCauchyJetGeometricData.CauchyJetEulerSixCanonicalL2OperatorData
      period hPeriod
  condition : CanonicalScalarHilbertLagrangianBoundaryCondition
    (BoundaryL2 period)
  referenceParameter : Real
  shiftedPositiveDecomposition :
    (assembleCanonicalPhysicalScalarBoundaryData period hPeriod
      geometric.toCanonicalNormalGreenData energyIdentity
        eulerCoefficientOperators).triple
      |>.LagrangianShiftedExternalPositiveDecompositionData
        condition referenceParameter Energy
  finiteCoordinateRellich : CanonicalPhysicalScalarFiniteCoordinateRellichData
    period hPeriod

namespace CanonicalPhysicalScalarIntrinsicWaveTangentialTimePrimitiveFinalData

/-- Conversion to the flattened final obligations package. -/
def toFinalObligationsData
    (data : CanonicalPhysicalScalarIntrinsicWaveTangentialTimePrimitiveFinalData
      period hPeriod massSquared Energy) :
    CanonicalPhysicalScalarProgramPFinalObligationsData
      period hPeriod massSquared Energy where
  geometric := data.geometric.toCanonicalNormalGreenData
  energyIdentity := data.energyIdentity
  eulerCoefficientOperators := data.eulerCoefficientOperators
  condition := data.condition
  referenceParameter := data.referenceParameter
  shiftedPositiveDecomposition := data.shiftedPositiveDecomposition
  finiteCoordinateRellich := data.finiteCoordinateRellich

/-- Completed Riesz trace. -/
def completedBoundaryTrace
    (data : CanonicalPhysicalScalarIntrinsicWaveTangentialTimePrimitiveFinalData
      period hPeriod massSquared Energy) :=
  data.toFinalObligationsData.completedBoundaryTrace

/-- Completed physical boundary triple. -/
def triple
    (data : CanonicalPhysicalScalarIntrinsicWaveTangentialTimePrimitiveFinalData
      period hPeriod massSquared Energy) :=
  data.toFinalObligationsData.triple

/-- Classical source solution. -/
noncomputable def sourceSolution
    (data : CanonicalPhysicalScalarIntrinsicWaveTangentialTimePrimitiveFinalData
      period hPeriod massSquared Energy) :=
  data.toFinalObligationsData.sourceSolution period hPeriod

/-- Actual Hilbert self-adjointness. -/
theorem actualAdjointDomain_eq
    (data : CanonicalPhysicalScalarIntrinsicWaveTangentialTimePrimitiveFinalData
      period hPeriod massSquared Energy) :
    data.triple.actualAdjointDomain data.condition =
      data.triple.realizationDomain data.condition :=
  data.toFinalObligationsData.actualAdjointDomain_eq period hPeriod

/-- Strong shifted source equation. -/
theorem sourceSolution_equation
    (data : CanonicalPhysicalScalarIntrinsicWaveTangentialTimePrimitiveFinalData
      period hPeriod massSquared Energy)
    (source : BulkL2 period hPeriod) :
    data.triple.lagrangianShiftedOperator
        data.condition data.referenceParameter
        (data.sourceSolution period hPeriod source) = source :=
  data.toFinalObligationsData.sourceSolution_equation
    period hPeriod source

/-- Unique global variational minimizer. -/
theorem sourceSolution_unique_minimizer
    (data : CanonicalPhysicalScalarIntrinsicWaveTangentialTimePrimitiveFinalData
      period hPeriod massSquared Energy)
    (source : BulkL2 period hPeriod) :
    (∀ field : data.triple.lagrangianDomainSubmodule data.condition,
      data.triple.lagrangianSourceAction
          data.condition data.referenceParameter source
          (data.sourceSolution period hPeriod source) ≤
        data.triple.lagrangianSourceAction
          data.condition data.referenceParameter source field) ∧
      (∀ field : data.triple.lagrangianDomainSubmodule data.condition,
        data.triple.lagrangianSourceAction
            data.condition data.referenceParameter source field =
          data.triple.lagrangianSourceAction
            data.condition data.referenceParameter source
            (data.sourceSolution period hPeriod source) →
        field = data.sourceSolution period hPeriod source) :=
  data.toFinalObligationsData.sourceSolution_unique_minimizer
    period hPeriod source

/-- Gaussian generating functional. -/
def gaussianGeneratingFunctional
    (data : CanonicalPhysicalScalarIntrinsicWaveTangentialTimePrimitiveFinalData
      period hPeriod massSquared Energy)
    (source : BulkL2 period hPeriod) : Real :=
  data.toFinalObligationsData.gaussianGeneratingFunctional
    period hPeriod source

/-- On-shell Gaussian identity and positivity. -/
theorem gaussian_certificate
    (data : CanonicalPhysicalScalarIntrinsicWaveTangentialTimePrimitiveFinalData
      period hPeriod massSquared Energy)
    (source : BulkL2 period hPeriod) :
    data.gaussianGeneratingFunctional period hPeriod source =
        -data.triple.lagrangianSourceAction
          data.condition data.referenceParameter source
          (data.sourceSolution period hPeriod source) ∧
      0 ≤ data.gaussianGeneratingFunctional period hPeriod source :=
  data.toFinalObligationsData.gaussian_certificate period hPeriod source

/-- Fredholm alternative. -/
theorem fredholmAlternative
    (data : CanonicalPhysicalScalarIntrinsicWaveTangentialTimePrimitiveFinalData
      period hPeriod massSquared Energy)
    (spectralParameter : Real)
    (hParameter : spectralParameter ≠ data.referenceParameter) :
    data.triple.LagrangianHasEigenvalue
        data.condition spectralParameter ∨
      data.triple.LagrangianResolventPoint
        data.condition spectralParameter :=
  data.toFinalObligationsData.fredholmAlternative
    period hPeriod spectralParameter hParameter

/-- Complete time-primitive final certificate. -/
theorem certificate
    (data : CanonicalPhysicalScalarIntrinsicWaveTangentialTimePrimitiveFinalData
      period hPeriod massSquared Energy)
    (source : BulkL2 period hPeriod) :
    (∀ field test normal sphere,
      (∫ time,
        data.geometric.timeDensity field test normal (sphere, time)
        ∂volume.restrict
          (P0EFTJanusMappingTorusCanonicalPhysicalH1TraceBound4D.canonicalLatitudeTimeInterval
            period)) = 0) ∧
      Function.Surjective data.completedBoundaryTrace ∧
      data.triple.actualAdjointDomain data.condition =
        data.triple.realizationDomain data.condition ∧
      data.triple.lagrangianShiftedOperator
          data.condition data.referenceParameter
          (data.sourceSolution period hPeriod source) = source ∧
      (∀ field : data.triple.lagrangianDomainSubmodule data.condition,
        data.triple.lagrangianSourceAction
            data.condition data.referenceParameter source
            (data.sourceSolution period hPeriod source) ≤
          data.triple.lagrangianSourceAction
            data.condition data.referenceParameter source field) ∧
      0 ≤ data.gaussianGeneratingFunctional period hPeriod source ∧
      (∀ spectralParameter : Real,
        spectralParameter ≠ data.referenceParameter →
          data.triple.LagrangianHasEigenvalue
              data.condition spectralParameter ∨
            data.triple.LagrangianResolventPoint
              data.condition spectralParameter) :=
  ⟨data.geometric.toTangentialTimePrimitiveData.time_integral_zero,
    (data.toFinalObligationsData.certificate period hPeriod source).2.2.1,
    data.actualAdjointDomain_eq period hPeriod,
    data.sourceSolution_equation period hPeriod source,
    (data.sourceSolution_unique_minimizer period hPeriod source).1,
    (data.gaussian_certificate period hPeriod source).2,
    data.fredholmAlternative period hPeriod⟩

end CanonicalPhysicalScalarIntrinsicWaveTangentialTimePrimitiveFinalData

/-- Marker for the periodic-time-primitive final endpoint. -/
theorem canonicalPhysicalScalarIntrinsicWaveTangentialTimePrimitiveFinalClosure_available : True :=
  trivial

end
end P0EFTJanusMappingTorusCanonicalPhysicalScalarIntrinsicWaveTangentialTimePrimitiveFinalClosure4D
end JanusFormal
