import JanusFormal.Branches.FundamentalGeometryPVariationalPrinciple.Gates.P0EFTJanusProgramPReferenceZetaTraceCoefficient4D
import JanusFormal.Branches.FundamentalGeometryPVariationalPrinciple.Gates.P0EFTJanusProgramPUnitaryRelativeZetaReferenceAtlasDerivation4D

/-!
# Unitary reference atlas from real finite-part trace identities

The unitary actual/reference atlas still accepted the standalone complex
identities

```text
T_reference = -trace_reference.
```

For each reference, those identities are generated by
`ReferenceZetaTraceCoefficientData`, whose inputs are only

* derivative of the finite-part logarithm equals the real logarithmic operator
  trace;
* the regularized zeta derivative at zero is real.

This file uses those real certificates to construct the complete reference
atlas derivation.
-/

namespace JanusFormal
namespace P0EFTJanusProgramPUnitaryRelativeZetaReferenceTraceAtlas4D

set_option autoImplicit false
noncomputable section

open P0EFTJanusProgramPReferenceZetaTraceCoefficient4D
open P0EFTJanusProgramPRelativeHeatMellinAnalyticDifferenceFamily4D
open P0EFTJanusProgramPRelativeHeatMellinZetaFamily4D
open P0EFTJanusProgramPRelativeZetaDeterminantConnection4D
open P0EFTJanusProgramPUnitaryActualZetaFamily4D
open P0EFTJanusProgramPUnitaryRelativeZetaReferenceAtlasDerivation4D

variable {Index E : Type*}
  [NormedAddCommGroup E] [InnerProductSpace Real E]

/-- Actual/reference atlas whose standalone reference coefficients are generated
from real finite-part trace identities. -/
structure UnitaryRelativeZetaReferenceTraceAtlasData
    (Index : Type*) (E : Type*)
    [NormedAddCommGroup E] [InnerProductSpace Real E] where
  actual : UnitaryActualZetaFamilyData (E := E)
  baseRelativeFamily : RelativeHeatMellinZetaFamilyData
  baseReferenceFamily : RelativeHeatMellinZetaFamilyData
  baseReferenceData : ReferenceZetaTraceCoefficientData baseReferenceFamily
  baseDifference : RelativeHeatMellinAnalyticDifferenceFamilyData
    baseRelativeFamily actual.family baseReferenceFamily
  localRelativeFamily : Index → RelativeHeatMellinZetaFamilyData
  localReferenceFamily : Index → RelativeHeatMellinZetaFamilyData
  localReferenceData : ∀ index,
    ReferenceZetaTraceCoefficientData (localReferenceFamily index)
  localDifference : ∀ index,
    RelativeHeatMellinAnalyticDifferenceFamilyData
      (localRelativeFamily index) actual.family (localReferenceFamily index)

namespace UnitaryRelativeZetaReferenceTraceAtlasData

/-- Convert real reference certificates into the complex-coefficient atlas
packet. -/
def toUnitaryAtlasDerivation
    (data : UnitaryRelativeZetaReferenceTraceAtlasData Index E) :
    UnitaryRelativeZetaReferenceAtlasDerivationData Index E where
  actual := data.actual
  baseRelativeFamily := data.baseRelativeFamily
  baseReferenceFamily := data.baseReferenceFamily
  baseReferenceTrace := data.baseReferenceData.logarithmicTrace
  baseDifference := data.baseDifference
  baseReferenceCoefficient :=
    data.baseReferenceData.connectionCoefficient_eq_neg_trace
  localRelativeFamily := data.localRelativeFamily
  localReferenceFamily := data.localReferenceFamily
  localReferenceTrace := fun index =>
    (data.localReferenceData index).logarithmicTrace
  localDifference := data.localDifference
  localReferenceCoefficient := fun index =>
    (data.localReferenceData index).connectionCoefficient_eq_neg_trace

/-- Base relative coefficient equals the generated base reference trace. -/
theorem baseCoefficient_eq_referenceTrace
    (data : UnitaryRelativeZetaReferenceTraceAtlasData Index E)
    (parameter : Real) :
    relativeZetaConnectionCoefficient data.baseRelativeFamily.toZetaFamily
        parameter = data.baseReferenceData.logarithmicTrace parameter :=
  data.toUnitaryAtlasDerivation.baseCoefficient_eq_referenceTrace parameter

/-- Every local relative coefficient equals its generated reference trace. -/
theorem localCoefficient_eq_referenceTrace
    (data : UnitaryRelativeZetaReferenceTraceAtlasData Index E)
    (index : Index) (parameter : Real) :
    relativeZetaConnectionCoefficient
        (data.localRelativeFamily index).toZetaFamily parameter =
      (data.localReferenceData index).logarithmicTrace parameter :=
  data.toUnitaryAtlasDerivation.localCoefficient_eq_referenceTrace index parameter

/-- The standalone base reference zeta derivative remains real. -/
theorem baseReference_parameterDerivative_im_zero
    (data : UnitaryRelativeZetaReferenceTraceAtlasData Index E)
    (parameter : Real) :
    (data.baseReferenceFamily.parameterDerivative parameter).im = 0 :=
  data.baseReferenceData.parameterDerivative_im_zero parameter

/-- Every standalone local reference zeta derivative remains real. -/
theorem localReference_parameterDerivative_im_zero
    (data : UnitaryRelativeZetaReferenceTraceAtlasData Index E)
    (index : Index) (parameter : Real) :
    ((data.localReferenceFamily index).parameterDerivative parameter).im = 0 :=
  (data.localReferenceData index).parameterDerivative_im_zero parameter

/-- Public real-input reference-atlas checkpoint. -/
theorem unitary_relative_zeta_reference_trace_atlas_gate
    (data : UnitaryRelativeZetaReferenceTraceAtlasData Index E) :
    (∀ parameter,
      relativeZetaConnectionCoefficient data.actual.family.toZetaFamily
          parameter = 0) ∧
    (∀ parameter,
      relativeZetaConnectionCoefficient data.baseRelativeFamily.toZetaFamily
          parameter = data.baseReferenceData.logarithmicTrace parameter) ∧
    (∀ index parameter,
      relativeZetaConnectionCoefficient
          (data.localRelativeFamily index).toZetaFamily parameter =
        (data.localReferenceData index).logarithmicTrace parameter) ∧
    (∀ parameter,
      (data.baseReferenceFamily.parameterDerivative parameter).im = 0) ∧
    (∀ index parameter,
      ((data.localReferenceFamily index).parameterDerivative parameter).im = 0) :=
  ⟨data.actual.connectionCoefficient_zero,
    data.baseCoefficient_eq_referenceTrace,
    data.localCoefficient_eq_referenceTrace,
    data.baseReference_parameterDerivative_im_zero,
    data.localReference_parameterDerivative_im_zero⟩

end UnitaryRelativeZetaReferenceTraceAtlasData

end
end P0EFTJanusProgramPUnitaryRelativeZetaReferenceTraceAtlas4D
end JanusFormal
