import JanusFormal.Branches.FundamentalGeometryPVariationalPrinciple.Gates.P0EFTJanusProgramPFiniteModeOrthogonalSchurBasis4D

/-!
# Orthogonal Schur reduction from named ambient reference vectors

A physical mode family is naturally specified by ambient vectors, not by a
subspace and a separate basis object.  Linear independence of the family makes
it a basis of its own span.  That span is finite-dimensional, hence closed, and
Hilbert projection supplies its canonical orthogonal complement.

The only remaining infinite-dimensional statement is invertibility of the
canonical complementary Hessian block.
-/

namespace JanusFormal
namespace P0EFTJanusProgramPFiniteModeOrthogonalSchurNamedVectors4D

set_option autoImplicit false
noncomputable section

open Set Submodule
open P0EFTJanusProgramPFiniteModeOrthogonalSchurDecomposition4D
open P0EFTJanusProgramPFiniteModeOrthogonalSchurBasis4D
open P0EFTJanusProgramPFiniteModeCanonicalSchurDecomposition4D
open P0EFTJanusProgramPFiniteModeContinuousSchurBlock4D

variable {E Mode : Type*}
  [NormedAddCommGroup E] [InnerProductSpace Real E] [CompleteSpace E]
  [Fintype Mode] [DecidableEq Mode]

/-- Subspace generated by the selected ambient reference modes. -/
def finiteModeNamedSubspace (vector : Mode → E) : Submodule Real E :=
  span Real (Set.range vector)

/-- Continuous finite coordinates generated by the named vectors. -/
noncomputable def finiteModeNamedContinuousEquiv
    (vector : Mode → E)
    (linearIndependent : LinearIndependent Real vector) :
    (Mode → Real) ≃L[Real] finiteModeNamedSubspace vector :=
  finiteModeContinuousEquivOfBasis (finiteModeNamedSubspace vector)
    (Module.Basis.span linearIndependent)

/-- Named ambient-vector Schur packet. -/
structure FiniteModeOrthogonalSchurNamedVectorsData
    (operator : E →L[Real] E) where
  vector : Mode → E
  linearIndependent : LinearIndependent Real vector
  complementEquiv :
    (finiteModeNamedSubspace vector)ᗮ ≃L[Real]
      (finiteModeNamedSubspace vector)ᗮ
  complementEquiv_eq :
    complementEquiv.toContinuousLinearMap =
      finiteModeCanonicalBlockD operator
        (finiteModeOrthogonalDecomposition
          (finiteModeNamedSubspace vector)
          (finiteModeNamedContinuousEquiv vector linearIndependent))

/-- The named vectors form the canonical basis of their span. -/
noncomputable def FiniteModeOrthogonalSchurNamedVectorsData.basis
    {operator : E →L[Real] E}
    (data : FiniteModeOrthogonalSchurNamedVectorsData
      (Mode := Mode) operator) :
    Module.Basis Mode Real (finiteModeNamedSubspace data.vector) :=
  Module.Basis.span data.linearIndependent

/-- The span basis evaluates to the original ambient vector. -/
@[simp]
theorem FiniteModeOrthogonalSchurNamedVectorsData.basis_coe
    {operator : E →L[Real] E}
    (data : FiniteModeOrthogonalSchurNamedVectorsData
      (Mode := Mode) operator)
    (mode : Mode) :
    ((data.basis mode : finiteModeNamedSubspace data.vector) : E) =
      data.vector mode :=
  Module.Basis.coe_span_apply data.linearIndependent mode

/-- Convert named vectors to the finite-basis orthogonal Schur packet. -/
def FiniteModeOrthogonalSchurNamedVectorsData.toBasisData
    {operator : E →L[Real] E}
    (data : FiniteModeOrthogonalSchurNamedVectorsData
      (Mode := Mode) operator) :
    FiniteModeOrthogonalSchurBasisData (Mode := Mode) operator where
  modeSubspace := finiteModeNamedSubspace data.vector
  basis := data.basis
  complementEquiv := data.complementEquiv
  complementEquiv_eq := data.complementEquiv_eq

/-- The basis packet recovers the original physical vector family exactly. -/
theorem FiniteModeOrthogonalSchurNamedVectorsData.toBasisData_modeVector
    {operator : E →L[Real] E}
    (data : FiniteModeOrthogonalSchurNamedVectorsData
      (Mode := Mode) operator) :
    data.toBasisData.modeVector = data.vector := by
  funext mode
  exact data.basis_coe mode

/-- Complete bounded Schur packet generated from named ambient vectors. -/
def FiniteModeOrthogonalSchurNamedVectorsData.toContinuousSchurBlockData
    {operator : E →L[Real] E}
    (data : FiniteModeOrthogonalSchurNamedVectorsData
      (Mode := Mode) operator) :
    FiniteModeContinuousSchurBlockData operator Mode
      (finiteModeNamedSubspace data.vector)ᗮ :=
  data.toBasisData.toContinuousSchurBlockData

/-- Public checkpoint from named ambient reference modes. -/
theorem finite_mode_orthogonal_schur_named_vectors_gate
    (operator : E →L[Real] E)
    (data : FiniteModeOrthogonalSchurNamedVectorsData
      (Mode := Mode) operator) :
    LinearIndependent Real data.vector ∧
      Nonempty
        (FiniteModeContinuousSchurBlockData operator Mode
          (finiteModeNamedSubspace data.vector)ᗮ) :=
  ⟨data.linearIndependent, ⟨data.toContinuousSchurBlockData⟩⟩

end
end P0EFTJanusProgramPFiniteModeOrthogonalSchurNamedVectors4D
end JanusFormal
