import JanusFormal.Branches.FundamentalGeometryPVariationalPrinciple.Gates.P0EFTJanusProgramPIntrinsicBismutFreedReferenceAtlas4D
import JanusFormal.Branches.FundamentalGeometryPVariationalPrinciple.Gates.P0EFTJanusProgramPRelativeBismutFreedCircleTraceBridge4D

/-!
# Intrinsic reference atlases anchored to the circle Quillen family

A multi-reference determinant atlas and a circle Quillen bridge should not be
two unrelated objects.  This file chooses one reference chart as the circle
chart and identifies its Mellin family and intrinsic logarithmic trace with the
operator-defined circle bridge.

The resulting certificate combines:

* an atlas generated by actual/reference Mellin families;
* transition derivatives computed by intrinsic reference-change traces;
* the Cech cocycle and connection gauge law;
* a circle-parallel base determinant;
* endpoint clutching and unitary phase holonomy.
-/

namespace JanusFormal
namespace P0EFTJanusProgramPIntrinsicBismutFreedReferenceQuillenAtlas4D

set_option autoImplicit false
set_option maxHeartbeats 5200000
set_option synthInstance.maxHeartbeats 2600000

noncomputable section

open P0EFTJanusCircleDiracHeatTraceCancellation
open P0EFTJanusCircleDeterminantTopologicalBundle
open P0EFTJanusCircleQuillenMetricFlatConnection
open P0EFTJanusProgramPIntrinsicBismutFreedReferenceAtlas4D
open P0EFTJanusProgramPRelativeBismutFreedCircleTraceBridge4D
open P0EFTJanusProgramPRelativeHeatMellinZetaFamily4D
open P0EFTJanusProgramPRelativeZetaDeterminantConnection4D
open P0EFTJanusProgramPRelativeZetaDeterminantCocycle4D
open P0EFTJanusProgramPRelativeZetaDeterminantLineAtlas4D
open P0EFTJanusProgramPRelativeZetaFinitePartFamily4D

universe u v w

variable {E : Type u} {Index : Type w}
  [NormedAddCommGroup E] [InnerProductSpace Real E] [CompleteSpace E]

/-- Operator-generated reference atlas with one selected circle chart. -/
structure IntrinsicBismutFreedReferenceQuillenAtlasData
    (actual : Real → E →L[Real] E)
    (reference : Index → Real → E →L[Real] E)
    (fold : Fold) where
  referenceAtlas :
    IntrinsicBismutFreedReferenceAtlasData.{u, v, w} actual reference
  baseIndex : Index
  circleBridge : RelativeBismutFreedCircleTraceBridgeData.{u, v}
    actual (reference baseIndex) fold
  baseFamily_eq : referenceAtlas.family baseIndex =
    circleBridge.bismutFreed.zetaFamily
  baseTrace_eq : ∀ parameter,
    referenceAtlas.operatorCocycle.localTrace baseIndex parameter =
      circleBridge.bismutFreed.operatorTrace.trace parameter

namespace IntrinsicBismutFreedReferenceQuillenAtlasData

/-- Base local determinant is exactly the determinant coordinate of the circle
Bismut--Freed family. -/
theorem baseDeterminant_eq_circle
    {actual : Real → E →L[Real] E}
    {reference : Index → Real → E →L[Real] E}
    {fold : Fold}
    (data : IntrinsicBismutFreedReferenceQuillenAtlasData.{u, v, w}
      actual reference fold)
    (parameter : Real) :
    data.referenceAtlas.localDeterminant data.baseIndex parameter =
      relativeHeatMellinZetaFamilyDeterminant
        data.circleBridge.bismutFreed.zetaFamily parameter := by
  unfold IntrinsicBismutFreedReferenceAtlasData.localDeterminant
  rw [data.baseFamily_eq]

/-- Base local zeta coefficient is the intrinsic circle coefficient. -/
theorem baseCoefficient_eq_circle
    {actual : Real → E →L[Real] E}
    {reference : Index → Real → E →L[Real] E}
    {fold : Fold}
    (data : IntrinsicBismutFreedReferenceQuillenAtlasData.{u, v, w}
      actual reference fold)
    (parameter : Real) :
    relativeZetaConnectionCoefficient
        (data.referenceAtlas.family data.baseIndex).toZetaFamily parameter =
      (circleQuillenConnectionCoefficient fold : Complex) := by
  calc
    relativeZetaConnectionCoefficient
        (data.referenceAtlas.family data.baseIndex).toZetaFamily parameter =
      data.referenceAtlas.operatorCocycle.localCoefficient data.baseIndex
        parameter :=
      data.referenceAtlas.coefficient_agreement data.baseIndex parameter
    _ = data.circleBridge.bismutFreed.operatorTrace.bismutFreedCoefficient
        parameter := by
      unfold P0EFTJanusProgramPIntrinsicRelativeTraceReferenceCocycle4D.IntrinsicRelativeTraceReferenceCocycleData.localCoefficient
        P0EFTJanusProgramPIntrinsicLogarithmicDerivativeTrace4D.RelativeIntrinsicLogarithmicDerivativeTraceData.bismutFreedCoefficient
      rw [data.baseTrace_eq parameter]
    _ = (circleQuillenConnectionCoefficient fold : Complex) :=
      data.circleBridge.coefficient_eq_circle parameter

/-- The base determinant is parallel for the circle connection. -/
theorem base_circle_parallel
    {actual : Real → E →L[Real] E}
    {reference : Index → Real → E →L[Real] E}
    {fold : Fold}
    (data : IntrinsicBismutFreedReferenceQuillenAtlasData.{u, v, w}
      actual reference fold)
    (parameter : Real) :
    circleQuillenConnectionAt fold
        (data.referenceAtlas.localDeterminant data.baseIndex parameter)
        (relativeZetaDeterminantCoordinateDerivative
          (data.referenceAtlas.family data.baseIndex).toZetaFamily parameter) = 0 := by
  rw [data.baseDeterminant_eq_circle parameter]
  rw [data.baseFamily_eq]
  exact data.circleBridge.circle_parallel parameter

/-- Generated determinant-line atlas certificate. -/
def atlasCertificate
    {actual : Real → E →L[Real] E}
    {reference : Index → Real → E →L[Real] E}
    {fold : Fold}
    (data : IntrinsicBismutFreedReferenceQuillenAtlasData.{u, v, w}
      actual reference fold) :
    RelativeZetaDeterminantLineAtlasCertificate
      data.referenceAtlas.zetaAtlas :=
  data.referenceAtlas.determinantLineAtlasCertificate

/-- Transition logarithmic derivative in intrinsic reference-trace form. -/
theorem transitionDerivative_eq_referenceTrace
    {actual : Real → E →L[Real] E}
    {reference : Index → Real → E →L[Real] E}
    {fold : Fold}
    (data : IntrinsicBismutFreedReferenceQuillenAtlasData.{u, v, w}
      actual reference fold)
    (first second : Index) (parameter : Real) :
    relativeZetaTransitionDerivative data.referenceAtlas.zetaAtlas first second
        parameter =
      (data.referenceAtlas.operatorCocycle.referenceChangeTrace first second
          parameter : Complex) *
        data.referenceAtlas.transition first second parameter :=
  data.referenceAtlas.transitionDerivative_eq_referenceChangeTrace first second
    parameter

/-- Circle endpoint clutching in the selected atlas chart. -/
theorem base_endpoint_clutching
    {actual : Real → E →L[Real] E}
    {reference : Index → Real → E →L[Real] E}
    {fold : Fold}
    (data : IntrinsicBismutFreedReferenceQuillenAtlasData.{u, v, w}
      actual reference fold) :
    circleLargeGaugeFrameCoordinateTransition fold
        (data.referenceAtlas.localDeterminant data.baseIndex 1) =
      data.referenceAtlas.localDeterminant data.baseIndex 0 := by
  rw [data.baseDeterminant_eq_circle 1,
    data.baseDeterminant_eq_circle 0]
  exact data.circleBridge.endpoint_clutching

/-- Closed Quillen holonomy equals the endpoint ratio of the normalized base
zeta phase. -/
theorem closedHolonomy_eq_basePhaseRatio
    {actual : Real → E →L[Real] E}
    {reference : Index → Real → E →L[Real] E}
    {fold : Fold}
    (data : IntrinsicBismutFreedReferenceQuillenAtlasData.{u, v, w}
      actual reference fold) :
    circleQuillenClosedHolonomy fold =
      relativeZetaFinitePartPhase
          data.circleBridge.bismutFreed.zetaFamily.toFinitePartComparison 0 /
        relativeZetaFinitePartPhase
          data.circleBridge.bismutFreed.zetaFamily.toFinitePartComparison 1 :=
  data.circleBridge.closedHolonomy_eq_phase_ratio

/-- Public intrinsic reference/Quillen atlas checkpoint. -/
theorem intrinsic_bismut_freed_reference_quillen_atlas_gate
    (actual : Real → E →L[Real] E)
    (reference : Index → Real → E →L[Real] E)
    (fold : Fold)
    (data : IntrinsicBismutFreedReferenceQuillenAtlasData.{u, v, w}
      actual reference fold) :
    RelativeZetaDeterminantLineAtlasCertificate
        data.referenceAtlas.zetaAtlas ∧
      (∀ first second parameter,
        relativeZetaTransitionDerivative data.referenceAtlas.zetaAtlas first
            second parameter =
          (data.referenceAtlas.operatorCocycle.referenceChangeTrace first second
              parameter : Complex) *
            data.referenceAtlas.transition first second parameter) ∧
      (∀ parameter,
        circleQuillenConnectionAt fold
            (data.referenceAtlas.localDeterminant data.baseIndex parameter)
            (relativeZetaDeterminantCoordinateDerivative
              (data.referenceAtlas.family data.baseIndex).toZetaFamily
                parameter) = 0) ∧
      circleLargeGaugeFrameCoordinateTransition fold
          (data.referenceAtlas.localDeterminant data.baseIndex 1) =
        data.referenceAtlas.localDeterminant data.baseIndex 0 ∧
      circleQuillenClosedHolonomy fold =
        relativeZetaFinitePartPhase
            data.circleBridge.bismutFreed.zetaFamily.toFinitePartComparison 0 /
          relativeZetaFinitePartPhase
            data.circleBridge.bismutFreed.zetaFamily.toFinitePartComparison 1 :=
  ⟨data.atlasCertificate,
    data.transitionDerivative_eq_referenceTrace,
    data.base_circle_parallel,
    data.base_endpoint_clutching,
    data.closedHolonomy_eq_basePhaseRatio⟩

end IntrinsicBismutFreedReferenceQuillenAtlasData

end
end P0EFTJanusProgramPIntrinsicBismutFreedReferenceQuillenAtlas4D
end JanusFormal
