import JanusFormal.Branches.FundamentalGeometryPVariationalPrinciple.Gates.P0EFTJanusProgramPProductThroatReferenceNuclearDuhamelFullyCountableTerminalBoundaryFrontend4D

/-!
# Locally uniform product-throat terminal boundary

Termwise continuity and one summable uniform majorant generate continuity of
the complete countable long-time operator integrand.
-/

namespace JanusFormal
namespace P0EFTJanusProgramPProductThroatReferenceNuclearDuhamelLocallyUniformFullyCountableTerminalBoundary4D

set_option autoImplicit false
noncomputable section

open MeasureTheory Set
open P0EFTJanusGlobalSeparatedDiracModel
open P0EFTJanusCircleDiracHeatTraceCancellation
open P0EFTJanusProgramPCountableRankOneNuclearTraceBochnerBridge4D
open P0EFTJanusProgramPFiniteHeatCountertermFinitePartVariation4D
open P0EFTJanusProgramPIntrinsicNuclearTrace4D
open P0EFTJanusProgramPNuclearHeatDuhamelCountertermSubtractedShortTimeQuadratic4D
open P0EFTJanusProgramPNuclearHeatDuhamelTraceVariation4D
open P0EFTJanusProgramPProductThroatNuclearDuhamelCountableRankOneBochnerOperatorIntegral4D
open P0EFTJanusProgramPProductThroatReferenceNuclearDuhamelFullyCountableTerminalBoundaryFrontend4D
open P0EFTJanusProgramPReferenceNuclearDuhamelFullyCountableTerminalBoundaryFrontend4D
open P0EFTJanusProgramPRenormalizedNuclearDuhamelCountableRankOneBochnerFrontend4D

universe u v

variable {E : Type u}
  [NormedAddCommGroup E] [InnerProductSpace Real E] [CompleteSpace E]

/-- A countable rank-one series is continuous on a region when every summand
is continuous there and one summable sequence dominates all operator norms. -/
theorem countableRankOne_integrand_continuousOn_of_uniform
    {bridgeRegion timeRegion : Set Real}
    {integrand : Real → E →L[Real] E}
    {pointwiseTraceClass : ∀ time,
      IntrinsicNuclearTraceData.{u, v} (integrand time)}
    (bridge : CountableRankOneNuclearTraceBochnerBridgeData
      bridgeRegion integrand pointwiseTraceClass)
    (majorant : bridge.Index → Real)
    (majorant_summable : Summable majorant)
    (summand_continuousOn : ∀ index,
      ContinuousOn (bridge.operatorSummand index) timeRegion)
    (summand_norm_le : ∀ index time, time ∈ timeRegion →
      ‖bridge.operatorSummand index time‖ ≤ majorant index) :
    ContinuousOn integrand timeRegion := by
  have hSeries : ContinuousOn
      (fun time => ∑' index, bridge.operatorSummand index time)
      timeRegion := by
    exact continuousOn_tsum summand_continuousOn majorant_summable
      summand_norm_le
  exact hSeries.congr fun time _ => bridge.integrand_eq_tsum time

/-- Product-throat operator boundary whose long-time continuity is expressed
by termwise locally uniform data instead of assumed for the full series. -/
structure ProductThroatReferenceNuclearDuhamelLocallyUniformFullyCountableTerminalBoundaryData
    (Index : Type*)
    (productData : ProductThroatSpectralData)
    (fold : Fold) (twist : CircleTwist)
    (nuclear : NuclearHeatDuhamelTraceVariationData.{u, v} (E := E))
    (finiteCounterterm : FiniteHeatCountertermFinitePartVariationData Index)
    (shortTime : NuclearHeatDuhamelCountertermSubtractedShortTimeQuadraticData
      nuclear 1) where
  shortFrontend :
    RenormalizedNuclearDuhamelCountableRankOneBochnerFrontendData
      nuclear shortTime
  longTime :
    ProductThroatNuclearDuhamelCountableRankOneBochnerOperatorIntegralData
      productData fold twist nuclear 1
  longMajorant : ∀ parameter,
    (longTime.rankOne parameter).Index → Real
  longMajorant_summable : ∀ parameter,
    Summable (longMajorant parameter)
  longSummand_continuousOn : ∀ parameter index,
    ContinuousOn
      ((longTime.rankOne parameter).operatorSummand index)
      (Set.Ici (1 : Real))
  longSummand_norm_le : ∀ parameter index time,
    time ∈ Set.Ici (1 : Real) →
      ‖(longTime.rankOne parameter).operatorSummand index time‖ ≤
        longMajorant parameter index
  finitePartOperator : Real → E →L[Real] E
  finitePartTraceClass : ∀ parameter,
    IntrinsicNuclearTraceData.{u, v} (finitePartOperator parameter)
  finitePartDerivative_eq_trace : ∀ parameter,
    finitePartDerivative finiteCounterterm parameter =
      intrinsicNuclearTrace (finitePartTraceClass parameter)
  logarithmicDerivativeOperator : Real → E →L[Real] E
  shortBoundaryIdentity : ∀ parameter,
    (shortFrontend.toRenormalizedOperatorIntegral.integratedOperator parameter -
        finitePartOperator parameter) +
      longTime.toCountableRankOneBochnerOperatorIntegral.integratedOperator
        parameter =
      logarithmicDerivativeOperator parameter

namespace ProductThroatReferenceNuclearDuhamelLocallyUniformFullyCountableTerminalBoundaryData

/-- Continuity of the full long-time integrand is generated by the uniform
rank-one series theorem. -/
theorem longIntegrand_continuousOn
    {Index : Type*}
    {productData : ProductThroatSpectralData}
    {fold : Fold} {twist : CircleTwist}
    {nuclear : NuclearHeatDuhamelTraceVariationData.{u, v} (E := E)}
    {finiteCounterterm : FiniteHeatCountertermFinitePartVariationData Index}
    {shortTime : NuclearHeatDuhamelCountertermSubtractedShortTimeQuadraticData
      nuclear 1}
    (data :
      ProductThroatReferenceNuclearDuhamelLocallyUniformFullyCountableTerminalBoundaryData
        Index productData fold twist nuclear finiteCounterterm shortTime)
    (parameter : Real) :
    ContinuousOn (data.longTime.operatorIntegrand parameter)
      (Set.Ici (1 : Real)) :=
  countableRankOne_integrand_continuousOn_of_uniform
    (data.longTime.rankOne parameter)
    (data.longMajorant parameter) (data.longMajorant_summable parameter)
    (data.longSummand_continuousOn parameter)
    (data.longSummand_norm_le parameter)

/-- Adapter to the complete product-throat terminal boundary. -/
def toFullyCountableTerminalBoundary
    {Index : Type*}
    {productData : ProductThroatSpectralData}
    {fold : Fold} {twist : CircleTwist}
    {nuclear : NuclearHeatDuhamelTraceVariationData.{u, v} (E := E)}
    {finiteCounterterm : FiniteHeatCountertermFinitePartVariationData Index}
    {shortTime : NuclearHeatDuhamelCountertermSubtractedShortTimeQuadraticData
      nuclear 1}
    (data :
      ProductThroatReferenceNuclearDuhamelLocallyUniformFullyCountableTerminalBoundaryData
        Index productData fold twist nuclear finiteCounterterm shortTime) :
    ProductThroatReferenceNuclearDuhamelFullyCountableTerminalBoundaryFrontendData
      Index productData fold twist nuclear finiteCounterterm shortTime where
  shortFrontend := data.shortFrontend
  longTime := data.longTime
  longIntegrand_continuousOn := data.longIntegrand_continuousOn
  finitePartOperator := data.finitePartOperator
  finitePartTraceClass := data.finitePartTraceClass
  finitePartDerivative_eq_trace := data.finitePartDerivative_eq_trace
  logarithmicDerivativeOperator := data.logarithmicDerivativeOperator
  shortBoundaryIdentity := data.shortBoundaryIdentity

/-- Public locally-uniform checkpoint. -/
theorem product_throat_reference_nuclear_duhamel_locally_uniform_terminal_boundary_gate
    {Index : Type*}
    {productData : ProductThroatSpectralData}
    {fold : Fold} {twist : CircleTwist}
    {nuclear : NuclearHeatDuhamelTraceVariationData.{u, v} (E := E)}
    {finiteCounterterm : FiniteHeatCountertermFinitePartVariationData Index}
    {shortTime : NuclearHeatDuhamelCountertermSubtractedShortTimeQuadraticData
      nuclear 1}
    (data :
      ProductThroatReferenceNuclearDuhamelLocallyUniformFullyCountableTerminalBoundaryData
        Index productData fold twist nuclear finiteCounterterm shortTime) :
    (∀ parameter,
      ContinuousOn (data.longTime.operatorIntegrand parameter)
        (Set.Ici (1 : Real))) ∧
    (∀ parameter,
      (data.toFullyCountableTerminalBoundary.toFullyCountableTerminalBoundaryFrontend.terminalTail
          parameter).matchingOperator =
        data.longTime.toCountableRankOneBochnerOperatorIntegral.integratedOperator
          parameter) :=
  ⟨data.longIntegrand_continuousOn,
    data.toFullyCountableTerminalBoundary.toFullyCountableTerminalBoundaryFrontend.terminalIntegral_eq_longOperator⟩

end ProductThroatReferenceNuclearDuhamelLocallyUniformFullyCountableTerminalBoundaryData

end
end P0EFTJanusProgramPProductThroatReferenceNuclearDuhamelLocallyUniformFullyCountableTerminalBoundary4D
end JanusFormal
