import JanusFormal.Branches.FundamentalGeometryPVariationalPrinciple.Gates.P0EFTJanusMappingTorusCanonicalPhysicalScalarCauchyJetCompatibilityBridge4D
import JanusFormal.Branches.FundamentalGeometryPVariationalPrinciple.Gates.P0EFTJanusMappingTorusCanonicalPhysicalScalarCauchyJetProfileL2Bound4D
import JanusFormal.Branches.FundamentalGeometryPVariationalPrinciple.Gates.P0EFTJanusMappingTorusCanonicalPhysicalScalarCauchyJetEulerL2Reduction4D
import JanusFormal.Branches.FundamentalGeometryPVariationalPrinciple.Gates.P0EFTJanusMappingTorusCanonicalPhysicalScalarEnergyGarding4D
import JanusFormal.Branches.FundamentalGeometryPVariationalPrinciple.Gates.P0EFTJanusMappingTorusCanonicalPhysicalScalarNormalEllipticRegularity4D
import JanusFormal.Branches.FundamentalGeometryPVariationalPrinciple.Gates.P0EFTJanusMappingTorusCanonicalPhysicalScalarCutoffClosedBoundaryTriple4D

/-!
# Explicit Cauchy-jet PDE closure

The physical boundary triple is now assembled from the standard local and global
PDE statements:

* Euler residual compatibility on the total holonomic atlas;
* the global Euler-skew/divergence integral identity;
* the canonical smooth value and normal cores and tubular inverse;
* a Gårding energy estimate;
* higher elliptic regularity with bounded normal trace;
* integrability of the two fixed Cauchy profiles;
* realization and product estimate of the Euler residual of the explicit jet.

The profile moments give the bulk `L²` component of the extension graph norm.
The local Euler product estimate gives its operator component.  Their maximum
provides the bounded right inverse of the completed Cauchy trace.  Coarea and the
already constructed shrinking cutoffs provide the value trace and minimal-core
density.  Hence these PDE inputs install the genuine completed physical boundary
triple.
-/

namespace JanusFormal
namespace P0EFTJanusMappingTorusCanonicalPhysicalScalarCauchyJetPDEClosure4D

set_option autoImplicit false
noncomputable section

open Set Topology
open P0EFTJanusMappingTorusCanonicalPhysicalScalarCauchyJetCompatibilityGreenCore4D
open P0EFTJanusMappingTorusCanonicalPhysicalScalarCauchyJetCompatibilityBridge4D
open P0EFTJanusMappingTorusCanonicalPhysicalScalarCauchyJetGeometricGreenCore4D
open P0EFTJanusMappingTorusCanonicalPhysicalScalarCauchyJetGraphBound4D
open P0EFTJanusMappingTorusCanonicalPhysicalScalarCauchyJetSquaredGraphBound4D
open P0EFTJanusMappingTorusCanonicalPhysicalScalarCauchyJetBulkL2Reduction4D
open P0EFTJanusMappingTorusCanonicalPhysicalScalarCauchyJetProfileL2Bound4D
open P0EFTJanusMappingTorusCanonicalPhysicalScalarCauchyJetEulerL2Reduction4D
open P0EFTJanusMappingTorusCanonicalPhysicalScalarEnergyGarding4D
open P0EFTJanusMappingTorusCanonicalPhysicalScalarNormalEllipticRegularity4D
open P0EFTJanusMappingTorusCanonicalPhysicalScalarCutoffClosedBoundaryTriple4D
open P0EFTJanusMappingTorusScalarHilbertGreenCoreCompletion4D

universe x y r

variable (period : Real) (hPeriod : period ≠ 0)
variable {Regularity : Type r}
  [NormedAddCommGroup Regularity] [NormedSpace Real Regularity]
  [CompleteSpace Regularity]

/-- Complete explicit-Cauchy PDE input. -/
structure CanonicalPhysicalScalarCauchyJetPDEData
    (massSquared : Real)
    (ValueCore : Type x) (NormalCore : Type y)
    [AddCommGroup ValueCore] [Module Real ValueCore]
    [AddCommGroup NormalCore] [Module Real NormalCore] where
  geometric : CanonicalPhysicalScalarCauchyJetCompatibilityData
    period hPeriod massSquared ValueCore NormalCore
  gardingEnergy : geometric.greenCore.EnergyGardingData period hPeriod
  normalRegularity : geometric.greenCore.NormalEllipticRegularityData
    period hPeriod (Regularity := Regularity)
  profile : CanonicalLatitudeCauchyJetProfileIntegrabilityData
  eulerRealization : geometric.toCauchyJetGeometricData.CauchyJetEulerProductRealizationData
    period hPeriod
  eulerEstimate : geometric.toCauchyJetGeometricData.CauchyJetEulerProductEstimateData
    period hPeriod eulerRealization

namespace CanonicalPhysicalScalarCauchyJetPDEData

/-- Wave-natural presentation used by the product-coordinate estimate modules. -/
def jetGeometric
    {ValueCore : Type x} {NormalCore : Type y}
    [AddCommGroup ValueCore] [Module Real ValueCore]
    [AddCommGroup NormalCore] [Module Real NormalCore]
    (pde : CanonicalPhysicalScalarCauchyJetPDEData
      period hPeriod massSquared ValueCore NormalCore
      (Regularity := Regularity)) :=
  pde.geometric.toCauchyJetGeometricData

/-- Bulk product estimate generated by the two fixed profile moments. -/
def bulkEstimate
    {ValueCore : Type x} {NormalCore : Type y}
    [AddCommGroup ValueCore] [Module Real ValueCore]
    [AddCommGroup NormalCore] [Module Real NormalCore]
    (pde : CanonicalPhysicalScalarCauchyJetPDEData
      period hPeriod massSquared ValueCore NormalCore
      (Regularity := Regularity)) :
    pde.jetGeometric.CauchyJetProductL2EstimateData period hPeriod :=
  pde.jetGeometric.cauchyJetProductL2EstimateData pde.profile

/-- Squared bulk and Euler component estimates. -/
def squaredGraphEstimate
    {ValueCore : Type x} {NormalCore : Type y}
    [AddCommGroup ValueCore] [Module Real ValueCore]
    [AddCommGroup NormalCore] [Module Real NormalCore]
    (pde : CanonicalPhysicalScalarCauchyJetPDEData
      period hPeriod massSquared ValueCore NormalCore
      (Regularity := Regularity)) :
    pde.jetGeometric.CauchyJetSquaredComponentGraphEstimateData period hPeriod :=
  pde.eulerEstimate.combine pde.bulkEstimate

/-- Linear component and graph estimates. -/
def graphEstimate
    {ValueCore : Type x} {NormalCore : Type y}
    [AddCommGroup ValueCore] [Module Real ValueCore]
    [AddCommGroup NormalCore] [Module Real NormalCore]
    (pde : CanonicalPhysicalScalarCauchyJetPDEData
      period hPeriod massSquared ValueCore NormalCore
      (Regularity := Regularity)) :
    pde.jetGeometric.CauchyJetComponentGraphEstimateData period hPeriod :=
  pde.squaredGraphEstimate.toComponentGraphEstimateData

/-- Squared Gårding estimate. -/
def garding
    {ValueCore : Type x} {NormalCore : Type y}
    [AddCommGroup ValueCore] [Module Real ValueCore]
    [AddCommGroup NormalCore] [Module Real NormalCore]
    (pde : CanonicalPhysicalScalarCauchyJetPDEData
      period hPeriod massSquared ValueCore NormalCore
      (Regularity := Regularity)) :
    pde.jetGeometric.greenCore.SquaredGardingEstimate period hPeriod :=
  pde.gardingEnergy.toSquaredGardingEstimate pde.jetGeometric.greenCore

/-- Normal regularity in graph form. -/
def normal
    {ValueCore : Type x} {NormalCore : Type y}
    [AddCommGroup ValueCore] [Module Real ValueCore]
    [AddCommGroup NormalCore] [Module Real NormalCore]
    (pde : CanonicalPhysicalScalarCauchyJetPDEData
      period hPeriod massSquared ValueCore NormalCore
      (Regularity := Regularity)) :
    pde.jetGeometric.greenCore.NormalRegularityData
      period hPeriod (Regularity := Regularity) :=
  pde.normalRegularity.toNormalRegularityData pde.jetGeometric.greenCore

/-- Cutoff-closed completed-boundary input generated by all four PDE layers. -/
def boundaryData
    {ValueCore : Type x} {NormalCore : Type y}
    [AddCommGroup ValueCore] [Module Real ValueCore]
    [AddCommGroup NormalCore] [Module Real NormalCore]
    (pde : CanonicalPhysicalScalarCauchyJetPDEData
      period hPeriod massSquared ValueCore NormalCore
      (Regularity := Regularity)) :
    CanonicalPhysicalScalarCutoffClosedBoundaryData
      period hPeriod massSquared ValueCore NormalCore
      (Regularity := Regularity) where
  geometric := pde.jetGeometric.toGeometricGreenCoreData
  garding := pde.garding
  normalRegularity := pde.normal
  extensionConstant := pde.graphEstimate.graphConstant
  extensionConstant_nonnegative := pde.graphEstimate.graphConstant_nonnegative
  extensionGraphBound := pde.graphEstimate.graph_bound

/-- Correct completed physical boundary triple. -/
def triple
    {ValueCore : Type x} {NormalCore : Type y}
    [AddCommGroup ValueCore] [Module Real ValueCore]
    [AddCommGroup NormalCore] [Module Real NormalCore]
    (pde : CanonicalPhysicalScalarCauchyJetPDEData
      period hPeriod massSquared ValueCore NormalCore
      (Regularity := Regularity)) :=
  pde.boundaryData.triple

/-- Complete physical boundary input package. -/
def completedInputs
    {ValueCore : Type x} {NormalCore : Type y}
    [AddCommGroup ValueCore] [Module Real ValueCore]
    [AddCommGroup NormalCore] [Module Real NormalCore]
    (pde : CanonicalPhysicalScalarCauchyJetPDEData
      period hPeriod massSquared ValueCore NormalCore
      (Regularity := Regularity)) :=
  pde.boundaryData.completedInputs

/-- Explicit Cauchy-jet graph bound. -/
theorem extension_graph_bound
    {ValueCore : Type x} {NormalCore : Type y}
    [AddCommGroup ValueCore] [Module Real ValueCore]
    [AddCommGroup NormalCore] [Module Real NormalCore]
    (pde : CanonicalPhysicalScalarCauchyJetPDEData
      period hPeriod massSquared ValueCore NormalCore
      (Regularity := Regularity))
    (data : ValueCore × NormalCore) :
    ‖canonicalScalarGreenCoreToGraph pde.geometric.greenCore.core
        (pde.geometric.extension data)‖ ≤
      max pde.profile.extensionConstant pde.eulerEstimate.constant *
        ‖P0EFTJanusMappingTorusScalarBoundarySmoothExtensionDensity4D.canonicalScalarBoundaryCorePairEmbedding
          pde.geometric.boundaryCore.valueEmbedding
          pde.geometric.boundaryCore.normalEmbedding data‖ := by
  exact pde.squaredGraphEstimate.graph_bound data

/-- Explicit-Cauchy PDE closure certificate. -/
theorem certificate
    {ValueCore : Type x} {NormalCore : Type y}
    [AddCommGroup ValueCore] [Module Real ValueCore]
    [AddCommGroup NormalCore] [Module Real NormalCore]
    (pde : CanonicalPhysicalScalarCauchyJetPDEData
      period hPeriod massSquared ValueCore NormalCore
      (Regularity := Regularity)) :
    DenseRange
        (P0EFTJanusMappingTorusCanonicalPhysicalScalarFirstSheetHilbertTrace4D.smoothCanonicalPhysicalScalarFirstSheetCauchyTrace
          period hPeriod) ∧
      pde.geometric.greenCore.MinimalCoreDense period hPeriod ∧
      Function.Injective
        (canonicalScalarGreenCoreGraphInclusion
          pde.geometric.greenCore.core) ∧
      Function.Surjective
        (canonicalScalarGreenCoreCompletedBoundaryTrace
          pde.geometric.greenCore.core
          (pde.completedInputs.traceBound pde.geometric.greenCore)) ∧
      (∀ data : ValueCore × NormalCore,
        ‖canonicalScalarGreenCoreToGraph pde.geometric.greenCore.core
            (pde.geometric.extension data)‖ ≤
          max pde.profile.extensionConstant pde.eulerEstimate.constant *
            ‖P0EFTJanusMappingTorusScalarBoundarySmoothExtensionDensity4D.canonicalScalarBoundaryCorePairEmbedding
              pde.geometric.boundaryCore.valueEmbedding
              pde.geometric.boundaryCore.normalEmbedding data‖) :=
  ⟨pde.geometric.boundaryTrace_denseRange,
    (pde.boundaryData.certificate).1,
    (pde.boundaryData.certificate).2.1,
    (pde.boundaryData.certificate).2.2,
    pde.extension_graph_bound⟩

end CanonicalPhysicalScalarCauchyJetPDEData

end
end P0EFTJanusMappingTorusCanonicalPhysicalScalarCauchyJetPDEClosure4D
end JanusFormal
