import JanusFormal.Branches.FundamentalGeometryPVariationalPrinciple.Gates.P0EFTJanusProgramPCandidateAFiveSectorSymmetricGarding4D

/-!
# Candidate-A sector Gårding from ten continuous cross forms

The ten symmetric cross-sector constants need not be chosen.  A continuous
bilinear cross form `B_st` has the canonical quadratic bound

`|B_st(x,x)| ≤ ‖B_st‖ ‖x‖²`.

Hence the off-diagonal coupling constant is the finite sum of the ten operator
norms.
-/

namespace JanusFormal
namespace P0EFTJanusProgramPCandidateAFiveSectorCrossFormGarding4D

set_option autoImplicit false
noncomputable section

open scoped BigOperators
open P0EFTJanusProgramPCandidateAFiveSectorSymmetricGarding4D
open P0EFTJanusProgramPCandidateAFiveSectorPairwiseGarding4D
open P0EFTJanusProgramPGlobalCandidateANamedZeroModeSectors4D

variable {E : Type*}
  [NormedAddCommGroup E] [NormedSpace Real E]

/-- Five diagonal sector estimates and ten continuous symmetric cross blocks. -/
structure CandidateAFiveSectorCrossFormGardingData where
  diagonalConstants : CandidateAFiveSectorDiagonalConstants
  sectorWeight : CandidateAZeroModeSector → E → Real
  sectorWeight_nonneg : ∀ sector vector,
    0 ≤ sectorWeight sector vector
  sectorWeight_sum : ∀ vector,
    ‖vector‖ ^ 2 =
      ∑ sector : CandidateAZeroModeSector,
        sectorWeight sector vector
  diagonalEnergy : E → Real
  diagonal_lower : ∀ vector,
    (∑ sector : CandidateAZeroModeSector,
      diagonalConstants.sectorConstant sector * sectorWeight sector vector) ≤
        diagonalEnergy vector
  crossForm : CandidateACrossSectorPair →
    E →L[Real] E →L[Real] Real
  cross_sum_small :
    (∑ pair : CandidateACrossSectorPair, ‖crossForm pair‖) <
      diagonalConstants.sectorFloor
  principalEnergy : E → Real
  principal_eq : ∀ vector,
    principalEnergy vector = diagonalEnergy vector +
      ∑ pair : CandidateACrossSectorPair,
        crossForm pair vector vector

namespace CandidateAFiveSectorCrossFormGardingData

/-- Canonical quadratic estimate for one continuous cross form. -/
theorem crossForm_quadratic_bound
    (data : CandidateAFiveSectorCrossFormGardingData (E := E))
    (pair : CandidateACrossSectorPair)
    (vector : E) :
    |data.crossForm pair vector vector| ≤
      ‖data.crossForm pair‖ * ‖vector‖ ^ 2 := by
  calc
    |data.crossForm pair vector vector| =
        ‖data.crossForm pair vector vector‖ :=
      (Real.norm_eq_abs _).symm
    _ ≤ ‖data.crossForm pair vector‖ * ‖vector‖ :=
      (data.crossForm pair vector).le_opNorm vector
    _ ≤ (‖data.crossForm pair‖ * ‖vector‖) * ‖vector‖ :=
      mul_le_mul_of_nonneg_right
        ((data.crossForm pair).le_opNorm vector)
        (norm_nonneg vector)
    _ = ‖data.crossForm pair‖ * ‖vector‖ ^ 2 := by
      ring

/-- Convert continuous cross forms to the ten-constant symmetric packet. -/
def toSymmetricGardingData
    (data : CandidateAFiveSectorCrossFormGardingData (E := E)) :
    CandidateAFiveSectorSymmetricGardingData (E := E) where
  diagonalConstants := data.diagonalConstants
  sectorWeight := data.sectorWeight
  sectorWeight_nonneg := data.sectorWeight_nonneg
  sectorWeight_sum := data.sectorWeight_sum
  diagonalEnergy := data.diagonalEnergy
  diagonal_lower := data.diagonal_lower
  crossEnergy := fun pair vector => data.crossForm pair vector vector
  crossConstant := fun pair => ‖data.crossForm pair‖
  crossConstant_nonneg := fun pair => norm_nonneg _
  cross_bound := data.crossForm_quadratic_bound
  cross_sum_small := data.cross_sum_small
  principalEnergy := data.principalEnergy
  principal_eq := data.principal_eq

/-- Canonical principal coupling constant: the sum of ten bilinear operator
norms. -/
def couplingConstant
    (data : CandidateAFiveSectorCrossFormGardingData (E := E)) : Real :=
  ∑ pair : CandidateACrossSectorPair, ‖data.crossForm pair‖

/-- Explicit principal margin generated by the continuous cross forms. -/
def margin
    (data : CandidateAFiveSectorCrossFormGardingData (E := E)) : Real :=
  data.diagonalConstants.sectorFloor - data.couplingConstant

/-- Candidate-A Gårding directly from the ten continuous cross blocks. -/
theorem candidateA_five_sector_cross_form_garding_gate
    (data : CandidateAFiveSectorCrossFormGardingData (E := E)) :
    0 < data.margin ∧
      ∀ vector : E,
        data.margin * ‖vector‖ ^ 2 ≤ data.principalEnergy vector := by
  simpa [margin, couplingConstant,
    CandidateAFiveSectorSymmetricGardingData.margin,
    CandidateAFiveSectorSymmetricGardingData.couplingConstant] using
      data.toSymmetricGardingData.candidateA_five_sector_symmetric_garding_gate

end CandidateAFiveSectorCrossFormGardingData

end
end P0EFTJanusProgramPCandidateAFiveSectorCrossFormGarding4D
end JanusFormal
