import JanusFormal.Branches.FundamentalGeometryPVariationalPrinciple.Gates.P0EFTJanusProgramPActualThroatGaugeCombinedFrameBaseChartSecondOrderGroupoid4D

/-!
# Generated setoid of local throat gauge second-jet presentations

A presentation records a valid tangent frame, a valid base chart and an
arbitrary framed second jet at one throat point.  Direct compatibility is the
exact value, Jacobian and Hessian transition law.  The public setoid is
explicitly the equivalence closure generated by that direct relation; this
gate does not claim that direct compatibility itself is already transitive.
-/

namespace JanusFormal
namespace P0EFTJanusProgramPActualThroatGaugeSecondOrderJetPresentationSetoid4D

set_option autoImplicit false
set_option synthInstance.maxHeartbeats 100000
set_option maxHeartbeats 600000

noncomputable section

open Set Filter
open scoped Manifold ContDiff RealInnerProductSpace Topology
open Bundle
open P0EFTJanusMappingTorusQuotient
open P0EFTJanusMappingTorusSmoothAtlasFrontier
open P0EFTJanusMappingTorusSmoothQuotientManifold
open P0EFTJanusMappingTorusGeneralLorentzMetricThroatTrace4D
open P0EFTJanusProgramPPhysicalSecondOrderJetCarrier4D
open P0EFTJanusProgramPActualThroatAbelianPotentialChartwiseSecondOrderJetExtraction4D
open P0EFTJanusProgramPActualThroatGaugeDifferentiatedOverlap4D
open P0EFTJanusProgramPActualThroatGaugeZeroOrderTransitionCocycle4D
open P0EFTJanusProgramPActualThroatGaugeChartwiseFirstOrderOverlap4D
open P0EFTJanusProgramPActualThroatGaugeBaseChartTransitionGerm4D
open P0EFTJanusProgramPActualThroatGaugeBaseChartSecondOrderJetOverlap4D
open P0EFTJanusProgramPActualThroatGaugeBaseChartTransitionSecondOrderCocycle4D
open P0EFTJanusProgramPActualThroatGaugeBaseChartTransitionSecondOrderGroupoid4D
open P0EFTJanusProgramPActualThroatGaugeArbitraryFrameBaseChartSecondOrderJetOverlap4D
open P0EFTJanusProgramPActualThroatGaugeCombinedFrameBaseChartSecondOrderGroupoid4D

variable (period : Real) (hPeriod : period ≠ 0)

private abbrev EffectiveThroat :=
  MappingTorus (fixedEquatorData period hPeriod)

local instance effectiveThroatChartedSpace :
    ChartedSpace ThroatCoverModel (EffectiveThroat period hPeriod) :=
  fixedThroatQuotientChartedSpace period hPeriod

local instance effectiveThroatIsManifold :
    IsManifold throatCoverModelWithCorners ω
      (EffectiveThroat period hPeriod) :=
  fixedThroatQuotient_isManifold period hPeriod

/-! ## Local presentations and their direct transition relation -/

/-- One arbitrary framed second jet together with a tangent frame and base
chart that are both valid at `current`. -/
structure ThroatGaugeSecondOrderJetPresentationAt
    (current : EffectiveThroat period hPeriod) where
  frameAnchor : EffectiveThroat period hPeriod
  chartAnchor : EffectiveThroat period hPeriod
  frame_mem : current ∈
    (trivializationAt ThroatCoverCoordinates
      (ThroatTangentFiber period hPeriod) frameAnchor).baseSet
  chart_mem : current ∈
    (extChartAt throatCoverModelWithCorners chartAnchor).source
  jet : FramedSecondOrderJet ThroatCoverCoordinates
    (FramedCovector ThroatCoverCoordinates)

/-- Exact one-step compatibility of two arbitrary local presentations.  The
second jet is pulled back by the base-chart Jacobian and Hessian while the
first jet is acted on by the varying contragredient frame transition. -/
structure DirectTransitionCompatible
    {current : EffectiveThroat period hPeriod}
    (first second :
      ThroatGaugeSecondOrderJetPresentationAt period hPeriod current) : Prop where
  value_transition :
    second.jet.value =
      throatGaugeCovectorTrivializationTransitionAt period hPeriod
        first.frameAnchor second.frameAnchor current first.jet.value
  firstDerivative_transition :
    second.jet.firstDerivative.comp
        (fderiv Real
          (throatGaugeBaseChartTransition period hPeriod
            first.chartAnchor second.chartAnchor)
          (extChartAt throatCoverModelWithCorners first.chartAnchor current)) =
      (throatGaugeCovectorTrivializationTransitionAt period hPeriod
          first.frameAnchor second.frameAnchor current :
            FramedCovector ThroatCoverCoordinates →L[Real]
              FramedCovector ThroatCoverCoordinates).comp
        first.jet.firstDerivative +
      (fderiv Real
        (throatGaugeCovectorTransitionCenteredChart period hPeriod
          first.frameAnchor second.frameAnchor first.chartAnchor)
        (extChartAt throatCoverModelWithCorners first.chartAnchor current)).flip
          first.jet.value
  secondDerivative_transition : ∀ firstDirection secondDirection,
    second.jet.secondDerivative
        (fderiv Real
          (throatGaugeBaseChartTransition period hPeriod
            first.chartAnchor second.chartAnchor)
          (extChartAt throatCoverModelWithCorners first.chartAnchor current)
            firstDirection)
        (fderiv Real
          (throatGaugeBaseChartTransition period hPeriod
            first.chartAnchor second.chartAnchor)
          (extChartAt throatCoverModelWithCorners first.chartAnchor current)
            secondDirection) +
      second.jet.firstDerivative
        (fderiv Real
          (fderiv Real
            (throatGaugeBaseChartTransition period hPeriod
              first.chartAnchor second.chartAnchor))
          (extChartAt throatCoverModelWithCorners first.chartAnchor current)
            firstDirection secondDirection) =
      throatGaugeCovectorTrivializationTransitionAt period hPeriod
        first.frameAnchor second.frameAnchor current
          (first.jet.secondDerivative firstDirection secondDirection) +
      fderiv Real
          (throatGaugeCovectorTransitionCenteredChart period hPeriod
            first.frameAnchor second.frameAnchor first.chartAnchor)
          (extChartAt throatCoverModelWithCorners first.chartAnchor current)
            firstDirection
        (first.jet.firstDerivative secondDirection) +
      fderiv Real
          (throatGaugeCovectorTransitionCenteredChart period hPeriod
            first.frameAnchor second.frameAnchor first.chartAnchor)
          (extChartAt throatCoverModelWithCorners first.chartAnchor current)
            secondDirection
        (first.jet.firstDerivative firstDirection) +
      fderiv Real
          (fun coordinate =>
            fderiv Real
              (throatGaugeCovectorTransitionCenteredChart period hPeriod
                first.frameAnchor second.frameAnchor first.chartAnchor)
              coordinate secondDirection)
          (extChartAt throatCoverModelWithCorners first.chartAnchor current)
            firstDirection first.jet.value

/-! ## Real extracted presentations -/

/-- The actual extracted gauge jet in any valid frame/chart presentation. -/
def actualThroatGaugeSecondOrderJetPresentationAt
    (potential : SmoothThroatAbelianGaugePotential period hPeriod)
    (component : Fin 2)
    (frameAnchor chartAnchor current : EffectiveThroat period hPeriod)
    (hFrame : current ∈
      (trivializationAt ThroatCoverCoordinates
        (ThroatTangentFiber period hPeriod) frameAnchor).baseSet)
    (hChart : current ∈
      (extChartAt throatCoverModelWithCorners chartAnchor).source) :
    ThroatGaugeSecondOrderJetPresentationAt period hPeriod current where
  frameAnchor := frameAnchor
  chartAnchor := chartAnchor
  frame_mem := hFrame
  chart_mem := hChart
  jet := throatGaugeCovectorSecondOrderJetInBaseChartAt period hPeriod
    potential component frameAnchor chartAnchor current hFrame hChart

/-- Any two actual extracted presentations are directly compatible. -/
theorem actualThroatGaugeSecondOrderJetPresentationAt_directCompatible
    (potential : SmoothThroatAbelianGaugePotential period hPeriod)
    (component : Fin 2)
    (firstAnchor secondAnchor firstCenter secondCenter current :
      EffectiveThroat period hPeriod)
    (hCurrent : current ∈
      throatGaugeCenteredTrivializationOverlap period hPeriod
        firstAnchor secondAnchor)
    (hFirst : current ∈
      (extChartAt throatCoverModelWithCorners firstCenter).source)
    (hSecond : current ∈
      (extChartAt throatCoverModelWithCorners secondCenter).source) :
    DirectTransitionCompatible period hPeriod
      (actualThroatGaugeSecondOrderJetPresentationAt period hPeriod potential
        component firstAnchor firstCenter current hCurrent.1 hFirst)
      (actualThroatGaugeSecondOrderJetPresentationAt period hPeriod potential
        component secondAnchor secondCenter current hCurrent.2 hSecond) := by
  constructor
  · exact throatGaugeCovectorSecondOrderJet_arbitraryFrameBaseChart_value
      period hPeriod potential component firstAnchor secondAnchor firstCenter
        secondCenter current hCurrent hFirst hSecond
  · exact
      throatGaugeCovectorSecondOrderJet_arbitraryFrameBaseChart_firstDerivative_transition
        period hPeriod potential component firstAnchor secondAnchor firstCenter
          secondCenter current hCurrent hFirst hSecond
  · exact
      throatGaugeCovectorSecondOrderJet_arbitraryFrameBaseChart_secondDerivative_transition_apply
        period hPeriod potential component firstAnchor secondAnchor firstCenter
          secondCenter current hCurrent hFirst hSecond

/-! ## Generated equivalence relation -/

/-- Equivalence relation generated by exact direct transition compatibility.
The name records that no equality with the direct relation is asserted. -/
def GeneratedTransitionRelation
    {current : EffectiveThroat period hPeriod} :
    ThroatGaugeSecondOrderJetPresentationAt period hPeriod current →
      ThroatGaugeSecondOrderJetPresentationAt period hPeriod current → Prop :=
  Relation.EqvGen (DirectTransitionCompatible period hPeriod)

/-- Setoid generated by the exact value/Jacobian/Hessian transition laws. -/
def throatGaugeSecondOrderJetPresentationGeneratedSetoid
    (current : EffectiveThroat period hPeriod) :
    Setoid (ThroatGaugeSecondOrderJetPresentationAt period hPeriod current) :=
  Relation.EqvGen.setoid (DirectTransitionCompatible period hPeriod)

theorem generatedTransitionRelation_refl
    {current : EffectiveThroat period hPeriod}
    (presentation :
      ThroatGaugeSecondOrderJetPresentationAt period hPeriod current) :
    GeneratedTransitionRelation period hPeriod presentation presentation :=
  Relation.EqvGen.refl presentation

theorem generatedTransitionRelation_symm
    {current : EffectiveThroat period hPeriod}
    {first second :
      ThroatGaugeSecondOrderJetPresentationAt period hPeriod current}
    (hRelation : GeneratedTransitionRelation period hPeriod first second) :
    GeneratedTransitionRelation period hPeriod second first :=
  Relation.EqvGen.symm first second hRelation

theorem generatedTransitionRelation_trans
    {current : EffectiveThroat period hPeriod}
    {first second third :
      ThroatGaugeSecondOrderJetPresentationAt period hPeriod current}
    (hFirst : GeneratedTransitionRelation period hPeriod first second)
    (hSecond : GeneratedTransitionRelation period hPeriod second third) :
    GeneratedTransitionRelation period hPeriod first third :=
  Relation.EqvGen.trans first second third hFirst hSecond

/-- Every exact direct transition is one generating step. -/
theorem directCompatible_generated
    {current : EffectiveThroat period hPeriod}
    {first second :
      ThroatGaugeSecondOrderJetPresentationAt period hPeriod current}
    (hDirect : DirectTransitionCompatible period hPeriod first second) :
    GeneratedTransitionRelation period hPeriod first second :=
  Relation.EqvGen.rel first second hDirect

/-- Hence all actual local representatives determine the same generated
equivalence class. -/
theorem actualThroatGaugeSecondOrderJetPresentationAt_generatedRelated
    (potential : SmoothThroatAbelianGaugePotential period hPeriod)
    (component : Fin 2)
    (firstAnchor secondAnchor firstCenter secondCenter current :
      EffectiveThroat period hPeriod)
    (hCurrent : current ∈
      throatGaugeCenteredTrivializationOverlap period hPeriod
        firstAnchor secondAnchor)
    (hFirst : current ∈
      (extChartAt throatCoverModelWithCorners firstCenter).source)
    (hSecond : current ∈
      (extChartAt throatCoverModelWithCorners secondCenter).source) :
    GeneratedTransitionRelation period hPeriod
      (actualThroatGaugeSecondOrderJetPresentationAt period hPeriod potential
        component firstAnchor firstCenter current hCurrent.1 hFirst)
      (actualThroatGaugeSecondOrderJetPresentationAt period hPeriod potential
        component secondAnchor secondCenter current hCurrent.2 hSecond) :=
  directCompatible_generated period hPeriod
    (actualThroatGaugeSecondOrderJetPresentationAt_directCompatible
      period hPeriod potential component firstAnchor secondAnchor firstCenter
        secondCenter current hCurrent hFirst hSecond)

end
end P0EFTJanusProgramPActualThroatGaugeSecondOrderJetPresentationSetoid4D
end JanusFormal
