import JanusFormal.Branches.FundamentalGeometryPVariationalPrinciple.Gates.P0EFTJanusProgramPFiveSectorL2HilbertCoordinates4D
import JanusFormal.Branches.FundamentalGeometryPVariationalPrinciple.Gates.P0EFTJanusProgramPFiniteCommutingProjectionKernelResolution4D

/-!
# L² five-sector bridge to commuting kernel resolutions

This is the smallest generic interface needed by the D11 actual-kernel route:
an L² five-sector facade supplies the self-adjoint ambient resolution, and one
commutation proof restricts it canonically to the true operator kernel.
-/

namespace JanusFormal
namespace P0EFTJanusProgramPFiveSectorL2CommutingKernelResolutionBridge4D

set_option autoImplicit false
set_option maxHeartbeats 3200000
set_option synthInstance.maxHeartbeats 1600000

noncomputable section

open scoped BigOperators InnerProductSpace
open P0EFTJanusProgramPFiveSectorOrthogonalProductResolution4D
open P0EFTJanusProgramPFiveSectorL2HilbertCoordinates4D
open P0EFTJanusProgramPFiniteSelfAdjointProjectionResolution4D
open P0EFTJanusProgramPFiniteCommutingProjectionKernelComplement4D

variable
  {E Metric Abelian Matter Longitudinal Boundary : Type*}
  [NormedAddCommGroup E] [InnerProductSpace Real E] [CompleteSpace E]
  [NormedAddCommGroup Metric] [InnerProductSpace Real Metric]
  [NormedAddCommGroup Abelian] [InnerProductSpace Real Abelian]
  [NormedAddCommGroup Matter] [InnerProductSpace Real Matter]
  [NormedAddCommGroup Longitudinal] [InnerProductSpace Real Longitudinal]
  [NormedAddCommGroup Boundary] [InnerProductSpace Real Boundary]

/-- The self-adjoint finite resolution generated by L² five-sector
coordinates. -/
def fiveSectorL2SelfAdjointResolution
    (coordinates : FiveSectorL2HilbertCoordinates
      (E := E) (Metric := Metric) (Abelian := Abelian) (Matter := Matter)
      (Longitudinal := Longitudinal) (Boundary := Boundary)) :
    FiniteSelfAdjointProjectionResolutionData
      (Sector := FiveSectorSlot) (E := E) where
  projection := coordinates.sectorProjector
  sum_projection := coordinates.projectors_reconstruct
  projection_idempotent := coordinates.sectorProjector_idempotent
  projection_symmetric := coordinates.sectorProjector_selfAdjoint

/-- Add commutation with one operator to obtain the exact ambient interface
used by the D11 kernel-restriction construction. -/
def fiveSectorL2CommutingResolution
    (coordinates : FiveSectorL2HilbertCoordinates
      (E := E) (Metric := Metric) (Abelian := Abelian) (Matter := Matter)
      (Longitudinal := Longitudinal) (Boundary := Boundary))
    (operator : E →L[Real] E)
    (commute : ∀ sector state,
      operator (coordinates.sectorProjector sector state) =
        coordinates.sectorProjector sector (operator state)) :
    FiniteCommutingProjectionResolutionData
      (Sector := FiveSectorSlot) operator where
  resolution := fiveSectorL2SelfAdjointResolution coordinates
  commute := commute

/-- Canonical L² five-sector resolution on the true kernel of a commuting
operator. -/
def fiveSectorL2KernelResolution
    (coordinates : FiveSectorL2HilbertCoordinates
      (E := E) (Metric := Metric) (Abelian := Abelian) (Matter := Matter)
      (Longitudinal := Longitudinal) (Boundary := Boundary))
    (operator : E →L[Real] E)
    (commute : ∀ sector state,
      operator (coordinates.sectorProjector sector state) =
        coordinates.sectorProjector sector (operator state)) :
    FiniteSelfAdjointProjectionResolutionData
      (Sector := FiveSectorSlot) (E := operator.ker) :=
  FiniteCommutingProjectionResolutionData.toKernelResolution
    (fiveSectorL2CommutingResolution coordinates operator commute)

/-- Public checkpoint for the D11-ready commuting-kernel bridge. -/
theorem five_sector_l2_commuting_kernel_resolution_gate
    (coordinates : FiveSectorL2HilbertCoordinates
      (E := E) (Metric := Metric) (Abelian := Abelian) (Matter := Matter)
      (Longitudinal := Longitudinal) (Boundary := Boundary))
    (operator : E →L[Real] E)
    (commute : ∀ sector state,
      operator (coordinates.sectorProjector sector state) =
        coordinates.sectorProjector sector (operator state)) :
    let resolution :=
      fiveSectorL2KernelResolution coordinates operator commute
    (∀ vector,
      (∑ sector : FiveSectorSlot,
        resolution.projection sector vector) = vector) ∧
    (∀ sector vector,
      resolution.projection sector (resolution.projection sector vector) =
        resolution.projection sector vector) ∧
    (∀ sector first second,
      inner Real (resolution.projection sector first) second =
        inner Real first (resolution.projection sector second)) ∧
    (∀ vector,
      ‖vector‖ ^ 2 =
        ∑ sector : FiveSectorSlot,
          ‖resolution.projection sector vector‖ ^ 2) := by
  exact
    FiniteCommutingProjectionResolutionData.finite_commuting_projection_kernel_gate
      operator (fiveSectorL2CommutingResolution coordinates operator commute)

end

end P0EFTJanusProgramPFiveSectorL2CommutingKernelResolutionBridge4D
end JanusFormal
