import Mathlib.Tactic
import JanusFormal.Branches.FundamentalGeometryPVariationalPrinciple.Gates.P0EFTJanusProgramPFiveSectorHilbertCoordinatesOrthogonality4D
import JanusFormal.Branches.FundamentalGeometryPVariationalPrinciple.Gates.P0EFTJanusProgramPFiniteSelfAdjointProjectionResolution4D

/-!
# Self-adjoint resolution from five-sector Hilbert coordinates

One linear isometric equivalence with the right-associated five-factor product
already defines the five canonical sector projectors.  This layer packages
those maps as the generic finite self-adjoint projection resolution used by the
kernel and kernel-complement constructions.
-/

namespace JanusFormal
namespace P0EFTJanusProgramPFiveSectorHilbertCoordinatesResolution4D

set_option autoImplicit false
noncomputable section

open scoped BigOperators InnerProductSpace
open P0EFTJanusProgramPFiveSectorHilbertCoordinates4D
open P0EFTJanusProgramPFiveSectorHilbertCoordinatesOrthogonality4D
open P0EFTJanusProgramPFiniteSelfAdjointProjectionResolution4D

variable
  {E Metric Abelian Matter Longitudinal Boundary : Type*}
  [NormedAddCommGroup E] [InnerProductSpace Real E]
  [NormedAddCommGroup Metric] [InnerProductSpace Real Metric]
  [NormedAddCommGroup Abelian] [InnerProductSpace Real Abelian]
  [NormedAddCommGroup Matter] [InnerProductSpace Real Matter]
  [NormedAddCommGroup Longitudinal] [InnerProductSpace Real Longitudinal]
  [NormedAddCommGroup Boundary] [InnerProductSpace Real Boundary]

private theorem five_physical_sector_univ :
    (Finset.univ : Finset FivePhysicalSector) =
      { .metricDiffeomorphism, .abelianGauge, .primitiveSpinCMatter,
        .longitudinalLL, .boundaryFiniteBV } := by
  decide

/-- Every canonical Hilbert-coordinate projector is symmetric. -/
theorem sectorProjector_symmetric
    (coordinates : FiveSectorHilbertCoordinates
      (E := E) (Metric := Metric) (Abelian := Abelian) (Matter := Matter)
      (Longitudinal := Longitudinal) (Boundary := Boundary))
    (sector : FivePhysicalSector) (first second : E) :
    inner Real (coordinates.sectorProjector sector first) second =
      inner Real first (coordinates.sectorProjector sector second) := by
  rw [← coordinates.decomposition.inner_map_map]
  rw [← coordinates.decomposition.inner_map_map]
  cases sector <;>
    simp [FiveSectorHilbertCoordinates.sectorProjector,
      FiveSectorHilbertCoordinates.metricProjector,
      FiveSectorHilbertCoordinates.abelianProjector,
      FiveSectorHilbertCoordinates.matterProjector,
      FiveSectorHilbertCoordinates.longitudinalProjector,
      FiveSectorHilbertCoordinates.boundaryProjector,
      fiveSectorMetricAxis, fiveSectorAbelianAxis, fiveSectorMatterAxis,
      fiveSectorLongitudinalAxis, fiveSectorBoundaryAxis,
      fiveSectorMetricCoordinate, fiveSectorAbelianCoordinate,
      fiveSectorMatterCoordinate, fiveSectorLongitudinalCoordinate,
      fiveSectorBoundaryCoordinate]

/-- The five projectors generated by one Hilbert coordinate decomposition form
an exact finite self-adjoint resolution of the identity. -/
def fiveSectorHilbertSelfAdjointResolution
    (coordinates : FiveSectorHilbertCoordinates
      (E := E) (Metric := Metric) (Abelian := Abelian) (Matter := Matter)
      (Longitudinal := Longitudinal) (Boundary := Boundary)) :
    FiniteSelfAdjointProjectionResolutionData
      (Sector := FivePhysicalSector) (E := E) where
  projection := coordinates.sectorProjector
  sum_projection := by
    intro vector
    rw [five_physical_sector_univ]
    simpa [FiveSectorHilbertCoordinates.sectorProjector] using
      coordinates.projectors_decompose vector
  projection_idempotent := coordinates.sectorProjector_idempotent
  projection_symmetric := sectorProjector_symmetric coordinates

/-- Public five-sector Hilbert resolution checkpoint. -/
theorem five_sector_hilbert_coordinates_resolution_gate
    (coordinates : FiveSectorHilbertCoordinates
      (E := E) (Metric := Metric) (Abelian := Abelian) (Matter := Matter)
      (Longitudinal := Longitudinal) (Boundary := Boundary)) :
    let resolution := fiveSectorHilbertSelfAdjointResolution coordinates
    (∀ vector,
      (∑ sector : FivePhysicalSector,
        resolution.projection sector vector) = vector) ∧
    (∀ sector vector,
      resolution.projection sector (resolution.projection sector vector) =
        resolution.projection sector vector) ∧
    (∀ sector first second,
      inner Real (resolution.projection sector first) second =
        inner Real first (resolution.projection sector second)) ∧
    (∀ vector,
      ‖vector‖ ^ 2 =
        ∑ sector : FivePhysicalSector,
          ‖resolution.projection sector vector‖ ^ 2) := by
  dsimp only
  let resolution := fiveSectorHilbertSelfAdjointResolution coordinates
  exact
    ⟨resolution.sum_projection,
      resolution.projection_idempotent,
      resolution.projection_symmetric,
      resolution.norm_sq_decomposition⟩

end
end P0EFTJanusProgramPFiveSectorHilbertCoordinatesResolution4D
end JanusFormal