import JanusFormal.Branches.FundamentalGeometryPVariationalPrinciple.Gates.P0EFTJanusIntegratedHolonomicMetricScalarVariation4D

/-!
# Flat four-dimensional holonomic scalar Euler operator

This gate performs the local integration-by-parts algebra for the genuine
`p = d phi` scalar variation.  It identifies the exact Euler expression and
the boundary-flux divergence pointwise on `R^4`.  Vanishing of the integrated
flux remains a named boundary condition rather than a hidden assumption.
-/

namespace JanusFormal
namespace P0EFTJanusFlatHolonomicScalarEuler4D

set_option autoImplicit false

noncomputable section

open P0EFTJanusMetricCoupledScalarMatterJetVariation
open P0EFTJanusMetricInducedScalarStressVariation4D
open P0EFTJanusHolonomicScalarFieldVariation4D

abbrev Coordinate4 := P0EFTJanusHolonomicScalarFieldVariation4D.Coordinate4
abbrev Index4 := P0EFTJanusMetricCoupledScalarMatterJetVariation.Index4
abbrev Matrix4 := P0EFTJanusMetricCoupledScalarMatterJetVariation.Matrix4

/-- Contravariant coordinate gradient for a fixed inverse metric. -/
def raisedCoordinateGradient
    (inverseMetric : Matrix4) (field : Coordinate4 → Real)
    (point : Coordinate4) (first : Index4) : Real :=
  ∑ second : Index4,
    inverseMetric first second * coordinateGradient field point second

/-- Coordinate divergence of a vector field on the flat chart. -/
def coordinateDivergence
    (vectorField : Coordinate4 → Index4 → Real) (point : Coordinate4) : Real :=
  ∑ index : Index4,
    fderiv Real (fun x ↦ vectorField x index) point (Pi.single index 1)

/-- Boundary flux generated by a scalar test variation. -/
def scalarBoundaryFlux
    (inverseMetric : Matrix4) (field variation : Coordinate4 → Real)
    (point : Coordinate4) (index : Index4) : Real :=
  variation point * raisedCoordinateGradient inverseMetric field point index

/-- Flat-chart Klein--Gordon Euler expression in the sign convention of the
matter Lagrangian used by Programme P. -/
def flatScalarEulerOperator
    (inverseMetric : Matrix4) (massSquared source : Real)
    (field : Coordinate4 → Real) (point : Coordinate4) : Real :=
  -coordinateDivergence
      (fun x ↦ raisedCoordinateGradient inverseMetric field x) point +
    massSquared * field point + source

private theorem symmetric_scalarMatterFirstVariation_eq_gradient_pairing
    (inverseMetric : Matrix4)
    (hSymmetric : inverseMetric.transpose = inverseMetric)
    (massSquared source : Real) (jet variation : ScalarMatterJet) :
    scalarMatterFirstVariation massSquared source inverseMetric 0 jet variation =
      (∑ index : Index4,
        variation.gradient index *
          (∑ second : Index4,
            inverseMetric index second * jet.gradient second)) +
      massSquared * jet.field * variation.field + source * variation.field := by
  have hSwap :
      (∑ first : Index4, ∑ second : Index4,
        inverseMetric first second * jet.gradient first * variation.gradient second) =
      ∑ first : Index4, ∑ second : Index4,
        inverseMetric first second * variation.gradient first * jet.gradient second := by
    rw [Finset.sum_comm]
    apply Finset.sum_congr rfl
    intro first _
    apply Finset.sum_congr rfl
    intro second _
    have hEntry := congrArg (fun matrix : Matrix4 ↦ matrix second first) hSymmetric
    simp only [Matrix.transpose_apply] at hEntry
    rw [hEntry]
    ring
  simp only [scalarMatterFirstVariation, scalarKineticFirstVariation,
    Matrix.zero_apply, zero_mul, zero_add]
  simp_rw [Finset.sum_add_distrib]
  rw [hSwap]
  have hPairing :
      (∑ first : Index4, variation.gradient first *
        (∑ second : Index4, inverseMetric first second * jet.gradient second)) =
      ∑ first : Index4, ∑ second : Index4,
        inverseMetric first second * variation.gradient first * jet.gradient second := by
    simp_rw [Finset.mul_sum]
    apply Finset.sum_congr rfl
    intro first _
    apply Finset.sum_congr rfl
    intro second _
    ring
  rw [hPairing]
  ring

/-- Product rule for the scalar boundary flux. -/
theorem coordinateDivergence_scalarBoundaryFlux
    (inverseMetric : Matrix4) (field variation : Coordinate4 → Real)
    (point : Coordinate4)
    (hVariation : DifferentiableAt Real variation point)
    (hRaised : ∀ index : Index4,
      DifferentiableAt Real
        (fun x ↦ raisedCoordinateGradient inverseMetric field x index) point) :
    coordinateDivergence
        (scalarBoundaryFlux inverseMetric field variation) point =
      (∑ index : Index4,
        coordinateGradient variation point index *
          raisedCoordinateGradient inverseMetric field point index) +
      variation point * coordinateDivergence
        (fun x ↦ raisedCoordinateGradient inverseMetric field x) point := by
  have hProduct (index : Index4) :
      fderiv Real
          (fun x ↦ variation x *
            raisedCoordinateGradient inverseMetric field x index)
          point (Pi.single index 1) =
        coordinateGradient variation point index *
            raisedCoordinateGradient inverseMetric field point index +
          variation point *
            fderiv Real
              (fun x ↦ raisedCoordinateGradient inverseMetric field x index)
              point (Pi.single index 1) := by
    rw [fderiv_fun_mul hVariation (hRaised index)]
    simp [coordinateGradient]
    ring
  unfold coordinateDivergence scalarBoundaryFlux
  simp_rw [hProduct]
  rw [Finset.sum_add_distrib]
  simp only [Finset.mul_sum]

/-- Exact pointwise Euler-plus-divergence decomposition of the holonomic first
variation. -/
theorem holonomicScalarDensityFirstVariation_euler_decomposition
    (data : FixedSignMetric4) (massSquared source : Real)
    (field variation : Coordinate4 → Real) (point : Coordinate4)
    (hVariation : DifferentiableAt Real variation point)
    (hRaised : ∀ index : Index4,
      DifferentiableAt Real
        (fun x ↦ raisedCoordinateGradient data.metric⁻¹ field x index) point) :
    holonomicScalarDensityFirstVariation data massSquared source
        field variation point =
      Real.sqrt |Matrix.det data.metric| *
        (coordinateDivergence
            (scalarBoundaryFlux data.metric⁻¹ field variation) point +
          variation point *
            flatScalarEulerOperator data.metric⁻¹ massSquared source field point) := by
  have hMatter := symmetric_scalarMatterFirstVariation_eq_gradient_pairing
    data.metric⁻¹ data.inverse_symmetric massSquared source
    (holonomicScalarJet field point) (holonomicScalarJet variation point)
  have hFlux := coordinateDivergence_scalarBoundaryFlux
    data.metric⁻¹ field variation point hVariation hRaised
  unfold holonomicScalarDensityFirstVariation
  rw [hMatter]
  simp only [holonomicScalarJet_field, holonomicScalarJet_gradient]
  rw [hFlux]
  unfold flatScalarEulerOperator
  simp only [raisedCoordinateGradient]
  ring

/-- Boundary condition needed to remove the divergence after integration. -/
def ScalarFluxVanishes
    (mu : MeasureTheory.Measure Coordinate4)
    (data : FixedSignMetric4) (field variation : Coordinate4 → Real) : Prop :=
  MeasureTheory.integral mu (fun point ↦
    coordinateDivergence
      (scalarBoundaryFlux data.metric⁻¹ field variation) point) = 0

end

end P0EFTJanusFlatHolonomicScalarEuler4D
end JanusFormal
