import Mathlib.LinearAlgebra.ExteriorPower.Basis
import JanusFormal.Branches.FundamentalGeometryPVariationalPrinciple.Gates.P0EFTJanusProgramPFiniteKernelBasisFamily4D

/-!
# Determinant lines of named finite kernel families

A fixed finite basis type turns every kernel `ker H_a` into a finite-dimensional
family with constant rank.  Its top exterior power is therefore a genuine
one-dimensional determinant line.

The coordinate-preserving kernel transport induces the corresponding exterior
power transport.  It sends the named volume element at one parameter exactly
to the named volume element at the next parameter and satisfies the expected
composition law.
-/

namespace JanusFormal
namespace P0EFTJanusProgramPFiniteKernelDeterminantLineFamily4D

set_option autoImplicit false
set_option maxHeartbeats 3600000
set_option synthInstance.maxHeartbeats 1800000

noncomputable section

open Module Set Set.powersetCard
open P0EFTJanusProgramPFiniteKernelBasisFamily4D

variable {E : Type*} {ZeroMode : Type}
  [NormedAddCommGroup E] [NormedSpace Real E]
  [Fintype ZeroMode] [DecidableEq ZeroMode] [LinearOrder ZeroMode]

/-- Top exterior power of the actual kernel. -/
abbrev FiniteKernelDeterminantFiber
    {operator : Real → E →L[Real] E}
    (data : FiniteKernelBasisFamilyData operator ZeroMode)
    (parameter : Real) :=
  ⋀[Real]^(Fintype.card ZeroMode) ((operator parameter).ker)

/-- The unique full finite subset used to select the top exterior basis vector. -/
def finiteKernelFullIndexSet :
    powersetCard ZeroMode (Fintype.card ZeroMode) :=
  ⟨Finset.univ, Fintype.card_congr (Equiv.refl ZeroMode)⟩

/-- Named top-degree volume element generated by the physical kernel basis. -/
def finiteKernelNamedVolume
    {operator : Real → E →L[Real] E}
    (data : FiniteKernelBasisFamilyData operator ZeroMode)
    (parameter : Real) :
    FiniteKernelDeterminantFiber data parameter :=
  (data.basis parameter).exteriorPower (Fintype.card ZeroMode)
    finiteKernelFullIndexSet

/-- Exterior-power transport induced by coordinate-preserving kernel transport. -/
def finiteKernelDeterminantTransport
    {operator : Real → E →L[Real] E}
    (data : FiniteKernelBasisFamilyData operator ZeroMode)
    (first second : Real) :
    FiniteKernelDeterminantFiber data first →ₗ[Real]
      FiniteKernelDeterminantFiber data second :=
  exteriorPower.map (Fintype.card ZeroMode)
    (data.kernelTransport first second).toLinearMap

/-- The determinant fibre is one-dimensional. -/
theorem finiteKernelDeterminantFiber_finrank_one
    {operator : Real → E →L[Real] E}
    (data : FiniteKernelBasisFamilyData operator ZeroMode)
    (parameter : Real) :
    Module.finrank Real (FiniteKernelDeterminantFiber data parameter) = 1 := by
  letI : Module.Finite Real (operator parameter).ker :=
    Module.Finite.of_basis (data.basis parameter)
  rw [exteriorPower.finrank_eq, data.kernel_finrank_eq_card parameter,
    Nat.choose_self]

/-- The named volume is nonzero. -/
theorem finiteKernelNamedVolume_ne_zero
    {operator : Real → E →L[Real] E}
    (data : FiniteKernelBasisFamilyData operator ZeroMode)
    (parameter : Real) :
    finiteKernelNamedVolume data parameter ≠ 0 := by
  exact ((data.basis parameter).exteriorPower
    (Fintype.card ZeroMode)).ne_zero finiteKernelFullIndexSet

/-- Determinant transport preserves the named volume exactly. -/
theorem finiteKernelDeterminantTransport_namedVolume
    {operator : Real → E →L[Real] E}
    (data : FiniteKernelBasisFamilyData operator ZeroMode)
    (first second : Real) :
    finiteKernelDeterminantTransport data first second
        (finiteKernelNamedVolume data first) =
      finiteKernelNamedVolume data second := by
  rw [finiteKernelNamedVolume, finiteKernelNamedVolume,
    exteriorPower.basis_apply, exteriorPower.basis_apply,
    finiteKernelDeterminantTransport,
    exteriorPower.map_apply_ιMulti_family]
  congr 1
  funext mode
  exact data.kernelTransport_basis first second mode

/-- Exterior transport is injective because kernel transport is an equivalence. -/
theorem finiteKernelDeterminantTransport_injective
    {operator : Real → E →L[Real] E}
    (data : FiniteKernelBasisFamilyData operator ZeroMode)
    (first second : Real) :
    Function.Injective (finiteKernelDeterminantTransport data first second) :=
  exteriorPower.map_injective_field
    (data.kernelTransport first second).injective

/-- Identity determinant transport. -/
@[simp]
theorem finiteKernelDeterminantTransport_self
    {operator : Real → E →L[Real] E}
    (data : FiniteKernelBasisFamilyData operator ZeroMode)
    (parameter : Real) :
    finiteKernelDeterminantTransport data parameter parameter = LinearMap.id := by
  unfold finiteKernelDeterminantTransport
  rw [data.kernelTransport_self parameter]
  exact exteriorPower.map_id

/-- Exact composition law of determinant-line transports. -/
theorem finiteKernelDeterminantTransport_trans
    {operator : Real → E →L[Real] E}
    (data : FiniteKernelBasisFamilyData operator ZeroMode)
    (first second third : Real) :
    (finiteKernelDeterminantTransport data second third).comp
        (finiteKernelDeterminantTransport data first second) =
      finiteKernelDeterminantTransport data first third := by
  unfold finiteKernelDeterminantTransport
  rw [← exteriorPower.map_comp]
  congr 1
  have hTransport := congrArg LinearEquiv.toLinearMap
    (data.kernelTransport_trans first second third)
  simpa only [LinearEquiv.coe_trans] using hTransport

/-- Public finite-kernel determinant-line checkpoint. -/
theorem finite_kernel_determinant_line_family_gate
    (operator : Real → E →L[Real] E)
    (data : FiniteKernelBasisFamilyData operator ZeroMode) :
    (∀ parameter,
      Module.finrank Real (FiniteKernelDeterminantFiber data parameter) = 1) ∧
      (∀ parameter, finiteKernelNamedVolume data parameter ≠ 0) ∧
      (∀ first second,
        finiteKernelDeterminantTransport data first second
            (finiteKernelNamedVolume data first) =
          finiteKernelNamedVolume data second) ∧
      (∀ first second third,
        (finiteKernelDeterminantTransport data second third).comp
            (finiteKernelDeterminantTransport data first second) =
          finiteKernelDeterminantTransport data first third) :=
  ⟨finiteKernelDeterminantFiber_finrank_one data,
    finiteKernelNamedVolume_ne_zero data,
    finiteKernelDeterminantTransport_namedVolume data,
    finiteKernelDeterminantTransport_trans data⟩

end
end P0EFTJanusProgramPFiniteKernelDeterminantLineFamily4D
end JanusFormal
