import Mathlib.Analysis.Normed.Operator.Bilinear
import Mathlib.LinearAlgebra.Trace

/-!
# Finite-frame metric dualizer algebra

For a nondegenerate symmetric musical equivalence and a finite family of
vectors, the covariant finite sum

`Σᵢⱼ h(vᵢ,vⱼ) (g(vᵢ,-) ⊗ g(vⱼ,-))`

pairs with `h` by the exact sum of squares of its frame readings.  This is the
fiber algebra behind the remaining smooth throat dualizer.
-/

namespace JanusFormal
namespace P0EFTJanusProgramPFiniteFrameMetricDualizerAlgebra4D

set_option autoImplicit false

noncomputable section

open scoped BigOperators

variable {V : Type*}
  [NormedAddCommGroup V] [NormedSpace Real V]
  [FiniteDimensional Real V]

/-- Covariant rank-one tensor generated by two vectors through a musical
equivalence. -/
def metricCovariantRankOne
    (musical : V ≃L[Real] (V →L[Real] Real))
    (first second : V) :
    V →L[Real] V →L[Real] Real :=
  (musical first).smulRight (musical second)

/-- Symmetrized covariant rank-one tensor. -/
def metricCovariantSymmetricRankOne
    (musical : V ≃L[Real] (V →L[Real] Real))
    (first second : V) :
    V →L[Real] V →L[Real] Real :=
  (1 / 2 : Real) • metricCovariantRankOne musical first second +
    (1 / 2 : Real) • metricCovariantRankOne musical second first

/-- Finite covariant dualizer associated with a tensor and a vector family. -/
def finiteFrameMetricDualizer
    {n : Nat}
    (musical : V ≃L[Real] (V →L[Real] Real))
    (tensor : V →L[Real] V →L[Real] Real)
    (frame : Fin n → V) :
    V →L[Real] V →L[Real] Real :=
  ∑ i, ∑ j,
    tensor (frame i) (frame j) •
      metricCovariantRankOne musical (frame i) (frame j)

/-- Finite dualizer assembled from individually symmetric rank-one terms. -/
def finiteFrameMetricSymmetricDualizer
    {n : Nat}
    (musical : V ≃L[Real] (V →L[Real] Real))
    (tensor : V →L[Real] V →L[Real] Real)
    (frame : Fin n → V) :
    V →L[Real] V →L[Real] Real :=
  ∑ i, ∑ j,
    tensor (frame i) (frame j) •
      metricCovariantSymmetricRankOne musical (frame i) (frame j)

private theorem raised_metricCovariantRankOne
    (musical : V ≃L[Real] (V →L[Real] Real))
    (first second : V) :
    musical.symm.toContinuousLinearMap.comp
        (metricCovariantRankOne musical first second) =
      (musical first).smulRight second := by
  apply ContinuousLinearMap.ext
  intro vector
  simp [metricCovariantRankOne]

private theorem trace_raised_rankOne
    (musical : V ≃L[Real] (V →L[Real] Real))
    (tensor : V →L[Real] V →L[Real] Real)
    (hMusicalSymmetric :
      ∀ first second, musical first second = musical second first)
    (hTensorSymmetric :
      ∀ first second, tensor first second = tensor second first)
    (first second : V) :
    LinearMap.trace Real V
        ((musical.symm.toContinuousLinearMap.comp tensor).toLinearMap *
          (musical.symm.toContinuousLinearMap.comp
            (metricCovariantRankOne musical first second)).toLinearMap) =
      tensor first second := by
  rw [raised_metricCovariantRankOne]
  have hComposition :
      (musical.symm.toContinuousLinearMap.comp tensor).toLinearMap *
          ((musical first).smulRight second).toLinearMap =
        (musical first).toLinearMap.smulRight
          (musical.symm (tensor second)) := by
    apply LinearMap.ext
    intro vector
    simp
  rw [hComposition, LinearMap.trace_smulRight]
  calc
    musical first (musical.symm (tensor second)) =
        musical (musical.symm (tensor second)) first :=
      hMusicalSymmetric first _
    _ = tensor second first := by
      rw [musical.apply_symm_apply]
    _ = tensor first second :=
      (hTensorSymmetric first second).symm

private theorem trace_raised_symmetricRankOne
    (musical : V ≃L[Real] (V →L[Real] Real))
    (tensor : V →L[Real] V →L[Real] Real)
    (hMusicalSymmetric :
      ∀ first second, musical first second = musical second first)
    (hTensorSymmetric :
      ∀ first second, tensor first second = tensor second first)
    (first second : V) :
    LinearMap.trace Real V
        ((musical.symm.toContinuousLinearMap.comp tensor).toLinearMap *
          (musical.symm.toContinuousLinearMap.comp
            (metricCovariantSymmetricRankOne
              musical first second)).toLinearMap) =
      tensor first second := by
  let pairing :
      (V →L[Real] V →L[Real] Real) →ₗ[Real] Real :=
    {
    toFun := fun value =>
      LinearMap.trace Real V
        ((musical.symm.toContinuousLinearMap.comp tensor).toLinearMap *
          (musical.symm.toContinuousLinearMap.comp value).toLinearMap)
    map_add' := by intro left right; simp [map_add, mul_add]
    map_smul' := by intro scalar value; simp [map_smul]
    }
  change pairing
      (metricCovariantSymmetricRankOne musical first second) = _
  unfold metricCovariantSymmetricRankOne
  rw [map_add, map_smul, map_smul]
  change (1 / 2 : Real) *
        LinearMap.trace Real V
          ((musical.symm.toContinuousLinearMap.comp tensor).toLinearMap *
            (musical.symm.toContinuousLinearMap.comp
              (metricCovariantRankOne musical first second)).toLinearMap) +
      (1 / 2 : Real) *
        LinearMap.trace Real V
          ((musical.symm.toContinuousLinearMap.comp tensor).toLinearMap *
            (musical.symm.toContinuousLinearMap.comp
              (metricCovariantRankOne musical second first)).toLinearMap) =
    tensor first second
  rw [trace_raised_rankOne musical tensor
      hMusicalSymmetric hTensorSymmetric,
    trace_raised_rankOne musical tensor
      hMusicalSymmetric hTensorSymmetric,
    hTensorSymmetric second first]
  ring

/-- Exact sum-of-squares identity for the finite-frame covariant dualizer. -/
theorem finiteFrameMetricDualizer_pairing_eq_energy
    {n : Nat}
    (musical : V ≃L[Real] (V →L[Real] Real))
    (tensor : V →L[Real] V →L[Real] Real)
    (frame : Fin n → V)
    (hMusicalSymmetric :
      ∀ first second, musical first second = musical second first)
    (hTensorSymmetric :
      ∀ first second, tensor first second = tensor second first) :
    LinearMap.trace Real V
        ((musical.symm.toContinuousLinearMap.comp tensor).toLinearMap *
          (musical.symm.toContinuousLinearMap.comp
            (finiteFrameMetricDualizer musical tensor frame)).toLinearMap) =
      ∑ i, ∑ j, (tensor (frame i) (frame j)) ^ 2 := by
  let pairing :
      (V →L[Real] V →L[Real] Real) →ₗ[Real] Real :=
    {
    toFun := fun second =>
      LinearMap.trace Real V
        ((musical.symm.toContinuousLinearMap.comp tensor).toLinearMap *
          (musical.symm.toContinuousLinearMap.comp second).toLinearMap)
    map_add' := by
      intro first second
      simp [map_add, mul_add]
    map_smul' := by
      intro scalar second
      simp [map_smul]
    }
  change pairing (finiteFrameMetricDualizer musical tensor frame) = _
  unfold finiteFrameMetricDualizer
  rw [map_sum]
  apply Finset.sum_congr rfl
  intro i _
  rw [map_sum]
  apply Finset.sum_congr rfl
  intro j _
  rw [map_smul]
  change tensor (frame i) (frame j) *
      LinearMap.trace Real V
        ((musical.symm.toContinuousLinearMap.comp tensor).toLinearMap *
          (musical.symm.toContinuousLinearMap.comp
            (metricCovariantRankOne musical (frame i) (frame j))).toLinearMap) =
    (tensor (frame i) (frame j)) ^ 2
  rw [trace_raised_rankOne musical tensor
    hMusicalSymmetric hTensorSymmetric]
  ring

/-- The symmetrized finite dualizer has the same exact sum-of-squares
pairing. -/
theorem finiteFrameMetricSymmetricDualizer_pairing_eq_energy
    {n : Nat}
    (musical : V ≃L[Real] (V →L[Real] Real))
    (tensor : V →L[Real] V →L[Real] Real)
    (frame : Fin n → V)
    (hMusicalSymmetric :
      ∀ first second, musical first second = musical second first)
    (hTensorSymmetric :
      ∀ first second, tensor first second = tensor second first) :
    LinearMap.trace Real V
        ((musical.symm.toContinuousLinearMap.comp tensor).toLinearMap *
          (musical.symm.toContinuousLinearMap.comp
            (finiteFrameMetricSymmetricDualizer
              musical tensor frame)).toLinearMap) =
      ∑ i, ∑ j, (tensor (frame i) (frame j)) ^ 2 := by
  let pairing :
      (V →L[Real] V →L[Real] Real) →ₗ[Real] Real :=
    {
    toFun := fun second =>
      LinearMap.trace Real V
        ((musical.symm.toContinuousLinearMap.comp tensor).toLinearMap *
          (musical.symm.toContinuousLinearMap.comp second).toLinearMap)
    map_add' := by intro first second; simp [map_add, mul_add]
    map_smul' := by intro scalar second; simp [map_smul]
    }
  change pairing
      (finiteFrameMetricSymmetricDualizer musical tensor frame) = _
  unfold finiteFrameMetricSymmetricDualizer
  rw [map_sum]
  apply Finset.sum_congr rfl
  intro i _
  rw [map_sum]
  apply Finset.sum_congr rfl
  intro j _
  rw [map_smul]
  change tensor (frame i) (frame j) *
      LinearMap.trace Real V
        ((musical.symm.toContinuousLinearMap.comp tensor).toLinearMap *
          (musical.symm.toContinuousLinearMap.comp
            (metricCovariantSymmetricRankOne
              musical (frame i) (frame j))).toLinearMap) =
    (tensor (frame i) (frame j)) ^ 2
  rw [trace_raised_symmetricRankOne musical tensor
    hMusicalSymmetric hTensorSymmetric]
  ring

end
end P0EFTJanusProgramPFiniteFrameMetricDualizerAlgebra4D
end JanusFormal
