import JanusFormal.Branches.FundamentalGeometryPVariationalPrinciple.Gates.P0EFTJanusProgramPUnitaryConjugatedMellinZetaFamily4D

/-!
# Actual zeta family generated by one unitary nuclear heat frame

The actual side of a relative spectral atlas should not separately store

* a parameterized nuclear heat family;
* a finite-part family;
* a Mellin continuation family;
* a proof that its connection coefficient vanishes.

One unitarily conjugated nuclear heat family, together with one basepoint
finite-part packet and one basepoint Mellin continuation, determines all of
those objects.
-/

namespace JanusFormal
namespace P0EFTJanusProgramPUnitaryActualZetaFamily4D

set_option autoImplicit false
noncomputable section

open P0EFTJanusCircleDiracHeatTraceCancellation
open P0EFTJanusProgramPRelativeHeatFinitePartDeterminant4D
open P0EFTJanusProgramPRelativeHeatMellinZetaContinuation4D
open P0EFTJanusProgramPRelativeHeatMellinZetaFamily4D
open P0EFTJanusProgramPRelativeZetaDeterminantConnection4D
open P0EFTJanusProgramPUnitaryConjugatedNuclearTraceFamily4D
open P0EFTJanusProgramPUnitaryConjugatedMellinZetaFamily4D

variable {E : Type*}
  [NormedAddCommGroup E] [InnerProductSpace Real E]

/-- Complete actual spectral family generated at one unitary basepoint. -/
structure UnitaryActualZetaFamilyData where
  heat : UnitaryConjugatedNuclearTraceFamilyData
    (Parameter := Real) (Time := HeatTime) (E := E)
  baseFinitePart : RelativeHeatFinitePartData heat.baseTrace
  baseContinuation : RelativeHeatMellinZetaContinuationData baseFinitePart

namespace UnitaryActualZetaFamilyData

/-- Parameterized actual zeta family generated from the unitary heat family. -/
def family
    (data : UnitaryActualZetaFamilyData (E := E)) :
    RelativeHeatMellinZetaFamilyData :=
  data.heat.transportedMellinZetaFamily data.baseFinitePart
    data.baseContinuation

/-- The actual zeta connection coefficient vanishes in the unitary frame. -/
theorem connectionCoefficient_zero
    (data : UnitaryActualZetaFamilyData (E := E))
    (parameter : Real) :
    relativeZetaConnectionCoefficient data.family.toZetaFamily parameter = 0 :=
  data.heat.transportedMellinZetaFamily_connectionCoefficient_zero
    data.baseFinitePart data.baseContinuation parameter

/-- The actual regularized derivative at zero is constant. -/
theorem zetaPrimeAtZero_eq_base
    (data : UnitaryActualZetaFamilyData (E := E))
    (parameter : Real) :
    data.family.zetaPrimeAtZero parameter =
      data.baseContinuation.derivativeAtZero :=
  data.heat.transportedMellinZetaFamily_zetaPrimeAtZero
    data.baseFinitePart data.baseContinuation parameter

/-- The actual finite-part logarithm is the basepoint logarithm. -/
theorem finitePartLogDeterminant_eq_base
    (data : UnitaryActualZetaFamilyData (E := E))
    (parameter : Real) :
    relativeHeatFinitePartLogDeterminant
        (data.family.finitePartFamily.finitePart parameter) =
      relativeHeatFinitePartLogDeterminant data.baseFinitePart :=
  data.heat.transportedFinitePart_logDeterminant data.baseFinitePart parameter

/-- The actual zeta determinant is constant. -/
theorem determinant_eq_base
    (data : UnitaryActualZetaFamilyData (E := E))
    (parameter : Real) :
    relativeHeatMellinZetaFamilyDeterminant data.family parameter =
      relativeHeatMellinZetaDeterminant data.baseContinuation :=
  data.heat.transportedMellinZetaFamily_determinant_eq_base
    data.baseFinitePart data.baseContinuation parameter

/-- Public unitary actual-zeta checkpoint. -/
theorem unitary_actual_zeta_family_gate
    (data : UnitaryActualZetaFamilyData (E := E)) :
    (∀ parameter,
      relativeZetaConnectionCoefficient data.family.toZetaFamily parameter = 0) ∧
    (∀ parameter,
      data.family.zetaPrimeAtZero parameter =
        data.baseContinuation.derivativeAtZero) ∧
    (∀ parameter,
      relativeHeatMellinZetaFamilyDeterminant data.family parameter =
        relativeHeatMellinZetaDeterminant data.baseContinuation) :=
  ⟨data.connectionCoefficient_zero,
    data.zetaPrimeAtZero_eq_base,
    data.determinant_eq_base⟩

end UnitaryActualZetaFamilyData

end
end P0EFTJanusProgramPUnitaryActualZetaFamily4D
end JanusFormal
