import JanusFormal.Branches.FundamentalGeometryPVariationalPrinciple.Gates.P0EFTJanusMappingTorusCanonicalPhysicalScalarCanonicalCauchyClosedBoundary4D
import JanusFormal.Branches.FundamentalGeometryPVariationalPrinciple.Gates.P0EFTJanusMappingTorusCanonicalPhysicalScalarCauchyClosedAnalyticClosure4D

/-!
# Canonical Cauchy-closed physical scalar analytic realization

This is the canonical-core specialization of the Cauchy-closed analytic
frontier.  The arbitrary value and normal core parameters disappear.  The
boundary Hilbert pair is generated by the canonical smooth periodic and
antiperiodic latitude representatives.

After the canonical boundary data are supplied, only three analytic fields
remain:

* smooth approximation of adjoint graph pairs;
* coercivity of one shifted form;
* compact approximation of the physical `H¹ -> L²` inclusion.
-/

namespace JanusFormal
namespace P0EFTJanusMappingTorusCanonicalPhysicalScalarCanonicalCauchyClosedAnalytic4D

set_option autoImplicit false
noncomputable section

open Set Topology Module End
open P0EFTJanusMappingTorusCanonicalLatitudeSmoothBoundaryCores4D
open P0EFTJanusMappingTorusCanonicalPhysicalScalarFirstSheetHilbertTrace4D
open P0EFTJanusMappingTorusCanonicalPhysicalScalarCanonicalCauchyClosedBoundary4D
open P0EFTJanusMappingTorusCanonicalPhysicalScalarCauchyClosedAnalyticClosure4D
open P0EFTJanusMappingTorusCanonicalPhysicalScalarRellichApproximation4D
open P0EFTJanusMappingTorusScalarHilbertBoundarySymplectic4D
open P0EFTJanusMappingTorusScalarCompletedBoundaryTripleAdjointGraphRegularity4D
open P0EFTJanusMappingTorusScalarCompletedBoundaryTripleShiftedForm4D

universe r

variable (period : Real) (hPeriod : period ≠ 0)
variable {Regularity : Type r}
  [NormedAddCommGroup Regularity] [NormedSpace Real Regularity]
  [CompleteSpace Regularity]

private abbrev ValueCore :=
  CanonicalLatitudeSmoothPeriodicValueCore period
private abbrev NormalCore :=
  CanonicalLatitudeSmoothAntiperiodicNormalCore period
private abbrev BoundaryL2 := CanonicalPhysicalScalarFirstSheetL2 period

/-- Canonical-core physical scalar analytic data. -/
structure CanonicalPhysicalScalarCanonicalCauchyClosedAnalyticData
    (massSquared : Real) where
  boundary : CanonicalPhysicalScalarCanonicalCauchyClosedBoundaryData
    period hPeriod massSquared (Regularity := Regularity)
  condition : CanonicalScalarHilbertLagrangianBoundaryCondition
    (BoundaryL2 period)
  adjointApproximation : boundary.triple.AdjointPairSmoothApproximationData
    condition
  referenceParameter : Real
  shiftedFormCoercive : boundary.triple.LagrangianShiftedFormCoerciveData
    condition referenceParameter
  rellichApproximation : CanonicalPhysicalScalarRellichApproximationData
    period hPeriod

namespace CanonicalPhysicalScalarCanonicalCauchyClosedAnalyticData

/-- Conversion to the general Cauchy-closed analytic package. -/
def toCauchyClosedAnalyticData
    (analytic : CanonicalPhysicalScalarCanonicalCauchyClosedAnalyticData
      period hPeriod massSquared (Regularity := Regularity)) :
    CanonicalPhysicalScalarCauchyClosedAnalyticData
      period hPeriod massSquared (ValueCore period) (NormalCore period)
      (Regularity := Regularity) where
  boundary := analytic.boundary.toCauchyClosedBoundaryData
  condition := analytic.condition
  adjointApproximation := analytic.adjointApproximation
  referenceParameter := analytic.referenceParameter
  shiftedFormCoercive := analytic.shiftedFormCoercive
  rellichApproximation := analytic.rellichApproximation

/-- Actual physical Hilbert self-adjointness. -/
theorem actualAdjointDomain_eq
    (analytic : CanonicalPhysicalScalarCanonicalCauchyClosedAnalyticData
      period hPeriod massSquared (Regularity := Regularity)) :
    analytic.boundary.triple.actualAdjointDomain analytic.condition =
      analytic.boundary.triple.realizationDomain analytic.condition :=
  analytic.toCauchyClosedAnalyticData.actualAdjointDomain_eq
    period hPeriod

/-- Compact physical reference resolvent. -/
noncomputable def compactResolvent
    (analytic : CanonicalPhysicalScalarCanonicalCauchyClosedAnalyticData
      period hPeriod massSquared (Regularity := Regularity)) :=
  analytic.toCauchyClosedAnalyticData.compactResolvent period hPeriod

/-- Physical Fredholm alternative. -/
theorem fredholmAlternative
    (analytic : CanonicalPhysicalScalarCanonicalCauchyClosedAnalyticData
      period hPeriod massSquared (Regularity := Regularity))
    (spectralParameter : Real)
    (hParameter : spectralParameter ≠ analytic.referenceParameter) :
    analytic.boundary.triple.LagrangianHasEigenvalue
        analytic.condition spectralParameter ∨
      analytic.boundary.triple.LagrangianResolventPoint
        analytic.condition spectralParameter :=
  analytic.toCauchyClosedAnalyticData.fredholmAlternative
    period hPeriod spectralParameter hParameter

/-- Lower spectral bound. -/
theorem eigenvalue_ge_referenceParameter
    (analytic : CanonicalPhysicalScalarCanonicalCauchyClosedAnalyticData
      period hPeriod massSquared (Regularity := Regularity))
    (eigenvalue : Real)
    (hEigenvalue : analytic.boundary.triple.LagrangianHasEigenvalue
      analytic.condition eigenvalue) :
    analytic.referenceParameter ≤ eigenvalue :=
  analytic.toCauchyClosedAnalyticData.eigenvalue_ge_referenceParameter
    period hPeriod eigenvalue hEigenvalue

/-- Spectral completeness of the compact reference resolvent. -/
theorem spectral_complete
    (analytic : CanonicalPhysicalScalarCanonicalCauchyClosedAnalyticData
      period hPeriod massSquared (Regularity := Regularity)) :
    (⨆ eigenvalue : Real,
      Module.End.eigenspace
        ((analytic.compactResolvent period hPeriod).bounded.ambientResolvent
          analytic.boundary.triple analytic.condition
            analytic.referenceParameter).toLinearMap eigenvalue)ᗮ = ⊥ :=
  analytic.toCauchyClosedAnalyticData.spectral_complete period hPeriod

/-- Canonical analytic certificate. -/
theorem certificate
    (analytic : CanonicalPhysicalScalarCanonicalCauchyClosedAnalyticData
      period hPeriod massSquared (Regularity := Regularity)) :
    DenseRange (canonicalLatitudeSmoothPeriodicValueEmbedding period) ∧
      DenseRange (canonicalLatitudeSmoothAntiperiodicNormalEmbedding period) ∧
      analytic.boundary.triple.actualAdjointDomain analytic.condition =
        analytic.boundary.triple.realizationDomain analytic.condition ∧
      IsCompactOperator
        (P0EFTJanusMappingTorusCanonicalPhysicalBulkL2H1Bridge4D.canonicalPhysicalScalarH1ToBulkL2
          period hPeriod) ∧
      (∀ spectralParameter : Real,
        spectralParameter ≠ analytic.referenceParameter →
          analytic.boundary.triple.LagrangianHasEigenvalue
              analytic.condition spectralParameter ∨
            analytic.boundary.triple.LagrangianResolventPoint
              analytic.condition spectralParameter) :=
  ⟨analytic.boundary.core.boundaryDensity.valueDense,
    analytic.boundary.core.boundaryDensity.normalDense,
    analytic.actualAdjointDomain_eq period hPeriod,
    analytic.rellichApproximation.rellich,
    analytic.fredholmAlternative period hPeriod⟩

end CanonicalPhysicalScalarCanonicalCauchyClosedAnalyticData

end
end P0EFTJanusMappingTorusCanonicalPhysicalScalarCanonicalCauchyClosedAnalytic4D
end JanusFormal
