import JanusFormal.Branches.FundamentalGeometryPVariationalPrinciple.Gates.P0EFTJanusProgramPGlobalEulerLagrangeFaithfulAugmentedSixAggregateBoundRieszResidual4D
import JanusFormal.Branches.FundamentalGeometryPVariationalPrinciple.Gates.P0EFTJanusProgramPGlobalCandidateACanonicalSixDenseCore4D

/-!
# Canonical-six full Euler--Riesz residual

The six non-Robin forms are the genuine Candidate-A chart Hessians. Exact H10
Robin agreement and one graph-norm bound for the core-to-chart map construct
the full seven-block extension and strong Euler residual.
-/

namespace JanusFormal
namespace P0EFTJanusProgramPGlobalEulerLagrangeCanonicalSixDenseCoreRieszResidual4D

set_option autoImplicit false
set_option synthInstance.maxHeartbeats 1600000

noncomputable section

open Set Topology MeasureTheory
open scoped Manifold ContDiff InnerProductSpace
open P0EFTJanusMappingTorusQuotient
open P0EFTJanusMappingTorusSmoothAtlasFrontier
open P0EFTJanusMappingTorusSmoothQuotientManifold
open P0EFTJanusProgramPGlobalFieldSpace4D
open P0EFTJanusProgramPGlobalTypedNonminimalFieldSpace4D
open P0EFTJanusProgramPGlobalCovariantAction4D
open P0EFTJanusProgramPGlobalAnalysisDomain4D
open P0EFTJanusProgramPGlobalLocalVariationalChart4D
open P0EFTJanusProgramPGlobalCandidateAAbelianGaugeFixedAction4D
open P0EFTJanusProgramPGlobalCandidateADiagonalExtendedBulkGraphC2Chart4D
open P0EFTJanusProgramPGlobalCandidateADiagonalExtendedBulkL2Riesz4D
open P0EFTJanusProgramPGlobalCandidateAMatterLLSameActionClosure4D
open P0EFTJanusProgramPGlobalCandidateACommonAugmentedAnalyticDomain4D
open P0EFTJanusProgramPGlobalCandidateAMinimalPhysicalLocalHessianBridge4D
open P0EFTJanusProgramPGlobalCandidateACanonicalSixDenseCore4D
open P0EFTJanusProgramPGlobalCandidateASixPhysicalAggregateBound4D
open P0EFTJanusProgramPGlobalCandidateASevenPhysicalBlockBounds4D
open P0EFTJanusProgramPDenseCoreChartBilinearBound4D
open P0EFTJanusProgramPGlobalEulerLagrangeFaithfulAugmentedRieszResidual4D
open P0EFTJanusProgramPGlobalEulerLagrangeFaithfulAugmentedSixAggregateBoundRieszResidual4D

variable (period : Real) (hPeriod : period ≠ 0)

private abbrev EffectiveQuotient :=
  MappingTorus (reflectedSphereData period hPeriod)

local instance effectiveQuotientChartedSpace :
    ChartedSpace CoverModel (EffectiveQuotient period hPeriod) :=
  reflectedSphereQuotientChartedSpace period hPeriod

local instance effectiveQuotientIsManifold :
    IsManifold coverModelWithCorners ω
      (EffectiveQuotient period hPeriod) :=
  reflectedSphereQuotient_isManifold period hPeriod

local instance effectiveQuotientMeasurableSpace :
    MeasurableSpace (EffectiveQuotient period hPeriod) := borel _

local instance effectiveQuotientBorelSpace :
    BorelSpace (EffectiveQuotient period hPeriod) where
  measurable_eq := rfl

attribute [local instance]
  GlobalCandidateALocalVariationalChart.normedAddCommGroup
  GlobalCandidateALocalVariationalChart.normedSpace

section

variable {couplings : GlobalCandidateAActionCouplings}
variable {NonNullFace NullFace : Type*}
variable [Fintype NonNullFace] [Fintype NullFace]
variable {measure : Measure (EffectiveQuotient period hPeriod)}
variable (configuration : GlobalGaugeFixedFieldConfiguration period hPeriod)
variable (data : GlobalCandidateAActionData period hPeriod
  configuration.physical couplings NonNullFace NullFace)
variable (analysis : GlobalAnalysisData period hPeriod configuration.physical)
variable (chart : GlobalCandidateALocalVariationalChart period hPeriod
  couplings NonNullFace NullFace measure)
variable (sameAction : ProgramPGlobalMinimalPhysicalLocalMatterLLSameActionBridge4D
  period hPeriod configuration data analysis chart)
variable (einsteinScale : Real)
variable (robin : GlobalCandidateAH10RobinDenseCoreAgreement4D period hPeriod
  configuration data analysis chart sameAction einsteinScale)
variable (chartBound : DenseCoreChartMapBound
  (globalCandidateASevenPhysicalCoreEmbedding period hPeriod configuration data
    analysis)
  (globalCandidateACanonicalSixCoreToChart period hPeriod configuration data
    analysis chart sameAction))

/-- The sole six-block estimate, derived from the six genuine chart Hessians. -/
def globalCandidateACanonicalSixDenseCoreBound :
    GlobalCandidateASixPhysicalAggregateCoreBound4D period hPeriod
      configuration data analysis chart sameAction einsteinScale :=
  globalCandidateASixPhysicalAggregateBound_of_canonicalDenseCore period
    hPeriod configuration data analysis chart sameAction einsteinScale robin
      chartBound

/-- Canonical seven-block extension generated by that estimate. -/
def globalCandidateACanonicalSixDenseCorePhysicalExtension :
    GlobalCandidateASevenPhysicalCommonDomainExtension4D period hPeriod
      configuration data analysis chart sameAction :=
  globalCandidateAFaithfulAugmentedSixAggregateBoundPhysicalExtension period
    hPeriod configuration data analysis chart sameAction einsteinScale
      (globalCandidateACanonicalSixDenseCoreBound period hPeriod configuration
        data analysis chart sameAction einsteinScale robin chartBound)

/-- Full augmented action with the six physical forms fixed canonically. -/
def globalCandidateACanonicalSixDenseCoreAugmentedAction
    (state : CommonAugmentedHilbert period hPeriod configuration data analysis) :
    Real :=
  globalCandidateACommonAugmentedAction period hPeriod configuration data
    analysis chart sameAction
      (globalCandidateACanonicalSixDenseCorePhysicalExtension period hPeriod
        configuration data analysis chart sameAction einsteinScale robin
          chartBound) state

/-- Strong residual of the canonical-six augmented action. -/
def globalCandidateACanonicalSixDenseCoreRieszResidual
    (state : CommonAugmentedHilbert period hPeriod configuration data analysis) :
    CommonAugmentedHilbert period hPeriod configuration data analysis :=
  globalCandidateAFaithfulAugmentedRieszResidual period hPeriod configuration
    data analysis chart sameAction
      (globalCandidateACanonicalSixDenseCorePhysicalExtension period hPeriod
        configuration data analysis chart sameAction einsteinScale robin
          chartBound) state

/-- Stationarity of the canonical-six augmented action is exactly its strong
Riesz equation. -/
theorem globalCandidateACanonicalSixDenseCoreEulerCovector_eq_zero_iff_rieszResidual
    (state : CommonAugmentedHilbert period hPeriod configuration data analysis) :
    fderiv Real
        (globalCandidateACanonicalSixDenseCoreAugmentedAction period hPeriod
          configuration data analysis chart sameAction einsteinScale robin
            chartBound) state = 0 ↔
      globalCandidateACanonicalSixDenseCoreRieszResidual period hPeriod
        configuration data analysis chart sameAction einsteinScale robin
          chartBound state = 0 := by
  unfold globalCandidateACanonicalSixDenseCoreAugmentedAction
  unfold globalCandidateACanonicalSixDenseCoreRieszResidual
  exact
    globalCandidateAFaithfulAugmentedEulerCovector_eq_zero_iff_rieszResidual
      period hPeriod configuration data analysis chart sameAction
        (globalCandidateACanonicalSixDenseCorePhysicalExtension period hPeriod
          configuration data analysis chart sameAction einsteinScale robin
            chartBound) state

/-- On the dense core, the canonical-six residual is the true local
gauge-fixed Candidate-A Hessian. -/
theorem globalCandidateACanonicalSixDenseCoreRieszResidual_smooth_pairing
    (first second : GlobalCandidateADiagonalExtendedBulkSmoothCore period
      hPeriod analysis) :
    globalCandidateAFaithfulAugmentedRieszResidualPairing period hPeriod
        configuration data analysis
        (globalCandidateACanonicalSixDenseCoreRieszResidual period hPeriod
          configuration data analysis chart sameAction einsteinScale robin
            chartBound
            (diagonalExtendedBulkL2SmoothEmbedding period hPeriod
              (globalCandidateAMetricBySector period hPeriod data)
              couplings.matterMassSquared data analysis first))
        (diagonalExtendedBulkL2SmoothEmbedding period hPeriod
          (globalCandidateAMetricBySector period hPeriod data)
          couplings.matterMassSquared data analysis second) =
      diagonalExtendedBulkMinimalPhysicalLocalGaugeFixedHessianOnCore period
        hPeriod configuration data analysis chart sameAction.chartBridge first
          second := by
  simpa only [globalCandidateACanonicalSixDenseCoreRieszResidual] using
    globalCandidateAFaithfulAugmentedRieszResidual_smooth_pairing period
      hPeriod configuration data analysis chart sameAction
        (globalCandidateACanonicalSixDenseCorePhysicalExtension period hPeriod
          configuration data analysis chart sameAction einsteinScale robin
            chartBound) first second

end

end
end P0EFTJanusProgramPGlobalEulerLagrangeCanonicalSixDenseCoreRieszResidual4D
end JanusFormal
