import JanusFormal.Branches.FundamentalGeometryPVariationalPrinciple.Gates.P0EFTJanusProgramPSelfAdjointFredholmDeterminantNamedFrame4D
import JanusFormal.Branches.FundamentalGeometryPVariationalPrinciple.Gates.P0EFTJanusProgramPFiniteKernelZetaFredholmDeterminant4D

/-!
# Named zeta coordinate on an actual self-adjoint Fredholm determinant line

A self-adjoint gapped family has an actual real Fredholm determinant fibre

`Hom(det coker H_a, det ker H_a)`

and a canonical frame induced by `coker H_a ≃ ker H_a`.  Pulling the named
kernel volume backwards fixes a nonzero named source volume.  The frame sends
that source volume exactly to the named kernel volume.

A reduced zeta family then supplies the complex scalar multiplying this
normalized real frame.  In the named coordinate the full scalar is exactly the
reduced zeta determinant and its connection is exactly the reduced zeta
connection.

This file joins the real Fredholm frame and the complex scalar at the level of
normalized coordinates.  It still does not identify the complexification of
the real Fredholm line with a separately constructed analytic Quillen line;
that geometric comparison remains explicit.
-/

namespace JanusFormal
namespace P0EFTJanusProgramPSelfAdjointFredholmZetaNamedCoordinate4D

set_option autoImplicit false
set_option maxHeartbeats 4200000
set_option synthInstance.maxHeartbeats 2100000

noncomputable section

open P0EFTJanusProgramPFiniteKernelDeterminantLineFamily4D
open P0EFTJanusProgramPSelfAdjointFredholmDeterminantLineFamily4D
open P0EFTJanusProgramPSelfAdjointFredholmDeterminantNamedFrame4D
open P0EFTJanusProgramPFiniteKernelZetaFredholmDeterminant4D
open P0EFTJanusProgramPSplitFredholmDeterminantFrameAtlas4D
open P0EFTJanusProgramPSplitFredholmDeterminantFrameConnection4D
open P0EFTJanusProgramPRelativeZetaDeterminantConnection4D

variable {E ZeroMode : Type*}
  [NormedAddCommGroup E] [NormedSpace Real E]
  [InnerProductSpace Real E] [CompleteSpace E]
  [Fintype ZeroMode] [DecidableEq ZeroMode] [LinearOrder ZeroMode]

/-- Actual Fredholm determinant family and the reduced zeta family attached to
its invertible complement. -/
structure SelfAdjointFredholmZetaNamedCoordinateData
    (operator : Real → E →L[Real] E)
    (ZeroMode : Type*) [Fintype ZeroMode] [DecidableEq ZeroMode]
    [LinearOrder ZeroMode] where
  fredholm : SelfAdjointFredholmDeterminantFamilyData operator ZeroMode
  zetaFamily : RelativeZetaDeterminantFamilyData

namespace SelfAdjointFredholmZetaNamedCoordinateData

/-- The split finite-kernel/reduced-zeta packet generated by the same data. -/
def split
    {operator : Real → E →L[Real] E}
    (data : SelfAdjointFredholmZetaNamedCoordinateData operator ZeroMode) :=
  finiteKernelZetaSplitDeterminant operator data.fredholm.kernels
    data.zetaFamily

/-- Named complex coordinate of the full Fredholm determinant section. -/
def fullCoordinate
    {operator : Real → E →L[Real] E}
    (data : SelfAdjointFredholmZetaNamedCoordinateData operator ZeroMode)
    (parameter : Real) : Complex :=
  relativeZetaDeterminantCoordinate data.zetaFamily parameter

/-- Ordinary derivative of the named full coordinate. -/
def fullCoordinateDerivative
    {operator : Real → E →L[Real] E}
    (data : SelfAdjointFredholmZetaNamedCoordinateData operator ZeroMode)
    (parameter : Real) : Complex :=
  relativeZetaDeterminantCoordinateDerivative data.zetaFamily parameter

/-- The actual real Fredholm frame sends the named cokernel volume to the named
kernel volume. -/
theorem frame_on_namedVolume
    {operator : Real → E →L[Real] E}
    (data : SelfAdjointFredholmZetaNamedCoordinateData operator ZeroMode)
    (parameter : Real) :
    data.fredholm.determinantFrame parameter
        (cokernelNamedVolume data.fredholm parameter) =
      finiteKernelNamedVolume data.fredholm.kernels parameter :=
  data.fredholm.determinantFrame_cokernelNamedVolume parameter

/-- The named source volume is nonzero. -/
theorem sourceVolume_ne_zero
    {operator : Real → E →L[Real] E}
    (data : SelfAdjointFredholmZetaNamedCoordinateData operator ZeroMode)
    (parameter : Real) :
    cokernelNamedVolume data.fredholm parameter ≠ 0 :=
  data.fredholm.cokernelNamedVolume_ne_zero parameter

/-- The named target volume is nonzero. -/
theorem targetVolume_ne_zero
    {operator : Real → E →L[Real] E}
    (data : SelfAdjointFredholmZetaNamedCoordinateData operator ZeroMode)
    (parameter : Real) :
    finiteKernelNamedVolume data.fredholm.kernels parameter ≠ 0 :=
  data.fredholm.kernels.finiteKernelNamedVolume_ne_zero parameter

/-- The named full complex coordinate is nonzero. -/
theorem fullCoordinate_ne_zero
    {operator : Real → E →L[Real] E}
    (data : SelfAdjointFredholmZetaNamedCoordinateData operator ZeroMode)
    (parameter : Real) :
    data.fullCoordinate parameter ≠ 0 :=
  relativeZetaDeterminantCoordinate_ne_zero data.zetaFamily parameter

/-- The named full coordinate is the actual derivative coordinate of the same
zeta family. -/
theorem fullCoordinate_hasDerivAt
    {operator : Real → E →L[Real] E}
    (data : SelfAdjointFredholmZetaNamedCoordinateData operator ZeroMode)
    (parameter : Real) :
    HasDerivAt data.fullCoordinate
      (data.fullCoordinateDerivative parameter) parameter :=
  relativeZetaDeterminantCoordinate_hasDerivAt data.zetaFamily parameter

/-- Connection in the named Fredholm frame. -/
def connectionAt
    {operator : Real → E →L[Real] E}
    (data : SelfAdjointFredholmZetaNamedCoordinateData operator ZeroMode)
    (parameter : Real) (value derivative : Complex) : Complex :=
  relativeZetaConnectionAt data.zetaFamily parameter value derivative

/-- The full normalized Fredholm determinant coordinate is parallel. -/
theorem fullCoordinate_parallel
    {operator : Real → E →L[Real] E}
    (data : SelfAdjointFredholmZetaNamedCoordinateData operator ZeroMode)
    (parameter : Real) :
    data.connectionAt parameter
        (data.fullCoordinate parameter)
        (data.fullCoordinateDerivative parameter) = 0 :=
  relativeZetaDeterminantCoordinate_parallel data.zetaFamily parameter

/-- The canonical split named-frame construction computes the same full
coordinate definitionally. -/
theorem split_namedFrame_eq_fullCoordinate
    {operator : Real → E →L[Real] E}
    (data : SelfAdjointFredholmZetaNamedCoordinateData operator ZeroMode)
    (parameter : Real) :
    (finiteKernelZetaNamedFrameAtlas operator data.fredholm.kernels
      data.zetaFamily).localDeterminant () parameter =
      data.fullCoordinate parameter :=
  finiteKernelZetaNamedFrame_localDeterminant operator data.fredholm.kernels
    data.zetaFamily parameter

/-- Complete normalization certificate joining the true real Fredholm line to
its complex reduced-zeta coordinate. -/
structure SelfAdjointFredholmZetaNamedCoordinateCertificate
    {operator : Real → E →L[Real] E}
    (data : SelfAdjointFredholmZetaNamedCoordinateData operator ZeroMode) : Prop where
  line_finrank_one : ∀ parameter,
    Module.finrank Real (data.fredholm.determinantLine parameter) = 1
  sourceVolume_nonzero : ∀ parameter,
    cokernelNamedVolume data.fredholm parameter ≠ 0
  targetVolume_nonzero : ∀ parameter,
    finiteKernelNamedVolume data.fredholm.kernels parameter ≠ 0
  frame_normalized : ∀ parameter,
    data.fredholm.determinantFrame parameter
        (cokernelNamedVolume data.fredholm parameter) =
      finiteKernelNamedVolume data.fredholm.kernels parameter
  coordinate_nonzero : ∀ parameter,
    data.fullCoordinate parameter ≠ 0
  coordinate_derivative : ∀ parameter,
    HasDerivAt data.fullCoordinate
      (data.fullCoordinateDerivative parameter) parameter
  coordinate_parallel : ∀ parameter,
    data.connectionAt parameter
        (data.fullCoordinate parameter)
        (data.fullCoordinateDerivative parameter) = 0
  split_agreement : ∀ parameter,
    (finiteKernelZetaNamedFrameAtlas operator data.fredholm.kernels
      data.zetaFamily).localDeterminant () parameter =
      data.fullCoordinate parameter

/-- Build the normalized Fredholm/zeta coordinate certificate. -/
def certificate
    {operator : Real → E →L[Real] E}
    (data : SelfAdjointFredholmZetaNamedCoordinateData operator ZeroMode) :
    SelfAdjointFredholmZetaNamedCoordinateCertificate data where
  line_finrank_one := data.fredholm.determinantLine_finrank_one
  sourceVolume_nonzero := data.sourceVolume_ne_zero
  targetVolume_nonzero := data.targetVolume_ne_zero
  frame_normalized := data.frame_on_namedVolume
  coordinate_nonzero := data.fullCoordinate_ne_zero
  coordinate_derivative := data.fullCoordinate_hasDerivAt
  coordinate_parallel := data.fullCoordinate_parallel
  split_agreement := data.split_namedFrame_eq_fullCoordinate

/-- Public actual-Fredholm-line plus zeta-coordinate checkpoint. -/
theorem self_adjoint_fredholm_zeta_named_coordinate_gate
    (operator : Real → E →L[Real] E)
    (data : SelfAdjointFredholmZetaNamedCoordinateData operator ZeroMode) :
    SelfAdjointFredholmZetaNamedCoordinateCertificate data :=
  data.certificate

end SelfAdjointFredholmZetaNamedCoordinateData

end
end P0EFTJanusProgramPSelfAdjointFredholmZetaNamedCoordinate4D
end JanusFormal
