import JanusFormal.Branches.FundamentalGeometryPVariationalPrinciple.Gates.P0EFTJanusProgramPCandidateAFiveSectorCrossFormPhysicalSmallness4D
import JanusFormal.Branches.FundamentalGeometryPVariationalPrinciple.Gates.P0EFTJanusProgramPQuadraticGardingOperatorLowerBound4D

/-!
# Candidate-A operator lower bound from the finite cross-form margin

This file turns the explicit total quadratic margin into the operator estimate
used by the Fredholm layer.  The only bridge is the Cauchy--Schwarz upper bound
for the actual Hessian energy.
-/

namespace JanusFormal
namespace P0EFTJanusProgramPCandidateAFiveSectorCrossFormOperatorGarding4D

set_option autoImplicit false
noncomputable section

open P0EFTJanusProgramPCandidateAFiveSectorCrossFormPhysicalSmallness4D
open P0EFTJanusProgramPQuadraticGardingOperatorLowerBound4D

variable {E : Type*}
  [NormedAddCommGroup E] [NormedSpace Real E]

/-- Finite Candidate-A margin identified with the quadratic energy of one
bounded Hessian operator. -/
structure CandidateAFiveSectorCrossFormOperatorGardingData
    (operator : E →L[Real] E) where
  finiteMargin : CandidateAFiveSectorCrossFormPhysicalSmallnessData (E := E)
  energy_upper : ∀ vector,
    finiteMargin.totalEnergy vector ≤ ‖vector‖ * ‖operator vector‖

namespace CandidateAFiveSectorCrossFormOperatorGardingData

/-- Generic quadratic-to-operator packet. -/
def toQuadraticGardingOperatorData
    {operator : E →L[Real] E}
    (data : CandidateAFiveSectorCrossFormOperatorGardingData operator) :
    QuadraticGardingOperatorData operator where
  margin := data.finiteMargin.margin
  margin_pos :=
    data.finiteMargin
      |>.candidateA_five_sector_cross_form_physical_smallness_gate |>.1
  energy := data.finiteMargin.totalEnergy
  energy_lower :=
    data.finiteMargin
      |>.candidateA_five_sector_cross_form_physical_smallness_gate |>.2
  energy_upper := data.energy_upper

/-- Explicit H12-style lower bound for the actual operator. -/
theorem lowerBound
    {operator : E →L[Real] E}
    (data : CandidateAFiveSectorCrossFormOperatorGardingData operator)
    (vector : E) :
    data.finiteMargin.margin * ‖vector‖ ≤ ‖operator vector‖ :=
  data.toQuadraticGardingOperatorData.lowerBound vector

/-- The zero-mode-free restriction is injective without a separate proof. -/
theorem injective
    {operator : E →L[Real] E}
    (data : CandidateAFiveSectorCrossFormOperatorGardingData operator) :
    Function.Injective operator :=
  data.toQuadraticGardingOperatorData.injective

/-- Public Candidate-A operator checkpoint generated by the finite margin. -/
theorem candidateA_five_sector_cross_form_operator_garding_gate
    (operator : E →L[Real] E)
    (data : CandidateAFiveSectorCrossFormOperatorGardingData operator) :
    (∀ vector,
      data.finiteMargin.margin * ‖vector‖ ≤ ‖operator vector‖) ∧
      Function.Injective operator :=
  ⟨data.lowerBound, data.injective⟩

end CandidateAFiveSectorCrossFormOperatorGardingData

end
end P0EFTJanusProgramPCandidateAFiveSectorCrossFormOperatorGarding4D
end JanusFormal
