import JanusFormal.Branches.FundamentalGeometryPVariationalPrinciple.Gates.P0EFTJanusMatterCurvatureFLRWConstraintBranch

/-!
# Dust FLRW constrained tangent and second variation

At the exact positive-dust witness, this gate computes the common kernel of
the two primary covectors and the secondary covector.  The kernel is exactly
one-dimensional, generated by `(2,1,2,1)`.

For equal fixed lapses, the actual ambient Hessian of the displayed reduced
Hamiltonian is negative on that generator.  The affine line used for this
Hessian leaves the primary constraint surface at second order.  An explicit
nonlinear curve with the same tangent remains on all three constraints, and
the constrained Hamiltonian and its second variation vanish along it.  Thus
the negative ambient number is not by itself a reduced stability, ADM, ghost,
or covariant conclusion.
-/

namespace JanusFormal
namespace P0EFTJanusDustFLRWConstrainedStability

set_option autoImplicit false

noncomputable section

open P0EFTJanusReducedFLRWSecondaryConstraint
open P0EFTJanusPTFlatVacuumFLRWConstraintNoGo
open P0EFTJanusMatterCurvatureFLRWConstraintBranch
open Filter Topology

/-- Unambiguous local copy of the matter-supported witness parameters. -/
def dustParameters : MatterCurvatureParameters :=
  { base := ptFlatParameters 1 0 1 1 1
    dustPlus := 1 / 12
    dustMinus := 1 / 12
    curvaturePlus := 0
    curvatureMinus := 0 }

/-- Unambiguous local copy of the matter-supported witness point. -/
def dustPoint : PhasePoint :=
  { aPlus := 1, pPlus := 1, aMinus := 1, pMinus := 1 }

theorem dustParameters_eq_imported_witness :
    dustParameters =
      P0EFTJanusMatterCurvatureFLRWConstraintBranch.witnessParameters := rfl

theorem dustPoint_eq_imported_witness :
    dustPoint =
      P0EFTJanusMatterCurvatureFLRWConstraintBranch.witnessPoint := rfl

/-- The secondary covector at the positive-dust witness. -/
theorem witness_secondary_covector_exact :
    secondaryDifferential dustParameters.base dustPoint =
      { aPlus := -1, pPlus := 1, aMinus := 1, pMinus := -1 } := by
  norm_num [secondaryDifferential, kinematicFactor, potentialFactor,
    dustParameters, dustPoint, ptFlatParameters, ptFlatCoefficients]

/-- Linearized satisfaction of both primary constraints and the secondary
constraint at the dust witness. -/
def ConstrainedTangent (variation : PhasePoint) : Prop :=
  covectorApply
      (extendedPlusDifferential dustParameters dustPoint) variation = 0 ∧
    covectorApply
      (extendedMinusDifferential dustParameters dustPoint) variation = 0 ∧
    covectorApply
      (secondaryDifferential dustParameters.base dustPoint) variation = 0

/-- A convenient integral generator of the common tangent kernel. -/
def tangentGenerator : PhasePoint :=
  { aPlus := 2, pPlus := 1, aMinus := 2, pMinus := 1 }

/-- Coordinate multiples of the tangent generator. -/
def tangentMultiple (scale : ℝ) : PhasePoint :=
  { aPlus := 2 * scale
    pPlus := scale
    aMinus := 2 * scale
    pMinus := scale }

theorem tangentGenerator_nonzero :
    tangentGenerator ≠
      ({ aPlus := 0, pPlus := 0, aMinus := 0, pMinus := 0 } : PhasePoint) := by
  intro h
  have hp := congrArg PhasePoint.pPlus h
  norm_num [tangentGenerator] at hp

theorem tangentGenerator_is_constrained :
    ConstrainedTangent tangentGenerator := by
  norm_num [ConstrainedTangent, covectorApply, tangentGenerator,
    extendedPlusDifferential, extendedMinusDifferential, plusDifferential,
    minusDifferential, secondaryDifferential, kinematicFactor,
    potentialFactor, dustParameters, dustPoint, ptFlatParameters,
    ptFlatCoefficients]

/-- Exact common kernel of the three constraint covectors. -/
theorem constrainedTangent_iff_multiple (variation : PhasePoint) :
    ConstrainedTangent variation ↔
      ∃ scale : ℝ, variation = tangentMultiple scale := by
  constructor
  · rcases variation with ⟨aPlus, pPlus, aMinus, pMinus⟩
    rintro ⟨hPlus, hMinus, hSecondary⟩
    norm_num [covectorApply, extendedPlusDifferential,
      extendedMinusDifferential, plusDifferential, minusDifferential,
      secondaryDifferential, kinematicFactor, potentialFactor,
      dustParameters, dustPoint, ptFlatParameters, ptFlatCoefficients]
      at hPlus hMinus hSecondary
    have haPlus : aPlus = 2 * pPlus := by linarith
    have haMinus : aMinus = 2 * pPlus := by linarith
    have hpMinus : pMinus = pPlus := by linarith
    subst aPlus
    subst aMinus
    subst pMinus
    exact ⟨pPlus, rfl⟩
  · rintro ⟨scale, rfl⟩
    norm_num [ConstrainedTangent, covectorApply, tangentMultiple,
      extendedPlusDifferential, extendedMinusDifferential, plusDifferential,
      minusDifferential, secondaryDifferential, kinematicFactor,
      potentialFactor, dustParameters, dustPoint, ptFlatParameters,
      ptFlatCoefficients]
    constructor <;> ring

/-- Equal-lapse reduced Hamiltonian selected by secondary preservation. -/
def fixedLapseHamiltonian (x : PhasePoint) : ℝ :=
  extendedPlusConstraint dustParameters x +
    extendedMinusConstraint dustParameters x

/-- The affine line used to evaluate the ambient Hessian. -/
def tangentAffineLine (t : ℝ) : PhasePoint :=
  phaseLine dustPoint tangentGenerator t

/-- Exact Hamiltonian on the regular part of the affine tangent line. -/
theorem fixedLapseHamiltonian_tangentAffineLine_exact
    (t : ℝ) (hScale : 1 + 2 * t ≠ 0) :
    fixedLapseHamiltonian (tangentAffineLine t) =
      -(t ^ 2) / (6 * (1 + 2 * t)) := by
  have hScale' : 1 + t * 2 ≠ 0 := by
    simpa [mul_comm] using hScale
  simp [fixedLapseHamiltonian, tangentAffineLine, phaseLine,
    tangentGenerator, extendedPlusConstraint, extendedMinusConstraint,
    plusSourceEnergy, minusSourceEnergy, plusConstraint, minusConstraint,
    plusPotential, minusPotential, dustParameters, dustPoint,
    ptFlatParameters, ptFlatCoefficients]
  field_simp [hScale, hScale']
  ring

/-- Actual first derivative of the equal-lapse Hamiltonian along the affine
tangent line. -/
def tangentAffineFirstVariation (t : ℝ) : ℝ :=
  -(t * (1 + t)) / (3 * (1 + 2 * t) ^ 2)

theorem fixedLapseHamiltonian_tangentAffineLine_hasDerivAt
    (t : ℝ) (hScale : 1 + 2 * t ≠ 0) :
    HasDerivAt
      (fun s => fixedLapseHamiltonian (tangentAffineLine s))
      (tangentAffineFirstVariation t) t := by
  have hOpen : IsOpen {s : ℝ | 1 + 2 * s ≠ 0} :=
    isOpen_ne_fun
      (continuous_const.add (continuous_const.mul continuous_id)) continuous_const
  have hLocal : ∀ᶠ s in 𝓝 t, 1 + 2 * s ≠ 0 := hOpen.mem_nhds hScale
  have hEq :
      (fun s => fixedLapseHamiltonian (tangentAffineLine s)) =ᶠ[𝓝 t]
        (fun s => -(s ^ 2) / (6 * (1 + 2 * s))) := by
    filter_upwards [hLocal] with s hs
    exact fixedLapseHamiltonian_tangentAffineLine_exact s hs
  have hNumerator : HasDerivAt (fun s : ℝ => -(s ^ 2)) (-(2 * t)) t := by
    have hRaw := ((hasDerivAt_id t).pow 2).neg
    refine (hRaw.congr_deriv ?_).congr_of_eventuallyEq
      (Filter.Eventually.of_forall ?_)
    · simp
    · intro s
      rfl
  have hDenominator :
      HasDerivAt (fun s : ℝ => 6 * (1 + 2 * s)) 12 t := by
    have hRaw :=
      (((hasDerivAt_id t).const_mul (2 : ℝ)).const_add (1 : ℝ)).const_mul 6
    refine (hRaw.congr_deriv ?_).congr_of_eventuallyEq
      (Filter.Eventually.of_forall ?_)
    · ring
    · intro s
      simp
  have hDenominatorNe : 6 * (1 + 2 * t) ≠ 0 := mul_ne_zero (by norm_num) hScale
  have hDerivative := hNumerator.div hDenominator hDenominatorNe
  refine (hDerivative.congr_deriv ?_).congr_of_eventuallyEq hEq
  simp [tangentAffineFirstVariation]
  field_simp [hScale]
  ring

/-- The true ambient second directional derivative is negative on the exact
kernel generator. -/
theorem fixedLapseHamiltonian_tangentGenerator_secondVariation :
    HasDerivAt tangentAffineFirstVariation (-(1 / 3 : ℝ)) 0 := by
  have ht : HasDerivAt (fun t : ℝ => t) 1 0 := hasDerivAt_id 0
  have hNumerator := (ht.mul (ht.const_add (1 : ℝ))).neg
  have hDenominator :=
    (((ht.const_mul (2 : ℝ)).const_add (1 : ℝ)).pow 2).const_mul (3 : ℝ)
  have hDerivative := hNumerator.div hDenominator
    (by norm_num : 3 * (1 + 2 * (0 : ℝ)) ^ 2 ≠ 0)
  refine (hDerivative.congr_deriv ?_).congr_of_eventuallyEq
    (Filter.Eventually.of_forall ?_)
  · norm_num
  · intro s
    simp [tangentAffineFirstVariation, div_eq_mul_inv]

theorem tangentGenerator_ambientHessian_negative :
    -(1 / 3 : ℝ) < 0 := by norm_num

/-- An exact nonlinear curve through the witness with the same tangent. -/
def exactConstraintCurve (t : ℝ) : PhasePoint :=
  { aPlus := (1 + t) ^ 2
    pPlus := 1 + t
    aMinus := (1 + t) ^ 2
    pMinus := 1 + t }

theorem exactConstraintCurve_at_zero :
    exactConstraintCurve 0 = dustPoint := by
  norm_num [exactConstraintCurve, dustPoint]

theorem exactConstraintCurve_has_tangentGenerator :
    HasDerivAt (fun t => (exactConstraintCurve t).aPlus)
        tangentGenerator.aPlus 0 ∧
      HasDerivAt (fun t => (exactConstraintCurve t).pPlus)
        tangentGenerator.pPlus 0 ∧
      HasDerivAt (fun t => (exactConstraintCurve t).aMinus)
        tangentGenerator.aMinus 0 ∧
      HasDerivAt (fun t => (exactConstraintCurve t).pMinus)
        tangentGenerator.pMinus 0 := by
  have ht : HasDerivAt (fun t : ℝ => t) 1 0 := hasDerivAt_id 0
  have hShift := ht.const_add (1 : ℝ)
  have hSquare : HasDerivAt (fun t : ℝ => (1 + t) ^ 2) 2 0 := by
    have hRaw := hShift.pow 2
    refine (hRaw.congr_deriv ?_).congr_of_eventuallyEq
      (Filter.Eventually.of_forall ?_)
    · norm_num
    · intro s
      rfl
  constructor
  · simpa [exactConstraintCurve, tangentGenerator] using hSquare
  constructor
  · simpa [exactConstraintCurve, tangentGenerator] using hShift
  constructor
  · simpa [exactConstraintCurve, tangentGenerator] using hSquare
  · simpa [exactConstraintCurve, tangentGenerator] using hShift

/-- Away from the zero-scale endpoint, the nonlinear curve satisfies all
three displayed constraints exactly. -/
theorem exactConstraintCurve_lies_on_constraints
    (t : ℝ) (hScale : 1 + t ≠ 0) :
    extendedPlusConstraint dustParameters (exactConstraintCurve t) = 0 ∧
      extendedMinusConstraint dustParameters (exactConstraintCurve t) = 0 ∧
      secondaryConstraint dustParameters.base (exactConstraintCurve t) = 0 := by
  have hSquare : (1 + t) ^ 2 ≠ 0 := pow_ne_zero 2 hScale
  constructor
  · simp [extendedPlusConstraint, plusSourceEnergy, plusConstraint,
      plusPotential, exactConstraintCurve, dustParameters, ptFlatParameters,
      ptFlatCoefficients]
    field_simp [hScale, hSquare]
    ring
  constructor
  · simp [extendedMinusConstraint, minusSourceEnergy, minusConstraint,
      minusPotential, exactConstraintCurve, dustParameters, ptFlatParameters,
      ptFlatCoefficients]
    field_simp [hScale, hSquare]
    ring
  · simp [secondaryConstraint, kinematicFactor, exactConstraintCurve,
      dustParameters, ptFlatParameters]

theorem fixedLapseHamiltonian_exactConstraintCurve_eq_zero
    (t : ℝ) (hScale : 1 + t ≠ 0) :
    fixedLapseHamiltonian (exactConstraintCurve t) = 0 := by
  rcases exactConstraintCurve_lies_on_constraints t hScale with ⟨hPlus, hMinus, _⟩
  simp [fixedLapseHamiltonian, hPlus, hMinus]

/-- The equal-lapse Hamiltonian has zero first derivative along the actual
constraint curve. -/
theorem fixedLapseHamiltonian_exactConstraintCurve_hasDerivAt
    (t : ℝ) (hScale : 1 + t ≠ 0) :
    HasDerivAt
      (fun s => fixedLapseHamiltonian (exactConstraintCurve s)) 0 t := by
  have hOpen : IsOpen {s : ℝ | 1 + s ≠ 0} :=
    isOpen_ne_fun (continuous_const.add continuous_id) continuous_const
  have hLocal : ∀ᶠ s in 𝓝 t, 1 + s ≠ 0 := hOpen.mem_nhds hScale
  have hEq :
      (fun s => fixedLapseHamiltonian (exactConstraintCurve s)) =ᶠ[𝓝 t]
        (fun _ : ℝ => 0) := by
    filter_upwards [hLocal] with s hs
    exact fixedLapseHamiltonian_exactConstraintCurve_eq_zero s hs
  exact (hasDerivAt_const t 0).congr_of_eventuallyEq hEq

/-- Consequently the true second variation along the exact constrained curve
is zero.  The negative affine Hessian above measures second-order departure
from the constraint surface, not a reduced instability theorem. -/
theorem fixedLapseHamiltonian_exactConstraintCurve_secondVariation :
    HasDerivAt
      (fun t => deriv
        (fun s => fixedLapseHamiltonian (exactConstraintCurve s)) t)
      (0 : ℝ) 0 := by
  have hOpen : IsOpen {t : ℝ | 1 + t ≠ 0} :=
    isOpen_ne_fun (continuous_const.add continuous_id) continuous_const
  have hAtZero : (0 : ℝ) ∈ {t : ℝ | 1 + t ≠ 0} := by norm_num
  have hLocal : ∀ᶠ t in 𝓝 (0 : ℝ), 1 + t ≠ 0 :=
    hOpen.mem_nhds hAtZero
  have hEq :
      (fun t => deriv
        (fun s => fixedLapseHamiltonian (exactConstraintCurve s)) t) =ᶠ[𝓝 0]
        (fun _ : ℝ => 0) := by
    filter_upwards [hLocal] with t ht
    exact (fixedLapseHamiltonian_exactConstraintCurve_hasDerivAt t ht).deriv
  exact (hasDerivAt_const (x := (0 : ℝ)) (c := (0 : ℝ))).congr_of_eventuallyEq hEq

end

end P0EFTJanusDustFLRWConstrainedStability
end JanusFormal
