import JanusFormal.Branches.FundamentalGeometryPVariationalPrinciple.Gates.P0EFTJanusMappingTorusCanonicalPhysicalScalarCanonicalDenseParametrizedCauchyJetGreenCore4D
import JanusFormal.Branches.FundamentalGeometryPVariationalPrinciple.Gates.P0EFTJanusMappingTorusCanonicalPhysicalScalarCanonicalAutomaticSixCoefficientPDEClosure4D

/-!
# Minimal canonical PDE closure from a dense physical parametrization

This file combines the dense-parametrized canonical Green core with the minimal
analytic boundary package.  The final completed boundary triple now requires:

* a continuous dense-range measure-preserving physical parametrization with an
  open-positive source measure;
* Euler overlap compatibility;
* density of the canonical periodic and antiperiodic boundary cores;
* the global Green--divergence identity;
* one first-jet energy estimate;
* one normal elliptic regularity estimate;
* six tangential Euler coefficient estimates.

In particular, no fieldwise almost-everywhere faithfulness hypothesis and no
tubular inverse regularity input remain in this interface.
-/

namespace JanusFormal
namespace P0EFTJanusMappingTorusCanonicalPhysicalScalarCanonicalDenseParametrizedAutomaticSixCoefficientPDEClosure4D

set_option autoImplicit false
noncomputable section

open Set Topology MeasureTheory
open P0EFTJanusMappingTorusCanonicalLatitudeSmoothBoundaryCores4D
open P0EFTJanusMappingTorusCanonicalPhysicalScalarCanonicalDenseParametrizedCauchyJetGreenCore4D
open P0EFTJanusMappingTorusCanonicalPhysicalScalarAutomaticGardingEnergy4D
open P0EFTJanusMappingTorusCanonicalPhysicalScalarNormalEllipticRegularity4D
open P0EFTJanusMappingTorusCanonicalPhysicalScalarCauchyJetGeometricGreenCore4D
open P0EFTJanusMappingTorusCanonicalPhysicalScalarCanonicalAutomaticSixCoefficientPDEClosure4D
open P0EFTJanusMappingTorusScalarHilbertGreenCoreCompletion4D

universe u r

variable (period : Real) (hPeriod : period ≠ 0)
variable {massSquared : Real}
variable {Regularity : Type r}
  [NormedAddCommGroup Regularity] [NormedSpace Real Regularity]
  [CompleteSpace Regularity]

/-- Minimal completed-boundary data with Euler faithfulness generated by a dense
physical measure parametrization. -/
structure CanonicalPhysicalScalarCanonicalDenseParametrizedAutomaticSixCoefficientPDEData
    (Source : Type u)
    [TopologicalSpace Source] [MeasurableSpace Source]
    (sourceMeasure : Measure Source)
    (massSquared : Real) where
  geometric :
    CanonicalPhysicalScalarCanonicalDenseParametrizedCauchyJetData
      period hPeriod Source sourceMeasure massSquared
  energy : (geometric.greenCore period hPeriod).AutomaticEnergyGardingData period hPeriod
  normalRegularity : (geometric.greenCore period hPeriod).NormalEllipticRegularityData
    period hPeriod (Regularity := Regularity)
  eulerCoefficients :
    ((((geometric.toCanonicalCauchyJetCompatibilityData period hPeriod)
      |>.toCompatibilityData period hPeriod).toCauchyJetGeometricData
      period hPeriod)).CauchyJetEulerSixCoefficientData
      period hPeriod
      (((((geometric.toCanonicalCauchyJetCompatibilityData period hPeriod)
        |>.toCompatibilityData period hPeriod).toCauchyJetGeometricData
        period hPeriod)).canonicalEulerProductRealization period hPeriod)

namespace CanonicalPhysicalScalarCanonicalDenseParametrizedAutomaticSixCoefficientPDEData

/-- Conversion to the already established minimal canonical PDE package. -/
def toCanonicalAutomaticSixCoefficientPDEData
    {Source : Type u}
    [TopologicalSpace Source] [MeasurableSpace Source]
    {sourceMeasure : Measure Source}
    (data :
      CanonicalPhysicalScalarCanonicalDenseParametrizedAutomaticSixCoefficientPDEData
        period hPeriod Source sourceMeasure massSquared
        (Regularity := Regularity)) :
    CanonicalPhysicalScalarCanonicalAutomaticSixCoefficientPDEData
      period hPeriod massSquared (Regularity := Regularity) where
  geometric := data.geometric.toCanonicalCauchyJetCompatibilityData period hPeriod
  energy := data.energy
  normalRegularity := data.normalRegularity
  eulerCoefficients := data.eulerCoefficients

/-- Correct completed physical boundary triple. -/
def triple
    {Source : Type u}
    [TopologicalSpace Source] [MeasurableSpace Source]
    {sourceMeasure : Measure Source}
    (data :
      CanonicalPhysicalScalarCanonicalDenseParametrizedAutomaticSixCoefficientPDEData
        period hPeriod Source sourceMeasure massSquared
        (Regularity := Regularity)) :=
  (data.toCanonicalAutomaticSixCoefficientPDEData period hPeriod).triple period hPeriod

/-- Completed physical boundary inputs. -/
def completedInputs
    {Source : Type u}
    [TopologicalSpace Source] [MeasurableSpace Source]
    {sourceMeasure : Measure Source}
    (data :
      CanonicalPhysicalScalarCanonicalDenseParametrizedAutomaticSixCoefficientPDEData
        period hPeriod Source sourceMeasure massSquared
        (Regularity := Regularity)) :=
  (data.toCanonicalAutomaticSixCoefficientPDEData period hPeriod).completedInputs
    period hPeriod

/-- Bounded right inverse of the completed Cauchy trace. -/
def completedExtension
    {Source : Type u}
    [TopologicalSpace Source] [MeasurableSpace Source]
    {sourceMeasure : Measure Source}
    (data :
      CanonicalPhysicalScalarCanonicalDenseParametrizedAutomaticSixCoefficientPDEData
        period hPeriod Source sourceMeasure massSquared
        (Regularity := Regularity)) :=
  (data.toCanonicalAutomaticSixCoefficientPDEData period hPeriod).completedExtension
    period hPeriod

/-- Physical graph-elliptic estimate generated from the single component-energy
pairing estimate. -/
def graphEllipticEstimate
    {Source : Type u}
    [TopologicalSpace Source] [MeasurableSpace Source]
    {sourceMeasure : Measure Source}
    (data :
      CanonicalPhysicalScalarCanonicalDenseParametrizedAutomaticSixCoefficientPDEData
        period hPeriod Source sourceMeasure massSquared
        (Regularity := Regularity)) :=
  (data.toCanonicalAutomaticSixCoefficientPDEData period hPeriod).graphEllipticEstimate
    period hPeriod

/-- Dense-parametrized minimal PDE certificate. -/
theorem certificate
    {Source : Type u}
    [TopologicalSpace Source] [MeasurableSpace Source]
    {sourceMeasure : Measure Source}
    (data :
      CanonicalPhysicalScalarCanonicalDenseParametrizedAutomaticSixCoefficientPDEData
        period hPeriod Source sourceMeasure massSquared
        (Regularity := Regularity)) :
    (P0EFTJanusMappingTorusCanonicalLorentzVolumeGluing4D.intrinsicCanonicalLorentzVolumeMeasure
        period hPeriod).IsOpenPosMeasure ∧
      (∀ field : P0EFTJanusMappingTorusSmoothFieldDescent4D.SmoothQuotientField
          period hPeriod Real,
        ‖P0EFTJanusMappingTorusCanonicalVolumeH1Trace4D.smoothToCanonicalPhysicalScalarH1
            period hPeriod field‖ ^ 2 ≤
          canonicalPhysicalScalarFirstJetComponentEnergy period hPeriod field) ∧
      Function.Injective
        (canonicalScalarGreenCoreGraphInclusion
          (data.geometric.greenCore period hPeriod).core) ∧
      Function.Surjective
        (canonicalScalarGreenCoreCompletedBoundaryTrace
          (data.geometric.greenCore period hPeriod).core
          ((data.completedInputs period hPeriod).traceBound period hPeriod
            (data.geometric.greenCore period hPeriod))) ∧
      (∀ boundary,
        canonicalScalarGreenCoreCompletedBoundaryTrace
            (data.geometric.greenCore period hPeriod).core
            ((data.completedInputs period hPeriod).traceBound period hPeriod
              (data.geometric.greenCore period hPeriod))
            (data.completedExtension period hPeriod boundary) = boundary) :=
  ⟨data.geometric.physicalMeasureOpenPositive,
    ((data.toCanonicalAutomaticSixCoefficientPDEData period hPeriod).certificate
      period hPeriod).1,
    ((data.toCanonicalAutomaticSixCoefficientPDEData period hPeriod).certificate
      period hPeriod).2.1,
    ((data.toCanonicalAutomaticSixCoefficientPDEData period hPeriod).certificate
      period hPeriod).2.2.1,
    ((data.toCanonicalAutomaticSixCoefficientPDEData period hPeriod).certificate
      period hPeriod).2.2.2⟩

end CanonicalPhysicalScalarCanonicalDenseParametrizedAutomaticSixCoefficientPDEData

end
end P0EFTJanusMappingTorusCanonicalPhysicalScalarCanonicalDenseParametrizedAutomaticSixCoefficientPDEClosure4D
end JanusFormal
