import JanusFormal.Branches.FundamentalGeometryPVariationalPrinciple.Gates.P0EFTJanusMappingTorusCanonicalPhysicalScalarIntrinsicWaveTangentialTimePrimitiveFinalClosure4D
import JanusFormal.Branches.FundamentalGeometryPVariationalPrinciple.Gates.P0EFTJanusMappingTorusCanonicalPhysicalScalarCanonicalStandardBoundaryResolventClosure4D

/-!
# Standard boundary realizations for the periodic time-primitive endpoint

This file specializes the most local final Green package to separated,
Dirichlet, Neumann and constant real Robin boundary conditions.  Time-divergence
cancellation is generated by a periodic primitive, while the completed Cauchy
pair is reconstructed by Riesz duality.
-/

namespace JanusFormal
namespace P0EFTJanusMappingTorusCanonicalPhysicalScalarIntrinsicWaveTangentialTimePrimitiveStandardBoundaryFinalClosure4D

set_option autoImplicit false
noncomputable section

open Set Topology MeasureTheory
open P0EFTJanusMappingTorusCanonicalPhysicalScalarFirstSheetHilbertTrace4D
open P0EFTJanusMappingTorusCanonicalPhysicalScalarIntrinsicWaveTangentialTimePrimitiveFinalClosure4D
open P0EFTJanusMappingTorusCanonicalPhysicalScalarCanonicalStandardBoundaryResolventClosure4D
open P0EFTJanusMappingTorusCanonicalPhysicalScalarFiniteCoordinateRellich4D
open P0EFTJanusMappingTorusScalarHilbertBoundarySymplectic4D
open P0EFTJanusMappingTorusScalarAbstractLagrangianBoundary4D
open P0EFTJanusMappingTorusScalarCompletedBoundaryTripleExternalPositiveShiftedForm4D

universe e

variable (period : Real) (hPeriod : period ≠ 0)
variable {Energy : Type e}
  [NormedAddCommGroup Energy] [NormedSpace Real Energy]

private abbrev BoundaryL2 := CanonicalPhysicalScalarFirstSheetL2 period

private abbrev BulkL2 :=
  P0EFTJanusMappingTorusCanonicalPhysicalBulkL2H1Bridge4D.CanonicalPhysicalBulkL2
    period hPeriod

/-- Final periodic-time-primitive data for one separated boundary condition. -/
structure CanonicalPhysicalScalarIntrinsicWaveTangentialTimePrimitiveSeparatedFinalData
    (massSquared a b : Real)
    (hNondegenerate : a ≠ 0 ∨ b ≠ 0)
    (Energy : Type e)
    [NormedAddCommGroup Energy] [NormedSpace Real Energy] where
  geometric :
    P0EFTJanusMappingTorusCanonicalPhysicalScalarIntrinsicWaveTangentialTimePrimitiveGreen4D.CanonicalPhysicalScalarIntrinsicWaveTangentialTimePrimitiveGreenData
      period hPeriod massSquared
  energyIdentity : geometric.greenCore.ScalarRemainderEnergyIdentityData
    period hPeriod
  eulerCoefficientOperators :
    geometric.toCanonicalNormalGreenData.toNormalTangentialGreenData.toIntrinsicWaveLocalGreenData.toCanonicalLocalDivergenceData.toCanonicalWaveCauchyJetData.toCanonicalCauchyJetCompatibilityData.toCompatibilityData.toCauchyJetGeometricData.CauchyJetEulerSixCanonicalL2OperatorData
      period hPeriod
  referenceParameter : Real
  shiftedPositiveDecomposition :
    (P0EFTJanusMappingTorusCanonicalPhysicalScalarProgramPFinalObligations4D.assembleCanonicalPhysicalScalarBoundaryData
      period hPeriod geometric.toCanonicalNormalGreenData energyIdentity
        eulerCoefficientOperators).triple
      |>.LagrangianShiftedExternalPositiveDecompositionData
        (canonicalPhysicalScalarSeparatedCondition
          period a b hNondegenerate)
        referenceParameter Energy
  finiteCoordinateRellich : CanonicalPhysicalScalarFiniteCoordinateRellichData
    period hPeriod

namespace CanonicalPhysicalScalarIntrinsicWaveTangentialTimePrimitiveSeparatedFinalData

/-- Conversion to the generic periodic-time-primitive final endpoint. -/
def toFinalData
    {a b : Real} {hNondegenerate : a ≠ 0 ∨ b ≠ 0}
    (data : CanonicalPhysicalScalarIntrinsicWaveTangentialTimePrimitiveSeparatedFinalData
      period hPeriod massSquared a b hNondegenerate Energy) :
    CanonicalPhysicalScalarIntrinsicWaveTangentialTimePrimitiveFinalData
      period hPeriod massSquared Energy where
  geometric := data.geometric
  energyIdentity := data.energyIdentity
  eulerCoefficientOperators := data.eulerCoefficientOperators
  condition := canonicalPhysicalScalarSeparatedCondition
    period a b hNondegenerate
  referenceParameter := data.referenceParameter
  shiftedPositiveDecomposition := data.shiftedPositiveDecomposition
  finiteCoordinateRellich := data.finiteCoordinateRellich

/-- Membership is exactly the separated completed Riesz constraint. -/
theorem mem_lagrangianDomainSubmodule_iff
    {a b : Real} {hNondegenerate : a ≠ 0 ∨ b ≠ 0}
    (data : CanonicalPhysicalScalarIntrinsicWaveTangentialTimePrimitiveSeparatedFinalData
      period hPeriod massSquared a b hNondegenerate Energy)
    (field : data.toFinalData.triple.MaximalDomain) :
    field ∈ data.toFinalData.triple.lagrangianDomainSubmodule
        (canonicalPhysicalScalarSeparatedCondition
          period a b hNondegenerate) ↔
      a • (data.toFinalData.completedBoundaryTrace field).1 +
        b • (data.toFinalData.completedBoundaryTrace field).2 = 0 := by
  change data.toFinalData.completedBoundaryTrace field ∈
      canonicalScalarHilbertSeparatedBoundarySubmodule
        (Trace := BoundaryL2 period) a b ↔ _
  exact mem_canonicalScalarHilbertSeparatedBoundarySubmodule
    (Trace := BoundaryL2 period) a b _

/-- Actual Hilbert self-adjointness. -/
theorem actualAdjointDomain_eq
    {a b : Real} {hNondegenerate : a ≠ 0 ∨ b ≠ 0}
    (data : CanonicalPhysicalScalarIntrinsicWaveTangentialTimePrimitiveSeparatedFinalData
      period hPeriod massSquared a b hNondegenerate Energy) :
    data.toFinalData.triple.actualAdjointDomain
        (canonicalPhysicalScalarSeparatedCondition
          period a b hNondegenerate) =
      data.toFinalData.triple.realizationDomain
        (canonicalPhysicalScalarSeparatedCondition
          period a b hNondegenerate) :=
  data.toFinalData.actualAdjointDomain_eq period hPeriod

/-- Classical source solution. -/
noncomputable def sourceSolution
    {a b : Real} {hNondegenerate : a ≠ 0 ∨ b ≠ 0}
    (data : CanonicalPhysicalScalarIntrinsicWaveTangentialTimePrimitiveSeparatedFinalData
      period hPeriod massSquared a b hNondegenerate Energy) :=
  data.toFinalData.sourceSolution period hPeriod

/-- Strong shifted source equation. -/
theorem sourceSolution_equation
    {a b : Real} {hNondegenerate : a ≠ 0 ∨ b ≠ 0}
    (data : CanonicalPhysicalScalarIntrinsicWaveTangentialTimePrimitiveSeparatedFinalData
      period hPeriod massSquared a b hNondegenerate Energy)
    (source : BulkL2 period hPeriod) :
    data.toFinalData.triple.lagrangianShiftedOperator
        (canonicalPhysicalScalarSeparatedCondition
          period a b hNondegenerate)
        data.referenceParameter
        (data.sourceSolution period hPeriod source) = source :=
  data.toFinalData.sourceSolution_equation period hPeriod source

/-- Unique global minimizer. -/
theorem sourceSolution_unique_minimizer
    {a b : Real} {hNondegenerate : a ≠ 0 ∨ b ≠ 0}
    (data : CanonicalPhysicalScalarIntrinsicWaveTangentialTimePrimitiveSeparatedFinalData
      period hPeriod massSquared a b hNondegenerate Energy)
    (source : BulkL2 period hPeriod) :=
  data.toFinalData.sourceSolution_unique_minimizer period hPeriod source

/-- Gaussian generating functional. -/
def gaussianGeneratingFunctional
    {a b : Real} {hNondegenerate : a ≠ 0 ∨ b ≠ 0}
    (data : CanonicalPhysicalScalarIntrinsicWaveTangentialTimePrimitiveSeparatedFinalData
      period hPeriod massSquared a b hNondegenerate Energy)
    (source : BulkL2 period hPeriod) : Real :=
  data.toFinalData.gaussianGeneratingFunctional period hPeriod source

/-- On-shell Gaussian identity and positivity. -/
theorem gaussian_certificate
    {a b : Real} {hNondegenerate : a ≠ 0 ∨ b ≠ 0}
    (data : CanonicalPhysicalScalarIntrinsicWaveTangentialTimePrimitiveSeparatedFinalData
      period hPeriod massSquared a b hNondegenerate Energy)
    (source : BulkL2 period hPeriod) :
    data.gaussianGeneratingFunctional period hPeriod source =
        -data.toFinalData.triple.lagrangianSourceAction
          (canonicalPhysicalScalarSeparatedCondition
            period a b hNondegenerate)
          data.referenceParameter source
          (data.sourceSolution period hPeriod source) ∧
      0 ≤ data.gaussianGeneratingFunctional period hPeriod source :=
  data.toFinalData.gaussian_certificate period hPeriod source

/-- Complete separated final certificate. -/
theorem finalProgramP_certificate
    {a b : Real} {hNondegenerate : a ≠ 0 ∨ b ≠ 0}
    (data : CanonicalPhysicalScalarIntrinsicWaveTangentialTimePrimitiveSeparatedFinalData
      period hPeriod massSquared a b hNondegenerate Energy)
    (source : BulkL2 period hPeriod) :
    (∀ field test normal sphere,
      (∫ time,
        data.geometric.timeDensity field test normal (sphere, time)
        ∂volume.restrict
          (P0EFTJanusMappingTorusCanonicalPhysicalH1TraceBound4D.canonicalLatitudeTimeInterval
            period)) = 0) ∧
      data.toFinalData.triple.actualAdjointDomain
          (canonicalPhysicalScalarSeparatedCondition
            period a b hNondegenerate) =
        data.toFinalData.triple.realizationDomain
          (canonicalPhysicalScalarSeparatedCondition
            period a b hNondegenerate) ∧
      data.toFinalData.triple.lagrangianShiftedOperator
          (canonicalPhysicalScalarSeparatedCondition
            period a b hNondegenerate)
          data.referenceParameter
          (data.sourceSolution period hPeriod source) = source ∧
      (∀ field : data.toFinalData.triple.lagrangianDomainSubmodule
          (canonicalPhysicalScalarSeparatedCondition
            period a b hNondegenerate),
        data.toFinalData.triple.lagrangianSourceAction
            (canonicalPhysicalScalarSeparatedCondition
              period a b hNondegenerate)
            data.referenceParameter source
            (data.sourceSolution period hPeriod source) ≤
          data.toFinalData.triple.lagrangianSourceAction
            (canonicalPhysicalScalarSeparatedCondition
              period a b hNondegenerate)
            data.referenceParameter source field) ∧
      0 ≤ data.gaussianGeneratingFunctional period hPeriod source :=
  ⟨data.geometric.toTangentialTimePrimitiveData.time_integral_zero,
    data.actualAdjointDomain_eq period hPeriod,
    data.sourceSolution_equation period hPeriod source,
    (data.sourceSolution_unique_minimizer period hPeriod source).1,
    (data.gaussian_certificate period hPeriod source).2⟩

end CanonicalPhysicalScalarIntrinsicWaveTangentialTimePrimitiveSeparatedFinalData

/-- Dirichlet endpoint. -/
abbrev CanonicalPhysicalScalarIntrinsicWaveTangentialTimePrimitiveDirichletFinalData
    (massSquared : Real) (Energy : Type e)
    [NormedAddCommGroup Energy] [NormedSpace Real Energy] :=
  CanonicalPhysicalScalarIntrinsicWaveTangentialTimePrimitiveSeparatedFinalData
    period hPeriod massSquared 1 0 (Or.inl one_ne_zero) Energy

/-- Neumann endpoint. -/
abbrev CanonicalPhysicalScalarIntrinsicWaveTangentialTimePrimitiveNeumannFinalData
    (massSquared : Real) (Energy : Type e)
    [NormedAddCommGroup Energy] [NormedSpace Real Energy] :=
  CanonicalPhysicalScalarIntrinsicWaveTangentialTimePrimitiveSeparatedFinalData
    period hPeriod massSquared 0 1 (Or.inr one_ne_zero) Energy

/-- Constant Robin endpoint. -/
abbrev CanonicalPhysicalScalarIntrinsicWaveTangentialTimePrimitiveRobinFinalData
    (massSquared coefficient : Real) (Energy : Type e)
    [NormedAddCommGroup Energy] [NormedSpace Real Energy] :=
  CanonicalPhysicalScalarIntrinsicWaveTangentialTimePrimitiveSeparatedFinalData
    period hPeriod massSquared (-coefficient) 1 (Or.inr one_ne_zero) Energy

namespace CanonicalPhysicalScalarIntrinsicWaveTangentialTimePrimitiveSeparatedFinalData

/-- Dirichlet domain is zero completed value trace. -/
theorem mem_dirichletDomain_iff
    (data : CanonicalPhysicalScalarIntrinsicWaveTangentialTimePrimitiveDirichletFinalData
      period hPeriod massSquared Energy)
    (field : data.toFinalData.triple.MaximalDomain) :
    field ∈ data.toFinalData.triple.lagrangianDomainSubmodule
        (canonicalPhysicalScalarDirichletCondition period) ↔
      (data.toFinalData.completedBoundaryTrace field).1 = 0 := by
  change data.toFinalData.completedBoundaryTrace field ∈
      canonicalScalarHilbertDirichletBoundarySubmodule
        (Trace := BoundaryL2 period) ↔ _
  exact mem_canonicalScalarHilbertDirichletBoundarySubmodule
    (Trace := BoundaryL2 period) _

/-- Neumann domain is zero completed normal trace. -/
theorem mem_neumannDomain_iff
    (data : CanonicalPhysicalScalarIntrinsicWaveTangentialTimePrimitiveNeumannFinalData
      period hPeriod massSquared Energy)
    (field : data.toFinalData.triple.MaximalDomain) :
    field ∈ data.toFinalData.triple.lagrangianDomainSubmodule
        (canonicalPhysicalScalarNeumannCondition period) ↔
      (data.toFinalData.completedBoundaryTrace field).2 = 0 := by
  change data.toFinalData.completedBoundaryTrace field ∈
      canonicalScalarHilbertNeumannBoundarySubmodule
        (Trace := BoundaryL2 period) ↔ _
  exact mem_canonicalScalarHilbertNeumannBoundarySubmodule
    (Trace := BoundaryL2 period) _

/-- Robin domain is `Γ₁ = κ Γ₀`. -/
theorem mem_robinDomain_iff
    (coefficient : Real)
    (data : CanonicalPhysicalScalarIntrinsicWaveTangentialTimePrimitiveRobinFinalData
      period hPeriod massSquared coefficient Energy)
    (field : data.toFinalData.triple.MaximalDomain) :
    field ∈ data.toFinalData.triple.lagrangianDomainSubmodule
        (canonicalPhysicalScalarRobinCondition period coefficient) ↔
      (data.toFinalData.completedBoundaryTrace field).2 =
        coefficient • (data.toFinalData.completedBoundaryTrace field).1 := by
  change data.toFinalData.completedBoundaryTrace field ∈
      canonicalScalarHilbertRobinBoundarySubmodule
        (Trace := BoundaryL2 period) coefficient ↔ _
  exact mem_canonicalScalarHilbertRobinBoundarySubmodule
    (Trace := BoundaryL2 period) coefficient _

end CanonicalPhysicalScalarIntrinsicWaveTangentialTimePrimitiveSeparatedFinalData

/-- Marker for standard periodic-time-primitive boundary families. -/
theorem canonicalPhysicalScalarIntrinsicWaveTangentialTimePrimitiveStandardBoundaryFinalClosure_available : True :=
  trivial

end
end P0EFTJanusMappingTorusCanonicalPhysicalScalarIntrinsicWaveTangentialTimePrimitiveStandardBoundaryFinalClosure4D
end JanusFormal
