import JanusFormal.Branches.FundamentalGeometryPVariationalPrinciple.Gates.P0EFTJanusMappingTorusScalarCompletedBoundaryTriplePositiveShiftedForm4D

/-!
# Positive shifted forms in an external energy space

The positive part of a shifted quadratic form naturally takes values in an
energy space such as a direct sum of first derivatives.  It need not be an
endomorphism of the operator domain.

This file generalizes the positive decomposition to

`Bρ(u,u) = ‖Q u‖²_E + gap * ‖u‖²`,

where `Q` maps continuously to any real normed energy space `E`.  The square term
is nonnegative, so the usual shifted coercivity, bounded resolvent and
semiboundedness conclusions follow exactly as before.
-/

namespace JanusFormal
namespace P0EFTJanusMappingTorusScalarCompletedBoundaryTripleExternalPositiveShiftedForm4D
end P0EFTJanusMappingTorusScalarCompletedBoundaryTripleExternalPositiveShiftedForm4D

namespace P0EFTJanusMappingTorusScalarHilbertGreenCoreCompletion4D

set_option autoImplicit false
noncomputable section

open Set Topology
open P0EFTJanusMappingTorusScalarHilbertBoundarySymplectic4D
open P0EFTJanusMappingTorusScalarAbstractLagrangianBoundary4D
open P0EFTJanusMappingTorusScalarHilbertGreenCoreCompletion4D
open P0EFTJanusMappingTorusScalarCompletedBoundaryTripleShiftedForm4D
open P0EFTJanusMappingTorusScalarCompletedBoundaryTriplePositiveShiftedForm4D

universe u v w e

variable {Domain : Type u} {Ambient : Type v} {Trace : Type w}
  [AddCommGroup Domain] [Module Real Domain]
  [NormedAddCommGroup Ambient] [InnerProductSpace Real Ambient]
  [CompleteSpace Ambient]
  [NormedAddCommGroup Trace] [InnerProductSpace Real Trace]
  [CompleteSpace Trace]
  {Energy : Type e}
  [NormedAddCommGroup Energy] [NormedSpace Real Energy]

namespace CanonicalScalarCompletedBoundaryTripleData

variable {core : CanonicalScalarHilbertGreenCore
    (Domain := Domain) (Ambient := Ambient) (Trace := Trace)}
  {traceBound : HasCanonicalScalarHilbertGreenCoreBoundaryGraphBound core}

/-- Positive decomposition through an arbitrary external energy space. -/
structure LagrangianShiftedExternalPositiveDecompositionData
    (triple : CanonicalScalarCompletedBoundaryTripleData core traceBound)
    (condition : CanonicalScalarHilbertLagrangianBoundaryCondition Trace)
    (spectralParameter : Real)
    (Energy : Type e)
    [NormedAddCommGroup Energy] [NormedSpace Real Energy] where
  positivePart :
    triple.lagrangianDomainSubmodule condition →L[Real] Energy
  gap : Real
  gap_pos : 0 < gap
  form_eq : ∀ field : triple.lagrangianDomainSubmodule condition,
    triple.lagrangianShiftedForm condition spectralParameter field field =
      ‖positivePart field‖ ^ 2 + gap * ‖field‖ ^ 2

namespace LagrangianShiftedExternalPositiveDecompositionData

/-- External positive decomposition implies shifted coercivity. -/
theorem coercive
    (triple : CanonicalScalarCompletedBoundaryTripleData core traceBound)
    (condition : CanonicalScalarHilbertLagrangianBoundaryCondition Trace)
    (spectralParameter : Real)
    (positive : triple.LagrangianShiftedExternalPositiveDecompositionData
      condition spectralParameter Energy)
    (field : triple.lagrangianDomainSubmodule condition) :
    positive.gap * ‖field‖ * ‖field‖ ≤
      triple.lagrangianShiftedForm condition spectralParameter field field := by
  rw [positive.form_eq]
  nlinarith [sq_nonneg ‖positive.positivePart field‖]

/-- Conversion to the canonical shifted coercivity package. -/
def toShiftedFormCoerciveData
    (triple : CanonicalScalarCompletedBoundaryTripleData core traceBound)
    (condition : CanonicalScalarHilbertLagrangianBoundaryCondition Trace)
    (spectralParameter : Real)
    (positive : triple.LagrangianShiftedExternalPositiveDecompositionData
      condition spectralParameter Energy) :
    triple.LagrangianShiftedFormCoerciveData condition spectralParameter where
  constant := positive.gap
  constant_pos := positive.gap_pos
  coercive := positive.coercive triple condition spectralParameter

/-- Bounded direct resolvent generated by the external positive decomposition. -/
noncomputable def boundedResolvent
    (triple : CanonicalScalarCompletedBoundaryTripleData core traceBound)
    (condition : CanonicalScalarHilbertLagrangianBoundaryCondition Trace)
    (spectralParameter : Real)
    (positive : triple.LagrangianShiftedExternalPositiveDecompositionData
      condition spectralParameter Energy)
    (hDense : DenseRange (triple.lagrangianInclusion condition)) :=
  (positive.toShiftedFormCoerciveData triple condition spectralParameter)
    |>.boundedResolvent triple condition spectralParameter hDense

/-- Operator-domain positive decompositions are a special case. -/
def ofInternal
    (triple : CanonicalScalarCompletedBoundaryTripleData core traceBound)
    (condition : CanonicalScalarHilbertLagrangianBoundaryCondition Trace)
    (spectralParameter : Real)
    (positive : triple.LagrangianShiftedPositiveDecompositionData
      condition spectralParameter) :
    triple.LagrangianShiftedExternalPositiveDecompositionData
      condition spectralParameter
      (triple.lagrangianDomainSubmodule condition) where
  positivePart := positive.positivePart
  gap := positive.gap
  gap_pos := positive.gap_pos
  form_eq := positive.form_eq

/-- External-energy positive decomposition certificate. -/
theorem certificate
    (triple : CanonicalScalarCompletedBoundaryTripleData core traceBound)
    (condition : CanonicalScalarHilbertLagrangianBoundaryCondition Trace)
    (spectralParameter : Real)
    (positive : triple.LagrangianShiftedExternalPositiveDecompositionData
      condition spectralParameter Energy) :
    (∀ field : triple.lagrangianDomainSubmodule condition,
      triple.lagrangianShiftedForm condition spectralParameter field field =
        ‖positive.positivePart field‖ ^ 2 + positive.gap * ‖field‖ ^ 2) ∧
      (∀ field : triple.lagrangianDomainSubmodule condition,
        positive.gap * ‖field‖ * ‖field‖ ≤
          triple.lagrangianShiftedForm condition spectralParameter field field) :=
  ⟨positive.form_eq,
    positive.coercive triple condition spectralParameter⟩

end LagrangianShiftedExternalPositiveDecompositionData

end CanonicalScalarCompletedBoundaryTripleData

end
end P0EFTJanusMappingTorusScalarHilbertGreenCoreCompletion4D
end JanusFormal
