import JanusFormal.Branches.FundamentalGeometryPVariationalPrinciple.Gates.P0EFTJanusMappingTorusCanonicalLatitudeBoundaryCoreDensityReduction4D
import JanusFormal.Branches.FundamentalGeometryPVariationalPrinciple.Gates.P0EFTJanusMappingTorusCanonicalPhysicalScalarCanonicalCauchyJetGreenCore4D

/-!
# Explicit-Cauchy physical scalar Green core

This package replaces the two abstract boundary-density fields by concrete
continuous-to-smooth approximation schemes.  It combines:

* wave globalization;
* periodic and antiperiodic smooth approximation in boundary `L²`;
* smooth normalized-tail tubular coordinates;
* the Euler-skew/divergence integral identity.

From these data it constructs the canonical smooth periodic/antiperiodic
boundary cores, the globally smooth explicit Cauchy extension and the dense
physical scalar Green core.
-/

namespace JanusFormal
namespace P0EFTJanusMappingTorusCanonicalPhysicalScalarExplicitCauchyGreenCore4D

set_option autoImplicit false
noncomputable section

open Set Topology
open P0EFTJanusMappingTorusSmoothFieldDescent4D
open P0EFTJanusMappingTorusCanonicalPhysicalScalarEulerAtlasNaturality4D
open P0EFTJanusMappingTorusCanonicalPhysicalScalarEulerGreenL2Reduction4D
open P0EFTJanusMappingTorusCanonicalLatitudeBoundaryCoreDensityReduction4D
open P0EFTJanusMappingTorusEquatorialTubularCoverInverseRegularity4D
open P0EFTJanusMappingTorusCanonicalPhysicalScalarCanonicalCauchyJetGreenCore4D
open P0EFTJanusMappingTorusCutBulkCanonicalDivergenceMeasure4D

variable (period : Real) (hPeriod : period ≠ 0)

/-- Geometric and approximation inputs for the explicit-Cauchy Green core. -/
structure CanonicalPhysicalScalarExplicitCauchyGreenCoreData
    (massSquared : Real) where
  globalization : CanonicalPhysicalScalarWaveGlobalizationData
    period hPeriod massSquared
  boundaryApproximation :
    CanonicalLatitudeBoundaryContinuousSmoothApproximationData period
  tubularBase : CanonicalLatitudeTubularEquatorialBaseRegularityData
    period hPeriod
  integral_eq_divergence :
    ∀ field test : SmoothQuotientField period hPeriod Real,
      (∫ point,
        canonicalPhysicalScalarEulerSkewDensity
          period hPeriod massSquared field test point
        ∂P0EFTJanusMappingTorusCanonicalLorentzVolumeGluing4D.intrinsicCanonicalLorentzVolumeMeasure
          period hPeriod) =
      -2 * cutBulkCanonicalDivergenceMeasure
        period hPeriod massSquared field test Set.univ

namespace CanonicalPhysicalScalarExplicitCauchyGreenCoreData

/-- Canonical smooth boundary-core density generated by the approximation
schemes. -/
def boundaryDensity
    (explicit : CanonicalPhysicalScalarExplicitCauchyGreenCoreData
      period hPeriod massSquared) :=
  explicit.boundaryApproximation.toBoundaryCoreDensityData

/-- Conversion to the canonical Cauchy-jet Green-core package. -/
def toCanonicalCauchyJetGreenCoreData
    (explicit : CanonicalPhysicalScalarExplicitCauchyGreenCoreData
      period hPeriod massSquared) :
    CanonicalPhysicalScalarCanonicalCauchyJetGreenCoreData
      period hPeriod massSquared where
  globalization := explicit.globalization
  boundaryDensity := explicit.boundaryDensity
  tubularBase := explicit.tubularBase
  integral_eq_divergence := explicit.integral_eq_divergence

/-- Explicit globally smooth Cauchy extension. -/
def extension
    (explicit : CanonicalPhysicalScalarExplicitCauchyGreenCoreData
      period hPeriod massSquared) :=
  explicit.toCanonicalCauchyJetGreenCoreData.extension

/-- Correct dense physical scalar Green core. -/
def greenCore
    (explicit : CanonicalPhysicalScalarExplicitCauchyGreenCoreData
      period hPeriod massSquared) :=
  explicit.toCanonicalCauchyJetGreenCoreData.greenCore

/-- Underlying general explicit-Cauchy geometric package. -/
def toCauchyJetGeometricData
    (explicit : CanonicalPhysicalScalarExplicitCauchyGreenCoreData
      period hPeriod massSquared) :=
  explicit.toCanonicalCauchyJetGreenCoreData.toCauchyJetGeometricData

/-- Explicit-Cauchy Green-core certificate. -/
theorem certificate
    (explicit : CanonicalPhysicalScalarExplicitCauchyGreenCoreData
      period hPeriod massSquared) :
    DenseRange
        (P0EFTJanusMappingTorusCanonicalLatitudeSmoothBoundaryCores4D.canonicalLatitudeSmoothPeriodicValueEmbedding
          period) ∧
      DenseRange
        (P0EFTJanusMappingTorusCanonicalLatitudeSmoothBoundaryCores4D.canonicalLatitudeSmoothAntiperiodicNormalEmbedding
          period) ∧
      DenseRange
        (P0EFTJanusMappingTorusCanonicalPhysicalScalarFirstSheetHilbertTrace4D.smoothCanonicalPhysicalScalarFirstSheetCauchyTrace
          period hPeriod) ∧
      (∀ data,
        P0EFTJanusMappingTorusCanonicalPhysicalScalarFirstSheetHilbertTrace4D.smoothCanonicalPhysicalScalarFirstSheetCauchyTrace
            period hPeriod (explicit.extension data) =
          P0EFTJanusMappingTorusScalarBoundarySmoothExtensionDensity4D.canonicalScalarBoundaryCorePairEmbedding
            (P0EFTJanusMappingTorusCanonicalLatitudeSmoothBoundaryCores4D.canonicalLatitudeSmoothPeriodicValueEmbedding
              period)
            (P0EFTJanusMappingTorusCanonicalLatitudeSmoothBoundaryCores4D.canonicalLatitudeSmoothAntiperiodicNormalEmbedding
              period)
            data) :=
  ⟨explicit.boundaryApproximation.periodic.denseRange,
    explicit.boundaryApproximation.antiperiodic.denseRange,
    explicit.toCanonicalCauchyJetGreenCoreData.boundaryTrace_denseRange,
    explicit.toCanonicalCauchyJetGreenCoreData.cauchyTrace_extension⟩

end CanonicalPhysicalScalarExplicitCauchyGreenCoreData

end
end P0EFTJanusMappingTorusCanonicalPhysicalScalarExplicitCauchyGreenCore4D
end JanusFormal
