import JanusFormal.Branches.FundamentalGeometryPVariationalPrinciple.Gates.P0EFTJanusProgramPReferenceFinitePartTraceVariation4D
import JanusFormal.Branches.FundamentalGeometryPVariationalPrinciple.Gates.P0EFTJanusProgramPUnitaryRelativeZetaReferenceTraceAtlas4D

/-!
# Unitary reference atlas from direct finite-part variation theorems

This layer replaces the equality

```text
finitePartFamily.logDerivative = logarithmicTrace
```

for every reference by the direct geometric derivative theorem

```text
HasDerivAt (finitePartLogDeterminant) logarithmicTrace.
```

Derivative uniqueness constructs the former equality, after which reality of
the regularized zeta derivative supplies the complete standalone reference
coefficient and all relative atlas coefficients.
-/

namespace JanusFormal
namespace P0EFTJanusProgramPUnitaryRelativeZetaReferenceVariationAtlas4D

set_option autoImplicit false
noncomputable section

open P0EFTJanusProgramPReferenceFinitePartTraceVariation4D
open P0EFTJanusProgramPRelativeHeatMellinAnalyticDifferenceFamily4D
open P0EFTJanusProgramPRelativeHeatMellinZetaFamily4D
open P0EFTJanusProgramPRelativeZetaDeterminantConnection4D
open P0EFTJanusProgramPUnitaryActualZetaFamily4D
open P0EFTJanusProgramPUnitaryRelativeZetaReferenceTraceAtlas4D

variable {Index E : Type*}
  [NormedAddCommGroup E] [InnerProductSpace Real E]

/-- Actual/reference atlas whose references are controlled by direct
finite-part variation theorems. -/
structure UnitaryRelativeZetaReferenceVariationAtlasData
    (Index : Type*) (E : Type*)
    [NormedAddCommGroup E] [InnerProductSpace Real E] where
  actual : UnitaryActualZetaFamilyData (E := E)
  baseRelativeFamily : RelativeHeatMellinZetaFamilyData
  baseReferenceFamily : RelativeHeatMellinZetaFamilyData
  baseReferenceVariation :
    ReferenceFinitePartTraceVariationData baseReferenceFamily
  baseDifference : RelativeHeatMellinAnalyticDifferenceFamilyData
    baseRelativeFamily actual.family baseReferenceFamily
  localRelativeFamily : Index → RelativeHeatMellinZetaFamilyData
  localReferenceFamily : Index → RelativeHeatMellinZetaFamilyData
  localReferenceVariation : ∀ index,
    ReferenceFinitePartTraceVariationData (localReferenceFamily index)
  localDifference : ∀ index,
    RelativeHeatMellinAnalyticDifferenceFamilyData
      (localRelativeFamily index) actual.family (localReferenceFamily index)

namespace UnitaryRelativeZetaReferenceVariationAtlasData

/-- Convert direct variation theorems into the preceding real-reference atlas. -/
def toReferenceTraceAtlas
    (data : UnitaryRelativeZetaReferenceVariationAtlasData Index E) :
    UnitaryRelativeZetaReferenceTraceAtlasData Index E where
  actual := data.actual
  baseRelativeFamily := data.baseRelativeFamily
  baseReferenceFamily := data.baseReferenceFamily
  baseReferenceData :=
    data.baseReferenceVariation.toReferenceZetaTraceCoefficient
  baseDifference := data.baseDifference
  localRelativeFamily := data.localRelativeFamily
  localReferenceFamily := data.localReferenceFamily
  localReferenceData := fun index =>
    (data.localReferenceVariation index).toReferenceZetaTraceCoefficient
  localDifference := data.localDifference

/-- Base relative coefficient generated by the base finite-part variation. -/
theorem baseCoefficient_eq_referenceTrace
    (data : UnitaryRelativeZetaReferenceVariationAtlasData Index E)
    (parameter : Real) :
    relativeZetaConnectionCoefficient data.baseRelativeFamily.toZetaFamily
        parameter =
      data.baseReferenceVariation.logarithmicTrace parameter :=
  data.toReferenceTraceAtlas.baseCoefficient_eq_referenceTrace parameter

/-- Every local relative coefficient is generated by the corresponding
finite-part variation. -/
theorem localCoefficient_eq_referenceTrace
    (data : UnitaryRelativeZetaReferenceVariationAtlasData Index E)
    (index : Index) (parameter : Real) :
    relativeZetaConnectionCoefficient
        (data.localRelativeFamily index).toZetaFamily parameter =
      (data.localReferenceVariation index).logarithmicTrace parameter :=
  data.toReferenceTraceAtlas.localCoefficient_eq_referenceTrace index parameter

/-- Public direct-variation reference-atlas checkpoint. -/
theorem unitary_relative_zeta_reference_variation_atlas_gate
    (data : UnitaryRelativeZetaReferenceVariationAtlasData Index E) :
    (∀ parameter,
      relativeZetaConnectionCoefficient data.actual.family.toZetaFamily
          parameter = 0) ∧
    (∀ parameter,
      relativeZetaConnectionCoefficient data.baseRelativeFamily.toZetaFamily
          parameter =
        data.baseReferenceVariation.logarithmicTrace parameter) ∧
    (∀ index parameter,
      relativeZetaConnectionCoefficient
          (data.localRelativeFamily index).toZetaFamily parameter =
        (data.localReferenceVariation index).logarithmicTrace parameter) ∧
    (∀ parameter,
      data.baseReferenceFamily.finitePartFamily.logDerivative parameter =
        data.baseReferenceVariation.logarithmicTrace parameter) ∧
    (∀ index parameter,
      (data.localReferenceFamily index).finitePartFamily.logDerivative parameter =
        (data.localReferenceVariation index).logarithmicTrace parameter) :=
  ⟨data.actual.connectionCoefficient_zero,
    data.baseCoefficient_eq_referenceTrace,
    data.localCoefficient_eq_referenceTrace,
    data.baseReferenceVariation.finitePartLogDerivative_eq_trace,
    fun index =>
      (data.localReferenceVariation index).finitePartLogDerivative_eq_trace⟩

end UnitaryRelativeZetaReferenceVariationAtlasData

end
end P0EFTJanusProgramPUnitaryRelativeZetaReferenceVariationAtlas4D
end JanusFormal
