import JanusFormal.Branches.FundamentalGeometryPVariationalPrinciple.Gates.P0EFTJanusMappingTorusCanonicalPhysicalScalarProgramPBClosure4D
import JanusFormal.Branches.FundamentalGeometryPVariationalPrinciple.Gates.P0EFTJanusMappingTorusCanonicalPhysicalScalarScalarRemainderEnergyIdentity4D
import JanusFormal.Branches.FundamentalGeometryPVariationalPrinciple.Gates.P0EFTJanusMappingTorusScalarCompletedBoundaryTripleExternalPositiveShiftedForm4D
import JanusFormal.Branches.FundamentalGeometryPVariationalPrinciple.Gates.P0EFTJanusMappingTorusCanonicalPhysicalScalarFiniteCoordinateRellich4D
import JanusFormal.Branches.FundamentalGeometryPVariationalPrinciple.Gates.P0EFTJanusMappingTorusCanonicalPhysicalScalarIntrinsicWaveNormalTangentialRieszProgramPClosure4D
import JanusFormal.Branches.FundamentalGeometryPVariationalPrinciple.Gates.P0EFTJanusMappingTorusCanonicalPhysicalScalarIntrinsicWaveNormalTangentialRieszStandardBoundaryProgramPClosure4D
import JanusFormal.Branches.FundamentalGeometryPVariationalPrinciple.Gates.P0EFTJanusMappingTorusCanonicalPhysicalScalarIntrinsicWaveNormalTangentialRieszMinimalAnalyticClosure4D
import JanusFormal.Branches.FundamentalGeometryPVariationalPrinciple.Gates.P0EFTJanusMappingTorusCanonicalPhysicalScalarIntrinsicWaveNormalTangentialRieszMinimalProgramPClosure4D
import JanusFormal.Branches.FundamentalGeometryPVariationalPrinciple.Gates.P0EFTJanusMappingTorusCanonicalPhysicalScalarIntrinsicWaveNormalTangentialRieszScalarEnergyPDEClosure4D
import JanusFormal.Branches.FundamentalGeometryPVariationalPrinciple.Gates.P0EFTJanusMappingTorusCanonicalPhysicalScalarIntrinsicWaveNormalTangentialRieszScalarEnergyMinimalAnalyticClosure4D
import JanusFormal.Branches.FundamentalGeometryPVariationalPrinciple.Gates.P0EFTJanusMappingTorusCanonicalPhysicalScalarIntrinsicWaveNormalTangentialRieszScalarEnergyMinimalProgramPClosure4D
import JanusFormal.Branches.FundamentalGeometryPVariationalPrinciple.Gates.P0EFTJanusMappingTorusCanonicalPhysicalScalarIntrinsicWaveNormalTangentialRieszScalarEnergyStandardBoundaryProgramPClosure4D

/-!
# Preferred physical scalar Program P-B closure

This is the recommended aggregate head for the scalar physical branch.

Compared with the historical Program P-B aggregate, the preferred endpoint has
removed the following independent inputs:

* physical-measure full support;
* periodic and antiperiodic boundary-core density;
* normal trace regularity and its constants;
* maximal-adjoint regularity and smooth adjoint approximation;
* an arbitrary bounded zeroth-order energy operator;
* an endomorphism-valued positive square;
* finite-dimensionality proofs for the ranges of Rellich approximants.

The smallest current complete data package uses:

1. an intrinsic global scalar-wave representative;
2. a normal/tangential local Green decomposition;
3. a scalar first-jet energy remainder;
4. six bounded coefficient operators for the explicit Cauchy lift;
5. a closed Lagrangian condition;
6. an external positive-square decomposition of one real shifted form;
7. finite-coordinate factorizations converging to `H¹ -> L²`.

The preferred complete endpoint is
`P0EFTJanusMappingTorusCanonicalPhysicalScalarIntrinsicWaveNormalTangentialRieszScalarEnergyMinimalProgramPClosure4D`.
Dirichlet, Neumann and constant Robin specializations are exposed by
`P0EFTJanusMappingTorusCanonicalPhysicalScalarIntrinsicWaveNormalTangentialRieszScalarEnergyStandardBoundaryProgramPClosure4D`.
-/

namespace JanusFormal
namespace P0EFTJanusMappingTorusCanonicalPhysicalScalarProgramPBPreferredClosure4D

set_option autoImplicit false
noncomputable section

/-- Marker for the preferred smallest scalar Program P-B endpoint. -/
theorem canonicalPhysicalScalarProgramPBPreferredClosure_available : True :=
  P0EFTJanusMappingTorusCanonicalPhysicalScalarIntrinsicWaveNormalTangentialRieszScalarEnergyMinimalProgramPClosure4D.canonicalPhysicalScalarIntrinsicWaveNormalTangentialRieszScalarEnergyMinimalProgramPClosure_available

/-- Marker for the preferred standard boundary families. -/
theorem canonicalPhysicalScalarProgramPBPreferredStandardBoundaries_available : True :=
  P0EFTJanusMappingTorusCanonicalPhysicalScalarIntrinsicWaveNormalTangentialRieszScalarEnergyStandardBoundaryProgramPClosure4D.canonicalPhysicalScalarIntrinsicWaveNormalTangentialRieszScalarEnergyStandardBoundaryProgramPClosure_available

end
end P0EFTJanusMappingTorusCanonicalPhysicalScalarProgramPBPreferredClosure4D
end JanusFormal
