import JanusFormal.Branches.FundamentalGeometryPVariationalPrinciple.Gates.P0EFTJanusProgramPD9PrimitiveSpinCHopfZeroModeSpectralRealization4D
import JanusFormal.Branches.FundamentalGeometryPVariationalPrinciple.Gates.P0EFTJanusProgramPD9PrimitiveSpinCFirstPositiveSphereDirac4D

/-!
# Dirac automorphism on one geometric Hopf zero-mode complex line

The quarter-root boundary condition forbids a zero normal momentum.  Hence
the genuine Hopf zero-mode complex line is not merely invariant under the
actual differential Dirac operator: its restriction is the nonzero scalar
`-k`, and therefore an explicit linear automorphism.
-/

namespace JanusFormal
namespace P0EFTJanusProgramPD9PrimitiveSpinCHopfZeroModeComplexAutomorphism4D

set_option autoImplicit false
noncomputable section

open P0EFTJanusNormalPinLiftBoundaryConditions
open P0EFTJanusProgramPD9PrimitiveSpinCFirstPositiveSphereDirac4D
open P0EFTJanusProgramPD9PrimitiveSpinCGeometricDiracDescent4D
open P0EFTJanusProgramPD9PrimitiveSpinCHopfZeroModeSpectralRealization4D
open P0EFTJanusProgramPD9PrimitiveSpinCNormalModeSection4D
open P0EFTJanusProgramPD9PrimitiveSpinCSmoothSectionCore4D

variable (period : Real) (hPeriod : period ≠ 0)

include hPeriod

/-- The Levi--Civita-corrected quarter-twisted normal frequency never
vanishes. -/
theorem normalRootLeviCivitaCorrectedFrequency_ne_zero
    (sector : NormalRootChoice) (mode : Int) :
    normalRootLeviCivitaCorrectedFrequency period sector mode ≠ 0 := by
  rw [normalRootLeviCivitaCorrectedFrequency_eq
    period hPeriod sector mode]
  have hNumerator :
      (normalRootModeNumerator sector mode : Real) ≠ 0 := by
    exact_mod_cast normal_root_mode_numerator_nonzero sector mode
  exact div_ne_zero
    (mul_ne_zero Real.pi_ne_zero hNumerator)
    (mul_ne_zero (by norm_num) hPeriod)

/-- The geometric complex line generated by one complete Hopf zero mode. -/
abbrev PrimitiveSpinCHopfZeroModeComplexSpan
    (sector : NormalRootChoice) (mode : Int) :=
  LinearMap.range
    (primitiveSpinCHopfZeroModeCoefficientLinearMap
      period hPeriod (sector, mode))

/-- The actual geometric Dirac operator preserves one Hopf zero-mode complex
line. -/
theorem primitiveSpinCHopfZeroModeComplexSpan_dirac_mem
    (sector : NormalRootChoice) (mode : Int)
    (state : PrimitiveSpinCHopfZeroModeComplexSpan
      period hPeriod sector mode) :
    d9PrimitiveSpinCGeometricDiracOperator
        period hPeriod .positiveQuarter state.1 ∈
      PrimitiveSpinCHopfZeroModeComplexSpan
        period hPeriod sector mode := by
  rcases state.property with ⟨coefficient, hCoefficient⟩
  refine ⟨(-normalRootLeviCivitaCorrectedFrequency
    period sector mode) • coefficient, ?_⟩
  rw [map_smul, ← hCoefficient]
  exact
    (primitiveSpinCHopfZeroModeCoefficientGeometricDiracOperator_eigen
      period hPeriod (sector, mode) coefficient).symm

/-- Restriction of the genuine differential Dirac operator to one Hopf
zero-mode complex line. -/
def primitiveSpinCHopfZeroModeComplexActualDirac
    (sector : NormalRootChoice) (mode : Int) :
    PrimitiveSpinCHopfZeroModeComplexSpan
        period hPeriod sector mode →ₗ[Real]
      PrimitiveSpinCHopfZeroModeComplexSpan
        period hPeriod sector mode where
  toFun state :=
    ⟨d9PrimitiveSpinCGeometricDiracOperator
        period hPeriod .positiveQuarter state.1,
      primitiveSpinCHopfZeroModeComplexSpan_dirac_mem
        period hPeriod sector mode state⟩
  map_add' first second := by
    apply Subtype.ext
    exact d9PrimitiveSpinCGeometricDiracOperator_add
      period hPeriod first.1 second.1
  map_smul' scalar state := by
    apply Subtype.ext
    exact d9PrimitiveSpinCGeometricDiracOperator_real_smul
      period hPeriod .positiveQuarter scalar state.1

/-- On the geometric range, the actual differential Dirac operator is exactly
the nonzero scalar `-k`. -/
theorem primitiveSpinCHopfZeroModeComplexActualDirac_eq_smul
    (sector : NormalRootChoice) (mode : Int)
    (state : PrimitiveSpinCHopfZeroModeComplexSpan
      period hPeriod sector mode) :
    primitiveSpinCHopfZeroModeComplexActualDirac
        period hPeriod sector mode state =
      (-normalRootLeviCivitaCorrectedFrequency
        period sector mode) • state := by
  rcases state.property with ⟨coefficient, hCoefficient⟩
  apply Subtype.ext
  change
    d9PrimitiveSpinCGeometricDiracOperator
        period hPeriod .positiveQuarter state.1 =
      (-normalRootLeviCivitaCorrectedFrequency
        period sector mode) • state.1
  rw [← hCoefficient]
  exact
    primitiveSpinCHopfZeroModeCoefficientGeometricDiracOperator_eigen
      period hPeriod (sector, mode) coefficient

/-- Explicit inverse scalar on the genuine Hopf zero-mode line. -/
def primitiveSpinCHopfZeroModeComplexActualDiracInverse
    (sector : NormalRootChoice) (mode : Int) :
    PrimitiveSpinCHopfZeroModeComplexSpan
        period hPeriod sector mode →ₗ[Real]
      PrimitiveSpinCHopfZeroModeComplexSpan
        period hPeriod sector mode :=
  (-normalRootLeviCivitaCorrectedFrequency
    period sector mode)⁻¹ • LinearMap.id

@[simp]
theorem primitiveSpinCHopfZeroModeComplexActualDiracInverse_apply
    (sector : NormalRootChoice) (mode : Int)
    (state : PrimitiveSpinCHopfZeroModeComplexSpan
      period hPeriod sector mode) :
    primitiveSpinCHopfZeroModeComplexActualDiracInverse
        period hPeriod sector mode state =
      (-normalRootLeviCivitaCorrectedFrequency
        period sector mode)⁻¹ • state :=
  rfl

/-- The explicit scalar inverse is a left inverse. -/
theorem primitiveSpinCHopfZeroModeComplexActualDiracInverse_left
    (sector : NormalRootChoice) (mode : Int)
    (state : PrimitiveSpinCHopfZeroModeComplexSpan
      period hPeriod sector mode) :
    primitiveSpinCHopfZeroModeComplexActualDiracInverse
        period hPeriod sector mode
        (primitiveSpinCHopfZeroModeComplexActualDirac
          period hPeriod sector mode state) =
      state := by
  rw [primitiveSpinCHopfZeroModeComplexActualDiracInverse_apply,
    primitiveSpinCHopfZeroModeComplexActualDirac_eq_smul,
    ← mul_smul]
  have hFrequency :=
    normalRootLeviCivitaCorrectedFrequency_ne_zero
      period hPeriod sector mode
  simp [hFrequency]

/-- The explicit scalar inverse is also a right inverse. -/
theorem primitiveSpinCHopfZeroModeComplexActualDiracInverse_right
    (sector : NormalRootChoice) (mode : Int)
    (state : PrimitiveSpinCHopfZeroModeComplexSpan
      period hPeriod sector mode) :
    primitiveSpinCHopfZeroModeComplexActualDirac
        period hPeriod sector mode
        (primitiveSpinCHopfZeroModeComplexActualDiracInverse
          period hPeriod sector mode state) =
      state := by
  rw [primitiveSpinCHopfZeroModeComplexActualDiracInverse_apply,
    map_smul,
    primitiveSpinCHopfZeroModeComplexActualDirac_eq_smul,
    ← mul_smul]
  have hFrequency :=
    normalRootLeviCivitaCorrectedFrequency_ne_zero
      period hPeriod sector mode
  simp [hFrequency]

/-- Exact linear equivalence induced by the actual differential Dirac operator
on one Hopf zero-mode complex line. -/
def primitiveSpinCHopfZeroModeComplexActualDiracLinearEquiv
    (sector : NormalRootChoice) (mode : Int) :
    PrimitiveSpinCHopfZeroModeComplexSpan
        period hPeriod sector mode ≃ₗ[Real]
      PrimitiveSpinCHopfZeroModeComplexSpan
        period hPeriod sector mode where
  toLinearMap :=
    primitiveSpinCHopfZeroModeComplexActualDirac
      period hPeriod sector mode
  invFun :=
    primitiveSpinCHopfZeroModeComplexActualDiracInverse
      period hPeriod sector mode
  left_inv :=
    primitiveSpinCHopfZeroModeComplexActualDiracInverse_left
      period hPeriod sector mode
  right_inv :=
    primitiveSpinCHopfZeroModeComplexActualDiracInverse_right
      period hPeriod sector mode

/-- The genuine Hopf zero-mode Dirac restriction is bijective. -/
theorem primitiveSpinCHopfZeroModeComplexActualDirac_bijective
    (sector : NormalRootChoice) (mode : Int) :
    Function.Bijective
      (primitiveSpinCHopfZeroModeComplexActualDirac
        period hPeriod sector mode) :=
  (primitiveSpinCHopfZeroModeComplexActualDiracLinearEquiv
    period hPeriod sector mode).bijective

/-- Its geometric kernel is exactly zero. -/
theorem primitiveSpinCHopfZeroModeComplexActualDirac_ker_eq_bot
    (sector : NormalRootChoice) (mode : Int) :
    LinearMap.ker
        (primitiveSpinCHopfZeroModeComplexActualDirac
          period hPeriod sector mode) = ⊥ := by
  exact LinearMap.ker_eq_bot.mpr
    (primitiveSpinCHopfZeroModeComplexActualDirac_bijective
      period hPeriod sector mode).1

/-- Consolidated operator-level closure of one complex Hopf zero mode. -/
theorem primitiveSpinCHopfZeroModeComplexActualDiracAutomorphism_closed
    (sector : NormalRootChoice) (mode : Int) :
    (∀ state : PrimitiveSpinCHopfZeroModeComplexSpan
        period hPeriod sector mode,
      primitiveSpinCHopfZeroModeComplexActualDirac
          period hPeriod sector mode state =
        (-normalRootLeviCivitaCorrectedFrequency
          period sector mode) • state) ∧
      Function.Bijective
        (primitiveSpinCHopfZeroModeComplexActualDirac
          period hPeriod sector mode) ∧
      LinearMap.ker
          (primitiveSpinCHopfZeroModeComplexActualDirac
            period hPeriod sector mode) = ⊥ :=
  ⟨primitiveSpinCHopfZeroModeComplexActualDirac_eq_smul
      period hPeriod sector mode,
    primitiveSpinCHopfZeroModeComplexActualDirac_bijective
      period hPeriod sector mode,
    primitiveSpinCHopfZeroModeComplexActualDirac_ker_eq_bot
      period hPeriod sector mode⟩

end
end P0EFTJanusProgramPD9PrimitiveSpinCHopfZeroModeComplexAutomorphism4D
end JanusFormal
