import Mathlib.Analysis.Calculus.FDeriv.Comp
import Mathlib.Analysis.Calculus.FDeriv.Add
import Mathlib.Analysis.Calculus.FDeriv.Congr
import Mathlib.Analysis.InnerProductSpace.Dual

/-!
# Infinitesimal symmetry orbits produce Hessian zero modes

A physical zero mode should not be inserted into the kernel of the Hessian by
hand.  For an affine one-parameter symmetry direction `v`, local invariance of
the action gradient along

`x(t) = x₀ + t • v`

forces the derivative of that gradient in the direction `v` to vanish.  This
is exactly the statement that `v` belongs to the kernel of the genuine second
Fréchet derivative.

The final lemma transports this vanishing to the Riesz representative on a
real Hilbert space.  It is the generic Noether-to-kernel bridge used by the
Candidate-A named-mode frontier; no projector, quotient or replacement action
is introduced.
-/

namespace JanusFormal
namespace P0EFTJanusProgramPSymmetryOrbitHessianKernel4D

set_option autoImplicit false
noncomputable section

open Filter Topology

variable {E F : Type*}
  [NormedAddCommGroup E] [NormedSpace Real E]
  [NormedAddCommGroup F] [NormedSpace Real F]

/-- Continuous linear map `t ↦ t • v`. -/
def scalarOrbitLinearMap (vector : E) : Real →L[Real] E :=
  (LinearMap.toSpanSingleton Real E vector).toContinuousLinearMap

@[simp]
theorem scalarOrbitLinearMap_apply
    (vector : E) (scalar : Real) :
    scalarOrbitLinearMap vector scalar = scalar • vector :=
  rfl

/-- Affine one-parameter orbit through `point` generated by `vector`. -/
def affineSymmetryOrbit (point vector : E) (parameter : Real) : E :=
  point + scalarOrbitLinearMap vector parameter

@[simp]
theorem affineSymmetryOrbit_zero (point vector : E) :
    affineSymmetryOrbit point vector 0 = point := by
  simp [affineSymmetryOrbit]

/-- The affine orbit has constant Fréchet derivative `t ↦ t • vector`. -/
theorem affineSymmetryOrbit_hasFDerivAt
    (point vector : E) (parameter : Real) :
    HasFDerivAt (affineSymmetryOrbit point vector)
      (scalarOrbitLinearMap vector) parameter := by
  unfold affineSymmetryOrbit
  apply (hasFDerivAt_const_add_iff point).2
  exact (scalarOrbitLinearMap vector).hasFDerivAt

/-- Local invariance of a map along one affine symmetry orbit.  In the main
application the map is the action gradient. -/
def OrbitEventuallyInvariantAt
    (map : E → F) (point vector : E) : Prop :=
  (fun parameter : Real =>
      map (affineSymmetryOrbit point vector parameter)) =ᶠ[𝓝 0]
    fun _ : Real => map point

/-- Differentiating an eventually invariant orbit shows that the derivative of
the map annihilates the orbit generator. -/
theorem fderiv_apply_eq_zero_of_orbitEventuallyInvariant
    (map : E → F) (point vector : E)
    (hDifferentiable : DifferentiableAt Real map point)
    (hInvariant : OrbitEventuallyInvariantAt map point vector) :
    fderiv Real map point vector = 0 := by
  have hOrbitDifferentiable : DifferentiableAt Real
      (affineSymmetryOrbit point vector) 0 :=
    (affineSymmetryOrbit_hasFDerivAt point vector 0).differentiableAt
  have hMapAtOrbit : DifferentiableAt Real map
      (affineSymmetryOrbit point vector 0) := by
    simpa using hDifferentiable
  have hChain :
      fderiv Real
          (fun parameter : Real =>
            map (affineSymmetryOrbit point vector parameter)) 0 =
        (fderiv Real map point).comp (scalarOrbitLinearMap vector) := by
    have hOrbit := affineSymmetryOrbit_hasFDerivAt point vector 0
    have hComp := hMapAtOrbit.hasFDerivAt.comp 0 hOrbit
    simpa [Function.comp_def] using hComp.fderiv
  have hOrbitDerivativeZero :
      fderiv Real
          (fun parameter : Real =>
            map (affineSymmetryOrbit point vector parameter)) 0 = 0 := by
    calc
      fderiv Real
          (fun parameter : Real =>
            map (affineSymmetryOrbit point vector parameter)) 0 =
          fderiv Real (fun _ : Real => map point) 0 :=
        hInvariant.fderiv_eq
      _ = 0 := by simp
  have hCompositeZero :
      (fderiv Real map point).comp (scalarOrbitLinearMap vector) = 0 := by
    rw [← hChain]
    exact hOrbitDerivativeZero
  have hAtOne := congrArg
    (fun derivative : Real →L[Real] F => derivative 1) hCompositeZero
  simpa [ContinuousLinearMap.comp_apply] using hAtOne

/-- Invariance of the genuine action gradient along one orbit. -/
def ActionGradientOrbitEventuallyInvariantAt
    (action : E → Real) (point vector : E) : Prop :=
  OrbitEventuallyInvariantAt
    (fun state => fderiv Real action state) point vector

/-- Noether kernel lemma in second-Fréchet form. -/
theorem secondFrechet_apply_eq_zero_of_gradientOrbitInvariant
    (action : E → Real) (point vector : E)
    (hGradientDifferentiable : DifferentiableAt Real
      (fun state => fderiv Real action state) point)
    (hInvariant :
      ActionGradientOrbitEventuallyInvariantAt action point vector) :
    fderiv Real (fun state => fderiv Real action state) point vector = 0 :=
  fderiv_apply_eq_zero_of_orbitEventuallyInvariant
    (fun state => fderiv Real action state) point vector
      hGradientDifferentiable hInvariant

section Hilbert

variable {H : Type*}
  [NormedAddCommGroup H] [InnerProductSpace Real H] [CompleteSpace H]

/-- If one slot of a bounded bilinear form vanishes, so does the corresponding
Riesz vector. -/
theorem continuousLinearMapOfBilin_apply_eq_zero
    (form : H →L[Real] H →L[Real] Real)
    (vector : H) (hVector : form vector = 0) :
    InnerProductSpace.continuousLinearMapOfBilin (𝕜 := Real) form vector = 0 := by
  change (InnerProductSpace.toDual Real H).symm (form vector) = 0
  rw [hVector]
  simp

/-- Direct Noether-to-Riesz-kernel bridge. -/
theorem riesz_apply_eq_zero_of_gradientOrbitInvariant
    (action : H → Real) (point vector : H)
    (hGradientDifferentiable : DifferentiableAt Real
      (fun state => fderiv Real action state) point)
    (hInvariant :
      ActionGradientOrbitEventuallyInvariantAt action point vector) :
    let form := fderiv Real (fun state => fderiv Real action state) point
    InnerProductSpace.continuousLinearMapOfBilin (𝕜 := Real) form vector = 0 := by
  dsimp only
  exact continuousLinearMapOfBilin_apply_eq_zero
    (fderiv Real (fun state => fderiv Real action state) point) vector
    (secondFrechet_apply_eq_zero_of_gradientOrbitInvariant action point vector
      hGradientDifferentiable hInvariant)

/-- Public generic checkpoint. -/
theorem symmetry_orbit_hessian_kernel_gate
    (action : E → Real) (point vector : E)
    (hGradientDifferentiable : DifferentiableAt Real
      (fun state => fderiv Real action state) point)
    (hInvariant :
      ActionGradientOrbitEventuallyInvariantAt action point vector) :
    fderiv Real (fun state => fderiv Real action state) point vector = 0 :=
  secondFrechet_apply_eq_zero_of_gradientOrbitInvariant action point vector
    hGradientDifferentiable hInvariant

end Hilbert

end
end P0EFTJanusProgramPSymmetryOrbitHessianKernel4D
end JanusFormal
