import JanusFormal.Branches.FundamentalGeometryPVariationalPrinciple.Gates.P0EFTJanusProgramPGlobalHessianPreferredFiveSectorH14D11SelectedTraceShortDominatedProductThroatLongTimeSpectralReferenceAtlas4D
import JanusFormal.Branches.FundamentalGeometryPVariationalPrinciple.Gates.P0EFTJanusProgramPIntrinsicNuclearTraceBoundedComposition4D
import JanusFormal.Branches.FundamentalGeometryPVariationalPrinciple.Gates.P0EFTJanusProgramPRelativeNuclearMellinDifferenceFamily4D
import JanusFormal.Branches.FundamentalGeometryPVariationalPrinciple.Gates.P0EFTJanusProgramPNuclearHeatCanonicalDuhamelTraceVariationFrontend4D
import JanusFormal.Branches.FundamentalGeometryPVariationalPrinciple.Gates.P0EFTJanusProgramPNuclearHeatUnitaryConjugatedCanonicalDuhamelFrontend4D
import JanusFormal.Branches.FundamentalGeometryPVariationalPrinciple.Gates.P0EFTJanusProgramPNuclearHeatUnitaryConjugatedCommutatorDuhamelFrontend4D
import JanusFormal.Branches.FundamentalGeometryPVariationalPrinciple.Gates.P0EFTJanusProgramPOperatorNormDifferentiableUnitaryGreenConjugation4D
import JanusFormal.Branches.FundamentalGeometryPVariationalPrinciple.Gates.P0EFTJanusProgramPGlobalCandidateAProductThroatSpectralIdentification4D
import JanusFormal.Branches.FundamentalGeometryPVariationalPrinciple.Gates.P0EFTJanusProgramPIntrinsicNuclearTraceIsometricEquivalenceTransport4D
import JanusFormal.Branches.FundamentalGeometryPVariationalPrinciple.Gates.P0EFTJanusProgramPReferenceProductThroatHeatOperatorIdentification4D
import JanusFormal.Branches.FundamentalGeometryPVariationalPrinciple.Gates.P0EFTJanusProgramPReferenceProductThroatRealHeatTraceContinuity4D
import JanusFormal.Branches.FundamentalGeometryPVariationalPrinciple.Gates.P0EFTJanusProgramPReferenceProductThroatRealHeatTraceExpansionFrontend4D
import JanusFormal.Branches.FundamentalGeometryPVariationalPrinciple.Gates.P0EFTJanusProductThroatHeatOperatorRealNuclearExpansion4D
import JanusFormal.Branches.FundamentalGeometryPVariationalPrinciple.Gates.P0EFTJanusProgramPProductThroatNuclearHeatDuhamelFiniteCountertermOperatorFrontend4D
import JanusFormal.Branches.FundamentalGeometryPVariationalPrinciple.Gates.P0EFTJanusProgramPProductThroatSphereNuclearFiniteCountertermSpectralBasepointFrontend4D
import JanusFormal.Branches.FundamentalGeometryPVariationalPrinciple.Gates.P0EFTJanusProgramPProductThroatSphereReferenceHeatDuhamelDifferentiableCanonicalSchwarzFrontend4D
import JanusFormal.Branches.FundamentalGeometryPVariationalPrinciple.Gates.P0EFTJanusProgramPProductThroatNuclearHeatDuhamelRealTraceLongTimeExponential4D
import JanusFormal.Branches.FundamentalGeometryPVariationalPrinciple.Gates.P0EFTJanusProgramPNuclearDuhamelProductThroatLongTimeDominatedCountableCollapsedRankOneIntegral4D
import JanusFormal.Branches.FundamentalGeometryPVariationalPrinciple.Gates.P0EFTJanusProgramPProductThroatNuclearHeatDuhamelFinitePartFamilyFrontend4D
import JanusFormal.Branches.FundamentalGeometryPVariationalPrinciple.Gates.P0EFTJanusProgramPProductThroatReferenceHeatDuhamelGeneratedFinitePartAssembly4D
import JanusFormal.Branches.FundamentalGeometryPVariationalPrinciple.Gates.P0EFTJanusProgramPProductThroatNuclearDuhamelCountableRankOneBochnerOperatorIntegral4D
import JanusFormal.Branches.FundamentalGeometryPVariationalPrinciple.Gates.P0EFTJanusProgramPProductThroatNuclearDuhamelLocallyUniformBochnerOperatorIntegral4D
import JanusFormal.Branches.FundamentalGeometryPVariationalPrinciple.Gates.P0EFTJanusProgramPProductThroatSphereNuclearBasepointFullyCountableOperatorBoundaryFrontend4D
import JanusFormal.Branches.FundamentalGeometryPVariationalPrinciple.Gates.P0EFTJanusProgramPProductThroatReferenceNuclearDuhamelFullyCountableTerminalBoundaryFrontend4D
import JanusFormal.Branches.FundamentalGeometryPVariationalPrinciple.Gates.P0EFTJanusProgramPProductThroatReferenceHeatDuhamelOperatorGeneratedFinitePartAssembly4D
import JanusFormal.Branches.FundamentalGeometryPVariationalPrinciple.Gates.P0EFTJanusProgramPProductThroatReferenceHeatDuhamelOperatorGeneratedCanonicalSchwarzAssembly4D
import JanusFormal.Branches.FundamentalGeometryPVariationalPrinciple.Gates.P0EFTJanusProgramPProductThroatReferenceHeatDuhamelOperatorGeneratedCanonicalSchwarzAtlas4D
import JanusFormal.Branches.FundamentalGeometryPVariationalPrinciple.Gates.P0EFTJanusProgramPProductThroatReferenceNuclearDuhamelLocallyUniformFullyCountableTerminalBoundary4D
import JanusFormal.Branches.FundamentalGeometryPVariationalPrinciple.Gates.P0EFTJanusProgramPProductThroatReferenceHeatDuhamelLocallyUniformOperatorGeneratedCanonicalSchwarzAssembly4D
import JanusFormal.Branches.FundamentalGeometryPVariationalPrinciple.Gates.P0EFTJanusProgramPProductThroatReferenceHeatDuhamelLocallyUniformCanonicalSchwarzAtlas4D
import JanusFormal.Branches.FundamentalGeometryPVariationalPrinciple.Gates.P0EFTJanusProgramPProductThroatReferenceHeatDuhamelDifferentiableCanonicalSchwarzAssembly4D
import JanusFormal.Branches.FundamentalGeometryPVariationalPrinciple.Gates.P0EFTJanusProgramPProductThroatReferenceHeatDuhamelDifferentiableCanonicalSchwarzAtlas4D
import JanusFormal.Branches.FundamentalGeometryPVariationalPrinciple.Gates.P0EFTJanusProgramPProductThroatNuclearHeatDuhamelBasepointFinitePartFamilyFrontend4D
import JanusFormal.Branches.FundamentalGeometryPVariationalPrinciple.Gates.P0EFTJanusProgramPProductThroatReferenceHeatDuhamelBasepointDifferentiableCanonicalSchwarzAssembly4D
import JanusFormal.Branches.FundamentalGeometryPVariationalPrinciple.Gates.P0EFTJanusProgramPProductThroatReferenceHeatDuhamelBasepointDifferentiableCanonicalSchwarzAtlas4D
import JanusFormal.Branches.FundamentalGeometryPVariationalPrinciple.Gates.P0EFTJanusProgramPProductThroatNuclearHeatDuhamelContinuousBasepointFinitePartFamilyFrontend4D
import JanusFormal.Branches.FundamentalGeometryPVariationalPrinciple.Gates.P0EFTJanusProgramPProductThroatReferenceHeatDuhamelContinuousBasepointDifferentiableCanonicalSchwarzAssembly4D
import JanusFormal.Branches.FundamentalGeometryPVariationalPrinciple.Gates.P0EFTJanusProgramPProductThroatReferenceHeatDuhamelContinuousBasepointDifferentiableCanonicalSchwarzAtlas4D
import JanusFormal.Branches.FundamentalGeometryPVariationalPrinciple.Gates.P0EFTJanusProgramPGlobalCandidateAProductThroatContinuousBasepointDifferentiableCanonicalSchwarzAtlas4D
import JanusFormal.Branches.FundamentalGeometryPVariationalPrinciple.Gates.P0EFTJanusProgramPLinearNaturalRepresentationAdmissibleIsomorphismFamilySectorMetric4D
import JanusFormal.Branches.FundamentalGeometryPVariationalPrinciple.Gates.P0EFTJanusProgramPGlobalHessianPreferredFiveSectorD11NamedKernelFamilyAdapter4D
import JanusFormal.Branches.FundamentalGeometryPVariationalPrinciple.Gates.P0EFTJanusProgramPProductThroatLongTimeD11NamedKernelTerminalAdapter4D
import JanusFormal.Branches.FundamentalGeometryPVariationalPrinciple.Gates.P0EFTJanusProgramPProductThroatLongTimeD11ConstructedNaturalBasepointFrameSectorNormTransportTerminal4D

/-!
# Terminal H14--D11 facade with concrete product-throat long-time decay

This is the strongest current dependency checkpoint for the Candidate-A
selected-trace determinant route.

For the base reference and every local spectral-cut reference, the long-time
analysis is no longer parameterized by an arbitrary positive rate.  A genuine
circle-times-monopole-sphere spectrum supplies

```text
c_ref = 1 / R_ref^2 > 0.
```

The sphere eigenvalues are bounded below by `c_ref`, the circle square is
nonnegative, and the complete infinite product heat trace obeys

```text
Tr K_ref(t)
  ≤ exp(c_ref) Tr K_ref(1) exp(-c_ref t),
  t ≥ 1.
```

Two natural operator estimates then generate both long-time inputs:

```text
‖Tr D_ref,a(t)‖ ≤ B_a Tr K_ref(t),
‖terminalPrimitive_a(T)‖ ≤ C_a Tr K_ref(T).
```

Consequently the imported chain derives

* the nuclear certificate for the canonical heat derivative `(-t) D(t)` from
  the Duhamel certificate alone, and its scalar derivative for a unitarily
  conjugated heat family with traceless Duhamel insertion; a certified nuclear
  commutator supplies that vanishing trace by cyclicity;
* the real ProductThroat rank-one expansion and its exact factor-two trace
  normalization from the two real axes of every complex spectral mode; hence
  the strong finite-counterterm frontend now needs only operator conjugacy,
  not a separate heat-trace normalization;
* integrability of the weighted long-time Duhamel derivative;
* Bochner integrability of the complete locally uniform rank-one operator sum;
* differentiation under the long-time heat integral;
* decay of the terminal primitive;
* the exact long-time boundary identity;
* the selected endpoint trace `Tr(G_ref H'_ref)`;
* canonical Schwarz reality and the reference zeta coefficient;
* the physical D11 kernel family and determinant atlas; upstream of
  `NamedKernel`, the established stable-physical-form H12 packet now supplies
  the basepoint basis directly. The minimal kernel route asks differentiability
  only on those
  finitely many transported modes. An optional stronger route uses norm
  preservation plus one operator-norm derivative to construct a unitary frame
  and discharge every mode at once. The D11 family can now also instantiate the
  exact `NamedKernelFamilyClosure` carried by an H14 spectral-cut atlas, with
  basepoint agreement proved from identity transport; the terminal atlas can
  consume this constructed closure directly, without a separate named-kernel
  input. Lower-level H12
  alternatives remain one global Garding estimate or same-sector orthogonality
  plus the five-sector gap.

The short-time subtraction remains local and dominated, because its majorant
is controlled by the heat asymptotic expansion rather than by the positive
large-time spectral gap.

No H14 two-sided Fredholm norm gap is reinterpreted as positivity of the heat
generator.  The positive rate in this terminal facade comes solely from the
concrete product reference spectrum.
-/

namespace JanusFormal
namespace P0EFTJanusProgramPGlobalHessianPreferredFiveSectorH14D11SelectedTraceShortDominatedProductThroatLongTimeNuclearDuhamelZetaTerminal4D

set_option autoImplicit false
noncomputable section

end
end P0EFTJanusProgramPGlobalHessianPreferredFiveSectorH14D11SelectedTraceShortDominatedProductThroatLongTimeNuclearDuhamelZetaTerminal4D
end JanusFormal
