import JanusFormal.Branches.FundamentalGeometryPVariationalPrinciple.Gates.P0EFTJanusProgramPSelfAdjointFredholmComplexification4D

/-!
# Complex coordinates on the actual Fredholm determinant line

A nonzero complex family (in particular a reduced zeta determinant) now acts
on the honest scalar extension `Complex ⊗[Real] Det_Fred(H_a)`.  This is the
first layer where the finite Fredholm frame and the reduced complex coordinate
are no longer stored as unrelated components.

The remaining geometric theorem is to identify this complexified finite line
with the determinant line generated by the reduced family and to prove the
family regularity/connection compatibility of that identification.
-/

namespace JanusFormal
namespace P0EFTJanusProgramPSelfAdjointFredholmComplexCoordinateFamily4D

set_option autoImplicit false
set_option maxHeartbeats 5200000
set_option synthInstance.maxHeartbeats 2600000

noncomputable section

open P0EFTJanusProgramPSelfAdjointFredholmDeterminantLineFamily4D
open P0EFTJanusProgramPSelfAdjointFredholmComplexification4D

variable {E : Type*} {ZeroMode : Type}
  [NormedAddCommGroup E]
  [InnerProductSpace Real E] [CompleteSpace E]
  [Fintype ZeroMode] [DecidableEq ZeroMode] [LinearOrder ZeroMode]

/-- A nonvanishing complex coordinate family attached to the actual Fredholm
family.  The intended instance is the intrinsic reduced zeta determinant. -/
structure SelfAdjointFredholmComplexCoordinateFamilyData
    {operator : Real → E →L[Real] E}
    (fredholm : SelfAdjointFredholmDeterminantFamilyData operator ZeroMode) where
  coordinate : Real → Complex
  coordinate_ne_zero : ∀ parameter, coordinate parameter ≠ 0

namespace SelfAdjointFredholmComplexCoordinateFamilyData

/-- Genuine complex determinant section obtained by weighting the complexified
finite Fredholm frame. -/
def determinantSection
    {operator : Real → E →L[Real] E}
    {fredholm : SelfAdjointFredholmDeterminantFamilyData operator ZeroMode}
    (data : SelfAdjointFredholmComplexCoordinateFamilyData fredholm)
    (parameter : Real) : fredholm.complexifiedDeterminantLine parameter :=
  fredholm.complexifiedDeterminantSection parameter (data.coordinate parameter)

/-- Pointwise description of the determinant section in the canonical finite
Fredholm frame. -/
theorem determinantSection_eq_coordinate_smul_frame
    {operator : Real → E →L[Real] E}
    {fredholm : SelfAdjointFredholmDeterminantFamilyData operator ZeroMode}
    (data : SelfAdjointFredholmComplexCoordinateFamilyData fredholm)
    (parameter : Real) :
    data.determinantSection parameter =
      data.coordinate parameter • fredholm.complexifiedDeterminantFrame parameter :=
  rfl

/-- Reference changes act on the section by the same multiplicative scalar law
as on the complex coordinate.  This is the algebraic core needed by the
operator-generated spectral-cut atlas. -/
theorem determinantSection_reference_change
    {operator : Real → E →L[Real] E}
    {fredholm : SelfAdjointFredholmDeterminantFamilyData operator ZeroMode}
    (data : SelfAdjointFredholmComplexCoordinateFamilyData fredholm)
    (parameter : Real) (transition : Complex) :
    transition • data.determinantSection parameter =
      fredholm.complexifiedDeterminantSection parameter
        (transition * data.coordinate parameter) := by
  simp [determinantSection,
    SelfAdjointFredholmDeterminantFamilyData.complexifiedDeterminantSection,
    mul_smul]

/-- Public checkpoint joining a nonzero complex determinant coordinate to the
actual complexified finite Fredholm frame. -/
theorem self_adjoint_fredholm_complex_coordinate_family_gate
    {operator : Real → E →L[Real] E}
    {fredholm : SelfAdjointFredholmDeterminantFamilyData operator ZeroMode}
    (data : SelfAdjointFredholmComplexCoordinateFamilyData fredholm) :
    (∀ parameter, data.coordinate parameter ≠ 0) ∧
      (∀ parameter,
        data.determinantSection parameter =
          data.coordinate parameter •
            fredholm.complexifiedDeterminantFrame parameter) :=
  ⟨data.coordinate_ne_zero,
    data.determinantSection_eq_coordinate_smul_frame⟩

end SelfAdjointFredholmComplexCoordinateFamilyData

end
end P0EFTJanusProgramPSelfAdjointFredholmComplexCoordinateFamily4D
end JanusFormal
