import JanusFormal.Branches.FundamentalGeometryPVariationalPrinciple.Gates.P0EFTJanusMetricInducedScalarStressVariation4D
import JanusFormal.Branches.FundamentalGeometryPVariationalPrinciple.Gates.P0EFTJanusMatrixInteractionFrechetNoether

/-!
# Pointwise Hessian of the metric volume density in four dimensions

This gate differentiates the already derived first variation of
`sqrt |det g|` along a second affine metric direction.  It reuses the exact
inverse-metric derivative and the continuous trace covector; no independent
inverse or measure tangent is introduced.

The result is pointwise and finite-dimensional.  No spacetime integration or
infinite-dimensional metric chart is asserted here.
-/

namespace JanusFormal
namespace P0EFTJanusMetricVolumeDensityHessian4D

set_option autoImplicit false

noncomputable section

open scoped Matrix.Norms.Frobenius
open P0EFTJanusMetricInducedScalarStressVariation4D

abbrev Matrix4 := Matrix (Fin 4) (Fin 4) Real

/-- Trace of the inverse metric contracted with a fixed first direction,
evaluated along the affine curve in a second direction. -/
def inverseMetricTraceCurve
    (data : FixedSignMetric4)
    (first second : SymmetricMetricVariation4) (t : Real) : Real :=
  Matrix.trace
    (exactInverseMetricCurve data second t * first.tensor)

@[simp]
theorem inverseMetricTraceCurve_zero
    (data : FixedSignMetric4)
    (first second : SymmetricMetricVariation4) :
    inverseMetricTraceCurve data first second 0 =
      Matrix.trace (relativeMetricVariation data first) := by
  simp [inverseMetricTraceCurve, relativeMetricVariation]

/-- The inverse contribution to the mixed volume-density variation. -/
theorem inverseMetricTraceCurve_hasDerivAt
    (data : FixedSignMetric4)
    (first second : SymmetricMetricVariation4) :
    FrobeniusScalarHasDerivAt
      (inverseMetricTraceCurve data first second)
      (-Matrix.trace
        (relativeMetricVariation data first *
          relativeMetricVariation data second)) 0 := by
  unfold FrobeniusScalarHasDerivAt
  have hInverse := exactInverseMetricCurve_hasDerivAt data second
  unfold FrobeniusMatrixHasDerivAt at hInverse
  have hInverseDeriv :
      HasDerivAt (exactInverseMetricCurve data second)
        (-(data.metric⁻¹ * second.tensor * data.metric⁻¹)) 0 :=
    hInverse.hasDerivAt.congr_deriv (by simp)
  have hProduct := hInverseDeriv.mul_const first.tensor
  have hTrace :=
    P0EFTJanusMatrixInteractionFrechetNoether.traceCovector.hasFDerivAt
      |>.comp_hasDerivAt 0 hProduct
  have hDerivative :
      P0EFTJanusMatrixInteractionFrechetNoether.traceCovector
          (-(data.metric⁻¹ * second.tensor * data.metric⁻¹) *
            first.tensor) =
        -Matrix.trace
          (relativeMetricVariation data first *
            relativeMetricVariation data second) := by
    rw [P0EFTJanusMatrixInteractionFrechetNoether.traceCovector_apply]
    simp only [relativeMetricVariation]
    calc
      Matrix.trace
          (-(data.metric⁻¹ * second.tensor * data.metric⁻¹) *
            first.tensor) =
          -Matrix.trace
            ((data.metric⁻¹ * second.tensor * data.metric⁻¹) *
              first.tensor) := by
            rw [neg_mul, Matrix.trace_neg]
      _ = -Matrix.trace
          (first.tensor *
            (data.metric⁻¹ * second.tensor * data.metric⁻¹)) := by
            rw [Matrix.trace_mul_comm]
      _ = -Matrix.trace
          ((first.tensor * data.metric⁻¹ * second.tensor) *
            data.metric⁻¹) := by
            simp only [Matrix.mul_assoc]
      _ = -Matrix.trace
          (data.metric⁻¹ *
            (first.tensor * data.metric⁻¹ * second.tensor)) := by
            rw [Matrix.trace_mul_comm]
      _ = -Matrix.trace
          ((data.metric⁻¹ * first.tensor) *
            (data.metric⁻¹ * second.tensor)) := by
            simp only [Matrix.mul_assoc]
  exact (hTrace.congr_deriv hDerivative).hasFDerivAt

/-- The first volume-density variation in `first`, transported along the
affine metric curve generated by `second`. -/
def metricMeasureFirstVariationCurve
    (data : FixedSignMetric4)
    (first second : SymmetricMetricVariation4) (t : Real) : Real :=
  (Real.sqrt |Matrix.det (metricCurve data second t)| / 2) *
    inverseMetricTraceCurve data first second t

@[simp]
theorem metricMeasureFirstVariationCurve_zero
    (data : FixedSignMetric4)
    (first second : SymmetricMetricVariation4) :
    metricMeasureFirstVariationCurve data first second 0 =
      (Real.sqrt |Matrix.det data.metric| / 2) *
        Matrix.trace (relativeMetricVariation data first) := by
  simp [metricMeasureFirstVariationCurve]

/-- Polarized second variation of the metric volume density. -/
def metricMeasureMixedSecondVariation
    (data : FixedSignMetric4)
    (first second : SymmetricMetricVariation4) : Real :=
  Real.sqrt |Matrix.det data.metric| *
    ((1 / 4 : Real) *
        Matrix.trace (relativeMetricVariation data first) *
        Matrix.trace (relativeMetricVariation data second) -
      (1 / 2 : Real) *
        Matrix.trace
          (relativeMetricVariation data first *
            relativeMetricVariation data second))

/-- Exact mixed second derivative
`D² sqrt|det g|[first, second]`. -/
theorem metricMeasureFirstVariationCurve_hasDerivAt
    (data : FixedSignMetric4)
    (first second : SymmetricMetricVariation4) :
    HasDerivAt
      (metricMeasureFirstVariationCurve data first second)
      (metricMeasureMixedSecondVariation data first second) 0 := by
  have hMeasure := (metricMeasureCurve_hasDerivAt data second).div_const 2
  have hTraceRaw := inverseMetricTraceCurve_hasDerivAt data first second
  unfold FrobeniusScalarHasDerivAt at hTraceRaw
  have hTrace :
      HasDerivAt (inverseMetricTraceCurve data first second)
        (-Matrix.trace
          (relativeMetricVariation data first *
            relativeMetricVariation data second)) 0 :=
    hTraceRaw.hasDerivAt.congr_deriv (by simp)
  have hProduct := hMeasure.mul hTrace
  refine hProduct.congr_deriv ?_
  simp only [metricCurve_zero, inverseMetricTraceCurve_zero]
  simp [metricMeasureMixedSecondVariation]
  ring

/-- The pointwise metric-volume Hessian is symmetric. -/
theorem metricMeasureMixedSecondVariation_symmetric
    (data : FixedSignMetric4)
    (first second : SymmetricMetricVariation4) :
    metricMeasureMixedSecondVariation data first second =
      metricMeasureMixedSecondVariation data second first := by
  simp only [metricMeasureMixedSecondVariation]
  rw [Matrix.trace_mul_comm
    (relativeMetricVariation data first)
    (relativeMetricVariation data second)]
  ring

end

end P0EFTJanusMetricVolumeDensityHessian4D
end JanusFormal
