import JanusFormal.Branches.FundamentalGeometryPVariationalPrinciple.Gates.P0EFTJanusMappingTorusCanonicalPhysicalScalarCanonicalFinalReducedVariational4D
import JanusFormal.Branches.FundamentalGeometryPVariationalPrinciple.Gates.P0EFTJanusMappingTorusScalarCompletedBoundaryTripleGaussian4D

/-!
# Final reduced physical scalar Gaussian response

The bounded resolvent generated by the positive shifted decomposition is the
Gaussian response operator of the final physical scalar realization.  This file
specializes the completed-boundary Gaussian theory to the smallest current
analytic endpoint.

It provides the symmetric two-source response, generating functional, exact
polarization, quadratic homogeneity, the on-shell action identity and
nonnegativity.
-/

namespace JanusFormal
namespace P0EFTJanusMappingTorusCanonicalPhysicalScalarCanonicalFinalReducedGaussian4D
end P0EFTJanusMappingTorusCanonicalPhysicalScalarCanonicalFinalReducedGaussian4D

namespace P0EFTJanusMappingTorusCanonicalPhysicalScalarCanonicalFinalReducedAnalyticClosure4D

set_option autoImplicit false
noncomputable section

open Set Topology
open P0EFTJanusMappingTorusCanonicalPhysicalScalarCanonicalFinalReducedAnalyticClosure4D
open P0EFTJanusMappingTorusCanonicalPhysicalScalarCanonicalFinalReducedVariational4D
open P0EFTJanusMappingTorusScalarCompletedBoundaryTripleGaussian4D

universe r

variable (period : Real) (hPeriod : period ≠ 0)
variable {massSquared : Real}
variable {Regularity : Type r}
  [NormedAddCommGroup Regularity] [NormedSpace Real Regularity]
  [CompleteSpace Regularity]

private abbrev BulkL2 :=
  P0EFTJanusMappingTorusCanonicalPhysicalBulkL2H1Bridge4D.CanonicalPhysicalBulkL2
    period hPeriod

namespace CanonicalPhysicalScalarCanonicalFinalReducedAnalyticData

/-- Symmetric Gaussian source pairing. -/
def gaussianPairing
    (analytic : CanonicalPhysicalScalarCanonicalFinalReducedAnalyticData
      period hPeriod massSquared (Regularity := Regularity))
    (first second : BulkL2 period hPeriod) : Real :=
  analytic.boundary.triple.lagrangianGaussianPairing
    analytic.condition analytic.referenceParameter
    (analytic.boundedResolvent period hPeriod) first second

/-- Gaussian generating functional. -/
def gaussianGeneratingFunctional
    (analytic : CanonicalPhysicalScalarCanonicalFinalReducedAnalyticData
      period hPeriod massSquared (Regularity := Regularity))
    (source : BulkL2 period hPeriod) : Real :=
  analytic.boundary.triple.lagrangianGaussianGeneratingFunctional
    analytic.condition analytic.referenceParameter
    (analytic.boundedResolvent period hPeriod) source

/-- Symmetry of the final physical Gaussian response. -/
theorem gaussianPairing_comm
    (analytic : CanonicalPhysicalScalarCanonicalFinalReducedAnalyticData
      period hPeriod massSquared (Regularity := Regularity))
    (first second : BulkL2 period hPeriod) :
    analytic.gaussianPairing period hPeriod first second =
      analytic.gaussianPairing period hPeriod second first :=
  analytic.boundary.triple.lagrangianGaussianPairing_comm
    analytic.condition analytic.referenceParameter
    (analytic.boundedResolvent period hPeriod) first second

/-- The generating functional is minus the on-shell source action. -/
theorem gaussianGeneratingFunctional_eq_neg_onShell
    (analytic : CanonicalPhysicalScalarCanonicalFinalReducedAnalyticData
      period hPeriod massSquared (Regularity := Regularity))
    (source : BulkL2 period hPeriod) :
    analytic.gaussianGeneratingFunctional period hPeriod source =
      -analytic.boundary.triple.lagrangianSourceAction
        analytic.condition analytic.referenceParameter source
        (analytic.sourceSolution period hPeriod source) := by
  unfold gaussianGeneratingFunctional sourceSolution
  exact analytic.boundary.triple
    |>.lagrangianGaussianGeneratingFunctional_eq_neg_onShell
      analytic.condition analytic.referenceParameter
      (analytic.boundedResolvent period hPeriod) source

/-- Exact polarization of the final generating functional. -/
theorem gaussianGeneratingFunctional_add
    (analytic : CanonicalPhysicalScalarCanonicalFinalReducedAnalyticData
      period hPeriod massSquared (Regularity := Regularity))
    (first second : BulkL2 period hPeriod) :
    analytic.gaussianGeneratingFunctional period hPeriod (first + second) =
      analytic.gaussianGeneratingFunctional period hPeriod first +
        analytic.gaussianGeneratingFunctional period hPeriod second +
        analytic.gaussianPairing period hPeriod first second :=
  analytic.boundary.triple.lagrangianGaussianGeneratingFunctional_add
    analytic.condition analytic.referenceParameter
    (analytic.boundedResolvent period hPeriod) first second

/-- Quadratic homogeneity of the generating functional. -/
theorem gaussianGeneratingFunctional_smul
    (analytic : CanonicalPhysicalScalarCanonicalFinalReducedAnalyticData
      period hPeriod massSquared (Regularity := Regularity))
    (scalar : Real) (source : BulkL2 period hPeriod) :
    analytic.gaussianGeneratingFunctional period hPeriod (scalar • source) =
      scalar ^ 2 *
        analytic.gaussianGeneratingFunctional period hPeriod source :=
  analytic.boundary.triple.lagrangianGaussianGeneratingFunctional_smul
    analytic.condition analytic.referenceParameter
    (analytic.boundedResolvent period hPeriod) scalar source

/-- Positive shifted decomposition makes the Gaussian response nonnegative. -/
theorem gaussianGeneratingFunctional_nonnegative
    (analytic : CanonicalPhysicalScalarCanonicalFinalReducedAnalyticData
      period hPeriod massSquared (Regularity := Regularity))
    (source : BulkL2 period hPeriod) :
    0 ≤ analytic.gaussianGeneratingFunctional period hPeriod source := by
  unfold gaussianGeneratingFunctional boundedResolvent
  exact (analytic.shiftedFormCoercive period hPeriod).gaussian_nonnegative
    analytic.boundary.triple analytic.condition analytic.referenceParameter
    (analytic.denseDomain period hPeriod) source

/-- Final reduced physical Gaussian certificate. -/
theorem gaussian_certificate
    (analytic : CanonicalPhysicalScalarCanonicalFinalReducedAnalyticData
      period hPeriod massSquared (Regularity := Regularity))
    (source : BulkL2 period hPeriod) :
    analytic.gaussianGeneratingFunctional period hPeriod source =
        -analytic.boundary.triple.lagrangianSourceAction
          analytic.condition analytic.referenceParameter source
          (analytic.sourceSolution period hPeriod source) ∧
      0 ≤ analytic.gaussianGeneratingFunctional period hPeriod source :=
  ⟨analytic.gaussianGeneratingFunctional_eq_neg_onShell
      period hPeriod source,
    analytic.gaussianGeneratingFunctional_nonnegative
      period hPeriod source⟩

end CanonicalPhysicalScalarCanonicalFinalReducedAnalyticData

end
end P0EFTJanusMappingTorusCanonicalPhysicalScalarCanonicalFinalReducedAnalyticClosure4D
end JanusFormal
