import JanusFormal.Branches.FundamentalGeometryPVariationalPrinciple.Gates.P0EFTJanusProgramPCandidateAFiveSectorProductOffDiagonalGarding4D

/-!
# Five-sector Gårding from the actual projected operator blocks

For a bounded self-adjoint principal operator `A` and the five projectors
produced by one orthogonal product decomposition, define

`A_diag = Σ_s P_s A P_s`,
`A_off  = A - A_diag`.

The bilinear form represented by `A_diag` is exactly the sum of the five
restricted diagonal forms.  Hence the complete off-diagonal form is represented
by `A_off`, and its bilinear-form norm is bounded by `‖A_off‖`.

This converts the preferred principal Gårding input to operator-level facts:

* five estimates for `⟪A P_s x, P_s x⟫`;
* one strict norm estimate for the single operator remainder `A_off`.

No ten independently supplied cross forms remain.
-/

namespace JanusFormal
namespace P0EFTJanusProgramPCandidateAFiveSectorProductOperatorOffDiagonalGarding4D

set_option autoImplicit false
set_option maxHeartbeats 4400000
set_option synthInstance.maxHeartbeats 2200000

noncomputable section

open scoped BigOperators InnerProductSpace
open P0EFTJanusProgramPFiveSectorOrthogonalProductResolution4D
open P0EFTJanusProgramPCandidateAFiveSectorProductResolutionAdapter4D
open P0EFTJanusProgramPCandidateAFiveSectorProductOffDiagonalGarding4D
open P0EFTJanusProgramPCandidateAFiveSectorPairwiseGarding4D
open P0EFTJanusProgramPGlobalCandidateANamedZeroModeSectors4D
open P0EFTJanusProgramPCandidateAZeroModeSector4D

variable
  {E Metric Abelian Matter Longitudinal Boundary : Type*}
  [NormedAddCommGroup E] [InnerProductSpace Real E] [CompleteSpace E]
  [NormedAddCommGroup Metric] [InnerProductSpace Real Metric]
  [NormedAddCommGroup Abelian] [InnerProductSpace Real Abelian]
  [NormedAddCommGroup Matter] [InnerProductSpace Real Matter]
  [NormedAddCommGroup Longitudinal] [InnerProductSpace Real Longitudinal]
  [NormedAddCommGroup Boundary] [InnerProductSpace Real Boundary]

/-- Continuous bilinear form represented by one bounded operator. -/
def operatorBilinearForm
    (operator : E →L[Real] E) : E →L[Real] E →L[Real] Real :=
  (innerSL Real).bilinearComp operator (ContinuousLinearMap.id Real E)

@[simp]
theorem operatorBilinearForm_apply
    (operator : E →L[Real] E) (first second : E) :
    operatorBilinearForm operator first second =
      inner Real (operator first) second :=
  rfl

/-- Passing from an operator to its represented bilinear form does not increase
operator norm. -/
theorem operatorBilinearForm_norm_le
    (operator : E →L[Real] E) :
    ‖operatorBilinearForm operator‖ ≤ ‖operator‖ := by
  apply (operatorBilinearForm operator).opNorm_le_bound (norm_nonneg operator)
  intro first
  calc
    ‖operatorBilinearForm operator first‖ ≤ ‖operator first‖ := by
      apply (operatorBilinearForm operator first).opNorm_le_bound
        (norm_nonneg (operator first))
      intro second
      change ‖inner Real (operator first) second‖ ≤
        ‖operator first‖ * ‖second‖
      exact norm_inner_le_norm (𝕜 := Real) (operator first) second
    _ ≤ ‖operator‖ * ‖first‖ := operator.le_opNorm first

/-- Operator-level five-sector principal packet. -/
structure CandidateAFiveSectorProductOperatorOffDiagonalGardingData
    (operator : E →L[Real] E) where
  operator_selfAdjoint : IsSelfAdjoint operator
  coordinates : FiveSectorOrthogonalProductDecomposition
    (E := E) (MetricDiffeomorphism := Metric) (AbelianGauge := Abelian)
    (PrimitiveSpinCMatter := Matter) (LongitudinalLL := Longitudinal)
    (BoundaryFiniteBV := Boundary)
  diagonalConstants : CandidateAFiveSectorDiagonalConstants
  diagonal_lower : ∀ sector vector,
    diagonalConstants.sectorConstant sector *
        ‖(candidateAFiveSectorSelfAdjointResolutionOfProduct coordinates).projection
          sector vector‖ ^ 2 ≤
      inner Real
        (operator
          ((candidateAFiveSectorSelfAdjointResolutionOfProduct coordinates).projection
            sector vector))
        ((candidateAFiveSectorSelfAdjointResolutionOfProduct coordinates).projection
          sector vector)
  offDiagonalOperator_small :
    ‖operator -
      ∑ sector : CandidateAZeroModeSector,
        ((candidateAFiveSectorSelfAdjointResolutionOfProduct coordinates).projection
          sector).comp
          (operator.comp
            ((candidateAFiveSectorSelfAdjointResolutionOfProduct coordinates).projection
              sector))‖ <
      diagonalConstants.sectorFloor

namespace CandidateAFiveSectorProductOperatorOffDiagonalGardingData

/-- Projection resolution generated by the one product coordinate system. -/
def resolution
    {operator : E →L[Real] E}
    (data : CandidateAFiveSectorProductOperatorOffDiagonalGardingData
      (Metric := Metric) (Abelian := Abelian) (Matter := Matter)
      (Longitudinal := Longitudinal) (Boundary := Boundary) operator) :=
  candidateAFiveSectorSelfAdjointResolutionOfProduct data.coordinates

/-- Sum of the five true diagonal operator blocks `P_s A P_s`. -/
def diagonalOperator
    {operator : E →L[Real] E}
    (data : CandidateAFiveSectorProductOperatorOffDiagonalGardingData
      (Metric := Metric) (Abelian := Abelian) (Matter := Matter)
      (Longitudinal := Longitudinal) (Boundary := Boundary) operator) :
    E →L[Real] E :=
  ∑ sector : CandidateAZeroModeSector,
    (data.resolution.projection sector).comp
      (operator.comp (data.resolution.projection sector))

/-- Single complete operator remainder. -/
def offDiagonalOperator
    {operator : E →L[Real] E}
    (data : CandidateAFiveSectorProductOperatorOffDiagonalGardingData
      (Metric := Metric) (Abelian := Abelian) (Matter := Matter)
      (Longitudinal := Longitudinal) (Boundary := Boundary) operator) :
    E →L[Real] E :=
  operator - data.diagonalOperator

/-- The bilinear form represented by the diagonal operator is exactly the sum
of the five diagonal restrictions of the principal form. -/
theorem diagonalOperator_form
    {operator : E →L[Real] E}
    (data : CandidateAFiveSectorProductOperatorOffDiagonalGardingData
      (Metric := Metric) (Abelian := Abelian) (Matter := Matter)
      (Longitudinal := Longitudinal) (Boundary := Boundary) operator) :
    operatorBilinearForm data.diagonalOperator =
      ∑ sector : CandidateAZeroModeSector,
        (operatorBilinearForm operator).bilinearComp
          (data.resolution.projection sector)
          (data.resolution.projection sector) := by
  ext first second
  simp only [diagonalOperator, operatorBilinearForm_apply,
    ContinuousLinearMap.sum_apply, ContinuousLinearMap.comp_apply,
    ContinuousLinearMap.bilinearComp_apply]
  change ((innerSL Real).flip second)
      (∑ sector, data.resolution.projection sector
        (operator (data.resolution.projection sector first))) = _
  rw [map_sum]
  apply Finset.sum_congr rfl
  intro sector _
  exact data.resolution.projection_symmetric sector
    (operator (data.resolution.projection sector first)) second

/-- The canonical off-diagonal principal form is represented by the single
operator remainder `A_off`. -/
theorem offDiagonalOperator_form
    {operator : E →L[Real] E}
    (data : CandidateAFiveSectorProductOperatorOffDiagonalGardingData
      (Metric := Metric) (Abelian := Abelian) (Matter := Matter)
      (Longitudinal := Longitudinal) (Boundary := Boundary) operator) :
    operatorBilinearForm operator -
        ∑ sector : CandidateAZeroModeSector,
          (operatorBilinearForm operator).bilinearComp
            (data.resolution.projection sector)
            (data.resolution.projection sector) =
      operatorBilinearForm data.offDiagonalOperator := by
  rw [← data.diagonalOperator_form]
  ext first second
  simp only [operatorBilinearForm_apply, ContinuousLinearMap.sub_apply,
    offDiagonalOperator]
  exact (inner_sub_left (operator first) (data.diagonalOperator first)
    second).symm

/-- Operator remainder smallness implies the exact off-diagonal form
smallness required by principal Gårding. -/
theorem offDiagonalForm_small
    {operator : E →L[Real] E}
    (data : CandidateAFiveSectorProductOperatorOffDiagonalGardingData
      (Metric := Metric) (Abelian := Abelian) (Matter := Matter)
      (Longitudinal := Longitudinal) (Boundary := Boundary) operator) :
    ‖operatorBilinearForm operator -
      ∑ sector : CandidateAZeroModeSector,
        (operatorBilinearForm operator).bilinearComp
          (data.resolution.projection sector)
          (data.resolution.projection sector)‖ <
      data.diagonalConstants.sectorFloor := by
  rw [data.offDiagonalOperator_form]
  exact lt_of_le_of_lt
    (operatorBilinearForm_norm_le data.offDiagonalOperator)
    (by simpa [offDiagonalOperator, diagonalOperator, resolution] using
      data.offDiagonalOperator_small)

/-- Convert operator block estimates to the established one-form Gårding
packet. -/
def toProductOffDiagonalGarding
    {operator : E →L[Real] E}
    (data : CandidateAFiveSectorProductOperatorOffDiagonalGardingData
      (Metric := Metric) (Abelian := Abelian) (Matter := Matter)
      (Longitudinal := Longitudinal) (Boundary := Boundary) operator) :
    CandidateAFiveSectorProductOffDiagonalGardingData
      (E := E) (Metric := Metric) (Abelian := Abelian) (Matter := Matter)
      (Longitudinal := Longitudinal) (Boundary := Boundary) where
  principalForm := operatorBilinearForm operator
  principal_symmetric := by
    intro first second
    calc
      inner Real (operator first) second =
          inner Real first (operator second) :=
        data.operator_selfAdjoint.isSymmetric first second
      _ = inner Real (operator second) first := real_inner_comm _ _
  coordinates := data.coordinates
  diagonalConstants := data.diagonalConstants
  diagonal_lower := data.diagonal_lower
  offDiagonal_small := data.offDiagonalForm_small

/-- Principal Gårding directly from projected operator blocks. -/
theorem candidateA_five_sector_product_operator_offDiagonal_garding_gate
    {operator : E →L[Real] E}
    (data : CandidateAFiveSectorProductOperatorOffDiagonalGardingData
      (Metric := Metric) (Abelian := Abelian) (Matter := Matter)
      (Longitudinal := Longitudinal) (Boundary := Boundary) operator) :
    0 < data.toProductOffDiagonalGarding.margin ∧
      ∀ vector : E,
        data.toProductOffDiagonalGarding.margin * ‖vector‖ ^ 2 ≤
          inner Real (operator vector) vector := by
  exact data.toProductOffDiagonalGarding
    |>.candidateA_five_sector_product_offDiagonal_garding_gate

end CandidateAFiveSectorProductOperatorOffDiagonalGardingData

end
end P0EFTJanusProgramPCandidateAFiveSectorProductOperatorOffDiagonalGarding4D
end JanusFormal
