import JanusFormal.Branches.FundamentalGeometryPVariationalPrinciple.Gates.P0EFTJanusProgramPCandidateAFiveSectorProductResolutionAdapter4D
import JanusFormal.Branches.FundamentalGeometryPVariationalPrinciple.Gates.P0EFTJanusProgramPFiniteSectorQuadraticGarding4D
import JanusFormal.Branches.FundamentalGeometryPVariationalPrinciple.Gates.P0EFTJanusProgramPCandidateAFiveSectorPairwiseGarding4D

/-!
# Principal Candidate-A Gårding from one five-factor product and one off-diagonal form

The strongest coordinate input is one orthogonal product decomposition

`E ≃ M × A × S × L × B`.

It canonically determines the five Candidate-A projections.  The principal
Hessian is then split definitionally into its five diagonal restrictions and
one complete off-diagonal remainder.  Five diagonal lower bounds and a single
strict norm comparison for this remainder imply the principal Gårding estimate.

No dependent Pi-space coordinates, separately supplied projections, ten cross
forms or block-expansion identity remain.
-/

namespace JanusFormal
namespace P0EFTJanusProgramPCandidateAFiveSectorProductOffDiagonalGarding4D

set_option autoImplicit false
set_option maxHeartbeats 4200000
set_option synthInstance.maxHeartbeats 2100000

noncomputable section

open scoped BigOperators InnerProductSpace
open P0EFTJanusProgramPCandidateAZeroModeSector4D
open P0EFTJanusProgramPFiveSectorOrthogonalProductResolution4D
open P0EFTJanusProgramPCandidateAFiveSectorProductResolutionAdapter4D
open P0EFTJanusProgramPCandidateAFiveSectorPairwiseGarding4D
open P0EFTJanusProgramPFiniteSectorQuadraticGarding4D
open P0EFTJanusProgramPGlobalCandidateANamedZeroModeSectors4D

variable
  {E Metric Abelian Matter Longitudinal Boundary : Type*}
  [NormedAddCommGroup E] [InnerProductSpace Real E]
  [NormedAddCommGroup Metric] [InnerProductSpace Real Metric]
  [NormedAddCommGroup Abelian] [InnerProductSpace Real Abelian]
  [NormedAddCommGroup Matter] [InnerProductSpace Real Matter]
  [NormedAddCommGroup Longitudinal] [InnerProductSpace Real Longitudinal]
  [NormedAddCommGroup Boundary] [InnerProductSpace Real Boundary]

/-- Principal data in the literal five-factor orthogonal coordinates. -/
structure CandidateAFiveSectorProductOffDiagonalGardingData where
  principalForm : E →L[Real] E →L[Real] Real
  principal_symmetric : ∀ first second,
    principalForm first second = principalForm second first
  coordinates : FiveSectorOrthogonalProductDecomposition
    (E := E) (MetricDiffeomorphism := Metric) (AbelianGauge := Abelian)
    (PrimitiveSpinCMatter := Matter) (LongitudinalLL := Longitudinal)
    (BoundaryFiniteBV := Boundary)
  diagonalConstants : CandidateAFiveSectorDiagonalConstants
  diagonal_lower : ∀ sector vector,
    diagonalConstants.sectorConstant sector *
        ‖(candidateAFiveSectorSelfAdjointResolutionOfProduct coordinates).projection
          sector vector‖ ^ 2 ≤
      principalForm
        ((candidateAFiveSectorSelfAdjointResolutionOfProduct coordinates).projection
          sector vector)
        ((candidateAFiveSectorSelfAdjointResolutionOfProduct coordinates).projection
          sector vector)
  offDiagonal_small :
    ‖principalForm -
      ∑ sector : CandidateAZeroModeSector,
        principalForm.bilinearComp
          ((candidateAFiveSectorSelfAdjointResolutionOfProduct coordinates).projection
            sector)
          ((candidateAFiveSectorSelfAdjointResolutionOfProduct coordinates).projection
            sector)‖ <
      diagonalConstants.sectorFloor

namespace CandidateAFiveSectorProductOffDiagonalGardingData

/-- Canonical Candidate-A projection resolution generated by the product
coordinates. -/
def resolution
    (data : CandidateAFiveSectorProductOffDiagonalGardingData
      (E := E) (Metric := Metric) (Abelian := Abelian) (Matter := Matter)
      (Longitudinal := Longitudinal) (Boundary := Boundary)) :=
  candidateAFiveSectorSelfAdjointResolutionOfProduct data.coordinates

/-- Five true diagonal restrictions of the principal Hessian. -/
def diagonalForm
    (data : CandidateAFiveSectorProductOffDiagonalGardingData
      (E := E) (Metric := Metric) (Abelian := Abelian) (Matter := Matter)
      (Longitudinal := Longitudinal) (Boundary := Boundary)) :
    E →L[Real] E →L[Real] Real :=
  ∑ sector : CandidateAZeroModeSector,
    data.principalForm.bilinearComp
      (data.resolution.projection sector)
      (data.resolution.projection sector)

/-- Unique complete off-diagonal remainder. -/
def offDiagonalForm
    (data : CandidateAFiveSectorProductOffDiagonalGardingData
      (E := E) (Metric := Metric) (Abelian := Abelian) (Matter := Matter)
      (Longitudinal := Longitudinal) (Boundary := Boundary)) :
    E →L[Real] E →L[Real] Real :=
  data.principalForm - data.diagonalForm

/-- Operator norm controls the off-diagonal quadratic energy. -/
theorem offDiagonal_quadratic_bound
    (data : CandidateAFiveSectorProductOffDiagonalGardingData
      (E := E) (Metric := Metric) (Abelian := Abelian) (Matter := Matter)
      (Longitudinal := Longitudinal) (Boundary := Boundary))
    (vector : E) :
    |data.offDiagonalForm vector vector| ≤
      ‖data.offDiagonalForm‖ * ‖vector‖ ^ 2 := by
  calc
    |data.offDiagonalForm vector vector| =
        ‖data.offDiagonalForm vector vector‖ := (Real.norm_eq_abs _).symm
    _ ≤ ‖data.offDiagonalForm vector‖ * ‖vector‖ :=
      (data.offDiagonalForm vector).le_opNorm vector
    _ ≤ (‖data.offDiagonalForm‖ * ‖vector‖) * ‖vector‖ :=
      mul_le_mul_of_nonneg_right
        (data.offDiagonalForm.le_opNorm vector) (norm_nonneg vector)
    _ = ‖data.offDiagonalForm‖ * ‖vector‖ ^ 2 := by ring

/-- Convert directly to the generic finite-sector Gårding packet. -/
def toFiniteSectorGarding
    (data : CandidateAFiveSectorProductOffDiagonalGardingData
      (E := E) (Metric := Metric) (Abelian := Abelian) (Matter := Matter)
      (Longitudinal := Longitudinal) (Boundary := Boundary)) :
    FiniteSectorQuadraticGardingData
      (Sector := CandidateAZeroModeSector) (E := E) where
  sectorWeight := fun sector vector => ‖data.resolution.projection sector vector‖ ^ 2
  sectorWeight_nonneg := fun _ _ => sq_nonneg _
  sectorWeight_sum := data.resolution.norm_sq_decomposition
  sectorConstant := data.diagonalConstants.sectorConstant
  sectorConstant_pos := data.diagonalConstants.sectorConstant_pos
  sectorFloor := data.diagonalConstants.sectorFloor
  sectorFloor_pos := data.diagonalConstants.sectorFloor_pos
  sectorFloor_le := data.diagonalConstants.sectorFloor_le
  diagonalEnergy := fun vector => data.diagonalForm vector vector
  diagonal_lower := by
    intro vector
    unfold diagonalForm
    simp only [ContinuousLinearMap.sum_apply,
      ContinuousLinearMap.bilinearComp_apply]
    apply Finset.sum_le_sum
    intro sector _
    exact data.diagonal_lower sector vector
  couplingEnergy := fun vector => data.offDiagonalForm vector vector
  couplingConstant := ‖data.offDiagonalForm‖
  couplingConstant_nonneg := norm_nonneg data.offDiagonalForm
  coupling_bound := data.offDiagonal_quadratic_bound
  coupling_small := by
    simpa [offDiagonalForm, diagonalForm, resolution] using data.offDiagonal_small
  principalEnergy := fun vector => data.principalForm vector vector
  principal_eq := by
    intro vector
    unfold offDiagonalForm
    simp only [ContinuousLinearMap.sub_apply]
    ring

/-- Explicit principal coercive margin. -/
def margin
    (data : CandidateAFiveSectorProductOffDiagonalGardingData
      (E := E) (Metric := Metric) (Abelian := Abelian) (Matter := Matter)
      (Longitudinal := Longitudinal) (Boundary := Boundary)) : Real :=
  data.diagonalConstants.sectorFloor - ‖data.offDiagonalForm‖

/-- Principal Gårding from exactly one orthogonal product decomposition and one
off-diagonal norm comparison. -/
theorem candidateA_five_sector_product_offDiagonal_garding_gate
    (data : CandidateAFiveSectorProductOffDiagonalGardingData
      (E := E) (Metric := Metric) (Abelian := Abelian) (Matter := Matter)
      (Longitudinal := Longitudinal) (Boundary := Boundary)) :
    0 < data.margin ∧
      ∀ vector : E,
        data.margin * ‖vector‖ ^ 2 ≤ data.principalForm vector vector := by
  simpa [margin, toFiniteSectorGarding,
    FiniteSectorQuadraticGardingData.margin] using
    data.toFiniteSectorGarding.finite_sector_quadratic_garding_gate

end CandidateAFiveSectorProductOffDiagonalGardingData

end
end P0EFTJanusProgramPCandidateAFiveSectorProductOffDiagonalGarding4D
end JanusFormal
