import JanusFormal.Branches.FundamentalGeometryPVariationalPrinciple.Gates.P0EFTJanusProgramPReferenceNuclearDuhamelGreenRankOneBoundary4D
import JanusFormal.Branches.FundamentalGeometryPVariationalPrinciple.Gates.P0EFTJanusProgramPReferenceNuclearHeatFinitePartBoundaryAssembly4D

/-!
# Reference finite parts from rank-one short/long Duhamel expansions

This frontend replaces the two scalar trace-integration bridges of the boundary
assembly by explicit common rank-one expansions on the short- and long-time
regions.  The only remaining integration theorem is the certified exchange of
the rank-one series with each time integral.

The construction chain is now

```text
rank-one Duhamel expansions
  -> operator-valued short/long integrals
  -> boundary matching
  -> global Duhamel--Green operator identity
  -> intrinsic trace identity
  -> finite-part logarithmic derivative
  -> standalone reference zeta coefficient.
```
-/

namespace JanusFormal
namespace P0EFTJanusProgramPReferenceNuclearHeatFinitePartRankOneBoundaryAssembly4D

set_option autoImplicit false
noncomputable section

open Set
open P0EFTJanusProgramPNuclearHeatDuhamelTraceVariation4D
open P0EFTJanusProgramPReferenceNuclearDuhamelGreenRankOneBoundary4D
open P0EFTJanusProgramPReferenceNuclearHeatFinitePartBoundaryAssembly4D

variable {E : Type*}
  [NormedAddCommGroup E] [InnerProductSpace Real E]

/-- Complete standalone reference packet from rank-one spectral Duhamel data. -/
structure ReferenceNuclearHeatFinitePartRankOneBoundaryAssemblyData
    (family : P0EFTJanusProgramPRelativeHeatMellinZetaFamily4D.
      RelativeHeatMellinZetaFamilyData)
    (shortTimeRegion longTimeRegion : Set Real) where
  nuclear : NuclearHeatDuhamelTraceVariationData (E := E)
  countertermContribution : Real → Real
  rankOneBoundary : ReferenceNuclearDuhamelGreenRankOneBoundaryData nuclear
    shortTimeRegion longTimeRegion
  hasDerivAt_counterterm : ∀ parameter,
    HasDerivAt countertermContribution
      (rankOneBoundary.countertermDerivative parameter) parameter
  logDeterminant_eq : ∀ parameter,
    P0EFTJanusProgramPRelativeHeatFinitePartDeterminant4D.
        relativeHeatFinitePartLogDeterminant
          (family.finitePartFamily.finitePart parameter) =
      countertermContribution parameter +
        rankOneBoundary.shortTime.weighted.toWeightedHeatTraceVariation.
            contribution parameter +
          rankOneBoundary.longTime.weighted.toWeightedHeatTraceVariation.
            contribution parameter
  zetaPrimeAtZero_real : ∀ parameter,
    (family.zetaPrimeAtZero parameter).im = 0

namespace ReferenceNuclearHeatFinitePartRankOneBoundaryAssemblyData

/-- Convert rank-one spectral data to the local boundary assembly. -/
def toBoundaryAssembly
    {family : P0EFTJanusProgramPRelativeHeatMellinZetaFamily4D.
      RelativeHeatMellinZetaFamilyData}
    {shortTimeRegion longTimeRegion : Set Real}
    (data : ReferenceNuclearHeatFinitePartRankOneBoundaryAssemblyData
      (E := E) family shortTimeRegion longTimeRegion) :
    ReferenceNuclearHeatFinitePartBoundaryAssemblyData
      (E := E) family shortTimeRegion longTimeRegion where
  nuclear := data.nuclear
  countertermContribution := data.countertermContribution
  boundaryMatching := data.rankOneBoundary.toBoundaryMatching
  hasDerivAt_counterterm := data.hasDerivAt_counterterm
  logDeterminant_eq := data.logDeterminant_eq
  zetaPrimeAtZero_real := data.zetaPrimeAtZero_real

/-- The finite-part logarithm differentiates to the logarithmic operator trace
constructed from the rank-one Duhamel expansions. -/
theorem hasDerivAt_finitePartLog
    {family : P0EFTJanusProgramPRelativeHeatMellinZetaFamily4D.
      RelativeHeatMellinZetaFamilyData}
    {shortTimeRegion longTimeRegion : Set Real}
    (data : ReferenceNuclearHeatFinitePartRankOneBoundaryAssemblyData
      (E := E) family shortTimeRegion longTimeRegion)
    (parameter : Real) :
    HasDerivAt
      (fun current =>
        P0EFTJanusProgramPRelativeHeatFinitePartDeterminant4D.
          relativeHeatFinitePartLogDeterminant
            (family.finitePartFamily.finitePart current))
      (data.rankOneBoundary.toBoundaryMatching.toOperatorIdentity.
        logarithmicTrace parameter) parameter :=
  data.toBoundaryAssembly.hasDerivAt_finitePartLog parameter

/-- Standalone reference coefficient generated by rank-one Duhamel spectral
expansions and boundary cancellation. -/
theorem connectionCoefficient_eq_neg_logarithmicTrace
    {family : P0EFTJanusProgramPRelativeHeatMellinZetaFamily4D.
      RelativeHeatMellinZetaFamilyData}
    {shortTimeRegion longTimeRegion : Set Real}
    (data : ReferenceNuclearHeatFinitePartRankOneBoundaryAssemblyData
      (E := E) family shortTimeRegion longTimeRegion)
    (parameter : Real) :
    P0EFTJanusProgramPRelativeZetaDeterminantConnection4D.
        relativeZetaConnectionCoefficient family.toZetaFamily parameter =
      -(data.rankOneBoundary.toBoundaryMatching.toOperatorIdentity.
          logarithmicTrace parameter : Complex) :=
  data.toBoundaryAssembly.connectionCoefficient_eq_neg_logarithmicTrace
    parameter

/-- Public rank-one finite-part assembly checkpoint. -/
theorem reference_nuclear_heat_finite_part_rank_one_boundary_assembly_gate
    (family : P0EFTJanusProgramPRelativeHeatMellinZetaFamily4D.
      RelativeHeatMellinZetaFamilyData)
    (shortTimeRegion longTimeRegion : Set Real)
    (data : ReferenceNuclearHeatFinitePartRankOneBoundaryAssemblyData
      (E := E) family shortTimeRegion longTimeRegion) :
    (∀ parameter,
      (∫ time in shortTimeRegion,
        data.nuclear.extendedDuhamelTrace parameter time) =
          P0EFTJanusProgramPIntrinsicNuclearTrace4D.intrinsicNuclearTrace
            (data.rankOneBoundary.shortTime.integratedTraceClass parameter)) ∧
    (∀ parameter,
      (∫ time in longTimeRegion,
        data.nuclear.extendedDuhamelTrace parameter time) =
          P0EFTJanusProgramPIntrinsicNuclearTrace4D.intrinsicNuclearTrace
            (data.rankOneBoundary.longTime.integratedTraceClass parameter)) ∧
    (∀ parameter,
      HasDerivAt
        (fun current =>
          P0EFTJanusProgramPRelativeHeatFinitePartDeterminant4D.
            relativeHeatFinitePartLogDeterminant
              (family.finitePartFamily.finitePart current))
        (data.rankOneBoundary.toBoundaryMatching.toOperatorIdentity.
          logarithmicTrace parameter) parameter) ∧
    (∀ parameter,
      P0EFTJanusProgramPRelativeZetaDeterminantConnection4D.
          relativeZetaConnectionCoefficient family.toZetaFamily parameter =
        -(data.rankOneBoundary.toBoundaryMatching.toOperatorIdentity.
            logarithmicTrace parameter : Complex)) :=
  ⟨data.rankOneBoundary.shortTimeIntegral_eq_trace,
    data.rankOneBoundary.longTimeIntegral_eq_trace,
    data.hasDerivAt_finitePartLog,
    data.connectionCoefficient_eq_neg_logarithmicTrace⟩

end ReferenceNuclearHeatFinitePartRankOneBoundaryAssemblyData

end
end P0EFTJanusProgramPReferenceNuclearHeatFinitePartRankOneBoundaryAssembly4D
end JanusFormal
