import JanusFormal.Branches.FundamentalGeometryPVariationalPrinciple.Gates.P0EFTJanusMappingTorusCanonicalLatitudeCauchyJetProfileIntegrability4D
import JanusFormal.Branches.FundamentalGeometryPVariationalPrinciple.Gates.P0EFTJanusMappingTorusCanonicalPhysicalScalarCauchyJetCompatibilityGreenCore4D
import JanusFormal.Branches.FundamentalGeometryPVariationalPrinciple.Gates.P0EFTJanusMappingTorusCanonicalPhysicalScalarCauchyJetEulerProductRealization4D
import JanusFormal.Branches.FundamentalGeometryPVariationalPrinciple.Gates.P0EFTJanusMappingTorusCanonicalPhysicalScalarFirstSheetBoundaryExtension4D
import JanusFormal.Branches.FundamentalGeometryPVariationalPrinciple.Gates.P0EFTJanusMappingTorusCanonicalLatitudeMinimalCutoffL2Convergence4D
import JanusFormal.Branches.FundamentalGeometryPVariationalPrinciple.Gates.P0EFTJanusMappingTorusScalarHilbertGreenCoreRieszBoundaryTrace4D

/-!
# Physical completed boundary triple by Riesz duality

The explicit Cauchy jet already has:

* an automatic bulk `L²` estimate from the two fixed normal-profile moments;
* a product-coordinate Euler estimate;
* exact smooth Cauchy data;
* a dense zero-Cauchy minimal core from the global shrinking cutoffs.

These facts make the smooth Cauchy extension bounded in the maximal graph norm.
The generic Riesz theorem then reconstructs the complete boundary trace from the
Green form itself.  Consequently no independent value/normal graph trace
estimate and no higher normal regularity space are needed.

The output is a surjective completed boundary triple whose trace is the
Riesz-represented Green boundary functional and whose right inverse is the
completed explicit Cauchy extension.
-/

namespace JanusFormal
namespace P0EFTJanusMappingTorusCanonicalPhysicalScalarCauchyJetRieszBoundaryTriple4D

set_option autoImplicit false
noncomputable section

open Set Topology MeasureTheory
open P0EFTJanusMappingTorusSmoothFieldDescent4D
open P0EFTJanusMappingTorusCanonicalLatitudeCauchyJetProfileIntegrability4D
open P0EFTJanusMappingTorusCanonicalPhysicalScalarCauchyJetCompatibilityGreenCore4D
open P0EFTJanusMappingTorusCanonicalPhysicalScalarCauchyJetGeometricGreenCore4D
open P0EFTJanusMappingTorusCanonicalPhysicalScalarCauchyJetProfileL2Bound4D
open P0EFTJanusMappingTorusCanonicalPhysicalScalarCauchyJetEulerL2Reduction4D
open P0EFTJanusMappingTorusCanonicalPhysicalScalarCauchyJetEulerProductRealization4D
open P0EFTJanusMappingTorusCanonicalPhysicalScalarCauchyJetSquaredGraphBound4D
open P0EFTJanusMappingTorusCanonicalPhysicalScalarFirstSheetBoundaryExtension4D
open P0EFTJanusMappingTorusCanonicalLatitudeMinimalCutoffL2Convergence4D
open P0EFTJanusMappingTorusScalarHilbertGreenCoreCompletion4D
open P0EFTJanusMappingTorusScalarBoundaryCauchyGraphExtension4D
open P0EFTJanusMappingTorusScalarHilbertGreenCoreRieszBoundaryTrace4D

universe x y

variable (period : Real) (hPeriod : period ≠ 0)

/-- Physical Riesz-boundary data: the only quantitative input is the explicit
Euler estimate of the Cauchy jet. -/
structure CanonicalPhysicalScalarCauchyJetRieszBoundaryData
    (massSquared : Real)
    (ValueCore : Type x) (NormalCore : Type y)
    [AddCommGroup ValueCore] [Module Real ValueCore]
    [AddCommGroup NormalCore] [Module Real NormalCore] where
  geometric : CanonicalPhysicalScalarCauchyJetCompatibilityData
    period hPeriod massSquared ValueCore NormalCore
  eulerEstimate :
    geometric.toCauchyJetGeometricData.CauchyJetEulerProductEstimateData
      period hPeriod
      geometric.toCauchyJetGeometricData.canonicalEulerProductRealization

namespace CanonicalPhysicalScalarCauchyJetRieszBoundaryData

/-- Explicit geometric Cauchy-jet data. -/
def jetGeometric
    {ValueCore : Type x} {NormalCore : Type y}
    [AddCommGroup ValueCore] [Module Real ValueCore]
    [AddCommGroup NormalCore] [Module Real NormalCore]
    (data : CanonicalPhysicalScalarCauchyJetRieszBoundaryData
      period hPeriod massSquared ValueCore NormalCore) :=
  data.geometric.toCauchyJetGeometricData

/-- Automatic bulk estimate generated by the fixed profile moments. -/
def bulkEstimate
    {ValueCore : Type x} {NormalCore : Type y}
    [AddCommGroup ValueCore] [Module Real ValueCore]
    [AddCommGroup NormalCore] [Module Real NormalCore]
    (data : CanonicalPhysicalScalarCauchyJetRieszBoundaryData
      period hPeriod massSquared ValueCore NormalCore) :=
  data.jetGeometric.cauchyJetProductL2EstimateData
    canonicalLatitudeCauchyJetProfileIntegrabilityData

/-- Complete squared bulk/Euler graph estimate. -/
def squaredGraphEstimate
    {ValueCore : Type x} {NormalCore : Type y}
    [AddCommGroup ValueCore] [Module Real ValueCore]
    [AddCommGroup NormalCore] [Module Real NormalCore]
    (data : CanonicalPhysicalScalarCauchyJetRieszBoundaryData
      period hPeriod massSquared ValueCore NormalCore) :=
  data.eulerEstimate.combine data.bulkEstimate

/-- Linear graph estimate for the explicit Cauchy extension. -/
def graphEstimate
    {ValueCore : Type x} {NormalCore : Type y}
    [AddCommGroup ValueCore] [Module Real ValueCore]
    [AddCommGroup NormalCore] [Module Real NormalCore]
    (data : CanonicalPhysicalScalarCauchyJetRieszBoundaryData
      period hPeriod massSquared ValueCore NormalCore) :=
  data.squaredGraphEstimate.toComponentGraphEstimateData

/-- Generic smooth Cauchy extension underlying the physical jet. -/
def smoothExtension
    {ValueCore : Type x} {NormalCore : Type y}
    [AddCommGroup ValueCore] [Module Real ValueCore]
    [AddCommGroup NormalCore] [Module Real NormalCore]
    (data : CanonicalPhysicalScalarCauchyJetRieszBoundaryData
      period hPeriod massSquared ValueCore NormalCore) :=
  data.geometric.toCompatibilityGreenCoreData.smoothCauchyExtensionData
    |>.toGenericExtension

/-- Bounded graph-valued Cauchy extension. -/
def boundedSmoothExtension
    {ValueCore : Type x} {NormalCore : Type y}
    [AddCommGroup ValueCore] [Module Real ValueCore]
    [AddCommGroup NormalCore] [Module Real NormalCore]
    (data : CanonicalPhysicalScalarCauchyJetRieszBoundaryData
      period hPeriod massSquared ValueCore NormalCore) :
    CanonicalScalarBoundedSmoothCauchyExtensionData
      (ValueCore := ValueCore) (NormalCore := NormalCore)
      data.geometric.greenCore.core where
  smooth := data.smoothExtension
  constant := max data.graphEstimate.inclusionConstant
    data.graphEstimate.operatorConstant
  nonnegative := max_nonneg
    data.graphEstimate.inclusionConstant_nonnegative
    data.graphEstimate.operatorConstant_nonnegative
  graph_bound := data.graphEstimate.graph_bound

/-- Density of the physical zero-Cauchy minimal core. -/
theorem minimalCoreDense
    {ValueCore : Type x} {NormalCore : Type y}
    [AddCommGroup ValueCore] [Module Real ValueCore]
    [AddCommGroup NormalCore] [Module Real NormalCore]
    (data : CanonicalPhysicalScalarCauchyJetRieszBoundaryData
      period hPeriod massSquared ValueCore NormalCore) :
    data.geometric.greenCore.MinimalCoreDense period hPeriod :=
  canonicalPhysicalScalarMinimalCoreDense
    period hPeriod data.geometric.greenCore

/-- Injectivity of the completed maximal graph inclusion. -/
theorem graphInclusion_injective
    {ValueCore : Type x} {NormalCore : Type y}
    [AddCommGroup ValueCore] [Module Real ValueCore]
    [AddCommGroup NormalCore] [Module Real NormalCore]
    (data : CanonicalPhysicalScalarCauchyJetRieszBoundaryData
      period hPeriod massSquared ValueCore NormalCore) :
    Function.Injective
      (canonicalScalarGreenCoreGraphInclusion
        data.geometric.greenCore.core) :=
  canonicalPhysicalScalarGraphInclusion_injective
    period hPeriod data.geometric.greenCore

/-- Riesz-generated physical graph trace bound. -/
def traceBound
    {ValueCore : Type x} {NormalCore : Type y}
    [AddCommGroup ValueCore] [Module Real ValueCore]
    [AddCommGroup NormalCore] [Module Real NormalCore]
    (data : CanonicalPhysicalScalarCauchyJetRieszBoundaryData
      period hPeriod massSquared ValueCore NormalCore) :=
  data.boundedSmoothExtension.rieszBoundaryGraphBound

/-- Riesz-generated completed physical Cauchy trace. -/
def completedBoundaryTrace
    {ValueCore : Type x} {NormalCore : Type y}
    [AddCommGroup ValueCore] [Module Real ValueCore]
    [AddCommGroup NormalCore] [Module Real NormalCore]
    (data : CanonicalPhysicalScalarCauchyJetRieszBoundaryData
      period hPeriod massSquared ValueCore NormalCore) :=
  data.boundedSmoothExtension.rieszBoundaryTrace

/-- Correct completed physical boundary triple without normal regularity input. -/
def triple
    {ValueCore : Type x} {NormalCore : Type y}
    [AddCommGroup ValueCore] [Module Real ValueCore]
    [AddCommGroup NormalCore] [Module Real NormalCore]
    (data : CanonicalPhysicalScalarCauchyJetRieszBoundaryData
      period hPeriod massSquared ValueCore NormalCore) :
    CanonicalScalarCompletedBoundaryTripleData
      data.geometric.greenCore.core data.traceBound :=
  data.boundedSmoothExtension.toRieszBoundaryTriple
    data.graphInclusion_injective

/-- Completed explicit Cauchy extension. -/
def completedExtension
    {ValueCore : Type x} {NormalCore : Type y}
    [AddCommGroup ValueCore] [Module Real ValueCore]
    [AddCommGroup NormalCore] [Module Real NormalCore]
    (data : CanonicalPhysicalScalarCauchyJetRieszBoundaryData
      period hPeriod massSquared ValueCore NormalCore) :=
  data.boundedSmoothExtension.completedExtension

/-- The completed extension is a right inverse of the Riesz trace. -/
theorem completedBoundaryTrace_extension
    {ValueCore : Type x} {NormalCore : Type y}
    [AddCommGroup ValueCore] [Module Real ValueCore]
    [AddCommGroup NormalCore] [Module Real NormalCore]
    (data : CanonicalPhysicalScalarCauchyJetRieszBoundaryData
      period hPeriod massSquared ValueCore NormalCore)
    (boundary :
      P0EFTJanusMappingTorusScalarHilbertBoundarySymplectic4D.CanonicalScalarHilbertBoundaryDatum
        (Trace := CanonicalPhysicalScalarFirstSheetL2 period)) :
    data.completedBoundaryTrace (data.completedExtension boundary) = boundary :=
  data.boundedSmoothExtension.rieszBoundaryTrace_extension boundary

/-- Riesz physical boundary-triple certificate. -/
theorem certificate
    {ValueCore : Type x} {NormalCore : Type y}
    [AddCommGroup ValueCore] [Module Real ValueCore]
    [AddCommGroup NormalCore] [Module Real NormalCore]
    (data : CanonicalPhysicalScalarCauchyJetRieszBoundaryData
      period hPeriod massSquared ValueCore NormalCore) :
    data.geometric.greenCore.MinimalCoreDense period hPeriod ∧
      Function.Injective
        (canonicalScalarGreenCoreGraphInclusion
          data.geometric.greenCore.core) ∧
      Function.Surjective data.completedBoundaryTrace ∧
      (∀ boundary,
        data.completedBoundaryTrace
          (data.completedExtension boundary) = boundary) ∧
      (∀ field : SmoothQuotientField period hPeriod Real,
        data.completedBoundaryTrace
            (canonicalScalarGreenCoreToGraph
              data.geometric.greenCore.core field) =
          data.geometric.greenCore.core.boundaryTrace field) :=
  ⟨data.minimalCoreDense,
    data.graphInclusion_injective,
    data.boundedSmoothExtension.rieszBoundaryTrace_surjective,
    data.completedBoundaryTrace_extension,
    data.boundedSmoothExtension.rieszBoundaryTrace_smooth⟩

end CanonicalPhysicalScalarCauchyJetRieszBoundaryData

end
end P0EFTJanusMappingTorusCanonicalPhysicalScalarCauchyJetRieszBoundaryTriple4D
end JanusFormal
