import JanusFormal.Branches.FundamentalGeometryPVariationalPrinciple.Gates.P0EFTJanusMetricInducedScalarStressVariation4D

/-!
# Scalar stress conservation on a covariant second jet

This gate proves the local algebraic Noether identity in a normal frame.  A
fixed symmetric nondegenerate four-metric raises the scalar first jet and a
symmetric matrix represents its covariant Hessian at the frame origin.  The
connection coefficients vanish there, so the explicitly expanded covariant
derivative of the stress satisfies

`div T = (box phi - V'(phi)) sharp(d phi)`.

Both potential conventions already present in Programme P are specialized:
the intrinsic fiber convention `V = -m² phi²/2`, and the matrix stress
convention `V = m² phi²/2 + source phi`.  This is not yet a global
stress-divergence theorem for smooth fields and does not install a connection.
-/

namespace JanusFormal
namespace P0EFTJanusScalarStressCovariantJetConservation4D

set_option autoImplicit false

noncomputable section

open P0EFTJanusMetricCoupledScalarMatterJetVariation
open P0EFTJanusMetricInducedScalarStressVariation4D

abbrev Index4 := P0EFTJanusMetricCoupledScalarMatterJetVariation.Index4
abbrev Vector4 := P0EFTJanusMetricCoupledScalarMatterJetVariation.Vector4
abbrev Matrix4 := P0EFTJanusMetricCoupledScalarMatterJetVariation.Matrix4

/-- Scalar value, covariant gradient and symmetric covariant Hessian at the
origin of one normal frame. -/
structure CovariantScalarJet2 where
  field : Real
  gradient : Vector4
  hessian : Matrix4
  hessian_symmetric : hessian.transpose = hessian

/-- Contravariant first jet `sharp(d phi)`. -/
def covariantScalarJetRaisedGradient
    (data : FixedSignMetric4) (jet : CovariantScalarJet2) : Vector4 :=
  Matrix.mulVec data.metric⁻¹ jet.gradient

/-- Covariant wave contraction `g^{mu nu} nabla_mu nabla_nu phi`. -/
def covariantScalarJetWave
    (data : FixedSignMetric4) (jet : CovariantScalarJet2) : Real :=
  ∑ first : Index4, ∑ second : Index4,
    data.metric⁻¹ first second * jet.hessian first second

/-- Stress tensor at the jet for a supplied potential value.  This is the
same structural convention `sharp p ⊗ sharp p - g⁻¹ L` used by both
existing scalar-stress gates. -/
def covariantScalarJetStress
    (data : FixedSignMetric4) (potentialValue : Real)
    (jet : CovariantScalarJet2) : Matrix4 :=
  fun first second =>
    covariantScalarJetRaisedGradient data jet first *
        covariantScalarJetRaisedGradient data jet second -
      data.metric⁻¹ first second *
        (scalarKinetic data.metric⁻¹ jet.gradient + potentialValue)

/-- Normal-frame covariant derivative of the stress.  `potentialSlope` is
`V'(phi)` at the jet. -/
def covariantScalarJetStressDerivative
    (data : FixedSignMetric4) (potentialSlope : Real)
    (jet : CovariantScalarJet2)
    (derivative first second : Index4) : Real :=
  (∑ index : Index4,
      data.metric⁻¹ first index * jet.hessian derivative index) *
      covariantScalarJetRaisedGradient data jet second +
    covariantScalarJetRaisedGradient data jet first *
      (∑ index : Index4,
        data.metric⁻¹ second index * jet.hessian derivative index) -
    data.metric⁻¹ first second *
      ((∑ index : Index4,
          covariantScalarJetRaisedGradient data jet index *
            jet.hessian derivative index) +
        potentialSlope * jet.gradient derivative)

/-- Normal-frame divergence `nabla_mu T^{mu nu}`. -/
def covariantScalarJetStressDivergence
    (data : FixedSignMetric4) (potentialSlope : Real)
    (jet : CovariantScalarJet2) (index : Index4) : Real :=
  ∑ derivative : Index4,
    covariantScalarJetStressDerivative data potentialSlope jet
      derivative derivative index

/-- Residual with the sign naturally generated by stress divergence. -/
def covariantScalarStressEulerResidual
    (data : FixedSignMetric4) (potentialSlope : Real)
    (jet : CovariantScalarJet2) : Real :=
  covariantScalarJetWave data jet - potentialSlope

private theorem inverseMetric_contract_gradient
    (data : FixedSignMetric4) (gradient : Vector4) (index : Index4) :
    (∑ first : Index4, data.metric⁻¹ first index * gradient first) =
      Matrix.mulVec data.metric⁻¹ gradient index := by
  unfold Matrix.mulVec dotProduct
  change (∑ first : Index4,
      data.metric⁻¹ first index * gradient first) =
    ∑ first : Index4, data.metric⁻¹ index first * gradient first
  apply Finset.sum_congr rfl
  intro first _
  have hSymmetric := congrArg
    (fun matrix : Matrix4 => matrix first index) data.inverse_symmetric
  simp only [Matrix.transpose_apply] at hSymmetric
  rw [hSymmetric]

private theorem covariantScalarJet_mixed_terms_eq
    (data : FixedSignMetric4) (jet : CovariantScalarJet2)
    (index : Index4) :
    (∑ first : Index4,
        covariantScalarJetRaisedGradient data jet first *
          (∑ second : Index4,
            data.metric⁻¹ index second * jet.hessian first second)) =
      ∑ first : Index4,
        data.metric⁻¹ first index *
          (∑ second : Index4,
            covariantScalarJetRaisedGradient data jet second *
              jet.hessian first second) := by
  simp_rw [Finset.mul_sum]
  rw [Finset.sum_comm]
  apply Finset.sum_congr rfl
  intro first _
  apply Finset.sum_congr rfl
  intro second _
  have hMetric := congrArg
    (fun matrix : Matrix4 => matrix first index) data.inverse_symmetric
  have hHessian := congrArg
    (fun matrix : Matrix4 => matrix first second) jet.hessian_symmetric
  simp only [Matrix.transpose_apply] at hMetric hHessian
  rw [hMetric, hHessian]
  ring

private theorem covariantScalarJet_potential_term
    (data : FixedSignMetric4) (jet : CovariantScalarJet2)
    (potentialSlope : Real) (index : Index4) :
    (∑ first : Index4,
        data.metric⁻¹ first index *
          (potentialSlope * jet.gradient first)) =
      potentialSlope * covariantScalarJetRaisedGradient data jet index := by
  calc
    (∑ first : Index4,
        data.metric⁻¹ first index *
          (potentialSlope * jet.gradient first)) =
        potentialSlope *
          (∑ first : Index4,
            data.metric⁻¹ first index * jet.gradient first) := by
          rw [Finset.mul_sum]
          apply Finset.sum_congr rfl
          intro first _
          ring
    _ = potentialSlope * covariantScalarJetRaisedGradient data jet index := by
      rw [inverseMetric_contract_gradient]
      rfl

/-- Local covariant algebraic identity in a normal frame. -/
theorem covariantScalarJetStressDivergence_eq_euler_mul_raisedGradient
    (data : FixedSignMetric4) (potentialSlope : Real)
    (jet : CovariantScalarJet2) (index : Index4) :
    covariantScalarJetStressDivergence data potentialSlope jet index =
      covariantScalarStressEulerResidual data potentialSlope jet *
        covariantScalarJetRaisedGradient data jet index := by
  unfold covariantScalarJetStressDivergence
    covariantScalarJetStressDerivative covariantScalarStressEulerResidual
    covariantScalarJetWave
  rw [Finset.sum_sub_distrib, Finset.sum_add_distrib]
  simp_rw [mul_add]
  rw [Finset.sum_add_distrib]
  rw [covariantScalarJet_mixed_terms_eq data jet index]
  rw [covariantScalarJet_potential_term data jet potentialSlope index]
  rw [← Finset.sum_mul]
  ring

/-- Stress is conserved at the jet whenever its stress-sign Euler residual
vanishes. -/
theorem covariantScalarJetStressDivergence_eq_zero_of_euler
    (data : FixedSignMetric4) (potentialSlope : Real)
    (jet : CovariantScalarJet2)
    (hEuler : covariantScalarStressEulerResidual
      data potentialSlope jet = 0) :
    covariantScalarJetStressDivergence data potentialSlope jet = 0 := by
  funext index
  rw [covariantScalarJetStressDivergence_eq_euler_mul_raisedGradient,
    hEuler]
  simp

/-! ## Existing Programme P sign conventions -/

/-- Potential value used by `fiberContravariantScalarStress`. -/
def fiberScalarPotentialValue
    (massSquared fieldValue : Real) : Real :=
  -(1 / 2) * massSquared * fieldValue ^ 2

/-- Its slope, giving residual `box phi + m² phi`. -/
def fiberScalarPotentialSlope
    (massSquared fieldValue : Real) : Real :=
  -massSquared * fieldValue

theorem fiberConventionStressDivergence
    (data : FixedSignMetric4) (massSquared : Real)
    (jet : CovariantScalarJet2) (index : Index4) :
    covariantScalarJetStressDivergence data
        (fiberScalarPotentialSlope massSquared jet.field) jet index =
      (covariantScalarJetWave data jet + massSquared * jet.field) *
        covariantScalarJetRaisedGradient data jet index := by
  rw [covariantScalarJetStressDivergence_eq_euler_mul_raisedGradient]
  unfold covariantScalarStressEulerResidual fiberScalarPotentialSlope
  ring

/-- Potential value used by `pointwiseScalarStressTensor`. -/
def pointwiseScalarPotentialValue
    (massSquared source fieldValue : Real) : Real :=
  massSquared / 2 * fieldValue ^ 2 + source * fieldValue

/-- Its slope, giving residual `box phi - m² phi - source`. -/
def pointwiseScalarPotentialSlope
    (massSquared source fieldValue : Real) : Real :=
  massSquared * fieldValue + source

/-- Exact anchoring to the existing matrix stress tensor. -/
theorem covariantScalarJetStress_eq_pointwiseScalarStressTensor
    (data : FixedSignMetric4) (massSquared source : Real)
    (jet : CovariantScalarJet2) :
    covariantScalarJetStress data
        (pointwiseScalarPotentialValue massSquared source jet.field) jet =
      pointwiseScalarStressTensor data massSquared source
        { field := jet.field, gradient := jet.gradient } := by
  ext first second
  unfold covariantScalarJetStress pointwiseScalarStressTensor
    covariantScalarJetRaisedGradient pointwiseScalarPotentialValue
    scalarMatterLagrangian raisedGradient
  ring

theorem pointwiseConventionStressDivergence
    (data : FixedSignMetric4) (massSquared source : Real)
    (jet : CovariantScalarJet2) (index : Index4) :
    covariantScalarJetStressDivergence data
        (pointwiseScalarPotentialSlope massSquared source jet.field) jet index =
      (covariantScalarJetWave data jet - massSquared * jet.field - source) *
        covariantScalarJetRaisedGradient data jet index := by
  rw [covariantScalarJetStressDivergence_eq_euler_mul_raisedGradient]
  unfold covariantScalarStressEulerResidual pointwiseScalarPotentialSlope
  ring

theorem pointwiseConventionStressConserved_of_euler
    (data : FixedSignMetric4) (massSquared source : Real)
    (jet : CovariantScalarJet2)
    (hEuler : covariantScalarJetWave data jet -
      massSquared * jet.field - source = 0) :
    covariantScalarJetStressDivergence data
        (pointwiseScalarPotentialSlope massSquared source jet.field) jet = 0 := by
  funext index
  rw [pointwiseConventionStressDivergence, hEuler]
  simp

end

end P0EFTJanusScalarStressCovariantJetConservation4D
end JanusFormal
