import JanusFormal.Branches.FundamentalGeometryPVariationalPrinciple.Gates.P0EFTJanusMappingTorusJointAnalyticTimeAction4D
import JanusFormal.Branches.FundamentalGeometryPVariationalPrinciple.Gates.P0EFTJanusMappingTorusMetricMatterGaugeActionNoetherBridge4D

/-!
# Time-translation metric, matter and gauge Noether block on D8

The complete analytic time action integrates one genuine geometric direction,
not every smooth tangent ghost.  Accordingly this file restricts the existing
metric/matter/`U(1)^2` block to the real line generated by time translation.

The only remaining input is that the two pointwise tensor pullback derivatives
are smooth symmetric global sections.  This is the exact dependent-bundle
regularity obstruction left by the present Mathlib API.
-/

namespace JanusFormal
namespace P0EFTJanusMappingTorusTimeTranslationMetricMatterGaugeNoether4D

set_option autoImplicit false
set_option synthInstance.maxHeartbeats 300000

noncomputable section

open scoped Manifold ContDiff
open Bundle
open P0EFTJanusMappingTorusQuotient
open P0EFTJanusMappingTorusSmoothAtlasFrontier
open P0EFTJanusMappingTorusSmoothQuotientManifold
open P0EFTJanusMappingTorusSmoothFieldDescent4D
open P0EFTJanusMappingTorusSmoothGlobalFieldConfiguration4D
open P0EFTJanusMappingTorusDiagonalDiffeomorphismAction4D
open P0EFTJanusMappingTorusGeneralLorentzTensor4D
open P0EFTJanusMappingTorusCovariantTensorDiffeomorphismGenerator4D
open P0EFTJanusMappingTorusAbelianGaugeBRST4D
open P0EFTJanusMappingTorusLinearizedDiffeomorphismBRST4D
open P0EFTJanusMappingTorusMatterGaugeNoetherOperator4D
open P0EFTJanusMappingTorusMetricMatterGaugeNoetherOperator4D
open P0EFTJanusMappingTorusMetricMatterGaugeActionNoetherBridge4D
open P0EFTJanusMappingTorusCompleteTimeFlow4D
open P0EFTJanusMappingTorusJointAnalyticTimeAction4D

variable (period : Real) (hPeriod : period ≠ 0)

private abbrev sphereData := reflectedSphereData period hPeriod
private abbrev EffectiveQuotient := MappingTorus (sphereData period hPeriod)

local instance effectiveQuotientChartedSpace :
    ChartedSpace CoverModel (EffectiveQuotient period hPeriod) :=
  reflectedSphereQuotientChartedSpace period hPeriod

local instance effectiveQuotientIsManifold :
    IsManifold coverModelWithCorners ω (EffectiveQuotient period hPeriod) :=
  reflectedSphereQuotient_isManifold period hPeriod

private def timeFlowInputBundle
    (point : EffectiveQuotient period hPeriod) :
    TangentBundle (𝓘(Real, Real).prod coverModelWithCorners)
      (Real × EffectiveQuotient period hPeriod) :=
  (equivTangentBundleProd 𝓘(Real, Real) Real coverModelWithCorners
      (EffectiveQuotient period hPeriod)).symm
    (⟨0, 1⟩, ⟨point, 0⟩)

@[simp]
private theorem timeFlowInputBundle_eq
    (point : EffectiveQuotient period hPeriod) :
    timeFlowInputBundle period hPeriod point =
      (⟨(0, point), (1, 0)⟩ :
        TangentBundle (𝓘(Real, Real).prod coverModelWithCorners)
          (Real × EffectiveQuotient period hPeriod)) :=
  rfl

private theorem timeFlowInputBundle_contMDiff :
    ContMDiff coverModelWithCorners
      (𝓘(Real, Real).prod coverModelWithCorners).tangent ω
      (timeFlowInputBundle period hPeriod) := by
  apply (contMDiff_equivTangentBundleProd_symm
    (I := 𝓘(Real, Real)) (I' := coverModelWithCorners)
    (M := Real) (M' := EffectiveQuotient period hPeriod)).comp
  exact contMDiff_const.prodMk
    (Bundle.contMDiff_zeroSection (n := ω) Real
      (TangentSpace coverModelWithCorners :
        EffectiveQuotient period hPeriod → Type _))

private def rawTimeTranslationBundle
    (point : EffectiveQuotient period hPeriod) :
    TangentBundle coverModelWithCorners (EffectiveQuotient period hPeriod) :=
  tangentMap (𝓘(Real, Real).prod coverModelWithCorners)
    coverModelWithCorners (effectiveJointTimeFlow period hPeriod)
    (timeFlowInputBundle period hPeriod point)

private theorem rawTimeTranslationBundle_contMDiff :
    ContMDiff coverModelWithCorners coverModelWithCorners.tangent ω
      (rawTimeTranslationBundle period hPeriod) :=
  ((effectiveJointTimeFlow_contMDiff period hPeriod)
      |>.contMDiff_tangentMap (m := ω) (by simp)).comp
    (timeFlowInputBundle_contMDiff period hPeriod)

private theorem rawTimeTranslationBundle_base
    (point : EffectiveQuotient period hPeriod) :
    (rawTimeTranslationBundle period hPeriod point).1 = point := by
  simpa [rawTimeTranslationBundle, timeFlowInputBundle, tangentMap,
    effectiveJointTimeFlow] using
      (effectiveTimeFlow_zero period hPeriod point)

/-- The intrinsic velocity of the actual complete D8 time action. -/
def effectiveTimeTranslationVelocity
    (point : EffectiveQuotient period hPeriod) :
    TangentSpace coverModelWithCorners point :=
  (rawTimeTranslationBundle_base period hPeriod point) ▸
    (rawTimeTranslationBundle period hPeriod point).2

private theorem effectiveTimeTranslationVelocity_bundle
    (point : EffectiveQuotient period hPeriod) :
    (⟨point, effectiveTimeTranslationVelocity period hPeriod point⟩ :
        TangentBundle coverModelWithCorners
          (EffectiveQuotient period hPeriod)) =
      rawTimeTranslationBundle period hPeriod point := by
  let raw := rawTimeTranslationBundle period hPeriod point
  have hBase : raw.1 = point :=
    rawTimeTranslationBundle_base period hPeriod point
  change (⟨point, hBase ▸ raw.2⟩ :
      TangentBundle coverModelWithCorners
        (EffectiveQuotient period hPeriod)) = raw
  rcases raw with ⟨base, vector⟩
  simp only at hBase
  subst base
  rfl

/-- A genuine smooth quotient tangent ghost generated by time translation. -/
def effectiveTimeTranslationGhost :
    SmoothDiffeomorphismGhost period hPeriod where
  toFun := effectiveTimeTranslationVelocity period hPeriod
  contMDiff_toFun :=
    (rawTimeTranslationBundle_contMDiff period hPeriod).congr
      (effectiveTimeTranslationVelocity_bundle period hPeriod)

private def effectiveTimeTranslationCurve
    (point : EffectiveQuotient period hPeriod) (parameter : Real) :
    EffectiveQuotient period hPeriod :=
  effectiveTimeFlow period hPeriod parameter point

private theorem effectiveTimeTranslationCurve_contMDiff
    (point : EffectiveQuotient period hPeriod) :
    ContMDiff 𝓘(Real, Real) coverModelWithCorners ω
      (effectiveTimeTranslationCurve period hPeriod point) := by
  exact ((effectiveJointTimeFlow_contMDiff period hPeriod).comp
    (contMDiff_id.prodMk contMDiff_const)).congr (fun _ => rfl)

private theorem rawTimeTranslationBundle_eq_curve
    (point : EffectiveQuotient period hPeriod) :
    rawTimeTranslationBundle period hPeriod point =
      tangentMap 𝓘(Real, Real) coverModelWithCorners
        (effectiveTimeTranslationCurve period hPeriod point)
        (⟨0, 1⟩ : TangentBundle 𝓘(Real, Real) Real) := by
  let slice : Real → Real × EffectiveQuotient period hPeriod :=
    fun parameter => (parameter, point)
  have hFlowAt : MDifferentiableAt
      (𝓘(Real, Real).prod coverModelWithCorners) coverModelWithCorners
      (effectiveJointTimeFlow period hPeriod) (0, point) :=
    (effectiveJointTimeFlow_contMDiff period hPeriod).mdifferentiableAt (by simp)
  have hSliceAt : MDifferentiableAt 𝓘(Real, Real)
      (𝓘(Real, Real).prod coverModelWithCorners) slice 0 :=
    mdifferentiableAt_id.prodMk mdifferentiableAt_const
  have hComp := tangentMap_comp_at
    (I := 𝓘(Real, Real))
    (I' := 𝓘(Real, Real).prod coverModelWithCorners)
    (I'' := coverModelWithCorners)
    (f := slice) (g := effectiveJointTimeFlow period hPeriod)
    (⟨0, 1⟩ : TangentBundle 𝓘(Real, Real) Real)
    hFlowAt hSliceAt
  rw [tangentMap_prod_left] at hComp
  change tangentMap 𝓘(Real, Real) coverModelWithCorners
      (effectiveTimeTranslationCurve period hPeriod point)
      (⟨0, 1⟩ : TangentBundle 𝓘(Real, Real) Real) =
    rawTimeTranslationBundle period hPeriod point at hComp
  exact hComp.symm

private theorem effectiveTimeTranslationVelocity_eq_curve_mfderiv
    (point : EffectiveQuotient period hPeriod) :
    effectiveTimeTranslationVelocity period hPeriod point =
      mfderiv 𝓘(Real, Real) coverModelWithCorners
        (effectiveTimeTranslationCurve period hPeriod point) 0 1 := by
  apply (TotalSpace.mk_injective
    (F := CoverCoordinates) (b := point))
  calc
    (⟨point, effectiveTimeTranslationVelocity period hPeriod point⟩ :
        TangentBundle coverModelWithCorners
          (EffectiveQuotient period hPeriod)) =
      rawTimeTranslationBundle period hPeriod point :=
        effectiveTimeTranslationVelocity_bundle period hPeriod point
    _ = tangentMap 𝓘(Real, Real) coverModelWithCorners
        (effectiveTimeTranslationCurve period hPeriod point)
        (⟨0, 1⟩ : TangentBundle 𝓘(Real, Real) Real) :=
      rawTimeTranslationBundle_eq_curve period hPeriod point
    _ = (⟨point,
          mfderiv 𝓘(Real, Real) coverModelWithCorners
            (effectiveTimeTranslationCurve period hPeriod point) 0 1⟩ :
        TangentBundle coverModelWithCorners
          (EffectiveQuotient period hPeriod)) := by
      simp [tangentMap, effectiveTimeTranslationCurve]
      exact HEq.rfl

/-- Public form of the intrinsic time-translation velocity: it is the
manifold derivative at zero of the genuine complete quotient flow. -/
theorem effectiveTimeTranslationVelocity_eq_timeFlow_mfderiv
    (point : EffectiveQuotient period hPeriod) :
    effectiveTimeTranslationVelocity period hPeriod point =
      mfderiv 𝓘(Real, Real) coverModelWithCorners
        (fun parameter : Real =>
          effectiveTimeFlow period hPeriod parameter point) 0 1 := by
  change effectiveTimeTranslationVelocity period hPeriod point =
    mfderiv 𝓘(Real, Real) coverModelWithCorners
      (effectiveTimeTranslationCurve period hPeriod point) 0 1
  exact effectiveTimeTranslationVelocity_eq_curve_mfderiv
    period hPeriod point

/-- Each orbit of the genuine complete quotient time flow is smooth. -/
theorem effectiveTimeFlow_orbit_contMDiff
    (point : EffectiveQuotient period hPeriod) :
    ContMDiff 𝓘(Real, Real) coverModelWithCorners ω
      (fun parameter : Real =>
        effectiveTimeFlow period hPeriod parameter point) := by
  change ContMDiff 𝓘(Real, Real) coverModelWithCorners ω
    (effectiveTimeTranslationCurve period hPeriod point)
  exact effectiveTimeTranslationCurve_contMDiff period hPeriod point

/-- Exact remaining regularity input for two arbitrary metric derivatives
along the fixed analytic time flow.  No arbitrary tangent ghost is
integrated. -/
structure TimeTranslationMetricPairContract
    (plusMetric minusMetric :
      SmoothSymmetricCovariantTwoTensor period hPeriod) where
  plusVariation : SmoothCovariantTwoTensor period hPeriod
  minusVariation : SmoothCovariantTwoTensor period hPeriod
  plus_realizes : ∀ point,
    plusVariation point =
      covariantTensorDiffeomorphismGeneratorAt period hPeriod
        (effectiveTimeFlowDiffeomorph period hPeriod)
        plusMetric.tensor.toTensorField point
  minus_realizes : ∀ point,
    minusVariation point =
      covariantTensorDiffeomorphismGeneratorAt period hPeriod
        (effectiveTimeFlowDiffeomorph period hPeriod)
        minusMetric.tensor.toTensorField point
  plus_symmetric : IsSymmetric period hPeriod plusVariation
  minus_symmetric : IsSymmetric period hPeriod minusVariation

/-- The specialized contract supplies an actual metric-pair pullback flow. -/
def TimeTranslationMetricPairContract.toFlow
    (plusMetric minusMetric :
      SmoothSymmetricCovariantTwoTensor period hPeriod)
    (contract : TimeTranslationMetricPairContract period hPeriod
      plusMetric minusMetric) :
    SmoothMetricPairPullbackFlow period hPeriod plusMetric minusMetric where
  curve := effectiveTimeFlowDiffeomorph period hPeriod
  atZero := by
    ext point
    exact effectiveTimeFlow_zero period hPeriod point
  map_add := by
    intro first second
    ext point
    simp only [Diffeomorph.coe_trans, Function.comp_apply]
    change effectiveTimeFlow period hPeriod (first + second) point =
      effectiveTimeFlow period hPeriod second
        (effectiveTimeFlow period hPeriod first point)
    simpa only [add_comm] using
      (effectiveTimeFlow_add period hPeriod second first point)
  orbit_smooth := by
    intro point
    change ContMDiff 𝓘(Real, Real) coverModelWithCorners ω
      (fun parameter => effectiveTimeFlow period hPeriod parameter point)
    exact ((effectiveJointTimeFlow_contMDiff period hPeriod).comp
      (contMDiff_id.prodMk contMDiff_const)).congr (fun _ => rfl)
  plusVariation := contract.plusVariation
  minusVariation := contract.minusVariation
  plus_realizes := contract.plus_realizes
  minus_realizes := contract.minus_realizes
  plusVariation_symmetric := contract.plus_symmetric
  minusVariation_symmetric := contract.minus_symmetric

/-- The specialized metric flow has exactly the smooth ghost generated by
the complete time-translation subgroup. -/
theorem TimeTranslationMetricPairContract.toFlow_generates_timeGhost
    (plusMetric minusMetric :
      SmoothSymmetricCovariantTwoTensor period hPeriod)
    (contract : TimeTranslationMetricPairContract period hPeriod
      plusMetric minusMetric)
    (point : EffectiveQuotient period hPeriod) :
    (contract.toFlow period hPeriod plusMetric minusMetric).velocityAt
        period hPeriod plusMetric minusMetric point =
      effectiveTimeTranslationGhost period hPeriod point := by
  change (contract.toFlow period hPeriod plusMetric minusMetric).velocityAt
      period hPeriod plusMetric minusMetric point =
    effectiveTimeTranslationVelocity period hPeriod point
  apply (TotalSpace.mk_injective
    (F := CoverCoordinates) (b := point))
  calc
    (⟨point,
        (contract.toFlow period hPeriod plusMetric minusMetric).velocityAt
          period hPeriod plusMetric minusMetric point⟩ :
        TangentBundle coverModelWithCorners
          (EffectiveQuotient period hPeriod)) =
      tangentMap 𝓘(Real, Real) coverModelWithCorners
        (effectiveTimeTranslationCurve period hPeriod point)
        (⟨0, 1⟩ : TangentBundle 𝓘(Real, Real) Real) := by
      unfold SmoothMetricPairPullbackFlow.velocityAt
      unfold SmoothMetricPairPullbackFlow.orbit
      unfold infinitesimalGenerator
      simp [tangentMap, TimeTranslationMetricPairContract.toFlow,
        effectiveTimeTranslationCurve]
      exact HEq.rfl
    _ = rawTimeTranslationBundle period hPeriod point :=
      (rawTimeTranslationBundle_eq_curve period hPeriod point).symm
    _ = (⟨point, effectiveTimeTranslationVelocity period hPeriod point⟩ :
        TangentBundle coverModelWithCorners
          (EffectiveQuotient period hPeriod)) :=
      (effectiveTimeTranslationVelocity_bundle period hPeriod point).symm

/-- Parameters for the true time-translation line and the two existing
abelian gauge factors.  There is deliberately no LL component. -/
abbrev TimeTranslationMatterGaugeParameterSpace :=
  Real ×
    (SmoothQuotientField period hPeriod GaugeLieAlgebra ×
      SmoothQuotientField period hPeriod GaugeLieAlgebra)

/-- Linear inclusion of the time-translation Lie algebra into smooth D8
diffeomorphism ghosts. -/
def timeTranslationGhostLine :
    Real →ₗ[Real] SmoothDiffeomorphismGhost period hPeriod where
  toFun amplitude := amplitude • effectiveTimeTranslationGhost period hPeriod
  map_add' first second := add_smul first second _
  map_smul' scalar amplitude := mul_smul scalar amplitude _

/-- Inclusion of the restricted parameters into the already implemented
matter plus `U(1)^2` parameter space. -/
def timeTranslationMatterGaugeParameterEmbedding :
    TimeTranslationMatterGaugeParameterSpace period hPeriod →ₗ[Real]
      MatterGaugeParameterSpace period hPeriod where
  toFun parameters :=
    (timeTranslationGhostLine period hPeriod parameters.1, parameters.2)
  map_add' first second := by
    apply Prod.ext
    · exact (timeTranslationGhostLine period hPeriod).map_add first.1 second.1
    · rfl
  map_smul' scalar parameters := by
    apply Prod.ext
    · exact (timeTranslationGhostLine period hPeriod).map_smul scalar parameters.1
    · rfl

/-- The strongest honest metric linearization supplied by one real subgroup:
scalar multiples of the two actual time-flow derivatives. -/
def timeTranslationMetricVariation
    (plusMetric minusMetric :
      SmoothSymmetricCovariantTwoTensor period hPeriod)
    (contract : TimeTranslationMetricPairContract period hPeriod
      plusMetric minusMetric) :
    Real →ₗ[Real]
      (SmoothCovariantTwoTensor period hPeriod ×
        SmoothCovariantTwoTensor period hPeriod) :=
  LinearMap.toSpanSingleton Real _
    (contract.plusVariation, contract.minusVariation)

/-- Restricted combined `R`: the metric block follows the genuine time
subgroup, while matter and `U(1)^2` reuse the existing concrete generator. -/
def timeTranslationMetricMatterGaugeLinearizedVariation
    (fields : IndependentFields period hPeriod)
    (plusMetric minusMetric :
      SmoothSymmetricCovariantTwoTensor period hPeriod)
    (contract : TimeTranslationMetricPairContract period hPeriod
      plusMetric minusMetric) :
    TimeTranslationMatterGaugeParameterSpace period hPeriod →ₗ[Real]
      MetricMatterGaugeVariationSpace period hPeriod :=
  LinearMap.prod
    ((timeTranslationMetricVariation period hPeriod plusMetric minusMetric
      contract).comp (LinearMap.fst Real Real _))
    ((matterGaugeGenerator period hPeriod fields).comp
      (timeTranslationMatterGaugeParameterEmbedding period hPeriod))

@[simp]
theorem timeTranslationMetricMatterGaugeLinearizedVariation_metric
    (fields : IndependentFields period hPeriod)
    (plusMetric minusMetric :
      SmoothSymmetricCovariantTwoTensor period hPeriod)
    (contract : TimeTranslationMetricPairContract period hPeriod
      plusMetric minusMetric)
    (parameters : TimeTranslationMatterGaugeParameterSpace period hPeriod) :
    (timeTranslationMetricMatterGaugeLinearizedVariation period hPeriod fields
      plusMetric minusMetric contract parameters).1 =
        parameters.1 •
          (contract.plusVariation, contract.minusVariation) :=
  by
    simp [timeTranslationMetricMatterGaugeLinearizedVariation,
      timeTranslationMetricVariation]

@[simp]
theorem timeTranslationMetricMatterGaugeLinearizedVariation_matterGauge
    (fields : IndependentFields period hPeriod)
    (plusMetric minusMetric :
      SmoothSymmetricCovariantTwoTensor period hPeriod)
    (contract : TimeTranslationMetricPairContract period hPeriod
      plusMetric minusMetric)
    (parameters : TimeTranslationMatterGaugeParameterSpace period hPeriod) :
    (timeTranslationMetricMatterGaugeLinearizedVariation period hPeriod fields
      plusMetric minusMetric contract parameters).2 =
        matterGaugeGenerator period hPeriod fields
          (timeTranslationMatterGaugeParameterEmbedding period hPeriod
            parameters) :=
  rfl

/-- Restricted algebraic `B = E ∘ R`. -/
def timeTranslationMetricMatterGaugeNoetherOperator
    (fields : IndependentFields period hPeriod)
    (plusMetric minusMetric :
      SmoothSymmetricCovariantTwoTensor period hPeriod)
    (contract : TimeTranslationMetricPairContract period hPeriod
      plusMetric minusMetric)
    (euler : MetricMatterGaugeVariationSpace period hPeriod →ₗ[Real] Real) :
    TimeTranslationMatterGaugeParameterSpace period hPeriod →ₗ[Real] Real :=
  euler.comp
    (timeTranslationMetricMatterGaugeLinearizedVariation period hPeriod fields
      plusMetric minusMetric contract)

@[simp]
theorem timeTranslationMetricMatterGaugeNoetherOperator_apply
    (fields : IndependentFields period hPeriod)
    (plusMetric minusMetric :
      SmoothSymmetricCovariantTwoTensor period hPeriod)
    (contract : TimeTranslationMetricPairContract period hPeriod
      plusMetric minusMetric)
    (euler : MetricMatterGaugeVariationSpace period hPeriod →ₗ[Real] Real)
    (parameters : TimeTranslationMatterGaugeParameterSpace period hPeriod) :
    timeTranslationMetricMatterGaugeNoetherOperator period hPeriod fields
        plusMetric minusMetric contract euler parameters =
      euler (timeTranslationMetricMatterGaugeLinearizedVariation period hPeriod
        fields plusMetric minusMetric contract parameters) :=
  rfl

theorem timeTranslationMetricMatterGaugeNoetherOperator_eq_zero_iff
    (fields : IndependentFields period hPeriod)
    (plusMetric minusMetric :
      SmoothSymmetricCovariantTwoTensor period hPeriod)
    (contract : TimeTranslationMetricPairContract period hPeriod
      plusMetric minusMetric)
    (euler : MetricMatterGaugeVariationSpace period hPeriod →ₗ[Real] Real) :
    timeTranslationMetricMatterGaugeNoetherOperator period hPeriod fields
        plusMetric minusMetric contract euler = 0 ↔
      ∀ parameters : TimeTranslationMatterGaugeParameterSpace period hPeriod,
        euler (timeTranslationMetricMatterGaugeLinearizedVariation period hPeriod
          fields plusMetric minusMetric contract parameters) = 0 := by
  constructor
  · intro hZero parameters
    exact LinearMap.congr_fun hZero parameters
  · intro hAnnihilates
    apply LinearMap.ext
    exact hAnnihilates

/-- Pure geometric time direction, with both `U(1)` parameters set to zero. -/
def pureTimeTranslationParameter (amplitude : Real) :
    TimeTranslationMatterGaugeParameterSpace period hPeriod :=
  (amplitude, 0)

def unitTimeTranslationParameter :
    TimeTranslationMatterGaugeParameterSpace period hPeriod :=
  pureTimeTranslationParameter period hPeriod 1

theorem pureTimeTranslationParameter_eq_smul_unit (amplitude : Real) :
    pureTimeTranslationParameter period hPeriod amplitude =
      amplitude • unitTimeTranslationParameter period hPeriod := by
  apply Prod.ext <;> simp [pureTimeTranslationParameter,
    unitTimeTranslationParameter]

/-- Infinitesimal variations along the complete subgroup scale with its Lie
algebra parameter. -/
theorem timeTranslationMetricMatterGaugeLinearizedVariation_pureTime
    (fields : IndependentFields period hPeriod)
    (plusMetric minusMetric :
      SmoothSymmetricCovariantTwoTensor period hPeriod)
    (contract : TimeTranslationMetricPairContract period hPeriod
      plusMetric minusMetric)
    (amplitude : Real) :
    timeTranslationMetricMatterGaugeLinearizedVariation period hPeriod fields
        plusMetric minusMetric contract
        (pureTimeTranslationParameter period hPeriod amplitude) =
      amplitude •
        timeTranslationMetricMatterGaugeLinearizedVariation period hPeriod fields
          plusMetric minusMetric contract
          (unitTimeTranslationParameter period hPeriod) := by
  rw [pureTimeTranslationParameter_eq_smul_unit]
  exact (timeTranslationMetricMatterGaugeLinearizedVariation period hPeriod fields
    plusMetric minusMetric contract).map_smul amplitude _

/-- Finite line invariance for every restricted time plus `U(1)^2`
direction. -/
def TimeTranslationMetricMatterGaugeLineInvariantAtZero
    (fields : IndependentFields period hPeriod)
    (plusMetric minusMetric :
      SmoothSymmetricCovariantTwoTensor period hPeriod)
    (contract : TimeTranslationMetricPairContract period hPeriod
      plusMetric minusMetric)
    (action : MetricMatterGaugeVariationSpace period hPeriod → Real) : Prop :=
  ∀ parameters : TimeTranslationMatterGaugeParameterSpace period hPeriod,
    ∀ lineParameter : Real,
      action (lineParameter •
        timeTranslationMetricMatterGaugeLinearizedVariation period hPeriod
          fields plusMetric minusMetric contract parameters) = action 0

/-- The existing directional first-variation bridge gives the restricted
metric/matter/`U(1)^2` Noether identity. -/
theorem timeTranslationMetricMatterGaugeNoetherOperator_eq_zero_of_invariant
    (fields : IndependentFields period hPeriod)
    (plusMetric minusMetric :
      SmoothSymmetricCovariantTwoTensor period hPeriod)
    (contract : TimeTranslationMetricPairContract period hPeriod
      plusMetric minusMetric)
    (action : MetricMatterGaugeVariationSpace period hPeriod → Real)
    (euler : MetricMatterGaugeVariationSpace period hPeriod →ₗ[Real] Real)
    (hFirstVariation :
      HasMetricMatterGaugeDirectionalFirstVariationAtZero period hPeriod
        action euler)
    (hInvariant :
      TimeTranslationMetricMatterGaugeLineInvariantAtZero period hPeriod fields
        plusMetric minusMetric contract action) :
    timeTranslationMetricMatterGaugeNoetherOperator period hPeriod fields
      plusMetric minusMetric contract euler = 0 := by
  apply (timeTranslationMetricMatterGaugeNoetherOperator_eq_zero_iff period
    hPeriod fields plusMetric minusMetric contract euler).2
  intro parameters
  let direction := timeTranslationMetricMatterGaugeLinearizedVariation period
    hPeriod fields plusMetric minusMetric contract parameters
  have hActionDerivative := hFirstVariation direction
  have hCurveConstant :
      (fun lineParameter : Real => action (lineParameter • direction)) =
        fun _ => action 0 := by
    funext lineParameter
    exact hInvariant parameters lineParameter
  have hZeroDerivative :
      HasDerivAt (fun lineParameter : Real =>
        action (lineParameter • direction)) 0 0 := by
    rw [hCurveConstant]
    exact hasDerivAt_const (x := (0 : Real)) (c := action 0)
  exact hActionDerivative.unique hZeroDerivative

/-- Invariance under only the true geometric time subgroup gives exactly the
time component of `B`, without claiming the independent `U(1)^2` identities. -/
def PureTimeTranslationLineInvariantAtZero
    (fields : IndependentFields period hPeriod)
    (plusMetric minusMetric :
      SmoothSymmetricCovariantTwoTensor period hPeriod)
    (contract : TimeTranslationMetricPairContract period hPeriod
      plusMetric minusMetric)
    (action : MetricMatterGaugeVariationSpace period hPeriod → Real) : Prop :=
  ∀ lineParameter : Real,
    action (lineParameter •
      timeTranslationMetricMatterGaugeLinearizedVariation period hPeriod fields
        plusMetric minusMetric contract
        (unitTimeTranslationParameter period hPeriod)) = action 0

theorem timeTranslationNoether_identity
    (fields : IndependentFields period hPeriod)
    (plusMetric minusMetric :
      SmoothSymmetricCovariantTwoTensor period hPeriod)
    (contract : TimeTranslationMetricPairContract period hPeriod
      plusMetric minusMetric)
    (action : MetricMatterGaugeVariationSpace period hPeriod → Real)
    (euler : MetricMatterGaugeVariationSpace period hPeriod →ₗ[Real] Real)
    (hFirstVariation :
      HasMetricMatterGaugeDirectionalFirstVariationAtZero period hPeriod
        action euler)
    (hInvariant : PureTimeTranslationLineInvariantAtZero period hPeriod fields
      plusMetric minusMetric contract action) :
    timeTranslationMetricMatterGaugeNoetherOperator period hPeriod fields
        plusMetric minusMetric contract euler
        (unitTimeTranslationParameter period hPeriod) = 0 := by
  rw [timeTranslationMetricMatterGaugeNoetherOperator_apply]
  let direction := timeTranslationMetricMatterGaugeLinearizedVariation period
    hPeriod fields plusMetric minusMetric contract
      (unitTimeTranslationParameter period hPeriod)
  have hActionDerivative := hFirstVariation direction
  have hCurveConstant :
      (fun lineParameter : Real => action (lineParameter • direction)) =
        fun _ => action 0 := by
    funext lineParameter
    exact hInvariant lineParameter
  have hZeroDerivative :
      HasDerivAt (fun lineParameter : Real =>
        action (lineParameter • direction)) 0 0 := by
    rw [hCurveConstant]
    exact hasDerivAt_const (x := (0 : Real)) (c := action 0)
  exact hActionDerivative.unique hZeroDerivative

end

end P0EFTJanusMappingTorusTimeTranslationMetricMatterGaugeNoether4D
end JanusFormal
