import JanusFormal.Branches.FundamentalGeometryPVariationalPrinciple.Gates.P0EFTJanusProgramPCandidateAFiveSectorSelfAdjointOperatorGarding4D
import JanusFormal.Branches.FundamentalGeometryPVariationalPrinciple.Gates.P0EFTJanusProgramPProjectionFiniteMarginActualKernelGap4D

/-!
# Actual-kernel gap from symmetric idempotent sector projections

A finite actual kernel and the operator lower bound generated by five symmetric
idempotent projections on its orthogonal complement form the complete H12 gap
packet.
-/

namespace JanusFormal
namespace P0EFTJanusProgramPSelfAdjointProjectionFiniteMarginActualKernelGap4D

set_option autoImplicit false
noncomputable section

open scoped InnerProductSpace
open P0EFTJanusProgramPCandidateAFiveSectorSelfAdjointOperatorGarding4D
open P0EFTJanusProgramPProjectionFiniteMarginActualKernelGap4D
open P0EFTJanusProgramPSelfAdjointKernelComplementReduction4D

variable {E : Type*}
  [NormedAddCommGroup E] [InnerProductSpace Real E] [CompleteSpace E]

/-- Finite actual kernel and natural five-projection control of its orthogonal
complement. -/
structure SelfAdjointProjectionFiniteMarginActualKernelGapData
    (operator : E →L[Real] E)
    (hSelfAdjoint : IsSelfAdjoint operator) where
  kernel_finite : FiniteDimensional Real operator.ker
  projectionGarding : CandidateAFiveSectorSelfAdjointOperatorGardingData
    (selfAdjointKernelComplementOperator operator hSelfAdjoint)

namespace SelfAdjointProjectionFiniteMarginActualKernelGapData

/-- Positive-projection actual-kernel packet. -/
def toProjectionFiniteMarginActualKernelGapData
    {operator : E →L[Real] E}
    {hSelfAdjoint : IsSelfAdjoint operator}
    (data : SelfAdjointProjectionFiniteMarginActualKernelGapData
      operator hSelfAdjoint) :
    ProjectionFiniteMarginActualKernelGapData operator hSelfAdjoint where
  kernel_finite := data.kernel_finite
  projectionGarding :=
    CandidateAFiveSectorSelfAdjointOperatorGardingData.toProjectionOperatorGardingData
      data.projectionGarding

/-- Established actual-kernel gap. -/
def toGapData
    {operator : E →L[Real] E}
    {hSelfAdjoint : IsSelfAdjoint operator}
    (data : SelfAdjointProjectionFiniteMarginActualKernelGapData
      operator hSelfAdjoint) :
    SelfAdjointKernelComplementGapData operator hSelfAdjoint :=
  ProjectionFiniteMarginActualKernelGapData.toGapData
    (toProjectionFiniteMarginActualKernelGapData data)

/-- Public natural-projection actual-kernel checkpoint. -/
def selfAdjoint_projection_finite_margin_actual_kernel_gap_gate
    (operator : E →L[Real] E)
    (hSelfAdjoint : IsSelfAdjoint operator)
    (data : SelfAdjointProjectionFiniteMarginActualKernelGapData
      operator hSelfAdjoint) :
    SelfAdjointKernelComplementGapData operator hSelfAdjoint :=
  toGapData data

end SelfAdjointProjectionFiniteMarginActualKernelGapData

end
end P0EFTJanusProgramPSelfAdjointProjectionFiniteMarginActualKernelGap4D
end JanusFormal
