import JanusFormal.Branches.FundamentalGeometryPVariationalPrinciple.Gates.P0EFTJanusProgramPReferenceNuclearDuhamelBoundaryLimits4D
import Mathlib.MeasureTheory.Measure.Typeclasses.Probability
import JanusFormal.Branches.FundamentalGeometryPVariationalPrinciple.Gates.P0EFTJanusProgramPReferenceNuclearDuhamelGreenCollapsedBoundary4D

/-!
# Collapsed Duhamel--Green matching from endpoint limits

This frontend removes the last two exact boundary equalities from the collapsed
Duhamel packet.

The short-time equality is obtained from convergence of cutoff counterterms,
cutoff spectral integrals and their renormalized remainder.  The long-time
equality is obtained from a finite-cutoff primitive formula and decay of its
terminal value.  These limit theorems are then inserted into the existing
semigroup-collapsed rank-one boundary construction.
-/

namespace JanusFormal
namespace P0EFTJanusProgramPReferenceNuclearDuhamelGreenCollapsedBoundaryLimits4D

set_option autoImplicit false
noncomputable section

open MeasureTheory

open Filter Set
open P0EFTJanusProgramPIntrinsicNuclearTrace4D
open P0EFTJanusProgramPNuclearHeatDuhamelTraceVariation4D
open P0EFTJanusProgramPNuclearHeatDuhamelWeightedIntegral4D.NuclearHeatDuhamelTraceVariationData
open P0EFTJanusProgramPNuclearDuhamelCollapsedRankOneIntegral4D
open P0EFTJanusProgramPReferenceNuclearDuhamelBoundaryLimits4D
open P0EFTJanusProgramPReferenceNuclearDuhamelGreenCollapsedBoundary4D

universe e i s a b

variable {Slice : Type s} {ShortCutoff : Type a} {LongCutoff : Type b}
  {E : Type e}
  [MeasurableSpace Slice]
  [NormedAddCommGroup E]
  [InnerProductSpace Real E] [CompleteSpace E]

/-- Complete collapsed reference boundary data whose short- and long-time
matching identities are generated by endpoint limits. -/
structure ReferenceNuclearDuhamelGreenCollapsedBoundaryLimitsData
    (sliceMeasure : Measure Slice) [IsProbabilityMeasure sliceMeasure]
    (shortCutoffFilter : Filter ShortCutoff) [NeBot shortCutoffFilter]
    (longCutoffFilter : Filter LongCutoff) [NeBot longCutoffFilter]
    (nuclear : NuclearHeatDuhamelTraceVariationData.{e, i} (E := E))
    (shortTimeRegion longTimeRegion : Set Real) where
  countertermOperator : Real → E →L[Real] E
  countertermTraceClass : ∀ parameter,
    IntrinsicNuclearTraceData.{e, i} (countertermOperator parameter)
  countertermDerivative : Real → Real
  countertermDerivative_eq_trace : ∀ parameter,
    countertermDerivative parameter =
      intrinsicNuclearTrace (countertermTraceClass parameter)
  shortTime : NuclearDuhamelCollapsedRankOneIntegralData sliceMeasure nuclear
    shortTimeRegion
  longTime : NuclearDuhamelCollapsedRankOneIntegralData sliceMeasure nuclear
    longTimeRegion
  countertermMinusShortTraceClass : ∀ parameter,
    IntrinsicNuclearTraceData.{e, i}
      (countertermOperator parameter - shortTime.integratedOperator parameter)
  totalTraceClass : ∀ parameter,
    IntrinsicNuclearTraceData.{e, i}
      ((countertermOperator parameter - shortTime.integratedOperator parameter) -
        longTime.integratedOperator parameter)
  logarithmicDerivativeOperator : Real → E →L[Real] E
  logarithmicDerivativeTraceClass : ∀ parameter,
    IntrinsicNuclearTraceData.{e, i} (logarithmicDerivativeOperator parameter)
  matchingOperator : Real → E →L[Real] E
  shortBoundaryLimit : ∀ parameter,
    ReferenceNuclearDuhamelShortTimeBoundaryLimitData shortCutoffFilter
      (countertermOperator parameter)
      (shortTime.integratedOperator parameter)
      (logarithmicDerivativeOperator parameter)
      (matchingOperator parameter)
  longBoundaryLimit : ∀ parameter,
    ReferenceNuclearDuhamelLongTimeBoundaryLimitData longCutoffFilter
      (longTime.integratedOperator parameter)
      (matchingOperator parameter)

namespace ReferenceNuclearDuhamelGreenCollapsedBoundaryLimitsData

/-- Convert endpoint limits into exact short/long boundary matching. -/
def toCollapsedBoundary
    {sliceMeasure : Measure Slice} [IsProbabilityMeasure sliceMeasure]
    {shortCutoffFilter : Filter ShortCutoff} [NeBot shortCutoffFilter]
    {longCutoffFilter : Filter LongCutoff} [NeBot longCutoffFilter]
    {nuclear : NuclearHeatDuhamelTraceVariationData.{e, i} (E := E)}
    {shortTimeRegion longTimeRegion : Set Real}
    (data : ReferenceNuclearDuhamelGreenCollapsedBoundaryLimitsData
      sliceMeasure shortCutoffFilter longCutoffFilter nuclear
        shortTimeRegion longTimeRegion) :
    ReferenceNuclearDuhamelGreenCollapsedBoundaryData sliceMeasure nuclear
      shortTimeRegion longTimeRegion where
  countertermOperator := data.countertermOperator
  countertermTraceClass := data.countertermTraceClass
  countertermDerivative := data.countertermDerivative
  countertermDerivative_eq_trace := data.countertermDerivative_eq_trace
  shortTime := data.shortTime
  longTime := data.longTime
  countertermMinusShortTraceClass := data.countertermMinusShortTraceClass
  totalTraceClass := data.totalTraceClass
  logarithmicDerivativeOperator := data.logarithmicDerivativeOperator
  logarithmicDerivativeTraceClass := data.logarithmicDerivativeTraceClass
  matchingOperator := data.matchingOperator
  shortBoundaryIdentity := fun parameter =>
    (data.shortBoundaryLimit parameter).boundaryIdentity
  longBoundaryIdentity := fun parameter =>
    (data.longBoundaryLimit parameter).boundaryIdentity

/-- Short-time boundary matching follows from renormalized cutoff convergence. -/
theorem shortBoundaryIdentity
    {sliceMeasure : Measure Slice} [IsProbabilityMeasure sliceMeasure]
    {shortCutoffFilter : Filter ShortCutoff} [NeBot shortCutoffFilter]
    {longCutoffFilter : Filter LongCutoff} [NeBot longCutoffFilter]
    {nuclear : NuclearHeatDuhamelTraceVariationData.{e, i} (E := E)}
    {shortTimeRegion longTimeRegion : Set Real}
    (data : ReferenceNuclearDuhamelGreenCollapsedBoundaryLimitsData
      sliceMeasure shortCutoffFilter longCutoffFilter nuclear
        shortTimeRegion longTimeRegion)
    (parameter : Real) :
    data.countertermOperator parameter -
        data.shortTime.integratedOperator parameter =
      data.logarithmicDerivativeOperator parameter +
        data.matchingOperator parameter :=
  (data.shortBoundaryLimit parameter).boundaryIdentity

/-- Long-time matching follows from terminal primitive decay. -/
theorem longBoundaryIdentity
    {sliceMeasure : Measure Slice} [IsProbabilityMeasure sliceMeasure]
    {shortCutoffFilter : Filter ShortCutoff} [NeBot shortCutoffFilter]
    {longCutoffFilter : Filter LongCutoff} [NeBot longCutoffFilter]
    {nuclear : NuclearHeatDuhamelTraceVariationData.{e, i} (E := E)}
    {shortTimeRegion longTimeRegion : Set Real}
    (data : ReferenceNuclearDuhamelGreenCollapsedBoundaryLimitsData
      sliceMeasure shortCutoffFilter longCutoffFilter nuclear
        shortTimeRegion longTimeRegion)
    (parameter : Real) :
    data.longTime.integratedOperator parameter =
      data.matchingOperator parameter :=
  (data.longBoundaryLimit parameter).boundaryIdentity

/-- The complete integrated Duhamel--Green identity is now generated from
semigroup collapse, spectral integration and endpoint limits. -/
theorem integratedDuhamel_eq_logarithmicTrace
    {sliceMeasure : Measure Slice} [IsProbabilityMeasure sliceMeasure]
    {shortCutoffFilter : Filter ShortCutoff} [NeBot shortCutoffFilter]
    {longCutoffFilter : Filter LongCutoff} [NeBot longCutoffFilter]
    {nuclear : NuclearHeatDuhamelTraceVariationData.{e, i} (E := E)}
    {shortTimeRegion longTimeRegion : Set Real}
    (data : ReferenceNuclearDuhamelGreenCollapsedBoundaryLimitsData
      sliceMeasure shortCutoffFilter longCutoffFilter nuclear
        shortTimeRegion longTimeRegion)
    (parameter : Real) :
    data.countertermDerivative parameter -
        (∫ time in shortTimeRegion,
          extendedDuhamelTrace nuclear parameter time) -
        (∫ time in longTimeRegion,
          extendedDuhamelTrace nuclear parameter time) =
      data.toCollapsedBoundary.toBoundaryMatching.toOperatorIdentity.logarithmicTrace
        parameter :=
  data.toCollapsedBoundary.integratedDuhamel_eq_logarithmicTrace parameter

/-- Public endpoint-limit collapsed-boundary checkpoint. -/
theorem reference_nuclear_duhamel_green_collapsed_boundary_limits_gate
    (sliceMeasure : Measure Slice) [IsProbabilityMeasure sliceMeasure]
    (shortCutoffFilter : Filter ShortCutoff) [NeBot shortCutoffFilter]
    (longCutoffFilter : Filter LongCutoff) [NeBot longCutoffFilter]
    (nuclear : NuclearHeatDuhamelTraceVariationData.{e, i} (E := E))
    (shortTimeRegion longTimeRegion : Set Real)
    (data : ReferenceNuclearDuhamelGreenCollapsedBoundaryLimitsData
      sliceMeasure shortCutoffFilter longCutoffFilter nuclear
        shortTimeRegion longTimeRegion) :
    (∀ parameter,
      data.countertermOperator parameter -
          data.shortTime.integratedOperator parameter =
        data.logarithmicDerivativeOperator parameter +
          data.matchingOperator parameter) ∧
    (∀ parameter,
      data.longTime.integratedOperator parameter =
        data.matchingOperator parameter) ∧
    (∀ parameter,
      data.countertermDerivative parameter -
          (∫ time in shortTimeRegion,
            extendedDuhamelTrace nuclear parameter time) -
          (∫ time in longTimeRegion,
            extendedDuhamelTrace nuclear parameter time) =
        data.toCollapsedBoundary.toBoundaryMatching.toOperatorIdentity.logarithmicTrace
          parameter) :=
  ⟨data.shortBoundaryIdentity,
    data.longBoundaryIdentity,
    data.integratedDuhamel_eq_logarithmicTrace⟩

end ReferenceNuclearDuhamelGreenCollapsedBoundaryLimitsData

end
end P0EFTJanusProgramPReferenceNuclearDuhamelGreenCollapsedBoundaryLimits4D
end JanusFormal
