import JanusFormal.Branches.FundamentalGeometryPVariationalPrinciple.Gates.P0EFTJanusMappingTorusCanonicalLatitudeCauchyJetProfileIntegrability4D
import JanusFormal.Branches.FundamentalGeometryPVariationalPrinciple.Gates.P0EFTJanusMappingTorusCanonicalPhysicalScalarCauchyJetCompatibilityGreenCore4D
import JanusFormal.Branches.FundamentalGeometryPVariationalPrinciple.Gates.P0EFTJanusMappingTorusCanonicalPhysicalScalarCauchyJetCompatibilityBridge4D
import JanusFormal.Branches.FundamentalGeometryPVariationalPrinciple.Gates.P0EFTJanusMappingTorusCanonicalPhysicalScalarCauchyJetEulerProductRealization4D
import JanusFormal.Branches.FundamentalGeometryPVariationalPrinciple.Gates.P0EFTJanusMappingTorusCanonicalPhysicalScalarFirstSheetBoundaryExtension4D
import JanusFormal.Branches.FundamentalGeometryPVariationalPrinciple.Gates.P0EFTJanusMappingTorusCanonicalLatitudeMinimalCutoffL2Convergence4D
import JanusFormal.Branches.FundamentalGeometryPVariationalPrinciple.Gates.P0EFTJanusMappingTorusScalarHilbertGreenCoreRieszBoundaryTrace4D

/-!
# Physical completed boundary triple by Riesz duality

The explicit Cauchy jet already has:

* an automatic bulk `L²` estimate from the two fixed normal-profile moments;
* a product-coordinate Euler estimate;
* exact smooth Cauchy data;
* a dense zero-Cauchy minimal core from the global shrinking cutoffs.

These facts make the smooth Cauchy extension bounded in the maximal graph norm.
The generic Riesz theorem then reconstructs the complete boundary trace from the
Green form itself.  Consequently no independent value/normal graph trace
estimate and no higher normal regularity space are needed.

The output is a surjective completed boundary triple whose trace is the
Riesz-represented Green boundary functional and whose right inverse is the
completed explicit Cauchy extension.
-/

namespace JanusFormal
namespace P0EFTJanusMappingTorusCanonicalPhysicalScalarCauchyJetRieszBoundaryTriple4D

set_option autoImplicit false
noncomputable section

open Set Topology MeasureTheory
open P0EFTJanusMappingTorusSmoothFieldDescent4D
open P0EFTJanusMappingTorusCanonicalLatitudeCauchyJetProfileIntegrability4D
open P0EFTJanusMappingTorusCanonicalPhysicalScalarCauchyJetCompatibilityGreenCore4D
open P0EFTJanusMappingTorusCanonicalPhysicalScalarCauchyJetGeometricGreenCore4D
open P0EFTJanusMappingTorusCanonicalPhysicalScalarCauchyJetProfileL2Bound4D
open P0EFTJanusMappingTorusCanonicalPhysicalScalarCauchyJetEulerProductRealization4D
open P0EFTJanusMappingTorusCanonicalPhysicalScalarFirstSheetHilbertTrace4D
open P0EFTJanusMappingTorusCanonicalPhysicalScalarFirstSheetBoundaryExtension4D
open P0EFTJanusMappingTorusCanonicalLatitudeMinimalCutoffL2Convergence4D
open P0EFTJanusMappingTorusScalarHilbertGreenCoreCompletion4D
open P0EFTJanusMappingTorusScalarBoundaryCauchyGraphExtension4D
open P0EFTJanusMappingTorusScalarHilbertGreenCoreRieszBoundaryTrace4D

universe x y

variable (period : Real) (hPeriod : period ≠ 0)
variable {massSquared : Real}

/-- Physical Riesz-boundary data: the only quantitative input is the explicit
Euler estimate of the Cauchy jet. -/
structure CanonicalPhysicalScalarCauchyJetRieszBoundaryData
    (massSquared : Real)
    (ValueCore : Type x) (NormalCore : Type y)
    [AddCommGroup ValueCore] [Module Real ValueCore]
    [AddCommGroup NormalCore] [Module Real NormalCore] where
  geometric : CanonicalPhysicalScalarCauchyJetCompatibilityData
    period hPeriod massSquared ValueCore NormalCore
  eulerEstimate :
    (geometric.toCauchyJetGeometricData period hPeriod).CauchyJetEulerProductEstimateData
      period hPeriod
      ((geometric.toCauchyJetGeometricData period hPeriod)
        |>.canonicalEulerProductRealization period hPeriod)

namespace CanonicalPhysicalScalarCauchyJetRieszBoundaryData

/-- Explicit geometric Cauchy-jet data. -/
def jetGeometric
    {ValueCore : Type x} {NormalCore : Type y}
    [AddCommGroup ValueCore] [Module Real ValueCore]
    [AddCommGroup NormalCore] [Module Real NormalCore]
    (data : CanonicalPhysicalScalarCauchyJetRieszBoundaryData
      period hPeriod massSquared ValueCore NormalCore) :=
  data.geometric.toCauchyJetGeometricData period hPeriod

/-- Automatic bulk estimate generated by the fixed profile moments. -/
def bulkEstimate
    {ValueCore : Type x} {NormalCore : Type y}
    [AddCommGroup ValueCore] [Module Real ValueCore]
    [AddCommGroup NormalCore] [Module Real NormalCore]
    (data : CanonicalPhysicalScalarCauchyJetRieszBoundaryData
      period hPeriod massSquared ValueCore NormalCore) :=
  (data.jetGeometric period hPeriod).cauchyJetProductL2EstimateData
    period hPeriod
    canonicalLatitudeCauchyJetProfileIntegrabilityData

/-- Complete squared bulk/Euler graph estimate. -/
def squaredGraphEstimate
    {ValueCore : Type x} {NormalCore : Type y}
    [AddCommGroup ValueCore] [Module Real ValueCore]
    [AddCommGroup NormalCore] [Module Real NormalCore]
    (data : CanonicalPhysicalScalarCauchyJetRieszBoundaryData
      period hPeriod massSquared ValueCore NormalCore) :=
  data.eulerEstimate.combine period hPeriod (data.bulkEstimate period hPeriod)

/-- Linear graph estimate for the explicit Cauchy extension. -/
def graphEstimate
    {ValueCore : Type x} {NormalCore : Type y}
    [AddCommGroup ValueCore] [Module Real ValueCore]
    [AddCommGroup NormalCore] [Module Real NormalCore]
    (data : CanonicalPhysicalScalarCauchyJetRieszBoundaryData
      period hPeriod massSquared ValueCore NormalCore) :=
  (data.squaredGraphEstimate period hPeriod).toComponentGraphEstimateData
    period hPeriod

/-- Generic smooth Cauchy extension underlying the physical jet. -/
def smoothExtension
    {ValueCore : Type x} {NormalCore : Type y}
    [AddCommGroup ValueCore] [Module Real ValueCore]
    [AddCommGroup NormalCore] [Module Real NormalCore]
    (data : CanonicalPhysicalScalarCauchyJetRieszBoundaryData
      period hPeriod massSquared ValueCore NormalCore) :=
  (data.geometric.toCompatibilityGreenCoreData period hPeriod)
    |>.smoothCauchyExtensionData period hPeriod
    |>.toGenericExtension

/-- Bounded graph-valued Cauchy extension. -/
def boundedSmoothExtension
    {ValueCore : Type x} {NormalCore : Type y}
    [AddCommGroup ValueCore] [Module Real ValueCore]
    [AddCommGroup NormalCore] [Module Real NormalCore]
    (data : CanonicalPhysicalScalarCauchyJetRieszBoundaryData
      period hPeriod massSquared ValueCore NormalCore) :
    CanonicalScalarBoundedSmoothCauchyExtensionData
      (ValueCore := ValueCore) (NormalCore := NormalCore)
      (data.geometric.greenCore period hPeriod).core where
  smooth := data.smoothExtension period hPeriod
  constant := (data.graphEstimate period hPeriod).graphConstant period hPeriod
  nonnegative :=
    (data.graphEstimate period hPeriod).graphConstant_nonnegative period hPeriod
  graph_bound := (data.graphEstimate period hPeriod).graph_bound period hPeriod

/-- Density of the physical zero-Cauchy minimal core. -/
theorem minimalCoreDense
    {ValueCore : Type x} {NormalCore : Type y}
    [AddCommGroup ValueCore] [Module Real ValueCore]
    [AddCommGroup NormalCore] [Module Real NormalCore]
    (data : CanonicalPhysicalScalarCauchyJetRieszBoundaryData
      period hPeriod massSquared ValueCore NormalCore) :
    (data.geometric.greenCore period hPeriod).MinimalCoreDense period hPeriod :=
  canonicalPhysicalScalarMinimalCoreDense
    period hPeriod (data.geometric.greenCore period hPeriod)

/-- Injectivity of the completed maximal graph inclusion. -/
theorem graphInclusion_injective
    {ValueCore : Type x} {NormalCore : Type y}
    [AddCommGroup ValueCore] [Module Real ValueCore]
    [AddCommGroup NormalCore] [Module Real NormalCore]
    (data : CanonicalPhysicalScalarCauchyJetRieszBoundaryData
      period hPeriod massSquared ValueCore NormalCore) :
    Function.Injective
      (canonicalScalarGreenCoreGraphInclusion
        (data.geometric.greenCore period hPeriod).core) :=
  canonicalPhysicalScalarGraphInclusion_injective
    period hPeriod (data.geometric.greenCore period hPeriod)

/-- Riesz-generated physical graph trace bound. -/
def traceBound
    {ValueCore : Type x} {NormalCore : Type y}
    [AddCommGroup ValueCore] [Module Real ValueCore]
    [AddCommGroup NormalCore] [Module Real NormalCore]
    (data : CanonicalPhysicalScalarCauchyJetRieszBoundaryData
      period hPeriod massSquared ValueCore NormalCore) :=
  (data.boundedSmoothExtension period hPeriod).rieszBoundaryGraphBound

/-- Riesz-generated completed physical Cauchy trace. -/
def completedBoundaryTrace
    {ValueCore : Type x} {NormalCore : Type y}
    [AddCommGroup ValueCore] [Module Real ValueCore]
    [AddCommGroup NormalCore] [Module Real NormalCore]
    (data : CanonicalPhysicalScalarCauchyJetRieszBoundaryData
      period hPeriod massSquared ValueCore NormalCore) :=
  (data.boundedSmoothExtension period hPeriod).rieszBoundaryTrace

/-- Correct completed physical boundary triple without normal regularity input. -/
def triple
    {ValueCore : Type x} {NormalCore : Type y}
    [AddCommGroup ValueCore] [Module Real ValueCore]
    [AddCommGroup NormalCore] [Module Real NormalCore]
    (data : CanonicalPhysicalScalarCauchyJetRieszBoundaryData
      period hPeriod massSquared ValueCore NormalCore) :
    CanonicalScalarCompletedBoundaryTripleData
      (data.geometric.greenCore period hPeriod).core
      (data.traceBound period hPeriod) :=
  (data.boundedSmoothExtension period hPeriod).toRieszBoundaryTriple
    (data.graphInclusion_injective period hPeriod)

/-- Completed explicit Cauchy extension. -/
def completedExtension
    {ValueCore : Type x} {NormalCore : Type y}
    [AddCommGroup ValueCore] [Module Real ValueCore]
    [AddCommGroup NormalCore] [Module Real NormalCore]
    (data : CanonicalPhysicalScalarCauchyJetRieszBoundaryData
      period hPeriod massSquared ValueCore NormalCore) :=
  (data.boundedSmoothExtension period hPeriod).completedExtension

/-- The completed extension is a right inverse of the Riesz trace. -/
theorem completedBoundaryTrace_extension
    {ValueCore : Type x} {NormalCore : Type y}
    [AddCommGroup ValueCore] [Module Real ValueCore]
    [AddCommGroup NormalCore] [Module Real NormalCore]
    (data : CanonicalPhysicalScalarCauchyJetRieszBoundaryData
      period hPeriod massSquared ValueCore NormalCore)
    (boundary :
      P0EFTJanusMappingTorusScalarHilbertBoundarySymplectic4D.CanonicalScalarHilbertBoundaryDatum
        (Trace := CanonicalPhysicalScalarFirstSheetL2 period)) :
    data.completedBoundaryTrace period hPeriod
        (data.completedExtension period hPeriod boundary) = boundary :=
  (data.boundedSmoothExtension period hPeriod).rieszBoundaryTrace_extension boundary

/-- Riesz physical boundary-triple certificate. -/
theorem certificate
    {ValueCore : Type x} {NormalCore : Type y}
    [AddCommGroup ValueCore] [Module Real ValueCore]
    [AddCommGroup NormalCore] [Module Real NormalCore]
    (data : CanonicalPhysicalScalarCauchyJetRieszBoundaryData
      period hPeriod massSquared ValueCore NormalCore) :
    (data.geometric.greenCore period hPeriod).MinimalCoreDense period hPeriod ∧
      Function.Injective
        (canonicalScalarGreenCoreGraphInclusion
          (data.geometric.greenCore period hPeriod).core) ∧
      Function.Surjective (data.completedBoundaryTrace period hPeriod) ∧
      (∀ boundary,
        data.completedBoundaryTrace period hPeriod
          (data.completedExtension period hPeriod boundary) = boundary) ∧
      (∀ field : SmoothQuotientField period hPeriod Real,
        data.completedBoundaryTrace period hPeriod
            (canonicalScalarGreenCoreToGraph
              (data.geometric.greenCore period hPeriod).core field) =
          (data.geometric.greenCore period hPeriod).core.boundaryTrace field) :=
  ⟨data.minimalCoreDense period hPeriod,
    data.graphInclusion_injective period hPeriod,
    (data.boundedSmoothExtension period hPeriod).rieszBoundaryTrace_surjective,
    data.completedBoundaryTrace_extension period hPeriod,
    (data.boundedSmoothExtension period hPeriod).rieszBoundaryTrace_smooth⟩

end CanonicalPhysicalScalarCauchyJetRieszBoundaryData

end
end P0EFTJanusMappingTorusCanonicalPhysicalScalarCauchyJetRieszBoundaryTriple4D
end JanusFormal
