import JanusFormal.Branches.FundamentalGeometryPVariationalPrinciple.Gates.P0EFTJanusProgramPFiniteIntertwiningOperatorKernelTransport4D

/-!
# Pairwise operator transport from a basepoint frame

A coherent equivalence for every pair of parameters is stronger than necessary.
It is enough to trivialize the ambient family from one basepoint.  Given linear
equivalences

`F_a : E ≃ E`

with `F_0 = id` and

`H_a F_a = F_a H_0`,

define

`T_ab = F_b ∘ F_a⁻¹`.

The identity, cocycle and operator-intertwining laws of `T_ab` are automatic.
This is the natural form of a family trivialization produced from D11 pullback
isomorphisms based at the H12 point.
-/

namespace JanusFormal
namespace P0EFTJanusProgramPFiniteIntertwiningOperatorFrameTransport4D

set_option autoImplicit false
noncomputable section

open P0EFTJanusProgramPFiniteIntertwiningOperatorKernelTransport4D

variable {E : Type*}
  [NormedAddCommGroup E] [NormedSpace Real E]

/-- Linear trivializing frame of an operator family based at parameter zero. -/
structure FiniteIntertwiningOperatorFrameData
    (operator : Real → E →L[Real] E) where
  frame : ∀ parameter : Real, E ≃ₗ[Real] E
  frame_zero : frame 0 = LinearEquiv.refl Real E
  intertwines_basepoint : ∀ parameter vector,
    operator parameter (frame parameter vector) =
      frame parameter (operator 0 vector)

namespace FiniteIntertwiningOperatorFrameData

/-- Pairwise transport generated by the basepoint frame. -/
def transport
    {operator : Real → E →L[Real] E}
    (data : FiniteIntertwiningOperatorFrameData operator)
    (first second : Real) : E ≃ₗ[Real] E :=
  (data.frame first).symm.trans (data.frame second)

@[simp]
theorem transport_apply
    {operator : Real → E →L[Real] E}
    (data : FiniteIntertwiningOperatorFrameData operator)
    (first second : Real) (vector : E) :
    data.transport first second vector =
      data.frame second ((data.frame first).symm vector) :=
  rfl

/-- The inverse frame intertwines in the reverse direction. -/
theorem frame_symm_intertwines
    {operator : Real → E →L[Real] E}
    (data : FiniteIntertwiningOperatorFrameData operator)
    (parameter : Real) (vector : E) :
    operator 0 ((data.frame parameter).symm vector) =
      (data.frame parameter).symm (operator parameter vector) := by
  apply (data.frame parameter).injective
  rw [(data.frame parameter).apply_symm_apply]
  have hIntertwine := data.intertwines_basepoint parameter
    ((data.frame parameter).symm vector)
  rw [(data.frame parameter).apply_symm_apply] at hIntertwine
  exact hIntertwine.symm

/-- Identity of the pairwise transport. -/
theorem transport_self
    {operator : Real → E →L[Real] E}
    (data : FiniteIntertwiningOperatorFrameData operator)
    (parameter : Real) :
    data.transport parameter parameter = LinearEquiv.refl Real E := by
  ext vector
  simp [transport]

/-- Exact transport cocycle. -/
theorem transport_trans
    {operator : Real → E →L[Real] E}
    (data : FiniteIntertwiningOperatorFrameData operator)
    (first second third : Real) :
    (data.transport first second).trans (data.transport second third) =
      data.transport first third := by
  ext vector
  simp [transport]

/-- Pairwise transport intertwines the corresponding operators. -/
theorem transport_intertwines
    {operator : Real → E →L[Real] E}
    (data : FiniteIntertwiningOperatorFrameData operator)
    (first second : Real) (vector : E) :
    operator second (data.transport first second vector) =
      data.transport first second (operator first vector) := by
  calc
    operator second (data.transport first second vector) =
        data.frame second
          (operator 0 ((data.frame first).symm vector)) := by
      rw [transport_apply]
      exact data.intertwines_basepoint second
        ((data.frame first).symm vector)
    _ = data.frame second
          ((data.frame first).symm (operator first vector)) := by
      rw [data.frame_symm_intertwines first vector]
    _ = data.transport first second (operator first vector) :=
      rfl

/-- Adapter to the generic coherent ambient intertwining packet. -/
def toFiniteIntertwiningOperatorTransport
    {operator : Real → E →L[Real] E}
    (data : FiniteIntertwiningOperatorFrameData operator) :
    FiniteIntertwiningOperatorTransportData operator where
  transport := data.transport
  transport_self := data.transport_self
  transport_trans := data.transport_trans
  intertwines := data.transport_intertwines

/-- At the basepoint the frame-generated transport is the frame itself. -/
theorem transport_zero
    {operator : Real → E →L[Real] E}
    (data : FiniteIntertwiningOperatorFrameData operator)
    (parameter : Real) :
    data.transport 0 parameter = data.frame parameter := by
  ext vector
  simp [transport, data.frame_zero]

/-- Public basepoint-frame transport checkpoint. -/
theorem finite_intertwining_operator_frame_transport_gate
    (operator : Real → E →L[Real] E)
    (data : FiniteIntertwiningOperatorFrameData operator) :
    (∀ first second vector,
      operator second (data.transport first second vector) =
        data.transport first second (operator first vector)) ∧
    (∀ parameter,
      data.transport parameter parameter = LinearEquiv.refl Real E) ∧
    (∀ first second third,
      (data.transport first second).trans (data.transport second third) =
        data.transport first third) ∧
    (∀ parameter,
      data.transport 0 parameter = data.frame parameter) :=
  ⟨data.transport_intertwines,
    data.transport_self,
    data.transport_trans,
    data.transport_zero⟩

end FiniteIntertwiningOperatorFrameData

end
end P0EFTJanusProgramPFiniteIntertwiningOperatorFrameTransport4D
end JanusFormal
