import JanusFormal.Branches.FundamentalGeometryPVariationalPrinciple.Gates.P0EFTJanusProgramPT12GaugeFixedLLFriedrichsPhysicalRelativeLogarithmicFactorization4D
import JanusFormal.Branches.FundamentalGeometryPVariationalPrinciple.Gates.P0EFTJanusProgramPIntrinsicNuclearTraceExpansionUniqueness4D
import JanusFormal.Branches.FundamentalGeometryPVariationalPrinciple.Gates.P0EFTJanusProgramPIntrinsicNuclearTraceIsometricEquivalenceTransport4D
import JanusFormal.Branches.FundamentalGeometryPVariationalPrinciple.Gates.P0EFTJanusProgramPIntrinsicNuclearTraceSmul4D

/-!
# Conditional nuclear relative logarithmic derivative

An explicit nuclear expansion of the positive stabilized-inverse sandwich,
together with ambient presentation independence, gives the intrinsic trace of
the exact physical-minus-reference logarithmic derivative.  The operator sign
is supplied by the preceding algebraic factorization.
-/

namespace JanusFormal
namespace P0EFTJanusProgramPT12GaugeFixedLLFriedrichsPhysicalRelativeLogarithmicNuclear4D

set_option autoImplicit false
noncomputable section

open Set MeasureTheory
open scoped ENNReal lp Manifold ContDiff InnerProductSpace LinearPMap Topology
open P0EFTJanusGaugeGhostBlockD9UnboundedFredholm4D
open P0EFTJanusImmersionFiberAlgebra
open P0EFTJanusMappingTorusQuotient
open P0EFTJanusMappingTorusSmoothAtlasFrontier
open P0EFTJanusMappingTorusSmoothQuotientManifold
open P0EFTJanusProgramPGlobalAnalysisDomain4D
open P0EFTJanusProgramPGlobalCandidateAAbelianGaugeFixedAction4D
open P0EFTJanusProgramPGlobalCandidateACommonAugmentedAnalyticDomain4D
open P0EFTJanusProgramPGlobalCandidateAMatterLLSameActionClosure4D
open P0EFTJanusProgramPGlobalCandidateAMinimalPhysicalLocalHessianBridge4D
open P0EFTJanusProgramPGlobalCovariantAction4D
open P0EFTJanusProgramPGlobalFieldSpace4D
open P0EFTJanusProgramPGlobalGaugeFixedLLFriedrichsHessianFredholm4D
open P0EFTJanusProgramPGlobalGaugeFixedSpectralHessianFredholm4D
open P0EFTJanusProgramPGlobalLocalVariationalChart4D
open P0EFTJanusProgramPGlobalTypedNonminimalFieldSpace4D
open P0EFTJanusProgramPIntrinsicNuclearTrace4D
open P0EFTJanusProgramPIntrinsicNuclearTraceExpansionUniqueness4D
open P0EFTJanusProgramPIntrinsicNuclearTraceIsometricEquivalenceTransport4D
open P0EFTJanusProgramPSummableRankOneOperatorExpansion4D
open P0EFTJanusProgramPT12GaugeFixedLLFriedrichsPhysicalNondegenerateLocus4D
open P0EFTJanusProgramPT12GaugeFixedLLFriedrichsPhysicalRelativeLogarithmicFactorization4D

attribute [local instance]
  programPGlobalGaugeFixedSpectralHessianHilbertRealInnerProductSpace

variable (period : Real) (hPeriod : period ≠ 0)

private abbrev EffectiveQuotient :=
  MappingTorus (reflectedSphereData period hPeriod)

local instance effectiveQuotientChartedSpace :
    ChartedSpace CoverModel (EffectiveQuotient period hPeriod) :=
  reflectedSphereQuotientChartedSpace period hPeriod

local instance effectiveQuotientIsManifold :
    IsManifold coverModelWithCorners ω
      (EffectiveQuotient period hPeriod) :=
  reflectedSphereQuotient_isManifold period hPeriod

local instance effectiveQuotientMeasurableSpace :
    MeasurableSpace (EffectiveQuotient period hPeriod) := borel _

local instance effectiveQuotientBorelSpace :
    BorelSpace (EffectiveQuotient period hPeriod) where
  measurable_eq := rfl

section Physical

variable {couplings : GlobalCandidateAActionCouplings}
variable {NonNullFace NullFace : Type*}
variable [Fintype NonNullFace] [Fintype NullFace]
variable {measure : Measure (EffectiveQuotient period hPeriod)}
variable (configuration : GlobalGaugeFixedFieldConfiguration period hPeriod)
variable (data : GlobalCandidateAActionData period hPeriod
  configuration.physical couplings NonNullFace NullFace)
variable (analysis : GlobalAnalysisData period hPeriod configuration.physical)
variable (chart : GlobalCandidateALocalVariationalChart period hPeriod
  couplings NonNullFace NullFace measure)
variable (sameAction : ProgramPGlobalMinimalPhysicalLocalMatterLLSameActionBridge4D
  period hPeriod configuration data analysis chart)
variable (physical : GlobalCandidateASevenPhysicalCommonDomainExtension4D
  period hPeriod configuration data analysis chart sameAction)

/-- Parameter subtype on which the physical Hessian is invertible. -/
abbrev PhysicalRelativeNondegenerateParameter
    {iota : Type*} [DecidableEq iota]
    (covector : iota → TangentVector3) :=
  programPT12GaugeFixedLLFriedrichsPhysicalNondegenerateSet
    period hPeriod configuration data analysis chart sameAction physical covector

/-- Exact conditional inputs for the intrinsic relative logarithmic trace.
The sandwich expansion can later be generated by the square-summable diagonal
sandwich theorem without changing this interface. -/
structure PhysicalRelativeLogarithmicNuclearInput4D
    {iota : Type*} [DecidableEq iota]
    {covector : iota → TangentVector3}
    (d9Ellipticity : D9GaugeGhostFiniteCharacteristicEllipticity covector) where
  traceUniqueness :
    NuclearRankOneTraceUniquenessData.{_, 0}
      (E := ProgramPGlobalGaugeFixedLLFriedrichsHessianHilbert
        period hPeriod iota analysis)
  sandwichExpansion : ∀ parameter :
      PhysicalRelativeNondegenerateParameter period hPeriod configuration data
        analysis chart sameAction physical covector,
    SummableRankOneOperatorExpansion.{0}
      (programPT12GaugeFixedLLFriedrichsPhysicalRelativeLogarithmicSandwich
        period hPeriod configuration data analysis chart sameAction physical
          d9Ellipticity parameter.1)

namespace PhysicalRelativeLogarithmicNuclearInput4D

/-- Nuclear expansion of the signed physical-minus-reference logarithmic
derivative. -/
def relativeExpansion
    {iota : Type*} [DecidableEq iota]
    {covector : iota → TangentVector3}
    {d9Ellipticity : D9GaugeGhostFiniteCharacteristicEllipticity covector}
    (input : PhysicalRelativeLogarithmicNuclearInput4D
      period hPeriod configuration data analysis chart sameAction physical
        d9Ellipticity)
    (parameter : PhysicalRelativeNondegenerateParameter period hPeriod
      configuration data analysis chart sameAction physical covector) :
    SummableRankOneOperatorExpansion.{0}
      (programPT12GaugeFixedLLFriedrichsFullPhysicalRelativeLogarithmicDerivative
        period hPeriod configuration data analysis chart sameAction physical
          d9Ellipticity parameter.1) :=
  transportExpansionOperator
    ((input.sandwichExpansion parameter).smul (-1))
    (by
      calc
        (-1 : Real) •
            programPT12GaugeFixedLLFriedrichsPhysicalRelativeLogarithmicSandwich
              period hPeriod configuration data analysis chart sameAction
                physical d9Ellipticity parameter.1 =
            -programPT12GaugeFixedLLFriedrichsPhysicalRelativeLogarithmicSandwich
              period hPeriod configuration data analysis chart sameAction
                physical d9Ellipticity parameter.1 := by
                  ext state
                  simp
        _ = programPT12GaugeFixedLLFriedrichsFullPhysicalRelativeLogarithmicDerivative
              period hPeriod configuration data analysis chart sameAction
                physical d9Ellipticity parameter.1 :=
          (programPT12GaugeFixedLLFriedrichsPhysicalRelativeLogarithmic_factorization
            period hPeriod configuration data analysis chart sameAction physical
              d9Ellipticity parameter.1 parameter.2).symm)

/-- Presentation-independent nuclear trace certificate for the exact relative
logarithmic derivative. -/
def relativeTraceClass
    {iota : Type*} [DecidableEq iota]
    {covector : iota → TangentVector3}
    {d9Ellipticity : D9GaugeGhostFiniteCharacteristicEllipticity covector}
    (input : PhysicalRelativeLogarithmicNuclearInput4D
      period hPeriod configuration data analysis chart sameAction physical
        d9Ellipticity)
    (parameter : PhysicalRelativeNondegenerateParameter period hPeriod
      configuration data analysis chart sameAction physical covector) :
    IntrinsicNuclearTraceData.{_, 0}
      (programPT12GaugeFixedLLFriedrichsFullPhysicalRelativeLogarithmicDerivative
        period hPeriod configuration data analysis chart sameAction physical
          d9Ellipticity parameter.1) :=
  input.traceUniqueness.intrinsicTraceData
    (input.relativeExpansion period hPeriod configuration data analysis chart
      sameAction physical parameter)

/-- Canonical physical-minus-reference logarithmic trace. -/
def trace
    {iota : Type*} [DecidableEq iota]
    {covector : iota → TangentVector3}
    {d9Ellipticity : D9GaugeGhostFiniteCharacteristicEllipticity covector}
    (input : PhysicalRelativeLogarithmicNuclearInput4D
      period hPeriod configuration data analysis chart sameAction physical
        d9Ellipticity)
    (parameter : PhysicalRelativeNondegenerateParameter period hPeriod
      configuration data analysis chart sameAction physical covector) : Real :=
  intrinsicNuclearTrace
    (input.relativeTraceClass period hPeriod configuration data analysis chart
      sameAction physical parameter)

/-- Relative Bismut--Freed coefficient in the zeta-prime convention. -/
def bismutFreedCoefficient
    {iota : Type*} [DecidableEq iota]
    {covector : iota → TangentVector3}
    {d9Ellipticity : D9GaugeGhostFiniteCharacteristicEllipticity covector}
    (input : PhysicalRelativeLogarithmicNuclearInput4D
      period hPeriod configuration data analysis chart sameAction physical
        d9Ellipticity)
    (parameter : PhysicalRelativeNondegenerateParameter period hPeriod
      configuration data analysis chart sameAction physical covector) : Complex :=
  (-(input.trace period hPeriod configuration data analysis chart sameAction
    physical parameter) : Real)

/-- Every certified expansion computes the canonical relative trace. -/
theorem expansionTrace_eq
    {iota : Type*} [DecidableEq iota]
    {covector : iota → TangentVector3}
    {d9Ellipticity : D9GaugeGhostFiniteCharacteristicEllipticity covector}
    (input : PhysicalRelativeLogarithmicNuclearInput4D
      period hPeriod configuration data analysis chart sameAction physical
        d9Ellipticity)
    (parameter : PhysicalRelativeNondegenerateParameter period hPeriod
      configuration data analysis chart sameAction physical covector)
    (expansion : SummableRankOneOperatorExpansion.{0}
      (programPT12GaugeFixedLLFriedrichsFullPhysicalRelativeLogarithmicDerivative
        period hPeriod configuration data analysis chart sameAction physical
          d9Ellipticity parameter.1)) :
    expansion.expansionTrace =
      input.trace period hPeriod configuration data analysis chart sameAction
        physical parameter :=
  (input.relativeTraceClass period hPeriod configuration data analysis chart
    sameAction physical parameter).expansionTrace_eq expansion

/-- The exact relative logarithmic derivative is compact. -/
theorem relativeLogarithmicDerivative_compact
    {iota : Type*} [DecidableEq iota]
    {covector : iota → TangentVector3}
    {d9Ellipticity : D9GaugeGhostFiniteCharacteristicEllipticity covector}
    (input : PhysicalRelativeLogarithmicNuclearInput4D
      period hPeriod configuration data analysis chart sameAction physical
        d9Ellipticity)
    (parameter : PhysicalRelativeNondegenerateParameter period hPeriod
      configuration data analysis chart sameAction physical covector) :
    IsCompactOperator
      (programPT12GaugeFixedLLFriedrichsFullPhysicalRelativeLogarithmicDerivative
        period hPeriod configuration data analysis chart sameAction physical
          d9Ellipticity parameter.1) :=
  (input.relativeTraceClass period hPeriod configuration data analysis chart
    sameAction physical parameter).operator_compact

@[simp]
theorem bismutFreedCoefficient_re
    {iota : Type*} [DecidableEq iota]
    {covector : iota → TangentVector3}
    {d9Ellipticity : D9GaugeGhostFiniteCharacteristicEllipticity covector}
    (input : PhysicalRelativeLogarithmicNuclearInput4D
      period hPeriod configuration data analysis chart sameAction physical
        d9Ellipticity)
    (parameter : PhysicalRelativeNondegenerateParameter period hPeriod
      configuration data analysis chart sameAction physical covector) :
    (input.bismutFreedCoefficient period hPeriod configuration data analysis
      chart sameAction physical parameter).re =
      -input.trace period hPeriod configuration data analysis chart sameAction
        physical parameter := by
  rfl

/-- Public conditional physical relative-logarithmic nuclear checkpoint. -/
theorem gate
    {iota : Type*} [DecidableEq iota]
    {covector : iota → TangentVector3}
    {d9Ellipticity : D9GaugeGhostFiniteCharacteristicEllipticity covector}
    (input : PhysicalRelativeLogarithmicNuclearInput4D
      period hPeriod configuration data analysis chart sameAction physical
        d9Ellipticity) :
    (∀ parameter : PhysicalRelativeNondegenerateParameter period hPeriod
      configuration data analysis chart sameAction physical covector,
      IsCompactOperator
        (programPT12GaugeFixedLLFriedrichsFullPhysicalRelativeLogarithmicDerivative
          period hPeriod configuration data analysis chart sameAction physical
            d9Ellipticity parameter.1)) ∧
    (∀ parameter : PhysicalRelativeNondegenerateParameter period hPeriod
        configuration data analysis chart sameAction physical covector,
      ∀ expansion : SummableRankOneOperatorExpansion.{0}
        (programPT12GaugeFixedLLFriedrichsFullPhysicalRelativeLogarithmicDerivative
          period hPeriod configuration data analysis chart sameAction physical
            d9Ellipticity parameter.1),
        expansion.expansionTrace =
          input.trace period hPeriod configuration data analysis chart
            sameAction physical parameter) ∧
    (∀ parameter : PhysicalRelativeNondegenerateParameter period hPeriod
        configuration data analysis chart sameAction physical covector,
      (input.bismutFreedCoefficient period hPeriod configuration data analysis
        chart sameAction physical parameter).re =
          -input.trace period hPeriod configuration data analysis chart
            sameAction physical parameter) :=
  ⟨input.relativeLogarithmicDerivative_compact period hPeriod configuration
      data analysis chart sameAction physical,
    input.expansionTrace_eq period hPeriod configuration data analysis chart
      sameAction physical,
    input.bismutFreedCoefficient_re period hPeriod configuration data analysis
      chart sameAction physical⟩

end PhysicalRelativeLogarithmicNuclearInput4D
end Physical
end
end P0EFTJanusProgramPT12GaugeFixedLLFriedrichsPhysicalRelativeLogarithmicNuclear4D
end JanusFormal
