import JanusFormal.Branches.FundamentalGeometryPVariationalPrinciple.Gates.P0EFTJanusMappingTorusCanonicalPhysicalScalarFirstSheetGreenCore4D
import JanusFormal.Branches.FundamentalGeometryPVariationalPrinciple.Gates.P0EFTJanusMappingTorusScalarBoundarySmoothExtensionDensity4D

/-!
# Physical first-sheet scalar Cauchy extension criteria

The corrected physical Green core needs two extension theorems at different
regularities.

At the smooth level, dense smooth value and normal cores together with a smooth
bulk jet extension imply density of the smooth Cauchy trace.

At the graph-completed level, a bounded right inverse of the completed trace
implies surjectivity and installs the completed physical boundary triple.  This
file packages those reductions for the concrete first-sheet scalar traces.
-/

namespace JanusFormal
namespace P0EFTJanusMappingTorusCanonicalPhysicalScalarFirstSheetBoundaryExtension4D

set_option autoImplicit false
noncomputable section

open Set Topology
open P0EFTJanusMappingTorusSmoothFieldDescent4D
open P0EFTJanusMappingTorusCanonicalPhysicalBulkL2H1Bridge4D
open P0EFTJanusMappingTorusCanonicalPhysicalScalarEulerAtlas4D
open P0EFTJanusMappingTorusCanonicalPhysicalScalarFirstSheetHilbertTrace4D
open P0EFTJanusMappingTorusCanonicalPhysicalScalarFirstSheetGreenCore4D
open P0EFTJanusMappingTorusScalarHilbertBoundarySymplectic4D
open P0EFTJanusMappingTorusScalarHilbertGreenCoreCompletion4D
open P0EFTJanusMappingTorusScalarHilbertGreenCoreMinimalClosable4D
open P0EFTJanusMappingTorusScalarBoundarySmoothExtensionDensity4D

universe x y

variable (period : Real) (hPeriod : period ≠ 0)

private abbrev SmoothDomain := SmoothQuotientField period hPeriod Real
private abbrev BoundaryL2 := CanonicalPhysicalScalarFirstSheetL2 period

/-- Smooth physical Cauchy extension data. -/
structure CanonicalPhysicalScalarSmoothCauchyExtensionData
    (massSquared : Real)
    (ValueCore : Type x) (NormalCore : Type y)
    [AddCommGroup ValueCore] [Module Real ValueCore]
    [AddCommGroup NormalCore] [Module Real NormalCore] where
  operatorData : CanonicalPhysicalScalarEulerGlobalOperatorData
    period hPeriod massSquared
  valueEmbedding : ValueCore →ₗ[Real] BoundaryL2 period
  normalEmbedding : NormalCore →ₗ[Real] BoundaryL2 period
  valueDense : DenseRange valueEmbedding
  normalDense : DenseRange normalEmbedding
  extension : ValueCore × NormalCore →ₗ[Real] SmoothDomain period hPeriod
  boundary_extension : ∀ data,
    smoothCanonicalPhysicalScalarFirstSheetCauchyTrace
        period hPeriod (extension data) =
      canonicalScalarBoundaryCorePairEmbedding
        valueEmbedding normalEmbedding data
  bulk_green_stokes : ∀ first second : SmoothDomain period hPeriod,
    inner Real (operatorData.toBulkL2LinearMap first)
          (smoothToCanonicalPhysicalBulkL2 period hPeriod second) -
        inner Real (smoothToCanonicalPhysicalBulkL2 period hPeriod first)
          (operatorData.toBulkL2LinearMap second) =
      P0EFTJanusMappingTorusCutBulkGlobalOrientedBoundaryCurrent4D.cutBulkGlobalOrientedScalarCurrentIntegral
        period hPeriod first second

namespace CanonicalPhysicalScalarSmoothCauchyExtensionData

/-- Generic smooth extension package underlying the physical data. -/
def toGenericExtension
    {ValueCore : Type x} {NormalCore : Type y}
    [AddCommGroup ValueCore] [Module Real ValueCore]
    [AddCommGroup NormalCore] [Module Real NormalCore]
    (extensionData : CanonicalPhysicalScalarSmoothCauchyExtensionData
      period hPeriod massSquared ValueCore NormalCore) :
    CanonicalScalarSmoothCauchyExtensionData
      (ValueCore := ValueCore) (NormalCore := NormalCore)
      (smoothCanonicalPhysicalScalarFirstSheetCauchyTrace period hPeriod) where
  valueEmbedding := extensionData.valueEmbedding
  normalEmbedding := extensionData.normalEmbedding
  valueDense := extensionData.valueDense
  normalDense := extensionData.normalDense
  extension := extensionData.extension
  boundary_extension := extensionData.boundary_extension

/-- Smooth physical Cauchy trace has dense range. -/
theorem boundaryTrace_denseRange
    {ValueCore : Type x} {NormalCore : Type y}
    [AddCommGroup ValueCore] [Module Real ValueCore]
    [AddCommGroup NormalCore] [Module Real NormalCore]
    (extensionData : CanonicalPhysicalScalarSmoothCauchyExtensionData
      period hPeriod massSquared ValueCore NormalCore) :
    DenseRange
      (smoothCanonicalPhysicalScalarFirstSheetCauchyTrace period hPeriod) :=
  extensionData.toGenericExtension.boundaryTrace_denseRange

/-- Correct physical Green core generated by the smooth extension theorem. -/
def greenCoreData
    {ValueCore : Type x} {NormalCore : Type y}
    [AddCommGroup ValueCore] [Module Real ValueCore]
    [AddCommGroup NormalCore] [Module Real NormalCore]
    (extensionData : CanonicalPhysicalScalarSmoothCauchyExtensionData
      period hPeriod massSquared ValueCore NormalCore) :
    CanonicalPhysicalScalarFirstSheetGreenCoreData
      period hPeriod massSquared where
  operatorData := extensionData.operatorData
  boundary_dense := extensionData.boundaryTrace_denseRange
  bulk_green_stokes := extensionData.bulk_green_stokes

/-- Physical smooth-extension certificate. -/
theorem certificate
    {ValueCore : Type x} {NormalCore : Type y}
    [AddCommGroup ValueCore] [Module Real ValueCore]
    [AddCommGroup NormalCore] [Module Real NormalCore]
    (extensionData : CanonicalPhysicalScalarSmoothCauchyExtensionData
      period hPeriod massSquared ValueCore NormalCore) :
    DenseRange
        (smoothCanonicalPhysicalScalarFirstSheetCauchyTrace period hPeriod) ∧
      (∀ data,
        smoothCanonicalPhysicalScalarFirstSheetCauchyTrace
            period hPeriod (extensionData.extension data) =
          canonicalScalarBoundaryCorePairEmbedding
            extensionData.valueEmbedding extensionData.normalEmbedding data) :=
  ⟨extensionData.boundaryTrace_denseRange,
    extensionData.boundary_extension⟩

end CanonicalPhysicalScalarSmoothCauchyExtensionData

/-- Completed physical Cauchy extension for a fixed graph-bound package. -/
structure CanonicalPhysicalScalarCompletedCauchyExtensionData
    (green : CanonicalPhysicalScalarFirstSheetGreenCoreData
      period hPeriod massSquared)
    (traceBound : HasCanonicalScalarHilbertGreenCoreBoundaryGraphBound
      green.core) where
  extension : CanonicalScalarHilbertBoundaryDatum
      (Trace := BoundaryL2 period) →L[Real]
    CanonicalScalarGreenCoreGraphSpace green.core
  boundary_extension : ∀ boundary,
    canonicalScalarGreenCoreCompletedBoundaryTrace green.core traceBound
        (extension boundary) = boundary

namespace CanonicalPhysicalScalarCompletedCauchyExtensionData

/-- Generic completed extension package. -/
def toGeneric
    (green : CanonicalPhysicalScalarFirstSheetGreenCoreData
      period hPeriod massSquared)
    {traceBound : HasCanonicalScalarHilbertGreenCoreBoundaryGraphBound
      green.core}
    (extensionData : CanonicalPhysicalScalarCompletedCauchyExtensionData
      period hPeriod green traceBound) :
    CanonicalScalarCompletedCauchyExtensionData green.core traceBound where
  extension := extensionData.extension
  boundary_extension := extensionData.boundary_extension

/-- Completed physical trace is surjective. -/
theorem boundaryTrace_surjective
    (green : CanonicalPhysicalScalarFirstSheetGreenCoreData
      period hPeriod massSquared)
    {traceBound : HasCanonicalScalarHilbertGreenCoreBoundaryGraphBound
      green.core}
    (extensionData : CanonicalPhysicalScalarCompletedCauchyExtensionData
      period hPeriod green traceBound) :
    Function.Surjective
      (canonicalScalarGreenCoreCompletedBoundaryTrace
        green.core traceBound) :=
  (extensionData.toGeneric green).boundaryTrace_surjective

/-- Install the complete physical boundary-triple inputs from the two extension
results and the graph estimates. -/
def completedBoundaryTripleInputs
    (green : CanonicalPhysicalScalarFirstSheetGreenCoreData
      period hPeriod massSquared)
    (coarea : CanonicalPhysicalScalarLatitudeCoareaTheorem period hPeriod)
    (elliptic : green.GraphEllipticEstimate period hPeriod)
    (normal : green.NormalGraphEstimate period hPeriod)
    (minimalDense : green.MinimalCoreDense period hPeriod)
    (extensionData : CanonicalPhysicalScalarCompletedCauchyExtensionData
      period hPeriod green
      (green.boundaryGraphBound period hPeriod coarea elliptic normal)) :
    green.CompletedBoundaryTripleInputs period hPeriod where
  coarea := coarea
  elliptic := elliptic
  normal := normal
  minimalDense := minimalDense
  completedTraceSurjective := extensionData.boundaryTrace_surjective green

/-- Completed physical extension certificate. -/
theorem certificate
    (green : CanonicalPhysicalScalarFirstSheetGreenCoreData
      period hPeriod massSquared)
    {traceBound : HasCanonicalScalarHilbertGreenCoreBoundaryGraphBound
      green.core}
    (extensionData : CanonicalPhysicalScalarCompletedCauchyExtensionData
      period hPeriod green traceBound) :
    Function.Surjective
        (canonicalScalarGreenCoreCompletedBoundaryTrace
          green.core traceBound) ∧
      (∀ boundary,
        canonicalScalarGreenCoreCompletedBoundaryTrace green.core traceBound
            (extensionData.extension boundary) = boundary) :=
  ⟨extensionData.boundaryTrace_surjective green,
    extensionData.boundary_extension⟩

end CanonicalPhysicalScalarCompletedCauchyExtensionData

end
end P0EFTJanusMappingTorusCanonicalPhysicalScalarFirstSheetBoundaryExtension4D
end JanusFormal
