import JanusFormal.Branches.FundamentalGeometryPVariationalPrinciple.Gates.P0EFTJanusProgramPGlobalCandidateANormalBoundaryEventuallyEqGerms4D
import JanusFormal.Branches.FundamentalGeometryPVariationalPrinciple.Gates.P0EFTJanusProgramPGlobalCandidateANormalBoundaryRobinC2Transfer4D

/-!
# Robin transfer directly from the terminal H10 action germ

Once the componentwise H10 gate has produced `SameRealActionGermAt`, the Robin
transfer packet is canonical.  Its domain, openness and action equality are
already contained in the germ; only the `C²` theorem for the completed action
is needed.
-/

namespace JanusFormal
namespace P0EFTJanusProgramPGlobalCandidateANormalBoundaryRobinFromGerm4D

set_option autoImplicit false
set_option maxHeartbeats 1000000
set_option synthInstance.maxHeartbeats 500000

noncomputable section

open Filter Set Topology
open scoped Topology

universe u

variable {Variation : Type u}
  [NormedAddCommGroup Variation]
  [NormedSpace Real Variation]

open P0EFTJanusProgramPGlobalCandidateANormalBoundaryActionGermCalculus4D
open P0EFTJanusProgramPGlobalCandidateANormalBoundaryRobinC2Transfer4D

/-- Canonical Robin transfer packet generated by a same-action germ. -/
def NormalBoundaryRobinC2TransferData.ofSameActionGerm
    {completed historical : Variation → Real}
    {base : Variation}
    (germ : SameRealActionGermAt completed historical base)
    (hCompleted : ContDiffOn Real 2 completed germ.domain) :
    NormalBoundaryRobinC2TransferData completed historical where
  domain := germ.domain
  isOpen_domain := germ.isOpen_domain
  completed_contDiffWithin_two := hCompleted
  sameAction := germ.eqOn_domain

/-- The resulting historical Robin action is `C²` and has the same Hessian at
the anchor. -/
theorem sameActionGerm_robin_c2_and_hessian
    {completed historical : Variation → Real}
    {base : Variation}
    (germ : SameRealActionGermAt completed historical base)
    (hCompleted : ContDiffOn Real 2 completed germ.domain) :
    ContDiffOn Real 2 historical germ.domain ∧
      fderiv Real (fun state => fderiv Real completed state) base =
        fderiv Real (fun state => fderiv Real historical state) base := by
  let transfer := NormalBoundaryRobinC2TransferData.ofSameActionGerm germ
    hCompleted
  exact ⟨transfer.historical_contDiffWithin_two,
    transfer.second_fderiv_eq germ.base_mem_domain⟩

/-- Public H10-to-family Robin gate. -/
def candidate_a_normal_boundary_robin_from_germ_gate
    {completed historical : Variation → Real}
    {base : Variation}
    (germ : SameRealActionGermAt completed historical base)
    (hCompleted : ContDiffOn Real 2 completed germ.domain) :
    NormalBoundaryRobinC2TransferData completed historical :=
  NormalBoundaryRobinC2TransferData.ofSameActionGerm germ hCompleted

end
end P0EFTJanusProgramPGlobalCandidateANormalBoundaryRobinFromGerm4D
end JanusFormal
