import JanusFormal.Branches.FundamentalGeometryDiracSpectral.Gates.P0EFTJanusRenormalizedSpectralDeterminant
import JanusFormal.Branches.FundamentalGeometryD7SpectralTheory.Gates.P0EFTJanusProductThroatDiracHeatCoefficients

namespace JanusFormal
namespace P0EFTJanusD2HeatCountertermBridge

set_option autoImplicit false

open P0EFTJanusGlobalSeparatedDiracModel
open P0EFTJanusRenormalizedSpectralDeterminant
open P0EFTJanusProductThroatLocalInvariants
open P0EFTJanusProductThroatDiracHeatCoefficients
open P0EFTJanusUniversalClosedHeatCoefficients

noncomputable section

/-- Three local coefficients controlling the product-throat cutoff subtraction. -/
structure HeatCountertermCoefficients where
  cubic : ℝ
  linear : ℝ
  inverse : ℝ

/-- Local subtraction generated by the three-dimensional `a0`, `a2`, `a4` terms. -/
def heatCounterterm (coefficients : HeatCountertermCoefficients) (N : ℕ) : ℝ :=
  coefficients.cubic * (N : ℝ) ^ 3 +
    coefficients.linear * (N : ℝ) +
    coefficients.inverse / ((N : ℝ) + 1)

theorem heat_counterterm_holonomy_independent
    (coefficients : HeatCountertermCoefficients) (N : ℕ)
    (firstHolonomy secondHolonomy : ℝ) :
    (fun _ : ℝ => heatCounterterm coefficients N) firstHolonomy =
      (fun _ : ℝ => heatCounterterm coefficients N) secondHolonomy := rfl

/-- Product-throat local coefficients specialized directly from `a0`, `a2`, `a4`. -/
noncomputable def productThroatHeatCounterterms
    (data : ProductThroatInvariantData) : HeatCountertermCoefficients where
  cubic := reducedA0
    (rankTwoDiracAsLaplaceData (productThroatDiracTraceData data))
  linear := reducedA2
    (rankTwoDiracAsLaplaceData (productThroatDiracTraceData data))
  inverse := reducedA4
    (rankTwoDiracAsLaplaceData (productThroatDiracTraceData data))

theorem product_throat_heat_counterterm_coefficients
    (data : ProductThroatInvariantData) :
    (productThroatHeatCounterterms data).cubic =
        8 * data.piConstant * data.geometricLength ^ 3 * data.circleModulus ∧
    (productThroatHeatCounterterms data).linear =
        -(4 * data.piConstant * data.geometricLength * data.circleModulus) / 3 ∧
    (productThroatHeatCounterterms data).inverse =
        2 * data.piConstant *
          (5 * (data.monopoleNumber : ℝ) ^ 2 - 1) * data.circleModulus /
          (15 * data.geometricLength) := by
  exact ⟨universal_product_throat_a0_formula data,
    universal_product_throat_a2_formula data,
    universal_product_throat_a4_formula data⟩

/-- D7 analytic remainder statement needed to close the D2 determinant family. -/
structure HeatRenormalizedHolonomyFamily (data : ProductThroatSpectralData) where
  coefficients : HeatCountertermCoefficients
  renormalizedLog : ℝ → ℝ
  remainderConverges : ∀ holonomy : ℝ,
    Filter.Tendsto
      (fun N => finiteCutoffLogDeterminant data N holonomy -
        heatCounterterm coefficients N)
      Filter.atTop (nhds (renormalizedLog holonomy))

def HeatRenormalizedHolonomyFamily.toD2Family
    {data : ProductThroatSpectralData}
    (family : HeatRenormalizedHolonomyFamily data) :
    RenormalizedDeterminantFamily data where
  localCounterterm := heatCounterterm family.coefficients
  renormalizedLog := family.renormalizedLog
  cutoffConverges := family.remainderConverges

theorem heat_family_closes_d2_determinant
    (data : ProductThroatSpectralData)
    (family : HeatRenormalizedHolonomyFamily data) :
    RenormalizedDeterminantClosureCertificate data :=
  renormalized_determinant_closure_of_existence data ⟨family.toD2Family⟩

/-- Fixed heat coefficients determine a unique renormalized determinant family. -/
theorem fixed_heat_coefficients_give_unique_determinant
    {data : ProductThroatSpectralData}
    (first second : HeatRenormalizedHolonomyFamily data)
    (hCoefficients : first.coefficients = second.coefficients) :
    first.toD2Family.determinant = second.toD2Family.determinant := by
  apply renormalized_determinant_unique
  simp [HeatRenormalizedHolonomyFamily.toD2Family, hCoefficients]

/-- Remaining D7 theorem is precisely convergence of the locally subtracted remainder. -/
def HeatCountertermClosureExists (data : ProductThroatSpectralData) : Prop :=
  Nonempty (HeatRenormalizedHolonomyFamily data)

theorem heat_counterterm_closure_implies_d2_determinant
    (data : ProductThroatSpectralData)
    (hClosure : HeatCountertermClosureExists data) :
    RenormalizedDeterminantExists data := by
  rcases hClosure with ⟨family⟩
  exact ⟨family.toD2Family⟩

end

end P0EFTJanusD2HeatCountertermBridge
end JanusFormal
